package com.opensocket.aievent.core.integration.issue.projection;

public enum IssueProjectionReasonCode {
    ISSUE_RELAY_NOT_FOUND,
    ISSUE_RELAY_NOT_READY,
    ISSUE_RELAY_NATIVE_RELATION_UNAVAILABLE,
    ISSUE_RELAY_PARTIAL_SUCCESS,
    ISSUE_RELAY_PROVIDER_FAILURE,
    ISSUE_RELAY_IDEMPOTENCY_CONFLICT,
    ISSUE_RELAY_CANONICAL_MATERIALIZATION_FAILED,
    ISSUE_PROJECTION_CONFLICT,
    ISSUE_PROJECTION_RETRY_EXHAUSTED,
    ISSUE_PROJECTION_DISABLED,
    ISSUE_PROJECTION_MAPPING_REQUIRED,
    ISSUE_PROJECTION_OBSERVED_DRIFT,
    ISSUE_PROJECTION_RECONCILIATION_REQUIRED
}
