package com.opensocket.aievent.core.integration.issue.projection;
public enum IssueRelayState { PENDING_SOURCE_CONTEXT, SOURCE_CONTEXT_READY, TARGET_ISSUE_PENDING, TARGET_ISSUE_CREATED, BACKLINK_PENDING, LINKED, PARTIALLY_LINKED, FAILED_RETRYABLE, FAILED_PERMANENT }
