package com.opensocket.aievent.database.persistence.issuerecovery.dao;
import java.time.OffsetDateTime;import java.util.*;import org.apache.ibatis.annotations.*;import com.opensocket.aievent.database.persistence.issuerecovery.*;
@Mapper public interface ProjectionRecoveryDao {
 void upsertLane(@Param("value")ProjectionLanePo value); int updateLaneExpectedVersion(@Param("value")ProjectionLanePo value,@Param("expectedVersion")long expectedVersion); ProjectionLanePo findLane(@Param("tenantId")String tenantId,@Param("laneId")String laneId); ProjectionLanePo findLaneByAggregate(@Param("tenantId")String tenantId,@Param("aggregateKey")String aggregateKey,@Param("laneType")String laneType); List<ProjectionLanePo> listLanes(@Param("tenantId")String tenantId,@Param("status")String status,@Param("limit")int limit);
 void upsertWork(@Param("value")ProjectionWorkPo value); int updateWorkExpectedVersion(@Param("value")ProjectionWorkPo value,@Param("expectedVersion")long expectedVersion); ProjectionWorkPo findWork(@Param("tenantId")String tenantId,@Param("workId")String workId); List<ProjectionWorkPo> listWork(@Param("tenantId")String tenantId,@Param("laneId")String laneId,@Param("status")String status,@Param("limit")int limit); List<ProjectionWorkPo> claimDueWork(@Param("tenantId")String tenantId,@Param("dueAt")OffsetDateTime dueAt,@Param("limit")int limit); List<ProjectionWorkPo> listExpiredClaims(@Param("tenantId")String tenantId,@Param("dueAt")OffsetDateTime dueAt,@Param("limit")int limit); List<ProjectionWorkPo> findCoalescible(@Param("tenantId")String tenantId,@Param("laneId")String laneId,@Param("coalesceKey")String coalesceKey,@Param("generation")long generation,@Param("limit")int limit);
 void upsertCase(@Param("value")ProjectionRecoveryCasePo value); int updateCaseExpectedVersion(@Param("value")ProjectionRecoveryCasePo value,@Param("expectedVersion")long expectedVersion); ProjectionRecoveryCasePo findCase(@Param("tenantId")String tenantId,@Param("caseId")String caseId); ProjectionRecoveryCasePo findOpenCase(@Param("tenantId")String tenantId,@Param("workId")String workId,@Param("caseType")String caseType); List<ProjectionRecoveryCasePo> listCases(@Param("tenantId")String tenantId,@Param("status")String status,@Param("limit")int limit);
 void upsertRun(@Param("value")ProjectionReconciliationRunPo value); int updateRunExpectedVersion(@Param("value")ProjectionReconciliationRunPo value,@Param("expectedVersion")long expectedVersion); ProjectionReconciliationRunPo findRun(@Param("tenantId")String tenantId,@Param("runId")String runId); List<ProjectionReconciliationRunPo> listRuns(@Param("tenantId")String tenantId,@Param("status")String status,@Param("limit")int limit);
 void upsertHealth(@Param("value")ProviderHealthStatePo value); int updateHealthExpectedVersion(@Param("value")ProviderHealthStatePo value,@Param("expectedVersion")long expectedVersion); ProviderHealthStatePo findHealth(@Param("tenantId")String tenantId,@Param("connectionId")String connectionId,@Param("projectMappingId")String projectMappingId); List<ProviderHealthStatePo> listHealth(@Param("tenantId")String tenantId,@Param("status")String status,@Param("limit")int limit);
 void insertEvent(@Param("value")ProjectionRecoveryEventPo value); ProjectionRecoveryEventPo latestEvent(@Param("tenantId")String tenantId,@Param("aggregateType")String aggregateType,@Param("aggregateId")String aggregateId); List<ProjectionRecoveryEventPo> listEvents(@Param("tenantId")String tenantId,@Param("aggregateType")String aggregateType,@Param("aggregateId")String aggregateId,@Param("limit")int limit);
}
