package com.opensocket.aievent.database.persistence.issueprojection;

import com.opensocket.aievent.core.integration.issue.projection.*;
import com.opensocket.aievent.database.persistence.issueprojection.po.*;
import com.opensocket.aievent.database.persistence.spi.DatabasePersistenceConverter;

@DatabasePersistenceConverter
public class IssueProjectionPersistenceConverter {
    public CrossProjectIssueRelayPo toPo(CrossProjectIssueRelay v){var p=new CrossProjectIssueRelayPo();p.setTenantId(v.tenantId());p.setRelayId(v.relayId());p.setA2aRequestId(v.a2aRequestId());p.setRootTaskId(v.rootTaskId());p.setSourceTaskId(v.sourceTaskId());p.setTargetTaskId(v.targetTaskId());p.setSourceMappingId(v.sourceMappingId());p.setTargetMappingId(v.targetMappingId());p.setSourceSnapshotId(v.sourceSnapshotId());p.setResultSnapshotId(v.resultSnapshotId());p.setSourceIssueLinkId(v.sourceIssueLinkId());p.setTargetIssueLinkId(v.targetIssueLinkId());p.setStrategy(v.strategy().name());p.setRelayState(v.relayState().name());p.setNativeRelationSupported(v.nativeRelationSupported());p.setSourceBacklinkStatus(v.sourceBacklinkStatus());p.setTargetBacklinkStatus(v.targetBacklinkStatus());p.setRetryCount(v.retryCount());p.setNextRetryAt(v.nextRetryAt());p.setLastErrorCode(v.lastErrorCode());p.setLastErrorMessage(v.lastErrorMessage());p.setIdempotencyKey(v.idempotencyKey());p.setCorrelationId(v.correlationId());p.setVersion(v.version());p.setCreatedAt(v.createdAt());p.setUpdatedAt(v.updatedAt());return p;}
    public CrossProjectIssueRelay relay(CrossProjectIssueRelayPo p){return new CrossProjectIssueRelay(p.getTenantId(),p.getRelayId(),p.getA2aRequestId(),p.getRootTaskId(),p.getSourceTaskId(),p.getTargetTaskId(),p.getSourceMappingId(),p.getTargetMappingId(),p.getSourceSnapshotId(),p.getResultSnapshotId(),p.getSourceIssueLinkId(),p.getTargetIssueLinkId(),IssueRelayStrategy.valueOf(p.getStrategy()),IssueRelayState.valueOf(p.getRelayState()),p.getNativeRelationSupported(),p.getSourceBacklinkStatus(),p.getTargetBacklinkStatus(),p.getRetryCount(),p.getNextRetryAt(),p.getLastErrorCode(),p.getLastErrorMessage(),p.getIdempotencyKey(),p.getCorrelationId(),p.getVersion(),p.getCreatedAt(),p.getUpdatedAt());}
    public IssueRelayAttemptPo toPo(IssueRelayAttempt v){var p=new IssueRelayAttemptPo();p.setTenantId(v.tenantId());p.setAttemptId(v.attemptId());p.setRelayId(v.relayId());p.setOperationCode(v.operationCode());p.setOperationSide(v.operationSide());p.setProviderType(v.providerType());p.setProjectMappingId(v.projectMappingId());p.setPrincipalId(v.principalId());p.setAttemptNo(v.attemptNo());p.setStatus(v.status().name());p.setProviderStatus(v.providerStatus());p.setExternalIssueId(v.externalIssueId());p.setExternalIssueUrl(v.externalIssueUrl());p.setResponseSummary(v.responseSummary());p.setErrorCode(v.errorCode());p.setRetryable(v.retryable());p.setStartedAt(v.startedAt());p.setCompletedAt(v.completedAt());p.setCorrelationId(v.correlationId());return p;}
    public IssueRelayAttempt attempt(IssueRelayAttemptPo p){return new IssueRelayAttempt(p.getTenantId(),p.getAttemptId(),p.getRelayId(),p.getOperationCode(),p.getOperationSide(),p.getProviderType(),p.getProjectMappingId(),p.getPrincipalId(),p.getAttemptNo(),IssueRelayOperationStatus.valueOf(p.getStatus()),p.getProviderStatus(),p.getExternalIssueId(),p.getExternalIssueUrl(),p.getResponseSummary(),p.getErrorCode(),p.isRetryable(),p.getStartedAt(),p.getCompletedAt(),p.getCorrelationId());}
    public IssueProjectionStatePo toPo(IssueProjectionState v){var p=new IssueProjectionStatePo();p.setTenantId(v.tenantId());p.setProjectionId(v.projectionId());p.setProjectionAggregateKey(v.projectionAggregateKey());p.setProjectionPurpose(v.projectionPurpose().name());p.setSourceEventId(v.sourceEventId());p.setSourceEventType(v.sourceEventType());p.setSourceAggregateType(v.sourceAggregateType());p.setSourceAggregateId(v.sourceAggregateId());p.setTaskId(v.taskId());p.setA2aRequestId(v.a2aRequestId());p.setHandoffSnapshotId(v.handoffSnapshotId());p.setTaskIssueLinkId(v.taskIssueLinkId());p.setConnectionId(v.connectionId());p.setProjectMappingId(v.projectMappingId());p.setProjectMappingVersion(v.projectMappingVersion());p.setProjectMappingSchemaHash(v.projectMappingSchemaHash());p.setCanonicalDocumentSchemaVersion(v.canonicalDocumentSchemaVersion());p.setCanonicalDocumentHash(v.canonicalDocumentHash());p.setDesiredState(v.desiredState().name());p.setObservedState(v.observedState().name());p.setLifecycleStatus(v.lifecycleStatus().name());p.setFailureClassification(v.failureClassification().name());p.setRecoveryStrategy(v.recoveryStrategy().name());p.setConflictPolicy(v.conflictPolicy().name());p.setDesiredPayloadHash(v.desiredPayloadHash());p.setObservedPayloadHash(v.observedPayloadHash());p.setLastAppliedDomainEventId(v.lastAppliedDomainEventId());p.setOperationSequence(v.operationSequence());p.setProjectionVersion(v.projectionVersion());p.setSupersededBy(v.supersededBy());p.setRetryCount(v.retryCount());p.setMaxAttempts(v.maxAttempts());p.setNextRetryAt(v.nextRetryAt());p.setLastErrorCode(v.lastErrorCode());p.setLastErrorMessage(v.lastErrorMessage());p.setVersion(v.version());p.setCreatedAt(v.createdAt());p.setUpdatedAt(v.updatedAt());p.setCompletedAt(v.completedAt());p.setCorrelationId(v.correlationId());return p;}
    public IssueProjectionState state(IssueProjectionStatePo p){return new IssueProjectionState(p.getTenantId(),p.getProjectionId(),p.getProjectionAggregateKey(),com.opensocket.aievent.core.issuetracking.contract.ProjectionPurpose.valueOf(p.getProjectionPurpose()),p.getSourceEventId(),p.getSourceEventType(),p.getSourceAggregateType(),p.getSourceAggregateId(),p.getTaskId(),p.getA2aRequestId(),p.getHandoffSnapshotId(),p.getTaskIssueLinkId(),p.getConnectionId(),p.getProjectMappingId(),p.getProjectMappingVersion(),p.getProjectMappingSchemaHash(),p.getCanonicalDocumentSchemaVersion(),p.getCanonicalDocumentHash(),IssueProjectionDesiredState.valueOf(p.getDesiredState()),IssueProjectionObservedState.valueOf(p.getObservedState()),com.opensocket.aievent.core.issuetracking.contract.ProjectionLifecycleStatus.valueOf(p.getLifecycleStatus()),com.opensocket.aievent.core.issuetracking.contract.ProjectionFailureClassification.valueOf(p.getFailureClassification()),com.opensocket.aievent.core.issuetracking.contract.ProjectionRecoveryStrategy.valueOf(p.getRecoveryStrategy()),IssueProjectionConflictPolicy.valueOf(p.getConflictPolicy()),p.getDesiredPayloadHash(),p.getObservedPayloadHash(),p.getLastAppliedDomainEventId(),p.getOperationSequence(),p.getProjectionVersion(),p.getSupersededBy(),p.getRetryCount(),p.getMaxAttempts(),p.getNextRetryAt(),p.getLastErrorCode(),p.getLastErrorMessage(),p.getVersion(),p.getCreatedAt(),p.getUpdatedAt(),p.getCompletedAt(),p.getCorrelationId());}
    public IssueProjectionReconciliationCasePo toPo(IssueProjectionReconciliationCase v){var p=new IssueProjectionReconciliationCasePo();p.setTenantId(v.tenantId());p.setCaseId(v.caseId());p.setProjectionId(v.projectionId());p.setReasonCode(v.reasonCode());p.setEvidenceReference(v.evidenceReference());p.setStatus(v.status().name());p.setNextAttemptAt(v.nextAttemptAt());p.setAttemptCount(v.attemptCount());p.setLastError(v.lastError());p.setResolvedBy(v.resolvedBy());p.setResolutionReason(v.resolutionReason());p.setCreatedAt(v.createdAt());p.setUpdatedAt(v.updatedAt());p.setResolvedAt(v.resolvedAt());p.setCorrelationId(v.correlationId());return p;}
    public IssueProjectionReconciliationCase reconciliation(IssueProjectionReconciliationCasePo p){return new IssueProjectionReconciliationCase(p.getTenantId(),p.getCaseId(),p.getProjectionId(),p.getReasonCode(),p.getEvidenceReference(),IssueProjectionReconciliationStatus.valueOf(p.getStatus()),p.getNextAttemptAt(),p.getAttemptCount(),p.getLastError(),p.getResolvedBy(),p.getResolutionReason(),p.getCreatedAt(),p.getUpdatedAt(),p.getResolvedAt(),p.getCorrelationId());}
}
