package com.opensocket.aievent.core.iam.persistence.config;
import com.opensocket.aievent.core.iam.persistence.crypto.HmacTokenSecretAdapter;import com.opensocket.aievent.core.iam.token.application.port.in.*;import com.opensocket.aievent.core.iam.token.application.port.out.*;import com.opensocket.aievent.core.iam.token.application.service.*;import java.time.Clock;import java.util.*;import org.springframework.aop.framework.ProxyFactory;import org.springframework.boot.autoconfigure.AutoConfiguration;import org.springframework.boot.autoconfigure.condition.*;import org.springframework.boot.context.properties.EnableConfigurationProperties;import org.springframework.context.annotation.Bean;import org.springframework.transaction.PlatformTransactionManager;import org.springframework.transaction.interceptor.*;
@AutoConfiguration(after={IamPersistenceAutoConfiguration.class,IamRbacApplicationServiceConfiguration.class}) @EnableConfigurationProperties(IamTokenProperties.class) @ConditionalOnProperty(prefix="aeg.iam.token",name="enabled",havingValue="true") public class IamTokenApplicationServiceConfiguration {
 @Bean @ConditionalOnMissingBean HmacTokenSecretAdapter hmacTokenSecretAdapter(IamTokenProperties p){return new HmacTokenSecretAdapter(decode(p.getSecretPepperBase64()));}
 @Bean @ConditionalOnMissingBean(TokenSecretPort.class) TokenSecretPort tokenSecretPort(HmacTokenSecretAdapter adapter){return adapter;}
 @Bean @ConditionalOnMissingBean(ServiceAccountCredentialSecretPort.class) ServiceAccountCredentialSecretPort serviceAccountCredentialSecretPort(HmacTokenSecretAdapter adapter){return adapter;}
 @Bean @ConditionalOnMissingBean AccessTokenCommandPort accessTokenCommandPort(AccessTokenRepository tokens,ServiceAccountRepository accounts,TokenSecretPort secrets,TokenPermissionAuthorityPort authority,TokenSecurityEpochPort epochs,TokenPolicyRepository policies,TokenRateLimitPort rates,TokenEventPublisher events,TokenUsageEvidencePort usage,Clock clock,PlatformTransactionManager tx){return proxy(new AccessTokenApplicationService(tokens,accounts,secrets,authority,epochs,policies,rates,events,usage,clock),AccessTokenCommandPort.class,tx);}
 @Bean @ConditionalOnMissingBean ServiceAccountCommandPort serviceAccountCommandPort(ServiceAccountRepository accounts,ServiceAccountOwnerPort owners,TokenEventPublisher events,Clock clock,PlatformTransactionManager tx){return proxy(new ServiceAccountApplicationService(accounts,owners,events,clock),ServiceAccountCommandPort.class,tx);}
 @Bean @ConditionalOnMissingBean ServiceAccountCredentialCommandPort serviceAccountCredentialCommandPort(ServiceAccountCredentialRepository credentials,ServiceAccountRepository accounts,ServiceAccountCredentialSecretPort secrets,TokenPermissionAuthorityPort authority,TokenSecurityEpochPort epochs,TokenEventPublisher events,Clock clock,PlatformTransactionManager tx){return proxy(new ServiceAccountCredentialApplicationService(credentials,accounts,secrets,authority,epochs,events,clock),ServiceAccountCredentialCommandPort.class,tx);}
 private byte[] decode(String v){if(v==null||v.isBlank())throw new IllegalStateException("aeg.iam.token.secret-pepper-base64 is required when token foundation is enabled");byte[] x=Base64.getDecoder().decode(v);if(x.length<32)throw new IllegalStateException("token pepper must decode to at least 32 bytes");return Arrays.copyOf(x,32);}
 private static <T>T proxy(T target,Class<T> api,PlatformTransactionManager manager){DefaultTransactionAttribute a=new DefaultTransactionAttribute();a.setName("iam-token:"+api.getSimpleName());MatchAlwaysTransactionAttributeSource s=new MatchAlwaysTransactionAttributeSource();s.setTransactionAttribute(a);TransactionInterceptor advice=new TransactionInterceptor(manager,s);ProxyFactory f=new ProxyFactory();f.setTarget(target);f.setInterfaces(api);f.addAdvice(advice);return api.cast(f.getProxy(api.getClassLoader()));}
}
