package com.opensocket.aievent.database.persistence.a2a.repository;
import java.time.OffsetDateTime;import java.util.*;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.stereotype.Repository;import com.opensocket.aievent.core.a2a.*;import com.opensocket.aievent.database.persistence.a2a.*;import com.opensocket.aievent.database.persistence.a2a.dao.*;
@Repository @ConditionalOnProperty(prefix="task",name="store",havingValue="MYBATIS")
public class MybatisA2AReconciliationCaseRepository implements A2AReconciliationCaseRepository {
 private final A2AReconciliationCaseDao dao;private final A2APersistenceConverter c;public MybatisA2AReconciliationCaseRepository(A2AReconciliationCaseDao d,A2APersistenceConverter c){dao=d;this.c=c;}
 public A2AReconciliationCase save(A2AReconciliationCase v){dao.upsert(c.toPo(v));return findById(v.getTenantId(),v.getCaseId()).orElse(v);}public A2AReconciliationCase saveExpectedVersion(A2AReconciliationCase v,long e){if(dao.updateExpectedVersion(c.toPo(v),e)!=1)throw new IllegalStateException("RESOURCE_VERSION_CONFLICT");return findById(v.getTenantId(),v.getCaseId()).orElseThrow();}
 public Optional<A2AReconciliationCase> findById(String t,String id){return Optional.ofNullable(dao.findById(t,id)).map(c::toDomain);}public Optional<A2AReconciliationCase> findOpenByCancellation(String t,String id){return Optional.ofNullable(dao.findOpenByCancellation(t,id)).map(c::toDomain);}public Optional<A2AReconciliationCase> findOpenByRequest(String t,String id){return Optional.ofNullable(dao.findOpenByRequest(t,id)).map(c::toDomain);}public List<A2AReconciliationCase> findOpen(String t,int l){return dao.findOpen(t,Math.max(1,Math.min(l,1000))).stream().map(c::toDomain).toList();}
 public List<A2AReconciliationCase> claimDue(String w,OffsetDateTime n,OffsetDateTime u,int l){return dao.claimDue(w,n,u,Math.max(1,Math.min(l,200))).stream().map(c::toDomain).toList();}public List<A2AReconciliationCase> claimExecutable(String w,OffsetDateTime n,OffsetDateTime u,int l){return dao.claimExecutable(w,n,u,Math.max(1,Math.min(l,200))).stream().map(c::toDomain).toList();}public boolean heartbeat(String t,String id,String w,long v,OffsetDateTime h,OffsetDateTime u){return dao.heartbeat(t,id,w,v,h,u)==1;}
 public List<A2AReconciliationCase> search(A2AReconciliationSearchQuery q){return dao.search(q.tenantId(),q.status(),q.caseType(),q.authorityOwner(),q.requestId(),q.text(),q.normalizedOffset(),q.cappedLimit(),q.normalizedSortDirection()).stream().map(c::toDomain).toList();}public long count(A2AReconciliationSearchQuery q){return dao.count(q.tenantId(),q.status(),q.caseType(),q.authorityOwner(),q.requestId(),q.text());}public String mode(){return "MYBATIS";}
}
