package com.opensocket.aievent.core.a2a.api;
import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import com.opensocket.aievent.core.a2a.*;import com.opensocket.aievent.core.a2a.application.port.in.A2AUnifiedReconciliationUseCase;
@RestController @RequestMapping("/api/a2a-reconciliation") public class A2AUnifiedReconciliationController {private final A2AUnifiedReconciliationUseCase useCase;private final A2AApiRequestContextAccessor context;public A2AUnifiedReconciliationController(A2AUnifiedReconciliationUseCase u,A2AApiRequestContextAccessor c){useCase=u;context=c;}
 @GetMapping public A2AReconciliationPage search(@RequestParam(required=false)String status,@RequestParam(required=false)String caseType,@RequestParam(required=false)String authorityOwner,@RequestParam(required=false)String requestId,@RequestParam(required=false)String q,@RequestParam(defaultValue="0")int offset,@RequestParam(defaultValue="50")int limit,@RequestParam(defaultValue="DESC")String sortDirection){return execute(()->useCase.search(new A2AReconciliationSearchQuery(tenant(),status,caseType,authorityOwner,requestId,q,offset,limit,sortDirection)));}
 @GetMapping("/{caseId}") public A2AReconciliationDetail detail(@PathVariable String caseId){return execute(()->useCase.detail(tenant(),caseId));}
 @PostMapping("/{caseId}/execute") public A2AReconciliationCase executeRepair(@PathVariable String caseId,@RequestHeader("Idempotency-Key")String key,@RequestBody ExecuteBody b){return execute(()->useCase.execute(new A2ARepairExecutionCommand(tenant(),caseId,b.expectedVersion(),b.planHash(),key,actor(),b.reason())));}
 @PostMapping("/{caseId}/outcome") public A2AReconciliationCase recordOutcome(@PathVariable String caseId,@RequestBody OutcomeBody b){return execute(()->useCase.recordOutcome(new A2ARepairOutcomeCommand(tenant(),caseId,b.expectedVersion(),b.succeeded(),b.retryable(),b.evidenceReference(),b.reasonCode(),b.reason(),actor())));}
 private String tenant(){A2AApiRequestContext c=context.current();if(c==null||c.tenantId()==null||c.tenantId().isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"tenantId is required");return c.tenantId().trim();}private String actor(){A2AApiRequestContext c=context.current();return c==null||c.actorId()==null||c.actorId().isBlank()?"unknown-operator":c.actorId();}private <T>T execute(Op<T> op){try{return op.run();}catch(IllegalArgumentException e){throw new ResponseStatusException(e.getMessage()!=null&&e.getMessage().contains("not found")?HttpStatus.NOT_FOUND:HttpStatus.BAD_REQUEST,e.getMessage(),e);}catch(IllegalStateException e){throw new ResponseStatusException(HttpStatus.CONFLICT,e.getMessage(),e);}}private interface Op<T>{T run();}public record ExecuteBody(long expectedVersion,String planHash,String reason){}public record OutcomeBody(long expectedVersion,boolean succeeded,boolean retryable,String evidenceReference,String reasonCode,String reason){}
}
