package com.opensocket.aievent.core.a2a.application.service;

import java.time.OffsetDateTime; import java.time.ZoneOffset; import java.util.*;
import org.springframework.transaction.annotation.Transactional;
import com.opensocket.aievent.core.a2a.*; import com.opensocket.aievent.core.a2a.application.port.in.A2AResultAcceptanceUseCase; import com.opensocket.aievent.core.a2a.core.*; import com.opensocket.aievent.core.a2a.core.port.ResultEvidenceAuthorityPort; import com.opensocket.aievent.core.a2a.core.port.ResultEvidenceAuthorityPort.Verification;

/** Sole authority for immutable canonical Result acceptance and precise duplicate classification. */
public class A2AResultAcceptanceService implements A2AResultAcceptanceUseCase {
 private static final Set<A2ARequestStatus> TERMINAL=Set.of(A2ARequestStatus.REJECTED,A2ARequestStatus.COMPLETED,A2ARequestStatus.FAILED,A2ARequestStatus.CANCELLED_CONFIRMED,A2ARequestStatus.EXPIRED);
 private final A2AResultEvidenceGuard guard=new A2AResultEvidenceGuard(); private final A2AStateMachine stateMachine=new A2AStateMachine(); private final A2APolicySnapshotFactory policySnapshots=new A2APolicySnapshotFactory();
 private final ResultEvidenceAuthorityPort authority; private final A2ARequestRepository requests; private final A2AResultRepository results; private final A2AResultAttemptRepository attempts; private final A2AResultIdempotencyClaimRepository claims; private final A2AResultEvidenceRepository evidence; private final A2AResultQuarantineRepository quarantine; private final A2AResultProcessingRepository processing; private final A2AStateHistoryRepository history; private final A2AResultCompletionCoordinator coordinator;
 public A2AResultAcceptanceService(ResultEvidenceAuthorityPort authority,A2ARequestRepository requests,A2AResultRepository results,A2AResultAttemptRepository attempts,A2AResultIdempotencyClaimRepository claims,A2AResultEvidenceRepository evidence,A2AResultQuarantineRepository quarantine,A2AResultProcessingRepository processing,A2AStateHistoryRepository history,A2AResultCompletionCoordinator coordinator){this.authority=authority;this.requests=requests;this.results=results;this.attempts=attempts;this.claims=claims;this.evidence=evidence;this.quarantine=quarantine;this.processing=processing;this.history=history;this.coordinator=coordinator;}

 @Transactional(noRollbackFor=A2AResultQuarantinedException.class) public A2AResult accept(A2AResultSubmission submission){
  guard.requireEvidence(submission); String fingerprint=A2AResultFingerprint.result(submission);
  Optional<A2AResultIdempotencyClaim> replay=claims.findByIdempotencyKey(submission.tenantId(),submission.idempotencyKey());
  if(replay.isPresent()){A2AResultIdempotencyClaim claim=replay.get();Optional<A2AResult> canonical=results.findById(submission.tenantId(),claim.getResultId());if(canonical.isEmpty())throw new IllegalStateException("A2A_RESULT_IDEMPOTENCY_CLAIM_ORPHANED:"+claim.getIdempotencyKey());if(same(claim.getRequestId(),submission.requestId())&&same(canonical.get().getResultFingerprint(),fingerprint))return canonical.get();throw quarantined("IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_RESULT",claim.getAcceptanceAttemptId());}
  A2ARequest request=requests.findById(submission.tenantId(),submission.requestId()).orElseThrow(()->new IllegalArgumentException("A2A Request not found: "+submission.requestId()));
  if(blank(request.getChildTaskId()))throw new IllegalStateException("A2A_CHILD_TASK_NOT_CREATED"); requireValidPolicyBinding(request);
  Optional<A2AResult> existing=results.findByRequest(submission.tenantId(),submission.requestId());
  if(existing.isPresent()){A2AResultClassification classification=same(existing.get().getResultFingerprint(),fingerprint)?A2AResultClassification.IDENTICAL_DUPLICATE:A2AResultClassification.CONFLICTING_DUPLICATE;A2AResultAcceptanceDecision decision=classification==A2AResultClassification.IDENTICAL_DUPLICATE?A2AResultAcceptanceDecision.DUPLICATE:A2AResultAcceptanceDecision.CONFLICT;A2AResultAttempt attempt=saveAttempt(request,submission,decision,classification,classification.name(),classification==A2AResultClassification.IDENTICAL_DUPLICATE?"Canonical Result already accepted":"Submission conflicts with Canonical Result",existing.get().getResultId(),null,fingerprint);saveEvidence(attempt,submission,null,fingerprint);if(decision==A2AResultAcceptanceDecision.DUPLICATE)return existing.get();saveQuarantine(attempt,submission,classification,attempt.getReasonCode(),attempt.getReason());throw quarantined(attempt.getReasonCode(),attempt.getAttemptId());}
  if(TERMINAL.contains(request.getRequestStatus())){A2AResultClassification classification=(request.getRequestStatus()==A2ARequestStatus.CANCELLED_CONFIRMED||request.getRequestStatus()==A2ARequestStatus.EXPIRED)?A2AResultClassification.LATE_RESULT:A2AResultClassification.TERMINAL_REQUEST;A2AResultAttempt attempt=saveAttempt(request,submission,A2AResultAcceptanceDecision.LATE,classification,classification.name(),"A2A Request is terminal without this Canonical Result",null,null,fingerprint);saveEvidence(attempt,submission,null,fingerprint);saveQuarantine(attempt,submission,classification,attempt.getReasonCode(),attempt.getReason());throw quarantined(attempt.getReasonCode(),attempt.getAttemptId());}
  Verification verification=authority.verify(request.getChildTaskId(),submission);
  if(!verification.accepted()){A2AResultClassification classification=verification.classification()==null?A2AResultClassification.MISSING_EVIDENCE:verification.classification();A2AResultAttempt attempt=saveAttempt(request,submission,verification.decision(),classification,verification.reasonCode(),verification.reason(),null,verification,fingerprint);saveEvidence(attempt,submission,verification,fingerprint);saveQuarantine(attempt,submission,classification,verification.reasonCode(),verification.reason());throw quarantined(verification.reasonCode(),attempt.getAttemptId());}
  OffsetDateTime now=now();long expected=request.getVersion();A2ATransitionDecision transition=stateMachine.decide(request,requestCommand(submission.resultStatus()),requestTarget(submission.resultStatus()),A2ABlockerCode.NONE,expected,first(submission.resultSummary(),"Evidence-bearing A2A Result accepted"),"callback:"+first(submission.callbackInboxId(),submission.idempotencyKey()),now);applyDecision(request,transition,now);
  try{request=requests.saveExpectedVersion(request,expected);}catch(IllegalStateException ex){if(!"RESOURCE_VERSION_CONFLICT".equals(ex.getMessage()))throw ex;return handleConflict(submission,verification,fingerprint);}
  String resultId="a2ares-"+UUID.randomUUID();A2AResultAttempt attempt=saveAttempt(request,submission,A2AResultAcceptanceDecision.ACCEPTED,null,verification.reasonCode(),verification.reason(),resultId,verification,fingerprint);saveEvidence(attempt,submission,verification,fingerprint);
  A2AResult result=new A2AResult();result.setTenantId(request.getTenantId());result.setResultId(resultId);result.setRequestId(request.getRequestId());result.setRootTaskId(request.getRootTaskId());result.setParentTaskId(request.getSourceTaskId());result.setChildTaskId(request.getChildTaskId());result.setResultStatus(submission.resultStatus());result.setResultSummary(trim(submission.resultSummary()));result.setResultPayloadRef(trim(submission.resultPayloadRef()));result.setEvidenceRefs(submission.evidenceRefs());result.setCompletedByAgentId(verification.authoritativeAgentId());result.setAssignmentId(verification.authoritativeAssignmentId());result.setExecutionAttemptId(verification.authoritativeExecutionAttemptId());result.setAttemptNo(verification.authoritativeAttemptNo());result.setDispatchRequestId(verification.authoritativeDispatchRequestId());result.setDispatchTokenHash(submission.dispatchTokenHash());result.setFencingTokenHash(submission.fencingTokenHash());result.setAgentSessionId(verification.authoritativeAgentSessionId());result.setCallbackInboxId(submission.callbackInboxId());result.setPayloadHash(submission.payloadHash());result.setResultSchemaVersion(submission.resultSchemaVersion());result.setResultEvidenceHash(submission.resultEvidenceHash());result.setResultFingerprint(fingerprint);result.setPolicyVersion(request.getPolicyVersion());result.setPolicySnapshotHash(request.getPolicySnapshotHash());result.setAcceptanceAttemptId(attempt.getAttemptId());result.setReceivedAt(attempt.getReceivedAt());result.setAcceptedAt(now);result.setCompletedAt(first(submission.occurredAt(),now));result.setIdempotencyKey(submission.idempotencyKey());result.setCreatedAt(now);result=results.save(result);saveIdempotencyClaim(result,attempt,fingerprint,now);
  A2AResultProcessing p=new A2AResultProcessing();p.setTenantId(result.getTenantId());p.setResultId(result.getResultId());p.setRequestId(result.getRequestId());p.setParentTaskId(result.getParentTaskId());p.setChildTaskId(result.getChildTaskId());p.setProcessingStatus(A2AResultProcessingStatus.CHILD_COMPLETION_PENDING);p.setCreatedAt(now);p.setUpdatedAt(now);p.setNextReconcileAt(now);processing.save(p);saveHistory(request,transition,submission,result,now);coordinator.process(result.getTenantId(),result.getResultId(),"A2A_RESULT_ACCEPTANCE");return result;
 }

 private A2AResult handleConflict(A2AResultSubmission s,Verification v,String fingerprint){A2ARequest current=requests.findById(s.tenantId(),s.requestId()).orElseThrow();Optional<A2AResult> canonical=results.findByRequest(s.tenantId(),s.requestId());A2AResultClassification classification;if(canonical.isPresent())classification=same(canonical.get().getResultFingerprint(),fingerprint)?A2AResultClassification.IDENTICAL_DUPLICATE:A2AResultClassification.CONFLICTING_DUPLICATE;else if(TERMINAL.contains(current.getRequestStatus()))classification=A2AResultClassification.TERMINAL_REQUEST;else classification=A2AResultClassification.STALE_ATTEMPT;A2AResultAcceptanceDecision decision=classification==A2AResultClassification.IDENTICAL_DUPLICATE?A2AResultAcceptanceDecision.DUPLICATE:classification==A2AResultClassification.CONFLICTING_DUPLICATE?A2AResultAcceptanceDecision.CONFLICT:classification==A2AResultClassification.TERMINAL_REQUEST?A2AResultAcceptanceDecision.LATE:A2AResultAcceptanceDecision.STALE;A2AResultAttempt attempt=saveAttempt(current,s,decision,classification,classification.name(),"Concurrent canonical acceptance claim was not won",canonical.map(A2AResult::getResultId).orElse(null),v,fingerprint);saveEvidence(attempt,s,v,fingerprint);if(decision==A2AResultAcceptanceDecision.DUPLICATE)return canonical.orElseThrow();saveQuarantine(attempt,s,classification,attempt.getReasonCode(),attempt.getReason());throw quarantined(attempt.getReasonCode(),attempt.getAttemptId());}
 private void requireValidPolicyBinding(A2ARequest r){A2ADirectionalPolicySnapshot snapshot=r.getPolicySnapshot();if(snapshot==null)return;if(blank(r.getPolicySnapshotHash())&&blank(snapshot.snapshotHash()))return;if(!policySnapshots.verify(snapshot)||r.getPolicyVersion()!=snapshot.policyVersion()||!same(r.getPolicySnapshotHash(),snapshot.snapshotHash()))throw new IllegalStateException("A2A_POLICY_BINDING_INVALID");}
 private A2AResultAttempt saveAttempt(A2ARequest r,A2AResultSubmission s,A2AResultAcceptanceDecision decision,A2AResultClassification classification,String code,String reason,String resultId,Verification v,String fingerprint){A2AResultAttempt a=new A2AResultAttempt();a.setTenantId(r.getTenantId());a.setAttemptId("a2aratt-"+UUID.randomUUID());a.setRequestId(r.getRequestId());a.setChildTaskId(r.getChildTaskId());a.setResultId(resultId);a.setAssignmentId(v==null?s.assignmentId():v.authoritativeAssignmentId());a.setExecutionAttemptId(v==null?s.executionAttemptId():v.authoritativeExecutionAttemptId());a.setAttemptNo(v==null?s.attemptNo():v.authoritativeAttemptNo());a.setDispatchRequestId(v==null?s.dispatchRequestId():v.authoritativeDispatchRequestId());a.setCallbackInboxId(s.callbackInboxId());a.setAgentId(v==null?s.completedByAgentId():v.authoritativeAgentId());a.setAgentSessionId(v==null?s.agentSessionId():v.authoritativeAgentSessionId());a.setResultStatus(s.resultStatus());a.setDecision(decision);a.setClassification(classification);a.setResultSchemaVersion(s.resultSchemaVersion());a.setResultEvidenceHash(s.resultEvidenceHash());a.setResultFingerprint(fingerprint);a.setPolicyVersion(r.getPolicyVersion());a.setPolicySnapshotHash(r.getPolicySnapshotHash());a.setReasonCode(code);a.setReason(reason);a.setPayloadHash(s.payloadHash());a.setIdempotencyKey(s.idempotencyKey());a.setCorrelationId(first(s.correlationId(),r.getCorrelationId()));a.setOccurredAt(s.occurredAt());a.setReceivedAt(now());return attempts.save(a);}
 private void saveIdempotencyClaim(A2AResult result,A2AResultAttempt attempt,String fingerprint,OffsetDateTime at){A2AResultIdempotencyClaim claim=new A2AResultIdempotencyClaim();claim.setTenantId(result.getTenantId());claim.setIdempotencyKey(result.getIdempotencyKey());claim.setRequestId(result.getRequestId());claim.setResultId(result.getResultId());claim.setAcceptanceAttemptId(attempt.getAttemptId());claim.setResultFingerprint(fingerprint);claim.setClaimedAt(at);claims.save(claim);}
 private void saveEvidence(A2AResultAttempt a,A2AResultSubmission s,Verification v,String fingerprint){saveEvidence(a,"CALLBACK_INBOX",s.callbackInboxId(),v==null?null:v.callbackFingerprint(),v,fingerprint);saveEvidence(a,"DISPATCH_TOKEN_HASH",s.dispatchRequestId(),s.dispatchTokenHash(),v,fingerprint);saveEvidence(a,"FENCING_TOKEN_HASH",s.assignmentId(),s.fencingTokenHash(),v,fingerprint);saveEvidence(a,"PAYLOAD_HASH",s.callbackInboxId(),s.payloadHash(),v,fingerprint);saveEvidence(a,"RESULT_EVIDENCE_HASH",s.callbackInboxId(),s.resultEvidenceHash(),v,fingerprint);saveEvidence(a,"EXECUTION_ATTEMPT",v==null?s.executionAttemptId():v.authoritativeExecutionAttemptId(),null,v,fingerprint);}
 private void saveEvidence(A2AResultAttempt a,String type,String ref,String hash,Verification v,String fingerprint){if(blank(ref)&&blank(hash))return;A2AResultEvidence e=new A2AResultEvidence();e.setTenantId(a.getTenantId());e.setEvidenceId("a2arev-"+UUID.randomUUID());e.setAttemptId(a.getAttemptId());e.setRequestId(a.getRequestId());e.setEvidenceType(type);e.setEvidenceReference(ref);e.setEvidenceHash(hash);e.setVerificationDecision(v==null?a.getDecision().name():v.decision().name());e.setClassification(a.getClassification());e.setResultFingerprint(fingerprint);e.setReasonCode(v==null?a.getReasonCode():v.reasonCode());e.setVerifiedAt(now());evidence.save(e);}
 private void saveQuarantine(A2AResultAttempt a,A2AResultSubmission s,A2AResultClassification classification,String code,String reason){A2AResultQuarantine q=new A2AResultQuarantine();q.setTenantId(a.getTenantId());q.setQuarantineId("a2arq-"+UUID.randomUUID());q.setAttemptId(a.getAttemptId());q.setRequestId(a.getRequestId());q.setChildTaskId(a.getChildTaskId());q.setClassification(classification);q.setReasonCode(code);q.setReason(reason);q.setPayloadHash(s.payloadHash());q.setCallbackInboxId(s.callbackInboxId());q.setAssignmentId(a.getAssignmentId());q.setExecutionAttemptId(a.getExecutionAttemptId());q.setStatus("OPEN");q.setQuarantinedAt(now());quarantine.save(q);}
 private void saveHistory(A2ARequest r,A2ATransitionDecision t,A2AResultSubmission s,A2AResult result,OffsetDateTime now){String key="result:"+s.idempotencyKey();if(history.findByIdempotencyKey(r.getTenantId(),key).isPresent())return;A2AStateHistoryEntry h=new A2AStateHistoryEntry();h.setTenantId(r.getTenantId());h.setHistoryId("a2ah-"+UUID.randomUUID());h.setRequestId(r.getRequestId());h.setFromStatus(t.fromStatus());h.setFromOperationalStage(t.fromStage());h.setToStatus(t.toStatus());h.setToOperationalStage(t.toStage());h.setBlockerCode(t.blockerCode());h.setTransitionCommand(t.command());h.setRequiredPermission(t.requiredPermission());h.setEvidenceType(t.evidenceType());h.setEvidenceReference(t.evidenceReference());h.setDomainEventCode(t.domainEventCode());h.setFailureHandling(t.failureHandling());h.setTimeoutPolicy(t.timeoutPolicy());h.setExpectedVersion(t.expectedVersion());h.setResultingVersion(t.resultingVersion());h.setRecovery(t.recovery());h.setReasonCode("A2A_CANONICAL_RESULT_"+s.resultStatus().name());h.setReason(s.resultSummary());h.setActorType("AGENT");h.setActorId(first(result.getCompletedByAgentId(),"A2A_RESULT_AUTHORITY"));h.setCorrelationId(r.getCorrelationId());h.setTransitionAt(now);h.setRequestVersion(r.getVersion());h.setIdempotencyKey(key);history.save(h);}
 private void applyDecision(A2ARequest r,A2ATransitionDecision t,OffsetDateTime at){r.setRequestStatus(t.toStatus());r.setOperationalStage(t.toStage());r.setBlockerCode(t.blockerCode());r.setBlockerReason(t.blockerCode()==A2ABlockerCode.NONE?null:t.auditReason());r.setUpdatedAt(at);r.setVersion(t.resultingVersion());}
 private A2ATransitionCommand requestCommand(A2AResultStatus s){return switch(s){case SUCCEEDED,PARTIAL->A2ATransitionCommand.COMPLETE;case FAILED->A2ATransitionCommand.FAIL;case CANCELLED->A2ATransitionCommand.CONFIRM_CANCEL;};}
 private A2ARequestStatus requestTarget(A2AResultStatus s){return switch(s){case SUCCEEDED,PARTIAL->A2ARequestStatus.COMPLETED;case FAILED->A2ARequestStatus.FAILED;case CANCELLED->A2ARequestStatus.CANCELLED_CONFIRMED;};}
 private A2AResultQuarantinedException quarantined(String c,String id){return new A2AResultQuarantinedException(c,id);} public static final class A2AResultQuarantinedException extends IllegalStateException{private final String reasonCode,attemptId;public A2AResultQuarantinedException(String c,String id){super("A2A_RESULT_QUARANTINED:"+c+":attemptId="+id);reasonCode=c;attemptId=id;}public String getReasonCode(){return reasonCode;}public String getAttemptId(){return attemptId;}}
 private OffsetDateTime now(){return OffsetDateTime.now(ZoneOffset.UTC);}private boolean blank(String v){return v==null||v.isBlank();}private boolean same(Object a,Object b){return Objects.equals(a,b);}private String trim(String v){return blank(v)?null:v.trim();}private String first(String...v){for(String x:v)if(!blank(x))return x;return null;}private OffsetDateTime first(OffsetDateTime a,OffsetDateTime b){return a==null?b:a;}
}
