package com.opensocket.aievent.core.a2a.application.service;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.util.HexFormat;
import com.opensocket.aievent.core.a2a.*;import com.opensocket.aievent.core.integration.handoff.*;
/** Converts every transitional subsystem into a unified deterministic reconciliation case. */
public final class A2AReconciliationCaseProducer {
 private final A2AResultProcessingRepository results;private final HandoffContextRepository handoffs;private final A2ACancellationRepository cancellations;private final A2AReconciliationCaseRepository cases;
 public A2AReconciliationCaseProducer(A2AResultProcessingRepository r,HandoffContextRepository h,A2ACancellationRepository c,A2AReconciliationCaseRepository x){results=r;handoffs=h;cancellations=c;cases=x;}
 public int produce(int limit){OffsetDateTime now=OffsetDateTime.now(ZoneOffset.UTC);int n=0;for(A2AResultProcessing v:results.findDue(now,limit)){n+=create(v.getTenantId(),"RESULT_PROCESSING_GAP",v.getRequestId(),null,null,v.getResultId(),null,"A2A_CORE","RESULT_PROCESSING_DUE",v.getLastError(),v.getRowVersion())?1:0;}for(HandoffContextSnapshot v:handoffs.findReleaseCandidates(now,limit)){n+=create(v.tenantId(),"HANDOFF_RELEASE_GAP",null,null,v.targetTaskId(),null,v.snapshotId(),"HANDOFF_CORE","HANDOFF_RELEASE_DUE",v.lastReleaseErrorCode(),v.rowVersion())?1:0;}for(A2ACancellationRecord v:cancellations.findDue(now,limit)){n+=create(v.getTenantId(),"CANCELLATION_ACK_MISSING",v.getRequestId(),v.getCancellationId(),v.getChildTaskId(),null,null,"RUNTIME_AUTHORITY","CANCELLATION_DUE",v.getLastError(),v.getVersion())?1:0;}return n;}
 private boolean create(String tenant,String type,String request,String cancellation,String child,String result,String handoff,String authority,String reasonCode,String reason,long resourceVersion){String resource=first(result,handoff,cancellation,request,child);if(tenant==null||resource==null)return false;String id="recon-"+hash(tenant+"|"+type+"|"+resource).substring(0,32);if(cases.findById(tenant,id).filter(A2AReconciliationCase::active).isPresent())return false;A2AReconciliationCase v=new A2AReconciliationCase();v.setTenantId(tenant);v.setCaseId(id);v.setCaseType(type);v.setRequestId(request);v.setCancellationId(cancellation);v.setChildTaskId(child);v.setResultId(result);v.setHandoffSnapshotId(handoff);v.setStatus(A2AReconciliationStatus.OPEN);v.setAuthorityOwner(authority);v.setReasonCode(reasonCode);v.setReason(first(reason,reasonCode));v.setEvidenceSummary("Deterministic producer observed "+type+" for "+resource);v.setExpectedResourceVersion(resourceVersion);v.setCreatedAt(now());v.setUpdatedAt(now());cases.save(v);return true;}
 private static String first(String...v){for(String x:v)if(x!=null&&!x.isBlank())return x;return null;}private static OffsetDateTime now(){return OffsetDateTime.now(ZoneOffset.UTC);}private static String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
