package com.opensocket.aievent.database.persistence.issuechange.dao;
import java.util.*; import org.apache.ibatis.annotations.*; import com.opensocket.aievent.database.persistence.issuechange.po.*;
@Mapper public interface ExternalChangeGovernanceDao {
 int upsertPolicy(@Param("value")ExternalChangePolicyPo value); int updatePolicyExpectedVersion(@Param("value")ExternalChangePolicyPo value,@Param("expectedVersion")long expectedVersion); ExternalChangePolicyPo findPolicy(@Param("tenantId")String tenantId,@Param("policyId")String policyId); List<ExternalChangePolicyPo> listPolicies(@Param("tenantId")String tenantId,@Param("status")String status,@Param("limit")int limit);
 int upsertComment(@Param("value")ExternalCommentSyncPo value); ExternalCommentSyncPo findCommentByMarker(@Param("tenantId")String tenantId,@Param("connectionId")String connectionId,@Param("sourceMarker")String sourceMarker); ExternalCommentSyncPo findCommentByIdempotency(@Param("tenantId")String tenantId,@Param("sourceCommentId")String sourceCommentId,@Param("direction")String direction); List<ExternalCommentSyncPo> listComments(@Param("tenantId")String tenantId,@Param("status")String status,@Param("limit")int limit);
 int upsertRelation(@Param("value")ExternalRelationSyncPo value); ExternalRelationSyncPo findRelationByMarker(@Param("tenantId")String tenantId,@Param("connectionId")String connectionId,@Param("sourceMarker")String sourceMarker); ExternalRelationSyncPo findRelationByIdempotency(@Param("tenantId")String tenantId,@Param("sourceExternalIssueId")String sourceExternalIssueId,@Param("targetExternalIssueId")String targetExternalIssueId,@Param("relationType")String relationType,@Param("direction")String direction); List<ExternalRelationSyncPo> listRelations(@Param("tenantId")String tenantId,@Param("status")String status,@Param("limit")int limit);
 int upsertCandidate(@Param("value")ProviderActionCandidatePo value); int updateCandidateExpectedVersion(@Param("value")ProviderActionCandidatePo value,@Param("expectedVersion")long expectedVersion); ProviderActionCandidatePo findCandidate(@Param("tenantId")String tenantId,@Param("candidateId")String candidateId); ProviderActionCandidatePo findCandidateByIdempotency(@Param("tenantId")String tenantId,@Param("idempotencyKey")String idempotencyKey); List<ProviderActionCandidatePo> listCandidates(@Param("tenantId")String tenantId,@Param("status")String status,@Param("limit")int limit);
 int insertCandidateEvent(@Param("value")ProviderActionCandidateEventPo value); ProviderActionCandidateEventPo latestCandidateEvent(@Param("tenantId")String tenantId,@Param("candidateId")String candidateId); List<ProviderActionCandidateEventPo> listCandidateEvents(@Param("tenantId")String tenantId,@Param("candidateId")String candidateId,@Param("limit")int limit);
}
