package com.opensocket.aievent.core.decision;

public enum DecisionAction {
    EVENT_NORMALIZED,
    FINGERPRINT_GENERATED,
    DEDUP_EVALUATED,
    INCIDENT_OBSERVED,
    CREATE_INCIDENT,
    UPDATE_INCIDENT_OCCURRENCE,
    ESCALATE_INCIDENT,
    CREATE_TASK,
    CREATE_ESCALATION_TASK,
    SUPPRESS_DUPLICATE_TASK,
    SUPPRESS_DUPLICATE_EVENT,
    SUPPRESS_OPEN_INCIDENT_TASK,
    SUPPRESS_TASK_BELOW_THRESHOLD,
    SUPPRESS_NEW_TASK,
    CREATE_ASSIGNMENT,
    SUPPRESS_ASSIGNMENT,
    CREATE_DISPATCH_REQUEST,
    SUPPRESS_DISPATCH,
    SUPPRESS_MCP_CALL,
    SUPPRESS_ISSUE_CREATION,
    TASK_RECOMMENDED_BUT_DISABLED
}
