package com.opensocket.aievent.core.action.executor.issue.scoped;
import com.opensocket.aievent.core.integration.identity.*; import org.springframework.context.annotation.Primary; import org.springframework.stereotype.Component; import tools.jackson.databind.ObjectMapper; import java.util.*;
@Component @Primary
public class ProviderPermissionProbeGateway implements IntegrationPermissionProbeGateway {
 private final IntegrationSecretResolver secrets; private final RedminePermissionProbeAdapter redmine; private final JiraPermissionProbeAdapter jira;
 public ProviderPermissionProbeGateway(IntegrationSecretResolver secrets,ObjectMapper json){this.secrets=secrets;this.redmine=new RedminePermissionProbeAdapter(json);this.jira=new JiraPermissionProbeAdapter(json);}
 public PermissionProbeObservation probe(IntegrationConnection c,IntegrationPrincipal p,IntegrationCredentialMetadata credential,IntegrationProjectMapping mapping){try(var resolved=secrets.resolve(credential)){String secret=resolved.reveal();return switch(c.providerType()){case REDMINE->redmine.probe(c,p,credential,mapping,secret);case JIRA->jira.probe(c,p,credential,mapping,secret);default->unsupported(c.providerType());};}catch(RuntimeException e){var results=new EnumMap<IntegrationPermissionCapability,PermissionProbeResultStatus>(IntegrationPermissionCapability.class);for(var capability:IntegrationPermissionCapability.values())results.put(capability,PermissionProbeResultStatus.ERROR);return new PermissionProbeObservation(results,List.of(),"Permission Probe could not resolve the scoped Credential reference. Review resolver and credential evidence.");}}
 private PermissionProbeObservation unsupported(IntegrationProviderType type){var results=new EnumMap<IntegrationPermissionCapability,PermissionProbeResultStatus>(IntegrationPermissionCapability.class);for(var capability:IntegrationPermissionCapability.values())results.put(capability,PermissionProbeResultStatus.UNSUPPORTED);return new PermissionProbeObservation(results,List.of(),type+" Permission Probe is not implemented in Phase 0E-1.");}
}
