package com.opensocket.aievent.core.action.executor.issue.scoped;
import com.opensocket.aievent.core.action.executor.issue.*; import com.opensocket.aievent.core.integration.identity.*; import java.net.*; import java.net.http.*; import java.nio.charset.StandardCharsets; import java.time.Duration; import java.util.*; import tools.jackson.core.type.TypeReference; import tools.jackson.databind.ObjectMapper;
final class ScopedJiraIssueVendorExecutor {
 private static final TypeReference<Map<String,Object>> MAP=new TypeReference<>(){}; private final ObjectMapper json; private final HttpClient client; private final ScopedIntegrationExecutionContext context; private final String secret;
 ScopedJiraIssueVendorExecutor(ObjectMapper json,ScopedIntegrationExecutionContext context,String secret){this.json=json;this.context=context;this.secret=secret;this.client=HttpClient.newBuilder().connectTimeout(Duration.ofMillis(Math.max(1000,context.connection().timeoutMs()))).build();}
 IssueExecutorResponse execute(IssueExecutorRequest request){try{return "ISSUE_UPDATE_COMMENT".equalsIgnoreCase(request.getActionType())?comment(request):create(request);}catch(Exception e){return failure(e.getClass().getSimpleName(),true,null);}}
 private IssueExecutorResponse create(IssueExecutorRequest request)throws Exception{String project=first(context.mapping().externalProjectKey(),context.mapping().externalProjectId());String issueType=first(context.mapping().externalIssueType(),"Task");String title=first(text(request,"issueTitle","title","subject"),"OpenDispatch Task "+request.getTaskId());String description=first(text(request,"issueDescription","description","message"),"OpenDispatch Task: "+request.getTaskId());Map<String,Object> fields=new LinkedHashMap<>();fields.put("project",Map.of("key",project));fields.put("summary",title);fields.put("issuetype",Map.of("name",issueType));fields.put("description",description);var response=send("POST",join("/rest/api/3/issue"),json.writeValueAsString(Map.of("fields",fields)));if(!ok(response.statusCode()))return failure("Jira create issue returned "+response.statusCode(),retryable(response.statusCode()),response.statusCode());Map<String,Object> body=parse(response.body());String key=body.get("key")==null?null:String.valueOf(body.get("key"));if(key==null)return failure("Jira create issue response missing key",false,response.statusCode());return success(key,join("/browse/"+encode(key)),"open","jira:"+key);}
 private IssueExecutorResponse comment(IssueExecutorRequest request)throws Exception{String issue=first(text(request,"linkedIssueId","issueId","externalIssueId","key"),null);if(issue==null)return failure("linkedIssueId is required for Jira comment update",false,null);String body=first(text(request,"issueComment","comment","notes","body"),"OpenDispatch update for Task "+request.getTaskId());var response=send("POST",join("/rest/api/3/issue/"+encode(issue)+"/comment"),json.writeValueAsString(Map.of("body",body)));if(!ok(response.statusCode()))return failure("Jira add comment returned "+response.statusCode(),retryable(response.statusCode()),response.statusCode());return success(issue,join("/browse/"+encode(issue)),"comment_synced","jira-comment:"+issue);}
 private HttpResponse<String> send(String method,String url,String body)throws Exception{var b=HttpRequest.newBuilder(URI.create(url)).timeout(Duration.ofMillis(Math.max(1000,context.connection().timeoutMs()))).header("Accept","application/json").header("Content-Type","application/json");auth().forEach(b::header);b.method(method,HttpRequest.BodyPublishers.ofString(body));return client.send(b.build(),HttpResponse.BodyHandlers.ofString());}
 private Map<String,String> auth(){var p=context.principal();var c=context.credential();var h=new LinkedHashMap<String,String>();if((c.authType()==IntegrationAuthType.API_TOKEN||c.authType()==IntegrationAuthType.BASIC_PASSWORD)&&p.externalPrincipalIdentifier()!=null&&!p.externalPrincipalIdentifier().isBlank())h.put("Authorization","Basic "+Base64.getEncoder().encodeToString((p.externalPrincipalIdentifier()+":"+secret).getBytes(StandardCharsets.UTF_8)));else h.put("Authorization","Bearer "+secret);return h;}
 private String text(IssueExecutorRequest r,String...keys){for(String k:keys){Object v=r.getPayload().get(k);if(v!=null&&!String.valueOf(v).isBlank())return String.valueOf(v).trim();}return null;} private String first(String a,String b){return a!=null&&!a.isBlank()?a:b;} private String join(String p){String b=context.connection().baseUrl();if(b.endsWith("/"))b=b.substring(0,b.length()-1);return b+(p.startsWith("/")?p:"/"+p);} private String encode(String v){return URLEncoder.encode(v,StandardCharsets.UTF_8).replace("+","%20");} private boolean ok(int s){return s>=200&&s<300;} private boolean retryable(int s){return s==408||s==429||s>=500;} private Map<String,Object> parse(String b){try{return json.readValue(b,MAP);}catch(Exception e){return Map.of();}}
 private IssueExecutorResponse success(String id,String url,String status,String ref){var r=new IssueExecutorResponse();r.setSuccess(true);r.setVendor("JIRA");r.setIssueId(id);r.setIssueUrl(url);r.setIssueStatus(status);r.setResponseRef(ref);return r;} private IssueExecutorResponse failure(String error,boolean retryable,Integer status){var r=new IssueExecutorResponse();r.setSuccess(false);r.setVendor("JIRA");r.setError(error);r.setRetryable(retryable);r.setStatusCode(status);return r;}
}
