package com.opensocket.aievent.core.action.executor.issue.scoped;
import java.net.URI; import java.net.http.*; import java.nio.charset.StandardCharsets; import java.time.Duration; import java.util.*; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.context.annotation.Primary; import org.springframework.stereotype.Component; import tools.jackson.databind.ObjectMapper;
import com.opensocket.aievent.core.action.*; import com.opensocket.aievent.core.action.executor.*; import com.opensocket.aievent.core.action.executor.issue.*; import com.opensocket.aievent.core.integration.handoff.HandoffContextSnapshot; import com.opensocket.aievent.core.integration.issue.projection.CrossProjectIssueRelay; import com.opensocket.aievent.core.integration.issue.projection.IssueRelayProviderGateway; import com.opensocket.aievent.core.integration.issue.projection.IssueRelayProviderResult; import com.opensocket.aievent.core.integration.identity.*;
/** Production relay gateway. Every provider operation resolves an operation-specific scoped Principal. */
@Component @Primary @ConditionalOnProperty(prefix="issue-projection",name="relay-provider",havingValue="SCOPED",matchIfMissing=true)
public class ScopedIssueRelayProviderGateway implements IssueRelayProviderGateway {
 private final IntegrationIdentityService identities; private final IntegrationSecretResolver secrets; private final ScopedIssueExecutionService execution; private final ObjectMapper json; private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build();
 public ScopedIssueRelayProviderGateway(IntegrationIdentityService identities,IntegrationSecretResolver secrets,ScopedIssueExecutionService execution,ObjectMapper json){this.identities=identities;this.secrets=secrets;this.execution=execution;this.json=json;}
 public IssueRelayProviderResult createTargetIssue(CrossProjectIssueRelay relay,HandoffContextSnapshot snapshot){var action=action(relay,relay.targetMappingId(),AdapterActionType.ISSUE_CREATE,Map.of("issueTitle",first(snapshot.summary(),"OpenDispatch Handoff "+relay.targetTaskId()),"issueDescription",description(snapshot),"taskType","HANDOFF","targetTaskId",relay.targetTaskId(),"sourceTaskId",relay.sourceTaskId()));return execute(action,relay.targetMappingId());}
 public IssueRelayProviderResult appendSourceBacklink(CrossProjectIssueRelay relay,String sourceIssueId,String targetIssueId,String targetIssueUrl){if(blank(sourceIssueId))return IssueRelayProviderResult.failure(false,null,"SOURCE_ISSUE_ID_REQUIRED","The source Issue is required for a source backlink.");String text="OpenDispatch created cross-project Task "+relay.targetTaskId()+" and target Issue "+targetIssueId+(blank(targetIssueUrl)?"":" ("+targetIssueUrl+")")+". Relay: "+relay.relayId();var action=action(relay,relay.sourceMappingId(),AdapterActionType.ISSUE_UPDATE_COMMENT,Map.of("linkedIssueId",sourceIssueId,"issueComment",text));return execute(action,relay.sourceMappingId());}
 public IssueRelayProviderResult appendTargetBacklink(CrossProjectIssueRelay relay,String sourceIssueId,String sourceIssueUrl,String targetIssueId){if(blank(targetIssueId))return IssueRelayProviderResult.failure(false,null,"TARGET_ISSUE_ID_REQUIRED","The target Issue is required for a target backlink.");String text="This Issue was derived from OpenDispatch Task "+relay.sourceTaskId()+(blank(sourceIssueId)?"":" and source Issue "+sourceIssueId)+(blank(sourceIssueUrl)?"":" ("+sourceIssueUrl+")")+". Root Task: "+relay.rootTaskId()+".";var action=action(relay,relay.targetMappingId(),AdapterActionType.ISSUE_UPDATE_COMMENT,Map.of("linkedIssueId",targetIssueId,"issueComment",text));return execute(action,relay.targetMappingId());}
 public IssueRelayProviderResult createNativeRelation(CrossProjectIssueRelay relay,String sourceIssueId,String targetIssueId){if(blank(sourceIssueId)||blank(targetIssueId))return IssueRelayProviderResult.failure(false,null,"ISSUE_RELAY_NATIVE_RELATION_UNAVAILABLE","Both source and target Issue identifiers are required.");IntegrationProjectMapping sm=identities.mapping(relay.tenantId(),relay.sourceMappingId()),tm=identities.mapping(relay.tenantId(),relay.targetMappingId());IntegrationConnection sc=identities.connection(relay.tenantId(),sm.connectionId()),tc=identities.connection(relay.tenantId(),tm.connectionId());if(!Objects.equals(sc.connectionId(),tc.connectionId())||sc.providerType()!=tc.providerType())return IssueRelayProviderResult.failure(false,null,"ISSUE_RELAY_NATIVE_RELATION_UNAVAILABLE","Native relations are unavailable across Provider Connections.");try{ScopedIntegrationExecutionContext ctx=identities.resolveExecutionContext(relay.tenantId(),sm.mappingId(),IntegrationOperation.RELATION);try(var secret=secrets.resolve(ctx.credential())){return switch(sc.providerType()){case JIRA -> jiraRelation(ctx,secret.reveal(),sourceIssueId,targetIssueId);case REDMINE -> redmineRelation(ctx,secret.reveal(),sourceIssueId,targetIssueId);default -> IssueRelayProviderResult.failure(false,null,"ISSUE_RELAY_NATIVE_RELATION_UNAVAILABLE","Provider does not expose a supported native relation API.");};}}catch(Exception e){return IssueRelayProviderResult.failure(false,null,"ISSUE_RELAY_NATIVE_RELATION_UNAVAILABLE",e.getMessage());}}
 private IssueRelayProviderResult execute(AdapterAction action,String mappingId){IntegrationProjectMapping m=identities.mapping(action.getPayload().get("tenantId").toString(),mappingId);IntegrationConnection c=identities.connection(m.tenantId(),m.connectionId());IssueVendor vendor=switch(c.providerType()){case JIRA->IssueVendor.JIRA;case REDMINE->IssueVendor.REDMINE;case GITLAB_ISSUES->IssueVendor.GITLAB;};AdapterExecutionResult r=execution.execute(action,vendor);return r.isSuccess()?new IssueRelayProviderResult(true,false,true,200,r.getIssueId(),r.getIssueUrl(),r.getResponseRef(),null):IssueRelayProviderResult.failure(r.isRetryable(),null,"ISSUE_RELAY_PROVIDER_FAILURE",r.getError());}
 private AdapterAction action(CrossProjectIssueRelay relay,String mapping,AdapterActionType type,Map<String,Object> extras){var p=new LinkedHashMap<String,Object>();p.put("tenantId",relay.tenantId());p.put("projectMappingId",mapping);p.put("correlationId",relay.correlationId());p.putAll(extras);var a=new AdapterAction();a.setActionId("relay-action-"+UUID.randomUUID());a.setIdempotencyKey(relay.idempotencyKey()+":"+type+":"+mapping+":"+extras.hashCode());a.setTaskId(relay.targetTaskId());a.setAdapterType(AdapterType.ISSUE_TRACKING);a.setActionType(type);a.setPayload(p);return a;}
 private IssueRelayProviderResult jiraRelation(ScopedIntegrationExecutionContext ctx,String secret,String source,String target)throws Exception{Map<String,Object> body=Map.of("type",Map.of("name","Relates"),"inwardIssue",Map.of("key",source),"outwardIssue",Map.of("key",target));HttpResponse<String> r=post(ctx,secret,"/rest/api/3/issueLink",json.writeValueAsString(body));return successOrFailure(r,"jira-relation:"+source+":"+target);}
 private IssueRelayProviderResult redmineRelation(ScopedIntegrationExecutionContext ctx,String secret,String source,String target)throws Exception{Map<String,Object> body=Map.of("relation",Map.of("issue_id",source,"issue_to_id",target,"relation_type","relates"));HttpResponse<String> r=post(ctx,secret,"/issue_relations.json",json.writeValueAsString(body));return successOrFailure(r,"redmine-relation:"+source+":"+target);}
 private HttpResponse<String> post(ScopedIntegrationExecutionContext ctx,String secret,String path,String body)throws Exception{String base=ctx.connection().baseUrl();if(base.endsWith("/"))base=base.substring(0,base.length()-1);var b=HttpRequest.newBuilder(URI.create(base+path)).timeout(Duration.ofMillis(Math.max(1000,ctx.connection().timeoutMs()))).header("Accept","application/json").header("Content-Type","application/json");auth(ctx,secret).forEach(b::header);return http.send(b.POST(HttpRequest.BodyPublishers.ofString(body)).build(),HttpResponse.BodyHandlers.ofString());}
 private Map<String,String> auth(ScopedIntegrationExecutionContext ctx,String secret){var h=new LinkedHashMap<String,String>();var c=ctx.credential();var p=ctx.principal();if((c.authType()==IntegrationAuthType.API_TOKEN||c.authType()==IntegrationAuthType.BASIC_PASSWORD)&&!blank(p.externalPrincipalIdentifier()))h.put("Authorization","Basic "+Base64.getEncoder().encodeToString((p.externalPrincipalIdentifier()+":"+secret).getBytes(StandardCharsets.UTF_8)));else h.put("Authorization","Bearer "+secret);if(ctx.connection().providerType()==IntegrationProviderType.REDMINE&&c.authType()==IntegrationAuthType.API_TOKEN)h.put("X-Redmine-API-Key",secret);return h;}
 private IssueRelayProviderResult successOrFailure(HttpResponse<String> r,String summary){if(r.statusCode()>=200&&r.statusCode()<300)return new IssueRelayProviderResult(true,false,true,r.statusCode(),null,null,summary,null);boolean retry=r.statusCode()==408||r.statusCode()==429||r.statusCode()>=500;return IssueRelayProviderResult.failure(retry,r.statusCode(),"ISSUE_RELAY_NATIVE_RELATION_UNAVAILABLE","Native relation returned "+r.statusCode()+".");}
 private String description(HandoffContextSnapshot s){StringBuilder b=new StringBuilder(first(s.summary(),"Cross-project handoff."));if(!s.structuredContext().isEmpty())b.append("\n\nApproved context:\n").append(s.structuredContext());if(!s.allowedCommentRefs().isEmpty())b.append("\n\nApproved comment references: ").append(s.allowedCommentRefs());return b.toString();} private String first(String a,String b){return blank(a)?b:a;} private boolean blank(String v){return v==null||v.isBlank();} public String mode(){return "SCOPED";}
}
