package com.opensocket.aievent.database.persistence.integrationidentity.dao;
import java.util.List; import org.apache.ibatis.annotations.*; import com.opensocket.aievent.database.persistence.integrationidentity.po.*; import com.opensocket.aievent.core.integration.identity.IntegrationResourceScope;
@Mapper public interface IntegrationIdentityDao {
 int upsertConnection(@Param("value")IntegrationConnectionPo value); IntegrationConnectionPo findConnection(@Param("tenantId")String tenantId,@Param("id")String id); List<IntegrationConnectionPo> listConnections(@Param("tenantId")String tenantId,@Param("limit")int limit); List<IntegrationConnectionPo> listConnectionsAuthorized(@Param("tenantId")String tenantId,@Param("scope")IntegrationResourceScope scope,@Param("limit")int limit);
 int upsertPrincipal(@Param("value")IntegrationPrincipalPo value); IntegrationPrincipalPo findPrincipal(@Param("tenantId")String tenantId,@Param("id")String id); List<IntegrationPrincipalPo> listPrincipals(@Param("tenantId")String tenantId,@Param("connectionId")String connectionId,@Param("limit")int limit); List<IntegrationPrincipalPo> listPrincipalsAuthorized(@Param("tenantId")String tenantId,@Param("connectionId")String connectionId,@Param("scope")IntegrationResourceScope scope,@Param("limit")int limit);
 int upsertCredential(@Param("value")IntegrationCredentialPo value); IntegrationCredentialPo findCredential(@Param("tenantId")String tenantId,@Param("id")String id); List<IntegrationCredentialPo> listCredentials(@Param("tenantId")String tenantId,@Param("principalId")String principalId,@Param("limit")int limit); List<IntegrationCredentialPo> listCredentialsAuthorized(@Param("tenantId")String tenantId,@Param("principalId")String principalId,@Param("scope")IntegrationResourceScope scope,@Param("limit")int limit);
 int insertProbeRun(@Param("run")IntegrationPermissionProbeRunPo run); int insertProbeResult(@Param("result")IntegrationPermissionProbeResultPo result); IntegrationPermissionProbeRunPo latestProbeRun(@Param("tenantId")String tenantId,@Param("principalId")String principalId,@Param("mappingId")String mappingId); List<IntegrationPermissionProbeResultPo> probeResults(@Param("tenantId")String tenantId,@Param("probeId")String probeId);
 int upsertRotationEvent(@Param("event")CredentialRotationEventPo event); List<CredentialRotationEventPo> listRotationEvents(@Param("tenantId")String tenantId,@Param("principalId")String principalId,@Param("limit")int limit);
 int upsertMapping(@Param("value")IntegrationProjectMappingPo value); IntegrationProjectMappingPo findMapping(@Param("tenantId")String tenantId,@Param("id")String id); List<IntegrationProjectMappingPo> listMappings(@Param("tenantId")String tenantId,@Param("connectionId")String connectionId,@Param("limit")int limit); List<IntegrationProjectMappingPo> listMappingsAuthorized(@Param("tenantId")String tenantId,@Param("connectionId")String connectionId,@Param("scope")IntegrationResourceScope scope,@Param("limit")int limit); List<IntegrationProjectMappingPo> resolutionCandidates(@Param("tenantId")String tenantId,@Param("connectionId")String connectionId);
 int insertMetadataSnapshot(@Param("value")ProviderMetadataSnapshotPo value); ProviderMetadataSnapshotPo findMetadataSnapshot(@Param("tenantId")String tenantId,@Param("snapshotId")String snapshotId); ProviderMetadataSnapshotPo latestMetadataSnapshot(@Param("tenantId")String tenantId,@Param("mappingId")String mappingId); List<ProviderMetadataSnapshotPo> listMetadataSnapshots(@Param("tenantId")String tenantId,@Param("mappingId")String mappingId,@Param("limit")int limit);
 int insertMappingVersion(@Param("value")IntegrationProjectMappingVersionPo value); IntegrationProjectMappingVersionPo findMappingVersion(@Param("tenantId")String tenantId,@Param("mappingId")String mappingId,@Param("mappingVersion")int mappingVersion); List<IntegrationProjectMappingVersionPo> listMappingVersions(@Param("tenantId")String tenantId,@Param("mappingId")String mappingId,@Param("limit")int limit);
 int upsertPrincipalScope(@Param("value")IntegrationPrincipalScopePo value); IntegrationPrincipalScopePo findPrincipalScope(@Param("tenantId")String tenantId,@Param("principalId")String principalId); List<IntegrationPrincipalScopePo> listPrincipalScopes(@Param("tenantId")String tenantId,@Param("connectionId")String connectionId,@Param("limit")int limit);
 int upsertSecurityOverride(@Param("value")IntegrationSecurityOverridePo value); IntegrationSecurityOverridePo findSecurityOverride(@Param("tenantId")String tenantId,@Param("overrideId")String overrideId); List<IntegrationSecurityOverridePo> listSecurityOverrides(@Param("tenantId")String tenantId,@Param("principalId")String principalId,@Param("mappingId")String mappingId,@Param("limit")int limit);
 int insertPermissionChangeEvent(@Param("value")IntegrationPermissionChangeEventPo value); List<IntegrationPermissionChangeEventPo> listPermissionChangeEvents(@Param("tenantId")String tenantId,@Param("principalId")String principalId,@Param("mappingId")String mappingId,@Param("limit")int limit);
 int upsertAuthorizationFailure(@Param("value")IntegrationProviderAuthorizationFailurePo value); List<IntegrationProviderAuthorizationFailurePo> listAuthorizationFailures(@Param("tenantId")String tenantId,@Param("mappingId")String mappingId,@Param("limit")int limit);
}
