package com.opensocket.aievent.core.a2a;

/** Stable blocker vocabulary for operations, reconciliation and API filtering. */
public enum A2ABlockerCode {
    NONE,
    APPROVAL_REQUIRED,
    CHILD_TASK_CREATION_PENDING,
    CHILD_TASK_CREATION_FAILED,
    HANDOFF_REQUIRED,
    DISPATCH_REQUEST_PENDING,
    DISPATCH_RETRY_WAITING,
    DISPATCH_FAILED,
    DISPATCH_TIMED_OUT,
    DISPATCH_DEAD_LETTER,
    NO_ELIGIBLE_AGENT,
    AGENT_UNAVAILABLE,
    ASSIGNMENT_EVIDENCE_MISSING,
    RESULT_EVIDENCE_MISSING,
    RESULT_QUARANTINED,
    CANCELLATION_UNCONFIRMED,
    POLICY_BINDING_INVALID,
    RECONCILIATION_REQUIRED,
    MANUAL_REVIEW_REQUIRED
}
