package com.opensocket.aievent.core.a2a;
public enum A2ARepairAction {
    RECONCILE_CHILD_TASK,
    RECONCILE_DISPATCH,
    RETRY_HANDOFF_RELEASE,
    RECONCILE_RESULT,
    RECOMPUTE_PARENT_AGGREGATION,
    RECONCILE_CANCELLATION,
    REBUILD_STATE_HISTORY,
    WAIT_HUMAN
}
