package com.opensocket.aievent.core.a2a;

public enum A2AReasonCode {
    A2A_LEGACY_ROUTING_RETIRED,
    A2A_CAPABILITY_DELEGATION_NOT_AVAILABLE,
    A2A_POLICY_NOT_FOUND,
    A2A_DIRECTION_NOT_ALLOWED,
    A2A_TASK_TYPE_NOT_ALLOWED,
    A2A_SERVICE_CODE_NOT_ALLOWED,
    A2A_CAPABILITY_NOT_ALLOWED,
    A2A_SENSITIVITY_EXCEEDED,
    A2A_HOP_LIMIT_EXCEEDED,
    A2A_CYCLE_DETECTED,
    A2A_RATE_LIMIT_EXCEEDED,
    A2A_APPROVAL_REQUIRED,
    REQUESTING_AGENT_NOT_CURRENT_ASSIGNEE,
    TARGET_POOL_NOT_FOUND,
    A2A_IDEMPOTENCY_CONFLICT,
    A2A_IDEMPOTENCY_IN_PROGRESS,
    A2A_REQUEST_EXPIRED,
    A2A_TARGET_SCOPE_NOT_ALLOWED,
    A2A_CROSS_SCOPE_AUTHORITY_REQUIRED,
    A2A_AGENT_RUNTIME_AUTHORIZATION_DENIED,
    A2A_MACHINE_IDENTITY_REQUIRED,
    A2A_MACHINE_TENANT_MISMATCH,
    A2A_AGENT_IDENTITY_MISMATCH,
    A2A_SOURCE_AGENT_NOT_ALLOWED,
    A2A_DELEGATION_CHAIN_INVALID
}
