package com.opensocket.aievent.core.a2a;
public enum A2AReconciliationCaseType {
    CHILD_TASK_CREATION_UNCERTAIN,
    DISPATCH_UNCERTAIN,
    HANDOFF_RELEASE_GAP,
    RESULT_PROCESSING_GAP,
    PARENT_AGGREGATION_MISSING,
    CANCELLATION_ACK_MISSING,
    STATE_HISTORY_GAP,
    OUTBOX_STUCK,
    UNKNOWN
}
