package com.opensocket.aievent.core.a2a;

public enum A2ATransitionFailureReason {
    ILLEGAL_SOURCE_STATE,
    COMMAND_TARGET_MISMATCH,
    EXPECTED_VERSION_REQUIRED,
    RESOURCE_VERSION_CONFLICT,
    APPROVAL_EXPIRED,
    TERMINAL_STATE_IMMUTABLE,
    BLOCKER_REQUIRED,
    EVIDENCE_REQUIRED,
    POLICY_BINDING_REQUIRED,
    POLICY_BINDING_HASH_MISMATCH,
    GUARD_REJECTED
}
