package com.opensocket.aievent.core.a2a;

public enum A2ATransitionEvidenceType {
    REQUEST_COMMAND,
    POLICY_DECISION,
    APPROVAL_EVIDENCE,
    TASK_AUTHORITY_RECEIPT,
    DISPATCH_AUTHORITY_RECEIPT,
    RUNTIME_EVIDENCE,
    RESULT_EVIDENCE,
    CANCELLATION_EVIDENCE,
    RECONCILIATION_EVIDENCE,
    TIME_EVIDENCE
}
