'use client';
import { createUuid } from '@/lib/utils/uuid';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { apiRequest } from '@/lib/api/client';

type Policy = { policyId:string; name:string; resourceType:string; direction:string; action:string; riskLevel:string; status:string; version:number; requiresReauthentication:boolean; requiresApproval:boolean; allowProviderMutation:boolean; };
type Candidate = { candidateId:string; conflictId?:string; externalIssueId:string; candidateType:string; riskLevel:string; status:string; requiresReauthentication:boolean; requiresApproval:boolean; reviewedBy?:string; approvedBy?:string; executionEvidence?:string; resolutionReason?:string; version:number; createdAt:string; updatedAt:string; };
type Sync = { syncId:string; connectionId:string; externalIssueId?:string; sourceExternalIssueId?:string; targetExternalIssueId?:string; direction:string; status:string; reasonCode?:string; safeMessage?:string; updatedAt:string; };
type Event = { eventId:string; eventType:string; actorId?:string; reasonCode:string; metadataJson:string; occurredAt:string; };

const terminal = new Set(['EXECUTED','REJECTED','SUPERSEDED']);

export function ExternalChangeGovernancePanel(){
  const [policies,setPolicies]=useState<Policy[]>([]); const [candidates,setCandidates]=useState<Candidate[]>([]);
  const [comments,setComments]=useState<Sync[]>([]); const [relations,setRelations]=useState<Sync[]>([]);
  const [events,setEvents]=useState<Record<string,Event[]>>({}); const [reason,setReason]=useState('');
  const [reauth,setReauth]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const [loading,setLoading]=useState(true); const [busy,setBusy]=useState('');
  const reasonValid=useMemo(()=>reason.trim().length>=12,[reason]);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [p,c,m,r]=await Promise.all([
    apiRequest<Policy[]>('/api/integrations/external-change-governance/policies?limit=200'),
    apiRequest<Candidate[]>('/api/integrations/external-change-governance/candidates?limit=200'),
    apiRequest<Sync[]>('/api/integrations/external-change-governance/comment-sync?limit=100'),
    apiRequest<Sync[]>('/api/integrations/external-change-governance/relation-sync?limit=100')]);
    setPolicies(p);setCandidates(c);setComments(m);setRelations(r);}catch(v){setError(v instanceof Error?v.message:'Unable to load external-change governance.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function candidateAction(item:Candidate,action:'review'|'approve'|'reject'|'execute'){
    if(!reasonValid||busy)return; if((action==='approve'||action==='execute')&&item.requiresReauthentication&&!reauth.trim()){setError('Reauthentication evidence is required.');return;}
    setBusy(`${action}:${item.candidateId}`);setError('');setMessage('');try{const headers:Record<string,string>={'If-Match':String(item.version)};if(action==='execute')headers['Idempotency-Key']=createUuid();
      await apiRequest(`/api/integrations/external-change-governance/candidates/${encodeURIComponent(item.candidateId)}/${action}`,{method:'POST',headers,body:{reason:reason.trim(),reauthenticationEvidence:reauth.trim()}});
      setMessage(action==='execute'?'Controlled command execution was requested; Task/A2A authority remains behind the command port.':`Candidate ${action} decision recorded.`);await load();
    }catch(v){setError(v instanceof Error?v.message:'Candidate action failed.');}finally{setBusy('');}}
  async function toggleEvents(id:string){if(events[id]){setEvents(v=>{const n={...v};delete n[id];return n;});return;}setBusy(`events:${id}`);try{const timeline=await apiRequest<Event[]>(`/api/integrations/external-change-governance/candidates/${encodeURIComponent(id)}/events?limit=200`);setEvents(v=>({...v,[id]:timeline}));}catch(v){setError(v instanceof Error?v.message:'Candidate timeline failed.');}finally{setBusy('');}}
  return <section className="rounded-2xl border border-violet-200 bg-white p-5" aria-labelledby="external-change-title">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="external-change-title" className="text-lg font-black text-slate-950">External Change and Bidirectional Sync Governance</h2><p className="mt-1 text-sm text-slate-600">Provider-neutral policies, loop-safe Comment/Relation synchronization, and reauthenticated Human Action Candidates. Provider assignee, close, approval, and high-risk field changes never directly become Task authority.</p></div><button type="button" onClick={()=>void load()} disabled={loading||!!busy} className="rounded-lg border px-3 py-2 text-sm font-bold disabled:opacity-50">Refresh</button></div>
    {message?<div role="status" className="mt-3 rounded-lg bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-800">{message}</div>:null}{error?<div role="alert" className="mt-3 rounded-lg bg-red-50 px-3 py-2 text-sm font-semibold text-red-800">{error}</div>:null}
    {loading?<div className="mt-5 rounded-xl bg-slate-50 p-5 text-sm text-slate-600">Loading policies, candidates, and synchronization evidence…</div>:<>
      <div className="mt-5 grid gap-3 md:grid-cols-4"><Summary label="Active policies" value={policies.filter(v=>v.status==='ACTIVE').length}/><Summary label="Open candidates" value={candidates.filter(v=>!terminal.has(v.status)).length}/><Summary label="Comment sync failures" value={comments.filter(v=>v.status.includes('FAILED')||v.status==='WAIT_HUMAN').length}/><Summary label="Relation sync failures" value={relations.filter(v=>v.status.includes('FAILED')||v.status==='WAIT_HUMAN').length}/></div>
      <div className="mt-6 overflow-x-auto"><h3 className="font-black text-slate-900">External Change Policies</h3><table className="mt-2 min-w-full text-left text-sm"><caption className="sr-only">External change policy matrix</caption><thead><tr className="border-b"><th scope="col" className="p-2">Policy</th><th scope="col" className="p-2">Resource / Direction</th><th scope="col" className="p-2">Decision</th><th scope="col" className="p-2">Governance</th><th scope="col" className="p-2">Status</th></tr></thead><tbody>{policies.length?policies.map(v=><tr key={v.policyId} className="border-b"><td className="p-2"><div className="font-semibold">{v.name}</div><div className="text-xs text-slate-500">{v.policyId}</div></td><td className="p-2">{v.resourceType}<div className="text-xs text-slate-500">{v.direction}</div></td><td className="p-2">{v.action}<div className="text-xs text-slate-500">Risk {v.riskLevel}</div></td><td className="p-2 text-xs">Reauth {v.requiresReauthentication?'required':'no'}<br/>Approval {v.requiresApproval?'required':'no'}<br/>Provider mutation {v.allowProviderMutation?'allowed':'blocked'}</td><td className="p-2">{v.status}<div className="text-xs text-slate-500">v{v.version}</div></td></tr>):<tr><td colSpan={5} className="p-5 text-center text-slate-500">No configured policies; secure defaults remain active.</td></tr>}</tbody></table></div>
      <div className="mt-6 overflow-x-auto"><h3 className="font-black text-slate-900">Human Action Candidates</h3><table className="mt-2 min-w-full text-left text-sm"><caption className="sr-only">Provider-originated actions awaiting controlled review and execution</caption><thead><tr className="border-b"><th scope="col" className="p-2">External Issue</th><th scope="col" className="p-2">Candidate</th><th scope="col" className="p-2">Controls</th><th scope="col" className="p-2">State</th><th scope="col" className="p-2">Actions</th></tr></thead><tbody>{candidates.length?candidates.map(v=><tr key={v.candidateId} className="border-b align-top"><td className="p-2"><div className="font-semibold">{v.externalIssueId}</div><div className="text-xs text-slate-500">{v.conflictId||'Webhook observation'}</div></td><td className="p-2">{v.candidateType}<div className="text-xs text-slate-500">Risk {v.riskLevel}</div>{events[v.candidateId]?<ol className="mt-2 space-y-1 border-l pl-3 text-xs">{events[v.candidateId].map(e=><li key={e.eventId}><span className="font-semibold">{e.eventType}</span> · {e.reasonCode}<br/><span className="text-slate-500">{e.occurredAt} · {e.actorId||'SYSTEM'}</span></li>)}</ol>:null}</td><td className="p-2 text-xs">Reauthentication {v.requiresReauthentication?'required':'not required'}<br/>Approval {v.requiresApproval?'required':'not required'}</td><td className="p-2">{v.status}<div className="text-xs text-slate-500">Version {v.version}</div></td><td className="p-2"><div className="flex min-w-44 flex-col gap-2"><button type="button" onClick={()=>void toggleEvents(v.candidateId)} disabled={!!busy} className="rounded-lg border px-2 py-1.5 font-bold disabled:opacity-50">{events[v.candidateId]?'Hide timeline':busy===`events:${v.candidateId}`?'Loading…':'Timeline'}</button>{!terminal.has(v.status)?<><button type="button" onClick={()=>void candidateAction(v,'review')} disabled={!reasonValid||!!busy} className="rounded-lg border px-2 py-1.5 font-bold disabled:opacity-50">Review</button><button type="button" onClick={()=>void candidateAction(v,'approve')} disabled={!reasonValid||!!busy} className="rounded-lg border px-2 py-1.5 font-bold disabled:opacity-50">Approve</button><button type="button" onClick={()=>void candidateAction(v,'reject')} disabled={!reasonValid||!!busy} className="rounded-lg border px-2 py-1.5 font-bold disabled:opacity-50">Reject</button><button type="button" onClick={()=>void candidateAction(v,'execute')} disabled={!reasonValid||!!busy} className="rounded-lg bg-violet-700 px-2 py-1.5 font-bold text-white disabled:opacity-50">Execute controlled command</button></>:null}</div></td></tr>):<tr><td colSpan={5} className="p-5 text-center text-slate-500">No Provider Action Candidates.</td></tr>}</tbody></table></div>
      <div className="mt-6 grid gap-5 xl:grid-cols-2"><SyncTable title="Comment synchronization" values={comments}/><SyncTable title="Relation synchronization" values={relations}/></div>
    </>}
    <div className="mt-5 grid gap-3 md:grid-cols-2"><label className="text-sm font-bold text-slate-700">Governance reason<textarea value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 min-h-24 w-full rounded-xl border p-3 font-normal" placeholder="Describe the evidence, affected authority, decision, and expected result."/></label><label className="text-sm font-bold text-slate-700">Reauthentication evidence<textarea value={reauth} onChange={e=>setReauth(e.target.value)} className="mt-1 min-h-24 w-full rounded-xl border p-3 font-normal" placeholder="Required for high-risk approval or controlled execution."/></label></div><p className={`mt-1 text-xs ${reason.length&&!reasonValid?'font-semibold text-red-700':'text-slate-500'}`}>Governance reason must contain at least 12 characters. Candidate execution remains fail-closed when no command adapter is available.</p>
  </section>;
}
function Summary({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-violet-100 bg-violet-50 p-4"><div className="text-2xl font-black text-violet-950">{value}</div><div className="text-xs font-semibold text-violet-800">{label}</div></div>}
function SyncTable({title,values}:{title:string;values:Sync[]}){return <div className="overflow-x-auto rounded-xl border p-4"><h3 className="font-black text-slate-900">{title}</h3><table className="mt-2 min-w-full text-left text-sm"><thead><tr className="border-b"><th scope="col" className="p-2">Object</th><th scope="col" className="p-2">Direction</th><th scope="col" className="p-2">Status</th></tr></thead><tbody>{values.length?values.map(v=><tr key={v.syncId} className="border-b"><td className="p-2">{v.externalIssueId||`${v.sourceExternalIssueId} → ${v.targetExternalIssueId}`}<div className="text-xs text-slate-500">{v.connectionId}</div></td><td className="p-2">{v.direction}</td><td className="p-2">{v.status}{v.reasonCode?<div className="text-xs text-red-700">{v.reasonCode}</div>:null}</td></tr>):<tr><td colSpan={3} className="p-4 text-center text-slate-500">No synchronization evidence.</td></tr>}</tbody></table></div>}
