'use client';
import { useMemo, useState } from 'react';
import { createProjectionIntent, previewProjectionIntent, type ProjectionIntentInput } from '@/lib/api/domains/issueProjectionApi';
import { PROJECTION_PURPOSES, issueProjectionCopy, type ProjectionIntentPreviewView, type ProjectionPurpose } from '@/lib/issueProjectionContract';
const initial=(connectionId:string):ProjectionIntentInput=>({taskId:'',taskType:'INCIDENT',sourceSystem:'ERP',connectionId,projectMappingId:'',projectionPurpose:'PRIMARY_ISSUE',mappingVersion:1,mappingSchemaHash:'',summary:'',description:'',issueType:'Task',priority:'',labels:[],components:[],approvedContext:{},sourceEvidence:{source:'operator-preview'},domainEventId:`preview-${Date.now()}`,operationSequence:1,expectedProjectionVersion:0});
function split(v:string){return v.split(',').map(x=>x.trim()).filter(Boolean);} function errorText(e:unknown){return e instanceof Error?e.message:'Operation failed.';}
export function ProjectionIntentContractPanel({connectionId}:{connectionId:string}){
 const [draft,setDraft]=useState<ProjectionIntentInput>(initial(connectionId)); const [preview,setPreview]=useState<ProjectionIntentPreviewView|null>(null); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const [contextText,setContextText]=useState('{}');
 const aggregate=useMemo(()=>[draft.taskId,draft.connectionId,draft.projectMappingId,draft.projectionPurpose].filter(Boolean).join(' · '),[draft]);
 async function runPreview(){setBusy(true);setMessage('');try{let approvedContext:Record<string,unknown>={};try{const parsed:unknown=JSON.parse(contextText);if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error('Approved Context must be a JSON object.');approvedContext=parsed as Record<string,unknown>;}catch(error){if(error instanceof Error&&error.message.includes('JSON object'))throw error;throw new Error('Approved Context must be valid JSON.');}const result=await previewProjectionIntent({...draft,connectionId:connectionId||draft.connectionId,approvedContext,domainEventId:draft.domainEventId||`preview-${Date.now()}`});setPreview(result);setMessage(result.accepted?'Canonical document accepted.':'Canonical document rejected.');}catch(e){setMessage(errorText(e));}finally{setBusy(false);}}
 async function persist(){if(!preview?.accepted)return;setBusy(true);setMessage('');try{const created=await createProjectionIntent({...draft,connectionId:connectionId||draft.connectionId,approvedContext:preview.document.approvedContext,domainEventId:draft.domainEventId||`intent-${Date.now()}`});setMessage(`Projection Intent ${created.projectionId} created at ${created.lifecycleStatus}.`);}catch(e){setMessage(errorText(e));}finally{setBusy(false);}}
 return <section className="rounded-2xl border border-cyan-200 bg-cyan-50 p-5" aria-labelledby="projection-intent-title">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 id="projection-intent-title" className="text-lg font-black text-cyan-950">Projection Intent Contract</h3><p className="mt-1 text-sm leading-6 text-cyan-900">{issueProjectionCopy.aggregateRule} {issueProjectionCopy.canonicalBoundary}</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-cyan-900">Schema v2</span></div>
  {message?<div role="status" className="mt-4 rounded-xl border border-cyan-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700">{message}</div>:null}
  <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
   <Field label="Task ID" value={draft.taskId} onChange={v=>setDraft({...draft,taskId:v})}/><Field label="Connection ID" value={connectionId||draft.connectionId} onChange={v=>setDraft({...draft,connectionId:v})} disabled={Boolean(connectionId)}/><Field label="Project Mapping ID" value={draft.projectMappingId} onChange={v=>setDraft({...draft,projectMappingId:v})}/><Field label="Mapping Schema Hash" value={draft.mappingSchemaHash} onChange={v=>setDraft({...draft,mappingSchemaHash:v})}/>
   <label className="text-sm font-bold text-slate-700">Projection Purpose<select value={draft.projectionPurpose} onChange={e=>setDraft({...draft,projectionPurpose:e.target.value as ProjectionPurpose})} className="mt-1 w-full rounded-xl border bg-white px-3 py-2">{PROJECTION_PURPOSES.map(v=><option key={v}>{v}</option>)}</select></label>
   <Field label="Issue Type" value={draft.issueType} onChange={v=>setDraft({...draft,issueType:v})}/><Field label="Summary" value={draft.summary} onChange={v=>setDraft({...draft,summary:v})}/><Field label="Priority" value={draft.priority??''} onChange={v=>setDraft({...draft,priority:v})}/>
  </div>
  <label className="mt-3 block text-sm font-bold text-slate-700">Description<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} className="mt-1 min-h-24 w-full rounded-xl border bg-white px-3 py-2 font-normal"/></label>
  <div className="mt-3 grid gap-3 md:grid-cols-2"><Field label="Labels (comma separated)" value={draft.labels.join(', ')} onChange={v=>setDraft({...draft,labels:split(v)})}/><Field label="Components (comma separated)" value={draft.components.join(', ')} onChange={v=>setDraft({...draft,components:split(v)})}/></div>
  <label className="mt-3 block text-sm font-bold text-slate-700">Approved Context JSON<textarea value={contextText} onChange={e=>setContextText(e.target.value)} className="mt-1 min-h-28 w-full rounded-xl border bg-white px-3 py-2 font-mono text-xs font-normal"/><span className="mt-1 block text-xs font-normal text-slate-500">Secret, credential, token, authorization, raw payload, and fencing fields are rejected recursively.</span></label>
  <div className="mt-4 flex flex-wrap gap-2"><button disabled={busy||!draft.taskId||!(connectionId||draft.connectionId)||!draft.projectMappingId||!draft.mappingSchemaHash||!draft.summary} onClick={runPreview} type="button" className="rounded-xl bg-cyan-800 px-4 py-2 font-black text-white disabled:opacity-50">Preview Canonical Document</button><button disabled={busy||!preview?.accepted} onClick={persist} type="button" className="rounded-xl border border-cyan-700 bg-white px-4 py-2 font-black text-cyan-900 disabled:opacity-50">Create Intent</button></div>
  {preview?<div className="mt-5 grid gap-4 xl:grid-cols-2"><div className="rounded-xl border border-cyan-200 bg-white p-4"><h4 className="font-black text-slate-950">Aggregate Binding</h4><dl className="mt-3 grid grid-cols-[auto_1fr] gap-x-3 gap-y-2 text-sm"><dt className="font-bold">Projection ID</dt><dd className="break-all font-mono text-xs">{preview.projectionId}</dd><dt className="font-bold">Aggregate</dt><dd>{aggregate}</dd><dt className="font-bold">Document Hash</dt><dd className="break-all font-mono text-xs">{preview.documentHash}</dd><dt className="font-bold">Mapping</dt><dd>v{preview.document.mappingVersion} · {preview.document.mappingSchemaHash}</dd></dl></div><div className="rounded-xl border border-cyan-200 bg-white p-4"><h4 className="font-black text-slate-950">Canonical ExternalIssueDocument</h4><pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap break-words rounded-lg bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(preview.document,null,2)}</pre>{preview.warnings.length?<ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-red-700">{preview.warnings.map(v=><li key={v}>{v}</li>)}</ul>:null}</div></div>:null}
 </section>;
}
function Field({label,value,onChange,disabled=false}:{label:string;value:string;onChange:(v:string)=>void;disabled?:boolean}){return <label className="text-sm font-bold text-slate-700">{label}<input disabled={disabled} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border bg-white px-3 py-2 font-normal disabled:bg-slate-100"/></label>;}
