package com.opensocket.aievent.database.persistence.integrationidentity;
import java.time.OffsetDateTime; import java.util.*; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import com.opensocket.aievent.core.integration.identity.*; import com.opensocket.aievent.database.persistence.integrationidentity.dao.IntegrationWebhookEndpointDao;
import com.opensocket.aievent.database.persistence.integrationidentity.po.IntegrationWebhookEndpointPo; import com.opensocket.aievent.database.persistence.spi.DatabaseRepositoryAdapter;
@DatabaseRepositoryAdapter @ConditionalOnProperty(prefix="integration-identity",name="store",havingValue="MYBATIS")
public class MybatisIntegrationWebhookEndpointRepository implements IntegrationWebhookEndpointRepository {
 private final IntegrationWebhookEndpointDao dao; public MybatisIntegrationWebhookEndpointRepository(IntegrationWebhookEndpointDao dao){this.dao=dao;}
 public IntegrationWebhookEndpoint save(IntegrationWebhookEndpoint v){if(dao.upsert(po(v))!=1)throw new IllegalStateException("WEBHOOK_ENDPOINT_VERSION_CONFLICT");return find(v.tenantId(),v.endpointId()).orElse(v);} public Optional<IntegrationWebhookEndpoint> find(String t,String id){return Optional.ofNullable(dao.find(t,id)).map(this::domain);} public Optional<IntegrationWebhookEndpoint> findByTokenHash(String h){return Optional.ofNullable(dao.findByTokenHash(h)).map(this::domain);} public List<IntegrationWebhookEndpoint> list(String t,String c,int n){return dao.list(t,c,n).stream().map(this::domain).toList();}
 public boolean reserveNonce(String t,String c,String e,String h,OffsetDateTime x,String corr){return dao.reserveNonce(t,c,e,h,x,corr)==1;} public int deleteExpiredNonces(OffsetDateTime b,int n){return dao.deleteExpiredNonces(b,n);} public String mode(){return "MYBATIS";}
 private IntegrationWebhookEndpointPo po(IntegrationWebhookEndpoint v){var p=new IntegrationWebhookEndpointPo();p.setTenantId(v.tenantId());p.setEndpointId(v.endpointId());p.setEndpointTokenHash(v.endpointTokenHash());p.setConnectionId(v.connectionId());p.setPrincipalId(v.principalId());p.setProviderType(v.providerType().name());p.setStatus(v.status().name());p.setSignatureAlgorithm(v.signatureAlgorithm());p.setMaxBodyBytes(v.maxBodyBytes());p.setRateLimitPerMinute(v.rateLimitPerMinute());p.setReplayWindowSeconds(v.replayWindowSeconds());p.setVersion(v.version());p.setCreatedAt(v.createdAt());p.setUpdatedAt(v.updatedAt());return p;}
 private IntegrationWebhookEndpoint domain(IntegrationWebhookEndpointPo p){return new IntegrationWebhookEndpoint(p.getTenantId(),p.getEndpointId(),p.getEndpointTokenHash(),p.getConnectionId(),p.getPrincipalId(),IntegrationProviderType.valueOf(p.getProviderType()),IntegrationWebhookEndpointStatus.valueOf(p.getStatus()),p.getSignatureAlgorithm(),p.getMaxBodyBytes(),p.getRateLimitPerMinute(),p.getReplayWindowSeconds(),p.getVersion(),p.getCreatedAt(),p.getUpdatedAt());}
}
