package com.opensocket.aievent.database.persistence.integrationidentity;
import java.util.*; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import com.opensocket.aievent.core.integration.identity.*; import com.opensocket.aievent.database.persistence.integrationidentity.dao.IntegrationIdentityDao; import com.opensocket.aievent.database.persistence.spi.DatabaseRepositoryAdapter;
@DatabaseRepositoryAdapter @ConditionalOnProperty(prefix="integration-identity",name="store",havingValue="MYBATIS")
public class MybatisIntegrationIdentityRepository implements IntegrationIdentityRepository {
 private final IntegrationIdentityDao dao; private final IntegrationIdentityPersistenceConverter c; public MybatisIntegrationIdentityRepository(IntegrationIdentityDao dao,IntegrationIdentityPersistenceConverter c){this.dao=dao;this.c=c;}
 public IntegrationConnection saveConnection(IntegrationConnection v){dao.upsertConnection(c.toPo(v));return findConnection(v.tenantId(),v.connectionId()).orElse(v);} public Optional<IntegrationConnection> findConnection(String t,String id){return Optional.ofNullable(dao.findConnection(t,id)).map(c::connection);} public List<IntegrationConnection> listConnections(String t,int n){return dao.listConnections(t,n).stream().map(c::connection).toList();} public List<IntegrationConnection> listConnectionsAuthorized(String t,IntegrationResourceScope scope,int n){return dao.listConnectionsAuthorized(t,scope,n).stream().map(c::connection).toList();}
 public IntegrationPrincipal savePrincipal(IntegrationPrincipal v){dao.upsertPrincipal(c.toPo(v));return findPrincipal(v.tenantId(),v.principalId()).orElse(v);} public Optional<IntegrationPrincipal> findPrincipal(String t,String id){return Optional.ofNullable(dao.findPrincipal(t,id)).map(c::principal);} public List<IntegrationPrincipal> listPrincipals(String t,String id,int n){return dao.listPrincipals(t,id,n).stream().map(c::principal).toList();} public List<IntegrationPrincipal> listPrincipalsAuthorized(String t,String id,IntegrationResourceScope scope,int n){return dao.listPrincipalsAuthorized(t,id,scope,n).stream().map(c::principal).toList();}
 public IntegrationCredentialMetadata saveCredential(IntegrationCredentialMetadata v){dao.upsertCredential(c.toPo(v));return findCredential(v.tenantId(),v.credentialId()).orElse(v);} public Optional<IntegrationCredentialMetadata> findCredential(String t,String id){return Optional.ofNullable(dao.findCredential(t,id)).map(c::credential);} public List<IntegrationCredentialMetadata> listCredentials(String t,String id,int n){return dao.listCredentials(t,id,n).stream().map(c::credential).toList();} public List<IntegrationCredentialMetadata> listCredentialsAuthorized(String t,String id,IntegrationResourceScope scope,int n){return dao.listCredentialsAuthorized(t,id,scope,n).stream().map(c::credential).toList();}
 public IntegrationProjectMapping saveMapping(IntegrationProjectMapping v){dao.upsertMapping(c.toPo(v));return findMapping(v.tenantId(),v.mappingId()).orElse(v);} public Optional<IntegrationProjectMapping> findMapping(String t,String id){return Optional.ofNullable(dao.findMapping(t,id)).map(c::mapping);} public List<IntegrationProjectMapping> listMappings(String t,String id,int n){return dao.listMappings(t,id,n).stream().map(c::mapping).toList();} public List<IntegrationProjectMapping> listMappingsAuthorized(String t,String id,IntegrationResourceScope scope,int n){return dao.listMappingsAuthorized(t,id,scope,n).stream().map(c::mapping).toList();} public List<IntegrationProjectMapping> resolutionCandidates(MappingResolutionRequest r){return dao.resolutionCandidates(r.tenantId(),r.connectionId()).stream().map(c::mapping).toList();}
 public PermissionProbeResult saveProbe(PermissionProbeResult v){dao.insertProbeRun(c.toRunPo(v));for(var row:c.toResultPos(v))dao.insertProbeResult(row);return v;} public Optional<PermissionProbeResult> latestProbe(String t,String p,String m){var run=dao.latestProbeRun(t,p,m);return run==null?Optional.empty():Optional.of(c.probe(run,dao.probeResults(t,run.getProbeId())));}
 public CredentialRotationEvent saveRotationEvent(CredentialRotationEvent v){dao.upsertRotationEvent(c.toPo(v));return v;} public List<CredentialRotationEvent> listRotationEvents(String t,String p,int n){return dao.listRotationEvents(t,p,n).stream().map(po->new CredentialRotationEvent(po.getTenantId(),po.getRotationEventId(),po.getPrincipalId(),po.getOldCredentialId(),po.getNewCredentialId(),po.getStatus(),po.getReason(),po.getCorrelationId(),po.getActorType(),po.getActorId(),po.getCreatedAt(),po.getGraceExpiresAt(),po.getActivatedAt(),po.getCompletedAt())).toList();}
 public IntegrationPrincipalScope savePrincipalScope(IntegrationPrincipalScope v){dao.upsertPrincipalScope(c.toPo(v));return findPrincipalScope(v.tenantId(),v.principalId()).orElse(v);} public Optional<IntegrationPrincipalScope> findPrincipalScope(String t,String p){return Optional.ofNullable(dao.findPrincipalScope(t,p)).map(c::principalScope);} public List<IntegrationPrincipalScope> listPrincipalScopes(String t,String connection,int n){return dao.listPrincipalScopes(t,connection,n).stream().map(c::principalScope).toList();}
 public IntegrationSecurityOverride saveSecurityOverride(IntegrationSecurityOverride v){dao.upsertSecurityOverride(c.toPo(v));return findSecurityOverride(v.tenantId(),v.overrideId()).orElse(v);} public Optional<IntegrationSecurityOverride> findSecurityOverride(String t,String id){return Optional.ofNullable(dao.findSecurityOverride(t,id)).map(c::securityOverride);} public List<IntegrationSecurityOverride> listSecurityOverrides(String t,String p,String m,int n){return dao.listSecurityOverrides(t,p,m,n).stream().map(c::securityOverride).toList();}
 public IntegrationPermissionChangeEvent savePermissionChangeEvent(IntegrationPermissionChangeEvent v){dao.insertPermissionChangeEvent(c.toPo(v));return v;} public List<IntegrationPermissionChangeEvent> listPermissionChangeEvents(String t,String p,String m,int n){return dao.listPermissionChangeEvents(t,p,m,n).stream().map(c::permissionChange).toList();}
 public IntegrationProviderAuthorizationFailure saveAuthorizationFailure(IntegrationProviderAuthorizationFailure v){dao.upsertAuthorizationFailure(c.toPo(v));return v;} public List<IntegrationProviderAuthorizationFailure> listAuthorizationFailures(String t,String m,int n){return dao.listAuthorizationFailures(t,m,n).stream().map(c::authorizationFailure).toList();}
 public ProviderMetadataSnapshot saveMetadataSnapshot(ProviderMetadataSnapshot v){dao.insertMetadataSnapshot(c.toPo(v));return findMetadataSnapshot(v.tenantId(),v.snapshotId()).orElse(v);} public Optional<ProviderMetadataSnapshot> findMetadataSnapshot(String t,String id){return Optional.ofNullable(dao.findMetadataSnapshot(t,id)).map(c::metadataSnapshot);} public Optional<ProviderMetadataSnapshot> latestMetadataSnapshot(String t,String m){return Optional.ofNullable(dao.latestMetadataSnapshot(t,m)).map(c::metadataSnapshot);} public List<ProviderMetadataSnapshot> listMetadataSnapshots(String t,String m,int n){return dao.listMetadataSnapshots(t,m,n).stream().map(c::metadataSnapshot).toList();}
 public IntegrationProjectMappingVersion saveMappingVersion(IntegrationProjectMappingVersion v){dao.insertMappingVersion(c.toPo(v));return findMappingVersion(v.tenantId(),v.mappingId(),v.mappingVersion()).orElse(v);} public Optional<IntegrationProjectMappingVersion> findMappingVersion(String t,String m,int v){return Optional.ofNullable(dao.findMappingVersion(t,m,v)).map(c::mappingVersion);} public List<IntegrationProjectMappingVersion> listMappingVersions(String t,String m,int n){return dao.listMappingVersions(t,m,n).stream().map(c::mappingVersion).toList();}
 public CredentialBlastRadius blastRadius(String t,String id){var credential=findCredential(t,id).orElseThrow();var principal=findPrincipal(t,credential.principalId()).orElseThrow();var projects=listMappings(t,principal.connectionId(),1000).stream().filter(v->java.util.stream.Stream.of(v.readPrincipalId(),v.createPrincipalId(),v.commentPrincipalId(),v.updatePrincipalId(),v.relationPrincipalId(),v.webhookPrincipalId()).filter(Objects::nonNull).anyMatch(principal.principalId()::equals)).map(IntegrationProjectMapping::externalProjectId).distinct().toList();return new CredentialBlastRadius(id,principal.principalId(),principal.connectionId(),principal.ownerDepartmentId(),principal.trustZoneId(),projects,0,credential.expiresAt(),credential.lastUsedAt());}
 public String mode(){return "MYBATIS";}
}
