import assert from 'node:assert/strict';
import test from 'node:test';
import { attachmentAvailability, backgroundJobExperience, bulkOperationPreview, classifyExportField, exportJobExperience, supportDiagnosticPreview, validateExportDraft } from '@/lib/phase7f/operationsExportAttachmentUx';

test('export preview omits secrets and masks fields above visibility',()=>{assert.equal(classifyExportField({field:'secret',classification:'SECRET',exportAllowed:true,visibilityGranted:'FULL'}).disposition,'OMITTED');assert.equal(classifyExportField({field:'description',classification:'SENSITIVE',exportAllowed:true,visibilityGranted:'STANDARD'}).disposition,'MASKED');});
test('export workflow never permits direct download',()=>{const result=validateExportDraft({resourceId:'task-1',format:'CSV',estimatedRowCount:100,purpose:'Operational evidence export for incident review',fields:[{field:'taskId',classification:'METADATA',exportAllowed:true,visibilityGranted:'STANDARD'}]});assert.equal(result.status,'READY');assert.equal(result.directDownloadAllowed,false);assert.equal(exportJobExperience('RUNNING',true).status,'REVOKED');});
test('attachment release requires clean scan, available content and enabled capability',()=>{assert.equal(attachmentAvailability({malwareStatus:'PENDING',contentAvailable:true,downloadCapability:'ENABLED'}).downloadAllowed,false);assert.equal(attachmentAvailability({malwareStatus:'CLEAN',contentAvailable:true,downloadCapability:'ENABLED'}).downloadAllowed,true);assert.equal(attachmentAvailability({malwareStatus:'INFECTED',contentAvailable:true,downloadCapability:'ENABLED'}).status,'DOWNLOAD_BLOCKED');});
test('background jobs require service principal, explicit resources, decisions and leases',()=>{assert.equal(backgroundJobExperience({servicePrincipal:true,explicitResourceCount:2,decisionCount:2,runtimeLeaseCount:2,executable:true}).ready,true);assert.equal(backgroundJobExperience({servicePrincipal:false,explicitResourceCount:2,decisionCount:1,runtimeLeaseCount:0,executable:false}).ready,false);});
test('bulk preview reconciles per-resource outcomes',()=>{const partial=bulkOperationPreview({selected:10,eligible:7,denied:1,locked:0,stale:1,requiresApproval:1,policy:'PARTIAL_ALLOWED'});assert.equal(partial.valid,true);assert.equal(partial.executable,true);assert.equal(partial.partial,true);});
test('support diagnostics ignore secret and raw payload values',()=>{const result=supportDiagnosticPreview({correlationIds:['a'],versions:['v1'],healthCategories:['health'],recentSafeEvents:['safe'],secretValues:['secret'],rawPayloads:['payload']});assert.equal(result.secretValueCountIgnored,1);assert.equal(result.rawPayloadCountIgnored,1);assert.ok(!JSON.stringify(result).includes('never-render'));});
