package com.opensocket.aievent.core.iam.persistence.repository;
import static com.opensocket.aievent.core.iam.persistence.repository.RowValues.*;import com.opensocket.aievent.core.iam.persistence.dao.IamTokenDao;import com.opensocket.aievent.core.iam.persistence.exception.IamOptimisticLockException;import com.opensocket.aievent.core.iam.security.contract.*;import com.opensocket.aievent.core.iam.token.application.port.out.AccessTokenRepository;import com.opensocket.aievent.core.iam.token.domain.*;import com.opensocket.aievent.database.persistence.spi.DatabaseRepositoryAdapter;import java.util.*;
@DatabaseRepositoryAdapter public class MybatisAccessTokenRepository implements AccessTokenRepository {
 private final IamTokenDao dao;public MybatisAccessTokenRepository(IamTokenDao dao){this.dao=dao;}
 public Optional<AccessToken> findById(String tenantId,TokenId id){return Optional.ofNullable(dao.findTokenById(tenantId,id.value())).map(this::domain);}
 public Optional<AccessToken> findByPrefix(String tenantId,String prefix){return Optional.ofNullable(dao.findTokenByPrefix(tenantId,prefix)).map(this::domain);}
 public Optional<String> findPersonalTenantByPrefix(String prefix){Map<String,Object> row=dao.findPersonalAccessTokenDirectory(prefix);return row==null?Optional.empty():Optional.ofNullable(string(row,"tenantId")).filter(v->!v.isBlank());}
 public AccessToken save(AccessToken t,long expected){int n=expected==0?dao.insertToken(row(t)):dao.updateToken(row(t),expected);if(n!=1)throw new IamOptimisticLockException("AccessToken",t.tokenId().value(),expected);return t;}
 public long countActive(String tenantId,PrincipalRef p,AccessTokenType type){return dao.countActiveTokens(tenantId,p.principalType().name(),p.principalId(),type.name());}
 public List<AccessToken> findActive(String tenantId,PrincipalRef p,AccessTokenType type){return dao.findActiveTokens(tenantId,p.principalType().name(),p.principalId(),type.name()).stream().map(this::domain).toList();}
 private AccessToken domain(Map<String,Object> x){TokenScope scope=new TokenScope(csv(x,"permissionsCsv"),csv(x,"audiencesCsv"),csv(x,"apiPrefixesCsv"),csv(x,"cidrsCsv"));SecurityEpoch epoch=new SecurityEpoch(longValue(x,"globalEpoch"),longValue(x,"tenantEpoch"),longValue(x,"principalEpoch"));return AccessToken.reconstitute(string(x,"tenantId"),new TokenId(string(x,"tokenId")),AccessTokenType.valueOf(string(x,"tokenType")),new PrincipalRef(PrincipalRef.PrincipalType.valueOf(string(x,"principalType")),string(x,"principalId")),string(x,"tokenName"),string(x,"tokenPrefix"),string(x,"last4"),new TokenHash(string(x,"hashAlgorithm"),string(x,"tokenHash")),scope,instant(x,"issuedAt"),instant(x,"expiresAt"),instant(x,"lastUsedAt"),string(x,"rotatedFromTokenId"),instant(x,"rotationGraceExpiresAt"),instant(x,"revokedAt"),string(x,"revokedBy"),string(x,"revocationReason"),instant(x,"consumedAt"),AccessTokenStatus.valueOf(string(x,"status")),epoch,longValue(x,"useCount"),longValue(x,"version"));}
 private Map<String,Object> row(AccessToken t){Map<String,Object>m=new HashMap<>();m.put("tenantId",t.tenantId());m.put("tokenId",t.tokenId().value());m.put("tokenType",t.type().name());m.put("principalType",t.principal().principalType().name());m.put("principalId",t.principal().principalId());m.put("tokenName",t.name());m.put("tokenPrefix",t.prefix());m.put("last4",t.last4());m.put("hashAlgorithm",t.secretHash().algorithm());m.put("tokenHash",t.secretHash().encoded());m.put("permissionsCsv",join(t.scope().permissions()));m.put("audiencesCsv",join(t.scope().audiences()));m.put("apiPrefixesCsv",join(t.scope().apiPrefixes()));m.put("cidrsCsv",join(t.scope().cidrs().stream().map(CidrBlock::notation).toList()));m.put("issuedAt",t.issuedAt());m.put("expiresAt",t.expiresAt());m.put("lastUsedAt",t.lastUsedAt());m.put("rotatedFromTokenId",t.rotatedFromTokenId().isBlank()?null:t.rotatedFromTokenId());m.put("rotationGraceExpiresAt",t.rotationGraceExpiresAt());m.put("revokedAt",t.revokedAt());m.put("revokedBy",t.revokedBy().isBlank()?null:t.revokedBy());m.put("revocationReason",t.revocationReason());m.put("consumedAt",t.consumedAt());m.put("status",t.status().name());m.put("globalEpoch",t.securityEpoch().globalEpoch());m.put("tenantEpoch",t.securityEpoch().tenantEpoch());m.put("principalEpoch",t.securityEpoch().principalEpoch());m.put("useCount",t.useCount());m.put("version",t.version());return m;}
}
