package com.opensocket.aievent.core.iam.persistence.repository;
import static com.opensocket.aievent.core.iam.persistence.repository.RowValues.*; import java.util.*;
import com.opensocket.aievent.core.iam.organization.application.port.out.DepartmentRevisionRepository; import com.opensocket.aievent.core.iam.organization.domain.*; import com.opensocket.aievent.core.iam.persistence.dao.IamTenantOrganizationDao; import com.opensocket.aievent.database.persistence.spi.DatabaseRepositoryAdapter;
@DatabaseRepositoryAdapter public class MybatisDepartmentRevisionRepository implements DepartmentRevisionRepository {
 private final IamTenantOrganizationDao dao; public MybatisDepartmentRevisionRepository(IamTenantOrganizationDao d){dao=d;}
 public Optional<DepartmentRevision> findCurrent(TenantId t,DepartmentId d){return Optional.ofNullable(dao.findCurrentDepartmentRevision(t.value(),d.value())).map(this::domain);}
 public DepartmentRevision save(DepartmentRevision v){if(v.validTo().isPresent()){int n=dao.closeCurrentDepartmentRevision(v.tenantId().value(),v.departmentId().value(),v.validTo().orElseThrow());if(n!=1)throw new IllegalStateException("DEPARTMENT_VERSION_CONFLICT: current revision missing");}else{if(dao.insertDepartmentRevision(row(v))!=1)throw new IllegalStateException("DEPARTMENT_REVISION_CONFLICT");}return v;}
 private DepartmentRevision domain(Map<String,Object>r){return new DepartmentRevision(new TenantId(string(r,"tenantId")),new DepartmentId(string(r,"departmentId")),longValue(r,"revision"),string(r,"departmentCode"),string(r,"departmentName"),Optional.ofNullable(string(r,"parentDepartmentId")).map(DepartmentId::new),csv(r,"ancestorPathIdsCsv").stream().map(DepartmentId::new).toList(),csv(r,"ancestorPathCodesCsv"),csv(r,"ancestorPathNamesCsv"),instant(r,"validFrom"),Optional.ofNullable(instant(r,"validTo")),DepartmentRevisionChangeType.valueOf(string(r,"changeType")),string(r,"changedBy"),string(r,"changeReason"),instant(r,"createdAt"));}
 private Map<String,Object> row(DepartmentRevision v){Map<String,Object>m=new HashMap<>();m.put("tenantId",v.tenantId().value());m.put("departmentId",v.departmentId().value());m.put("revision",v.revision());m.put("departmentCode",v.departmentCode());m.put("departmentName",v.departmentName());m.put("parentDepartmentId",v.parentDepartmentId().map(DepartmentId::value).orElse(null));m.put("ancestorPathIdsCsv",join(v.ancestorPathIds().stream().map(DepartmentId::value).toList()));m.put("ancestorPathCodesCsv",join(v.ancestorPathCodes()));m.put("ancestorPathNamesCsv",join(v.ancestorPathNames()));m.put("validFrom",v.validFrom());m.put("validTo",v.validTo().orElse(null));m.put("changeType",v.changeType().name());m.put("changedBy",v.changedBy());m.put("changeReason",v.changeReason());m.put("createdAt",v.createdAt());return m;}
}
