package com.opensocket.aievent.core.iam.persistence.repository;
import com.opensocket.aievent.core.iam.persistence.dao.IamTokenDao;import com.opensocket.aievent.core.iam.security.contract.PrincipalRef;import com.opensocket.aievent.core.iam.token.application.port.out.*;import com.opensocket.aievent.core.iam.token.domain.*;import com.opensocket.aievent.database.persistence.spi.DatabaseRepositoryAdapter;import java.time.*;import java.time.temporal.ChronoUnit;import java.util.*;
@DatabaseRepositoryAdapter public class MybatisTokenGovernanceAdapter implements TokenPermissionAuthorityPort,ServiceAccountOwnerPort,TokenPolicyRepository,TokenRateLimitPort,TokenUsageEvidencePort {
 private final IamTokenDao dao;private final Clock clock;public MybatisTokenGovernanceAdapter(IamTokenDao dao,Clock clock){this.dao=dao;this.clock=clock;}
 public Set<String> effectivePermissions(String tenantId,PrincipalRef p){return Set.copyOf(dao.findEffectivePermissions(tenantId,p.principalType().name(),p.principalId(),clock.instant()));}
 public void requireActivePrincipal(String tenantId,PrincipalRef p){if(dao.countActivePrincipal(tenantId,p.principalType().name(),p.principalId())!=1)throw new TokenDomainException(TokenReasonCode.AUTH_TOKEN_INVALID,"Principal is not active in Tenant");}
 public void requireEligibleOneTimeSubject(String tenantId,PrincipalRef p,AccessTokenType type){if(p.principalType()!=PrincipalRef.PrincipalType.USER||dao.countEligibleOneTimeSubject(tenantId,p.principalId(),type.name())!=1)throw new TokenDomainException(TokenReasonCode.AUTH_TOKEN_INVALID,"One-time token subject is not eligible");}
 public boolean isActiveOwner(String tenantId,String user,String department){return dao.countActiveOwner(tenantId,user,department)==1;}
 public TokenPolicy effectivePolicy(String tenantId){Map<String,Object>x=dao.findTokenPolicy(tenantId);if(x==null)return TokenPolicy.secureDefault();return new TokenPolicy(Duration.ofSeconds(RowValues.longValue(x,"personalDefaultTtlSeconds")),Duration.ofSeconds(RowValues.longValue(x,"personalMaxTtlSeconds")),Duration.ofSeconds(RowValues.longValue(x,"serviceDefaultTtlSeconds")),Duration.ofSeconds(RowValues.longValue(x,"serviceMaxTtlSeconds")),RowValues.intValue(x,"maxActivePersonalTokens"),RowValues.intValue(x,"maxActiveServiceTokens"),RowValues.bool(x,"requireServiceCidr"));}
 public boolean tryAcquire(String tenantId,String rateLimitKey,int limit,Instant at){return dao.tryAcquireRateLimit(tenantId,rateLimitKey,at.truncatedTo(ChronoUnit.MINUTES),limit);}
 public void append(String eventId,AccessToken t,String outcome,String reason,String audience,String apiPath,String sourceIp,Instant at,String correlation){Map<String,Object>m=new HashMap<>();m.put("eventId",eventId);m.put("tenantId",t.tenantId());m.put("tokenId",t.tokenId().value());m.put("tokenType",t.type().name());m.put("principalType",t.principal().principalType().name());m.put("principalId",t.principal().principalId());m.put("outcome",outcome);m.put("reasonCode",reason);m.put("audience",audience);m.put("apiPath",apiPath);m.put("sourceIp",sourceIp);m.put("occurredAt",at);m.put("correlationId",correlation);dao.insertUsageEvidence(m);}
}
