package com.opensocket.aievent.core.iam.persistence.repository;
import static com.opensocket.aievent.core.iam.persistence.repository.RowValues.*; import java.util.*;
import com.opensocket.aievent.core.iam.organization.application.port.out.OrganizationSnapshotRepository; import com.opensocket.aievent.core.iam.organization.domain.*; import com.opensocket.aievent.core.iam.persistence.dao.IamTenantOrganizationDao; import com.opensocket.aievent.database.persistence.spi.DatabaseRepositoryAdapter;
@DatabaseRepositoryAdapter public class MybatisOrganizationSnapshotRepository implements OrganizationSnapshotRepository {
 private final IamTenantOrganizationDao dao; public MybatisOrganizationSnapshotRepository(IamTenantOrganizationDao d){dao=d;}
 public OrganizationSnapshot saveIfAbsentByContentHash(OrganizationSnapshot v){dao.insertSnapshot(row(v));return Optional.ofNullable(dao.findSnapshotByHash(v.tenantId().value(),v.contentHash())).map(this::domain).orElseThrow();}
 private OrganizationSnapshot domain(Map<String,Object>r){return new OrganizationSnapshot(new SnapshotId(string(r,"snapshotId")),new TenantId(string(r,"tenantId")),new DepartmentId(string(r,"departmentId")),longValue(r,"departmentRevision"),string(r,"departmentCode"),string(r,"departmentName"),csv(r,"ancestorPathIdsCsv").stream().map(DepartmentId::new).toList(),csv(r,"ancestorPathCodesCsv"),csv(r,"ancestorPathNamesCsv"),csv(r,"groupIdsCsv").stream().filter(s->!s.isBlank()).map(GroupId::new).collect(java.util.stream.Collectors.toUnmodifiableSet()),instant(r,"capturedAt"),string(r,"contentHash"));}
 private Map<String,Object> row(OrganizationSnapshot v){Map<String,Object>m=new HashMap<>();m.put("snapshotId",v.snapshotId().value());m.put("tenantId",v.tenantId().value());m.put("departmentId",v.departmentId().value());m.put("departmentRevision",v.departmentRevision());m.put("departmentCode",v.departmentCode());m.put("departmentName",v.departmentName());m.put("ancestorPathIdsCsv",join(v.ancestorPathIds().stream().map(DepartmentId::value).toList()));m.put("ancestorPathCodesCsv",join(v.ancestorPathCodes()));m.put("ancestorPathNamesCsv",join(v.ancestorPathNames()));m.put("groupIdsCsv",join(v.groupIds().stream().map(GroupId::value).sorted().toList()));m.put("capturedAt",v.capturedAt());m.put("contentHash",v.contentHash());return m;}
}
