package com.opensocket.aievent.core.iam.persistence.repository;
import static com.opensocket.aievent.core.iam.persistence.repository.RowValues.*;
import com.opensocket.aievent.core.iam.persistence.dao.IamRbacDao;
import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantContextHolder;
import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantExecutionContext;
import com.opensocket.aievent.core.iam.rbac.application.command.manifest.RegisterApplicationPermissionManifestCommand;
import com.opensocket.aievent.core.iam.rbac.application.command.shadow.*;
import com.opensocket.aievent.core.iam.rbac.application.port.out.EntryPointAuthorityRepository;
import com.opensocket.aievent.core.iam.rbac.domain.entrypoint.*;
import com.opensocket.aievent.core.iam.rbac.domain.manifest.*;
import com.opensocket.aievent.core.iam.rbac.domain.shadow.*;
import com.opensocket.aievent.database.persistence.spi.DatabaseRepositoryAdapter;
import java.math.BigDecimal;
import java.time.*;import java.util.*;import java.util.function.Supplier;
@DatabaseRepositoryAdapter
public class MybatisEntryPointAuthorityRepository implements EntryPointAuthorityRepository {
 private final IamRbacDao dao;public MybatisEntryPointAuthorityRepository(IamRbacDao dao){this.dao=dao;}
 @Override public List<EntryPointAuthorityRecord> findEntries(String t,String s,String o,int l){return instance(()->dao.findEntryPoints(t,s,o,l).stream().map(this::entry).toList());}
 @Override public Optional<EntryPointAuthorityRecord> findEntry(String id){return instance(()->Optional.ofNullable(dao.findEntryPoint(id)).map(this::entry));}
 @Override public EntryPointBurnDownSummary summary(){return instance(()->{Map<String,Object> r=dao.summarizeEntryPoints();Map<String,Long> by=new LinkedHashMap<>();for(String s:List.of("LEGACY_ONLY","DUAL_SHADOW","TARGET_READY","TARGET_ONLY","EXEMPT"))by.put(s,longValue(r,toCamel(s)));return new EntryPointBurnDownSummary(longValue(r,"total"),by,longValue(r,"unknownPermissions"),longValue(r,"missingMappings"),longValue(r,"missingResolvers"),longValue(r,"overdue"),longValue(r,"activeBypasses"),longValue(r,"expiredBypasses"),longValue(r,"cutoverBlockers"));});}
 @Override public List<LegacyAuthorityMapping> findMappings(String s,int l){return instance(()->dao.findLegacyAuthorityMappings(s,l).stream().map(this::mapping).toList());}
 @Override public Optional<LegacyAuthorityMapping> findMapping(String id){return instance(()->Optional.ofNullable(dao.findLegacyAuthorityMapping(id)).map(this::mapping));}
 @Override public List<EntryPointBypass> findBypasses(String s,int l){return instance(()->dao.findEntryPointBypasses(s,l).stream().map(this::bypass).toList());}
 @Override public Optional<EntryPointBypass> findBypass(String id){return instance(()->Optional.ofNullable(dao.findEntryPointBypass(id)).map(this::bypass));}
 @Override public boolean updateEntryPoint(EntryPointAuthorityRecord v,long x,String a,String c,String reason){return instance(()->{context(a,c,reason);return dao.updateEntryPoint(entryRow(v),x)==1;});}
 @Override public boolean updateMapping(LegacyAuthorityMapping v,long x,String a,String c,String reason){return instance(()->{context(a,c,reason);return dao.updateLegacyAuthorityMapping(mappingRow(v),x)==1;});}
 @Override public void insertBypass(EntryPointBypass v,String c,String reason){instance(()->{context(v.createdBy(),c,reason);if(dao.insertEntryPointBypass(bypassRow(v))!=1)throw new IllegalStateException("ENTRY_POINT_BYPASS_CREATE_FAILED");return null;});}
 @Override public boolean revokeBypass(String id,long x,String a,String reason,Instant at,String c,String audit){return instance(()->{context(a,c,audit);return dao.revokeEntryPointBypass(id,x,a,reason,at)==1;});}
 @Override public List<ApplicationPermissionManifest> findApplicationManifests(int limit){return instance(()->dao.findApplicationManifests(limit).stream().map(this::manifest).toList());}
 @Override public Optional<ApplicationPermissionManifest> findApplicationManifest(String id){return instance(()->Optional.ofNullable(dao.findApplicationManifest(id)).map(this::manifest));}
 @Override public List<ApplicationPermissionManifestEntry> findApplicationManifestEntries(String id,String drift,int limit){return instance(()->dao.findApplicationManifestEntries(id,drift,limit).stream().map(this::manifestEntry).toList());}
 @Override public PermissionManifestDriftSummary summarizeManifestDrift(String id){return instance(()->{Map<String,Object> r=dao.summarizeApplicationManifestDrift(id);if(r==null)throw new IllegalStateException("PERMISSION_MANIFEST_NOT_FOUND");return new PermissionManifestDriftSummary(string(r,"manifestId"),longValue(r,"total"),longValue(r,"matching"),longValue(r,"sourceChanged"),longValue(r,"descriptorChanged"),longValue(r,"unregisteredSource"),longValue(r,"staleManifest"),longValue(r,"unknownPermission"),longValue(r,"retiredPermission"),longValue(r,"missingResolver"),longValue(r,"blockers"));});}
 @Override public List<PermissionCoverageEvidence> findCoverageEvidence(int limit){return instance(()->dao.findPermissionCoverageEvidence(limit).stream().map(this::coverageEvidence).toList());}
 @Override public ApplicationPermissionManifest registerManifest(RegisterApplicationPermissionManifestCommand c){
  return instance(()->{
   context(c.actorId(),c.correlationId(),c.auditReason());
   if(dao.insertApplicationManifest(manifestRow(c))!=1)throw new IllegalStateException("PERMISSION_MANIFEST_CATALOG_BINDING_MISMATCH");
   for(PermissionManifestRegistrationEntry e:c.entries())if(dao.insertApplicationManifestEntry(manifestEntryRow(c.manifestId(),e))!=1)throw new IllegalStateException("PERMISSION_MANIFEST_ENTRY_CREATE_FAILED");
   dao.activateApplicationManifest(c.manifestId(),c.actorId(),c.correlationId(),c.auditReason());
   return Optional.ofNullable(dao.findApplicationManifest(c.manifestId())).map(this::manifest).orElseThrow(()->new IllegalStateException("PERMISSION_MANIFEST_NOT_FOUND"));
  });
 }
 @Override public List<ShadowObservation> findShadowObservations(String tenantId,String domainCode,String category,int limit){return dao.findShadowObservations(tenantId,domainCode,category,limit).stream().map(this::shadowObservation).toList();}
 @Override public ShadowObservationSummary summarizeShadowObservations(String tenantId,String domainCode){Map<String,Object> r=dao.summarizeShadowObservations(tenantId,domainCode);Map<String,Long> by=new LinkedHashMap<>();for(String k:List.of("MATCH","UNEXPECTED_ALLOW","SCOPE_WIDENED","VISIBILITY_WIDENED","TARGET_ERROR","CONTEXT_INCOMPLETE","UNEXPECTED_DENY","REASON_DIFFERENT","LEGACY_UNAVAILABLE"))by.put(k,longValue(r,toCamel(k)));return new ShadowObservationSummary(longValue(r,"total"),by,longValue(r,"critical"),longValue(r,"openCases"),longValue(r,"overdueCases"),longValue(r,"activeWaivers"),longValue(r,"cutoverBlockers"));}
 @Override public Optional<ShadowObservation> findShadowObservation(String tenantId,String comparisonId){return Optional.ofNullable(dao.findShadowObservation(tenantId,comparisonId)).map(this::shadowObservation);}
 @Override public List<ShadowMismatchCase> findMismatchCases(String tenantId,String domainCode,String status,int limit){return dao.findShadowMismatchCases(tenantId,domainCode,status,limit).stream().map(this::shadowCase).toList();}
 @Override public Optional<ShadowMismatchCase> findMismatchCase(String caseId){return Optional.ofNullable(dao.findShadowMismatchCase(caseId)).map(this::shadowCase);}
 @Override public void insertMismatchCase(ShadowMismatchCase v,String correlationId,String auditReason){context(v.createdBy(),correlationId,auditReason);if(dao.insertShadowMismatchCase(shadowCaseRow(v))!=1)throw new IllegalStateException("MISMATCH_CASE_CREATE_FAILED");}
 @Override public boolean updateMismatchCase(ShadowMismatchCase v,long expectedVersion,String correlationId,String auditReason){context(v.updatedBy(),correlationId,auditReason);return dao.updateShadowMismatchCase(shadowCaseRow(v),expectedVersion)==1;}
 @Override public ShadowMismatchWaiver insertMismatchWaiver(CreateMismatchWaiverCommand c){context(c.actorId(),c.correlationId(),c.auditReason());Map<String,Object> r=new HashMap<>();r.put("waiverId",c.waiverId());r.put("caseId",c.caseId());r.put("reason",c.reason());r.put("approvedBy",c.actorId());r.put("approvedAt",c.requestedAt());r.put("expiresAt",c.expiresAt());if(dao.insertShadowMismatchWaiver(r)!=1)throw new IllegalStateException("MISMATCH_WAIVER_CREATE_FAILED");return shadowWaiver(dao.findShadowMismatchWaiver(c.waiverId()));}
 @Override public ShadowRegressionEvidence insertRegressionEvidence(AddRegressionEvidenceCommand c){context(c.actorId(),c.correlationId(),c.auditReason());Map<String,Object> r=new HashMap<>();r.put("evidenceId",c.evidenceId());r.put("caseId",c.caseId());r.put("testReference",c.testReference());r.put("result",c.result());r.put("detailsJson",c.detailsJson()==null||c.detailsJson().isBlank()?"{}":c.detailsJson());r.put("executedAt",c.executedAt());r.put("executedBy",c.actorId());if(dao.insertShadowRegressionEvidence(r)!=1)throw new IllegalStateException("REGRESSION_EVIDENCE_CREATE_FAILED");return regression(dao.findShadowRegressionEvidence(c.evidenceId()));}
 @Override public List<DomainReadinessEvidence> findDomainReadiness(String tenantId,String domainCode,int limit){return dao.findDomainReadinessEvidence(tenantId,domainCode,limit).stream().map(this::domainReadiness).toList();}
 @Override public DomainReadinessEvidence evaluateDomainReadiness(EvaluateDomainReadinessCommand c){context(c.actorId(),c.correlationId(),c.auditReason());String id=dao.evaluateDomainReadiness(c.tenantId(),c.domainCode().toUpperCase(Locale.ROOT),c.windowStartedAt(),c.windowEndedAt(),c.actorId(),c.correlationId(),c.auditReason());return domainReadiness(dao.findDomainReadinessEvidenceById(id));}
 @Override public List<Phase6EligibilityEvidence> findPhase6Eligibility(String tenantId,int limit){return dao.findPhase6EligibilityEvidence(tenantId,limit).stream().map(this::phase6).toList();}
 @Override public Phase6EligibilityEvidence evaluatePhase6Eligibility(EvaluatePhase6EligibilityCommand c){context(c.actorId(),c.correlationId(),c.auditReason());String id=dao.evaluatePhase6Eligibility(c.tenantId(),c.actorId(),c.correlationId(),c.auditReason());return phase6(dao.findPhase6EligibilityEvidenceById(id));}
 @Override public ShadowPipelineReadiness shadowPipelineReadiness(){return pipeline(dao.findShadowPipelineReadiness());}
 @Override public ShadowStorageReadiness shadowStorageReadiness(){return storage(dao.findShadowStorageReadiness());}
 @Override public List<ShadowRetentionRun> shadowRetentionRuns(int limit){return dao.findShadowRetentionRuns(limit).stream().map(this::retention).toList();}
 @Override public String processShadowPipeline(String workerId,int batchSize,String actorId,String correlationId,String auditReason){return dao.processShadowPipeline(workerId,batchSize,actorId,correlationId,auditReason);}
 @Override public ShadowRetentionRun runShadowRetention(RunShadowRetentionCommand c){context(c.actorId(),c.correlationId(),c.auditReason());String id=dao.runShadowRetention(c.actorId(),c.auditReason(),c.correlationId());return retention(dao.findShadowRetentionRun(id));}
 @Override public List<Phase5RuntimeCertificationEvidence> phase5RuntimeCertificationEvidence(int limit){return dao.findPhase5RuntimeCertificationEvidence(limit).stream().map(this::runtimeEvidence).toList();}
 @Override public Phase5RuntimeCertificationEvidence generatePhase5RuntimeCertificationEvidence(GeneratePhase5RuntimeCertificationCommand c){context(c.actorId(),c.correlationId(),c.auditReason());String id=dao.generatePhase5RuntimeCertificationEvidence(c.sourceVersion(),c.postgresqlCleanStatus(),c.postgresqlUpgradeStatus(),c.applicationContextStatus(),c.adminUiBuildStatus(),c.playwrightStatus(),c.loadTestStatus(),c.pipelineStatus(),c.evidenceJson(),c.actorId(),c.auditReason(),c.correlationId());return runtimeEvidence(dao.findPhase5RuntimeCertificationEvidenceById(id));}
 private <T>T instance(Supplier<T> action){return IamTenantContextHolder.withContext(new IamTenantExecutionContext("INSTANCE","permission-readiness"),action);}
 private void context(String actor,String correlation,String reason){dao.setPermissionReadinessContext(actor,correlation,reason);}
 private ShadowObservation shadowObservation(Map<String,Object> r){return new ShadowObservation(string(r,"tenantId"),string(r,"comparisonId"),string(r,"domainCode"),opt(r,"entryPointId"),string(r,"resourceType"),string(r,"resourceId"),string(r,"permissionCode"),string(r,"legacyEffect"),string(r,"legacyScope"),string(r,"legacyVisibility"),string(r,"legacyReasonCode"),bool(r,"legacyContextComplete"),string(r,"targetEffect"),string(r,"targetScope"),string(r,"targetVisibility"),string(r,"targetReasonCode"),bool(r,"targetContextComplete"),string(r,"category"),string(r,"severity"),string(r,"riskLane"),string(r,"protectionMode"),string(r,"correlationId"),instant(r,"comparedAt"),opt(r,"caseId"),opt(r,"caseStatus"),opt(r,"ownerId"),Optional.ofNullable(instant(r,"slaDueAt")),bool(r,"activeWaiver"),bool(r,"cutoverBlocker"));}
 private ShadowMismatchCase shadowCase(Map<String,Object> r){return new ShadowMismatchCase(string(r,"caseId"),string(r,"sourceTenantId"),string(r,"comparisonId"),string(r,"domainCode"),opt(r,"entryPointId"),string(r,"permissionCode"),string(r,"category"),string(r,"severity"),string(r,"status"),string(r,"ownerId"),instant(r,"slaDueAt"),string(r,"title"),opt(r,"resolution"),instant(r,"firstSeenAt"),instant(r,"lastSeenAt"),longValue(r,"occurrenceCount"),instant(r,"createdAt"),string(r,"createdBy"),instant(r,"updatedAt"),string(r,"updatedBy"),longValue(r,"version"),bool(r,"activeWaiver"),longValue(r,"regressionPassed"),longValue(r,"regressionFailed"));}
 private ShadowMismatchWaiver shadowWaiver(Map<String,Object> r){return new ShadowMismatchWaiver(string(r,"waiverId"),string(r,"caseId"),string(r,"reason"),string(r,"approvedBy"),instant(r,"approvedAt"),instant(r,"expiresAt"),string(r,"status"),Optional.ofNullable(instant(r,"revokedAt")),opt(r,"revokedBy"),longValue(r,"version"));}
 private ShadowRegressionEvidence regression(Map<String,Object> r){return new ShadowRegressionEvidence(string(r,"evidenceId"),string(r,"caseId"),string(r,"testReference"),string(r,"result"),string(r,"detailsJson"),instant(r,"executedAt"),string(r,"executedBy"),instant(r,"createdAt"));}
 private DomainReadinessEvidence domainReadiness(Map<String,Object> r){return new DomainReadinessEvidence(string(r,"evidenceId"),string(r,"sourceTenantId"),string(r,"domainCode"),string(r,"status"),instant(r,"windowStartedAt"),instant(r,"windowEndedAt"),longValue(r,"sampleCount"),longValue(r,"matchCount"),longValue(r,"unexpectedAllowCount"),longValue(r,"scopeWidenedCount"),longValue(r,"visibilityWidenedCount"),longValue(r,"targetErrorCount"),longValue(r,"contextIncompleteCount"),longValue(r,"unexpectedDenyCount"),longValue(r,"reasonDifferentCount"),longValue(r,"openBlockingCases"),longValue(r,"activeWaivers"),longValue(r,"failedRegressions"),decimal(r,"manifestCoveragePercent"),longValue(r,"runtimeDriftBlockers"),longValue(r,"entryPointBlockers"),longValue(r,"expiredBypasses"),string(r,"blockersJson"),string(r,"catalogRevisionId"),opt(r,"manifestId"),string(r,"actorId"),string(r,"auditReason"),opt(r,"correlationId"),instant(r,"evaluatedAt"));}
 private ShadowPipelineReadiness pipeline(Map<String,Object> r){return new ShadowPipelineReadiness(longValue(r,"pendingCount"),longValue(r,"processingCount"),longValue(r,"readyCount"),longValue(r,"oldestPendingSeconds"),longValue(r,"deadLetters24h"),longValue(r,"dropped24h"),longValue(r,"retries24h"),longValue(r,"processed24h"),longValue(r,"queueCapacity"),bool(r,"enabled"));}
 private ShadowStorageReadiness storage(Map<String,Object> r){return new ShadowStorageReadiness(longValue(r,"durableMismatchRows"),longValue(r,"sampledMatchRows"),longValue(r,"metricRows"),longValue(r,"receiptRows"),longValue(r,"archivedPartitions"),longValue(r,"overdueArchivePurges"),longValue(r,"durablePartitions"),longValue(r,"sampledPartitions"),longValue(r,"deadLetterPartitions"),Optional.ofNullable(instant(r,"lastRetentionCompletedAt")));}
 private ShadowRetentionRun retention(Map<String,Object> r){return new ShadowRetentionRun(string(r,"runId"),string(r,"status"),longValue(r,"metricsDeleted"),longValue(r,"receiptsDeleted"),longValue(r,"deadLettersDeleted"),intValue(r,"partitionsArchived"),intValue(r,"partitionsPurged"),string(r,"detailsJson"),instant(r,"startedAt"),Optional.ofNullable(instant(r,"completedAt")),string(r,"actorId"),string(r,"auditReason"),opt(r,"correlationId"));}
 private Phase5RuntimeCertificationEvidence runtimeEvidence(Map<String,Object> r){return new Phase5RuntimeCertificationEvidence(string(r,"evidenceId"),string(r,"status"),string(r,"sourceVersion"),string(r,"catalogRevisionId"),opt(r,"manifestId"),string(r,"postgresqlCleanStatus"),string(r,"postgresqlUpgradeStatus"),string(r,"applicationContextStatus"),string(r,"adminUiBuildStatus"),string(r,"playwrightStatus"),string(r,"loadTestStatus"),string(r,"pipelineStatus"),string(r,"evidenceJson"),string(r,"actorId"),string(r,"auditReason"),opt(r,"correlationId"),instant(r,"generatedAt"));}
 private Phase6EligibilityEvidence phase6(Map<String,Object> r){return new Phase6EligibilityEvidence(string(r,"evidenceId"),string(r,"sourceTenantId"),string(r,"status"),string(r,"requiredDomainsJson"),string(r,"domainEvidenceRefsJson"),longValue(r,"eligibleDomains"),longValue(r,"blockedDomains"),longValue(r,"observingDomains"),string(r,"catalogRevisionId"),opt(r,"manifestId"),decimal(r,"manifestCoveragePercent"),longValue(r,"runtimeDriftBlockers"),longValue(r,"entryPointBlockers"),longValue(r,"expiredBypasses"),longValue(r,"openBlockingCases"),string(r,"blockersJson"),string(r,"actorId"),string(r,"auditReason"),opt(r,"correlationId"),instant(r,"evaluatedAt"));}
 private Map<String,Object> shadowCaseRow(ShadowMismatchCase v){Map<String,Object> r=new HashMap<>();r.put("caseId",v.caseId());r.put("sourceTenantId",v.sourceTenantId());r.put("comparisonId",v.comparisonId());r.put("domainCode",v.domainCode());r.put("entryPointId",v.entryPointId().orElse(""));r.put("permissionCode",v.permissionCode());r.put("category",v.category());r.put("severity",v.severity());r.put("status",v.status());r.put("ownerId",v.ownerId());r.put("slaDueAt",v.slaDueAt());r.put("title",v.title());r.put("resolution",v.resolution().orElse(""));r.put("firstSeenAt",v.firstSeenAt());r.put("lastSeenAt",v.lastSeenAt());r.put("occurrenceCount",v.occurrenceCount());r.put("createdAt",v.createdAt());r.put("createdBy",v.createdBy());r.put("updatedAt",v.updatedAt());r.put("updatedBy",v.updatedBy());r.put("version",v.version());return r;}
 private EntryPointAuthorityRecord entry(Map<String,Object> r){return new EntryPointAuthorityRecord(string(r,"entryPointId"),EntryPointType.valueOf(string(r,"entryPointType")),string(r,"applicationId"),string(r,"ownerModule"),string(r,"displayName"),opt(r,"routePattern"),opt(r,"httpMethod"),EntryPointAuthorityState.valueOf(string(r,"authorityState")),opt(r,"targetPermissionCode"),opt(r,"legacyAuthorityType"),jsonArray(string(r,"legacyAuthorities")),string(r,"resourceType"),string(r,"resourceResolverId"),opt(r,"exemptionReason"),optDate(r,"migrationDeadline"),string(r,"manifestRevision"),string(r,"sourceRef"),string(r,"sourceHash"),instant(r,"lastVerifiedAt"),longValue(r,"version"),bool(r,"unknownPermission"),bool(r,"missingMapping"),bool(r,"missingResolver"),bool(r,"overdue"),bool(r,"activeBypass"),bool(r,"expiredBypass"));}
 private LegacyAuthorityMapping mapping(Map<String,Object> r){return new LegacyAuthorityMapping(string(r,"mappingId"),string(r,"legacyAuthorityType"),string(r,"legacyAuthorityCode"),opt(r,"targetPermissionCode"),string(r,"ownerModule"),string(r,"status"),optDate(r,"migrationDeadline"),string(r,"notes"),instant(r,"updatedAt"),longValue(r,"version"));}
 private EntryPointBypass bypass(Map<String,Object> r){return new EntryPointBypass(string(r,"bypassId"),string(r,"entryPointId"),string(r,"ownerId"),string(r,"reason"),string(r,"replacement"),instant(r,"expiresAt"),string(r,"status"),instant(r,"createdAt"),string(r,"createdBy"),Optional.ofNullable(instant(r,"revokedAt")),opt(r,"revokedBy"),opt(r,"revokeReason"),longValue(r,"version"));}
 private ApplicationPermissionManifest manifest(Map<String,Object> r){return new ApplicationPermissionManifest(string(r,"manifestId"),string(r,"applicationId"),string(r,"environment"),string(r,"buildVersion"),string(r,"manifestRevision"),intValue(r,"schemaVersion"),string(r,"manifestHash"),string(r,"catalogRevisionId"),string(r,"catalogRevisionCode"),string(r,"catalogContentHash"),string(r,"sourceInventoryRevision"),intValue(r,"entryCount"),intValue(r,"protectedEntryCount"),intValue(r,"coveredEntryCount"),decimal(r,"coveragePercent"),intValue(r,"targetPermissionCount"),intValue(r,"legacyAuthorityCount"),intValue(r,"exemptCount"),intValue(r,"delegatedCount"),intValue(r,"uncoveredCount"),string(r,"status"),instant(r,"registeredAt"),string(r,"registeredBy"),Optional.ofNullable(instant(r,"activatedAt")),opt(r,"activatedBy"),longValue(r,"version"),longValue(r,"matchingEntries"),longValue(r,"sourceChanged"),longValue(r,"descriptorChanged"),longValue(r,"unregisteredSource"),longValue(r,"staleManifest"),longValue(r,"unknownPermission"),longValue(r,"retiredPermission"),longValue(r,"missingResolver"),longValue(r,"runtimeDriftBlockers"));}
 private ApplicationPermissionManifestEntry manifestEntry(Map<String,Object> r){return new ApplicationPermissionManifestEntry(string(r,"manifestId"),string(r,"entryPointId"),string(r,"entryPointType"),string(r,"ownerModule"),string(r,"displayName"),opt(r,"routePattern"),opt(r,"httpMethod"),string(r,"authorityState"),string(r,"protectionMode"),string(r,"coverageStatus"),opt(r,"permissionCode"),jsonArray(string(r,"legacyAuthorities")),string(r,"resourceType"),string(r,"resourceResolverId"),bool(r,"scopeRequired"),opt(r,"exemptionReason"),string(r,"sourceRef"),string(r,"sourceHash"),string(r,"descriptorHash"),string(r,"driftStatus"),bool(r,"blocker"));}
 private PermissionCoverageEvidence coverageEvidence(Map<String,Object> r){return new PermissionCoverageEvidence(string(r,"evidenceId"),string(r,"manifestId"),string(r,"evidenceType"),string(r,"manifestHash"),string(r,"catalogRevisionId"),string(r,"catalogContentHash"),intValue(r,"entryCount"),intValue(r,"coveredEntryCount"),decimal(r,"coveragePercent"),string(r,"sourceInventoryRevision"),string(r,"detailsJson"),string(r,"actorId"),opt(r,"correlationId"),instant(r,"occurredAt"));}
 private Map<String,Object> entryRow(EntryPointAuthorityRecord v){Map<String,Object> r=new HashMap<>();r.put("entryPointId",v.entryPointId());r.put("ownerModule",v.ownerModule());r.put("authorityState",v.authorityState().name());r.put("targetPermissionCode",v.targetPermissionCode().orElse(""));r.put("legacyAuthorityType",v.legacyAuthorityType().orElse(""));r.put("legacyAuthorities",json(v.legacyAuthorities()));r.put("resourceType",v.resourceType());r.put("resourceResolverId",v.resourceResolverId());r.put("exemptionReason",v.exemptionReason().orElse(""));r.put("migrationDeadline",v.migrationDeadline().orElse(null));r.put("lastVerifiedAt",v.lastVerifiedAt());return r;}
 private Map<String,Object> mappingRow(LegacyAuthorityMapping v){Map<String,Object> r=new HashMap<>();r.put("mappingId",v.mappingId());r.put("targetPermissionCode",v.targetPermissionCode().orElse(""));r.put("ownerModule",v.ownerModule());r.put("status",v.status());r.put("migrationDeadline",v.migrationDeadline().orElse(null));r.put("notes",v.notes());return r;}
 private Map<String,Object> bypassRow(EntryPointBypass v){Map<String,Object> r=new HashMap<>();r.put("bypassId",v.bypassId());r.put("entryPointId",v.entryPointId());r.put("ownerId",v.ownerId());r.put("reason",v.reason());r.put("replacement",v.replacement());r.put("expiresAt",v.expiresAt());r.put("status",v.status());r.put("createdAt",v.createdAt());r.put("createdBy",v.createdBy());r.put("version",v.version());return r;}
 private Map<String,Object> manifestRow(RegisterApplicationPermissionManifestCommand c){Map<String,Object> r=new HashMap<>();r.put("manifestId",c.manifestId());r.put("applicationId",c.applicationId());r.put("environment",c.environment());r.put("buildVersion",c.buildVersion());r.put("manifestRevision",c.manifestRevision());r.put("schemaVersion",c.schemaVersion());r.put("manifestHash",c.manifestHash());r.put("catalogRevisionId",c.catalogRevisionId());r.put("catalogRevisionCode",c.catalogRevisionCode());r.put("sourceInventoryRevision",c.sourceInventoryRevision());r.put("entryCount",c.entryCount());r.put("protectedEntryCount",c.protectedEntryCount());r.put("coveredEntryCount",c.coveredEntryCount());r.put("coveragePercent",c.coveragePercent());r.put("targetPermissionCount",c.targetPermissionCount());r.put("legacyAuthorityCount",c.legacyAuthorityCount());r.put("exemptCount",c.exemptCount());r.put("delegatedCount",c.delegatedCount());r.put("uncoveredCount",c.uncoveredCount());r.put("registeredAt",c.requestedAt());r.put("registeredBy",c.actorId());return r;}
 private Map<String,Object> manifestEntryRow(String manifestId,PermissionManifestRegistrationEntry e){Map<String,Object> r=new HashMap<>();r.put("manifestId",manifestId);r.put("entryPointId",e.entryPointId());r.put("entryPointType",e.entryPointType());r.put("ownerModule",e.ownerModule());r.put("displayName",e.displayName());r.put("routePattern",e.routePattern().orElse(""));r.put("httpMethod",e.httpMethod().orElse(""));r.put("authorityState",e.authorityState());r.put("protectionMode",e.protectionMode());r.put("coverageStatus",e.coverageStatus());r.put("permissionCode",e.permissionCode().orElse(""));r.put("legacyAuthorities",json(e.legacyAuthorities()));r.put("resourceType",e.resourceType());r.put("resourceResolverId",e.resourceResolverId());r.put("scopeRequired",e.scopeRequired());r.put("exemptionReason",e.exemptionReason().orElse(""));r.put("sourceRef",e.sourceRef());r.put("sourceHash",e.sourceHash());r.put("descriptorHash",e.descriptorHash());return r;}
 private Optional<String> opt(Map<String,Object> r,String k){String v=string(r,k);return v==null||v.isBlank()?Optional.empty():Optional.of(v);}
 private Optional<LocalDate> optDate(Map<String,Object> r,String k){Object v=r.get(k);return v==null?Optional.empty():Optional.of(v instanceof LocalDate d?d:LocalDate.parse(String.valueOf(v)));}
 private List<String> jsonArray(String v){if(v==null||v.length()<2)return List.of();String x=v.substring(1,v.length()-1).trim();if(x.isEmpty())return List.of();List<String> out=new ArrayList<>();for(String p:x.split(",")){String s=p.trim();if(s.startsWith("\"")&&s.endsWith("\""))s=s.substring(1,s.length()-1);out.add(s.replace("\\\"","\"").replace("\\\\","\\"));}return List.copyOf(out);}
 private String json(List<String> values){return values.stream().map(v->"\""+v.replace("\\","\\\\").replace("\"","\\\"")+"\"").collect(java.util.stream.Collectors.joining(",","[","]"));}
 private BigDecimal decimal(Map<String,Object> r,String k){Object v=r.get(k);return v instanceof BigDecimal b?b:new BigDecimal(String.valueOf(v));}
 private String toCamel(String s){StringBuilder b=new StringBuilder();boolean up=false;for(char c:s.toLowerCase(Locale.ROOT).toCharArray()){if(c=='_'){up=true;}else{b.append(up?Character.toUpperCase(c):c);up=false;}}return b.toString();}
}
