-- R4 Unified Access Management Backend.
-- Adds one canonical administration facade without creating a second IAM/RBAC domain.

select set_config('app.current_tenant_id','INSTANCE',true);
select set_config('app.current_actor_id','r4-unified-access-management',true);

comment on column departments.manager_user_id is
'Official Department Manager organizational relationship. It is not a User attribute, Department membership type, or RBAC Role.';

comment on table org_tenant_memberships is
'Tenant admission boundary only. Administrative authority is granted exclusively through RBAC Role Bindings.';

comment on table org_department_memberships is
'Department placement and Primary Department relationship only. MEMBER and DELEGATE never imply an Access Role.';

comment on table org_group_memberships is
'Group membership relationship only. Access is inherited only when the Group principal has an active RBAC Role Binding.';

insert into permission_entry_point_inventory(
 entry_point_id,entry_point_type,application_id,owner_module,display_name,route_pattern,http_method,authority_state,
 target_permission_code,legacy_authority_type,legacy_authorities,resource_type,resource_resolver_id,exemption_reason,
 migration_deadline,manifest_revision,source_ref,source_hash,last_verified_at,created_by,updated_by)
values
('REST:DELETE:/api/admin/access/tenants/{tenantId}/department-memberships/{membershipId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.delete','/api/admin/access/tenants/{tenantId}/department-memberships/{membershipId}','DELETE','TARGET_ONLY','identity.membership.manage',null,'[]'::jsonb,'IAM_MEMBERSHIP','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:DELETE:/api/admin/access/tenants/{tenantId}/group-memberships/{membershipId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.delete','/api/admin/access/tenants/{tenantId}/group-memberships/{membershipId}','DELETE','TARGET_ONLY','identity.membership.manage',null,'[]'::jsonb,'IAM_MEMBERSHIP','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants','GET','TARGET_ONLY','instance.tenant.read',null,'[]'::jsonb,'IAM_TENANT','R4_ROUTE_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}','GET','TARGET_ONLY','instance.tenant.read',null,'[]'::jsonb,'IAM_TENANT','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/audit','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/audit','GET','TARGET_ONLY','audit.identity.read',null,'[]'::jsonb,'IAM_IDENTITY_AUDIT','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/departments','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/departments','GET','TARGET_ONLY','identity.department.read',null,'[]'::jsonb,'IAM_DEPARTMENT','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/departments/{departmentId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/departments/{departmentId}','GET','TARGET_ONLY','identity.department.read',null,'[]'::jsonb,'IAM_DEPARTMENT','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/groups','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/groups','GET','TARGET_ONLY','identity.group.read',null,'[]'::jsonb,'IAM_GROUP','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/groups/{groupId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/groups/{groupId}','GET','TARGET_ONLY','identity.group.read',null,'[]'::jsonb,'IAM_GROUP','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/permissions','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/permissions','GET','TARGET_ONLY','identity.tenant_role.read',null,'[]'::jsonb,'IAM_PERMISSION','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/role-bindings','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/role-bindings','GET','TARGET_ONLY','identity.role_binding.read',null,'[]'::jsonb,'IAM_ROLE_BINDING','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/role-bindings/{bindingId}/revocation-preview','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/role-bindings/{bindingId}/revocation-preview','GET','TARGET_ONLY','identity.role_binding.read',null,'[]'::jsonb,'IAM_ROLE_BINDING','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/roles','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/roles','GET','TARGET_ONLY','identity.tenant_role.read',null,'[]'::jsonb,'IAM_ROLE','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/roles/{roleId}/permissions','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/roles/{roleId}/permissions','GET','TARGET_ONLY','identity.tenant_role.read',null,'[]'::jsonb,'IAM_ROLE','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/sessions','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/sessions','GET','TARGET_ONLY','security.session.read',null,'[]'::jsonb,'IAM_SESSION','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/users','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/users','GET','TARGET_ONLY','identity.user.read',null,'[]'::jsonb,'IAM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/users/{userId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/users/{userId}','GET','TARGET_ONLY','identity.user.read',null,'[]'::jsonb,'IAM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/users/{userId}/effective-access','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/users/{userId}/effective-access','GET','TARGET_ONLY','identity.role_binding.read',null,'[]'::jsonb,'IAM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/users/{userId}/memberships','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/users/{userId}/memberships','GET','TARGET_ONLY','identity.tenant_membership.read',null,'[]'::jsonb,'IAM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/tenants/{tenantId}/users/{userId}/overview','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/tenants/{tenantId}/users/{userId}/overview','GET','TARGET_ONLY','identity.role_binding.read',null,'[]'::jsonb,'IAM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/users','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/users','GET','TARGET_ONLY','identity.platform_user.read',null,'[]'::jsonb,'IAM_PLATFORM_USER','R4_ROUTE_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/users/{userId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/users/{userId}','GET','TARGET_ONLY','identity.platform_user.read',null,'[]'::jsonb,'IAM_PLATFORM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:GET:/api/admin/access/users/{userId}/tenant-memberships','REST','control-plane-app','iam-api','UnifiedAccessManagementController.get','/api/admin/access/users/{userId}/tenant-memberships','GET','TARGET_ONLY','identity.platform_user.read',null,'[]'::jsonb,'IAM_PLATFORM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants','POST','TARGET_ONLY','instance.tenant.manage',null,'[]'::jsonb,'IAM_TENANT','R4_ROUTE_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/departments','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/departments','POST','TARGET_ONLY','identity.department.manage',null,'[]'::jsonb,'IAM_DEPARTMENT','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/departments/{departmentId}/move','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/departments/{departmentId}/move','POST','TARGET_ONLY','identity.department.manage',null,'[]'::jsonb,'IAM_DEPARTMENT','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/departments/{departmentId}/status','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/departments/{departmentId}/status','POST','TARGET_ONLY','identity.department.manage',null,'[]'::jsonb,'IAM_DEPARTMENT','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/groups','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/groups','POST','TARGET_ONLY','identity.group.manage',null,'[]'::jsonb,'IAM_GROUP','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/groups/{groupId}/status','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/groups/{groupId}/status','POST','TARGET_ONLY','identity.group.manage',null,'[]'::jsonb,'IAM_GROUP','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/memberships','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/memberships','POST','TARGET_ONLY','identity.tenant_membership.manage',null,'[]'::jsonb,'IAM_MEMBERSHIP','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/memberships/{membershipId}/status','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/memberships/{membershipId}/status','POST','TARGET_ONLY','identity.tenant_membership.manage',null,'[]'::jsonb,'IAM_MEMBERSHIP','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/role-bindings','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/role-bindings','POST','TARGET_ONLY','identity.role_binding.manage',null,'[]'::jsonb,'IAM_ROLE_BINDING','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/role-bindings/preview','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/role-bindings/preview','POST','TARGET_ONLY','identity.role_binding.read',null,'[]'::jsonb,'IAM_ROLE_BINDING','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/role-bindings/{bindingId}/revoke','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/role-bindings/{bindingId}/revoke','POST','TARGET_ONLY','identity.role_binding.manage',null,'[]'::jsonb,'IAM_ROLE_BINDING','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/roles','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/roles','POST','TARGET_ONLY','identity.tenant_role.manage',null,'[]'::jsonb,'IAM_ROLE','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/roles/{roleId}/status','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/roles/{roleId}/status','POST','TARGET_ONLY','identity.tenant_role.manage',null,'[]'::jsonb,'IAM_ROLE','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/sessions/{sessionId}/revoke','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/sessions/{sessionId}/revoke','POST','TARGET_ONLY','security.session.revoke',null,'[]'::jsonb,'IAM_SESSION','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/status/{status}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/status/{status}','POST','TARGET_ONLY','instance.tenant.manage',null,'[]'::jsonb,'IAM_TENANT','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/users','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/users','POST','TARGET_ONLY','identity.user.create',null,'[]'::jsonb,'IAM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/users/{userId}/department-memberships','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/users/{userId}/department-memberships','POST','TARGET_ONLY','identity.membership.manage',null,'[]'::jsonb,'IAM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/users/{userId}/group-memberships','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/users/{userId}/group-memberships','POST','TARGET_ONLY','identity.membership.manage',null,'[]'::jsonb,'IAM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/users/{userId}/reset-mfa','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/users/{userId}/reset-mfa','POST','TARGET_ONLY','security.mfa.reset',null,'[]'::jsonb,'IAM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/users/{userId}/reset-password','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/users/{userId}/reset-password','POST','TARGET_ONLY','identity.user.update',null,'[]'::jsonb,'IAM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/tenants/{tenantId}/users/{userId}/revoke-sessions','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/tenants/{tenantId}/users/{userId}/revoke-sessions','POST','TARGET_ONLY','security.session.revoke',null,'[]'::jsonb,'IAM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/users','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/users','POST','TARGET_ONLY','identity.platform_user.create',null,'[]'::jsonb,'IAM_PLATFORM_USER','R4_ROUTE_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/users/{userId}/require-password-change','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/users/{userId}/require-password-change','POST','TARGET_ONLY','identity.platform_user.security',null,'[]'::jsonb,'IAM_PLATFORM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/users/{userId}/revoke-all-sessions','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/users/{userId}/revoke-all-sessions','POST','TARGET_ONLY','identity.platform_user.security',null,'[]'::jsonb,'IAM_PLATFORM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:POST:/api/admin/access/users/{userId}/status','REST','control-plane-app','iam-api','UnifiedAccessManagementController.post','/api/admin/access/users/{userId}/status','POST','TARGET_ONLY','identity.platform_user.update',null,'[]'::jsonb,'IAM_PLATFORM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:PUT:/api/admin/access/tenants/{tenantId}/department-memberships/{membershipId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.put','/api/admin/access/tenants/{tenantId}/department-memberships/{membershipId}','PUT','TARGET_ONLY','identity.membership.manage',null,'[]'::jsonb,'IAM_MEMBERSHIP','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:PUT:/api/admin/access/tenants/{tenantId}/departments/{departmentId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.put','/api/admin/access/tenants/{tenantId}/departments/{departmentId}','PUT','TARGET_ONLY','identity.department.manage',null,'[]'::jsonb,'IAM_DEPARTMENT','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:PUT:/api/admin/access/tenants/{tenantId}/departments/{departmentId}/official-manager','REST','control-plane-app','iam-api','UnifiedAccessManagementController.put','/api/admin/access/tenants/{tenantId}/departments/{departmentId}/official-manager','PUT','TARGET_ONLY','identity.department.manage',null,'[]'::jsonb,'IAM_DEPARTMENT','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:PUT:/api/admin/access/tenants/{tenantId}/group-memberships/{membershipId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.put','/api/admin/access/tenants/{tenantId}/group-memberships/{membershipId}','PUT','TARGET_ONLY','identity.membership.manage',null,'[]'::jsonb,'IAM_MEMBERSHIP','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:PUT:/api/admin/access/tenants/{tenantId}/groups/{groupId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.put','/api/admin/access/tenants/{tenantId}/groups/{groupId}','PUT','TARGET_ONLY','identity.group.manage',null,'[]'::jsonb,'IAM_GROUP','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:PUT:/api/admin/access/tenants/{tenantId}/memberships/{membershipId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.put','/api/admin/access/tenants/{tenantId}/memberships/{membershipId}','PUT','TARGET_ONLY','identity.tenant_membership.manage',null,'[]'::jsonb,'IAM_MEMBERSHIP','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:PUT:/api/admin/access/tenants/{tenantId}/roles/{roleId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.put','/api/admin/access/tenants/{tenantId}/roles/{roleId}','PUT','TARGET_ONLY','identity.tenant_role.manage',null,'[]'::jsonb,'IAM_ROLE','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:PUT:/api/admin/access/tenants/{tenantId}/roles/{roleId}/permissions','REST','control-plane-app','iam-api','UnifiedAccessManagementController.put','/api/admin/access/tenants/{tenantId}/roles/{roleId}/permissions','PUT','TARGET_ONLY','identity.role_permission.manage',null,'[]'::jsonb,'IAM_ROLE','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:PUT:/api/admin/access/tenants/{tenantId}/users/{userId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.put','/api/admin/access/tenants/{tenantId}/users/{userId}','PUT','TARGET_ONLY','identity.user.update',null,'[]'::jsonb,'IAM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management'),
('REST:PUT:/api/admin/access/users/{userId}','REST','control-plane-app','iam-api','UnifiedAccessManagementController.put','/api/admin/access/users/{userId}','PUT','TARGET_ONLY','identity.platform_user.update',null,'[]'::jsonb,'IAM_PLATFORM_USER','R4_PATH_RESOURCE_RESOLVER',null,null,'r4-unified-access-management-2026-08-03','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java','5f51b2d86159852ceb8645f4beee46bc642df2e8b1cdb3f8794785964d530d37',now(),'r4-unified-access-management','r4-unified-access-management')
on conflict(entry_point_id) do update set
 entry_point_type=excluded.entry_point_type,application_id=excluded.application_id,owner_module=excluded.owner_module,
 display_name=excluded.display_name,route_pattern=excluded.route_pattern,http_method=excluded.http_method,
 authority_state='TARGET_ONLY',target_permission_code=excluded.target_permission_code,legacy_authority_type=null,
 legacy_authorities='[]'::jsonb,resource_type=excluded.resource_type,resource_resolver_id=excluded.resource_resolver_id,
 exemption_reason=null,migration_deadline=null,manifest_revision=excluded.manifest_revision,source_ref=excluded.source_ref,
 source_hash=excluded.source_hash,last_verified_at=now(),updated_at=now(),updated_by='r4-unified-access-management',
 version=permission_entry_point_inventory.version+1;

do $$
declare route_count integer;
begin
 select count(*) into route_count from permission_entry_point_inventory
  where manifest_revision='r4-unified-access-management-2026-08-03' and authority_state='TARGET_ONLY';
 if route_count <> 58 then
   raise exception 'R4 unified access route inventory incomplete: expected 58, found %',route_count;
 end if;
 if exists(select 1 from permission_entry_point_inventory
   where manifest_revision='r4-unified-access-management-2026-08-03'
     and (target_permission_code is null or resource_resolver_id is null or authority_state<>'TARGET_ONLY')) then
   raise exception 'R4 unified access route has incomplete canonical authorization metadata';
 end if;
 if exists(select 1 from org_department_memberships where membership_type='MANAGER') then
   raise exception 'R4 Manager semantics violation: MANAGER remains a Department membership type';
 end if;
end $$;

update rbac_policy_versions set policy_version=policy_version+1,updated_at=now(),updated_by='r4-unified-access-management';
insert into rbac_policy_versions(scope_type,scope_id,tenant_id,policy_version,updated_at,updated_by)
select 'TENANT',tenant_id,tenant_id,1,now(),'r4-unified-access-management' from tenants
on conflict(scope_type,scope_id) do update set policy_version=rbac_policy_versions.policy_version+1,updated_at=now(),updated_by='r4-unified-access-management';
