-- Phase 6 business-facing Responsibility and Access lifecycle read projections.
-- source_hash values below are SHA-256 digests of the owning Java source file in the phase source artifact.
select set_config('app.current_tenant_id','INSTANCE',true);
select set_config('app.current_actor_id','phase6-access-workspace',true);

insert into permission_entry_point_inventory(
 entry_point_id,entry_point_type,application_id,owner_module,display_name,route_pattern,http_method,authority_state,
 target_permission_code,legacy_authority_type,legacy_authorities,resource_type,resource_resolver_id,exemption_reason,
 migration_deadline,manifest_revision,source_ref,source_hash,last_verified_at,created_by,updated_by)
values
('REST:GET:/api/admin/access/tenants/{tenantId}/responsibility-templates','REST','control-plane-app','iam-api','UnifiedAccessManagementController.responsibilityTemplates','/api/admin/access/tenants/{tenantId}/responsibility-templates','GET','TARGET_ONLY','identity.tenant_role.read',null,'[]'::jsonb,'UNIFIED_ACCESS_MANAGEMENT','R3_PATH_RESOURCE_RESOLVER',null,null,'phase6-access-workspace-2026-08-05','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java#responsibilityTemplates','0fef1191fb33653f55af1919045f5c8f8469ae0e3c06e35ff3b31f530b18fff4',now(),'phase6-access-workspace','phase6-access-workspace'),
('REST:GET:/api/admin/access/tenants/{tenantId}/access-assignments','REST','control-plane-app','iam-api','UnifiedAccessManagementController.accessAssignments','/api/admin/access/tenants/{tenantId}/access-assignments','GET','TARGET_ONLY','identity.role_binding.read',null,'[]'::jsonb,'UNIFIED_ACCESS_MANAGEMENT','R3_PATH_RESOURCE_RESOLVER',null,null,'phase6-access-workspace-2026-08-05','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java#accessAssignments','0fef1191fb33653f55af1919045f5c8f8469ae0e3c06e35ff3b31f530b18fff4',now(),'phase6-access-workspace','phase6-access-workspace'),
('REST:GET:/api/admin/access/tenants/{tenantId}/access-lifecycle-summary','REST','control-plane-app','iam-api','UnifiedAccessManagementController.accessLifecycleSummary','/api/admin/access/tenants/{tenantId}/access-lifecycle-summary','GET','TARGET_ONLY','identity.role_binding.read',null,'[]'::jsonb,'UNIFIED_ACCESS_MANAGEMENT','R3_PATH_RESOURCE_RESOLVER',null,null,'phase6-access-workspace-2026-08-05','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java#accessLifecycleSummary','0fef1191fb33653f55af1919045f5c8f8469ae0e3c06e35ff3b31f530b18fff4',now(),'phase6-access-workspace','phase6-access-workspace'),
('REST:GET:/api/admin/access/tenants/{tenantId}/access-review-candidates','REST','control-plane-app','iam-api','UnifiedAccessManagementController.accessReviewCandidates','/api/admin/access/tenants/{tenantId}/access-review-candidates','GET','TARGET_ONLY','identity.role_binding.read',null,'[]'::jsonb,'UNIFIED_ACCESS_MANAGEMENT','R3_PATH_RESOURCE_RESOLVER',null,null,'phase6-access-workspace-2026-08-05','ai-event-gateway-core/iam-api/src/main/java/com/opensocket/aievent/core/iam/api/controller/UnifiedAccessManagementController.java#accessReviewCandidates','0fef1191fb33653f55af1919045f5c8f8469ae0e3c06e35ff3b31f530b18fff4',now(),'phase6-access-workspace','phase6-access-workspace')
on conflict (entry_point_id) do update set display_name=excluded.display_name,route_pattern=excluded.route_pattern,http_method=excluded.http_method,authority_state=excluded.authority_state,target_permission_code=excluded.target_permission_code,legacy_authority_type=null,legacy_authorities='[]'::jsonb,resource_type=excluded.resource_type,resource_resolver_id=excluded.resource_resolver_id,exemption_reason=null,migration_deadline=null,manifest_revision=excluded.manifest_revision,source_ref=excluded.source_ref,source_hash=excluded.source_hash,last_verified_at=now(),updated_by='phase6-access-workspace',version=permission_entry_point_inventory.version+1;

update rbac_policy_versions set policy_version=policy_version+1,updated_at=now(),updated_by='phase6-access-workspace';
