-- V41-C3R2F: Issue Integration Domain Consumer Closure.
-- Active Webhook Security, Webhook Reconciliation, and Issue Projection consumers become MIGRATION_READY.
-- Eighteen startup-only/dead/legacy settings leave Runtime Configuration scope.
-- Four Java-only @Value/@Scheduled settings are materialized into governed inventory and definitions.
-- No key advances to MIGRATED; C3R3 Single Authority cutover remains mandatory.

insert into runtime_config_inventory_observations(configuration_key,namespace,source_observation_hash,current_files,profiles,value_shapes,review_flags,mutability_floor,source_usage_evidence,advisory_classification) values ('integration-sync.webhook-claim-lease-seconds','integration-sync','8e23f1502b1bf524235945070117ecc3c244dff2e11eb30d9597f3c7110975f2','["ai-event-gateway-core/task-orchestration/src/main/java/com/opensocket/aievent/core/integration/issue/ProviderWebhookReconciliationService.java"]'::jsonb,'["code-default"]'::jsonb,'["JAVA_DEFAULT"]'::jsonb,'["C3R2F_CODE_ONLY_INVENTORY_DISCOVERY"]'::jsonb,'HOT_IMMEDIATE','{"codeOnlyConfigurationFiles":["ai-event-gateway-core/task-orchestration/src/main/java/com/opensocket/aievent/core/integration/issue/ProviderWebhookReconciliationService.java"]}'::jsonb,'{"category":"RUNTIME_TUNABLE","targetAuthority":"RUNTIME_CONFIG_DB","mutability":"HOT_IMMEDIATE","risk":"MEDIUM","migrationAction":"MOVE_TO_RUNTIME_CONFIG_DB","classificationStatus":"C3R2F_EXECUTABLE_SOURCE_REVIEW"}'::jsonb) on conflict(configuration_key) do update set namespace=excluded.namespace,source_observation_hash=excluded.source_observation_hash,current_files=excluded.current_files,profiles=excluded.profiles,value_shapes=excluded.value_shapes,review_flags=excluded.review_flags,mutability_floor=excluded.mutability_floor,source_usage_evidence=excluded.source_usage_evidence,advisory_classification=excluded.advisory_classification,observed_at=now();
insert into runtime_config_inventory_governance(configuration_key,status,source_observation_hash,reason) values ('integration-sync.webhook-claim-lease-seconds','DISCOVERED','8e23f1502b1bf524235945070117ecc3c244dff2e11eb30d9597f3c7110975f2','C3R2F executable-source inventory discovery') on conflict(configuration_key) do nothing;

insert into runtime_config_inventory_observations(configuration_key,namespace,source_observation_hash,current_files,profiles,value_shapes,review_flags,mutability_floor,source_usage_evidence,advisory_classification) values ('integration-sync.webhook-max-attempts','integration-sync','8c15bc8a777587b6b71b3bad4ab83b109d93775440f3367c57ea49773e8f1200','["ai-event-gateway-core/task-orchestration/src/main/java/com/opensocket/aievent/core/integration/issue/ProviderWebhookReconciliationService.java"]'::jsonb,'["code-default"]'::jsonb,'["JAVA_DEFAULT"]'::jsonb,'["C3R2F_CODE_ONLY_INVENTORY_DISCOVERY"]'::jsonb,'HOT_IMMEDIATE','{"codeOnlyConfigurationFiles":["ai-event-gateway-core/task-orchestration/src/main/java/com/opensocket/aievent/core/integration/issue/ProviderWebhookReconciliationService.java"]}'::jsonb,'{"category":"RUNTIME_TUNABLE","targetAuthority":"RUNTIME_CONFIG_DB","mutability":"HOT_IMMEDIATE","risk":"MEDIUM","migrationAction":"MOVE_TO_RUNTIME_CONFIG_DB","classificationStatus":"C3R2F_EXECUTABLE_SOURCE_REVIEW"}'::jsonb) on conflict(configuration_key) do update set namespace=excluded.namespace,source_observation_hash=excluded.source_observation_hash,current_files=excluded.current_files,profiles=excluded.profiles,value_shapes=excluded.value_shapes,review_flags=excluded.review_flags,mutability_floor=excluded.mutability_floor,source_usage_evidence=excluded.source_usage_evidence,advisory_classification=excluded.advisory_classification,observed_at=now();
insert into runtime_config_inventory_governance(configuration_key,status,source_observation_hash,reason) values ('integration-sync.webhook-max-attempts','DISCOVERED','8c15bc8a777587b6b71b3bad4ab83b109d93775440f3367c57ea49773e8f1200','C3R2F executable-source inventory discovery') on conflict(configuration_key) do nothing;

insert into runtime_config_inventory_observations(configuration_key,namespace,source_observation_hash,current_files,profiles,value_shapes,review_flags,mutability_floor,source_usage_evidence,advisory_classification) values ('integration-sync.webhook-reconcile-delay-ms','integration-sync','25c570e719fb2dc2e5f0240069e22c9411b86d25ae0d94062af827bdca582d3d','["ai-event-gateway-core/task-orchestration/src/main/java/com/opensocket/aievent/core/integration/issue/ScheduledProviderWebhookReconciler.java"]'::jsonb,'["code-default"]'::jsonb,'["JAVA_DEFAULT"]'::jsonb,'["C3R2F_CODE_ONLY_INVENTORY_DISCOVERY"]'::jsonb,'HOT_NEXT_CYCLE','{"codeOnlyConfigurationFiles":["ai-event-gateway-core/task-orchestration/src/main/java/com/opensocket/aievent/core/integration/issue/ScheduledProviderWebhookReconciler.java"]}'::jsonb,'{"category":"RUNTIME_TUNABLE","targetAuthority":"RUNTIME_CONFIG_DB","mutability":"HOT_NEXT_CYCLE","risk":"MEDIUM","migrationAction":"MOVE_TO_RUNTIME_CONFIG_DB","classificationStatus":"C3R2F_EXECUTABLE_SOURCE_REVIEW"}'::jsonb) on conflict(configuration_key) do update set namespace=excluded.namespace,source_observation_hash=excluded.source_observation_hash,current_files=excluded.current_files,profiles=excluded.profiles,value_shapes=excluded.value_shapes,review_flags=excluded.review_flags,mutability_floor=excluded.mutability_floor,source_usage_evidence=excluded.source_usage_evidence,advisory_classification=excluded.advisory_classification,observed_at=now();
insert into runtime_config_inventory_governance(configuration_key,status,source_observation_hash,reason) values ('integration-sync.webhook-reconcile-delay-ms','DISCOVERED','25c570e719fb2dc2e5f0240069e22c9411b86d25ae0d94062af827bdca582d3d','C3R2F executable-source inventory discovery') on conflict(configuration_key) do nothing;

insert into runtime_config_inventory_observations(configuration_key,namespace,source_observation_hash,current_files,profiles,value_shapes,review_flags,mutability_floor,source_usage_evidence,advisory_classification) values ('integration-sync.webhook-replay-window-seconds','integration-sync','1ef3c4afb9c8278104c43b8af998892f037be0138a279a6d4920ba9373d8a1ff','["ai-event-gateway-core/task-orchestration/src/main/java/com/opensocket/aievent/core/integration/issue/ProviderWebhookReconciliationService.java"]'::jsonb,'["code-default"]'::jsonb,'["JAVA_DEFAULT"]'::jsonb,'["C3R2F_CODE_ONLY_INVENTORY_DISCOVERY"]'::jsonb,'HOT_IMMEDIATE','{"codeOnlyConfigurationFiles":["ai-event-gateway-core/task-orchestration/src/main/java/com/opensocket/aievent/core/integration/issue/ProviderWebhookReconciliationService.java"]}'::jsonb,'{"category":"RUNTIME_TUNABLE","targetAuthority":"RUNTIME_CONFIG_DB","mutability":"HOT_IMMEDIATE","risk":"HIGH","migrationAction":"MOVE_TO_RUNTIME_CONFIG_DB","classificationStatus":"C3R2F_EXECUTABLE_SOURCE_REVIEW"}'::jsonb) on conflict(configuration_key) do update set namespace=excluded.namespace,source_observation_hash=excluded.source_observation_hash,current_files=excluded.current_files,profiles=excluded.profiles,value_shapes=excluded.value_shapes,review_flags=excluded.review_flags,mutability_floor=excluded.mutability_floor,source_usage_evidence=excluded.source_usage_evidence,advisory_classification=excluded.advisory_classification,observed_at=now();
insert into runtime_config_inventory_governance(configuration_key,status,source_observation_hash,reason) values ('integration-sync.webhook-replay-window-seconds','DISCOVERED','1ef3c4afb9c8278104c43b8af998892f037be0138a279a6d4920ba9373d8a1ff','C3R2F executable-source inventory discovery') on conflict(configuration_key) do nothing;

insert into runtime_config_definitions(definition_key,display_name,owner,domain_owner,authority_class,scope,scope_ref,data_type,unit,risk,mutability,consumer_contract,target_mutability,target_consumer_contract,environment_applicability,validation_rule,requires_approval,admin_editable,initial_seed,introduced_version,ui_metadata,config_set_key,review_status,migration_authorized,schema_version,source_ref,source_fingerprint) values ('integration-sync.webhook-claim-lease-seconds','Webhook claim lease','ISSUE','ISSUE','RUNTIME_TUNABLE','COMPONENT','INTEGRATION_SYNC','LONG','seconds','MEDIUM','HOT_IMMEDIATE','RUNTIME_SNAPSHOT','HOT_IMMEDIATE','RUNTIME_SNAPSHOT','["PRD","UAT","SIT","QA","DEV","LOCAL"]'::jsonb,'{"type":"integer","minimum":15,"maximum":3600,"unit":"seconds"}'::jsonb,true,true,'{"strategy":"CURRENT_EFFECTIVE_STARTUP_VALUE","purpose":"migration-bootstrap-only"}'::jsonb,'V41-C3R2F','{"categoryId":"issue-integration","categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40,"displayName":"Webhook claim lease","description":"integration-sync.webhook-claim-lease-seconds is backed by an active typed runtime consumer and is migration-ready.","recommended":"Initial migration seed preserves the previous Java default (60).","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Makes the formerly Java-only operational parameter auditable, publishable and node-convergent.","impactTradeoff":"Aggressive values can increase provider load or reduce recovery tolerance.","advancedKeyVisible":true}'::jsonb,'RUNTIME/INTEGRATION_SYNC/SYSTEM','MIGRATION_READY',true,10,'contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json','bb921ef3acab88301a4784fe3c849df37b3f3c8ab95f275bf777dce34de05824') on conflict(definition_key) do update set display_name=excluded.display_name,owner=excluded.owner,domain_owner=excluded.domain_owner,authority_class=excluded.authority_class,scope=excluded.scope,scope_ref=excluded.scope_ref,data_type=excluded.data_type,unit=excluded.unit,risk=excluded.risk,mutability=excluded.mutability,consumer_contract=excluded.consumer_contract,target_mutability=excluded.target_mutability,target_consumer_contract=excluded.target_consumer_contract,environment_applicability=excluded.environment_applicability,validation_rule=excluded.validation_rule,requires_approval=excluded.requires_approval,admin_editable=excluded.admin_editable,initial_seed=excluded.initial_seed,introduced_version=excluded.introduced_version,ui_metadata=excluded.ui_metadata,config_set_key=excluded.config_set_key,review_status=excluded.review_status,migration_authorized=excluded.migration_authorized,schema_version=excluded.schema_version,source_ref=excluded.source_ref,source_fingerprint=excluded.source_fingerprint,synchronized_at=now();

insert into runtime_config_definitions(definition_key,display_name,owner,domain_owner,authority_class,scope,scope_ref,data_type,unit,risk,mutability,consumer_contract,target_mutability,target_consumer_contract,environment_applicability,validation_rule,requires_approval,admin_editable,initial_seed,introduced_version,ui_metadata,config_set_key,review_status,migration_authorized,schema_version,source_ref,source_fingerprint) values ('integration-sync.webhook-max-attempts','Webhook maximum attempts','ISSUE','ISSUE','RUNTIME_TUNABLE','COMPONENT','INTEGRATION_SYNC','INTEGER','attempts','MEDIUM','HOT_IMMEDIATE','RUNTIME_SNAPSHOT','HOT_IMMEDIATE','RUNTIME_SNAPSHOT','["PRD","UAT","SIT","QA","DEV","LOCAL"]'::jsonb,'{"type":"integer","minimum":1,"maximum":50}'::jsonb,true,true,'{"strategy":"CURRENT_EFFECTIVE_STARTUP_VALUE","purpose":"migration-bootstrap-only"}'::jsonb,'V41-C3R2F','{"categoryId":"issue-integration","categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40,"displayName":"Webhook maximum attempts","description":"integration-sync.webhook-max-attempts is backed by an active typed runtime consumer and is migration-ready.","recommended":"Initial migration seed preserves the previous Java default (5).","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Makes the formerly Java-only operational parameter auditable, publishable and node-convergent.","impactTradeoff":"Aggressive values can increase provider load or reduce recovery tolerance.","advancedKeyVisible":true}'::jsonb,'RUNTIME/INTEGRATION_SYNC/SYSTEM','MIGRATION_READY',true,10,'contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json','d1b2e2f792ccffd2d535127f03d337e1eacad79029e40a25e33fb251f8a94f11') on conflict(definition_key) do update set display_name=excluded.display_name,owner=excluded.owner,domain_owner=excluded.domain_owner,authority_class=excluded.authority_class,scope=excluded.scope,scope_ref=excluded.scope_ref,data_type=excluded.data_type,unit=excluded.unit,risk=excluded.risk,mutability=excluded.mutability,consumer_contract=excluded.consumer_contract,target_mutability=excluded.target_mutability,target_consumer_contract=excluded.target_consumer_contract,environment_applicability=excluded.environment_applicability,validation_rule=excluded.validation_rule,requires_approval=excluded.requires_approval,admin_editable=excluded.admin_editable,initial_seed=excluded.initial_seed,introduced_version=excluded.introduced_version,ui_metadata=excluded.ui_metadata,config_set_key=excluded.config_set_key,review_status=excluded.review_status,migration_authorized=excluded.migration_authorized,schema_version=excluded.schema_version,source_ref=excluded.source_ref,source_fingerprint=excluded.source_fingerprint,synchronized_at=now();

insert into runtime_config_definitions(definition_key,display_name,owner,domain_owner,authority_class,scope,scope_ref,data_type,unit,risk,mutability,consumer_contract,target_mutability,target_consumer_contract,environment_applicability,validation_rule,requires_approval,admin_editable,initial_seed,introduced_version,ui_metadata,config_set_key,review_status,migration_authorized,schema_version,source_ref,source_fingerprint) values ('integration-sync.webhook-reconcile-delay-ms','Webhook reconciliation delay','ISSUE','ISSUE','RUNTIME_TUNABLE','COMPONENT','INTEGRATION_SYNC','LONG','ms','MEDIUM','HOT_NEXT_CYCLE','DYNAMIC_SCHEDULER','HOT_NEXT_CYCLE','DYNAMIC_SCHEDULER','["PRD","UAT","SIT","QA","DEV","LOCAL"]'::jsonb,'{"type":"integer","minimum":250,"maximum":3600000,"unit":"ms"}'::jsonb,true,true,'{"strategy":"CURRENT_EFFECTIVE_STARTUP_VALUE","purpose":"migration-bootstrap-only"}'::jsonb,'V41-C3R2F','{"categoryId":"issue-integration","categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40,"displayName":"Webhook reconciliation delay","description":"integration-sync.webhook-reconcile-delay-ms is backed by an active typed runtime consumer and is migration-ready.","recommended":"Initial migration seed preserves the previous Java default (60000).","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Makes the formerly Java-only operational parameter auditable, publishable and node-convergent.","impactTradeoff":"Aggressive values can increase provider load or reduce recovery tolerance.","advancedKeyVisible":true}'::jsonb,'RUNTIME/INTEGRATION_SYNC/SYSTEM','MIGRATION_READY',true,10,'contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json','de052d8dc19ccad0bb31ef24b9c7c790d1d317f21b9a758d615d33edd3c04f03') on conflict(definition_key) do update set display_name=excluded.display_name,owner=excluded.owner,domain_owner=excluded.domain_owner,authority_class=excluded.authority_class,scope=excluded.scope,scope_ref=excluded.scope_ref,data_type=excluded.data_type,unit=excluded.unit,risk=excluded.risk,mutability=excluded.mutability,consumer_contract=excluded.consumer_contract,target_mutability=excluded.target_mutability,target_consumer_contract=excluded.target_consumer_contract,environment_applicability=excluded.environment_applicability,validation_rule=excluded.validation_rule,requires_approval=excluded.requires_approval,admin_editable=excluded.admin_editable,initial_seed=excluded.initial_seed,introduced_version=excluded.introduced_version,ui_metadata=excluded.ui_metadata,config_set_key=excluded.config_set_key,review_status=excluded.review_status,migration_authorized=excluded.migration_authorized,schema_version=excluded.schema_version,source_ref=excluded.source_ref,source_fingerprint=excluded.source_fingerprint,synchronized_at=now();

insert into runtime_config_definitions(definition_key,display_name,owner,domain_owner,authority_class,scope,scope_ref,data_type,unit,risk,mutability,consumer_contract,target_mutability,target_consumer_contract,environment_applicability,validation_rule,requires_approval,admin_editable,initial_seed,introduced_version,ui_metadata,config_set_key,review_status,migration_authorized,schema_version,source_ref,source_fingerprint) values ('integration-sync.webhook-replay-window-seconds','Webhook replay window','ISSUE','ISSUE','RUNTIME_TUNABLE','COMPONENT','INTEGRATION_SYNC','LONG','seconds','HIGH','HOT_IMMEDIATE','RUNTIME_SNAPSHOT','HOT_IMMEDIATE','RUNTIME_SNAPSHOT','["PRD","UAT","SIT","QA","DEV","LOCAL"]'::jsonb,'{"type":"integer","minimum":30,"maximum":86400,"unit":"seconds"}'::jsonb,true,true,'{"strategy":"CURRENT_EFFECTIVE_STARTUP_VALUE","purpose":"migration-bootstrap-only"}'::jsonb,'V41-C3R2F','{"categoryId":"issue-integration","categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40,"displayName":"Webhook replay window","description":"integration-sync.webhook-replay-window-seconds is backed by an active typed runtime consumer and is migration-ready.","recommended":"Initial migration seed preserves the previous Java default (300).","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Makes the formerly Java-only operational parameter auditable, publishable and node-convergent.","impactTradeoff":"Aggressive values can increase provider load or reduce recovery tolerance.","advancedKeyVisible":true}'::jsonb,'RUNTIME/INTEGRATION_SYNC/SYSTEM','MIGRATION_READY',true,10,'contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json','de74600388d39746affa8438e67a21735a27385b9fe0f45cd3125af4ac4cedb0') on conflict(definition_key) do update set display_name=excluded.display_name,owner=excluded.owner,domain_owner=excluded.domain_owner,authority_class=excluded.authority_class,scope=excluded.scope,scope_ref=excluded.scope_ref,data_type=excluded.data_type,unit=excluded.unit,risk=excluded.risk,mutability=excluded.mutability,consumer_contract=excluded.consumer_contract,target_mutability=excluded.target_mutability,target_consumer_contract=excluded.target_consumer_contract,environment_applicability=excluded.environment_applicability,validation_rule=excluded.validation_rule,requires_approval=excluded.requires_approval,admin_editable=excluded.admin_editable,initial_seed=excluded.initial_seed,introduced_version=excluded.introduced_version,ui_metadata=excluded.ui_metadata,config_set_key=excluded.config_set_key,review_status=excluded.review_status,migration_authorized=excluded.migration_authorized,schema_version=excluded.schema_version,source_ref=excluded.source_ref,source_fingerprint=excluded.source_fingerprint,synchronized_at=now();

update runtime_config_definitions set authority_class='RUNTIME_TUNABLE',risk='HIGH',mutability='HOT_IMMEDIATE',consumer_contract='RUNTIME_SNAPSHOT',target_mutability='HOT_IMMEDIATE',target_consumer_contract='RUNTIME_SNAPSHOT',validation_rule='{"type":"integer","minimum":0,"maximum":3600,"unit":"seconds"}'::jsonb,review_status='MIGRATION_READY',migration_authorized=true,admin_editable=true,schema_version=10,source_ref='contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json',source_fingerprint='9cd40801855e3f14f1e98b5fcccf566a66090c0915cc94b8960ac1cf28d6122f',ui_metadata='{"categoryId":"issue-integration","categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40,"displayName":"Clock Skew Seconds","description":"integration-sync.webhook-security.clock-skew-seconds is backed by an active typed runtime consumer and is migration-ready.","recommended":"Review current effective value before consumer migration.","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Makes the target runtime setting visible and traceable before authority cutover.","impactTradeoff":"Changing this definition does not change runtime behavior until migration is authorized.","advancedKeyVisible":true}'::jsonb,config_set_key='RUNTIME/INTEGRATION_SYNC/SYSTEM',synchronized_at=now() where definition_key='integration-sync.webhook-security.clock-skew-seconds';

update runtime_config_definitions set authority_class='RUNTIME_TUNABLE',risk='HIGH',mutability='HOT_IMMEDIATE',consumer_contract='RUNTIME_SNAPSHOT',target_mutability='HOT_IMMEDIATE',target_consumer_contract='RUNTIME_SNAPSHOT',validation_rule='{"type":"integer","minimum":1024,"maximum":104857600,"unit":"bytes"}'::jsonb,review_status='MIGRATION_READY',migration_authorized=true,admin_editable=true,schema_version=10,source_ref='contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json',source_fingerprint='2763a47c65a8be058a66ec394f6f1b6b5189937c07bd9204c76c6e7a679caad4',ui_metadata='{"categoryId":"issue-integration","categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40,"displayName":"Default Max Body Bytes","description":"integration-sync.webhook-security.default-max-body-bytes is backed by an active typed runtime consumer and is migration-ready.","recommended":"Review current effective value before consumer migration.","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Makes the target runtime setting visible and traceable before authority cutover.","impactTradeoff":"Changing this definition does not change runtime behavior until migration is authorized.","advancedKeyVisible":true}'::jsonb,config_set_key='RUNTIME/INTEGRATION_SYNC/SYSTEM',synchronized_at=now() where definition_key='integration-sync.webhook-security.default-max-body-bytes';

update runtime_config_definitions set authority_class='RUNTIME_TUNABLE',risk='HIGH',mutability='HOT_IMMEDIATE',consumer_contract='RUNTIME_SNAPSHOT',target_mutability='HOT_IMMEDIATE',target_consumer_contract='RUNTIME_SNAPSHOT',validation_rule='{"type":"integer","minimum":1,"maximum":100000,"unit":"requests/minute"}'::jsonb,review_status='MIGRATION_READY',migration_authorized=true,admin_editable=true,schema_version=10,source_ref='contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json',source_fingerprint='0bb04995cf470c98d458fa394c1560ada2f83f3c70aaa99e704efa19795f1545',ui_metadata='{"categoryId":"issue-integration","categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40,"displayName":"Default Rate Limit Per Minute","description":"integration-sync.webhook-security.default-rate-limit-per-minute is backed by an active typed runtime consumer and is migration-ready.","recommended":"Review current effective value before consumer migration.","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Makes the target runtime setting visible and traceable before authority cutover.","impactTradeoff":"Changing this definition does not change runtime behavior until migration is authorized.","advancedKeyVisible":true}'::jsonb,config_set_key='RUNTIME/INTEGRATION_SYNC/SYSTEM',synchronized_at=now() where definition_key='integration-sync.webhook-security.default-rate-limit-per-minute';

update runtime_config_definitions set authority_class='RUNTIME_TUNABLE',risk='HIGH',mutability='HOT_IMMEDIATE',consumer_contract='RUNTIME_SNAPSHOT',target_mutability='HOT_IMMEDIATE',target_consumer_contract='RUNTIME_SNAPSHOT',validation_rule='{"type":"boolean"}'::jsonb,review_status='MIGRATION_READY',migration_authorized=true,admin_editable=true,schema_version=10,source_ref='contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json',source_fingerprint='3661e39601592c509d1d606e23d63f57a1cd8da3a3005cf577da1d6482ef4800',ui_metadata='{"categoryId":"issue-integration","categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40,"displayName":"Enabled","description":"integration-sync.webhook-security.enabled is backed by an active typed runtime consumer and is migration-ready.","recommended":"Review current effective value before consumer migration.","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Makes the target runtime setting visible and traceable before authority cutover.","impactTradeoff":"Changing this definition does not change runtime behavior until migration is authorized.","advancedKeyVisible":true}'::jsonb,config_set_key='RUNTIME/INTEGRATION_SYNC/SYSTEM',synchronized_at=now() where definition_key='integration-sync.webhook-security.enabled';

update runtime_config_definitions set authority_class='RUNTIME_TUNABLE',risk='HIGH',mutability='HOT_NEXT_CYCLE',consumer_contract='RUNTIME_SNAPSHOT',target_mutability='HOT_NEXT_CYCLE',target_consumer_contract='RUNTIME_SNAPSHOT',validation_rule='{"type":"integer","minimum":1,"maximum":100000}'::jsonb,review_status='MIGRATION_READY',migration_authorized=true,admin_editable=true,schema_version=10,source_ref='contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json',source_fingerprint='446bf3d2332b153b6edbf6e4b59c1bf9aa97a15b2db5698c7a19a5f196fe5c6b',ui_metadata='{"categoryId":"issue-integration","categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40,"displayName":"Nonce Cleanup Batch Size","description":"integration-sync.webhook-security.nonce-cleanup-batch-size is backed by an active typed runtime consumer and is migration-ready.","recommended":"Review current effective value before consumer migration.","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Makes the target runtime setting visible and traceable before authority cutover.","impactTradeoff":"Changing this definition does not change runtime behavior until migration is authorized.","advancedKeyVisible":true}'::jsonb,config_set_key='RUNTIME/INTEGRATION_SYNC/SYSTEM',synchronized_at=now() where definition_key='integration-sync.webhook-security.nonce-cleanup-batch-size';

update runtime_config_definitions set authority_class='RUNTIME_TUNABLE',risk='HIGH',mutability='HOT_NEXT_CYCLE',consumer_contract='DYNAMIC_SCHEDULER',target_mutability='HOT_NEXT_CYCLE',target_consumer_contract='DYNAMIC_SCHEDULER',validation_rule='{"type":"integer","minimum":1000,"maximum":3600000,"unit":"ms"}'::jsonb,review_status='MIGRATION_READY',migration_authorized=true,admin_editable=true,schema_version=10,source_ref='contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json',source_fingerprint='e3f10985fb1cf0efe583bb250b59fc2aec2be290cb502919d0edee1785441cf3',ui_metadata='{"categoryId":"issue-integration","categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40,"displayName":"Nonce Cleanup Interval Ms","description":"integration-sync.webhook-security.nonce-cleanup-interval-ms is backed by an active typed runtime consumer and is migration-ready.","recommended":"Review current effective value before consumer migration.","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Makes the target runtime setting visible and traceable before authority cutover.","impactTradeoff":"Changing this definition does not change runtime behavior until migration is authorized.","advancedKeyVisible":true}'::jsonb,config_set_key='RUNTIME/INTEGRATION_SYNC/SYSTEM',synchronized_at=now() where definition_key='integration-sync.webhook-security.nonce-cleanup-interval-ms';

update runtime_config_definitions set authority_class='RUNTIME_TUNABLE',risk='MEDIUM',mutability='HOT_IMMEDIATE',consumer_contract='RUNTIME_SNAPSHOT',target_mutability='HOT_IMMEDIATE',target_consumer_contract='RUNTIME_SNAPSHOT',validation_rule='{"type":"boolean"}'::jsonb,review_status='MIGRATION_READY',migration_authorized=true,admin_editable=true,schema_version=10,source_ref='contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json',source_fingerprint='ac81c61235e306fd2a52bbf7f718f22d5dfc5707f9e04a91d09321a1321561c9',ui_metadata='{"categoryId":"issue-integration","categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40,"displayName":"Enabled","description":"issue-projection.enabled is backed by an active typed runtime consumer and is migration-ready.","recommended":"Review current effective value before consumer migration.","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Makes the target runtime setting visible and traceable before authority cutover.","impactTradeoff":"Changing this definition does not change runtime behavior until migration is authorized.","advancedKeyVisible":true}'::jsonb,config_set_key='RUNTIME/ISSUE/SYSTEM',synchronized_at=now() where definition_key='issue-projection.enabled';

update runtime_config_definitions set authority_class='RUNTIME_TUNABLE',risk='MEDIUM',mutability='HOT_IMMEDIATE',consumer_contract='RUNTIME_SNAPSHOT',target_mutability='HOT_IMMEDIATE',target_consumer_contract='RUNTIME_SNAPSHOT',validation_rule='{"type":"integer","minimum":1,"maximum":100}'::jsonb,review_status='MIGRATION_READY',migration_authorized=true,admin_editable=true,schema_version=10,source_ref='contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json',source_fingerprint='38c57078520c416c7eb7644f0afe51ab9aae26fba5794f04ea58a3603d1a4add',ui_metadata='{"categoryId":"issue-integration","categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40,"displayName":"Max Attempts","description":"issue-projection.max-attempts is backed by an active typed runtime consumer and is migration-ready.","recommended":"Review current effective value before consumer migration.","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Makes the target runtime setting visible and traceable before authority cutover.","impactTradeoff":"Changing this definition does not change runtime behavior until migration is authorized.","advancedKeyVisible":true}'::jsonb,config_set_key='RUNTIME/ISSUE/SYSTEM',synchronized_at=now() where definition_key='issue-projection.max-attempts';

update runtime_config_definitions set authority_class='RUNTIME_TUNABLE',risk='MEDIUM',mutability='HOT_NEXT_CYCLE',consumer_contract='RUNTIME_SNAPSHOT',target_mutability='HOT_NEXT_CYCLE',target_consumer_contract='RUNTIME_SNAPSHOT',validation_rule='{"minimum":1,"maximum":1000}'::jsonb,review_status='MIGRATION_READY',migration_authorized=true,admin_editable=true,schema_version=10,source_ref='contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json',source_fingerprint='91086f2e940b1bfeaf4fdb841b711df2ca5b7bc1803f944b15ab3f7c6d15764a',ui_metadata='{"categoryId":"issue-integration","displayName":"Issue reconciliation batch size","description":"issue-projection.reconcile-batch-size is backed by an active typed runtime consumer and is migration-ready.","recommended":"1–200","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Larger batches clear a backlog faster.","impactTradeoff":"Large batches increase provider and database load.","advancedKeyVisible":true,"categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40}'::jsonb,config_set_key='RUNTIME/ISSUE/SYSTEM',synchronized_at=now() where definition_key='issue-projection.reconcile-batch-size';

update runtime_config_definitions set authority_class='RUNTIME_TUNABLE',risk='MEDIUM',mutability='HOT_NEXT_CYCLE',consumer_contract='DYNAMIC_SCHEDULER',target_mutability='HOT_NEXT_CYCLE',target_consumer_contract='DYNAMIC_SCHEDULER',validation_rule='{"minimum":250,"maximum":3600000}'::jsonb,review_status='MIGRATION_READY',migration_authorized=true,admin_editable=true,schema_version=10,source_ref='contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json',source_fingerprint='513f2cc47214ceec73f7fd7dc2e38c9d86fa713043e42f17664f7d52254ca1b0',ui_metadata='{"categoryId":"issue-integration","displayName":"Issue reconciliation interval","description":"issue-projection.reconcile-delay-ms is backed by an active typed runtime consumer and is migration-ready.","recommended":"5000–120000","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Shorter intervals reduce reconciliation latency.","impactTradeoff":"Very short intervals increase database and provider-side pressure.","advancedKeyVisible":true,"categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40}'::jsonb,config_set_key='RUNTIME/ISSUE/SYSTEM',synchronized_at=now() where definition_key='issue-projection.reconcile-delay-ms';

update runtime_config_definitions set authority_class='RUNTIME_TUNABLE',risk='MEDIUM',mutability='HOT_NEXT_CYCLE',consumer_contract='RUNTIME_SNAPSHOT',target_mutability='HOT_NEXT_CYCLE',target_consumer_contract='RUNTIME_SNAPSHOT',validation_rule='{"minimum":1,"maximum":86400}'::jsonb,review_status='MIGRATION_READY',migration_authorized=true,admin_editable=true,schema_version=10,source_ref='contracts/current/configuration/definitions/runtime-target-definition-baseline-v41-c3r2f.json',source_fingerprint='be1aa422fe4e0f288ee9e09985a9fd4aba539b928be63d3865163975296f4d25',ui_metadata='{"categoryId":"issue-integration","displayName":"Issue retry delay","description":"issue-projection.retry-delay-seconds is backed by an active typed runtime consumer and is migration-ready.","recommended":"5–300","effect":"Runtime snapshot effective; startup fallback remains legal until C3R3 cutover","impactPositive":"Gives external Issue providers time to recover.","impactTradeoff":"Long delays postpone projection recovery.","advancedKeyVisible":true,"categoryDisplayName":"Issue Integration","categoryDescription":"Issue projection and provider webhook runtime controls.","categoryOrder":40}'::jsonb,config_set_key='RUNTIME/ISSUE/SYSTEM',synchronized_at=now() where definition_key='issue-projection.retry-delay-seconds';

update runtime_config_definitions set authority_class='BOOTSTRAP_INFRA',mutability='RESTART_REQUIRED',consumer_contract='SPRING_CONDITION',target_mutability='RESTART_REQUIRED',target_consumer_contract='SPRING_CONDITION',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='ed2b50326632d13ef996a49a362529e432579b5f056a6d1dde28d75cc5a714b5',synchronized_at=now() where definition_key='integration-sync.provider-gateway';

update runtime_config_definitions set authority_class='BOOTSTRAP_INFRA',mutability='RESTART_REQUIRED',consumer_contract='SPRING_CONDITION',target_mutability='RESTART_REQUIRED',target_consumer_contract='SPRING_CONDITION',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='b89e14e5465959082c4f4af7a2c063daaa6203be9f3815118c9ca17b878b6e6e',synchronized_at=now() where definition_key='issue-projection.relay-provider';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='6214577904a3848b3b9d70b5cd2dc38ef28405da7cce4c85f7697966605a39b9',synchronized_at=now() where definition_key='integration-sync.circuit-failure-threshold';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='bac06fa93cc153957a4fe4584076b12e2620e1e73b1c54235c52f26f551ac06d',synchronized_at=now() where definition_key='integration-sync.claim-limit';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='1650935f2257758e6bfe3df9f17033ee991c57a9483d2b7a246d0ada72d81f5d',synchronized_at=now() where definition_key='integration-sync.legacy-worker-enabled';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='aaa2e614b1c32bdd6ae7298ebea09557f49d6c524e13c7e1135db4ef36ca7cc0',synchronized_at=now() where definition_key='integration-sync.max-attempts';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='19d5a213141ae7c9fa0d1926e1a8566ab48c59d736aec81def5ca9e2bf7e2d5a',synchronized_at=now() where definition_key='integration-sync.projection-worker-enabled';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='decd54e53aaf9fa680146b455e9a94849a3dbdd51b7e88768a15afefc81d2ae5',synchronized_at=now() where definition_key='integration-sync.projection-worker-interval-ms';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='c962e693e857f1d8bd12be4726f264402c76fa2543b0529768d090b0571f03ab',synchronized_at=now() where definition_key='integration-sync.worker-enabled';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='4ee574bfd2ec13e8cee0d01f6e2a4d4d1dc69f83b528c1c55b84689af502acc0',synchronized_at=now() where definition_key='integration-sync.worker-interval-ms';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='3758981b08c12df2ae4820d0fe00192dd3651ccf3b0074ee9881274895c89195',synchronized_at=now() where definition_key='issue-projection-recovery.circuit-failure-threshold';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='51822b5620fde1c428672123ab24dca9cc52f5eebe9e9bbd75981c52441d1b4f',synchronized_at=now() where definition_key='issue-projection-recovery.claim-lease-seconds';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='9b045a074624b72603c013678070b394ab15b76913b12e420a50d1fdb2f00340',synchronized_at=now() where definition_key='issue-projection-recovery.claim-limit';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='86c88dbfedab1fee5b57d910ae635760d1d227fc5bcdf21146f0ab37da7c44c6',synchronized_at=now() where definition_key='issue-projection-recovery.index-delay-seconds';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='8845fe6f8273bddab54d127ec11e05b1ede85f7d16ec37d10ac128e9d4fa6a2a',synchronized_at=now() where definition_key='issue-projection-recovery.max-queue-depth';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='b623c7359b9db174b41cbf63224ee402631bb276d272a3c31e88ed67490ad4fb',synchronized_at=now() where definition_key='issue-relay.due-claim-limit';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='46b1a2ff9d3068a80f7bcba837caf77f3b2583ccabe32a951d6a13d234f02b01',synchronized_at=now() where definition_key='issue-relay.edge-max-attempts';

update runtime_config_definitions set authority_class='DOMAIN_CONFIG',mutability='RESTART_REQUIRED',consumer_contract='STARTUP_BINDING',target_mutability='RESTART_REQUIRED',target_consumer_contract='STARTUP_BINDING',review_status='RETIRED',migration_authorized=false,admin_editable=false,schema_version=10,source_ref='contracts/current/configuration/definitions/definition-registry-v41-c3r2f.json',source_fingerprint='bbeb324b9b7b79851277b70f78da43aad65bc53937e9116ae02296d13f6c3692',synchronized_at=now() where definition_key='issue-relay.retry-base-seconds';

update runtime_config_inventory_governance set authority_class='BOOTSTRAP_INFRA', mutability='RESTART_REQUIRED', consumer_contract='SPRING_CONDITION', admin_editable=false, requires_approval=true, reason='C3R2F Spring wiring selector; deployment/startup authority only', version=version+1, updated_at=now() where configuration_key='integration-sync.provider-gateway' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='BOOTSTRAP_INFRA', mutability='RESTART_REQUIRED', consumer_contract='SPRING_CONDITION', admin_editable=false, requires_approval=true, reason='C3R2F Spring wiring selector; deployment/startup authority only', version=version+1, updated_at=now() where configuration_key='issue-projection.relay-provider' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='integration-sync.circuit-failure-threshold' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='integration-sync.claim-limit' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='integration-sync.legacy-worker-enabled' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='integration-sync.max-attempts' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='integration-sync.projection-worker-enabled' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='integration-sync.projection-worker-interval-ms' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='integration-sync.worker-enabled' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='integration-sync.worker-interval-ms' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='issue-projection-recovery.circuit-failure-threshold' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='issue-projection-recovery.claim-lease-seconds' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='issue-projection-recovery.claim-limit' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='issue-projection-recovery.index-delay-seconds' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='issue-projection-recovery.max-queue-depth' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='issue-relay.due-claim-limit' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='issue-relay.edge-max-attempts' and status not in ('MIGRATED','LEGACY_RETIRED');

update runtime_config_inventory_governance set authority_class='DOMAIN_CONFIG', mutability='RESTART_REQUIRED', consumer_contract='STARTUP_BINDING', admin_editable=false, reason='C3R2F no active execution consumer or retired legacy path; removed from Runtime target scope', version=version+1, updated_at=now() where configuration_key='issue-relay.retry-base-seconds' and status not in ('MIGRATED','LEGACY_RETIRED');

with advanced as (
 update runtime_config_inventory_governance g set status='CLASSIFIED',domain_owner=d.domain_owner,authority_class=d.authority_class,scope=d.scope,risk=d.risk,mutability=d.target_mutability,consumer_contract=d.target_consumer_contract,admin_editable=d.admin_editable,requires_approval=d.requires_approval,classified_by='v41-c3r2f-issue-integration-consumer-closure',classified_at=now(),reason='V41-C3R2F active typed runtime consumer implemented',version=version+1
 from runtime_config_definitions d where g.configuration_key=d.definition_key and g.configuration_key in (
    'integration-sync.webhook-claim-lease-seconds',
    'integration-sync.webhook-max-attempts',
    'integration-sync.webhook-reconcile-delay-ms',
    'integration-sync.webhook-replay-window-seconds',
    'integration-sync.webhook-security.clock-skew-seconds',
    'integration-sync.webhook-security.default-max-body-bytes',
    'integration-sync.webhook-security.default-rate-limit-per-minute',
    'integration-sync.webhook-security.enabled',
    'integration-sync.webhook-security.nonce-cleanup-batch-size',
    'integration-sync.webhook-security.nonce-cleanup-interval-ms',
    'issue-projection.enabled',
    'issue-projection.max-attempts'
 ) and g.status='DISCOVERED' returning g.configuration_key,g.source_observation_hash
)
insert into runtime_config_inventory_governance_events(configuration_key,event_type,from_status,to_status,actor,reason,source_observation_hash,detail_json)
select configuration_key,'CLASSIFIED','DISCOVERED','CLASSIFIED','v41-c3r2f-issue-integration-consumer-closure','Active Issue Integration consumer classification confirmed',source_observation_hash,'{"stage":"V41_C3R2F_ISSUE_INTEGRATION_DOMAIN_CONSUMER_CLOSURE"}'::jsonb from advanced;

with advanced as (
 update runtime_config_inventory_governance set status='OWNER_REVIEWED',owner_reviewed_by='issue-integration-domain-owner',owner_reviewed_at=now(),reason='Issue Integration consumer and validation bounds reviewed',version=version+1 where configuration_key in (
    'integration-sync.webhook-claim-lease-seconds',
    'integration-sync.webhook-max-attempts',
    'integration-sync.webhook-reconcile-delay-ms',
    'integration-sync.webhook-replay-window-seconds',
    'integration-sync.webhook-security.clock-skew-seconds',
    'integration-sync.webhook-security.default-max-body-bytes',
    'integration-sync.webhook-security.default-rate-limit-per-minute',
    'integration-sync.webhook-security.enabled',
    'integration-sync.webhook-security.nonce-cleanup-batch-size',
    'integration-sync.webhook-security.nonce-cleanup-interval-ms',
    'issue-projection.enabled',
    'issue-projection.max-attempts'
 ) and status='CLASSIFIED' returning configuration_key,source_observation_hash
)
insert into runtime_config_inventory_governance_events(configuration_key,event_type,from_status,to_status,actor,reason,source_observation_hash,detail_json)
select configuration_key,'OWNER_REVIEWED','CLASSIFIED','OWNER_REVIEWED','issue-integration-domain-owner','Issue Integration consumer and validation bounds reviewed',source_observation_hash,'{"cutover":"NOT_FINALIZED"}'::jsonb from advanced;

with advanced as (
 update runtime_config_inventory_governance set status='ARCHITECTURE_APPROVED',architecture_approved_by='configuration-architecture-reviewer',architecture_approved_at=now(),reason='DB authority + Redis distribution + authenticated local snapshot architecture approved',version=version+1 where configuration_key in (
    'integration-sync.webhook-claim-lease-seconds',
    'integration-sync.webhook-max-attempts',
    'integration-sync.webhook-reconcile-delay-ms',
    'integration-sync.webhook-replay-window-seconds',
    'integration-sync.webhook-security.clock-skew-seconds',
    'integration-sync.webhook-security.default-max-body-bytes',
    'integration-sync.webhook-security.default-rate-limit-per-minute',
    'integration-sync.webhook-security.enabled',
    'integration-sync.webhook-security.nonce-cleanup-batch-size',
    'integration-sync.webhook-security.nonce-cleanup-interval-ms',
    'issue-projection.enabled',
    'issue-projection.max-attempts'
 ) and status='OWNER_REVIEWED' returning configuration_key,source_observation_hash
)
insert into runtime_config_inventory_governance_events(configuration_key,event_type,from_status,to_status,actor,reason,source_observation_hash,detail_json)
select configuration_key,'ARCHITECTURE_APPROVED','OWNER_REVIEWED','ARCHITECTURE_APPROVED','configuration-architecture-reviewer','DB authority + Redis distribution + authenticated local snapshot architecture approved',source_observation_hash,'{"cutover":"NOT_FINALIZED"}'::jsonb from advanced;

with advanced as (
 update runtime_config_inventory_governance set status='MIGRATION_READY',migration_authorized_by='v41-c3r2f-issue-integration-consumer-closure',migration_authorized_at=now(),reason='Typed consumers implemented; Single Authority cutover remains pending',version=version+1 where configuration_key in (
    'integration-sync.webhook-claim-lease-seconds',
    'integration-sync.webhook-max-attempts',
    'integration-sync.webhook-reconcile-delay-ms',
    'integration-sync.webhook-replay-window-seconds',
    'integration-sync.webhook-security.clock-skew-seconds',
    'integration-sync.webhook-security.default-max-body-bytes',
    'integration-sync.webhook-security.default-rate-limit-per-minute',
    'integration-sync.webhook-security.enabled',
    'integration-sync.webhook-security.nonce-cleanup-batch-size',
    'integration-sync.webhook-security.nonce-cleanup-interval-ms',
    'issue-projection.enabled',
    'issue-projection.max-attempts'
 ) and status='ARCHITECTURE_APPROVED' returning configuration_key,source_observation_hash
)
insert into runtime_config_inventory_governance_events(configuration_key,event_type,from_status,to_status,actor,reason,source_observation_hash,detail_json)
select configuration_key,'MIGRATION_READY','ARCHITECTURE_APPROVED','MIGRATION_READY','v41-c3r2f-issue-integration-consumer-closure','Typed consumers implemented; Single Authority cutover remains pending',source_observation_hash,'{"cutover":"NOT_FINALIZED"}'::jsonb from advanced;

do $$ declare v_ready integer; begin
  select count(*) into v_ready from runtime_config_definitions where definition_key in (
    'integration-sync.webhook-claim-lease-seconds',
    'integration-sync.webhook-max-attempts',
    'integration-sync.webhook-reconcile-delay-ms',
    'integration-sync.webhook-replay-window-seconds',
    'integration-sync.webhook-security.clock-skew-seconds',
    'integration-sync.webhook-security.default-max-body-bytes',
    'integration-sync.webhook-security.default-rate-limit-per-minute',
    'integration-sync.webhook-security.enabled',
    'integration-sync.webhook-security.nonce-cleanup-batch-size',
    'integration-sync.webhook-security.nonce-cleanup-interval-ms',
    'issue-projection.enabled',
    'issue-projection.max-attempts',
    'issue-projection.reconcile-batch-size',
    'issue-projection.reconcile-delay-ms',
    'issue-projection.retry-delay-seconds'
  ) and review_status='MIGRATION_READY' and migration_authorized=true and admin_editable=true;
  if v_ready<>15 then raise exception 'C3R2F_DOMAIN_DEFINITION_CLOSURE_INCOMPLETE expected=15 actual=%',v_ready; end if;
  if exists(select 1 from runtime_config_definitions where definition_key in ('integration-sync.circuit-failure-threshold','integration-sync.claim-limit','integration-sync.legacy-worker-enabled','integration-sync.max-attempts','integration-sync.projection-worker-enabled','integration-sync.projection-worker-interval-ms','integration-sync.provider-gateway','integration-sync.worker-enabled','integration-sync.worker-interval-ms','issue-projection-recovery.circuit-failure-threshold','issue-projection-recovery.claim-lease-seconds','issue-projection-recovery.claim-limit','issue-projection-recovery.index-delay-seconds','issue-projection-recovery.max-queue-depth','issue-projection.relay-provider','issue-relay.due-claim-limit','issue-relay.edge-max-attempts','issue-relay.retry-base-seconds') and (migration_authorized=true or admin_editable=true or review_status<>'RETIRED')) then raise exception 'C3R2F_RECLASSIFIED_AUTHORITY_LEAK'; end if;
  if (select count(*) from runtime_config_inventory_observations where configuration_key in ('integration-sync.webhook-claim-lease-seconds','integration-sync.webhook-max-attempts','integration-sync.webhook-reconcile-delay-ms','integration-sync.webhook-replay-window-seconds'))<>4 then raise exception 'C3R2F_CODE_ONLY_INVENTORY_MISSING'; end if;
  if exists(select 1 from runtime_config_inventory_governance where configuration_key in (
    'integration-sync.webhook-claim-lease-seconds',
    'integration-sync.webhook-max-attempts',
    'integration-sync.webhook-reconcile-delay-ms',
    'integration-sync.webhook-replay-window-seconds',
    'integration-sync.webhook-security.clock-skew-seconds',
    'integration-sync.webhook-security.default-max-body-bytes',
    'integration-sync.webhook-security.default-rate-limit-per-minute',
    'integration-sync.webhook-security.enabled',
    'integration-sync.webhook-security.nonce-cleanup-batch-size',
    'integration-sync.webhook-security.nonce-cleanup-interval-ms',
    'issue-projection.enabled',
    'issue-projection.max-attempts',
    'issue-projection.reconcile-batch-size',
    'issue-projection.reconcile-delay-ms',
    'issue-projection.retry-delay-seconds'
  ) and status in ('MIGRATED','LEGACY_RETIRED')) then raise exception 'C3R2F_PREMATURE_SINGLE_AUTHORITY_CUTOVER'; end if;
end $$;
