-- Phase 3E: durable Provider Projection Outbox, claim lease, attempt evidence, readback verification and governed dead-letter replay.
-- PostgreSQL 18 provides pg_catalog.sha256(bytea) as a core function. Phase 3E deliberately
-- avoids extension provisioning so Flyway and runtime roles remain least-privileged.
create table if not exists issue_projection_outbox_reliability(
 tenant_id varchar(64) not null,outbox_id varchar(128) not null,projection_id varchar(160) not null,
 operation_sequence bigint not null,projection_version bigint not null,canonical_document_hash varchar(128) not null,
 mapping_version integer not null,credential_version varchar(128) not null,provider_request_fingerprint varchar(128) not null,
 status varchar(32) not null default 'PENDING',claim_owner varchar(160),claim_token_hash varchar(128),claim_until timestamptz,
 heartbeat_at timestamptz,row_version bigint not null default 1,retry_after_at timestamptz,rate_limit_reset_at timestamptz,
 verification_mode varchar(32) not null default 'READBACK_ON_UNCERTAIN',external_idempotency_marker varchar(255) not null,
 last_attempt_id varchar(160),last_error_code varchar(128),last_error_message text,sent_at timestamptz,acknowledged_at timestamptz,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(tenant_id,outbox_id),
 unique(tenant_id,external_idempotency_marker),foreign key(tenant_id,outbox_id) references integration_outbox(tenant_id,outbox_id),
 check(status in('PENDING','CLAIMED','SENDING','SENT','VERIFYING','ACKNOWLEDGED','FAILED_RETRYABLE','DEAD_LETTER','CANCELLED')),
 check(operation_sequence>0 and projection_version>0 and mapping_version>0 and row_version>0),
 check((claim_owner is null and claim_token_hash is null and claim_until is null) or (claim_owner is not null and claim_token_hash is not null and claim_until is not null)),
 check((status='ACKNOWLEDGED' and acknowledged_at is not null) or status<>'ACKNOWLEDGED')
);
insert into issue_projection_outbox_reliability(tenant_id,outbox_id,projection_id,operation_sequence,projection_version,canonical_document_hash,mapping_version,credential_version,provider_request_fingerprint,status,retry_after_at,verification_mode,external_idempotency_marker,sent_at,acknowledged_at,created_at,updated_at)
select o.tenant_id,o.outbox_id,coalesce(p.projection_id,o.aggregate_id),coalesce(p.operation_sequence,1),coalesce(p.projection_version,1),coalesce(p.canonical_document_hash,o.payload_hash),coalesce(p.project_mapping_version,1),'LEGACY_UNRESOLVED',pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(coalesce(p.projection_id,o.aggregate_id)||'|'||coalesce(p.operation_sequence,1)::text||'|'||coalesce(p.projection_version,1)::text||'|'||coalesce(p.canonical_document_hash,o.payload_hash)||'|LEGACY_UNRESOLVED','UTF8')),'hex'),case o.status when 'COMPLETED' then 'ACKNOWLEDGED' when 'DEAD_LETTER' then 'DEAD_LETTER' when 'CANCELLED' then 'CANCELLED' when 'FAILED_RETRYABLE' then 'FAILED_RETRYABLE' else 'PENDING' end,o.next_attempt_at,'READBACK_ON_UNCERTAIN','opendispatch:'||coalesce(p.projection_id,o.aggregate_id)||':'||coalesce(p.operation_sequence,1)::text||':'||coalesce(p.projection_version,1)::text,case when o.status='COMPLETED' then o.updated_at end,case when o.status='COMPLETED' then coalesce(o.completed_at,o.updated_at) end,o.created_at,o.updated_at
from integration_outbox o left join issue_projection_states p on p.tenant_id=o.tenant_id and p.task_issue_link_id=o.task_issue_link_id
on conflict(tenant_id,outbox_id) do nothing;
create index if not exists idx_projection_outbox_due_p3e on issue_projection_outbox_reliability(status,coalesce(rate_limit_reset_at,retry_after_at,created_at),created_at) where status in('PENDING','FAILED_RETRYABLE','VERIFYING');
create index if not exists idx_projection_outbox_claim_p3e on issue_projection_outbox_reliability(claim_until,claim_owner) where status in('CLAIMED','SENDING','SENT','VERIFYING');
create table if not exists issue_projection_provider_attempts(tenant_id varchar(64) not null,attempt_id varchar(160) not null,outbox_id varchar(128) not null,projection_id varchar(160) not null,attempt_no integer not null,operation_sequence bigint not null,projection_version bigint not null,canonical_document_hash varchar(128) not null,mapping_version integer not null,credential_version varchar(128) not null,provider_request_fingerprint varchar(128) not null,external_idempotency_marker varchar(255) not null,worker_id varchar(160),status varchar(40) not null,provider_status integer,retryable boolean not null,error_code varchar(128),response_summary text,retry_after_at timestamptz,started_at timestamptz not null,completed_at timestamptz,correlation_id varchar(128),primary key(tenant_id,attempt_id),unique(tenant_id,outbox_id,attempt_no),foreign key(tenant_id,outbox_id) references issue_projection_outbox_reliability(tenant_id,outbox_id));
create table if not exists issue_projection_readback_evidence(tenant_id varchar(64) not null,evidence_id varchar(160) not null,outbox_id varchar(128) not null,projection_id varchar(160) not null,external_idempotency_marker varchar(255) not null,status varchar(32) not null,external_issue_id varchar(255),external_issue_key varchar(255),observed_fingerprint varchar(128),reason_code varchar(128),safe_summary text,observed_at timestamptz not null,correlation_id varchar(128),primary key(tenant_id,evidence_id),foreign key(tenant_id,outbox_id) references issue_projection_outbox_reliability(tenant_id,outbox_id),check(status in('MATCHED','NOT_FOUND','CONFLICT','RETRYABLE_FAILURE')));
create or replace function phase3e_immutable_evidence() returns trigger language plpgsql as $$ begin raise exception 'PHASE3E_PROVIDER_EVIDENCE_IMMUTABLE'; end $$;
drop trigger if exists trg_phase3e_attempt_immutable on issue_projection_provider_attempts;create trigger trg_phase3e_attempt_immutable before update or delete on issue_projection_provider_attempts for each row execute function phase3e_immutable_evidence();
drop trigger if exists trg_phase3e_readback_immutable on issue_projection_readback_evidence;create trigger trg_phase3e_readback_immutable before update or delete on issue_projection_readback_evidence for each row execute function phase3e_immutable_evidence();
create or replace function phase3e_outbox_guard() returns trigger language plpgsql as $$ begin
 if old.tenant_id is distinct from new.tenant_id or old.outbox_id is distinct from new.outbox_id or old.projection_id is distinct from new.projection_id or old.operation_sequence is distinct from new.operation_sequence or old.projection_version is distinct from new.projection_version or old.canonical_document_hash is distinct from new.canonical_document_hash or old.mapping_version is distinct from new.mapping_version or old.credential_version is distinct from new.credential_version or old.provider_request_fingerprint is distinct from new.provider_request_fingerprint or old.external_idempotency_marker is distinct from new.external_idempotency_marker then raise exception 'PHASE3E_OUTBOX_BINDING_IMMUTABLE'; end if;
 if new.row_version<>old.row_version+1 then raise exception 'PHASE3E_OUTBOX_VERSION_CONFLICT'; end if;
 if not(new.status=old.status or (old.status in('PENDING','FAILED_RETRYABLE','VERIFYING') and new.status='CLAIMED') or (old.status='CLAIMED' and new.status in('SENDING','VERIFYING','FAILED_RETRYABLE','DEAD_LETTER','CANCELLED')) or (old.status='SENDING' and new.status in('SENT','VERIFYING','FAILED_RETRYABLE','DEAD_LETTER')) or (old.status='SENT' and new.status in('VERIFYING','ACKNOWLEDGED','FAILED_RETRYABLE','DEAD_LETTER')) or (old.status='VERIFYING' and new.status in('ACKNOWLEDGED','FAILED_RETRYABLE','DEAD_LETTER'))) then raise exception 'PHASE3E_OUTBOX_STATE_TRANSITION_DENIED: % -> %',old.status,new.status; end if;
 return new; end $$;
drop trigger if exists trg_phase3e_outbox_guard on issue_projection_outbox_reliability;create trigger trg_phase3e_outbox_guard before update on issue_projection_outbox_reliability for each row execute function phase3e_outbox_guard();
comment on column issue_projection_outbox_reliability.provider_request_fingerprint is 'Binds projection, operation sequence, projection version, canonical document hash, mapping version and credential version.';
comment on column issue_projection_outbox_reliability.external_idempotency_marker is 'Provider-visible marker used for response-loss readback verification; contains no secret.';
