package com.opensocket.aievent.database.persistence.issuerelay.dao;
import java.time.OffsetDateTime; import java.util.List; import org.apache.ibatis.annotations.Mapper; import org.apache.ibatis.annotations.Param; import com.opensocket.aievent.database.persistence.issuerelay.*;
@Mapper public interface RelayGovernanceDao {
 int upsertRelation(@Param("value")CanonicalIssueRelationPo value); int updateRelationExpectedVersion(@Param("value")CanonicalIssueRelationPo value,@Param("expectedVersion")long expectedVersion); CanonicalIssueRelationPo findRelation(@Param("tenantId")String tenantId,@Param("relationId")String relationId); List<CanonicalIssueRelationPo> listRelations(@Param("tenantId")String tenantId,@Param("status")String status,@Param("limit")int limit);
 int upsertTopology(@Param("value")RelayTopologyPo value); int updateTopologyExpectedVersion(@Param("value")RelayTopologyPo value,@Param("expectedVersion")long expectedVersion); RelayTopologyPo findTopology(@Param("tenantId")String tenantId,@Param("topologyId")String topologyId); List<RelayTopologyPo> listTopologies(@Param("tenantId")String tenantId,@Param("status")String status,@Param("limit")int limit);
 int upsertEdge(@Param("value")RelayEdgePo value); int updateEdgeExpectedVersion(@Param("value")RelayEdgePo value,@Param("expectedVersion")long expectedVersion); RelayEdgePo findEdge(@Param("tenantId")String tenantId,@Param("edgeId")String edgeId); List<RelayEdgePo> listEdges(@Param("tenantId")String tenantId,@Param("topologyId")String topologyId,@Param("status")String status,@Param("limit")int limit); List<RelayEdgePo> claimDueEdges(@Param("tenantId")String tenantId,@Param("dueAt")OffsetDateTime dueAt,@Param("limit")int limit);
 int upsertCompensation(@Param("value")RelayCompensationPo value); int updateCompensationExpectedVersion(@Param("value")RelayCompensationPo value,@Param("expectedVersion")long expectedVersion); RelayCompensationPo findCompensation(@Param("tenantId")String tenantId,@Param("compensationId")String compensationId); List<RelayCompensationPo> listCompensations(@Param("tenantId")String tenantId,@Param("topologyId")String topologyId,@Param("status")String status,@Param("limit")int limit);
 int insertEvent(@Param("value")RelayEventPo value); RelayEventPo latestEvent(@Param("tenantId")String tenantId,@Param("aggregateType")String aggregateType,@Param("aggregateId")String aggregateId); List<RelayEventPo> listEvents(@Param("tenantId")String tenantId,@Param("aggregateType")String aggregateType,@Param("aggregateId")String aggregateId,@Param("limit")int limit);
}
