'use client';
import { useCallback,useEffect,useState } from 'react';
import { platformGovernanceApi } from '@/lib/api/platformGovernanceApi';
import type { Phase5RuntimeCertificationEvidence,ShadowPipelineReadiness,ShadowRetentionRun,ShadowStorageReadiness } from '@/lib/iam/types';

export function Phase5RuntimeOperationsPanel({auditReason}:{auditReason:string}){
 const [pipeline,setPipeline]=useState<ShadowPipelineReadiness|null>(null),[storage,setStorage]=useState<ShadowStorageReadiness|null>(null),[runs,setRuns]=useState<ShadowRetentionRun[]>([]),[evidence,setEvidence]=useState<Phase5RuntimeCertificationEvidence[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{try{const [p,s,r,e]=await Promise.all([platformGovernanceApi.shadowPipelineReadiness(),platformGovernanceApi.shadowStorageReadiness(),platformGovernanceApi.shadowRetentionRuns(20),platformGovernanceApi.phase5RuntimeCertificationEvidence(20)]);setPipeline(p);setStorage(s);setRuns(r);setEvidence(e);setError('');}catch(ex){setError(ex instanceof Error?ex.message:'Unable to load Phase 5 runtime operations.');}},[]);
 useEffect(()=>{void load();},[load]);
 async function process(){try{setBusy(true);await platformGovernanceApi.processShadowPipeline(500,auditReason);await load();}catch(ex){setError(ex instanceof Error?ex.message:'Unable to process the Shadow pipeline.');}finally{setBusy(false);}}
 async function retain(){try{setBusy(true);await platformGovernanceApi.runShadowRetention(auditReason);await load();}catch(ex){setError(ex instanceof Error?ex.message:'Unable to run retention.');}finally{setBusy(false);}}
 return <section className="space-y-3 rounded-2xl border bg-slate-50 p-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black">Observation pipeline and storage</h3><p className="text-xs text-slate-500">Metrics, durable mismatches, sampled matches, backpressure, partitions and runtime certification evidence.</p></div><div className="flex gap-2"><button disabled={busy||!auditReason.trim()} onClick={()=>void process()} className="rounded-xl bg-blue-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Process 500</button><button disabled={busy||!auditReason.trim()} onClick={()=>void retain()} className="rounded-xl bg-slate-950 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">Run retention</button></div></div>
  {error?<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-bold text-rose-700">{error}</div>:null}
  <div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6">
   <Metric label="Queue" value={pipeline?`${pipeline.pendingCount}/${pipeline.queueCapacity}`:'—'}/><Metric label="Processed 24h" value={pipeline?.processed24h??'—'}/><Metric label="Dropped 24h" value={pipeline?.dropped24h??'—'}/><Metric label="Durable mismatch" value={storage?.durableMismatchRows??'—'}/><Metric label="Sampled match" value={storage?.sampledMatchRows??'—'}/><Metric label="Dead letters 24h" value={pipeline?.deadLetters24h??'—'}/>
  </div>
  <div className="grid gap-3 lg:grid-cols-2"><div className="rounded-xl border bg-white p-3 text-sm"><b>Storage partitions</b><div className="mt-2 grid grid-cols-2 gap-1"><span>Durable</span><span>{storage?.durablePartitions??'—'}</span><span>Sampled</span><span>{storage?.sampledPartitions??'—'}</span><span>Dead letter</span><span>{storage?.deadLetterPartitions??'—'}</span><span>Archived</span><span>{storage?.archivedPartitions??'—'}</span><span>Overdue purge</span><span>{storage?.overdueArchivePurges??'—'}</span><span>Last retention</span><span>{storage?.lastRetentionCompletedAt??'Never'}</span></div></div><div className="rounded-xl border bg-white p-3 text-sm"><b>Latest runtime certification</b>{evidence[0]?<div className="mt-2"><div className={`font-black ${evidence[0].status==='CERTIFIED'?'text-emerald-700':'text-amber-700'}`}>{evidence[0].status}</div><div>PostgreSQL clean: {evidence[0].postgresqlCleanStatus}</div><div>Upgrade: {evidence[0].postgresqlUpgradeStatus}</div><div>Application context: {evidence[0].applicationContextStatus}</div><div>Admin UI: {evidence[0].adminUiBuildStatus}</div><div>Playwright: {evidence[0].playwrightStatus}</div><div>Load test: {evidence[0].loadTestStatus}</div></div>:<div className="mt-2 text-slate-500">No immutable runtime evidence generated.</div>}</div></div>
  {runs[0]?<details className="rounded-xl border bg-white p-3 text-xs"><summary className="font-bold">Latest retention run: {runs[0].status}</summary><pre className="mt-2 overflow-x-auto whitespace-pre-wrap">{runs[0].detailsJson}</pre></details>:null}
 </section>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-xl border bg-white p-3"><div className="text-xs uppercase text-slate-500">{label}</div><div className="mt-1 text-xl font-black">{value}</div></div>}
