package com.opensocket.aievent.core.iam.api.controller;
import com.opensocket.aievent.core.iam.api.application.service.IamEntryPointAuthorityAdministrationService;import com.opensocket.aievent.core.iam.api.context.IamApiRequestContextFactory;import com.opensocket.aievent.core.iam.api.request.*;import com.opensocket.aievent.core.iam.api.response.*;import com.opensocket.aievent.core.iam.api.security.*;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import java.util.List;import org.springframework.boot.autoconfigure.condition.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;
@RestController
@RequestMapping("/api/admin/access/platform/permission-readiness")
@ConditionalOnBean({IamEntryPointAuthorityAdministrationService.class,IamPermissionGuard.class})
@ConditionalOnProperty(prefix="aeg.iam.api",name="enabled",havingValue="true")
public class IamEntryPointAuthorityController {
 private final IamEntryPointAuthorityAdministrationService service;private final IamPermissionGuard guard;private final IamApiRequestContextFactory contexts;
 public IamEntryPointAuthorityController(IamEntryPointAuthorityAdministrationService s,IamPermissionGuard g,IamApiRequestContextFactory c){service=s;guard=g;contexts=c;}
 @GetMapping("/summary") public EntryPointBurnDownSummaryResponse summary(HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.ENTRY_POINT_READ,"ENTRY_POINT_INVENTORY","SUMMARY");return service.summary();}
 @GetMapping("/entry-points") public List<EntryPointAuthorityResponse> entries(@RequestParam(defaultValue="") String text,@RequestParam(defaultValue="") String state,@RequestParam(defaultValue="") String ownerModule,@RequestParam(defaultValue="200") int limit,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.ENTRY_POINT_READ,"ENTRY_POINT_INVENTORY","");return service.entries(text,state,ownerModule,limit);}
 @PutMapping("/entry-points/{entryPointId}") public EntryPointAuthorityResponse updateEntry(@PathVariable String entryPointId,@RequestHeader("If-Match") String ifMatch,@Valid @RequestBody UpdateEntryPointAuthorityRequest body,HttpServletRequest r){var c=contexts.from(r);c.requireAuditReason();guard.requireInstance(c,IamPermissions.ENTRY_POINT_MANAGE,"ENTRY_POINT",entryPointId);return service.updateEntry(entryPointId,body,c.requireExpectedVersion(ifMatch),c);}
 @GetMapping("/legacy-mappings") public List<LegacyAuthorityMappingResponse> mappings(@RequestParam(defaultValue="") String status,@RequestParam(defaultValue="200") int limit,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.ENTRY_POINT_READ,"LEGACY_MAPPING","");return service.mappings(status,limit);}
 @PutMapping("/legacy-mappings/{mappingId}") public LegacyAuthorityMappingResponse updateMapping(@PathVariable String mappingId,@RequestHeader("If-Match") String ifMatch,@Valid @RequestBody UpdateLegacyAuthorityMappingRequest body,HttpServletRequest r){var c=contexts.from(r);c.requireAuditReason();guard.requireInstance(c,IamPermissions.LEGACY_MAPPING_MANAGE,"LEGACY_MAPPING",mappingId);return service.updateMapping(mappingId,body,c.requireExpectedVersion(ifMatch),c);}
 @GetMapping("/bypasses") public List<EntryPointBypassResponse> bypasses(@RequestParam(defaultValue="") String status,@RequestParam(defaultValue="200") int limit,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.ENTRY_POINT_READ,"ENTRY_POINT_BYPASS","");return service.bypasses(status,limit);}
 @PostMapping("/bypasses") public ResponseEntity<EntryPointBypassResponse> createBypass(@Valid @RequestBody CreateEntryPointBypassRequest body,HttpServletRequest r){var c=contexts.from(r);c.requireAuditReason();guard.requireInstance(c,IamPermissions.BYPASS_MANAGE,"ENTRY_POINT_BYPASS",body.entryPointId());return ResponseEntity.status(201).body(service.createBypass(body,c));}
 @PostMapping("/bypasses/{bypassId}/revoke") public EntryPointBypassResponse revokeBypass(@PathVariable String bypassId,@RequestHeader("If-Match") String ifMatch,@Valid @RequestBody RevokeEntryPointBypassRequest body,HttpServletRequest r){var c=contexts.from(r);c.requireAuditReason();guard.requireInstance(c,IamPermissions.BYPASS_MANAGE,"ENTRY_POINT_BYPASS",bypassId);return service.revokeBypass(bypassId,body,c.requireExpectedVersion(ifMatch),c);}
 @GetMapping("/manifests") public List<ApplicationPermissionManifestResponse> manifests(@RequestParam(defaultValue="50") int limit,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.PERMISSION_MANIFEST_READ,"APPLICATION_PERMISSION_MANIFEST","");return service.manifests(limit);}
 @GetMapping("/manifests/{manifestId}") public ApplicationPermissionManifestResponse manifest(@PathVariable String manifestId,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.PERMISSION_MANIFEST_READ,"APPLICATION_PERMISSION_MANIFEST",manifestId);return service.manifest(manifestId);}
 @GetMapping("/manifests/{manifestId}/entries") public List<ApplicationPermissionManifestEntryResponse> manifestEntries(@PathVariable String manifestId,@RequestParam(defaultValue="") String driftStatus,@RequestParam(defaultValue="200") int limit,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.PERMISSION_MANIFEST_READ,"APPLICATION_PERMISSION_MANIFEST",manifestId);return service.manifestEntries(manifestId,driftStatus,limit);}
 @GetMapping("/manifests/{manifestId}/drift") public PermissionManifestDriftSummaryResponse manifestDrift(@PathVariable String manifestId,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.PERMISSION_COVERAGE_READ,"PERMISSION_COVERAGE_EVIDENCE",manifestId);return service.manifestDrift(manifestId);}
 @GetMapping("/coverage-evidence") public List<PermissionCoverageEvidenceResponse> coverageEvidence(@RequestParam(defaultValue="50") int limit,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.PERMISSION_COVERAGE_READ,"PERMISSION_COVERAGE_EVIDENCE","");return service.coverageEvidence(limit);}
 @PostMapping("/manifests") public ResponseEntity<ApplicationPermissionManifestResponse> registerManifest(@Valid @RequestBody RegisterApplicationPermissionManifestRequest body,HttpServletRequest r){var c=contexts.from(r);c.requireAuditReason();guard.requireInstance(c,IamPermissions.PERMISSION_MANIFEST_REGISTER,"APPLICATION_PERMISSION_MANIFEST",body.applicationId());return ResponseEntity.status(201).body(service.registerManifest(body,c));}
 @GetMapping("/shadow/summary") public ShadowObservationSummaryResponse shadowSummary(@RequestParam String tenantId,@RequestParam(defaultValue="") String domainCode,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.SHADOW_READ,"SHADOW_OBSERVATION",tenantId);return service.shadowSummary(tenantId,domainCode);}
 @GetMapping("/shadow/observations") public List<ShadowObservationResponse> shadowObservations(@RequestParam String tenantId,@RequestParam(defaultValue="") String domainCode,@RequestParam(defaultValue="") String category,@RequestParam(defaultValue="200") int limit,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.SHADOW_READ,"SHADOW_OBSERVATION",tenantId);return service.shadowObservations(tenantId,domainCode,category,limit);}
 @GetMapping("/mismatch-cases") public List<ShadowMismatchCaseResponse> mismatchCases(@RequestParam String tenantId,@RequestParam(defaultValue="") String domainCode,@RequestParam(defaultValue="") String status,@RequestParam(defaultValue="200") int limit,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.MISMATCH_READ,"MISMATCH_CASE",tenantId);return service.mismatchCases(tenantId,domainCode,status,limit);}
 @PostMapping("/mismatch-cases") public ResponseEntity<ShadowMismatchCaseResponse> createMismatchCase(@Valid @RequestBody CreateMismatchCaseRequest body,HttpServletRequest r){var c=contexts.from(r);c.requireAuditReason();guard.requireInstance(c,IamPermissions.MISMATCH_MANAGE,"MISMATCH_CASE",body.comparisonId());return ResponseEntity.status(201).body(service.createMismatchCase(body,c));}
 @PutMapping("/mismatch-cases/{caseId}") public ShadowMismatchCaseResponse updateMismatchCase(@PathVariable String caseId,@RequestHeader("If-Match") String ifMatch,@Valid @RequestBody UpdateMismatchCaseRequest body,HttpServletRequest r){var c=contexts.from(r);c.requireAuditReason();guard.requireInstance(c,IamPermissions.MISMATCH_MANAGE,"MISMATCH_CASE",caseId);return service.updateMismatchCase(caseId,body,c.requireExpectedVersion(ifMatch),c);}
 @PostMapping("/mismatch-cases/{caseId}/waivers") public ResponseEntity<ShadowMismatchWaiverResponse> createMismatchWaiver(@PathVariable String caseId,@Valid @RequestBody CreateMismatchWaiverRequest body,HttpServletRequest r){var c=contexts.from(r);c.requireAuditReason();guard.requireInstance(c,IamPermissions.MISMATCH_WAIVE,"MISMATCH_WAIVER",caseId);return ResponseEntity.status(201).body(service.createMismatchWaiver(caseId,body,c));}
 @PostMapping("/mismatch-cases/{caseId}/regressions") public ResponseEntity<ShadowRegressionEvidenceResponse> addRegressionEvidence(@PathVariable String caseId,@Valid @RequestBody AddRegressionEvidenceRequest body,HttpServletRequest r){var c=contexts.from(r);c.requireAuditReason();guard.requireInstance(c,IamPermissions.MISMATCH_MANAGE,"MISMATCH_REGRESSION",caseId);return ResponseEntity.status(201).body(service.addRegressionEvidence(caseId,body,c));}
 @GetMapping("/domain-readiness") public List<DomainReadinessEvidenceResponse> domainReadiness(@RequestParam String tenantId,@RequestParam(defaultValue="") String domainCode,@RequestParam(defaultValue="50") int limit,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.DOMAIN_READINESS_READ,"DOMAIN_READINESS",tenantId);return service.domainReadiness(tenantId,domainCode,limit);}
 @PostMapping("/domain-readiness/evaluate") public ResponseEntity<DomainReadinessEvidenceResponse> evaluateDomainReadiness(@Valid @RequestBody EvaluateDomainReadinessRequest body,HttpServletRequest r){var c=contexts.from(r);c.requireAuditReason();guard.requireInstance(c,IamPermissions.DOMAIN_READINESS_EVALUATE,"DOMAIN_READINESS",body.tenantId());return ResponseEntity.status(201).body(service.evaluateDomainReadiness(body,c));}
 @GetMapping("/phase6-eligibility") public List<Phase6EligibilityEvidenceResponse> phase6Eligibility(@RequestParam String tenantId,@RequestParam(defaultValue="50") int limit,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.PHASE6_ELIGIBILITY_READ,"PHASE6_ELIGIBILITY",tenantId);return service.phase6Eligibility(tenantId,limit);}
 @PostMapping("/phase6-eligibility/evaluate") public ResponseEntity<Phase6EligibilityEvidenceResponse> evaluatePhase6Eligibility(@Valid @RequestBody EvaluatePhase6EligibilityRequest body,HttpServletRequest r){var c=contexts.from(r);c.requireAuditReason();guard.requireInstance(c,IamPermissions.PHASE6_ELIGIBILITY_EVALUATE,"PHASE6_ELIGIBILITY",body.tenantId());return ResponseEntity.status(201).body(service.evaluatePhase6Eligibility(body,c));}
 @GetMapping("/shadow/pipeline") public ShadowPipelineReadinessResponse shadowPipelineReadiness(HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.PIPELINE_READ,"SHADOW_PIPELINE","SUMMARY");return service.shadowPipelineReadiness();}
 @GetMapping("/shadow/storage") public ShadowStorageReadinessResponse shadowStorageReadiness(HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.STORAGE_READ,"SHADOW_STORAGE","SUMMARY");return service.shadowStorageReadiness();}
 @GetMapping("/shadow/retention-runs") public List<ShadowRetentionRunResponse> shadowRetentionRuns(@RequestParam(defaultValue="50") int limit,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.STORAGE_READ,"SHADOW_RETENTION","LIST");return service.shadowRetentionRuns(limit);}
 @PostMapping("/shadow/pipeline/process") public String processShadowPipeline(@Valid @RequestBody ProcessShadowPipelineRequest body,HttpServletRequest r){var c=contexts.from(r);c.requireAuditReason();guard.requireInstance(c,IamPermissions.PIPELINE_MANAGE,"SHADOW_PIPELINE","PROCESS");return service.processShadowPipeline(body,c);}
 @PostMapping("/shadow/storage/retention") public ResponseEntity<ShadowRetentionRunResponse> runShadowRetention(@Valid @RequestBody RunShadowRetentionRequest body,HttpServletRequest r){var c=contexts.from(r);c.requireAuditReason();guard.requireInstance(c,IamPermissions.STORAGE_MANAGE,"SHADOW_RETENTION","RUN");return ResponseEntity.status(201).body(service.runShadowRetention(body,c));}
 @GetMapping("/runtime-certification") public List<Phase5RuntimeCertificationEvidenceResponse> phase5RuntimeCertificationEvidence(@RequestParam(defaultValue="50") int limit,HttpServletRequest r){var c=contexts.from(r);guard.requireInstance(c,IamPermissions.RUNTIME_EVIDENCE_READ,"PHASE5_RUNTIME_CERTIFICATION","LIST");return service.phase5RuntimeCertificationEvidence(limit);}
 @PostMapping("/runtime-certification") public ResponseEntity<Phase5RuntimeCertificationEvidenceResponse> generatePhase5RuntimeCertificationEvidence(@Valid @RequestBody GeneratePhase5RuntimeCertificationRequest body,HttpServletRequest r){var c=contexts.from(r);c.requireAuditReason();guard.requireInstance(c,IamPermissions.RUNTIME_EVIDENCE_GENERATE,"PHASE5_RUNTIME_CERTIFICATION",body.sourceVersion());return ResponseEntity.status(201).body(service.generatePhase5RuntimeCertificationEvidence(body,c));}

}
