package com.opensocket.aievent.database.persistence.issuesync;
import java.util.*;import java.time.OffsetDateTime;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import com.opensocket.aievent.core.integration.issue.*;import com.opensocket.aievent.database.persistence.issuesync.dao.ProjectionOutboxReliabilityDao;import com.opensocket.aievent.database.persistence.issuesync.po.*;import com.opensocket.aievent.database.persistence.spi.DatabaseRepositoryAdapter;
@DatabaseRepositoryAdapter @ConditionalOnProperty(prefix="integration-sync",name="store",havingValue="MYBATIS")
public class MybatisProjectionOutboxReliabilityRepository implements ProjectionOutboxReliabilityRepository {
 private final ProjectionOutboxReliabilityDao dao; public MybatisProjectionOutboxReliabilityRepository(ProjectionOutboxReliabilityDao dao){this.dao=dao;}
 public ProjectionOutboxReliability save(ProjectionOutboxReliability v){if(dao.insert(po(v))!=1)throw new IllegalStateException("PROJECTION_OUTBOX_ALREADY_EXISTS");return v;}
 public ProjectionOutboxReliability saveExpectedVersion(ProjectionOutboxReliability v,long e){if(dao.updateCas(po(v),e)!=1)throw new IllegalStateException("PROJECTION_OUTBOX_VERSION_CONFLICT");return v;}
 public Optional<ProjectionOutboxReliability> find(String t,String o){return Optional.ofNullable(dao.find(t,o)).map(this::domain);}
 public List<ProjectionOutboxReliability> claimDue(String w,OffsetDateTime n,OffsetDateTime u,int l){return dao.claimDue(w,n,u,Math.max(1,Math.min(l,200))).stream().map(this::domain).toList();}
 public boolean heartbeat(String t,String o,String w,String h,long e,OffsetDateTime at,OffsetDateTime u){return dao.heartbeat(t,o,w,h,e,at,u)==1;}
 public List<ProjectionOutboxReliability> list(String t,ProjectionOutboxReliabilityStatus s,int l){return dao.list(t,s==null?null:s.name(),Math.max(1,Math.min(l,500))).stream().map(this::domain).toList();}
 public ProjectionProviderAttemptEvidence appendAttempt(ProjectionProviderAttemptEvidence v){dao.insertAttempt(at(v));return v;} public List<ProjectionProviderAttemptEvidence> listAttempts(String t,String o,int l){return dao.listAttempts(t,o,Math.max(1,Math.min(l,500))).stream().map(this::at).toList();}
 public ProjectionReadbackEvidence appendReadback(ProjectionReadbackEvidence v){dao.insertReadback(rb(v));return v;} public List<ProjectionReadbackEvidence> listReadbacks(String t,String o,int l){return dao.listReadbacks(t,o,Math.max(1,Math.min(l,500))).stream().map(this::rb).toList();}
 public String mode(){return "MYBATIS";}
 private ProjectionOutboxReliabilityPo po(ProjectionOutboxReliability v){var p=new ProjectionOutboxReliabilityPo();p.setTenantId(v.tenantId());p.setOutboxId(v.outboxId());p.setProjectionId(v.projectionId());p.setOperationSequence(v.operationSequence());p.setProjectionVersion(v.projectionVersion());p.setCanonicalDocumentHash(v.canonicalDocumentHash());p.setMappingVersion(v.mappingVersion());p.setCredentialVersion(v.credentialVersion());p.setProviderRequestFingerprint(v.providerRequestFingerprint());p.setStatus(v.status().name());p.setClaimOwner(v.claimOwner());p.setClaimTokenHash(v.claimTokenHash());p.setClaimUntil(v.claimUntil());p.setHeartbeatAt(v.heartbeatAt());p.setRowVersion(v.rowVersion());p.setRetryAfterAt(v.retryAfterAt());p.setRateLimitResetAt(v.rateLimitResetAt());p.setVerificationMode(v.verificationMode());p.setExternalIdempotencyMarker(v.externalIdempotencyMarker());p.setLastAttemptId(v.lastAttemptId());p.setLastErrorCode(v.lastErrorCode());p.setLastErrorMessage(v.lastErrorMessage());p.setSentAt(v.sentAt());p.setAcknowledgedAt(v.acknowledgedAt());p.setCreatedAt(v.createdAt());p.setUpdatedAt(v.updatedAt());return p;}
 private ProjectionOutboxReliability domain(ProjectionOutboxReliabilityPo p){return new ProjectionOutboxReliability(p.getTenantId(),p.getOutboxId(),p.getProjectionId(),p.getOperationSequence(),p.getProjectionVersion(),p.getCanonicalDocumentHash(),p.getMappingVersion(),p.getCredentialVersion(),p.getProviderRequestFingerprint(),ProjectionOutboxReliabilityStatus.valueOf(p.getStatus()),p.getClaimOwner(),p.getClaimTokenHash(),p.getClaimUntil(),p.getHeartbeatAt(),p.getRowVersion(),p.getRetryAfterAt(),p.getRateLimitResetAt(),p.getVerificationMode(),p.getExternalIdempotencyMarker(),p.getLastAttemptId(),p.getLastErrorCode(),p.getLastErrorMessage(),p.getSentAt(),p.getAcknowledgedAt(),p.getCreatedAt(),p.getUpdatedAt());}
 private ProjectionProviderAttemptEvidencePo at(ProjectionProviderAttemptEvidence v){var p=new ProjectionProviderAttemptEvidencePo();p.setTenantId(v.tenantId());p.setAttemptId(v.attemptId());p.setOutboxId(v.outboxId());p.setProjectionId(v.projectionId());p.setAttemptNo(v.attemptNo());p.setOperationSequence(v.operationSequence());p.setProjectionVersion(v.projectionVersion());p.setCanonicalDocumentHash(v.canonicalDocumentHash());p.setMappingVersion(v.mappingVersion());p.setCredentialVersion(v.credentialVersion());p.setProviderRequestFingerprint(v.providerRequestFingerprint());p.setExternalIdempotencyMarker(v.externalIdempotencyMarker());p.setWorkerId(v.workerId());p.setStatus(v.status());p.setProviderStatus(v.providerStatus());p.setRetryable(v.retryable());p.setErrorCode(v.errorCode());p.setResponseSummary(v.responseSummary());p.setRetryAfterAt(v.retryAfterAt());p.setStartedAt(v.startedAt());p.setCompletedAt(v.completedAt());p.setCorrelationId(v.correlationId());return p;}
 private ProjectionProviderAttemptEvidence at(ProjectionProviderAttemptEvidencePo p){return new ProjectionProviderAttemptEvidence(p.getTenantId(),p.getAttemptId(),p.getOutboxId(),p.getProjectionId(),p.getAttemptNo(),p.getOperationSequence(),p.getProjectionVersion(),p.getCanonicalDocumentHash(),p.getMappingVersion(),p.getCredentialVersion(),p.getProviderRequestFingerprint(),p.getExternalIdempotencyMarker(),p.getWorkerId(),p.getStatus(),p.getProviderStatus(),p.isRetryable(),p.getErrorCode(),p.getResponseSummary(),p.getRetryAfterAt(),p.getStartedAt(),p.getCompletedAt(),p.getCorrelationId());}
 private ProjectionReadbackEvidencePo rb(ProjectionReadbackEvidence v){var p=new ProjectionReadbackEvidencePo();p.setTenantId(v.tenantId());p.setEvidenceId(v.evidenceId());p.setOutboxId(v.outboxId());p.setProjectionId(v.projectionId());p.setExternalIdempotencyMarker(v.externalIdempotencyMarker());p.setStatus(v.status().name());p.setExternalIssueId(v.externalIssueId());p.setExternalIssueKey(v.externalIssueKey());p.setObservedFingerprint(v.observedFingerprint());p.setReasonCode(v.reasonCode());p.setSafeSummary(v.safeSummary());p.setObservedAt(v.observedAt());p.setCorrelationId(v.correlationId());return p;}
 private ProjectionReadbackEvidence rb(ProjectionReadbackEvidencePo p){return new ProjectionReadbackEvidence(p.getTenantId(),p.getEvidenceId(),p.getOutboxId(),p.getProjectionId(),p.getExternalIdempotencyMarker(),ProjectionReadbackStatus.valueOf(p.getStatus()),p.getExternalIssueId(),p.getExternalIssueKey(),p.getObservedFingerprint(),p.getReasonCode(),p.getSafeSummary(),p.getObservedAt(),p.getCorrelationId());}
}
