package com.opensocket.aievent.database.persistence.issuesync;

import java.util.*;
import java.time.OffsetDateTime;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import com.opensocket.aievent.core.integration.issue.*;
import com.opensocket.aievent.database.persistence.issuesync.dao.IssueSyncDao;
import com.opensocket.aievent.database.persistence.issuesync.po.*;
import com.opensocket.aievent.database.persistence.spi.DatabaseRepositoryAdapter;

@DatabaseRepositoryAdapter
@ConditionalOnProperty(prefix="integration-sync",name="store",havingValue="MYBATIS")
public class MybatisIssueSyncRepository implements IssueSyncRepository {
 private final IssueSyncDao dao; public MybatisIssueSyncRepository(IssueSyncDao dao){this.dao=dao;}
 public IssueRelationship saveRelationship(IssueRelationship v){dao.upsertRelationship(rel(v));return v;}
 public Optional<IssueRelationship> findRelationship(String t,String id){return Optional.ofNullable(dao.findRelationship(t,id)).map(this::rel);}
 public List<IssueRelationship> listRelationships(String t,String link,int n){return dao.listRelationships(t,link,limit(n)).stream().map(this::rel).toList();}
 public List<String> listDueTenants(OffsetDateTime now,int limit){return dao.listDueTenants(now,limit);}
 public IntegrationOutboxEntry saveOutbox(IntegrationOutboxEntry v){dao.upsertOutbox(out(v));return v;}
 public Optional<IntegrationOutboxEntry> findOutbox(String t,String id){return Optional.ofNullable(dao.findOutbox(t,id)).map(this::out);}
 public Optional<IntegrationOutboxEntry> findOutboxByIdempotencyKey(String t,String k){return Optional.ofNullable(dao.findOutboxByIdempotencyKey(t,k)).map(this::out);}
 public List<IntegrationOutboxEntry> claimDue(String t,String w,java.time.OffsetDateTime now,java.time.OffsetDateTime until,int n){return dao.claimDue(t,w,now,until,limit(n)).stream().map(this::out).toList();}
 public IntegrationInboxEntry saveInbox(IntegrationInboxEntry v){dao.upsertInbox(in(v));return v;}
 public Optional<IntegrationInboxEntry> findInboxByProviderEvent(String t,String c,String e){return Optional.ofNullable(dao.findInboxByProviderEvent(t,c,e)).map(this::in);}
 public List<IntegrationInboxEntry> listInbox(String t,int n){return dao.listInbox(t,limit(n)).stream().map(this::in).toList();}
 public IntegrationSyncAttempt saveAttempt(IntegrationSyncAttempt v){dao.insertAttempt(at(v));return v;}
 public List<IntegrationSyncAttempt> listAttempts(String t,String o,int n){return dao.listAttempts(t,o,limit(n)).stream().map(this::at).toList();}
 public IntegrationDeadLetter saveDeadLetter(IntegrationDeadLetter v){dao.upsertDeadLetter(dead(v));return v;}
 public Optional<IntegrationDeadLetter> findDeadLetter(String t,String id){return Optional.ofNullable(dao.findDeadLetter(t,id)).map(this::dead);}
 public Optional<IntegrationDeadLetter> findDeadLetterByOutbox(String t,String o){return Optional.ofNullable(dao.findDeadLetterByOutbox(t,o)).map(this::dead);}
 public List<IntegrationDeadLetter> listDeadLetters(String t,IntegrationDeadLetterStatus s,int n){return dao.listDeadLetters(t,s==null?null:s.name(),limit(n)).stream().map(this::dead).toList();}
 public IntegrationConflict saveConflict(IntegrationConflict v){dao.upsertConflict(conf(v));return v;}
 public Optional<IntegrationConflict> findConflict(String t,String id){return Optional.ofNullable(dao.findConflict(t,id)).map(this::conf);}
 public List<IntegrationConflict> listConflicts(String t,IntegrationConflictStatus s,int n){return dao.listConflicts(t,s==null?null:s.name(),limit(n)).stream().map(this::conf).toList();}
 public IntegrationCircuitBreaker saveCircuitBreaker(IntegrationCircuitBreaker v){dao.upsertCircuitBreaker(circuit(v));return v;}
 public Optional<IntegrationCircuitBreaker> findCircuitBreaker(String t,String c,String m){return Optional.ofNullable(dao.findCircuitBreaker(t,c,m)).map(this::circuit);}
 public String mode(){return "MYBATIS";} private int limit(int n){return Math.max(1,Math.min(n,1000));}
 private <E extends Enum<E>> E en(Class<E> c,String v,E d){try{return v==null?d:Enum.valueOf(c,v);}catch(Exception e){return d;}}
 private IssueRelationshipPo rel(IssueRelationship v){var p=new IssueRelationshipPo();p.setTenantId(v.tenantId());p.setRelationshipId(v.relationshipId());p.setFromTaskIssueLinkId(v.fromTaskIssueLinkId());p.setToTaskIssueLinkId(v.toTaskIssueLinkId());p.setRelationshipType(v.relationshipType().name());p.setProviderRelationId(v.providerRelationId());p.setSyncStatus(v.syncStatus().name());p.setPayloadHash(v.payloadHash());p.setIdempotencyKey(v.idempotencyKey());p.setLastErrorCode(v.lastErrorCode());p.setLastErrorMessage(v.lastErrorMessage());p.setResourceVersion(v.resourceVersion());p.setCreatedAt(v.createdAt());p.setUpdatedAt(v.updatedAt());return p;}
 private IssueRelationship rel(IssueRelationshipPo p){return new IssueRelationship(p.getTenantId(),p.getRelationshipId(),p.getFromTaskIssueLinkId(),p.getToTaskIssueLinkId(),en(IssueRelationshipType.class,p.getRelationshipType(),IssueRelationshipType.RELATES),p.getProviderRelationId(),en(IntegrationSyncStatus.class,p.getSyncStatus(),IntegrationSyncStatus.PENDING),p.getPayloadHash(),p.getIdempotencyKey(),p.getLastErrorCode(),p.getLastErrorMessage(),p.getResourceVersion(),p.getCreatedAt(),p.getUpdatedAt());}
 private IntegrationOutboxPo out(IntegrationOutboxEntry v){var p=new IntegrationOutboxPo();p.setTenantId(v.tenantId());p.setOutboxId(v.outboxId());p.setAggregateType(v.aggregateType());p.setAggregateId(v.aggregateId());p.setTaskId(v.taskId());p.setTaskIssueLinkId(v.taskIssueLinkId());p.setIssueRelationshipId(v.issueRelationshipId());p.setConnectionId(v.connectionId());p.setProjectMappingId(v.projectMappingId());p.setOperationType(v.operationType().name());p.setEventType(v.eventType());p.setPayloadJson(v.payloadJson());p.setPayloadHash(v.payloadHash());p.setIdempotencyKey(v.idempotencyKey());p.setStatus(v.status().name());p.setPriority(v.priority());p.setAttemptCount(v.attemptCount());p.setMaxAttempts(v.maxAttempts());p.setNextAttemptAt(v.nextAttemptAt());p.setClaimedBy(v.claimedBy());p.setClaimUntil(v.claimUntil());p.setLastErrorCode(v.lastErrorCode());p.setLastErrorMessage(v.lastErrorMessage());p.setCorrelationId(v.correlationId());p.setCausationId(v.causationId());p.setCreatedAt(v.createdAt());p.setUpdatedAt(v.updatedAt());p.setCompletedAt(v.completedAt());return p;}
 private IntegrationOutboxEntry out(IntegrationOutboxPo p){return new IntegrationOutboxEntry(p.getTenantId(),p.getOutboxId(),p.getAggregateType(),p.getAggregateId(),p.getTaskId(),p.getTaskIssueLinkId(),p.getIssueRelationshipId(),p.getConnectionId(),p.getProjectMappingId(),en(IntegrationOperationType.class,p.getOperationType(),IntegrationOperationType.ISSUE_CREATE),p.getEventType(),p.getPayloadJson(),p.getPayloadHash(),p.getIdempotencyKey(),en(IntegrationOutboxStatus.class,p.getStatus(),IntegrationOutboxStatus.PENDING),p.getPriority(),p.getAttemptCount(),p.getMaxAttempts(),p.getNextAttemptAt(),p.getClaimedBy(),p.getClaimUntil(),p.getLastErrorCode(),p.getLastErrorMessage(),p.getCorrelationId(),p.getCausationId(),p.getCreatedAt(),p.getUpdatedAt(),p.getCompletedAt());}
 private IntegrationInboxPo in(IntegrationInboxEntry v){var p=new IntegrationInboxPo();p.setTenantId(v.tenantId());p.setInboxId(v.inboxId());p.setConnectionId(v.connectionId());p.setProviderType(v.providerType());p.setProviderEventId(v.providerEventId());p.setEventType(v.eventType());p.setExternalProjectId(v.externalProjectId());p.setExternalIssueId(v.externalIssueId());p.setSignatureVerified(v.signatureVerified());p.setPayloadJson(v.payloadJson());p.setPayloadHash(v.payloadHash());p.setStatus(v.status().name());p.setReplayCount(v.replayCount());p.setReceivedAt(v.receivedAt());p.setProcessedAt(v.processedAt());p.setLastErrorCode(v.lastErrorCode());p.setLastErrorMessage(v.lastErrorMessage());p.setCorrelationId(v.correlationId());return p;}
 private IntegrationInboxEntry in(IntegrationInboxPo p){return new IntegrationInboxEntry(p.getTenantId(),p.getInboxId(),p.getConnectionId(),p.getProviderType(),p.getProviderEventId(),p.getEventType(),p.getExternalProjectId(),p.getExternalIssueId(),p.isSignatureVerified(),p.getPayloadJson(),p.getPayloadHash(),en(IntegrationInboxStatus.class,p.getStatus(),IntegrationInboxStatus.RECEIVED),p.getReplayCount(),p.getReceivedAt(),p.getProcessedAt(),p.getLastErrorCode(),p.getLastErrorMessage(),p.getCorrelationId());}
 private IntegrationSyncAttemptPo at(IntegrationSyncAttempt v){var p=new IntegrationSyncAttemptPo();p.setTenantId(v.tenantId());p.setAttemptId(v.attemptId());p.setOutboxId(v.outboxId());p.setAttemptNo(v.attemptNo());p.setWorkerId(v.workerId());p.setStatus(v.status());p.setProviderStatus(v.providerStatus());p.setRequestPayloadHash(v.requestPayloadHash());p.setResponseSummary(v.responseSummary());p.setRetryable(v.retryable());p.setErrorCode(v.errorCode());p.setErrorMessage(v.errorMessage());p.setStartedAt(v.startedAt());p.setCompletedAt(v.completedAt());p.setCorrelationId(v.correlationId());return p;}
 private IntegrationSyncAttempt at(IntegrationSyncAttemptPo p){return new IntegrationSyncAttempt(p.getTenantId(),p.getAttemptId(),p.getOutboxId(),p.getAttemptNo(),p.getWorkerId(),p.getStatus(),p.getProviderStatus(),p.getRequestPayloadHash(),p.getResponseSummary(),p.isRetryable(),p.getErrorCode(),p.getErrorMessage(),p.getStartedAt(),p.getCompletedAt(),p.getCorrelationId());}
 private IntegrationDeadLetterPo dead(IntegrationDeadLetter v){var p=new IntegrationDeadLetterPo();p.setTenantId(v.tenantId());p.setDeadLetterId(v.deadLetterId());p.setOutboxId(v.outboxId());p.setTaskId(v.taskId());p.setTaskIssueLinkId(v.taskIssueLinkId());p.setOperationType(v.operationType().name());p.setPayloadJson(v.payloadJson());p.setPayloadHash(v.payloadHash());p.setFailureCode(v.failureCode());p.setFailureMessage(v.failureMessage());p.setAttemptCount(v.attemptCount());p.setStatus(v.status().name());p.setOpenedAt(v.openedAt());p.setRetriedAt(v.retriedAt());p.setResolvedAt(v.resolvedAt());p.setResolvedBy(v.resolvedBy());p.setResolutionReason(v.resolutionReason());p.setCorrelationId(v.correlationId());return p;}
 private IntegrationDeadLetter dead(IntegrationDeadLetterPo p){return new IntegrationDeadLetter(p.getTenantId(),p.getDeadLetterId(),p.getOutboxId(),p.getTaskId(),p.getTaskIssueLinkId(),en(IntegrationOperationType.class,p.getOperationType(),IntegrationOperationType.ISSUE_CREATE),p.getPayloadJson(),p.getPayloadHash(),p.getFailureCode(),p.getFailureMessage(),p.getAttemptCount(),en(IntegrationDeadLetterStatus.class,p.getStatus(),IntegrationDeadLetterStatus.OPEN),p.getOpenedAt(),p.getRetriedAt(),p.getResolvedAt(),p.getResolvedBy(),p.getResolutionReason(),p.getCorrelationId());}
 private IntegrationConflictPo conf(IntegrationConflict v){var p=new IntegrationConflictPo();p.setTenantId(v.tenantId());p.setConflictId(v.conflictId());p.setTaskId(v.taskId());p.setTaskIssueLinkId(v.taskIssueLinkId());p.setInboxId(v.inboxId());p.setConflictType(v.conflictType());p.setTaskStatus(v.taskStatus());p.setExternalIssueStatus(v.externalIssueStatus());p.setDetailJson(v.detailJson());p.setStatus(v.status().name());p.setDetectedAt(v.detectedAt());p.setResolvedAt(v.resolvedAt());p.setResolvedBy(v.resolvedBy());p.setResolutionAction(v.resolutionAction());p.setResolutionReason(v.resolutionReason());p.setCorrelationId(v.correlationId());return p;}
 private IntegrationConflict conf(IntegrationConflictPo p){return new IntegrationConflict(p.getTenantId(),p.getConflictId(),p.getTaskId(),p.getTaskIssueLinkId(),p.getInboxId(),p.getConflictType(),p.getTaskStatus(),p.getExternalIssueStatus(),p.getDetailJson(),en(IntegrationConflictStatus.class,p.getStatus(),IntegrationConflictStatus.OPEN),p.getDetectedAt(),p.getResolvedAt(),p.getResolvedBy(),p.getResolutionAction(),p.getResolutionReason(),p.getCorrelationId());}
 private IntegrationCircuitBreakerPo circuit(IntegrationCircuitBreaker v){var p=new IntegrationCircuitBreakerPo();p.setTenantId(v.tenantId());p.setConnectionId(v.connectionId());p.setProjectMappingId(v.projectMappingId());p.setState(v.state().name());p.setConsecutiveFailures(v.consecutiveFailures());p.setFailureThreshold(v.failureThreshold());p.setOpenedAt(v.openedAt());p.setNextProbeAt(v.nextProbeAt());p.setLastSuccessAt(v.lastSuccessAt());p.setLastFailureAt(v.lastFailureAt());p.setLastErrorCode(v.lastErrorCode());p.setUpdatedAt(v.updatedAt());return p;}
 private IntegrationCircuitBreaker circuit(IntegrationCircuitBreakerPo p){return new IntegrationCircuitBreaker(p.getTenantId(),p.getConnectionId(),p.getProjectMappingId(),en(IntegrationCircuitState.class,p.getState(),IntegrationCircuitState.CLOSED),p.getConsecutiveFailures(),p.getFailureThreshold(),p.getOpenedAt(),p.getNextProbeAt(),p.getLastSuccessAt(),p.getLastFailureAt(),p.getLastErrorCode(),p.getUpdatedAt());}
}
