package com.opensocket.aievent.core.issuetracking.change;
public enum ProviderActionCandidateEventType { CANDIDATE_CREATED, REVIEW_STARTED, REAUTHENTICATION_VERIFIED, APPROVAL_GRANTED, APPROVAL_REJECTED, EXECUTION_REQUESTED, EXECUTION_STARTED, EXECUTION_SUCCEEDED, EXECUTION_FAILED, SUPERSEDED }
