package com.opensocket.aievent.core.integration.issue.webhook;
import java.io.*; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.*; import java.util.*;
import jakarta.servlet.*; import jakarta.servlet.http.*;
import org.springframework.http.MediaType; import org.springframework.security.core.context.*; import org.springframework.web.filter.OncePerRequestFilter;
import com.opensocket.aievent.core.integration.identity.*; import tools.jackson.databind.ObjectMapper;
/** Authenticates the external Webhook as a scoped machine Principal before MVC, without trusting caller Tenant headers. */
public class ProviderWebhookAuthenticationFilter extends OncePerRequestFilter {
 public static final String MACHINE_PRINCIPAL_ATTRIBUTE=ProviderWebhookAuthenticationFilter.class.getName()+".principal";
 private static final String PREFIX="/api/external/provider-webhooks/";
 private final IntegrationWebhookEndpointRepository endpoints; private final IntegrationIdentityRepository identities; private final ProviderWebhookSignatureVerifier signatures; private final ProviderWebhookRateLimiter limiter; private final ProviderWebhookSecurityProperties properties; private final ObjectMapper json;
 public ProviderWebhookAuthenticationFilter(IntegrationWebhookEndpointRepository endpoints,IntegrationIdentityRepository identities,ProviderWebhookSignatureVerifier signatures,ProviderWebhookRateLimiter limiter,ProviderWebhookSecurityProperties properties,ObjectMapper json){this.endpoints=endpoints;this.identities=identities;this.signatures=signatures;this.limiter=limiter;this.properties=properties;this.json=json;}
 @Override protected boolean shouldNotFilter(HttpServletRequest request){return !path(request).startsWith(PREFIX);}
 @Override protected void doFilterInternal(HttpServletRequest request,HttpServletResponse response,FilterChain chain)throws ServletException,IOException{
  if(!properties.isEnabled()){reject(response,503,"WEBHOOK_SECURITY_DISABLED","External Webhook security is disabled.",correlation(request));return;}
  if(!"POST".equalsIgnoreCase(request.getMethod())){reject(response,405,"WEBHOOK_METHOD_NOT_ALLOWED","Only POST is allowed.",correlation(request));return;}
  String correlation=correlation(request),token=path(request).substring(PREFIX.length());if(token.isBlank()||token.contains("/")){reject(response,401,"WEBHOOK_ENDPOINT_INVALID","Webhook authentication failed.",correlation);return;}
  var endpoint=endpoints.findByTokenHash(hash(token)).orElse(null);if(endpoint==null||endpoint.status()!=IntegrationWebhookEndpointStatus.ACTIVE){reject(response,401,"WEBHOOK_ENDPOINT_INVALID","Webhook authentication failed.",correlation);return;}
  String contentType=request.getContentType();if(contentType==null||!contentType.toLowerCase(Locale.ROOT).startsWith(MediaType.APPLICATION_JSON_VALUE)){reject(response,415,"WEBHOOK_CONTENT_TYPE_INVALID","Content-Type must be application/json.",correlation);return;}
  int max=positive(endpoint.maxBodyBytes(),properties.getDefaultMaxBodyBytes());long declared=request.getContentLengthLong();if(declared>max){reject(response,413,"WEBHOOK_BODY_TOO_LARGE","Webhook body exceeds the configured limit.",correlation);return;}
  byte[] body=request.getInputStream().readNBytes(max+1);if(body.length>max){reject(response,413,"WEBHOOK_BODY_TOO_LARGE","Webhook body exceeds the configured limit.",correlation);return;}
  String eventId=header(request,"X-Provider-Event-Id"),timestamp=header(request,"X-Webhook-Timestamp"),nonce=header(request,"X-Webhook-Nonce"),signature=header(request,"X-Webhook-Signature");
  if(blank(eventId)||blank(timestamp)||blank(nonce)||blank(signature)){reject(response,401,"WEBHOOK_SECURITY_HEADER_REQUIRED","Webhook security headers are required.",correlation);return;}
  OffsetDateTime observed=parseTimestamp(timestamp);OffsetDateTime now=OffsetDateTime.now(ZoneOffset.UTC);long window=Math.max(30,endpoint.replayWindowSeconds()),skew=Math.max(0,properties.getClockSkewSeconds());
  if(observed==null||observed.isBefore(now.minusSeconds(window))||observed.isAfter(now.plusSeconds(skew))){reject(response,401,"WEBHOOK_TIMESTAMP_INVALID","Webhook timestamp is outside the accepted replay window.",correlation);return;}
  var connection=identities.findConnection(endpoint.tenantId(),endpoint.connectionId()).orElse(null);var principal=identities.findPrincipal(endpoint.tenantId(),endpoint.principalId()).orElse(null);var scope=identities.findPrincipalScope(endpoint.tenantId(),endpoint.principalId()).orElse(null);
  if(connection==null||!connection.enabled()||connection.status()!=IntegrationConnectionStatus.ACTIVE||connection.providerType()!=endpoint.providerType()){reject(response,403,"WEBHOOK_CONNECTION_BINDING_INVALID","Webhook Connection binding is not active.",correlation);return;}
  if(principal==null||principal.status()!=IntegrationPrincipalStatus.ACTIVE||!principal.connectionId().equals(connection.connectionId())){reject(response,403,"WEBHOOK_PRINCIPAL_BINDING_INVALID","Webhook Principal binding is not active.",correlation);return;}
  if(scope==null||!scope.productionAllowed()||!scope.allowsOperation(IntegrationOperation.WEBHOOK)){reject(response,403,"WEBHOOK_PRINCIPAL_SCOPE_INVALID","Webhook Principal scope does not allow ingress.",correlation);return;}
  String bodyDigest=hash(body);var signing=new ProviderWebhookSigningRequest(request.getMethod(),path(request),connection.connectionId(),connection.providerType().name(),eventId,timestamp,nonce,bodyDigest);
  var result=signatures.verify(signing,signature,identities.listCredentials(endpoint.tenantId(),principal.principalId(),100));if(!result.verified()){reject(response,401,result.reasonCode(),"Webhook signature verification failed.",correlation);return;}
  String project=externalProject(body);if(blank(project)||!scope.allowsProject(project,principal.trustZoneId())){reject(response,403,"WEBHOOK_PROJECT_SCOPE_INVALID","Webhook Project is outside the Principal scope.",correlation);return;}
  if(!limiter.tryAcquire(endpoint.tenantId()+":"+endpoint.endpointId(),positive(endpoint.rateLimitPerMinute(),properties.getDefaultRateLimitPerMinute()),Instant.now())){reject(response,429,"WEBHOOK_RATE_LIMITED","Webhook rate limit exceeded.",correlation);return;}
  if(!endpoints.reserveNonce(endpoint.tenantId(),connection.connectionId(),endpoint.endpointId(),hash(nonce),observed.plusSeconds(window),correlation)){reject(response,409,"WEBHOOK_NONCE_REPLAYED","Webhook nonce was already used.",correlation);return;}
  var machine=new ProviderWebhookMachinePrincipal(endpoint.tenantId(),endpoint.endpointId(),connection.connectionId(),principal.principalId(),connection.providerType().name(),result.credentialId(),result.secretVersion(),bodyDigest,correlation);
  var context=SecurityContextHolder.createEmptyContext();context.setAuthentication(new ProviderWebhookAuthenticationToken(machine));SecurityContextHolder.setContext(context);request.setAttribute(MACHINE_PRINCIPAL_ATTRIBUTE,machine);response.setHeader("X-Correlation-Id",correlation);
  try{chain.doFilter(new CachedBodyHttpServletRequest(request,body),response);}finally{SecurityContextHolder.clearContext();}
 }
 @SuppressWarnings("unchecked") private String externalProject(byte[] body){try{Object v=json.readValue(body,Map.class).get("externalProjectId");return v==null?null:String.valueOf(v);}catch(Exception e){return null;}}
 private String path(HttpServletRequest r){String uri=r.getRequestURI()==null?"":r.getRequestURI(),ctx=r.getContextPath()==null?"":r.getContextPath();return !ctx.isBlank()&&uri.startsWith(ctx)?uri.substring(ctx.length()):uri;}
 private String correlation(HttpServletRequest r){String v=header(r,"X-Correlation-Id");return blank(v)?"webhook-"+UUID.randomUUID():v.trim();} private String header(HttpServletRequest r,String n){return r.getHeader(n);} private boolean blank(String v){return v==null||v.isBlank();} private int positive(int v,int d){return v>0?v:d;}
 private OffsetDateTime parseTimestamp(String v){try{return OffsetDateTime.parse(v);}catch(Exception ignored){try{return OffsetDateTime.ofInstant(Instant.ofEpochSecond(Long.parseLong(v)),ZoneOffset.UTC);}catch(Exception x){return null;}}}
 private String hash(String v){return hash(v.getBytes(StandardCharsets.UTF_8));} private String hash(byte[] b){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}catch(Exception e){throw new IllegalStateException("SHA-256 unavailable",e);}}
 private void reject(HttpServletResponse response,int status,String code,String message,String correlation)throws IOException{response.setStatus(status);response.setContentType(MediaType.APPLICATION_JSON_VALUE);response.setCharacterEncoding(StandardCharsets.UTF_8.name());response.setHeader("X-Correlation-Id",correlation);String safe=message.replace("\\","\\\\").replace("\"","\\\"");response.getWriter().write("{\"success\":false,\"code\":\""+code+"\",\"message\":\""+safe+"\",\"correlationId\":\""+correlation+"\"}");}
}
