package com.opensocket.aievent.core.resourceaccess.core;
import com.opensocket.aievent.core.resourceaccess.contract.*;
import java.time.*;import java.util.*;
/** Application service for release assessment. It never changes runtime mode by configuration side effect. */
public final class ResourceAccessReleaseGateService {
 private final ResourceAccessReleaseGateRepository repository;private final ResourceAccessReleaseGatePolicy policy;
 public ResourceAccessReleaseGateService(ResourceAccessReleaseGateRepository repository,ResourceAccessReleaseGatePolicy policy){this.repository=Objects.requireNonNull(repository);this.policy=Objects.requireNonNull(policy);}
 public ResourceAccessReleaseAssessment assess(String tenantId,ResourceAccessEnforcementMode from,ResourceAccessEnforcementMode target,ShadowAcceptanceThreshold threshold,Instant windowStart,Instant windowEnd,String actor,String correlation){
  required(tenantId,"tenantId");Objects.requireNonNull(from);Objects.requireNonNull(target);Objects.requireNonNull(threshold);if(!policy.validForwardTransition(from,target))throw new IllegalStateException("INVALID_RESOURCE_ACCESS_FORWARD_TRANSITION");
  var aggregate=repository.aggregateShadowEvidence(tenantId,windowStart,windowEnd);var evidence=repository.latestCertificationEvidence(tenantId);var bypasses=repository.activeLegacyBypasses(tenantId,windowEnd);var blockers=policy.blockers(aggregate,threshold,target,evidence,bypasses);
  var assessment=new ResourceAccessReleaseAssessment(UUID.randomUUID().toString(),tenantId,from,target,blockers.isEmpty()?ResourceAccessReleaseGateStatus.PASSED:ResourceAccessReleaseGateStatus.BLOCKED,aggregate.sampleCount(),aggregate.mismatchCount(),aggregate.criticalMismatchCount(),aggregate.legacyUnavailableCount(),aggregate.mismatchRateBps(),aggregate.legacyUnavailableRateBps(),blockers,aggregate.windowStartedAt(),aggregate.windowEndedAt(),Instant.now(),required(actor,"actor"),required(correlation,"correlation"));repository.appendAssessment(assessment);return assessment;
 }
 public void recordTransition(ResourceAccessReleaseAssessment assessment,String transitionId,String actor,String reason,String correlation,Instant at){if(assessment==null||!assessment.executableTransitionEvidence())throw new IllegalStateException("PASSED_RELEASE_ASSESSMENT_REQUIRED");if(!policy.validForwardTransition(assessment.fromMode(),assessment.targetMode()))throw new IllegalStateException("INVALID_RESOURCE_ACCESS_FORWARD_TRANSITION");repository.appendRolloutTransition(assessment.tenantId(),required(transitionId,"transitionId"),assessment.fromMode(),assessment.targetMode(),assessment.assessmentId(),required(actor,"actor"),required(reason,"reason"),required(correlation,"correlation"),Objects.requireNonNull(at));}
 public void recordRollback(String tenantId,String rehearsalId,ResourceAccessEnforcementMode from,ResourceAccessEnforcementMode to,boolean passed,String incidentId,String artifactRef,String actor,String correlation,Instant at){if(!policy.validRollbackTransition(from,to))throw new IllegalStateException("INVALID_RESOURCE_ACCESS_ROLLBACK_TRANSITION");repository.appendRollbackRehearsal(required(tenantId,"tenantId"),required(rehearsalId,"rehearsalId"),from,to,passed,required(incidentId,"incidentId"),required(artifactRef,"artifactRef"),required(actor,"actor"),required(correlation,"correlation"),Objects.requireNonNull(at));}
 private static String required(String v,String f){if(v==null||v.isBlank())throw new IllegalArgumentException(f+" is required");return v.trim();}
}
