package com.opensocket.aievent.core.capability;

import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantContextHolder;
import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantExecutionContext;
import java.sql.ResultSet;import java.sql.SQLException;import java.time.OffsetDateTime;import java.util.ArrayList;import java.util.LinkedHashSet;import java.util.List;import java.util.Locale;import java.util.Map;import java.util.Optional;import java.util.Set;import java.util.UUID;
import org.springframework.dao.EmptyResultDataAccessException;import org.springframework.jdbc.core.RowMapper;import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import tools.jackson.core.type.TypeReference;import tools.jackson.databind.ObjectMapper;

/**
 * Phase 9 aggregation + Case authority.
 * Aggregation consumes normalized Phase 8 Artifacts and produces a CapabilityRequirement only.
 * Case creation consumes an authoritative aggregation Artifact. External issues remain 0..N projections.
 */
@Service
public class CaseConvergenceService {
    private static final Set<String> DEFINITION_STATUSES=Set.of("DRAFT","ACTIVE","DISABLED","RETIRED");
    private static final Set<String> CASE_STATUSES=Set.of("OPEN","UNDER_REVIEW","RESOLVED","CLOSED");
    private static final TypeReference<List<String>> STRINGS=new TypeReference<>(){};
    private static final TypeReference<Map<String,Object>> MAP=new TypeReference<>(){};
    private final NamedParameterJdbcTemplate jdbc;private final ObjectMapper json;
    public CaseConvergenceService(NamedParameterJdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}

    @Transactional(readOnly=true)
    public List<AggregationDefinition> definitions(String tenantId,String status,int limit){String tenant=tenant(tenantId);bind(tenant);MapSqlParameterSource p=new MapSqlParameterSource("tenant",tenant).addValue("limit",limit(limit));String w=" where tenant_id=:tenant";if(!blank(status)){w+=" and status=:status";p.addValue("status",definitionStatus(status));}return jdbc.query("select * from aggregation_definitions"+w+" order by aggregation_id limit :limit",p,new AggregationDefinitionMapper());}

    @Transactional
    public AggregationDefinition upsertDefinition(String tenantId,String pathId,AggregationDefinition req,String changeReason){String tenant=tenant(tenantId);bind(tenant);if(req==null)throw new IllegalArgumentException("Aggregation Definition body is required");String id=required(first(pathId,req.aggregationId()),"aggregationId"),cap=required(req.aggregationCapabilityCode(),"aggregationCapabilityCode"),op=required(req.operation(),"operation").toUpperCase(Locale.ROOT),status=definitionStatus(req.status());validateCanonicalCapability(tenant,cap,op);AggregationDefinition existing=findDefinition(tenant,id).orElse(null);if(existing!=null&&blank(changeReason))throw new IllegalArgumentException("X-Change-Reason is required when changing an existing Aggregation Definition");double min=req.minInputConfidence()==null?0d:req.minInputConfidence();if(min<0||min>1)throw new IllegalArgumentException("minInputConfidence must be between 0 and 1");int version=existing==null?1:existing.version()+1;OffsetDateTime now=OffsetDateTime.now(),created=existing==null?now:existing.createdAt();List<String> requiredCaps=clean(req.requiredInputCapabilities());jdbc.update("""
      insert into aggregation_definitions(tenant_id,aggregation_id,display_name,aggregation_capability_code,operation,required_input_capabilities_json,min_input_confidence,allow_partial_evidence,require_human_review_on_partial,status,version,created_at,updated_at)
      values(:tenant,:id,:name,:cap,:op,cast(:inputs as jsonb),:min,:partial,:review,:status,:version,:created,:updated)
      on conflict(tenant_id,aggregation_id) do update set display_name=excluded.display_name,aggregation_capability_code=excluded.aggregation_capability_code,operation=excluded.operation,required_input_capabilities_json=excluded.required_input_capabilities_json,min_input_confidence=excluded.min_input_confidence,allow_partial_evidence=excluded.allow_partial_evidence,require_human_review_on_partial=excluded.require_human_review_on_partial,status=excluded.status,version=excluded.version,updated_at=excluded.updated_at
      """,new MapSqlParameterSource("tenant",tenant).addValue("id",id).addValue("name",required(req.displayName(),"displayName")).addValue("cap",cap).addValue("op",op).addValue("inputs",write(requiredCaps)).addValue("min",req.minInputConfidence()).addValue("partial",req.allowPartialEvidence()).addValue("review",req.requireHumanReviewOnPartial()).addValue("status",status).addValue("version",version).addValue("created",created).addValue("updated",now));AggregationDefinition saved=findDefinition(tenant,id).orElseThrow();appendDefinitionVersion(saved,existing==null?"INITIAL_CREATE":changeReason);return saved;}

    @Transactional(readOnly=true)
    public List<AggregationDefinitionVersion> definitionVersions(String tenantId,String id){String tenant=tenant(tenantId);bind(tenant);return jdbc.query("select * from aggregation_definition_versions where tenant_id=:tenant and aggregation_id=:id order by version desc",new MapSqlParameterSource("tenant",tenant).addValue("id",required(id,"aggregationId")),(rs,n)->new AggregationDefinitionVersion(tenant,rs.getString("aggregation_id"),rs.getInt("version"),readMap(rs.getString("snapshot_json")),rs.getString("change_reason"),rs.getString("actor_ref"),rs.getObject("created_at",OffsetDateTime.class)));}

    @Transactional
    public AggregationPreparationDecision prepare(String tenantId,AggregationPreparationRequest req){String tenant=tenant(tenantId);bind(tenant);if(req==null)throw new IllegalArgumentException("Aggregation preparation request is required");AggregationDefinition def=requireActiveDefinition(tenant,required(req.aggregationId(),"aggregationId"));String run=required(req.runId(),"runId");Map<String,Object> runRow=one("select status,plan_id from plan_execution_runs where tenant_id=:tenant and run_id=:id",tenant,run);String runStatus=str(runRow,"status");List<ArtifactRow> artifacts=loadArtifacts(tenant,run,req.artifactIds());List<String> reasons=new ArrayList<>();boolean review=false;String result="READY_FOR_CAPABILITY_EXECUTION";if(!Set.of("SUCCEEDED","PARTIAL_SUCCEEDED").contains(runStatus)){result="RUN_NOT_TERMINAL";reasons.add("PLAN_RUN_NOT_TERMINAL");}
        Set<String> present=new LinkedHashSet<>();for(ArtifactRow a:artifacts){present.add(a.capabilityCode());if(a.confidence()!=null&&def.minInputConfidence()!=null&&a.confidence()<def.minInputConfidence())reasons.add("ARTIFACT_CONFIDENCE_BELOW_DEFINITION:"+a.artifactId());}
        for(String requiredCap:def.requiredInputCapabilities())if(!present.contains(requiredCap))reasons.add("MISSING_REQUIRED_INPUT_CAPABILITY:"+requiredCap);
        if("PARTIAL_SUCCEEDED".equals(runStatus)&&!def.allowPartialEvidence())reasons.add("PARTIAL_RUN_NOT_ALLOWED");
        if(!reasons.isEmpty()&&"READY_FOR_CAPABILITY_EXECUTION".equals(result)){result="INCOMPLETE_EVIDENCE";review=def.requireHumanReviewOnPartial();}
        CapabilityRequirement requirement=null;if("READY_FOR_CAPABILITY_EXECUTION".equals(result)){try{validateCanonicalCapability(tenant,def.aggregationCapabilityCode(),def.operation());}catch(IllegalArgumentException ex){result="CAPABILITY_GAP";reasons.add("AGGREGATION_CAPABILITY_NOT_ACTIVE_OR_OPERATION_UNSUPPORTED");}if("READY_FOR_CAPABILITY_EXECUTION".equals(result)){List<String> ids=artifacts.stream().map(ArtifactRow::artifactId).toList();requirement=new CapabilityRequirement(def.aggregationCapabilityCode(),def.operation(),Map.of("artifactRefs",ids,"planRunRef",run),Map.of(),highestClassification(artifacts),null,null,"HIGH_ACCURACY");reasons.add("WHAT_PREPARED_ONLY_WHO_CAN_MAY_SHOULD_HOW_STILL_REQUIRED");}}
        String decision="aggregation-decision-"+UUID.randomUUID();List<String> ids=artifacts.stream().map(ArtifactRow::artifactId).toList();jdbc.update("insert into aggregation_preparation_decisions(tenant_id,decision_id,aggregation_id,aggregation_version,run_id,result,aggregation_requirement_json,input_artifact_ids_json,reason_codes_json,requires_human_review,created_at) values(:tenant,:decision,:aggregation,:version,:run,:result,cast(:req as jsonb),cast(:artifacts as jsonb),cast(:reasons as jsonb),:review,:at)",new MapSqlParameterSource("tenant",tenant).addValue("decision",decision).addValue("aggregation",def.aggregationId()).addValue("version",def.version()).addValue("run",run).addValue("result",result).addValue("req",requirement==null?null:write(requirement)).addValue("artifacts",write(ids)).addValue("reasons",write(reasons)).addValue("review",review).addValue("at",OffsetDateTime.now()));return new AggregationPreparationDecision(decision,tenant,def.aggregationId(),def.version(),run,result,requirement,ids,reasons,review,OffsetDateTime.now());}

    @Transactional(readOnly=true)
    public List<AggregationPreparationDecision> preparationDecisions(String tenantId,String runId,int limit){String tenant=tenant(tenantId);bind(tenant);MapSqlParameterSource p=new MapSqlParameterSource("tenant",tenant).addValue("limit",limit(limit));String w=" where tenant_id=:tenant";if(!blank(runId)){w+=" and run_id=:run";p.addValue("run",runId.trim());}return jdbc.query("select * from aggregation_preparation_decisions"+w+" order by created_at desc,decision_id desc limit :limit",p,new AggregationDecisionMapper());}

    @Transactional
    public EnterpriseCaseRecord convergeCase(String tenantId,CaseConvergenceRequest req){String tenant=tenant(tenantId);bind(tenant);if(req==null)throw new IllegalArgumentException("Case convergence request is required");String run=required(req.runId(),"runId"),key=required(req.idempotencyKey(),"idempotencyKey");Optional<EnterpriseCaseRecord> prior=findCaseByIdempotency(tenant,run,key);if(prior.isPresent())return prior.get();Map<String,Object> rr=one("select status,plan_id from plan_execution_runs where tenant_id=:tenant and run_id=:id",tenant,run);String status=str(rr,"status");if(!Set.of("SUCCEEDED","PARTIAL_SUCCEEDED").contains(status))throw new IllegalArgumentException("CASE_REQUIRES_TERMINAL_PLAN_RUN");String plan=str(rr,"plan_id");AggregationDefinition def=requireActiveDefinition(tenant,required(req.aggregationId(),"aggregationId"));validateCaseEvidence(tenant,run,status,def);ArtifactRow aggregation=requireArtifact(tenant,required(req.aggregationArtifactId(),"aggregationArtifactId"));if(!run.equals(aggregation.runId()))throw new IllegalArgumentException("AGGREGATION_ARTIFACT_RUN_MISMATCH");if(!def.aggregationCapabilityCode().equals(aggregation.capabilityCode()))throw new IllegalArgumentException("AGGREGATION_ARTIFACT_CAPABILITY_MISMATCH");String caseId=blank(req.caseId())?"case-"+UUID.randomUUID():req.caseId().trim();String taskRef=planTaskRef(tenant,plan);Map<String,Object> output=aggregation.output();String rootCause=first(str(output,"rootCause"),aggregation.finding());List<String> actions=objectStrings(output.get("recommendedActions"));String correlation="case-corr-"+UUID.randomUUID(),trace="case-trace-"+UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();jdbc.update("""
      insert into enterprise_cases(tenant_id,case_id,source_task_ref,plan_id,run_id,aggregation_id,aggregation_version,aggregation_artifact_id,classification,affected_resources_json,root_cause,confidence,recommended_actions_json,status,version,correlation_id,trace_id,idempotency_key,created_at,updated_at)
      values(:tenant,:caseId,:task,:plan,:run,:aggregation,:version,:artifact,:classification,cast(:resources as jsonb),:root,:confidence,cast(:actions as jsonb),'OPEN',1,:correlation,:trace,:key,:at,:at)
      """,new MapSqlParameterSource("tenant",tenant).addValue("caseId",caseId).addValue("task",taskRef).addValue("plan",plan).addValue("run",run).addValue("aggregation",def.aggregationId()).addValue("version",def.version()).addValue("artifact",aggregation.artifactId()).addValue("classification",trim(req.classification())).addValue("resources",write(clean(req.affectedResources()))).addValue("root",rootCause).addValue("confidence",aggregation.confidence()).addValue("actions",write(actions)).addValue("correlation",correlation).addValue("trace",trace).addValue("key",key).addValue("at",now));if("PARTIAL_SUCCEEDED".equals(status)&&def.requireHumanReviewOnPartial())jdbc.update("update enterprise_cases set status='UNDER_REVIEW',updated_at=:at where tenant_id=:tenant and case_id=:caseId",new MapSqlParameterSource("tenant",tenant).addValue("caseId",caseId).addValue("at",now));linkRunArtifacts(tenant,caseId,run,aggregation.artifactId());EnterpriseCaseRecord created=requireCase(tenant,caseId);appendCaseVersion(created,"INITIAL_CONVERGENCE");appendCaseEvent(tenant,caseId,"CASE_CREATED","INITIAL_CONVERGENCE",Map.of("runId",run,"aggregationArtifactId",aggregation.artifactId(),"childIssuesCreated",false));return created;}

    @Transactional(readOnly=true)
    public List<EnterpriseCaseRecord> cases(String tenantId,String status,String afterCaseId,int limit){String tenant=tenant(tenantId);bind(tenant);MapSqlParameterSource p=new MapSqlParameterSource("tenant",tenant).addValue("limit",limit(limit));String w=" where tenant_id=:tenant";if(!blank(status)){w+=" and status=:status";p.addValue("status",caseStatus(status));}if(!blank(afterCaseId)){w+=" and case_id>:after";p.addValue("after",afterCaseId.trim());}return jdbc.query("select * from enterprise_cases"+w+" order by case_id limit :limit",p,new CaseMapper());}
    @Transactional(readOnly=true) public EnterpriseCaseRecord caseById(String tenantId,String caseId){String tenant=tenant(tenantId);bind(tenant);return requireCase(tenant,required(caseId,"caseId"));}

    @Transactional
    public EnterpriseCaseRecord reviewCase(String tenantId,String caseId,CaseReviewRequest req){String tenant=tenant(tenantId);bind(tenant);if(req==null)throw new IllegalArgumentException("Case review request is required");EnterpriseCaseRecord current=requireCase(tenant,required(caseId,"caseId"));String status=caseStatus(req.status()),reason=required(req.reason(),"reason");if("CLOSED".equals(current.status()))throw new IllegalArgumentException("CLOSED_CASE_IS_IMMUTABLE");validateCaseTransition(current.status(),status);if(Set.of("RESOLVED","CLOSED").contains(status)){required(req.humanDecision(),"humanDecision");required(req.accountableRef(),"accountableRef");}int version=current.version()+1;OffsetDateTime now=OffsetDateTime.now();jdbc.update("update enterprise_cases set status=:status,human_decision=:decision,accountable_ref=:accountable,version=:version,updated_at=:at where tenant_id=:tenant and case_id=:caseId",new MapSqlParameterSource("tenant",tenant).addValue("caseId",caseId).addValue("status",status).addValue("decision",trim(req.humanDecision())).addValue("accountable",trim(req.accountableRef())).addValue("version",version).addValue("at",now));EnterpriseCaseRecord updated=requireCase(tenant,caseId);appendCaseVersion(updated,reason);appendCaseEvent(tenant,caseId,"CASE_REVIEWED",reason,Map.of("fromStatus",current.status(),"toStatus",status));return updated;}

    @Transactional(readOnly=true)
    public List<CaseArtifactLink> caseArtifacts(String tenantId,String caseId){String tenant=tenant(tenantId);bind(tenant);return jdbc.query("select * from enterprise_case_artifacts where tenant_id=:tenant and case_id=:caseId order by linked_at,artifact_id",new MapSqlParameterSource("tenant",tenant).addValue("caseId",required(caseId,"caseId")),(rs,n)->new CaseArtifactLink(tenant,rs.getString("case_id"),rs.getString("artifact_id"),rs.getString("role"),rs.getString("step_id"),rs.getString("capability_code"),rs.getObject("linked_at",OffsetDateTime.class)));}

    @Transactional
    public CaseIssueProjection recordProjectionIntent(String tenantId,String caseId,CaseIssueProjectionRequest req){String tenant=tenant(tenantId);bind(tenant);requireCase(tenant,required(caseId,"caseId"));if(req==null)throw new IllegalArgumentException("Projection intent is required");String key=required(req.idempotencyKey(),"idempotencyKey");Optional<CaseIssueProjection> prior=findProjectionByIdempotency(tenant,caseId,key);if(prior.isPresent())return prior.get();String projectionId=blank(req.projectionId())?"case-projection-"+UUID.randomUUID():req.projectionId().trim();if(req.primaryProjection()){Integer count=jdbc.queryForObject("select count(*) from enterprise_case_issue_projections where tenant_id=:tenant and case_id=:caseId and primary_projection=true and status<>'SUPERSEDED'",new MapSqlParameterSource("tenant",tenant).addValue("caseId",caseId),Integer.class);if(count!=null&&count>0)throw new IllegalArgumentException("CASE_ALREADY_HAS_ACTIVE_PRIMARY_PROJECTION");}String state=blank(req.existingProjectionRef())?"INTENT_RECORDED":"LINKED";OffsetDateTime now=OffsetDateTime.now();jdbc.update("insert into enterprise_case_issue_projections(tenant_id,projection_id,case_id,connector_type,target_ref,primary_projection,status,existing_projection_ref,idempotency_key,created_at,updated_at) values(:tenant,:projection,:caseId,:connector,:target,:primary,:status,:existing,:key,:at,:at)",new MapSqlParameterSource("tenant",tenant).addValue("projection",projectionId).addValue("caseId",caseId).addValue("connector",required(req.connectorType(),"connectorType").toUpperCase(Locale.ROOT)).addValue("target",required(req.targetRef(),"targetRef")).addValue("primary",req.primaryProjection()).addValue("status",state).addValue("existing",trim(req.existingProjectionRef())).addValue("key",key).addValue("at",now));appendCaseEvent(tenant,caseId,"ISSUE_PROJECTION_INTENT_RECORDED","NO_EXTERNAL_IO",Map.of("projectionId",projectionId,"connectorType",req.connectorType(),"childTaskProjection",false));return requireProjection(tenant,projectionId);}

    @Transactional(readOnly=true)
    public List<CaseIssueProjection> projections(String tenantId,String caseId){String tenant=tenant(tenantId);bind(tenant);return jdbc.query("select * from enterprise_case_issue_projections where tenant_id=:tenant and case_id=:caseId order by created_at,projection_id",new MapSqlParameterSource("tenant",tenant).addValue("caseId",required(caseId,"caseId")),new ProjectionMapper());}
    @Transactional(readOnly=true)
    public List<CaseEvent> events(String tenantId,String caseId,int limit){String tenant=tenant(tenantId);bind(tenant);return jdbc.query("select * from enterprise_case_events where tenant_id=:tenant and case_id=:caseId order by occurred_at desc,event_id desc limit :limit",new MapSqlParameterSource("tenant",tenant).addValue("caseId",required(caseId,"caseId")).addValue("limit",limit(limit)),(rs,n)->new CaseEvent(tenant,rs.getString("event_id"),rs.getString("case_id"),rs.getString("event_type"),rs.getString("actor_ref"),rs.getString("reason"),readMap(rs.getString("evidence_json")),rs.getObject("occurred_at",OffsetDateTime.class)));}

    private void validateCaseEvidence(String tenant,String run,String runStatus,AggregationDefinition def){List<ArtifactRow> artifacts=loadArtifacts(tenant,run,List.of());if("PARTIAL_SUCCEEDED".equals(runStatus)&&!def.allowPartialEvidence())throw new IllegalArgumentException("CASE_PARTIAL_EVIDENCE_NOT_ALLOWED");Set<String> present=new LinkedHashSet<>();for(ArtifactRow a:artifacts){present.add(a.capabilityCode());if(a.confidence()!=null&&def.minInputConfidence()!=null&&a.confidence()<def.minInputConfidence())throw new IllegalArgumentException("CASE_ARTIFACT_CONFIDENCE_BELOW_DEFINITION:"+a.artifactId());}for(String cap:def.requiredInputCapabilities())if(!present.contains(cap))throw new IllegalArgumentException("CASE_MISSING_REQUIRED_INPUT_CAPABILITY:"+cap);}
    private void validateCaseTransition(String from,String to){if(from.equals(to))return;boolean ok=switch(from){case "OPEN"->Set.of("UNDER_REVIEW","RESOLVED").contains(to);case "UNDER_REVIEW"->Set.of("RESOLVED").contains(to);case "RESOLVED"->Set.of("UNDER_REVIEW","CLOSED").contains(to);default->false;};if(!ok)throw new IllegalArgumentException("INVALID_CASE_STATUS_TRANSITION:"+from+"->"+to);}
    private void validateCanonicalCapability(String tenant,String cap,String op){Map<String,Object> c=one("select status,operations_json from capability_definitions where tenant_id=:tenant and capability_code=:id",tenant,cap);if(!"ACTIVE".equals(str(c,"status")))throw new IllegalArgumentException("AGGREGATION_CAPABILITY_NOT_ACTIVE");List<String> ops=readStrings(String.valueOf(c.get("operations_json")));if(!ops.isEmpty()&&ops.stream().noneMatch(x->x.equalsIgnoreCase(op)))throw new IllegalArgumentException("AGGREGATION_OPERATION_NOT_SUPPORTED");}
    private AggregationDefinition requireActiveDefinition(String tenant,String id){AggregationDefinition d=findDefinition(tenant,id).orElseThrow(()->new IllegalArgumentException("Aggregation Definition not found: "+id));if(!"ACTIVE".equals(d.status()))throw new IllegalArgumentException("AGGREGATION_DEFINITION_NOT_ACTIVE");return d;}
    private Optional<AggregationDefinition> findDefinition(String tenant,String id){try{return Optional.ofNullable(jdbc.queryForObject("select * from aggregation_definitions where tenant_id=:tenant and aggregation_id=:id",new MapSqlParameterSource("tenant",tenant).addValue("id",id),new AggregationDefinitionMapper()));}catch(EmptyResultDataAccessException ex){return Optional.empty();}}
    private void appendDefinitionVersion(AggregationDefinition d,String reason){jdbc.update("insert into aggregation_definition_versions(tenant_id,aggregation_id,version,snapshot_json,change_reason,actor_ref,created_at) values(:tenant,:id,:version,cast(:snapshot as jsonb),:reason,:actor,:at)",new MapSqlParameterSource("tenant",d.tenantId()).addValue("id",d.aggregationId()).addValue("version",d.version()).addValue("snapshot",write(d)).addValue("reason",required(reason,"changeReason")).addValue("actor",actor()).addValue("at",OffsetDateTime.now()));}
    private List<ArtifactRow> loadArtifacts(String tenant,String run,List<String> ids){MapSqlParameterSource p=new MapSqlParameterSource("tenant",tenant).addValue("run",run);String sql="select * from plan_execution_artifacts where tenant_id=:tenant and run_id=:run";if(ids!=null&&!ids.isEmpty()){List<String> cleaned=clean(ids);p.addValue("ids",cleaned);sql+=" and artifact_id in (:ids)";}List<ArtifactRow> rows=jdbc.query(sql+" order by created_at,artifact_id",p,new ArtifactRowMapper());if(ids!=null&&!ids.isEmpty()&&rows.size()!=new LinkedHashSet<>(clean(ids)).size())throw new IllegalArgumentException("AGGREGATION_ARTIFACT_NOT_FOUND_OR_WRONG_RUN");return rows;}
    private ArtifactRow requireArtifact(String tenant,String id){try{return jdbc.queryForObject("select * from plan_execution_artifacts where tenant_id=:tenant and artifact_id=:id",new MapSqlParameterSource("tenant",tenant).addValue("id",id),new ArtifactRowMapper());}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("Plan execution Artifact not found: "+id);}}
    private void linkRunArtifacts(String tenant,String caseId,String run,String aggregationArtifact){List<ArtifactRow> rows=loadArtifacts(tenant,run,List.of());for(ArtifactRow a:rows)jdbc.update("insert into enterprise_case_artifacts(tenant_id,case_id,artifact_id,role,step_id,capability_code,linked_at) values(:tenant,:caseId,:artifact,:role,:step,:cap,:at) on conflict do nothing",new MapSqlParameterSource("tenant",tenant).addValue("caseId",caseId).addValue("artifact",a.artifactId()).addValue("role",a.artifactId().equals(aggregationArtifact)?"AGGREGATION":"EVIDENCE").addValue("step",a.stepId()).addValue("cap",a.capabilityCode()).addValue("at",OffsetDateTime.now()));}
    private String planTaskRef(String tenant,String plan){try{return jdbc.queryForObject("select task_ref from execution_plans where tenant_id=:tenant and plan_id=:id",new MapSqlParameterSource("tenant",tenant).addValue("id",plan),String.class);}catch(EmptyResultDataAccessException ex){return null;}}
    private EnterpriseCaseRecord requireCase(String tenant,String id){try{return jdbc.queryForObject("select * from enterprise_cases where tenant_id=:tenant and case_id=:id",new MapSqlParameterSource("tenant",tenant).addValue("id",id),new CaseMapper());}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("Enterprise Case not found: "+id);}}
    private Optional<EnterpriseCaseRecord> findCaseByIdempotency(String tenant,String run,String key){try{return Optional.ofNullable(jdbc.queryForObject("select * from enterprise_cases where tenant_id=:tenant and run_id=:run and idempotency_key=:key",new MapSqlParameterSource("tenant",tenant).addValue("run",run).addValue("key",key),new CaseMapper()));}catch(EmptyResultDataAccessException ex){return Optional.empty();}}
    private void appendCaseVersion(EnterpriseCaseRecord c,String reason){jdbc.update("insert into enterprise_case_versions(tenant_id,case_id,version,snapshot_json,change_reason,actor_ref,created_at) values(:tenant,:caseId,:version,cast(:snapshot as jsonb),:reason,:actor,:at)",new MapSqlParameterSource("tenant",c.tenantId()).addValue("caseId",c.caseId()).addValue("version",c.version()).addValue("snapshot",write(c)).addValue("reason",required(reason,"changeReason")).addValue("actor",actor()).addValue("at",OffsetDateTime.now()));}
    private void appendCaseEvent(String tenant,String caseId,String type,String reason,Map<String,Object> evidence){jdbc.update("insert into enterprise_case_events(tenant_id,event_id,case_id,event_type,actor_ref,reason,evidence_json,occurred_at) values(:tenant,:event,:caseId,:type,:actor,:reason,cast(:evidence as jsonb),:at)",new MapSqlParameterSource("tenant",tenant).addValue("event","case-event-"+UUID.randomUUID()).addValue("caseId",caseId).addValue("type",type).addValue("actor",actor()).addValue("reason",reason).addValue("evidence",write(evidence)).addValue("at",OffsetDateTime.now()));}
    private Optional<CaseIssueProjection> findProjectionByIdempotency(String tenant,String caseId,String key){try{return Optional.ofNullable(jdbc.queryForObject("select * from enterprise_case_issue_projections where tenant_id=:tenant and case_id=:caseId and idempotency_key=:key",new MapSqlParameterSource("tenant",tenant).addValue("caseId",caseId).addValue("key",key),new ProjectionMapper()));}catch(EmptyResultDataAccessException ex){return Optional.empty();}}
    private CaseIssueProjection requireProjection(String tenant,String id){try{return jdbc.queryForObject("select * from enterprise_case_issue_projections where tenant_id=:tenant and projection_id=:id",new MapSqlParameterSource("tenant",tenant).addValue("id",id),new ProjectionMapper());}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("Case projection not found: "+id);}}
    private String highestClassification(List<ArtifactRow> rows){for(ArtifactRow r:rows)if(!blank(r.dataClassification()))return r.dataClassification();return null;}
    private Map<String,Object> one(String sql,String tenant,String id){try{return jdbc.queryForMap(sql,new MapSqlParameterSource("tenant",tenant).addValue("id",id));}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("Required Phase 9 evidence not found: "+id);}}
    private void bind(String tenant){IamTenantExecutionContext c=IamTenantContextHolder.current().orElse(null);if(c!=null&&!"INSTANCE".equalsIgnoreCase(c.tenantId())&&!tenant.equals(c.tenantId()))throw new IllegalArgumentException("Tenant context mismatch for Case Convergence persistence");jdbc.getJdbcTemplate().queryForObject("select set_config('app.current_tenant_id', ?, true)",String.class,tenant);jdbc.getJdbcTemplate().queryForObject("select set_config('app.current_actor_id', ?, true)",String.class,actor());}
    private String actor(){IamTenantExecutionContext c=IamTenantContextHolder.current().orElse(null);return c==null||blank(c.actorId())?"case-convergence":c.actorId();}
    private String definitionStatus(String x){String v=blank(x)?"DRAFT":x.trim().toUpperCase(Locale.ROOT);if(!DEFINITION_STATUSES.contains(v))throw new IllegalArgumentException("Unsupported Aggregation Definition status: "+v);return v;}
    private String caseStatus(String x){String v=required(x,"status").toUpperCase(Locale.ROOT);if(!CASE_STATUSES.contains(v))throw new IllegalArgumentException("Unsupported Case status: "+v);return v;}
    private List<String> clean(List<String> values){if(values==null)return List.of();LinkedHashSet<String> out=new LinkedHashSet<>();for(String v:values)if(!blank(v))out.add(v.trim());return List.copyOf(out);}
    private List<String> objectStrings(Object v){if(!(v instanceof List<?> l))return List.of();List<String> out=new ArrayList<>();for(Object x:l)if(x!=null&&!String.valueOf(x).isBlank())out.add(String.valueOf(x));return List.copyOf(out);}
    private int limit(int n){return Math.max(1,Math.min(n<=0?100:n,500));}private String tenant(String x){return required(x,"tenantId");}private String required(String x,String f){if(blank(x))throw new IllegalArgumentException(f+" is required");return x.trim();}private String first(String a,String b){return !blank(a)?a:b;}private String trim(String x){return blank(x)?null:x.trim();}private boolean blank(String x){return x==null||x.isBlank();}private String str(Map<String,Object> m,String k){Object v=m.get(k);return v==null?null:String.valueOf(v);}private String write(Object x){try{return json.writeValueAsString(x);}catch(Exception ex){throw new IllegalArgumentException("Phase 9 JSON serialization failed",ex);}}private List<String> readStrings(String x){try{return blank(x)?List.of():json.readValue(x,STRINGS);}catch(Exception ex){throw new IllegalArgumentException("Phase 9 string-array JSON invalid",ex);}}private Map<String,Object> readMap(String x){try{return blank(x)?Map.of():json.readValue(x,MAP);}catch(Exception ex){throw new IllegalArgumentException("Phase 9 object JSON invalid",ex);}}

    private record ArtifactRow(String artifactId,String runId,String stepId,String capabilityCode,String finding,Double confidence,List<String> evidenceRefs,Map<String,Object> output,String dataClassification,OffsetDateTime createdAt){}
    private final class ArtifactRowMapper implements RowMapper<ArtifactRow>{public ArtifactRow mapRow(ResultSet rs,int n)throws SQLException{return new ArtifactRow(rs.getString("artifact_id"),rs.getString("run_id"),rs.getString("step_id"),rs.getString("capability_code"),rs.getString("finding"),rs.getObject("confidence",Double.class),readStrings(rs.getString("evidence_refs_json")),readMap(rs.getString("output_json")),rs.getString("data_classification"),rs.getObject("created_at",OffsetDateTime.class));}}
    private final class AggregationDefinitionMapper implements RowMapper<AggregationDefinition>{public AggregationDefinition mapRow(ResultSet rs,int n)throws SQLException{return new AggregationDefinition(rs.getString("tenant_id"),rs.getString("aggregation_id"),rs.getString("display_name"),rs.getString("aggregation_capability_code"),rs.getString("operation"),readStrings(rs.getString("required_input_capabilities_json")),rs.getObject("min_input_confidence",Double.class),rs.getBoolean("allow_partial_evidence"),rs.getBoolean("require_human_review_on_partial"),rs.getString("status"),rs.getInt("version"),rs.getObject("created_at",OffsetDateTime.class),rs.getObject("updated_at",OffsetDateTime.class));}}
    private final class AggregationDecisionMapper implements RowMapper<AggregationPreparationDecision>{public AggregationPreparationDecision mapRow(ResultSet rs,int n)throws SQLException{String raw=rs.getString("aggregation_requirement_json");CapabilityRequirement req=null;if(!blank(raw)){try{req=json.readValue(raw,CapabilityRequirement.class);}catch(Exception ex){throw new SQLException(ex);}}return new AggregationPreparationDecision(rs.getString("decision_id"),rs.getString("tenant_id"),rs.getString("aggregation_id"),rs.getInt("aggregation_version"),rs.getString("run_id"),rs.getString("result"),req,readStrings(rs.getString("input_artifact_ids_json")),readStrings(rs.getString("reason_codes_json")),rs.getBoolean("requires_human_review"),rs.getObject("created_at",OffsetDateTime.class));}}
    private final class CaseMapper implements RowMapper<EnterpriseCaseRecord>{public EnterpriseCaseRecord mapRow(ResultSet rs,int n)throws SQLException{return new EnterpriseCaseRecord(rs.getString("case_id"),rs.getString("tenant_id"),rs.getString("source_task_ref"),rs.getString("plan_id"),rs.getString("run_id"),rs.getString("aggregation_id"),rs.getInt("aggregation_version"),rs.getString("aggregation_artifact_id"),rs.getString("classification"),readStrings(rs.getString("affected_resources_json")),rs.getString("root_cause"),rs.getObject("confidence",Double.class),readStrings(rs.getString("recommended_actions_json")),rs.getString("human_decision"),rs.getString("accountable_ref"),rs.getString("status"),rs.getInt("version"),rs.getString("correlation_id"),rs.getString("trace_id"),rs.getObject("created_at",OffsetDateTime.class),rs.getObject("updated_at",OffsetDateTime.class));}}
    private static final class ProjectionMapper implements RowMapper<CaseIssueProjection>{public CaseIssueProjection mapRow(ResultSet rs,int n)throws SQLException{return new CaseIssueProjection(rs.getString("tenant_id"),rs.getString("projection_id"),rs.getString("case_id"),rs.getString("connector_type"),rs.getString("target_ref"),rs.getBoolean("primary_projection"),rs.getString("status"),rs.getString("existing_projection_ref"),rs.getString("external_issue_ref"),rs.getString("idempotency_key"),rs.getObject("created_at",OffsetDateTime.class),rs.getObject("updated_at",OffsetDateTime.class));}}
}
