package com.opensocket.aievent.core.capability;

import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantContextHolder;
import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantExecutionContext;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

/** Transactional outbox store for A0-R7 DispatchIntent. */
@Service
public class ExecutionDispatchIntentStore {
    private static final TypeReference<Map<String,Object>> OBJECT_MAP=new TypeReference<>(){};
    private final NamedParameterJdbcTemplate jdbc; private final ObjectMapper json;
    public ExecutionDispatchIntentStore(NamedParameterJdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}

    @Transactional
    public ExecutionDispatchIntentV206 claimNext(String tenantId,String workerId,int leaseSeconds){String t=req(tenantId,"tenantId"),w=req(workerId,"workerId");bind(t);OffsetDateTime now=OffsetDateTime.now(),until=now.plusSeconds(Math.max(10,Math.min(leaseSeconds,300)));try{
        String id=jdbc.queryForObject("with c as (select intent_id from execution_dispatch_intents_v206 where tenant_id=:tenant and status='PENDING' order by created_at for update skip locked limit 1),u as (update execution_dispatch_intents_v206 i set status='CLAIMED',claimed_by=:worker,claim_token=:token,claim_until=:until,attempt_count=attempt_count+1,updated_at=:now from c where i.tenant_id=:tenant and i.intent_id=c.intent_id returning i.intent_id) select intent_id from u",new MapSqlParameterSource("tenant",t).addValue("worker",w).addValue("token","intent-claim-"+UUID.randomUUID()).addValue("until",until).addValue("now",now),String.class);
        if(id==null)return null;ExecutionDispatchIntentV206 x=mapOne(jdbc,json,t,id);append(t,x.intentId(),x.assignmentId(),"PENDING","CLAIMED","WORKER_CLAIMED",Map.of("workerId",w));return x;
    }catch(EmptyResultDataAccessException e){return null;}}

    @Transactional(readOnly=true)
    public ExecutionDispatchIntentV206 revalidateClaim(String tenantId,String intentId,String workerId){String t=req(tenantId,"tenantId");bind(t);OffsetDateTime now=OffsetDateTime.now();Integer ok=jdbc.queryForObject("select count(*) from execution_dispatch_intents_v206 i where i.tenant_id=:tenant and i.intent_id=:id and i.status='CLAIMED' and i.claimed_by=:worker and i.claim_until>:now and exists(select 1 from execution_leases_v206 l where l.tenant_id=i.tenant_id and l.lease_id=i.lease_id and l.assignment_id=i.assignment_id and l.fencing_token=i.fencing_token and l.status='ACTIVE' and l.lease_until>:now) and exists(select 1 from flow_routing_migration_state f where f.tenant_id=i.tenant_id and f.flow_id=i.flow_id and f.migration_state='NEW_AUTHORITATIVE')",new MapSqlParameterSource("tenant",t).addValue("id",req(intentId,"intentId")).addValue("worker",req(workerId,"workerId")).addValue("now",now),Integer.class);if(ok==null||ok!=1)throw new IllegalStateException("A0_R7_INTENT_FENCE_OR_AUTHORITY_LOST");return mapOne(jdbc,json,t,intentId);}

    @Transactional
    public ExecutionDispatchIntentV206 markHandedOff(String tenantId,String intentId,String workerId,String externalRef){String t=req(tenantId,"tenantId");bind(t);ExecutionDispatchIntentV206 before=mapOne(jdbc,json,t,intentId);int rows=jdbc.update("update execution_dispatch_intents_v206 set status='HANDED_OFF',handed_off_at=now(),external_execution_ref=:ref,claimed_by=null,claim_token=null,claim_until=null,updated_at=now() where tenant_id=:tenant and intent_id=:id and status='CLAIMED' and claimed_by=:worker and claim_until>now()",new MapSqlParameterSource("tenant",t).addValue("id",req(intentId,"intentId")).addValue("worker",req(workerId,"workerId")).addValue("ref",req(externalRef,"externalRef")));if(rows!=1)throw new IllegalStateException("A0_R7_INTENT_HANDOFF_CLAIM_LOST");append(t,intentId,before.assignmentId(),before.status(),"HANDED_OFF","DURABLE_RUNTIME_OUTBOX_HANDOFF",Map.of("externalExecutionRef",externalRef));return mapOne(jdbc,json,t,intentId);}
    @Transactional
    public ExecutionDispatchIntentV206 markBlocked(String tenantId,String intentId,String code,String message){return transition(tenantId,intentId,null,"BLOCKED",code,null,code,message);}
    @Transactional
    public ExecutionDispatchIntentV206 markDeliveryUnknown(String tenantId,String intentId,String code,String message){String t=req(tenantId,"tenantId");bind(t);OffsetDateTime now=OffsetDateTime.now();ExecutionDispatchIntentV206 before=mapOne(jdbc,json,t,intentId);jdbc.update("update execution_dispatch_intents_v206 set status='DELIVERY_UNKNOWN',delivery_unknown_since=coalesce(delivery_unknown_since,:now),last_error_code=:code,last_error_message=:message,claimed_by=null,claim_token=null,claim_until=null,updated_at=:now where tenant_id=:tenant and intent_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",intentId).addValue("now",now).addValue("code",code).addValue("message",message));append(t,intentId,before.assignmentId(),before.status(),"DELIVERY_UNKNOWN",code,Map.of("message",message==null?"":message));return mapOne(jdbc,json,t,intentId);}

    @Transactional
    public ExecutionDispatchIntentV206 markNetworkResultByDispatchRequest(String tenantId,String dispatchRequestId,boolean success,boolean unknown,String code,String message){String t=req(tenantId,"tenantId");bind(t);String next=success?"ACKNOWLEDGED":(unknown?"DELIVERY_UNKNOWN":"DELIVERY_FAILED");return transitionByExternalRef(t,"dispatch:"+req(dispatchRequestId,"dispatchRequestId"),"SEND_STARTED",next,code==null?next:code,message);}

    @Transactional(readOnly=true) public List<Map<String,Object>> recent(String tenantId,int limit){String t=req(tenantId,"tenantId");bind(t);return jdbc.queryForList("select * from execution_safety_trace_v206 where tenant_id=:tenant order by created_at desc limit :limit",new MapSqlParameterSource("tenant",t).addValue("limit",Math.max(1,Math.min(limit<=0?100:limit,500))));}

    private ExecutionDispatchIntentV206 transitionByExternalRef(String tenant,String ref,String expected,String next,String reason,String message){String intentId;try{intentId=jdbc.queryForObject("select intent_id from execution_dispatch_intents_v206 where tenant_id=:tenant and external_execution_ref=:ref and status=:expected",new MapSqlParameterSource("tenant",tenant).addValue("ref",ref).addValue("expected",expected),String.class);}catch(EmptyResultDataAccessException e){return null;}if(intentId==null)return null;ExecutionDispatchIntentV206 before=mapOne(jdbc,json,tenant,intentId);OffsetDateTime now=OffsetDateTime.now();int rows=jdbc.update("update execution_dispatch_intents_v206 set status=:next,send_started_at=case when :next='SEND_STARTED' then coalesce(send_started_at,:now) else send_started_at end,delivery_unknown_since=case when :next='DELIVERY_UNKNOWN' then coalesce(delivery_unknown_since,:now) else delivery_unknown_since end,last_error_code=case when :next in ('DELIVERY_FAILED','DELIVERY_UNKNOWN') then :reason else last_error_code end,last_error_message=case when :next in ('DELIVERY_FAILED','DELIVERY_UNKNOWN') then :message else last_error_message end,updated_at=:now where tenant_id=:tenant and intent_id=:id and status=:expected",new MapSqlParameterSource("tenant",tenant).addValue("id",before.intentId()).addValue("expected",expected).addValue("next",next).addValue("now",now).addValue("reason",reason).addValue("message",message));if(rows!=1)throw new IllegalStateException("A0_R7_NETWORK_LIFECYCLE_TRANSITION_CONFLICT");append(tenant,before.intentId(),before.assignmentId(),expected,next,reason,Map.of("externalExecutionRef",ref,"message",message==null?"":message));return mapOne(jdbc,json,tenant,before.intentId());}

    private ExecutionDispatchIntentV206 transition(String tenantId,String intentId,String expected,String next,String reason,String externalRef,String code,String message){String t=req(tenantId,"tenantId");bind(t);ExecutionDispatchIntentV206 before=mapOne(jdbc,json,t,intentId);String sql="update execution_dispatch_intents_v206 set status=:next,handed_off_at=case when :next='HANDED_OFF' then now() else handed_off_at end,external_execution_ref=coalesce(:ref,external_execution_ref),last_error_code=coalesce(:code,last_error_code),last_error_message=coalesce(:message,last_error_message),claimed_by=null,claim_token=null,claim_until=null,updated_at=now() where tenant_id=:tenant and intent_id=:id"+(expected==null?"":" and status=:expected");MapSqlParameterSource p=new MapSqlParameterSource("tenant",t).addValue("id",intentId).addValue("next",next).addValue("ref",externalRef).addValue("code",code).addValue("message",message).addValue("expected",expected);if(jdbc.update(sql,p)!=1)throw new IllegalStateException("A0_R7_INTENT_TRANSITION_CONFLICT");append(t,intentId,before.assignmentId(),before.status(),next,reason,Map.of("externalExecutionRef",externalRef==null?"":externalRef));return mapOne(jdbc,json,t,intentId);}
    private void append(String t,String intent,String assignment,String from,String to,String reason,Map<String,Object> evidence){jdbc.update("insert into execution_dispatch_intent_events_v206(tenant_id,event_id,intent_id,assignment_id,from_status,to_status,reason_code,actor_ref,evidence_json,occurred_at) values(:tenant,:event,:intent,:assignment,:from,:to,:reason,:actor,cast(:evidence as jsonb),now())",new MapSqlParameterSource("tenant",t).addValue("event","dispatch-intent-event-"+UUID.randomUUID()).addValue("intent",intent).addValue("assignment",assignment).addValue("from",from).addValue("to",to).addValue("reason",reason).addValue("actor",actor()).addValue("evidence",write(evidence)));}
    static ExecutionDispatchIntentV206 mapOne(NamedParameterJdbcTemplate jdbc,ObjectMapper json,String t,String id){return jdbc.queryForObject("select * from execution_dispatch_intents_v206 where tenant_id=:tenant and intent_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",id),(rs,n)->new ExecutionDispatchIntentV206(rs.getString("intent_id"),rs.getString("tenant_id"),rs.getString("assignment_id"),rs.getString("lease_id"),rs.getLong("fencing_token"),rs.getString("task_id"),rs.getString("plan_id"),rs.getInt("plan_revision"),rs.getString("step_id"),rs.getString("flow_id"),rs.getString("binding_id"),rs.getString("provider_id"),rs.getString("provider_type"),rs.getString("selected_adapter_id"),rs.getString("adapter_type"),rs.getString("execution_safety_mode"),rs.getString("side_effect"),rs.getString("write_semantics"),readMap(json,rs.getString("payload_json")),rs.getString("status"),rs.getInt("attempt_count"),rs.getString("claimed_by"),rs.getString("claim_token"),rs.getObject("claim_until",OffsetDateTime.class),rs.getObject("send_started_at",OffsetDateTime.class),rs.getObject("handed_off_at",OffsetDateTime.class),rs.getString("external_execution_ref"),rs.getObject("delivery_unknown_since",OffsetDateTime.class),rs.getString("last_error_code"),rs.getString("last_error_message"),rs.getObject("created_at",OffsetDateTime.class),rs.getObject("updated_at",OffsetDateTime.class)));}
    private static Map<String,Object> readMap(ObjectMapper json,String v){try{return v==null||v.isBlank()?Map.of():json.readValue(v,OBJECT_MAP);}catch(Exception e){return Map.of();}} private String write(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalStateException(e);}}
    private void bind(String t){IamTenantExecutionContext c=IamTenantContextHolder.current().orElse(null);if(c!=null&&!"INSTANCE".equalsIgnoreCase(c.tenantId())&&!t.equals(c.tenantId()))throw new IllegalArgumentException("Tenant context mismatch for A0-R7 intent store");jdbc.getJdbcTemplate().queryForObject("select set_config('app.current_tenant_id', ?, true)",String.class,t);jdbc.getJdbcTemplate().queryForObject("select set_config('app.current_actor_id', ?, true)",String.class,actor());}private String actor(){IamTenantExecutionContext c=IamTenantContextHolder.current().orElse(null);return c==null||c.actorId()==null?"a0-r7-intent-store":c.actorId();}private static String req(String v,String f){if(v==null||v.isBlank())throw new IllegalArgumentException(f+" is required");return v.trim();}
}
