package com.opensocket.aievent.core.capability;

import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantContextHolder;
import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantExecutionContext;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

/**
 * Legacy Phase11 compatibility boundary. Stage12 retires direct runtime activation. Historical policy,
 * shadow and certification evidence remains available, but resolveForRuntime can only fail closed to
 * the adaptive path. The new Stage12 Fast Path returns semantic hints and never starts a Plan/Run.
 */
@Service
public class FastPathRuntimeIntegrationService implements FastPathRuntimePort {
    private static final Set<String> POLICY_STATUSES=Set.of("DRAFT","ACTIVE","DISABLED","RETIRED");
    private static final Set<String> CERT_STATUSES=Set.of("CERTIFIED","SUSPENDED","REVOKED");
    private static final TypeReference<Map<String,Object>> MAP=new TypeReference<>(){};
    private static final TypeReference<List<String>> STRINGS=new TypeReference<>(){};
    private final NamedParameterJdbcTemplate jdbc; private final ObjectMapper json;
    public FastPathRuntimeIntegrationService(NamedParameterJdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}

    @Transactional(readOnly=true)
    public List<FastPathRuntimePolicy> policies(String tenantId,String status,int limit){String t=tenant(tenantId);bind(t);MapSqlParameterSource p=new MapSqlParameterSource("tenant",t).addValue("limit",limit(limit));String w=" where tenant_id=:tenant";if(!blank(status)){w+=" and status=:status";p.addValue("status",policyStatus(status));}return jdbc.query("select * from fast_path_runtime_policies"+w+" order by policy_id limit :limit",p,new PolicyMapper());}

    @Transactional
    public FastPathRuntimePolicy upsertPolicy(String tenantId,String pathId,FastPathRuntimePolicy req,String reason){String t=tenant(tenantId);bind(t);if(req==null)throw new IllegalArgumentException("Fast Path Runtime Policy body is required");if(req.activeFastPathEnabled())throw new IllegalArgumentException("LEGACY_PHASE11_DIRECT_RUNTIME_RETIRED_STAGE12");String id=required(first(pathId,req.policyId()),"policyId"),status=policyStatus(req.status());if(req.minShadowComparisons()<1)throw new IllegalArgumentException("minShadowComparisons must be >= 1");rate(req.minShadowPlanMatchRate(),"minShadowPlanMatchRate");rate(req.minShadowCapabilityCoverage(),"minShadowCapabilityCoverage");FastPathRuntimePolicy old=findPolicy(t,id).orElse(null);if(old!=null&&blank(reason))throw new IllegalArgumentException("X-Change-Reason is required when changing an existing Fast Path Runtime Policy");if("ACTIVE".equals(status)){Integer n=jdbc.queryForObject("select count(*) from fast_path_runtime_policies where tenant_id=:tenant and status='ACTIVE' and policy_id<>:id",new MapSqlParameterSource("tenant",t).addValue("id",id),Integer.class);if(n!=null&&n>0)throw new IllegalArgumentException("Only one ACTIVE Fast Path Runtime Policy is allowed per Tenant");}int version=old==null?1:old.version()+1;OffsetDateTime now=OffsetDateTime.now(),created=old==null?now:old.createdAt();jdbc.update("""
      insert into fast_path_runtime_policies(tenant_id,policy_id,display_name,active_fast_path_enabled,shadow_evaluation_enabled,emergency_kill_switch,min_shadow_comparisons,min_shadow_plan_match_rate,min_shadow_capability_coverage,status,version,created_at,updated_at)
      values(:tenant,:id,:name,:active,:shadow,:kill,:n,:match,:coverage,:status,:version,:created,:updated)
      on conflict(tenant_id,policy_id) do update set display_name=excluded.display_name,active_fast_path_enabled=excluded.active_fast_path_enabled,shadow_evaluation_enabled=excluded.shadow_evaluation_enabled,emergency_kill_switch=excluded.emergency_kill_switch,min_shadow_comparisons=excluded.min_shadow_comparisons,min_shadow_plan_match_rate=excluded.min_shadow_plan_match_rate,min_shadow_capability_coverage=excluded.min_shadow_capability_coverage,status=excluded.status,version=excluded.version,updated_at=excluded.updated_at
      """,new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("name",required(req.displayName(),"displayName")).addValue("active",req.activeFastPathEnabled()).addValue("shadow",req.shadowEvaluationEnabled()).addValue("kill",req.emergencyKillSwitch()).addValue("n",req.minShadowComparisons()).addValue("match",req.minShadowPlanMatchRate()).addValue("coverage",req.minShadowCapabilityCoverage()).addValue("status",status).addValue("version",version).addValue("created",created).addValue("updated",now));FastPathRuntimePolicy saved=findPolicy(t,id).orElseThrow();appendPolicyVersion(saved,old==null?"INITIAL_CREATE":reason);if(old!=null&&old.version()!=saved.version())suspendStaleCertifications(t,"RUNTIME_POLICY_VERSION_CHANGED");return saved;}

    @Transactional(readOnly=true)
    public List<FastPathRuntimePolicyVersion> policyVersions(String tenantId,String id){String t=tenant(tenantId);bind(t);return jdbc.query("select * from fast_path_runtime_policy_versions where tenant_id=:tenant and policy_id=:id order by version desc",new MapSqlParameterSource("tenant",t).addValue("id",required(id,"policyId")),(r,n)->new FastPathRuntimePolicyVersion(t,r.getString("policy_id"),r.getInt("version"),readMap(r.getString("snapshot_json")),r.getString("change_reason"),r.getString("actor_ref"),r.getObject("created_at",OffsetDateTime.class)));}

    /** Records non-authoritative SHADOW evidence by comparing a pattern with the actual adaptive Plan. */
    @Transactional
    public FastPathShadowComparison compareShadow(String tenantId,FastPathShadowComparisonRequest req){String t=tenant(tenantId);bind(t);if(req==null)throw new IllegalArgumentException("Shadow comparison request is required");FastPathRuntimePolicy runtime=activePolicy(t).orElseThrow(()->new IllegalArgumentException("FAST_PATH_RUNTIME_POLICY_NOT_CONFIGURED"));if(!runtime.shadowEvaluationEnabled())throw new IllegalArgumentException("SHADOW_EVALUATION_DISABLED");RoutingPatternView p=pattern(t,required(req.patternId(),"patternId"));if(!"SHADOW".equals(p.status()))throw new IllegalArgumentException("Only a SHADOW Routing Pattern may create shadow comparison evidence");int revision=req.actualPlanRevision()==null?currentPlanRevision(t,required(req.actualPlanId(),"actualPlanId")):req.actualPlanRevision();Map<String,Object> actual=actualPlanTemplate(t,req.actualPlanId(),revision);String ph=hashCanonical(p.planTemplate()),ah=hashCanonical(actual);Set<String> patternCaps=capabilityKeys(p.planTemplate()),actualCaps=capabilityKeys(actual);double coverage=patternCaps.isEmpty()?0d:((double)actualCaps.stream().filter(patternCaps::contains).count())/patternCaps.size();boolean dependency=dependencyShape(p.planTemplate()).equals(dependencyShape(actual));boolean match=ph.equals(ah);String result=match?"MATCHED":"DIVERGED";List<String> reasons=new ArrayList<>();reasons.add(match?"SHADOW_PLAN_MATCHED":"SHADOW_PLAN_DIVERGED");if(!dependency)reasons.add("SHADOW_DEPENDENCY_TOPOLOGY_DIVERGED");if(coverage<1d)reasons.add("SHADOW_CAPABILITY_COVERAGE_INCOMPLETE");reasons.add("SHADOW_NEVER_AFFECTS_REAL_EXECUTION");String id="shadow-comparison-"+UUID.randomUUID();OffsetDateTime at=OffsetDateTime.now();jdbc.update("insert into fast_path_shadow_comparisons(tenant_id,comparison_id,pattern_id,pattern_version,actual_plan_id,actual_plan_revision,result,plan_match,dependency_match,capability_coverage,pattern_template_hash,actual_template_hash,reason_codes_json,observed_at) values(:tenant,:id,:pattern,:version,:plan,:revision,:result,:match,:dependency,:coverage,:ph,:ah,cast(:reasons as jsonb),:at)",new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("pattern",p.patternId()).addValue("version",p.version()).addValue("plan",req.actualPlanId()).addValue("revision",revision).addValue("result",result).addValue("match",match).addValue("dependency",dependency).addValue("coverage",coverage).addValue("ph",ph).addValue("ah",ah).addValue("reasons",write(reasons)).addValue("at",at));return shadow(t,id);}

    @Transactional(readOnly=true)
    public List<FastPathShadowComparison> shadowComparisons(String tenantId,String patternId,int limit){String t=tenant(tenantId);bind(t);MapSqlParameterSource p=new MapSqlParameterSource("tenant",t).addValue("limit",limit(limit));String w=" where tenant_id=:tenant";if(!blank(patternId)){w+=" and pattern_id=:pattern";p.addValue("pattern",patternId.trim());}return jdbc.query("select * from fast_path_shadow_comparisons"+w+" order by observed_at desc,comparison_id desc limit :limit",p,new ShadowMapper());}

    /** Human certification is separate from Phase10 ACTIVE semantic status; exact pattern/runtime-policy versions are pinned. */
    @Transactional
    public FastPathRuntimeCertification certify(String tenantId,String patternId,FastPathCertificationRequest req){String t=tenant(tenantId);bind(t);if(req==null)throw new IllegalArgumentException("Certification request is required");String target=required(req.targetStatus(),"targetStatus").toUpperCase(Locale.ROOT);if(!CERT_STATUSES.contains(target))throw new IllegalArgumentException("Unsupported certification status: "+target);String why=required(req.reason(),"reason");RoutingPatternView p=pattern(t,required(patternId,"patternId"));FastPathRuntimePolicy runtime=activePolicy(t).orElseThrow(()->new IllegalArgumentException("FAST_PATH_RUNTIME_POLICY_NOT_CONFIGURED"));if("CERTIFIED".equals(target)){if(!"ACTIVE".equals(p.status()))throw new IllegalArgumentException("Runtime certification requires a Phase10 ACTIVE Routing Pattern");ShadowMetrics m=shadowMetrics(t,p);if(m.count()<runtime.minShadowComparisons())throw new IllegalArgumentException("MIN_SHADOW_COMPARISONS_NOT_MET");if(m.matchRate()<runtime.minShadowPlanMatchRate())throw new IllegalArgumentException("MIN_SHADOW_PLAN_MATCH_RATE_NOT_MET");if(m.coverage()<runtime.minShadowCapabilityCoverage())throw new IllegalArgumentException("MIN_SHADOW_CAPABILITY_COVERAGE_NOT_MET");return appendCertification(t,p,runtime,target,m,why);}FastPathRuntimeCertification current=latestCertification(t,p.patternId()).orElseThrow(()->new IllegalArgumentException("No existing runtime certification to "+target));return appendCertification(t,p,runtime,target,new ShadowMetrics(current.shadowComparisonCount(),current.shadowPlanMatchRate(),current.shadowCapabilityCoverage()),why);}

    @Transactional(readOnly=true)
    public List<FastPathRuntimeCertification> certifications(String tenantId,String patternId,int limit){String t=tenant(tenantId);bind(t);MapSqlParameterSource p=new MapSqlParameterSource("tenant",t).addValue("limit",limit(limit));String w=" where tenant_id=:tenant";if(!blank(patternId)){w+=" and pattern_id=:pattern";p.addValue("pattern",patternId.trim());}return jdbc.query("select * from fast_path_runtime_certifications"+w+" order by certified_at desc,certification_id desc limit :limit",p,new CertificationMapper());}

    /** Internal runtime call. On any missing/stale certification or kill switch it persists evidence and falls back, never guesses. */
    @Override @Transactional
    public FastPathRuntimeDecision resolveForRuntime(String tenantId,FastPathRuntimeRequest req){String t=tenant(tenantId);bind(t);if(req==null)throw new IllegalArgumentException("Fast Path runtime request is required");String task=required(req.taskRef(),"taskRef"),key=required(req.idempotencyKey(),"idempotencyKey");Optional<FastPathRuntimeDecision> prior=priorDecision(t,task,key);if(prior.isPresent())return prior.get();List<String> keys=validateSignatureRequirements(t,req.requiredCapabilities());String sig=signature(req.classification(),keys);return decision(t,task,key,sig,"FALLBACK_ADAPTIVE_PATH",null,null,null,null,null,null,null,List.of("LEGACY_PHASE11_DIRECT_RUNTIME_RETIRED_STAGE12","MEMORY_MAY_RECOMMEND_BUT_NEVER_AUTHORIZE","FALLBACK_ADAPTIVE_PATH"));}

    @Transactional(readOnly=true)
    public List<FastPathRuntimeDecision> runtimeDecisions(String tenantId,String taskRef,int limit){String t=tenant(tenantId);bind(t);MapSqlParameterSource p=new MapSqlParameterSource("tenant",t).addValue("limit",limit(limit));String w=" where tenant_id=:tenant";if(!blank(taskRef)){w+=" and task_ref=:task";p.addValue("task",taskRef.trim());}return jdbc.query("select * from fast_path_runtime_decisions"+w+" order by decided_at desc,decision_id desc limit :limit",p,new DecisionMapper());}

    private FastPathRuntimeCertification appendCertification(String t,RoutingPatternView p,FastPathRuntimePolicy runtime,String status,ShadowMetrics m,String reason){String id="runtime-certification-"+UUID.randomUUID();OffsetDateTime at=OffsetDateTime.now();jdbc.update("insert into fast_path_runtime_certifications(tenant_id,certification_id,pattern_id,pattern_version,runtime_policy_id,runtime_policy_version,status,shadow_comparison_count,shadow_plan_match_rate,shadow_capability_coverage,reason,actor_ref,certified_at) values(:tenant,:id,:pattern,:pv,:policy,:policyVersion,:status,:count,:match,:coverage,:reason,:actor,:at)",new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("pattern",p.patternId()).addValue("pv",p.version()).addValue("policy",runtime.policyId()).addValue("policyVersion",runtime.version()).addValue("status",status).addValue("count",m.count()).addValue("match",m.matchRate()).addValue("coverage",m.coverage()).addValue("reason",reason).addValue("actor",actor()).addValue("at",at));return latestCertification(t,p.patternId()).orElseThrow();}
    private ShadowMetrics shadowMetrics(String t,RoutingPatternView p){String hash=hashCanonical(p.planTemplate());List<FastPathShadowComparison> xs=jdbc.query("select * from fast_path_shadow_comparisons where tenant_id=:tenant and pattern_id=:pattern and pattern_template_hash=:hash order by observed_at desc",new MapSqlParameterSource("tenant",t).addValue("pattern",p.patternId()).addValue("hash",hash),new ShadowMapper());if(xs.isEmpty())return new ShadowMetrics(0,0,0);double match=xs.stream().filter(FastPathShadowComparison::planMatch).count()/(double)xs.size();double coverage=xs.stream().mapToDouble(FastPathShadowComparison::capabilityCoverage).average().orElse(0);return new ShadowMetrics(xs.size(),match,coverage);}
    private void suspendStaleCertifications(String t,String reason){List<Map<String,Object>> rows=jdbc.queryForList("select distinct on(pattern_id) pattern_id,pattern_version,shadow_comparison_count,shadow_plan_match_rate,shadow_capability_coverage from fast_path_runtime_certifications where tenant_id=:tenant and status='CERTIFIED' order by pattern_id,certified_at desc",new MapSqlParameterSource("tenant",t));FastPathRuntimePolicy p=activePolicy(t).orElse(null);if(p==null)return;for(Map<String,Object> r:rows){RoutingPatternView pattern=pattern(t,String.valueOf(r.get("pattern_id")));appendCertification(t,pattern,p,"SUSPENDED",new ShadowMetrics(((Number)r.get("shadow_comparison_count")).intValue(),((Number)r.get("shadow_plan_match_rate")).doubleValue(),((Number)r.get("shadow_capability_coverage")).doubleValue()),reason);}}
    private List<String> validatePatternCurrent(String t,RoutingPatternView p){List<String> reasons=new ArrayList<>();Map<String,Object> lp=oneOrNull("select policy_id,version,status from learning_policies where tenant_id=:tenant and status='ACTIVE'",t,null);if(lp==null||!p.learningPolicyId().equals(str(lp,"policy_id"))||p.learningPolicyVersion()!=((Number)lp.get("version")).intValue())reasons.add("LEARNING_POLICY_DRIFT");for(String k:p.capabilityKeys())if(!canonicalKeyActive(t,k))reasons.add("CAPABILITY_DRIFT:"+k);return reasons;}
    private List<String> validateSignatureRequirements(String t,List<CapabilityRequirement> reqs){if(reqs==null||reqs.isEmpty())throw new IllegalArgumentException("requiredCapabilities must not be empty");List<String> keys=new ArrayList<>();for(CapabilityRequirement r:reqs){if(r==null)continue;String cap=required(r.capabilityCode(),"capabilityCode"),op=required(r.operation(),"operation").toUpperCase(Locale.ROOT);if(!canonicalKeyActive(t,cap+"#"+op))throw new IllegalArgumentException("Canonical Capability is not ACTIVE or operation unsupported: "+cap+"#"+op);keys.add(cap+"#"+op);}Collections.sort(keys);return List.copyOf(keys);}
    private boolean canonicalKeyActive(String t,String key){int i=key.lastIndexOf('#');if(i<=0)return false;Integer n=jdbc.queryForObject("select count(*) from capability_definitions where tenant_id=:tenant and capability_code=:cap and status='ACTIVE' and jsonb_exists(operations_json, cast(:op as text))",new MapSqlParameterSource("tenant",t).addValue("cap",key.substring(0,i)).addValue("op",key.substring(i+1)),Integer.class);return n!=null&&n==1;}
    private Map<String,Object> actualPlanTemplate(String t,String plan,int rev){List<RawStep> raw=jdbc.query("select step_id,capability_requirement_json,depends_on_json,purpose,required,sequence_hint from execution_plan_revision_steps where tenant_id=:tenant and plan_id=:plan and revision=:revision order by coalesce(sequence_hint,2147483647),step_id",new MapSqlParameterSource("tenant",t).addValue("plan",plan).addValue("revision",rev),(r,n)->new RawStep(r.getString("step_id"),readMap(r.getString("capability_requirement_json")),readStrings(r.getString("depends_on_json")),r.getString("purpose"),r.getBoolean("required"),(Integer)r.getObject("sequence_hint")));if(raw.isEmpty())throw new IllegalArgumentException("Actual Plan revision has no steps");Map<String,String> stable=new LinkedHashMap<>();for(int i=0;i<raw.size();i++)stable.put(raw.get(i).id(),String.format(Locale.ROOT,"S%03d",i+1));List<Map<String,Object>> steps=new ArrayList<>();for(RawStep r:raw){Map<String,Object> m=new LinkedHashMap<>();m.put("stepId",stable.get(r.id()));m.put("requiredCapability",r.req());m.put("dependsOn",r.deps().stream().map(d->stable.getOrDefault(d,"UNKNOWN_DEPENDENCY")).sorted().toList());m.put("purpose",r.purpose());m.put("required",r.required());if(r.seq()!=null)m.put("sequenceHint",r.seq());steps.add(m);}return Map.of("contract","phase10-semantic-plan-template-v1","steps",steps,"executionRule","EACH_STEP_MUST_REEVALUATE_WHO_MAY_WHO_SHOULD_HOW");}
    private Set<String> capabilityKeys(Map<String,Object> template){Set<String> out=new TreeSet<>();Object o=template.get("steps");if(o instanceof List<?> l)for(Object x:l)if(x instanceof Map<?,?> m){Object r=m.get("requiredCapability");if(r instanceof Map<?,?> rm){String c=Objects.toString(rm.get("capabilityCode"),"").trim(),op=Objects.toString(rm.get("operation"),"").trim().toUpperCase(Locale.ROOT);if(!c.isBlank()&&!op.isBlank())out.add(c+"#"+op);}}return out;}
    private List<String> dependencyShape(Map<String,Object> template){List<String> out=new ArrayList<>();Object o=template.get("steps");if(o instanceof List<?> l)for(Object x:l)if(x instanceof Map<?,?> m){String id=Objects.toString(m.get("stepId"),"");Object ds=m.get("dependsOn");List<String> deps=new ArrayList<>();if(ds instanceof List<?> dl)for(Object d:dl)deps.add(Objects.toString(d,""));Collections.sort(deps);out.add(id+"<-"+String.join(",",deps));}Collections.sort(out);return out;}
    private String signature(String classification,List<String> keys){try{String base=Objects.toString(classification,"").trim().toUpperCase(Locale.ROOT)+"|"+String.join("|",new TreeSet<>(keys));return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(base.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException("Unable to calculate problem signature",e);}}
    private String hashCanonical(Object value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(json.writeValueAsBytes(canonical(value))));}catch(Exception e){throw new IllegalArgumentException("Unable to hash semantic Plan",e);}}
    private Object canonical(Object v){if(v instanceof Map<?,?> m){TreeMap<String,Object> t=new TreeMap<>();for(var e:m.entrySet())t.put(String.valueOf(e.getKey()),canonical(e.getValue()));return t;}if(v instanceof List<?> l){List<Object> out=new ArrayList<>();for(Object x:l)out.add(canonical(x));return out;}return v;}
    private int currentPlanRevision(String t,String plan){Integer n=jdbc.queryForObject("select current_revision from execution_plans where tenant_id=:tenant and plan_id=:plan",new MapSqlParameterSource("tenant",t).addValue("plan",plan),Integer.class);if(n==null)throw new IllegalArgumentException("Plan not found: "+plan);return n;}
    private RoutingPatternView pattern(String t,String id){try{return jdbc.queryForObject("select * from routing_patterns where tenant_id=:tenant and pattern_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",id),new PatternMapper());}catch(EmptyResultDataAccessException e){throw new IllegalArgumentException("Routing Pattern not found: "+id);}}
    private FastPathShadowComparison shadow(String t,String id){return jdbc.queryForObject("select * from fast_path_shadow_comparisons where tenant_id=:tenant and comparison_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",id),new ShadowMapper());}
    private Optional<FastPathRuntimePolicy> activePolicy(String t){try{return Optional.of(jdbc.queryForObject("select * from fast_path_runtime_policies where tenant_id=:tenant and status='ACTIVE'",new MapSqlParameterSource("tenant",t),new PolicyMapper()));}catch(EmptyResultDataAccessException e){return Optional.empty();}}
    private Optional<FastPathRuntimePolicy> findPolicy(String t,String id){try{return Optional.of(jdbc.queryForObject("select * from fast_path_runtime_policies where tenant_id=:tenant and policy_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",id),new PolicyMapper()));}catch(EmptyResultDataAccessException e){return Optional.empty();}}
    private Optional<FastPathRuntimeCertification> latestCertification(String t,String pattern){try{return Optional.of(jdbc.queryForObject("select * from fast_path_runtime_certifications where tenant_id=:tenant and pattern_id=:pattern order by certified_at desc,certification_id desc limit 1",new MapSqlParameterSource("tenant",t).addValue("pattern",pattern),new CertificationMapper()));}catch(EmptyResultDataAccessException e){return Optional.empty();}}
    private Optional<FastPathRuntimeDecision> priorDecision(String t,String task,String key){try{return Optional.of(jdbc.queryForObject("select * from fast_path_runtime_decisions where tenant_id=:tenant and task_ref=:task and idempotency_key=:key",new MapSqlParameterSource("tenant",t).addValue("task",task).addValue("key",key),new DecisionMapper()));}catch(EmptyResultDataAccessException e){return Optional.empty();}}
    private FastPathRuntimeDecision decision(String t,String task,String key,String sig,String result,String pattern,Integer pv,String cert,String plan,Integer rev,String pd,String run,List<String> reasons){String id="fast-runtime-decision-"+UUID.randomUUID();OffsetDateTime at=OffsetDateTime.now();jdbc.update("insert into fast_path_runtime_decisions(tenant_id,decision_id,task_ref,idempotency_key,problem_signature,result,pattern_id,pattern_version,certification_id,plan_id,plan_revision,plan_decision_id,run_id,reason_codes_json,decided_at) values(:tenant,:id,:task,:key,:sig,:result,:pattern,:pv,:cert,:plan,:rev,:pd,:run,cast(:reasons as jsonb),:at)",new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("task",task).addValue("key",key).addValue("sig",sig).addValue("result",result).addValue("pattern",pattern).addValue("pv",pv).addValue("cert",cert).addValue("plan",plan).addValue("rev",rev).addValue("pd",pd).addValue("run",run).addValue("reasons",write(reasons)).addValue("at",at));return priorDecision(t,task,key).orElseThrow();}
    private void appendPolicyVersion(FastPathRuntimePolicy p,String reason){jdbc.update("insert into fast_path_runtime_policy_versions(tenant_id,policy_id,version,snapshot_json,change_reason,actor_ref,created_at) values(:tenant,:id,:version,cast(:snapshot as jsonb),:reason,:actor,:at)",new MapSqlParameterSource("tenant",p.tenantId()).addValue("id",p.policyId()).addValue("version",p.version()).addValue("snapshot",write(p)).addValue("reason",required(reason,"changeReason")).addValue("actor",actor()).addValue("at",OffsetDateTime.now()));}
    private Map<String,Object> oneOrNull(String sql,String t,String id){try{MapSqlParameterSource p=new MapSqlParameterSource("tenant",t);if(id!=null)p.addValue("id",id);return jdbc.queryForMap(sql,p);}catch(EmptyResultDataAccessException e){return null;}}
    private String actor(){IamTenantExecutionContext c=IamTenantContextHolder.current().orElse(null);return c==null||blank(c.actorId())?"fast-path-runtime":c.actorId();}
    private String tenant(String s){return required(s,"tenantId");}private void bind(String t){IamTenantContextHolder.current().ifPresent(c->{if(!t.equals(c.tenantId()))throw new IllegalArgumentException("Tenant mismatch");});}
    private String policyStatus(String s){String v=blank(s)?"DRAFT":s.trim().toUpperCase(Locale.ROOT);if(!POLICY_STATUSES.contains(v))throw new IllegalArgumentException("Unsupported runtime policy status: "+v);return v;}private int limit(int n){return Math.max(1,Math.min(n,500));}private boolean blank(String s){return s==null||s.isBlank();}private String required(String s,String n){if(blank(s))throw new IllegalArgumentException(n+" is required");return s.trim();}private String first(String a,String b){return !blank(a)?a:b;}private void rate(double d,String n){if(d<0||d>1)throw new IllegalArgumentException(n+" must be between 0 and 1");}private String str(Map<String,Object> m,String k){Object v=m.get(k);return v==null?null:v.toString();}private String safe(String s){if(s==null)return "UNKNOWN";return s.length()>180?s.substring(0,180):s;}private List<String> merge(List<String>a,List<String>b){List<String> x=new ArrayList<>();if(a!=null)x.addAll(a);if(b!=null)x.addAll(b);return List.copyOf(new LinkedHashSet<>(x));}
    private String write(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new IllegalArgumentException("Unable to serialize Phase11 evidence",e);}}private Map<String,Object> readMap(String s){try{return s==null?Map.of():json.readValue(s,MAP);}catch(Exception e){throw new IllegalArgumentException("Invalid JSON evidence",e);}}private List<String> readStrings(String s){try{return s==null?List.of():json.readValue(s,STRINGS);}catch(Exception e){throw new IllegalArgumentException("Invalid JSON array evidence",e);}}
    private final class PolicyMapper implements RowMapper<FastPathRuntimePolicy>{public FastPathRuntimePolicy mapRow(ResultSet r,int n)throws SQLException{return new FastPathRuntimePolicy(r.getString("tenant_id"),r.getString("policy_id"),r.getString("display_name"),r.getBoolean("active_fast_path_enabled"),r.getBoolean("shadow_evaluation_enabled"),r.getBoolean("emergency_kill_switch"),r.getInt("min_shadow_comparisons"),r.getDouble("min_shadow_plan_match_rate"),r.getDouble("min_shadow_capability_coverage"),r.getString("status"),r.getInt("version"),r.getObject("created_at",OffsetDateTime.class),r.getObject("updated_at",OffsetDateTime.class));}}
    private final class ShadowMapper implements RowMapper<FastPathShadowComparison>{public FastPathShadowComparison mapRow(ResultSet r,int n)throws SQLException{return new FastPathShadowComparison(r.getString("comparison_id"),r.getString("tenant_id"),r.getString("pattern_id"),r.getInt("pattern_version"),r.getString("actual_plan_id"),r.getInt("actual_plan_revision"),r.getString("result"),r.getBoolean("plan_match"),r.getBoolean("dependency_match"),r.getDouble("capability_coverage"),r.getString("pattern_template_hash"),r.getString("actual_template_hash"),readStrings(r.getString("reason_codes_json")),r.getObject("observed_at",OffsetDateTime.class));}}
    private final class CertificationMapper implements RowMapper<FastPathRuntimeCertification>{public FastPathRuntimeCertification mapRow(ResultSet r,int n)throws SQLException{return new FastPathRuntimeCertification(r.getString("certification_id"),r.getString("tenant_id"),r.getString("pattern_id"),r.getInt("pattern_version"),r.getString("runtime_policy_id"),r.getInt("runtime_policy_version"),r.getString("status"),r.getInt("shadow_comparison_count"),r.getDouble("shadow_plan_match_rate"),r.getDouble("shadow_capability_coverage"),r.getString("reason"),r.getString("actor_ref"),r.getObject("certified_at",OffsetDateTime.class));}}
    private final class DecisionMapper implements RowMapper<FastPathRuntimeDecision>{public FastPathRuntimeDecision mapRow(ResultSet r,int n)throws SQLException{return new FastPathRuntimeDecision(r.getString("decision_id"),r.getString("tenant_id"),r.getString("task_ref"),r.getString("problem_signature"),r.getString("result"),r.getString("pattern_id"),(Integer)r.getObject("pattern_version"),r.getString("certification_id"),r.getString("plan_id"),(Integer)r.getObject("plan_revision"),r.getString("plan_decision_id"),r.getString("run_id"),readStrings(r.getString("reason_codes_json")),r.getObject("decided_at",OffsetDateTime.class));}}
    private final class PatternMapper implements RowMapper<RoutingPatternView>{public RoutingPatternView mapRow(ResultSet r,int n)throws SQLException{return new RoutingPatternView(r.getString("pattern_id"),r.getString("problem_signature"),r.getString("classification"),readStrings(r.getString("capability_keys_json")),readMap(r.getString("plan_template_json")),r.getString("status"),r.getInt("version"),r.getString("learning_policy_id"),r.getInt("learning_policy_version"));}}
    private record RoutingPatternView(String patternId,String problemSignature,String classification,List<String> capabilityKeys,Map<String,Object> planTemplate,String status,int version,String learningPolicyId,int learningPolicyVersion){}
    private record RawStep(String id,Map<String,Object> req,List<String> deps,String purpose,boolean required,Integer seq){}
    private record ShadowMetrics(int count,double matchRate,double coverage){}
}
