package com.opensocket.aievent.core.capability;

import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantContextHolder;
import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantExecutionContext;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Duration;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

/**
 * Phase 8 Governed Plan Execution authority.
 *
 * <p>A frozen Phase 7 revision is executed dependency-first. READY means dependency readiness only.
 * Every attempt must carry current WHO MAY -> WHO SHOULD -> HOW evidence. Retry clears the chain.
 * Fan-in consumes normalized Artifact references; Planner output never selects Provider/Agent/Pool/protocol.</p>
 */
@Service
public class GovernedPlanExecutionService {
    private static final Set<String> POLICY_STATUSES=Set.of("DRAFT","ACTIVE","DISABLED","RETIRED");
    private static final Set<String> MODES=Set.of("SIMULATION","RUNTIME");
    private static final Set<String> TERMINAL_STEPS=Set.of("SUCCEEDED","FAILED","TIMED_OUT","CANCELLED","SKIPPED");
    private static final TypeReference<List<String>> STRING_LIST=new TypeReference<>(){};
    private static final TypeReference<Map<String,Object>> OBJECT_MAP=new TypeReference<>(){};
    private static final TypeReference<List<Map<String,Object>>> MAP_LIST=new TypeReference<>(){};

    private final NamedParameterJdbcTemplate jdbc;
    private final ObjectMapper json;
    private final ObjectProvider<PlanChildTaskPort> childTasks;
    private final ObjectProvider<RuntimeStepAuthorityAutomationPort> authorityAutomation;
    private final List<ExecutionAdapterPort> adapters;
    private final List<PlanExecutionCancellationPort> cancellationPorts;
    private final CapabilityRuntimeAuthorizationEnvelopeService authorizationEnvelopes;
    private final PlanAdmissionService planAdmission;

    public GovernedPlanExecutionService(NamedParameterJdbcTemplate jdbc,ObjectMapper json,
            ObjectProvider<PlanChildTaskPort> childTasks,ObjectProvider<RuntimeStepAuthorityAutomationPort> authorityAutomation,
            List<ExecutionAdapterPort> adapters,List<PlanExecutionCancellationPort> cancellationPorts,
            CapabilityRuntimeAuthorizationEnvelopeService authorizationEnvelopes,PlanAdmissionService planAdmission){
        this.jdbc=jdbc;this.json=json;this.childTasks=childTasks;this.authorityAutomation=authorityAutomation;this.adapters=adapters==null?List.of():List.copyOf(adapters);
        this.cancellationPorts=cancellationPorts==null?List.of():List.copyOf(cancellationPorts);this.authorizationEnvelopes=authorizationEnvelopes;this.planAdmission=planAdmission;
    }

    @Transactional(readOnly=true)
    public List<PlanExecutionPolicy> listPolicies(String tenantId,String status,int limit){
        String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);MapSqlParameterSource p=new MapSqlParameterSource("tenant",tenant).addValue("limit",limit(limit));
        String w=" where tenant_id=:tenant";if(!blank(status)){w+=" and status=:status";p.addValue("status",normalizePolicyStatus(status));}
        return jdbc.query("select * from plan_execution_policies"+w+" order by policy_id limit :limit",p,new PolicyMapper());
    }

    @Transactional
    public PlanExecutionPolicy upsertPolicy(String tenantId,String pathPolicyId,PlanExecutionPolicy request,String changeReason){
        String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);if(request==null)throw new IllegalArgumentException("Plan Execution Policy request body is required");
        String id=requireNonBlank(first(pathPolicyId,request.policyId()),"policyId");String status=normalizePolicyStatus(request.status());
        int attempts=between(request.maxAttemptsPerStep(),1,20,"maxAttemptsPerStep");long timeout=betweenLong(request.defaultStepTimeoutSeconds(),1,86400,"defaultStepTimeoutSeconds");int active=between(request.maxActiveSteps(),1,500,"maxActiveSteps");
        PlanExecutionPolicy existing=findPolicy(tenant,id).orElse(null);if(existing!=null&&blank(changeReason))throw new IllegalArgumentException("X-Change-Reason is required when changing an existing Plan Execution Policy");
        if("ACTIVE".equals(status)){Integer count=jdbc.queryForObject("select count(*) from plan_execution_policies where tenant_id=:tenant and status='ACTIVE' and policy_id<>:id",new MapSqlParameterSource("tenant",tenant).addValue("id",id),Integer.class);if(count!=null&&count>0)throw new IllegalArgumentException("Only one ACTIVE Plan Execution Policy is allowed per Tenant");}
        int version=existing==null?1:existing.version()+1;OffsetDateTime now=OffsetDateTime.now();OffsetDateTime created=existing==null?now:existing.createdAt();
        jdbc.update("""
            insert into plan_execution_policies(tenant_id,policy_id,display_name,max_attempts_per_step,default_step_timeout_seconds,max_active_steps,require_artifact_on_success,status,version,created_at,updated_at)
            values(:tenant,:id,:name,:attempts,:timeout,:active,:artifact,:status,:version,:created,:updated)
            on conflict(tenant_id,policy_id) do update set display_name=excluded.display_name,max_attempts_per_step=excluded.max_attempts_per_step,default_step_timeout_seconds=excluded.default_step_timeout_seconds,max_active_steps=excluded.max_active_steps,require_artifact_on_success=excluded.require_artifact_on_success,status=excluded.status,version=excluded.version,updated_at=excluded.updated_at
            """,new MapSqlParameterSource("tenant",tenant).addValue("id",id).addValue("name",requireNonBlank(request.displayName(),"displayName")).addValue("attempts",attempts).addValue("timeout",timeout).addValue("active",active).addValue("artifact",request.requireArtifactOnSuccess()).addValue("status",status).addValue("version",version).addValue("created",created).addValue("updated",now));
        PlanExecutionPolicy saved=findPolicy(tenant,id).orElseThrow();appendPolicyVersion(saved,existing==null?"INITIAL_CREATE":changeReason);return saved;
    }

    @Transactional(readOnly=true)
    public List<PlanExecutionPolicyVersion> policyVersions(String tenantId,String policyId){
        String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);return jdbc.query("select * from plan_execution_policy_versions where tenant_id=:tenant and policy_id=:id order by version desc",new MapSqlParameterSource("tenant",tenant).addValue("id",requireNonBlank(policyId,"policyId")),(rs,n)->new PlanExecutionPolicyVersion(tenant,rs.getString("policy_id"),rs.getInt("version"),readMap(rs.getString("snapshot_json")),rs.getString("change_reason"),rs.getString("actor_ref"),rs.getObject("created_at",OffsetDateTime.class)));
    }

    @Transactional
    public PlanExecutionRun startRun(String tenantId,PlanExecutionStartRequest request){
        String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);if(request==null)throw new IllegalArgumentException("Plan execution start request is required");
        String planId=requireNonBlank(request.planId(),"planId"),decisionId=requireNonBlank(request.planDecisionId(),"planDecisionId"),mode=normalizeMode(request.executionMode()),key=requireNonBlank(request.idempotencyKey(),"idempotencyKey");String completionPolicy=normalizeCompletionPolicy(request.completionPolicy());Integer quorumRequired=request.quorumRequired();
        PlanHeader plan=requirePlan(tenant,planId);if(!"SEMANTICALLY_VALIDATED".equals(plan.status()))throw new IllegalArgumentException("Only a SEMANTICALLY_VALIDATED Plan can start execution");
        int revision=request.planRevision()==null?plan.currentRevision():request.planRevision();if(revision!=plan.currentRevision())throw new IllegalArgumentException("A new run must freeze the current validated Plan revision");
        validatePlanDecision(tenant,decisionId,planId,revision);
        if("RUNTIME".equals(mode)) planAdmission.requireCurrentAdmission(tenant,planId,revision);
        PlanExecutionPolicy policy=activePolicy(tenant).orElseThrow(()->new IllegalArgumentException("PLAN_EXECUTION_POLICY_NOT_CONFIGURED"));
        Optional<PlanExecutionRun> prior=findRunByIdempotency(tenant,planId,revision,key);if(prior.isPresent())return prior.get();
        String runId="plan-run-"+UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();
        jdbc.update("insert into plan_execution_runs(tenant_id,run_id,plan_id,plan_revision,plan_decision_id,execution_mode,status,policy_id,policy_version,idempotency_key,fencing_token,completion_policy,quorum_required,started_at,updated_at) values(:tenant,:run,:plan,:revision,:decision,:mode,'RUNNING',:policy,:policyVersion,:key,1,:completionPolicy,:quorumRequired,:at,:at)",new MapSqlParameterSource("tenant",tenant).addValue("run",runId).addValue("plan",planId).addValue("revision",revision).addValue("decision",decisionId).addValue("mode",mode).addValue("policy",policy.policyId()).addValue("policyVersion",policy.version()).addValue("key",key).addValue("completionPolicy",completionPolicy).addValue("quorumRequired",quorumRequired).addValue("at",now));
        List<PlanStepSnapshot> snapshots=loadPlanSteps(tenant,planId,revision);if(snapshots.isEmpty())throw new IllegalArgumentException("Validated Plan revision contains no Steps");
        for(PlanStepSnapshot s:snapshots){String state=s.dependsOn().isEmpty()?"READY":"BLOCKED";String envelopeId="RUNTIME".equals(mode)?planAdmission.requireActiveEnvelope(tenant,planId,revision,s.stepId()).envelopeId():null;jdbc.update("insert into plan_execution_steps(tenant_id,run_id,step_id,capability_requirement_json,depends_on_json,required,state,attempt_count,side_effect,write_semantics,compensation_binding_id,max_binding_fallback,binding_authorization_envelope_id,updated_at) values(:tenant,:run,:step,cast(:req as jsonb),cast(:deps as jsonb),:required,:state,0,:side,:write,:comp,:fallback,:envelope,:at)",new MapSqlParameterSource("tenant",tenant).addValue("run",runId).addValue("step",s.stepId()).addValue("req",write(s.requirement())).addValue("deps",write(s.dependsOn())).addValue("required",s.required()).addValue("state",state).addValue("side",s.sideEffect()).addValue("write",s.writeSemantics()).addValue("comp",s.compensationBindingId()).addValue("fallback",s.maxBindingFallback()).addValue("envelope",envelopeId).addValue("at",now));appendEvent(tenant,runId,s.stepId(),"STEP_INITIALIZED",null,state,"FROZEN_PLAN_REVISION",Map.of("planRevision",revision,"bindingAuthorizationEnvelopeId",envelopeId==null?"SIMULATION":envelopeId));}
        appendEvent(tenant,runId,null,"RUN_STARTED",null,"RUNNING","FROZEN_PLAN_REVISION",Map.of("planId",planId,"planRevision",revision,"executionMode",mode,"completionPolicy",completionPolicy,"quorumRequired",quorumRequired==null?0:quorumRequired));
        if("RUNTIME".equals(mode)) automateReadyStepsInternal(tenant,runId);
        return requireRun(tenant,runId);
    }

    @Transactional(readOnly=true)
    public List<PlanExecutionRun> listRuns(String tenantId,String status,String afterRunId,int limit){String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);MapSqlParameterSource p=new MapSqlParameterSource("tenant",tenant).addValue("limit",limit(limit));String w=" where tenant_id=:tenant";if(!blank(status)){w+=" and status=:status";p.addValue("status",status.trim().toUpperCase(Locale.ROOT));}if(!blank(afterRunId)){w+=" and run_id>:after";p.addValue("after",afterRunId.trim());}return jdbc.query("select * from plan_execution_runs"+w+" order by run_id limit :limit",p,new RunMapper());}
    @Transactional(readOnly=true) public Optional<PlanExecutionRun> findRun(String tenantId,String runId){String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);try{return Optional.ofNullable(jdbc.queryForObject("select * from plan_execution_runs where tenant_id=:tenant and run_id=:run",new MapSqlParameterSource("tenant",tenant).addValue("run",requireNonBlank(runId,"runId")),new RunMapper()));}catch(EmptyResultDataAccessException ex){return Optional.empty();}}
    @Transactional(readOnly=true) public List<GovernedPlanExecutionStep> steps(String tenantId,String runId){String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);requireRun(tenant,runId);return jdbc.query("select * from plan_execution_steps where tenant_id=:tenant and run_id=:run order by step_id",new MapSqlParameterSource("tenant",tenant).addValue("run",runId),new StepMapper());}

    @Transactional
    public GovernedPlanExecutionStep attachAuthority(String tenantId,String runId,String stepId,PlanStepAuthorityRequest request){
        String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);PlanExecutionRun run=requireActiveRun(tenant,runId);GovernedPlanExecutionStep step=requireStep(tenant,runId,stepId);if(!"READY".equals(step.state()))throw new IllegalArgumentException("Step must be READY before WHO MAY/WHO SHOULD/HOW evidence can be attached");if(request==null)throw new IllegalArgumentException("Step authority request is required");
        AuthorityEvidence a=validateAuthorityChain(tenant,run,step,request);
        if("RUNTIME".equals(run.executionMode())) planAdmission.assertBindingAdmitted(tenant,step.bindingAuthorizationEnvelopeId(),a.bindingId(),step.requiredCapability().capabilityCode());
        jdbc.update("update plan_execution_steps set state='DISPATCH_READY',authorization_decision_id=:auth,routing_decision_id=:routing,adapter_resolution_id=:adapter,updated_at=:at where tenant_id=:tenant and run_id=:run and step_id=:step and state='READY'",new MapSqlParameterSource("tenant",tenant).addValue("run",runId).addValue("step",stepId).addValue("auth",a.authorizationDecisionId()).addValue("routing",a.routingDecisionId()).addValue("adapter",a.adapterResolutionId()).addValue("at",OffsetDateTime.now()));
        appendEvent(tenant,runId,stepId,"STEP_AUTHORITY_ATTACHED","READY","DISPATCH_READY","WHO_MAY_WHO_SHOULD_HOW_VALIDATED",Map.of("authorizationDecisionId",a.authorizationDecisionId(),"routingDecisionId",a.routingDecisionId(),"adapterResolutionId",a.adapterResolutionId(),"bindingId",a.bindingId(),"providerId",a.providerId()));return requireStep(tenant,runId,stepId);
    }


    /** Phase 12 machine/server-side READY-step authority orchestration. Caller supplies no Provider/Agent/Pool/transport. */
    @Transactional
    public RuntimeStepAuthorityAutomationResult automateAuthority(String tenantId,String runId,String stepId){
        String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);PlanExecutionRun run=requireActiveRun(tenant,runId);if(!"RUNTIME".equals(run.executionMode()))throw new IllegalArgumentException("Automatic authority orchestration is valid only for RUNTIME runs");GovernedPlanExecutionStep step=requireStep(tenant,runId,stepId);if(!"READY".equals(step.state()))throw new IllegalArgumentException("Step must be READY before automatic authority orchestration");RuntimeStepAuthorityAutomationPort port=authorityAutomation.getIfAvailable();if(port==null)throw new IllegalArgumentException("RUNTIME_STEP_AUTHORITY_AUTOMATION_NOT_AVAILABLE");RuntimeStepAuthorityAutomationResult result=port.prepare(tenant,runId,stepId);appendEvent(tenant,runId,stepId,"STEP_AUTHORITY_AUTOMATION",step.state(),step.state(),result.result(),Map.of("runtimeAuthorityDecisionId",result.decision().decisionId()));if("AUTHORIZED".equals(result.result())&&result.authorityRequest()!=null){attachAuthority(tenant,runId,stepId,result.authorityRequest());}return result;
    }

    private void automateReadyStepsInternal(String tenant,String runId){
        RuntimeStepAuthorityAutomationPort port=authorityAutomation.getIfAvailable();if(port==null){appendEvent(tenant,runId,null,"RUNTIME_AUTHORITY_AUTOMATION_UNAVAILABLE","RUNNING","RUNNING","RUNTIME_STEP_AUTHORITY_AUTOMATION_NOT_AVAILABLE",Map.of());return;}
        List<GovernedPlanExecutionStep> ready=jdbc.query("select * from plan_execution_steps where tenant_id=:tenant and run_id=:run and state='READY' order by step_id",new MapSqlParameterSource("tenant",tenant).addValue("run",runId),new StepMapper());
        for(GovernedPlanExecutionStep step:ready){try{RuntimeStepAuthorityAutomationResult result=port.prepare(tenant,runId,step.stepId());appendEvent(tenant,runId,step.stepId(),"STEP_AUTHORITY_AUTOMATION","READY","READY",result.result(),Map.of("runtimeAuthorityDecisionId",result.decision().decisionId()));if("AUTHORIZED".equals(result.result())&&result.authorityRequest()!=null)attachAuthority(tenant,runId,step.stepId(),result.authorityRequest());}catch(IllegalArgumentException ex){appendEvent(tenant,runId,step.stepId(),"STEP_AUTHORITY_AUTOMATION_FAILED","READY","READY",first(ex.getMessage(),"RUNTIME_AUTHORITY_AUTOMATION_FAILED"),Map.of());}}
    }


    @Transactional
    public PlanExecutionAttempt submitStep(String tenantId,String runId,String stepId,PlanStepSubmitRequest request){
        String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);PlanExecutionRun run=requireActiveRun(tenant,runId);GovernedPlanExecutionStep step=requireStep(tenant,runId,stepId);if(!"DISPATCH_READY".equals(step.state()))throw new IllegalArgumentException("Step must be DISPATCH_READY before submission");if(request==null)throw new IllegalArgumentException("Step submit request is required");String key=requireNonBlank(request.idempotencyKey(),"idempotencyKey");
        Optional<PlanExecutionAttempt> prior=findAttemptByIdempotency(tenant,runId,stepId,key);if(prior.isPresent())return prior.get();PlanExecutionPolicy policy=requirePolicyVersionCurrent(tenant,run);
        if(step.attemptCount()>=policy.maxAttemptsPerStep())throw new IllegalArgumentException("MAX_ATTEMPTS_PER_STEP_EXCEEDED");Integer active=jdbc.queryForObject("select count(*) from plan_execution_steps where tenant_id=:tenant and run_id=:run and state in ('RUNNING','CANCEL_REQUESTED')",new MapSqlParameterSource("tenant",tenant).addValue("run",runId),Integer.class);if(active!=null&&active>=policy.maxActiveSteps())throw new IllegalArgumentException("RUN_CONCURRENCY_LIMIT_REACHED");
        AuthorityEvidence authority=validateAuthorityChain(tenant,run,step,new PlanStepAuthorityRequest(step.authorizationDecisionId(),step.routingDecisionId(),step.adapterResolutionId()));
        if("RUNTIME".equals(run.executionMode())) planAdmission.assertBindingAdmitted(tenant,step.bindingAuthorizationEnvelopeId(),authority.bindingId(),step.requiredCapability().capabilityCode());ExecutionAdapterRegistration adapter=requireAdapterRegistration(tenant,authority);
        if(("MCP_TOOL".equals(authority.providerType())||"REMOTE_A2A_AGENT".equals(authority.providerType()))&&!"READ".equalsIgnoreCase(step.requiredCapability().operation()))throw new IllegalArgumentException("STAGE9_REMOTE_WRITE_FORBIDDEN");
        int attemptNo=step.attemptCount()+1;String attemptId="plan-attempt-"+UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();OffsetDateTime deadline=request.deadlineAt()==null?now.plusSeconds(policy.defaultStepTimeoutSeconds()):request.deadlineAt();if(!deadline.isAfter(now))throw new IllegalArgumentException("deadlineAt must be in the future");List<String> artifacts=dependencyArtifacts(tenant,runId,step.dependsOn());
        PlanChildTaskReference child;
        if("SIMULATION".equals(run.executionMode())){child=new PlanChildTaskReference("simulation-child:"+runId+":"+stepId+":"+attemptNo,false);}else{
            PlanChildTaskPort childPort=childTasks.getIfAvailable();if(childPort==null)throw new IllegalArgumentException("PLAN_CHILD_TASK_RUNTIME_NOT_AVAILABLE");
            child=childPort.createChildTask(new PlanChildTaskRequest(tenant,runId,stepId,attemptNo,step.requiredCapability(),artifacts,planTaskRef(tenant,run.planId())));
            if(child==null||!child.authoritative()||blank(child.taskId()))throw new IllegalArgumentException("AUTHORITATIVE_CHILD_TASK_REQUIRED");
        }
        jdbc.update("insert into plan_execution_attempts(tenant_id,attempt_id,run_id,step_id,attempt_no,idempotency_key,state,adapter_resolution_id,child_task_ref,external_execution_ref,reason_codes_json,submitted_at,deadline_at) values(:tenant,:attempt,:run,:step,:no,:key,'SUBMITTED',:adapter,:child,null,'[]'::jsonb,:at,:deadline)",new MapSqlParameterSource("tenant",tenant).addValue("attempt",attemptId).addValue("run",runId).addValue("step",stepId).addValue("no",attemptNo).addValue("key",key).addValue("adapter",authority.adapterResolutionId()).addValue("child",child.taskId()).addValue("at",now).addValue("deadline",deadline));
        ExecutionAdapterResult result;
        if("SIMULATION".equals(run.executionMode())){result=new ExecutionAdapterResult(true,"SIMULATED",null,List.of("SIMULATION_NO_EXTERNAL_IO"),now);}else{
            ExecutionAdapterPort port=adapters.stream().filter(x->adapter.adapterType().equals(x.adapterType())).findFirst().orElseThrow(()->new IllegalArgumentException("EXECUTION_ADAPTER_RUNTIME_NOT_AVAILABLE:"+adapter.adapterType()));
            Map<String,Object> executionInput=new java.util.LinkedHashMap<>(step.requiredCapability().inputContext()==null?Map.of():step.requiredCapability().inputContext());
            executionInput.put("executionContextType","PLAN_STEP");executionInput.put("planRunId",runId);executionInput.put("planStepId",stepId);executionInput.put("planAttemptId",attemptId);
            executionInput.put("bindingId",authority.bindingId());executionInput.put("authorizationDecisionId",authority.authorizationDecisionId());executionInput.put("routingDecisionId",authority.routingDecisionId());executionInput.put("providerId",authority.providerId());
            result=port.submit(adapter,new ExecutionAdapterCommand(tenant,child.taskId(),authority.adapterResolutionId(),step.requiredCapability().capabilityCode(),step.requiredCapability().operation(),executionInput,artifacts,deadline));if(result==null)throw new IllegalArgumentException("Execution Adapter returned no result");
            if(result.accepted()){
                String assignmentId=jdbc.queryForObject("select assignment_id from task_assignments where tenant_id=:tenant and task_id=:task and status='ASSIGNED' order by assigned_at desc,assignment_id desc limit 1",new MapSqlParameterSource("tenant",tenant).addValue("task",child.taskId()),String.class);
                authorizationEnvelopes.issuePlanStep(tenant,runId,stepId,attemptId,assignmentId,authority.bindingId(),authority.authorizationDecisionId(),authority.routingDecisionId(),step.bindingAuthorizationEnvelopeId());
            }
        }
        String attemptState=result.accepted()?("SIMULATION".equals(run.executionMode())?"SIMULATED":"RUNNING"):"FAILED";String stepState=result.accepted()?"RUNNING":((attemptNo<policy.maxAttemptsPerStep())?"RETRY_WAIT":"FAILED");
        jdbc.update("update plan_execution_attempts set state=:state,external_execution_ref=:external,reason_codes_json=cast(:reasons as jsonb),completed_at=:completed where tenant_id=:tenant and attempt_id=:attempt",new MapSqlParameterSource("tenant",tenant).addValue("attempt",attemptId).addValue("state",attemptState).addValue("external",result.externalExecutionRef()).addValue("reasons",write(result.reasonCodes())).addValue("completed",result.accepted()?null:now));
        jdbc.update("update plan_execution_steps set state=:state,attempt_count=:count,child_task_ref=:child,deadline_at=:deadline,runtime_claimed_by=null,runtime_claim_until=null,updated_at=:at where tenant_id=:tenant and run_id=:run and step_id=:step",new MapSqlParameterSource("tenant",tenant).addValue("run",runId).addValue("step",stepId).addValue("state",stepState).addValue("count",attemptNo).addValue("child",child.taskId()).addValue("deadline",deadline).addValue("at",now));
        appendEvent(tenant,runId,stepId,"STEP_SUBMITTED","DISPATCH_READY",stepState,result.accepted()?"ADAPTER_ACCEPTED":"ADAPTER_REJECTED",Map.of("attemptId",attemptId,"attemptNo",attemptNo,"authoritativeChildTask",child.authoritative(),"adapterType",adapter.adapterType(),"providerType",authority.providerType()));
        if(!result.accepted())finalizeRunIfTerminal(tenant,runId);return requireAttempt(tenant,attemptId);
    }

    @Transactional
    public GovernedPlanExecutionStep completeStep(String tenantId,String runId,String stepId,PlanStepCompletionRequest request){
        String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);PlanExecutionRun run=requireRun(tenant,runId);if(!"SIMULATION".equals(run.executionMode()))throw new IllegalArgumentException("RUNTIME_COMPLETION_REQUIRES_MACHINE_EVIDENCE_PORT");return completeInternal(tenant,run,stepId,request,null);
    }

    /** Runtime callback entrypoint for trusted adapter/task integration. It is intentionally not exposed by the Human Admin controller. */
    @Transactional
    public GovernedPlanExecutionStep recordRuntimeCompletion(String tenantId,String runId,String stepId,PlanRuntimeStepCompletion runtime){
        String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);PlanExecutionRun run=requireRun(tenant,runId);if(!"RUNTIME".equals(run.executionMode()))throw new IllegalArgumentException("Runtime completion is valid only for RUNTIME runs");if(runtime==null)throw new IllegalArgumentException("Runtime completion evidence is required");PlanExecutionAttempt a=latestAttempt(tenant,runId,stepId);if(blank(a.externalExecutionRef())||!a.externalExecutionRef().equals(runtime.externalExecutionRef()))throw new IllegalArgumentException("RUNTIME_EXTERNAL_EXECUTION_REF_MISMATCH");PlanStepCompletionRequest normalized=new PlanStepCompletionRequest(runtime.result(),runtime.finding(),runtime.confidence(),runtime.evidenceRefs(),runtime.output(),runtime.dataClassification(),runtime.failureReason());return completeInternal(tenant,run,stepId,normalized,runtime.externalExecutionRef());
    }

    private GovernedPlanExecutionStep completeInternal(String tenant,PlanExecutionRun run,String stepId,PlanStepCompletionRequest request,String runtimeEvidenceRef){
        String runId=run.runId();GovernedPlanExecutionStep step=requireStep(tenant,runId,stepId);if(!Set.of("RUNNING","CANCEL_REQUESTED").contains(step.state()))throw new IllegalArgumentException("Only RUNNING/CANCEL_REQUESTED Steps can complete");if(request==null)throw new IllegalArgumentException("Step completion request is required");String result=normalizeCompletionResult(request.result());PlanExecutionAttempt attempt=latestAttempt(tenant,runId,stepId);PlanExecutionPolicy policy=requirePolicyVersionCurrent(tenant,run);
        OffsetDateTime now=OffsetDateTime.now();String target=result;List<String> reasons=new ArrayList<>();if("SUCCEEDED".equals(result)){boolean artifactContent=!blank(request.finding())||!request.evidenceRefs().isEmpty()||!request.output().isEmpty();if(policy.requireArtifactOnSuccess()&&!artifactContent)throw new IllegalArgumentException("SUCCESS_ARTIFACT_REQUIRED");String artifactId="plan-artifact-"+UUID.randomUUID();jdbc.update("insert into plan_execution_artifacts(tenant_id,artifact_id,run_id,step_id,attempt_id,capability_code,finding,confidence,evidence_refs_json,output_json,data_classification,created_at) values(:tenant,:artifact,:run,:step,:attempt,:capability,:finding,:confidence,cast(:refs as jsonb),cast(:output as jsonb),:class,:at)",new MapSqlParameterSource("tenant",tenant).addValue("artifact",artifactId).addValue("run",runId).addValue("step",stepId).addValue("attempt",attempt.attemptId()).addValue("capability",step.requiredCapability().capabilityCode()).addValue("finding",trim(request.finding())).addValue("confidence",request.confidence()).addValue("refs",write(request.evidenceRefs())).addValue("output",write(request.output())).addValue("class",trim(request.dataClassification())).addValue("at",now));reasons.add("NORMALIZED_ARTIFACT_CREATED");} else if(!blank(request.failureReason()))reasons.add(request.failureReason().trim());
        jdbc.update("update plan_execution_attempts set state=:state,reason_codes_json=cast(:reasons as jsonb),completed_at=:at where tenant_id=:tenant and attempt_id=:attempt",new MapSqlParameterSource("tenant",tenant).addValue("attempt",attempt.attemptId()).addValue("state",target).addValue("reasons",write(reasons)).addValue("at",now));jdbc.update("update plan_execution_steps set state=:state,deadline_at=null,updated_at=:at where tenant_id=:tenant and run_id=:run and step_id=:step",new MapSqlParameterSource("tenant",tenant).addValue("run",runId).addValue("step",stepId).addValue("state",target).addValue("at",now));Map<String,Object> completionEvidence=new java.util.LinkedHashMap<>();completionEvidence.put("attemptId",attempt.attemptId());if(runtimeEvidenceRef!=null)completionEvidence.put("externalExecutionRef",runtimeEvidenceRef);appendEvent(tenant,runId,stepId,"STEP_COMPLETED",step.state(),target,blank(request.failureReason())?"NORMALIZED_COMPLETION":request.failureReason(),completionEvidence);refreshDependencyStates(tenant,runId);if("RUNTIME".equals(run.executionMode()))automateReadyStepsInternal(tenant,runId);finalizeRunIfTerminal(tenant,runId);return requireStep(tenant,runId,stepId);
    }

    @Transactional
    public GovernedPlanExecutionStep retryStep(String tenantId,String runId,String stepId,PlanStepRetryRequest request){
        String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);PlanExecutionRun run=requireActiveRun(tenant,runId);GovernedPlanExecutionStep step=requireStep(tenant,runId,stepId);if(!Set.of("FAILED","TIMED_OUT","RETRY_WAIT").contains(step.state()))throw new IllegalArgumentException("Only FAILED/TIMED_OUT/RETRY_WAIT Steps can retry");PlanExecutionPolicy policy=requirePolicyVersionCurrent(tenant,run);if(step.attemptCount()>=policy.maxAttemptsPerStep())throw new IllegalArgumentException("MAX_ATTEMPTS_PER_STEP_EXCEEDED");String reason=request==null?"OPERATOR_RETRY":first(request.reason(),"OPERATOR_RETRY");
        jdbc.update("update plan_execution_steps set state='READY',authorization_decision_id=null,routing_decision_id=null,adapter_resolution_id=null,child_task_ref=null,deadline_at=null,updated_at=:at where tenant_id=:tenant and run_id=:run and step_id=:step",new MapSqlParameterSource("tenant",tenant).addValue("run",runId).addValue("step",stepId).addValue("at",OffsetDateTime.now()));appendEvent(tenant,runId,stepId,"STEP_RETRY_READY",step.state(),"READY",reason,Map.of("AUTHORITY_CHAIN_CLEARED_FOR_RETRY",true,"attemptCount",step.attemptCount()));if("RUNTIME".equals(run.executionMode()))automateReadyStepsInternal(tenant,runId);return requireStep(tenant,runId,stepId);
    }

    @Transactional
    public PlanExecutionRun cancelRun(String tenantId,String runId,PlanExecutionCancelRequest request){
        String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);PlanExecutionRun run=requireRun(tenant,runId);if(isTerminalRun(run.status()))return run;String reason=request==null?"OPERATOR_CANCEL":first(request.reason(),"OPERATOR_CANCEL");OffsetDateTime now=OffsetDateTime.now();jdbc.update("update plan_execution_runs set status='CANCELLING',updated_at=:at where tenant_id=:tenant and run_id=:run",new MapSqlParameterSource("tenant",tenant).addValue("run",runId).addValue("at",now));
        for(GovernedPlanExecutionStep step:steps(tenant,runId)){if(TERMINAL_STEPS.contains(step.state()))continue;if("RUNNING".equals(step.state())){PlanExecutionAttempt a=latestAttempt(tenant,runId,step.stepId());boolean cancelled=false;if(!blank(a.externalExecutionRef())){String adapterType=adapterTypeForResolution(tenant,a.adapterResolutionId());for(PlanExecutionCancellationPort p:cancellationPorts)if(p.supports(adapterType)){cancelled=p.cancel(tenant,a.externalExecutionRef(),reason);break;}}String state=cancelled?"CANCELLED":"CANCEL_REQUESTED";jdbc.update("update plan_execution_steps set state=:state,updated_at=:at where tenant_id=:tenant and run_id=:run and step_id=:step",new MapSqlParameterSource("tenant",tenant).addValue("run",runId).addValue("step",step.stepId()).addValue("state",state).addValue("at",now));jdbc.update("update plan_execution_attempts set state=:state,completed_at=:completed where tenant_id=:tenant and attempt_id=:attempt",new MapSqlParameterSource("tenant",tenant).addValue("attempt",a.attemptId()).addValue("state",state).addValue("completed",cancelled?now:null));appendEvent(tenant,runId,step.stepId(),"STEP_CANCEL_REQUESTED","RUNNING",state,reason,Map.of("externalCancellationAccepted",cancelled));}else{jdbc.update("update plan_execution_steps set state='CANCELLED',updated_at=:at where tenant_id=:tenant and run_id=:run and step_id=:step",new MapSqlParameterSource("tenant",tenant).addValue("run",runId).addValue("step",step.stepId()).addValue("at",now));appendEvent(tenant,runId,step.stepId(),"STEP_CANCELLED",step.state(),"CANCELLED",reason,Map.of());}}
        appendEvent(tenant,runId,null,"RUN_CANCELLATION_REQUESTED",run.status(),"CANCELLING",reason,Map.of());finalizeRunIfTerminal(tenant,runId);return requireRun(tenant,runId);
    }

    @Transactional
    public int sweepTimeouts(String tenantId){String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);OffsetDateTime now=OffsetDateTime.now();List<Map<String,Object>> rows=jdbc.queryForList("select run_id,step_id from plan_execution_steps where tenant_id=:tenant and state='RUNNING' and deadline_at is not null and deadline_at<:now",new MapSqlParameterSource("tenant",tenant).addValue("now",now));for(Map<String,Object> row:rows){String run=String.valueOf(row.get("run_id")),step=String.valueOf(row.get("step_id"));PlanExecutionAttempt a=latestAttempt(tenant,run,step);jdbc.update("update plan_execution_attempts set state='TIMED_OUT',completed_at=:at where tenant_id=:tenant and attempt_id=:attempt",new MapSqlParameterSource("tenant",tenant).addValue("attempt",a.attemptId()).addValue("at",now));jdbc.update("update plan_execution_steps set state='TIMED_OUT',deadline_at=null,updated_at=:at where tenant_id=:tenant and run_id=:run and step_id=:step",new MapSqlParameterSource("tenant",tenant).addValue("run",run).addValue("step",step).addValue("at",now));appendEvent(tenant,run,step,"STEP_TIMED_OUT","RUNNING","TIMED_OUT","STEP_DEADLINE_EXCEEDED",Map.of("attemptId",a.attemptId()));refreshDependencyStates(tenant,run);finalizeRunIfTerminal(tenant,run);}return rows.size();}

    @Transactional(readOnly=true) public List<PlanExecutionAttempt> attempts(String tenantId,String runId,String stepId,int limit){String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);MapSqlParameterSource p=new MapSqlParameterSource("tenant",tenant).addValue("run",requireNonBlank(runId,"runId")).addValue("limit",limit(limit));String w=" and run_id=:run";if(!blank(stepId)){w+=" and step_id=:step";p.addValue("step",stepId.trim());}return jdbc.query("select * from plan_execution_attempts where tenant_id=:tenant"+w+" order by submitted_at desc limit :limit",p,new AttemptMapper());}
    @Transactional(readOnly=true) public List<PlanExecutionArtifact> artifacts(String tenantId,String runId,String stepId,int limit){String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);MapSqlParameterSource p=new MapSqlParameterSource("tenant",tenant).addValue("run",requireNonBlank(runId,"runId")).addValue("limit",limit(limit));String w=" and run_id=:run";if(!blank(stepId)){w+=" and step_id=:step";p.addValue("step",stepId.trim());}return jdbc.query("select * from plan_execution_artifacts where tenant_id=:tenant"+w+" order by created_at desc limit :limit",p,new ArtifactMapper());}
    @Transactional(readOnly=true) public List<PlanExecutionEvent> events(String tenantId,String runId,int limit){String tenant=requireTenant(tenantId);bindDatabaseTenantContext(tenant);return jdbc.query("select * from plan_execution_events where tenant_id=:tenant and run_id=:run order by occurred_at desc,event_id desc limit :limit",new MapSqlParameterSource("tenant",tenant).addValue("run",requireNonBlank(runId,"runId")).addValue("limit",limit(limit)),new EventMapper());}

    private AuthorityEvidence validateAuthorityChain(String tenant,PlanExecutionRun run,GovernedPlanExecutionStep step,PlanStepAuthorityRequest request){
        String auth=requireNonBlank(request.authorizationDecisionId(),"authorizationDecisionId"),routing=requireNonBlank(request.routingDecisionId(),"routingDecisionId"),resolution=requireNonBlank(request.adapterResolutionId(),"adapterResolutionId");String requiredMode="RUNTIME".equals(run.executionMode())?"RUNTIME":null;String cap=step.requiredCapability().capabilityCode(),op=step.requiredCapability().operation();
        Map<String,Object> a=one("select * from delegation_authorization_decisions where tenant_id=:tenant and decision_id=:id",tenant,auth);if(!"PASS".equals(str(a,"result")))throw new IllegalArgumentException("WHO_MAY_DECISION_NOT_PASS");if(requiredMode!=null&&!requiredMode.equals(str(a,"decision_mode")))throw new IllegalArgumentException("RUNTIME_RUN_REQUIRES_RUNTIME_WHO_MAY_EVIDENCE");ensureRequirement(cap,op,a,"WHO_MAY");String binding=str(a,"binding_id"),provider=str(a,"provider_id");
        Map<String,Object> r=one("select * from provider_routing_decisions where tenant_id=:tenant and decision_id=:id",tenant,routing);if(!"SELECTED".equals(str(r,"result")))throw new IllegalArgumentException("WHO_SHOULD_DECISION_NOT_SELECTED");if(requiredMode!=null&&!requiredMode.equals(str(r,"decision_mode")))throw new IllegalArgumentException("RUNTIME_RUN_REQUIRES_RUNTIME_WHO_SHOULD_EVIDENCE");ensureRequirement(cap,op,r,"WHO_SHOULD");if(!binding.equals(str(r,"selected_binding_id"))||!provider.equals(str(r,"selected_provider_id")))throw new IllegalArgumentException("WHO_MAY_WHO_SHOULD_PROVIDER_MISMATCH");String eligibilityId=candidateEligibility(str(r,"candidates_json"),auth,binding,provider);if(blank(eligibilityId))throw new IllegalArgumentException("WHO_SHOULD_DECISION_DOES_NOT_REFERENCE_WHO_MAY_EVIDENCE");validateCurrentProviderTrust(tenant,cap,op,binding,provider);validateCurrentWhoMayPolicy(tenant,a);validateCurrentRoutingProfileAndEligibility(tenant,r,binding,provider,eligibilityId);
        Map<String,Object> e=one("select * from execution_adapter_resolutions where tenant_id=:tenant and resolution_id=:id",tenant,resolution);if(!"SELECTED".equals(str(e,"result")))throw new IllegalArgumentException("HOW_RESOLUTION_NOT_SELECTED");if(requiredMode!=null&&!requiredMode.equals(str(e,"resolution_mode")))throw new IllegalArgumentException("RUNTIME_RUN_REQUIRES_RUNTIME_HOW_EVIDENCE");ensureRequirement(cap,op,e,"HOW");if(!routing.equals(str(e,"routing_decision_id"))||!binding.equals(str(e,"binding_id"))||!provider.equals(str(e,"provider_id")))throw new IllegalArgumentException("WHO_SHOULD_HOW_EVIDENCE_MISMATCH");String latestResolution=jdbc.queryForObject("select resolution_id from execution_adapter_resolutions where tenant_id=:tenant and routing_decision_id=:routing order by resolved_at desc,resolution_id desc limit 1",new MapSqlParameterSource("tenant",tenant).addValue("routing",routing),String.class);if(!resolution.equals(latestResolution))throw new IllegalArgumentException("HOW_RESOLUTION_STALE");return new AuthorityEvidence(auth,routing,resolution,binding,provider,str(e,"provider_type"),str(e,"adapter_id"),(Integer)e.get("adapter_version"),str(e,"adapter_type"));
    }

    private ExecutionAdapterRegistration requireAdapterRegistration(String tenant,AuthorityEvidence a){Map<String,Object> m=one("select * from execution_adapter_registrations where tenant_id=:tenant and adapter_id=:id",tenant,a.adapterId());if(!"ACTIVE".equals(str(m,"status")))throw new IllegalArgumentException("EXECUTION_ADAPTER_NOT_ACTIVE");if(!a.providerId().equals(str(m,"provider_id"))||!a.adapterType().equals(str(m,"adapter_type")))throw new IllegalArgumentException("EXECUTION_ADAPTER_REGISTRATION_MISMATCH");Integer v=(Integer)m.get("version");if(a.adapterVersion()!=null&&!a.adapterVersion().equals(v))throw new IllegalArgumentException("EXECUTION_ADAPTER_VERSION_STALE");return new ExecutionAdapterRegistration(tenant,str(m,"adapter_id"),str(m,"provider_id"),str(m,"provider_type"),str(m,"adapter_type"),str(m,"protocol"),str(m,"protocol_version"),str(m,"endpoint_ref"),str(m,"credential_ref"),str(m,"runtime_ref"),str(m,"status"),(Integer)m.get("selection_priority"),readMap(str(m,"configuration_json")),v,(OffsetDateTime)m.get("created_at"),(OffsetDateTime)m.get("updated_at"));}

    private void refreshDependencyStates(String tenant,String runId){List<GovernedPlanExecutionStep> all=steps(tenant,runId);Map<String,GovernedPlanExecutionStep> byId=new java.util.LinkedHashMap<>();for(var s:all)byId.put(s.stepId(),s);for(var s:all){if(!"BLOCKED".equals(s.state()))continue;boolean allSuccess=true,terminalFailure=false;for(String dep:s.dependsOn()){var d=byId.get(dep);if(d==null){terminalFailure=true;allSuccess=false;break;}if(!"SUCCEEDED".equals(d.state()))allSuccess=false;if(TERMINAL_STEPS.contains(d.state())&&!"SUCCEEDED".equals(d.state()))terminalFailure=true;}if(allSuccess)transitionStep(tenant,runId,s.stepId(),"BLOCKED","READY","DEPENDENCIES_SUCCEEDED");else if(terminalFailure)transitionStep(tenant,runId,s.stepId(),"BLOCKED","SKIPPED","DEPENDENCY_NOT_SUCCESSFUL");}}
    private void finalizeRunIfTerminal(String tenant,String runId){
        PlanExecutionRun run=requireRun(tenant,runId);List<GovernedPlanExecutionStep> ss=steps(tenant,runId);if(ss.stream().anyMatch(s->!TERMINAL_STEPS.contains(s.state())))return;
        if("CANCELLING".equals(run.status())){OffsetDateTime now=OffsetDateTime.now();jdbc.update("update plan_execution_runs set status='CANCELLED',convergence_outcome='CANCELLED',convergence_reason='OPERATOR_CANCEL',updated_at=:at,completed_at=:at where tenant_id=:tenant and run_id=:run",new MapSqlParameterSource("tenant",tenant).addValue("run",runId).addValue("at",now));appendEvent(tenant,runId,null,"RUN_COMPLETED",run.status(),"CANCELLED","OPERATOR_CANCEL",Map.of());return;}
        List<Map<String,Object>> outputs=jdbc.query("select output_json::text from plan_execution_artifacts where tenant_id=:tenant and run_id=:run order by created_at,artifact_id",new MapSqlParameterSource("tenant",tenant).addValue("run",runId),(rs,n)->readMap(rs.getString(1)));
        List<PlanExecutionConvergenceEvaluator.StepState> states=ss.stream().map(x->new PlanExecutionConvergenceEvaluator.StepState(x.required(),x.state())).toList();
        PlanExecutionConvergenceEvaluator.Decision d=PlanExecutionConvergenceEvaluator.evaluate(run.completionPolicy(),run.quorumRequired(),states,outputs);
        String runStatus=switch(d.outcome()){case "SUCCEEDED"->"SUCCEEDED";case "PARTIAL","PROVISIONAL","EVIDENCE_CONFLICT"->"PARTIAL_SUCCEEDED";default->"FAILED";};
        OffsetDateTime now=OffsetDateTime.now();String convergenceId="plan-convergence-"+UUID.randomUUID();
        jdbc.update("insert into plan_execution_convergence_decisions(tenant_id,convergence_id,run_id,completion_policy,quorum_required,required_step_count,successful_required_count,failed_required_count,successful_step_count,non_success_step_count,artifact_count,conflict_count,outcome,reason_codes_json,evidence_json,decided_at) values(:tenant,:id,:run,:policy,:quorum,:required,:successRequired,:failedRequired,:success,:nonSuccess,:artifacts,:conflicts,:outcome,cast(:reasons as jsonb),cast(:evidence as jsonb),:at) on conflict(tenant_id,run_id) do nothing",new MapSqlParameterSource("tenant",tenant).addValue("id",convergenceId).addValue("run",runId).addValue("policy",d.completionPolicy()).addValue("quorum",d.quorumRequired()).addValue("required",d.requiredStepCount()).addValue("successRequired",d.successfulRequiredCount()).addValue("failedRequired",d.failedRequiredCount()).addValue("success",d.successfulStepCount()).addValue("nonSuccess",d.nonSuccessStepCount()).addValue("artifacts",d.artifactCount()).addValue("conflicts",d.conflictCount()).addValue("outcome",d.outcome()).addValue("reasons",write(d.reasonCodes())).addValue("evidence",write(Map.of("conflicts",d.conflicts()))).addValue("at",now));
        jdbc.update("update plan_execution_runs set status=:status,convergence_outcome=:outcome,convergence_reason=:reason,updated_at=:at,completed_at=:at where tenant_id=:tenant and run_id=:run",new MapSqlParameterSource("tenant",tenant).addValue("run",runId).addValue("status",runStatus).addValue("outcome",d.outcome()).addValue("reason",String.join(",",d.reasonCodes())).addValue("at",now));
        appendEvent(tenant,runId,null,"RUN_CONVERGED",run.status(),runStatus,d.outcome(),Map.of("completionPolicy",d.completionPolicy(),"convergenceOutcome",d.outcome(),"conflictCount",d.conflictCount()));
    }
    private void transitionStep(String tenant,String run,String step,String from,String to,String reason){jdbc.update("update plan_execution_steps set state=:to,updated_at=:at where tenant_id=:tenant and run_id=:run and step_id=:step and state=:from",new MapSqlParameterSource("tenant",tenant).addValue("run",run).addValue("step",step).addValue("from",from).addValue("to",to).addValue("at",OffsetDateTime.now()));appendEvent(tenant,run,step,"STEP_STATE_CHANGED",from,to,reason,Map.of());}

    private List<String> dependencyArtifacts(String tenant,String run,List<String> deps){if(deps==null||deps.isEmpty())return List.of();List<String> out=new ArrayList<>();for(String dep:deps)out.addAll(jdbc.queryForList("select artifact_id from plan_execution_artifacts where tenant_id=:tenant and run_id=:run and step_id=:step order by created_at",new MapSqlParameterSource("tenant",tenant).addValue("run",run).addValue("step",dep),String.class));return List.copyOf(out);}
    private String candidateEligibility(String raw,String auth,String binding,String provider){try{for(Map<String,Object> m:json.readValue(raw,MAP_LIST))if(auth.equals(String.valueOf(m.get("authorizationDecisionId")))&&binding.equals(String.valueOf(m.get("bindingId")))&&provider.equals(String.valueOf(m.get("providerId")))){Object v=m.get("eligibilityObservationId");return v==null?null:String.valueOf(v);}return null;}catch(Exception ex){throw new IllegalStateException("Routing candidate evidence cannot be read",ex);}}
    private void validateCurrentProviderTrust(String tenant,String cap,String op,String binding,String provider){Map<String,Object> p=one("select * from capability_providers where tenant_id=:tenant and provider_id=:id",tenant,provider);if(!"REGISTERED".equals(str(p,"catalog_status")))throw new IllegalArgumentException("PROVIDER_NOT_REGISTERED");Map<String,Object> b=one("select * from capability_bindings where tenant_id=:tenant and binding_id=:id",tenant,binding);if(!"APPROVED".equals(str(b,"trust_status"))||!cap.equals(str(b,"capability_code"))||!provider.equals(str(b,"provider_id")))throw new IllegalArgumentException("CAPABILITY_BINDING_NOT_APPROVED_OR_MISMATCHED");OffsetDateTime stale=(OffsetDateTime)b.get("stale_after");if(stale!=null&&!stale.isAfter(OffsetDateTime.now()))throw new IllegalArgumentException("CAPABILITY_BINDING_STALE");if(!readStrings(str(b,"supported_operations_json")).contains(op))throw new IllegalArgumentException("CAPABILITY_BINDING_OPERATION_NOT_SUPPORTED");}
    private void validateCurrentWhoMayPolicy(String tenant,Map<String,Object> decision){String policy=str(decision,"selected_policy_id");Object version=decision.get("selected_policy_version");if(blank(policy)||version==null)throw new IllegalArgumentException("WHO_MAY_POLICY_EVIDENCE_MISSING");Map<String,Object> p=one("select policy_id,status,version from delegation_policies where tenant_id=:tenant and policy_id=:id",tenant,policy);if(!"ACTIVE".equals(str(p,"status"))||((Number)p.get("version")).intValue()!=((Number)version).intValue())throw new IllegalArgumentException("WHO_MAY_POLICY_STALE");}
    private void validateCurrentRoutingProfileAndEligibility(String tenant,Map<String,Object> routing,String binding,String provider,String eligibilityId){String profile=str(routing,"routing_profile_id");Integer version=((Number)routing.get("routing_profile_version")).intValue();Map<String,Object> p=one("select profile_id,status,version from routing_profiles where tenant_id=:tenant and profile_id=:id",tenant,profile);if(!"ACTIVE".equals(str(p,"status"))||((Number)p.get("version")).intValue()!=version)throw new IllegalArgumentException("ROUTING_PROFILE_STALE");Map<String,Object> e=one("select * from provider_eligibility_observations where tenant_id=:tenant and observation_id=:id",tenant,eligibilityId);if(!binding.equals(str(e,"binding_id"))||!provider.equals(str(e,"provider_id"))||!Boolean.TRUE.equals(e.get("available"))||!Boolean.TRUE.equals(e.get("healthy"))||!Boolean.TRUE.equals(e.get("capacity_available")))throw new IllegalArgumentException("PROVIDER_ELIGIBILITY_NO_LONGER_VALID");OffsetDateTime expires=(OffsetDateTime)e.get("expires_at");if(expires!=null&&!expires.isAfter(OffsetDateTime.now()))throw new IllegalArgumentException("PROVIDER_ELIGIBILITY_EXPIRED");String latest=jdbc.queryForObject("select observation_id from provider_eligibility_observations where tenant_id=:tenant and binding_id=:binding order by observed_at desc,observation_id desc limit 1",new MapSqlParameterSource("tenant",tenant).addValue("binding",binding),String.class);if(!eligibilityId.equals(latest))throw new IllegalArgumentException("PROVIDER_ELIGIBILITY_OBSERVATION_STALE");}
    private void ensureRequirement(String cap,String op,Map<String,Object> m,String label){if(!cap.equals(str(m,"capability_code"))||!op.equals(str(m,"operation")))throw new IllegalArgumentException(label+"_CAPABILITY_OPERATION_MISMATCH");}
    private String adapterTypeForResolution(String tenant,String resolution){Map<String,Object> m=one("select adapter_type from execution_adapter_resolutions where tenant_id=:tenant and resolution_id=:id",tenant,resolution);return str(m,"adapter_type");}

    private PlanExecutionPolicy requirePolicyVersionCurrent(String tenant,PlanExecutionRun run){PlanExecutionPolicy p=findPolicy(tenant,run.policyId()).orElseThrow(()->new IllegalArgumentException("PLAN_EXECUTION_POLICY_NOT_FOUND"));if(p.version()!=run.policyVersion()||!"ACTIVE".equals(p.status()))throw new IllegalArgumentException("PLAN_EXECUTION_POLICY_STALE");return p;}
    private Optional<PlanExecutionPolicy> activePolicy(String tenant){try{return Optional.ofNullable(jdbc.queryForObject("select * from plan_execution_policies where tenant_id=:tenant and status='ACTIVE'",new MapSqlParameterSource("tenant",tenant),new PolicyMapper()));}catch(EmptyResultDataAccessException ex){return Optional.empty();}}
    private Optional<PlanExecutionPolicy> findPolicy(String tenant,String id){try{return Optional.ofNullable(jdbc.queryForObject("select * from plan_execution_policies where tenant_id=:tenant and policy_id=:id",new MapSqlParameterSource("tenant",tenant).addValue("id",id),new PolicyMapper()));}catch(EmptyResultDataAccessException ex){return Optional.empty();}}
    private void appendPolicyVersion(PlanExecutionPolicy p,String reason){jdbc.update("insert into plan_execution_policy_versions(tenant_id,policy_id,version,snapshot_json,change_reason,actor_ref,created_at) values(:tenant,:id,:version,cast(:snapshot as jsonb),:reason,:actor,:at)",new MapSqlParameterSource("tenant",p.tenantId()).addValue("id",p.policyId()).addValue("version",p.version()).addValue("snapshot",write(p)).addValue("reason",requireNonBlank(reason,"changeReason")).addValue("actor",actorRef()).addValue("at",OffsetDateTime.now()));}
    private Optional<PlanExecutionRun> findRunByIdempotency(String tenant,String plan,int revision,String key){try{return Optional.ofNullable(jdbc.queryForObject("select * from plan_execution_runs where tenant_id=:tenant and plan_id=:plan and plan_revision=:revision and idempotency_key=:key",new MapSqlParameterSource("tenant",tenant).addValue("plan",plan).addValue("revision",revision).addValue("key",key),new RunMapper()));}catch(EmptyResultDataAccessException ex){return Optional.empty();}}
    private PlanExecutionRun requireRun(String tenant,String run){return findRun(tenant,run).orElseThrow(()->new IllegalArgumentException("Plan execution run not found: "+run));}
    private PlanExecutionRun requireActiveRun(String tenant,String run){PlanExecutionRun r=requireRun(tenant,run);if(!"RUNNING".equals(r.status()))throw new IllegalArgumentException("Plan execution run is not RUNNING: "+r.status());return r;}
    private GovernedPlanExecutionStep requireStep(String tenant,String run,String step){try{return jdbc.queryForObject("select * from plan_execution_steps where tenant_id=:tenant and run_id=:run and step_id=:step",new MapSqlParameterSource("tenant",tenant).addValue("run",run).addValue("step",requireNonBlank(step,"stepId")),new StepMapper());}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("Plan execution Step not found: "+step);}}
    private Optional<PlanExecutionAttempt> findAttemptByIdempotency(String tenant,String run,String step,String key){try{return Optional.ofNullable(jdbc.queryForObject("select * from plan_execution_attempts where tenant_id=:tenant and run_id=:run and step_id=:step and idempotency_key=:key",new MapSqlParameterSource("tenant",tenant).addValue("run",run).addValue("step",step).addValue("key",key),new AttemptMapper()));}catch(EmptyResultDataAccessException ex){return Optional.empty();}}
    private PlanExecutionAttempt requireAttempt(String tenant,String attempt){try{return jdbc.queryForObject("select * from plan_execution_attempts where tenant_id=:tenant and attempt_id=:attempt",new MapSqlParameterSource("tenant",tenant).addValue("attempt",attempt),new AttemptMapper());}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("Plan execution attempt not found: "+attempt);}}
    private PlanExecutionAttempt latestAttempt(String tenant,String run,String step){try{return jdbc.queryForObject("select * from plan_execution_attempts where tenant_id=:tenant and run_id=:run and step_id=:step order by attempt_no desc limit 1",new MapSqlParameterSource("tenant",tenant).addValue("run",run).addValue("step",step),new AttemptMapper());}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("No execution attempt exists for Step: "+step);}}
    private PlanHeader requirePlan(String tenant,String plan){try{return jdbc.queryForObject("select plan_id,status,current_revision,task_ref from execution_plans where tenant_id=:tenant and plan_id=:plan",new MapSqlParameterSource("tenant",tenant).addValue("plan",plan),(rs,n)->new PlanHeader(rs.getString("plan_id"),rs.getString("status"),rs.getInt("current_revision"),rs.getString("task_ref")));}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("Execution Plan not found: "+plan);}}
    private String planTaskRef(String tenant,String plan){return requirePlan(tenant,plan).taskRef();}
    private void validatePlanDecision(String tenant,String decision,String plan,int revision){Map<String,Object> m=one("select result,plan_id,plan_revision from execution_plan_decisions where tenant_id=:tenant and decision_id=:id",tenant,decision);if(!"PLAN_VALIDATED".equals(str(m,"result"))||!plan.equals(str(m,"plan_id"))||revision!=((Number)m.get("plan_revision")).intValue())throw new IllegalArgumentException("PLAN_VALIDATION_EVIDENCE_MISMATCH");}
    private List<PlanStepSnapshot> loadPlanSteps(String tenant,String plan,int revision){return jdbc.query("select * from execution_plan_revision_steps where tenant_id=:tenant and plan_id=:plan and revision=:revision order by coalesce(sequence_hint,2147483647),step_id",new MapSqlParameterSource("tenant",tenant).addValue("plan",plan).addValue("revision",revision),(rs,n)->new PlanStepSnapshot(rs.getString("step_id"),readRequirement(rs.getString("capability_requirement_json")),readStrings(rs.getString("depends_on_json")),rs.getBoolean("required"),rs.getString("side_effect"),rs.getString("write_semantics"),rs.getString("compensation_binding_id"),rs.getInt("max_binding_fallback")));}

    private Map<String,Object> one(String sql,String tenant,String id){try{return jdbc.queryForMap(sql,new MapSqlParameterSource("tenant",tenant).addValue("id",id));}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("Required governance evidence not found: "+id);}}
    private void appendEvent(String tenant,String run,String step,String type,String from,String to,String reason,Map<String,Object> evidence){jdbc.update("insert into plan_execution_events(tenant_id,event_id,run_id,step_id,event_type,from_state,to_state,reason,actor_ref,evidence_json,occurred_at) values(:tenant,:event,:run,:step,:type,:from,:to,:reason,:actor,cast(:evidence as jsonb),:at)",new MapSqlParameterSource("tenant",tenant).addValue("event","plan-event-"+UUID.randomUUID()).addValue("run",run).addValue("step",step).addValue("type",type).addValue("from",from).addValue("to",to).addValue("reason",reason).addValue("actor",actorRef()).addValue("evidence",write(evidence)).addValue("at",OffsetDateTime.now()));}

    private String normalizePolicyStatus(String v){String x=blank(v)?"DRAFT":v.trim().toUpperCase(Locale.ROOT);if(!POLICY_STATUSES.contains(x))throw new IllegalArgumentException("Unsupported Plan Execution Policy status: "+x);return x;}
    private String normalizeMode(String v){String x=blank(v)?"SIMULATION":v.trim().toUpperCase(Locale.ROOT);if(!MODES.contains(x))throw new IllegalArgumentException("executionMode must be SIMULATION or RUNTIME");return x;}
    private String normalizeCompletionPolicy(String v){String x=blank(v)?"ALL_REQUIRED":v.trim().toUpperCase(Locale.ROOT);if(!Set.of("ALL_REQUIRED","QUORUM","BEST_EFFORT").contains(x))throw new IllegalArgumentException("Unsupported completionPolicy: "+x);return x;}
    private String normalizeCompletionResult(String v){String x=requireNonBlank(v,"result").toUpperCase(Locale.ROOT);if(!Set.of("SUCCEEDED","FAILED","TIMED_OUT","CANCELLED").contains(x))throw new IllegalArgumentException("Unsupported Step completion result: "+x);return x;}
    private boolean isTerminalRun(String s){return Set.of("SUCCEEDED","PARTIAL_SUCCEEDED","FAILED","CANCELLED","TIMED_OUT").contains(s);}
    private int between(int v,int min,int max,String f){if(v<min||v>max)throw new IllegalArgumentException(f+" must be between "+min+" and "+max);return v;}
    private long betweenLong(long v,long min,long max,String f){if(v<min||v>max)throw new IllegalArgumentException(f+" must be between "+min+" and "+max);return v;}
    private int limit(int v){return Math.max(1,Math.min(v<=0?100:v,500));}
    private String requireTenant(String v){return requireNonBlank(v,"tenantId");}
    private String requireNonBlank(String v,String f){if(blank(v))throw new IllegalArgumentException(f+" is required");return v.trim();}
    private String first(String a,String b){return !blank(a)?a:b;}
    private String trim(String v){return blank(v)?null:v.trim();}
    private boolean blank(String v){return v==null||v.isBlank();}
    private String str(Map<String,Object> m,String k){Object v=m.get(k);return v==null?null:String.valueOf(v);}
    private String write(Object v){try{return json.writeValueAsString(v);}catch(Exception ex){throw new IllegalArgumentException("Plan execution JSON cannot be serialized",ex);}}
    private Map<String,Object> readMap(String v){try{return blank(v)?Map.of():json.readValue(v,OBJECT_MAP);}catch(Exception ex){throw new IllegalStateException("Plan execution JSON object cannot be read",ex);}}
    private List<String> readStrings(String v){try{return blank(v)?List.of():json.readValue(v,STRING_LIST);}catch(Exception ex){throw new IllegalStateException("Plan execution JSON list cannot be read",ex);}}
    private CapabilityRequirement readRequirement(String v){try{return json.readValue(v,CapabilityRequirement.class);}catch(Exception ex){throw new IllegalStateException("CapabilityRequirement cannot be read",ex);}}
    private void bindDatabaseTenantContext(String tenant){IamTenantExecutionContext c=IamTenantContextHolder.current().orElse(null);if(c!=null&&!"INSTANCE".equalsIgnoreCase(c.tenantId())&&!tenant.equals(c.tenantId()))throw new IllegalArgumentException("Tenant context mismatch for Plan Execution persistence");jdbc.getJdbcTemplate().queryForObject("select set_config('app.current_tenant_id', ?, true)",String.class,tenant);jdbc.getJdbcTemplate().queryForObject("select set_config('app.current_actor_id', ?, true)",String.class,actorRef());}
    private String actorRef(){IamTenantExecutionContext c=IamTenantContextHolder.current().orElse(null);return c==null||blank(c.actorId())?"governed-plan-execution":c.actorId();}

    private final class PolicyMapper implements RowMapper<PlanExecutionPolicy>{public PlanExecutionPolicy mapRow(ResultSet rs,int n)throws SQLException{return new PlanExecutionPolicy(rs.getString("tenant_id"),rs.getString("policy_id"),rs.getString("display_name"),rs.getInt("max_attempts_per_step"),rs.getLong("default_step_timeout_seconds"),rs.getInt("max_active_steps"),rs.getBoolean("require_artifact_on_success"),rs.getString("status"),rs.getInt("version"),rs.getObject("created_at",OffsetDateTime.class),rs.getObject("updated_at",OffsetDateTime.class));}}
    private final class RunMapper implements RowMapper<PlanExecutionRun>{public PlanExecutionRun mapRow(ResultSet rs,int n)throws SQLException{return new PlanExecutionRun(rs.getString("run_id"),rs.getString("tenant_id"),rs.getString("plan_id"),rs.getInt("plan_revision"),rs.getString("plan_decision_id"),rs.getString("execution_mode"),rs.getString("status"),rs.getString("policy_id"),rs.getInt("policy_version"),rs.getString("idempotency_key"),rs.getLong("fencing_token"),rs.getString("completion_policy"),(Integer)rs.getObject("quorum_required"),rs.getString("convergence_outcome"),rs.getString("convergence_reason"),rs.getObject("started_at",OffsetDateTime.class),rs.getObject("updated_at",OffsetDateTime.class),rs.getObject("completed_at",OffsetDateTime.class));}}
    private final class StepMapper implements RowMapper<GovernedPlanExecutionStep>{public GovernedPlanExecutionStep mapRow(ResultSet rs,int n)throws SQLException{return new GovernedPlanExecutionStep(rs.getString("tenant_id"),rs.getString("run_id"),rs.getString("step_id"),readRequirement(rs.getString("capability_requirement_json")),readStrings(rs.getString("depends_on_json")),rs.getBoolean("required"),rs.getString("state"),rs.getInt("attempt_count"),rs.getString("authorization_decision_id"),rs.getString("routing_decision_id"),rs.getString("adapter_resolution_id"),rs.getString("child_task_ref"),rs.getObject("deadline_at",OffsetDateTime.class),rs.getObject("updated_at",OffsetDateTime.class),rs.getString("binding_authorization_envelope_id"),rs.getString("side_effect"),rs.getString("write_semantics"),rs.getString("compensation_binding_id"),rs.getInt("max_binding_fallback"));}}
    private final class AttemptMapper implements RowMapper<PlanExecutionAttempt>{public PlanExecutionAttempt mapRow(ResultSet rs,int n)throws SQLException{return new PlanExecutionAttempt(rs.getString("attempt_id"),rs.getString("tenant_id"),rs.getString("run_id"),rs.getString("step_id"),rs.getInt("attempt_no"),rs.getString("idempotency_key"),rs.getString("state"),rs.getString("adapter_resolution_id"),rs.getString("child_task_ref"),rs.getString("external_execution_ref"),readStrings(rs.getString("reason_codes_json")),rs.getObject("submitted_at",OffsetDateTime.class),rs.getObject("deadline_at",OffsetDateTime.class),rs.getObject("completed_at",OffsetDateTime.class));}}
    private final class ArtifactMapper implements RowMapper<PlanExecutionArtifact>{public PlanExecutionArtifact mapRow(ResultSet rs,int n)throws SQLException{return new PlanExecutionArtifact(rs.getString("artifact_id"),rs.getString("tenant_id"),rs.getString("run_id"),rs.getString("step_id"),rs.getString("attempt_id"),rs.getString("capability_code"),rs.getString("finding"),rs.getObject("confidence")==null?null:rs.getDouble("confidence"),readStrings(rs.getString("evidence_refs_json")),readMap(rs.getString("output_json")),rs.getString("data_classification"),rs.getObject("created_at",OffsetDateTime.class));}}
    private final class EventMapper implements RowMapper<PlanExecutionEvent>{public PlanExecutionEvent mapRow(ResultSet rs,int n)throws SQLException{return new PlanExecutionEvent(rs.getString("event_id"),rs.getString("tenant_id"),rs.getString("run_id"),rs.getString("step_id"),rs.getString("event_type"),rs.getString("from_state"),rs.getString("to_state"),rs.getString("reason"),rs.getString("actor_ref"),readMap(rs.getString("evidence_json")),rs.getObject("occurred_at",OffsetDateTime.class));}}
    private record PlanHeader(String planId,String status,int currentRevision,String taskRef){}
    private record PlanStepSnapshot(String stepId,CapabilityRequirement requirement,List<String> dependsOn,boolean required,String sideEffect,String writeSemantics,String compensationBindingId,int maxBindingFallback){}
    private record AuthorityEvidence(String authorizationDecisionId,String routingDecisionId,String adapterResolutionId,String bindingId,String providerId,String providerType,String adapterId,Integer adapterVersion,String adapterType){}
}
