package com.opensocket.aievent.core.capability;

import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantContextHolder;
import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantExecutionContext;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;
import tools.jackson.databind.ObjectMapper;

/**
 * Stage 12 governance boundary.
 * Execution Memory may recommend; it never authorizes. A certified Fast Path yields a semantic hint only.
 * This service deliberately has no execution-authority dependency and cannot create assignments, dispatch requests, provider routing decisions or plan runs.
 */
@Service
public class GovernedLearningFastPathService {
    private static final Set<String> RECOMMENDATION_TARGETS=Set.of(
        "FLOW_RULE_CANDIDATE","ROUTING_PROFILE_CANDIDATE","CAPABILITY_MAPPING_CANDIDATE",
        "PROVIDER_RELIABILITY_RECOMMENDATION","GOVERNANCE_POLICY_RECOMMENDATION","OPERATIONAL_RECOMMENDATION");
    private static final Set<String> RECOMMENDATION_REVIEW=Set.of("APPROVED","REJECTED");
    private static final Set<String> FORBIDDEN_TEMPLATE_KEYS=Set.of(
        "providerid","bindingid","agentid","agentpoolid","peerid","interfaceid","targetagentid","targetagentpoolid",
        "targetpeerid","targetdomain","targetsystem","preferredbinding","preferredagentpool","adapterid","endpointref","credentialref");
    private final NamedParameterJdbcTemplate jdbc;
    private final ObjectMapper json;
    public GovernedLearningFastPathService(NamedParameterJdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}

    @Transactional(readOnly=true)
    public List<Map<String,Object>> policies(String tenantId){String t=tenant(tenantId);bind(t);return jdbc.queryForList("select * from learning_governance_policies_v53 where tenant_id=:tenant order by updated_at desc,policy_id",p(t));}

    @Transactional
    public Map<String,Object> upsertPolicy(String tenantId,String policyId,Map<String,Object> body,String reason){
        String t=tenant(tenantId);bind(t);String id=required(policyId,"policyId"),status=upper(str(body,"status","DRAFT"));
        if(!Set.of("DRAFT","ACTIVE","DISABLED","RETIRED").contains(status))throw new IllegalArgumentException("Unsupported policy status: "+status);
        if(!bool(body,"requireHumanCertification",true))throw new IllegalArgumentException("Stage12 requires human certification and cannot be disabled");
        int recommendationSamples=intv(body,"minRecommendationSamples",20),replaySamples=intv(body,"minReplaySamples",20),shadowSamples=intv(body,"minShadowSamples",20);
        double replayRate=doublev(body,"minReplayMatchRate",.95),shadowRate=doublev(body,"minShadowMatchRate",.98),coverage=doublev(body,"minShadowCapabilityCoverage",1d);
        if(recommendationSamples<1||replaySamples<1||shadowSamples<1)throw new IllegalArgumentException("Sample thresholds must be >= 1");rate(replayRate);rate(shadowRate);rate(coverage);
        MapSqlParameterSource q=p(t).addValue("id",id);List<Map<String,Object>> old=jdbc.queryForList("select * from learning_governance_policies_v53 where tenant_id=:tenant and policy_id=:id",q);int version=old.isEmpty()?1:((Number)old.getFirst().get("version")).intValue()+1;
        if(!old.isEmpty()&&blank(reason))throw new IllegalArgumentException("X-Change-Reason is required when updating a Stage12 policy");
        if("ACTIVE".equals(status))jdbc.update("update learning_governance_policies_v53 set status='DISABLED',updated_at=now() where tenant_id=:tenant and status='ACTIVE' and policy_id<>:id",q);
        String name=str(body,"displayName",id);
        jdbc.update("""
          insert into learning_governance_policies_v53(tenant_id,policy_id,display_name,min_recommendation_samples,min_replay_samples,min_replay_match_rate,min_shadow_samples,min_shadow_match_rate,min_shadow_capability_coverage,require_human_certification,status,version)
          values(:tenant,:id,:name,:recommendation,:replaySamples,:replayRate,:shadowSamples,:shadowRate,:coverage,true,:status,:version)
          on conflict(tenant_id,policy_id) do update set display_name=excluded.display_name,min_recommendation_samples=excluded.min_recommendation_samples,min_replay_samples=excluded.min_replay_samples,min_replay_match_rate=excluded.min_replay_match_rate,min_shadow_samples=excluded.min_shadow_samples,min_shadow_match_rate=excluded.min_shadow_match_rate,min_shadow_capability_coverage=excluded.min_shadow_capability_coverage,require_human_certification=true,status=excluded.status,version=excluded.version,updated_at=now()
          """,q.addValue("name",name).addValue("recommendation",recommendationSamples).addValue("replaySamples",replaySamples).addValue("replayRate",replayRate).addValue("shadowSamples",shadowSamples).addValue("shadowRate",shadowRate).addValue("coverage",coverage).addValue("status",status).addValue("version",version));
        Map<String,Object> snapshot=new LinkedHashMap<>();snapshot.put("policyId",id);snapshot.put("displayName",name);snapshot.put("minRecommendationSamples",recommendationSamples);snapshot.put("minReplaySamples",replaySamples);snapshot.put("minReplayMatchRate",replayRate);snapshot.put("minShadowSamples",shadowSamples);snapshot.put("minShadowMatchRate",shadowRate);snapshot.put("minShadowCapabilityCoverage",coverage);snapshot.put("requireHumanCertification",true);snapshot.put("status",status);snapshot.put("version",version);
        jdbc.update("insert into learning_governance_policy_versions_v53(tenant_id,policy_id,version,snapshot_json,change_reason,actor_ref) values(:tenant,:id,:version,cast(:snapshot as jsonb),:reason,:actor)",q.addValue("snapshot",write(snapshot)).addValue("reason",old.isEmpty()?"INITIAL_CREATE":reason.trim()).addValue("actor",actor()));
        return snapshot;
    }

    @Transactional(readOnly=true)
    public List<Map<String,Object>> recommendations(String tenantId,String status,int limit){String t=tenant(tenantId);bind(t);MapSqlParameterSource q=p(t).addValue("limit",limit(limit));String sql="select * from learning_recommendations_v53 where tenant_id=:tenant";if(!blank(status)){sql+=" and status=:status";q.addValue("status",upper(status));}return jdbc.queryForList(sql+" order by created_at desc,recommendation_id desc limit :limit",q);}

    /** Converts executor-level observations into reviewable recommendations only. No routing pattern or Fast Path is created. */
    @Transactional
    public Map<String,Object> generateRecommendationsFromMemory(String tenantId,int limit){
        String t=tenant(tenantId);bind(t);Map<String,Object> policy=activePolicy(t);int min=((Number)policy.get("min_recommendation_samples")).intValue();
        List<Map<String,Object>> rows=jdbc.queryForList("select * from execution_memory_rollup_v53 where tenant_id=:tenant and sample_count>=:min order by sample_count desc limit :limit",p(t).addValue("min",min).addValue("limit",limit(limit)));
        int created=0,duplicate=0;for(Map<String,Object> r:rows){String capability=Objects.toString(r.get("capability_code"),"");String op=Objects.toString(r.get("operation"),"");String ptype=Objects.toString(r.get("provider_type"),"");String provider=Objects.toString(r.get("provider_id"),"");String binding=Objects.toString(r.get("binding_id"),"");Number rate=(Number)r.get("observed_success_rate");long samples=num(r.get("sample_count"));String target=rate!=null?"PROVIDER_RELIABILITY_RECOMMENDATION":"OPERATIONAL_RECOMMENDATION";String key=String.join("|",capability,op,ptype,provider,binding);String digest=sha(write(Map.of("key",key,"samples",samples,"rate",rate==null?"NULL":rate,"refreshedAt",Objects.toString(r.get("refreshed_at"),""))));String id="learning-rec-"+UUID.randomUUID();String title="PROVIDER_RELIABILITY_RECOMMENDATION".equals(target)?"Provider reliability observation":"Execution-memory operational observation";String summary="Observed "+samples+" executions for "+capability+" / "+ptype+". Human review is required; this recommendation has no execution authority.";
            try{jdbc.update("""
              insert into learning_recommendations_v53(tenant_id,recommendation_id,target_type,target_key,title,summary,capability_code,operation,provider_type,provider_id,binding_id,source_window_start,source_window_end,sample_count,observed_success_rate,average_latency_ms,booked_actual_cost,normalized_comparison_cost,unbooked_count,payload_json,evidence_digest,status)
              values(:tenant,:id,:target,:key,:title,:summary,:capability,:operation,:ptype,:provider,:binding,:start,:end,:samples,:rate,:latency,:actual,:normalized,:unbooked,cast(:payload as jsonb),:digest,'PROPOSED')
              """,p(t).addValue("id",id).addValue("target",target).addValue("key",key).addValue("title",title).addValue("summary",summary).addValue("capability",nullIfBlank(capability)).addValue("operation",nullIfBlank(op)).addValue("ptype",nullIfBlank(ptype)).addValue("provider",nullIfBlank(provider)).addValue("binding",nullIfBlank(binding)).addValue("start",r.get("first_bucket_date")).addValue("end",r.get("last_bucket_date")).addValue("samples",samples).addValue("rate",rate).addValue("latency",r.get("average_latency_ms")).addValue("actual",r.get("booked_actual_cost")).addValue("normalized",r.get("normalized_comparison_cost")).addValue("unbooked",num(r.get("unbooked_count"))).addValue("payload",write(Map.of("authority","RECOMMENDATION_ONLY","memoryRow",r))).addValue("digest",digest));appendRecommendationEvent(t,id,"CREATED",null,"PROPOSED","Generated from Stage11 Execution Memory",Map.of("executionAuthority",false));created++;}catch(DuplicateKeyException ex){duplicate++;}}
        return Map.of("status","COMPLETED","observationsEvaluated",rows.size(),"recommendationsCreated",created,"duplicatesSkipped",duplicate,"executionAuthorized",false);
    }

    @Transactional
    public Map<String,Object> reviewRecommendation(String tenantId,String recommendationId,String targetStatus,String reason){String t=tenant(tenantId);bind(t);String id=required(recommendationId,"recommendationId"),target=upper(targetStatus);if(!RECOMMENDATION_REVIEW.contains(target))throw new IllegalArgumentException("Review status must be APPROVED or REJECTED");String why=required(reason,"reason");Map<String,Object> row=one(t,"select * from learning_recommendations_v53 where tenant_id=:tenant and recommendation_id=:id",id);String from=Objects.toString(row.get("status"),"");if(!"PROPOSED".equals(from))throw new IllegalArgumentException("Only PROPOSED recommendations may be reviewed");jdbc.update("update learning_recommendations_v53 set status=:status,reviewed_by=:actor,review_reason=:reason,reviewed_at=now() where tenant_id=:tenant and recommendation_id=:id and status='PROPOSED'",p(t).addValue("id",id).addValue("status",target).addValue("actor",actor()).addValue("reason",why));appendRecommendationEvent(t,id,"HUMAN_REVIEW",from,target,why,Map.of("executionAuthorized",false));return one(t,"select * from learning_recommendations_v53 where tenant_id=:tenant and recommendation_id=:id",id);}

    @Transactional(readOnly=true)
    public List<Map<String,Object>> candidates(String tenantId,String status,int limit){String t=tenant(tenantId);bind(t);MapSqlParameterSource q=p(t).addValue("limit",limit(limit));String sql="select *,semantic_plan_template_json::text as semantic_plan_template_text,capability_keys_json::text as capability_keys_text from fast_path_semantic_candidates_v53 where tenant_id=:tenant";if(!blank(status)){sql+=" and status=:status";q.addValue("status",upper(status));}return jdbc.queryForList(sql+" order by updated_at desc,candidate_id desc limit :limit",q);}

    @Transactional
    public Map<String,Object> createCandidate(String tenantId,Map<String,Object> body){String t=tenant(tenantId);bind(t);String source=str(body,"sourceRecommendationId",null);if(!blank(source)){Map<String,Object> rec=one(t,"select * from learning_recommendations_v53 where tenant_id=:tenant and recommendation_id=:id",source);if(!"APPROVED".equals(Objects.toString(rec.get("status"))))throw new IllegalArgumentException("Source recommendation must be APPROVED");}String signature=required(str(body,"problemSignature",null),"problemSignature");Object template=body.get("semanticPlanTemplate");if(!(template instanceof Map<?,?>))throw new IllegalArgumentException("semanticPlanTemplate must be a JSON object");rejectForbiddenKeys(template);List<String> caps=strings(body.get("capabilityKeys"));if(caps.isEmpty())throw new IllegalArgumentException("capabilityKeys must not be empty");validateCapabilities(t,caps);String templateJson=write(template),capsJson=write(caps),digest=sha(canonical(template)+"|"+canonical(caps));String id="fast-path-candidate-"+UUID.randomUUID();jdbc.update("insert into fast_path_semantic_candidates_v53(tenant_id,candidate_id,source_recommendation_id,problem_signature,classification,source_plan_id,source_plan_revision,semantic_plan_template_json,capability_keys_json,template_digest,status,version,created_by) values(:tenant,:id,:source,:signature,:classification,:plan,:revision,cast(:template as jsonb),cast(:caps as jsonb),:digest,'REPLAY_REQUIRED',1,:actor)",p(t).addValue("id",id).addValue("source",nullIfBlank(source)).addValue("signature",signature).addValue("classification",nullIfBlank(str(body,"classification",null))).addValue("plan",nullIfBlank(str(body,"sourcePlanId",null))).addValue("revision",body.get("sourcePlanRevision")).addValue("template",templateJson).addValue("caps",capsJson).addValue("digest",digest).addValue("actor",actor()));return one(t,"select * from fast_path_semantic_candidates_v53 where tenant_id=:tenant and candidate_id=:id",id);}

    @Transactional
    public Map<String,Object> recordReplay(String tenantId,String candidateId,Map<String,Object> body){String t=tenant(tenantId);bind(t);Map<String,Object> c=candidate(t,candidateId);if(!"REPLAY_REQUIRED".equals(Objects.toString(c.get("status"))))throw new IllegalArgumentException("Candidate must be REPLAY_REQUIRED");int samples=intv(body,"sampleCount",0),mismatches=intv(body,"mismatchCount",0);double match=doublev(body,"semanticMatchRate",-1);if(samples<1)throw new IllegalArgumentException("sampleCount must be >=1");rate(match);String id="replay-"+UUID.randomUUID();jdbc.update("insert into fast_path_replay_evidence_v53(tenant_id,evidence_id,candidate_id,candidate_version,sample_count,semantic_match_rate,mismatch_count,execution_affected,evidence_json) values(:tenant,:id,:candidate,:version,:samples,:match,:mismatches,false,cast(:evidence as jsonb))",p(t).addValue("id",id).addValue("candidate",candidateId).addValue("version",c.get("version")).addValue("samples",samples).addValue("match",match).addValue("mismatches",mismatches).addValue("evidence",write(body.getOrDefault("evidence",Map.of()))));Map<String,Object> pol=activePolicy(t);boolean pass=samples>=num(pol.get("min_replay_samples"))&&match>=doubleNum(pol.get("min_replay_match_rate"));if(pass)jdbc.update("update fast_path_semantic_candidates_v53 set status='SHADOW_REQUIRED',updated_at=now() where tenant_id=:tenant and candidate_id=:id and status='REPLAY_REQUIRED'",p(t).addValue("id",candidateId));return Map.of("evidenceId",id,"candidateId",candidateId,"result",pass?"REPLAY_PASSED":"REPLAY_INSUFFICIENT","nextStatus",pass?"SHADOW_REQUIRED":"REPLAY_REQUIRED","executionAffected",false);}

    @Transactional
    public Map<String,Object> recordShadow(String tenantId,String candidateId,Map<String,Object> body){String t=tenant(tenantId);bind(t);Map<String,Object> c=candidate(t,candidateId);if(!"SHADOW_REQUIRED".equals(Objects.toString(c.get("status"))))throw new IllegalArgumentException("Candidate must be SHADOW_REQUIRED");int samples=intv(body,"sampleCount",0),mismatches=intv(body,"mismatchCount",0);double match=doublev(body,"semanticMatchRate",-1),coverage=doublev(body,"capabilityCoverage",-1);if(samples<1)throw new IllegalArgumentException("sampleCount must be >=1");rate(match);rate(coverage);String id="shadow-"+UUID.randomUUID();jdbc.update("insert into fast_path_shadow_evidence_v53(tenant_id,evidence_id,candidate_id,candidate_version,sample_count,semantic_match_rate,capability_coverage,mismatch_count,execution_affected,evidence_json) values(:tenant,:id,:candidate,:version,:samples,:match,:coverage,:mismatches,false,cast(:evidence as jsonb))",p(t).addValue("id",id).addValue("candidate",candidateId).addValue("version",c.get("version")).addValue("samples",samples).addValue("match",match).addValue("coverage",coverage).addValue("mismatches",mismatches).addValue("evidence",write(body.getOrDefault("evidence",Map.of()))));Map<String,Object> pol=activePolicy(t);boolean pass=samples>=num(pol.get("min_shadow_samples"))&&match>=doubleNum(pol.get("min_shadow_match_rate"))&&coverage>=doubleNum(pol.get("min_shadow_capability_coverage"));if(pass)jdbc.update("update fast_path_semantic_candidates_v53 set status='CERTIFICATION_READY',updated_at=now() where tenant_id=:tenant and candidate_id=:id and status='SHADOW_REQUIRED'",p(t).addValue("id",candidateId));return Map.of("evidenceId",id,"candidateId",candidateId,"result",pass?"SHADOW_PASSED":"SHADOW_INSUFFICIENT","nextStatus",pass?"CERTIFICATION_READY":"SHADOW_REQUIRED","executionAffected",false);}

    @Transactional
    public Map<String,Object> certify(String tenantId,String candidateId,String reason){String t=tenant(tenantId);bind(t);Map<String,Object> c=candidate(t,candidateId);if(!"CERTIFICATION_READY".equals(Objects.toString(c.get("status"))))throw new IllegalArgumentException("Candidate must be CERTIFICATION_READY");String why=required(reason,"reason");Map<String,Object> pol=activePolicy(t);if(!Boolean.TRUE.equals(pol.get("require_human_certification")))throw new IllegalStateException("Stage12 human certification invariant violated");Map<String,Object> replay=latest(t,"fast_path_replay_evidence_v53",candidateId),shadow=latest(t,"fast_path_shadow_evidence_v53",candidateId);if(replay==null||shadow==null)throw new IllegalArgumentException("Replay and Shadow evidence are required");int replaySamples=((Number)replay.get("sample_count")).intValue(),shadowSamples=((Number)shadow.get("sample_count")).intValue();double replayRate=doubleNum(replay.get("semantic_match_rate")),shadowRate=doubleNum(shadow.get("semantic_match_rate")),coverage=doubleNum(shadow.get("capability_coverage"));if(replaySamples<num(pol.get("min_replay_samples"))||replayRate<doubleNum(pol.get("min_replay_match_rate"))||shadowSamples<num(pol.get("min_shadow_samples"))||shadowRate<doubleNum(pol.get("min_shadow_match_rate"))||coverage<doubleNum(pol.get("min_shadow_capability_coverage")))throw new IllegalArgumentException("Candidate no longer satisfies certification policy thresholds");List<String> caps=readStrings(Objects.toString(c.get("capability_keys_json"),"[]"));String schemaDigest=capabilitySchemaDigest(t,caps);String id="fast-cert-"+UUID.randomUUID();jdbc.update("insert into fast_path_certifications_v53(tenant_id,certification_id,candidate_id,candidate_version,template_digest,capability_schema_digest,policy_id,policy_version,replay_sample_count,replay_match_rate,shadow_sample_count,shadow_match_rate,shadow_capability_coverage,status,certified_by,certification_reason) values(:tenant,:id,:candidate,:version,:template,:schema,:policy,:policyVersion,:replaySamples,:replayRate,:shadowSamples,:shadowRate,:coverage,'CERTIFIED',:actor,:reason)",p(t).addValue("id",id).addValue("candidate",candidateId).addValue("version",c.get("version")).addValue("template",c.get("template_digest")).addValue("schema",schemaDigest).addValue("policy",pol.get("policy_id")).addValue("policyVersion",pol.get("version")).addValue("replaySamples",replaySamples).addValue("replayRate",replayRate).addValue("shadowSamples",shadowSamples).addValue("shadowRate",shadowRate).addValue("coverage",coverage).addValue("actor",actor()).addValue("reason",why));jdbc.update("update fast_path_semantic_candidates_v53 set status='CERTIFIED',updated_at=now() where tenant_id=:tenant and candidate_id=:id and status='CERTIFICATION_READY'",p(t).addValue("id",candidateId));return certification(t,id);}

    @Transactional(readOnly=true)
    public List<Map<String,Object>> certifications(String tenantId,String candidateId,int limit){String t=tenant(tenantId);bind(t);MapSqlParameterSource q=p(t).addValue("limit",limit(limit));String sql="select * from fast_path_certifications_v53 where tenant_id=:tenant";if(!blank(candidateId)){sql+=" and candidate_id=:candidate";q.addValue("candidate",candidateId.trim());}return jdbc.queryForList(sql+" order by certified_at desc,certification_id desc limit :limit",q);}

    @Transactional
    public Map<String,Object> resolveRuntimeHint(String tenantId,Map<String,Object> body){String t=tenant(tenantId);bind(t);String task=required(str(body,"taskRef",null),"taskRef"),key=required(str(body,"idempotencyKey",null),"idempotencyKey"),signature=required(str(body,"problemSignature",null),"problemSignature");List<Map<String,Object>> prior=jdbc.queryForList("select * from fast_path_runtime_hints_v53 where tenant_id=:tenant and task_ref=:task and idempotency_key=:key",p(t).addValue("task",task).addValue("key",key));if(!prior.isEmpty())return prior.getFirst();List<Map<String,Object>> matches=jdbc.queryForList("select * from fast_path_semantic_candidates_v53 where tenant_id=:tenant and problem_signature=:signature and status='CERTIFIED'",p(t).addValue("signature",signature));if(matches.size()!=1)return insertHint(t,task,key,signature,matches.isEmpty()?"NO_CANDIDATE":"MULTIPLE_CANDIDATES_FAIL_CLOSED",null,null,List.of(matches.isEmpty()?"NO_CERTIFIED_SEMANTIC_CANDIDATE":"MULTIPLE_CERTIFIED_CANDIDATES_FAIL_CLOSED","FALLBACK_ADAPTIVE_PATH"));Map<String,Object> c=matches.getFirst();Map<String,Object> cert=latestCertification(t,Objects.toString(c.get("candidate_id")));if(cert==null||!"CERTIFIED".equals(Objects.toString(cert.get("status"))))return insertHint(t,task,key,signature,"NOT_CERTIFIED",c,null,List.of("CURRENT_HUMAN_CERTIFICATION_REQUIRED","FALLBACK_ADAPTIVE_PATH"));String currentTemplateDigest=sha(canonicalJsonText(Objects.toString(c.get("semantic_plan_template_json"),"{}"))+"|"+canonicalJsonText(Objects.toString(c.get("capability_keys_json"),"[]")));String storedTemplateDigest=Objects.toString(c.get("template_digest"),"");if(!storedTemplateDigest.equals(Objects.toString(cert.get("template_digest"),""))||!storedTemplateDigest.equals(currentTemplateDigest)){suspend(t,c,cert,"CANDIDATE_TEMPLATE_DRIFT");return insertHint(t,task,key,signature,"CANDIDATE_TEMPLATE_DRIFT",c,cert,List.of("CANDIDATE_TEMPLATE_DRIFT","CERTIFICATION_AUTO_SUSPENDED","FALLBACK_ADAPTIVE_PATH"));}List<String> caps=readStrings(Objects.toString(c.get("capability_keys_json"),"[]"));String schema=capabilitySchemaDigest(t,caps);if(!schema.equals(Objects.toString(cert.get("capability_schema_digest"),""))){suspend(t,c,cert,"CAPABILITY_SCHEMA_DRIFT");return insertHint(t,task,key,signature,"CAPABILITY_SCHEMA_DRIFT",c,cert,List.of("CAPABILITY_SCHEMA_DRIFT","CERTIFICATION_AUTO_SUSPENDED","FALLBACK_ADAPTIVE_PATH"));}return insertHint(t,task,key,signature,"HINT_AVAILABLE",c,cert,List.of("CERTIFIED_SEMANTIC_HINT_AVAILABLE","EXECUTION_NOT_AUTHORIZED","CURRENT_WHO_CAN_WHO_MAY_WHO_SHOULD_HOW_STILL_REQUIRED","CURRENT_AUTHORIZATION_EPOCH_AND_LEASE_FENCING_STILL_REQUIRED"));}

    @Transactional(readOnly=true)
    public List<Map<String,Object>> runtimeHints(String tenantId,String taskRef,int limit){String t=tenant(tenantId);bind(t);MapSqlParameterSource q=p(t).addValue("limit",limit(limit));String sql="select * from fast_path_runtime_hints_v53 where tenant_id=:tenant";if(!blank(taskRef)){sql+=" and task_ref=:task";q.addValue("task",taskRef.trim());}return jdbc.queryForList(sql+" order by created_at desc,hint_id desc limit :limit",q);}

    private Map<String,Object> insertHint(String t,String task,String key,String signature,String result,Map<String,Object> c,Map<String,Object> cert,List<String> reasons){String id="fast-hint-"+UUID.randomUUID();jdbc.update("insert into fast_path_runtime_hints_v53(tenant_id,hint_id,task_ref,idempotency_key,problem_signature,result,candidate_id,candidate_version,certification_id,template_digest,semantic_plan_template_json,capability_keys_json,execution_authorized,reason_codes_json) values(:tenant,:id,:task,:key,:signature,:result,:candidate,:version,:cert,:digest,cast(:template as jsonb),cast(:caps as jsonb),false,cast(:reasons as jsonb))",p(t).addValue("id",id).addValue("task",task).addValue("key",key).addValue("signature",signature).addValue("result",result).addValue("candidate",c==null?null:c.get("candidate_id")).addValue("version",c==null?null:c.get("version")).addValue("cert",cert==null?null:cert.get("certification_id")).addValue("digest",c==null?null:c.get("template_digest")).addValue("template",c==null?null:Objects.toString(c.get("semantic_plan_template_json"),null)).addValue("caps",c==null?null:Objects.toString(c.get("capability_keys_json"),null)).addValue("reasons",write(reasons)));return one(t,"select * from fast_path_runtime_hints_v53 where tenant_id=:tenant and hint_id=:id",id);}
    private void suspend(String t,Map<String,Object> c,Map<String,Object> cert,String reason){jdbc.update("update fast_path_certifications_v53 set status='SUSPENDED',suspended_reason=:reason,suspended_at=now() where tenant_id=:tenant and certification_id=:id and status='CERTIFIED'",p(t).addValue("id",cert.get("certification_id")).addValue("reason",reason));jdbc.update("update fast_path_semantic_candidates_v53 set status='SUSPENDED',updated_at=now() where tenant_id=:tenant and candidate_id=:id and status='CERTIFIED'",p(t).addValue("id",c.get("candidate_id")));}
    private void appendRecommendationEvent(String t,String recommendationId,String type,String from,String to,String reason,Map<String,Object> evidence){jdbc.update("insert into learning_recommendation_events_v53(tenant_id,event_id,recommendation_id,event_type,from_status,to_status,actor_ref,reason,evidence_json) values(:tenant,:event,:id,:type,:from,:to,:actor,:reason,cast(:evidence as jsonb))",p(t).addValue("event","learning-event-"+UUID.randomUUID()).addValue("id",recommendationId).addValue("type",type).addValue("from",from).addValue("to",to).addValue("actor",actor()).addValue("reason",reason).addValue("evidence",write(evidence)));}
    private Map<String,Object> activePolicy(String t){List<Map<String,Object>> rows=jdbc.queryForList("select * from learning_governance_policies_v53 where tenant_id=:tenant and status='ACTIVE' order by version desc limit 1",p(t));if(rows.isEmpty())throw new IllegalArgumentException("STAGE12_LEARNING_GOVERNANCE_POLICY_NOT_CONFIGURED");return rows.getFirst();}
    private Map<String,Object> candidate(String t,String id){return one(t,"select * from fast_path_semantic_candidates_v53 where tenant_id=:tenant and candidate_id=:id",required(id,"candidateId"));}
    private Map<String,Object> certification(String t,String id){return one(t,"select * from fast_path_certifications_v53 where tenant_id=:tenant and certification_id=:id",id);}
    private Map<String,Object> latest(String t,String table,String candidateId){List<Map<String,Object>> rows=jdbc.queryForList("select * from "+table+" where tenant_id=:tenant and candidate_id=:candidate order by observed_at desc,evidence_id desc limit 1",p(t).addValue("candidate",candidateId));return rows.isEmpty()?null:rows.getFirst();}
    private Map<String,Object> latestCertification(String t,String candidateId){List<Map<String,Object>> rows=jdbc.queryForList("select * from fast_path_certifications_v53 where tenant_id=:tenant and candidate_id=:candidate order by certified_at desc,certification_id desc limit 1",p(t).addValue("candidate",candidateId));return rows.isEmpty()?null:rows.getFirst();}
    private Map<String,Object> one(String t,String sql,String id){List<Map<String,Object>> rows=jdbc.queryForList(sql,p(t).addValue("id",id));if(rows.isEmpty())throw new IllegalArgumentException("Stage12 resource not found: "+id);return rows.getFirst();}
    private void validateCapabilities(String t,List<String> caps){for(String code:caps){Integer n=jdbc.queryForObject("select count(*) from capability_definitions where tenant_id=:tenant and capability_code=:code and status='ACTIVE'",p(t).addValue("code",code),Integer.class);if(n==null||n!=1)throw new IllegalArgumentException("Canonical ACTIVE Capability not found: "+code);}}
    private String capabilitySchemaDigest(String t,List<String> caps){if(caps.isEmpty())return sha("[]");List<Map<String,Object>> rows=jdbc.queryForList("select capability_code,version,operations_json::text as operations,input_schema_json::text as input_schema,output_schema_json::text as output_schema,data_classes_json::text as data_classes,status from capability_definitions where tenant_id=:tenant and capability_code in (:codes) order by capability_code",p(t).addValue("codes",caps));if(rows.size()!=new LinkedHashSet<>(caps).size())return sha("MISSING_CAPABILITY:"+write(caps));return sha(write(rows));}
    private void rejectForbiddenKeys(Object value){if(value instanceof Map<?,?> map){for(Map.Entry<?,?> e:map.entrySet()){String k=String.valueOf(e.getKey()).replace("_","").replace("-","").toLowerCase(Locale.ROOT);if(FORBIDDEN_TEMPLATE_KEYS.contains(k))throw new IllegalArgumentException("Semantic Fast Path template may not contain runtime target selector: "+e.getKey());rejectForbiddenKeys(e.getValue());}}else if(value instanceof Collection<?> c){c.forEach(this::rejectForbiddenKeys);}}
    private List<String> strings(Object v){if(!(v instanceof Collection<?> c))return List.of();LinkedHashSet<String> out=new LinkedHashSet<>();for(Object x:c){if(x!=null&&!String.valueOf(x).isBlank())out.add(String.valueOf(x).trim());}return List.copyOf(out);}
    private List<String> readStrings(String text){try{return json.readValue(text,json.getTypeFactory().constructCollectionType(List.class,String.class));}catch(Exception e){throw new IllegalArgumentException("Invalid capability key evidence",e);}}
    private String actor(){IamTenantExecutionContext c=IamTenantContextHolder.current().orElse(null);return c==null||blank(c.actorId())?"stage12-governance":c.actorId();}
    private String tenant(String v){return required(v,"tenantId");}
    private void bind(String t){bindTenantContext(t,"STAGE12_GOVERNED_LEARNING");}
    private void bindTenantContext(String tenantId,String backgroundActor){
        IamTenantExecutionContext current=IamTenantContextHolder.current().orElse(null);
        String actor=backgroundActor;
        if(current!=null){
            if(!tenantId.equals(current.tenantId()))throw new IllegalStateException("TENANT_CONTEXT_MISMATCH");
            actor=current.actorId();
        }else{
            if(!TransactionSynchronizationManager.isActualTransactionActive()||!TransactionSynchronizationManager.isSynchronizationActive())throw new IllegalStateException("TENANT_TRANSACTION_REQUIRED");
            IamTenantContextHolder.Scope scope=IamTenantContextHolder.open(new IamTenantExecutionContext(tenantId,backgroundActor));
            TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){@Override public void afterCompletion(int status){scope.close();}});
        }
        MapSqlParameterSource context=new MapSqlParameterSource("tenant",tenantId).addValue("actor",actor);
        jdbc.queryForObject("select set_config('app.current_tenant_id',:tenant,true) || ':' || set_config('app.current_actor_id',:actor,true)",context,String.class);
    }
    private MapSqlParameterSource p(String t){return new MapSqlParameterSource("tenant",t);}private int limit(int n){return Math.max(1,Math.min(n,1000));}private static boolean blank(String s){return s==null||s.isBlank();}private static String required(String s,String n){if(blank(s))throw new IllegalArgumentException(n+" is required");return s.trim();}private static String upper(String s){return required(s,"value").toUpperCase(Locale.ROOT);}private static String nullIfBlank(String s){return blank(s)?null:s.trim();}
    private String str(Map<String,Object>b,String k,String d){Object v=b==null?null:b.get(k);return v==null?d:String.valueOf(v);}private int intv(Map<String,Object>b,String k,int d){Object v=b==null?null:b.get(k);return v instanceof Number n?n.intValue():v==null?d:Integer.parseInt(String.valueOf(v));}private double doublev(Map<String,Object>b,String k,double d){Object v=b==null?null:b.get(k);return v instanceof Number n?n.doubleValue():v==null?d:Double.parseDouble(String.valueOf(v));}private boolean bool(Map<String,Object>b,String k,boolean d){Object v=b==null?null:b.get(k);return v==null?d:Boolean.parseBoolean(String.valueOf(v));}private void rate(double d){if(d<0||d>1)throw new IllegalArgumentException("Rate must be between 0 and 1");}private long num(Object o){return o instanceof Number n?n.longValue():o==null?0:Long.parseLong(String.valueOf(o));}private double doubleNum(Object o){return o instanceof Number n?n.doubleValue():Double.parseDouble(String.valueOf(o));}

    private String canonicalJsonText(String text){try{return canonical(json.readValue(text,Object.class));}catch(Exception e){throw new IllegalArgumentException("Invalid Stage12 JSON evidence",e);}}
    private String canonical(Object value){try{return json.writeValueAsString(normalize(value));}catch(Exception e){throw new IllegalArgumentException("Unable to canonicalize Stage12 evidence",e);}}
    private Object normalize(Object value){if(value instanceof Map<?,?> map){TreeMap<String,Object> sorted=new TreeMap<>();for(Map.Entry<?,?> e:map.entrySet())sorted.put(String.valueOf(e.getKey()),normalize(e.getValue()));return sorted;}if(value instanceof Collection<?> c){List<Object> out=new ArrayList<>();for(Object x:c)out.add(normalize(x));return out;}return value;}
    private String write(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new IllegalArgumentException("Unable to serialize Stage12 evidence",e);}}private String sha(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
