package com.opensocket.aievent.core.capability;

import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantContextHolder;
import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantExecutionContext;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Duration;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

/**
 * Phase 10 learning authority. Learning can propose semantic plan templates but never Provider/Agent/Pool/transport.
 * Promotion is human governed. Fast Path skips repeated Triage/Planner only; every execution step still traverses
 * WHO MAY -> WHO SHOULD -> HOW with current evidence.
 */
@Service
public class LearningFastPathService {
    private static final String SIGNATURE_VERSION="CAPABILITY_SET_V1";
    private static final Set<String> POLICY_STATUSES=Set.of("DRAFT","ACTIVE","DISABLED","RETIRED");
    private static final Set<String> PATTERN_STATUSES=Set.of("SHADOW","ACTIVE","DEGRADED","RETIRED");
    private static final TypeReference<Map<String,Object>> MAP=new TypeReference<>(){};
    private static final TypeReference<List<String>> STRINGS=new TypeReference<>(){};
    private final NamedParameterJdbcTemplate jdbc; private final ObjectMapper json;
    public LearningFastPathService(NamedParameterJdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}

    @Transactional(readOnly=true)
    public List<LearningPolicy> policies(String tenantId,String status,int limit){String t=tenant(tenantId);bind(t);MapSqlParameterSource p=new MapSqlParameterSource("tenant",t).addValue("limit",limit(limit));String w=" where tenant_id=:tenant";if(!blank(status)){w+=" and status=:status";p.addValue("status",policyStatus(status));}return jdbc.query("select * from learning_policies"+w+" order by policy_id limit :limit",p,new LearningPolicyMapper());}

    @Transactional
    public LearningPolicy upsertPolicy(String tenantId,String pathId,LearningPolicy req,String changeReason){String t=tenant(tenantId);bind(t);if(req==null)throw new IllegalArgumentException("Learning Policy body is required");String id=required(first(pathId,req.policyId()),"policyId"),status=policyStatus(req.status());LearningPolicy old=findPolicy(t,id).orElse(null);if(old!=null&&blank(changeReason))throw new IllegalArgumentException("X-Change-Reason is required when changing an existing Learning Policy");validatePolicy(req);if("ACTIVE".equals(status)){Integer n=jdbc.queryForObject("select count(*) from learning_policies where tenant_id=:tenant and status='ACTIVE' and policy_id<>:id",new MapSqlParameterSource("tenant",t).addValue("id",id),Integer.class);if(n!=null&&n>0)throw new IllegalArgumentException("Only one ACTIVE Learning Policy is allowed per Tenant");}
        int version=old==null?1:old.version()+1;OffsetDateTime now=OffsetDateTime.now(),created=old==null?now:old.createdAt();jdbc.update("""
        insert into learning_policies(tenant_id,policy_id,display_name,min_candidate_samples,min_candidate_success_rate,min_candidate_human_acceptance_rate,min_shadow_samples,min_active_success_rate,min_active_human_acceptance_rate,max_p95_latency_ms,drift_window_size,require_human_approval_for_promotion,status,version,created_at,updated_at)
        values(:tenant,:id,:name,:mcs,:mcsr,:mchar,:mss,:masr,:mahar,:lat,:window,:human,:status,:version,:created,:updated)
        on conflict(tenant_id,policy_id) do update set display_name=excluded.display_name,min_candidate_samples=excluded.min_candidate_samples,min_candidate_success_rate=excluded.min_candidate_success_rate,min_candidate_human_acceptance_rate=excluded.min_candidate_human_acceptance_rate,min_shadow_samples=excluded.min_shadow_samples,min_active_success_rate=excluded.min_active_success_rate,min_active_human_acceptance_rate=excluded.min_active_human_acceptance_rate,max_p95_latency_ms=excluded.max_p95_latency_ms,drift_window_size=excluded.drift_window_size,require_human_approval_for_promotion=excluded.require_human_approval_for_promotion,status=excluded.status,version=excluded.version,updated_at=excluded.updated_at
        """,new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("name",required(req.displayName(),"displayName")).addValue("mcs",req.minCandidateSamples()).addValue("mcsr",req.minCandidateSuccessRate()).addValue("mchar",req.minCandidateHumanAcceptanceRate()).addValue("mss",req.minShadowSamples()).addValue("masr",req.minActiveSuccessRate()).addValue("mahar",req.minActiveHumanAcceptanceRate()).addValue("lat",req.maxP95LatencyMs()).addValue("window",req.driftWindowSize()).addValue("human",req.requireHumanApprovalForPromotion()).addValue("status",status).addValue("version",version).addValue("created",created).addValue("updated",now));LearningPolicy saved=findPolicy(t,id).orElseThrow();appendPolicyVersion(saved,old==null?"INITIAL_CREATE":changeReason);if(old!=null&&"ACTIVE".equals(old.status())&&(saved.version()!=old.version()||!"ACTIVE".equals(saved.status())))degradePatternsForPolicyChange(t,old.policyId(),saved.version(),"LEARNING_POLICY_CHANGED_REQUIRES_REQUALIFICATION");return saved;}

    @Transactional(readOnly=true)
    public List<LearningPolicyVersion> policyVersions(String tenantId,String id){String t=tenant(tenantId);bind(t);return jdbc.query("select * from learning_policy_versions where tenant_id=:tenant and policy_id=:id order by version desc",new MapSqlParameterSource("tenant",t).addValue("id",required(id,"policyId")),(rs,n)->new LearningPolicyVersion(t,rs.getString("policy_id"),rs.getInt("version"),readMap(rs.getString("snapshot_json")),rs.getString("change_reason"),rs.getString("actor_ref"),rs.getObject("created_at",OffsetDateTime.class)));}

    @Transactional
    public ExecutionOutcomeEvidence recordOutcome(String tenantId,String caseId){String t=tenant(tenantId);bind(t);String cid=required(caseId,"caseId");Optional<ExecutionOutcomeEvidence> existing=findOutcomeByCase(t,cid);if(existing.isPresent())return existing.get();Map<String,Object> c=one("select case_id,run_id,plan_id,status,classification,human_decision,accountable_ref from enterprise_cases where tenant_id=:tenant and case_id=:id",t,cid);String caseStatus=str(c,"status"),human=str(c,"human_decision"),accountable=str(c,"accountable_ref");if(!Set.of("RESOLVED","CLOSED").contains(caseStatus)||blank(human)||blank(accountable))throw new IllegalArgumentException("Learning requires a RESOLVED/CLOSED Case with Human Decision and accountableRef");String run=str(c,"run_id"),plan=str(c,"plan_id");Map<String,Object> r=one("select plan_revision,status,started_at,completed_at from plan_execution_runs where tenant_id=:tenant and run_id=:id",t,run);String runStatus=str(r,"status");if(!Set.of("SUCCEEDED","PARTIAL_SUCCEEDED","FAILED","TIMED_OUT","CANCELLED").contains(runStatus))throw new IllegalArgumentException("Learning requires a terminal Plan Run");int revision=((Number)r.get("plan_revision")).intValue();Map<String,Object> template=planTemplate(t,plan,revision);List<String> keys=capabilityKeys(template);String classification=str(c,"classification"),signature=signature(classification,keys);OffsetDateTime started=(OffsetDateTime)r.get("started_at"),completed=(OffsetDateTime)r.get("completed_at");Long latency=started!=null&&completed!=null?Math.max(0,Duration.between(started,completed).toMillis()):null;boolean success="SUCCEEDED".equals(runStatus);String oid="outcome-"+UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();jdbc.update("""
        insert into execution_outcome_evidence(tenant_id,outcome_id,case_id,run_id,plan_id,plan_revision,problem_signature,signature_version,classification,capability_keys_json,execution_succeeded,human_accepted,latency_ms,token_usage,estimated_cost,human_decision,accountable_ref,recorded_at)
        values(:tenant,:oid,:case,:run,:plan,:revision,:signature,:sv,:classification,cast(:keys as jsonb),:success,true,:latency,null,null,:human,:accountable,:at)
        """,new MapSqlParameterSource("tenant",t).addValue("oid",oid).addValue("case",cid).addValue("run",run).addValue("plan",plan).addValue("revision",revision).addValue("signature",signature).addValue("sv",SIGNATURE_VERSION).addValue("classification",classification).addValue("keys",write(keys)).addValue("success",success).addValue("latency",latency).addValue("human",human).addValue("accountable",accountable).addValue("at",now));ExecutionOutcomeEvidence out=findOutcomeByCase(t,cid).orElseThrow();refreshCandidate(t,out,template);return out;}

    @Transactional(readOnly=true)
    public List<ExecutionOutcomeEvidence> outcomes(String tenantId,String signature,int limit){String t=tenant(tenantId);bind(t);MapSqlParameterSource p=new MapSqlParameterSource("tenant",t).addValue("limit",limit(limit));String w=" where tenant_id=:tenant";if(!blank(signature)){w+=" and problem_signature=:signature";p.addValue("signature",signature.trim());}return jdbc.query("select * from execution_outcome_evidence"+w+" order by recorded_at desc,outcome_id desc limit :limit",p,new OutcomeMapper());}

    @Transactional(readOnly=true)
    public List<RoutingPatternCandidate> candidates(String tenantId,String status,int limit){String t=tenant(tenantId);bind(t);MapSqlParameterSource p=new MapSqlParameterSource("tenant",t).addValue("limit",limit(limit));String w=" where tenant_id=:tenant";if(!blank(status)){w+=" and status=:status";p.addValue("status",status.trim().toUpperCase(Locale.ROOT));}return jdbc.query("select * from routing_pattern_candidates"+w+" order by last_observed_at desc,candidate_id desc limit :limit",p,new CandidateMapper());}

    @Transactional
    public PatternPromotionDecision promoteCandidateToShadow(String tenantId,String candidateId,String reason){String t=tenant(tenantId);bind(t);String cid=required(candidateId,"candidateId"),why=required(reason,"reason");RoutingPatternCandidate c=requireCandidate(t,cid);LearningPolicy p=requireActivePolicy(t);List<String> reasons=new ArrayList<>();if(!"CANDIDATE_READY".equals(c.status()))reasons.add("CANDIDATE_NOT_READY");if(c.sampleCount()<p.minCandidateSamples())reasons.add("MIN_CANDIDATE_SAMPLES_NOT_MET");if(c.successRate()<p.minCandidateSuccessRate())reasons.add("MIN_CANDIDATE_SUCCESS_RATE_NOT_MET");if(c.humanAcceptanceRate()<p.minCandidateHumanAcceptanceRate())reasons.add("MIN_CANDIDATE_HUMAN_ACCEPTANCE_NOT_MET");if(p.maxP95LatencyMs()!=null&&c.p95LatencyMs()!=null&&c.p95LatencyMs()>p.maxP95LatencyMs())reasons.add("MAX_P95_LATENCY_EXCEEDED");if(!reasons.isEmpty())return promotionDecision(t,cid,null,c.status(),"SHADOW","REJECTED",reasons);
        String patternId="pattern-"+UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();jdbc.update("""
        insert into routing_patterns(tenant_id,pattern_id,candidate_id,problem_signature,signature_version,classification,capability_keys_json,plan_template_json,status,version,learning_policy_id,learning_policy_version,created_at,updated_at)
        values(:tenant,:pattern,:candidate,:signature,:sv,:classification,cast(:keys as jsonb),cast(:plan as jsonb),'SHADOW',1,:policy,:policyVersion,:at,:at)
        """,new MapSqlParameterSource("tenant",t).addValue("pattern",patternId).addValue("candidate",cid).addValue("signature",c.problemSignature()).addValue("sv",c.signatureVersion()).addValue("classification",c.classification()).addValue("keys",write(c.capabilityKeys())).addValue("plan",write(c.planTemplate())).addValue("policy",p.policyId()).addValue("policyVersion",p.version()).addValue("at",now));jdbc.update("update routing_pattern_candidates set status='PROMOTED' where tenant_id=:tenant and candidate_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",cid));RoutingPattern pattern=requirePattern(t,patternId);appendPatternVersion(pattern,why);return promotionDecision(t,cid,patternId,"CANDIDATE_READY","SHADOW","APPROVED",List.of("HUMAN_GOVERNANCE_PROMOTED_TO_SHADOW","FAST_PATH_NOT_ACTIVE"));}

    @Transactional(readOnly=true)
    public List<RoutingPattern> patterns(String tenantId,String status,int limit){String t=tenant(tenantId);bind(t);MapSqlParameterSource p=new MapSqlParameterSource("tenant",t).addValue("limit",limit(limit));String w=" where tenant_id=:tenant";if(!blank(status)){w+=" and status=:status";p.addValue("status",patternStatus(status));}return jdbc.query("select * from routing_patterns"+w+" order by updated_at desc,pattern_id desc limit :limit",p,new PatternMapper());}

    @Transactional(readOnly=true)
    public List<RoutingPatternVersion> patternVersions(String tenantId,String patternId){String t=tenant(tenantId);bind(t);return jdbc.query("select * from routing_pattern_versions where tenant_id=:tenant and pattern_id=:id order by version desc",new MapSqlParameterSource("tenant",t).addValue("id",required(patternId,"patternId")),(rs,n)->new RoutingPatternVersion(t,rs.getString("pattern_id"),rs.getInt("version"),readMap(rs.getString("snapshot_json")),rs.getString("change_reason"),rs.getString("actor_ref"),rs.getObject("created_at",OffsetDateTime.class)));}

    @Transactional
    public PatternQualitySnapshot refreshQuality(String tenantId,String patternId){String t=tenant(tenantId);bind(t);RoutingPattern pattern=requirePattern(t,patternId);LearningPolicy p=requirePolicyVersionCurrent(t,pattern);return refreshQualityAgainstPolicy(t,pattern,p);}

    @Transactional
    public PatternPromotionDecision transitionPattern(String tenantId,String patternId,PatternPromotionRequest req){String t=tenant(tenantId);bind(t);if(req==null)throw new IllegalArgumentException("Pattern transition request is required");RoutingPattern pattern=requirePattern(t,patternId);String target=patternStatus(required(req.targetStatus(),"targetStatus")),why=required(req.reason(),"reason");List<String> reasons=new ArrayList<>();if("ACTIVE".equals(target)){if(!"SHADOW".equals(pattern.status()))reasons.add("ACTIVE_REQUIRES_SHADOW");LearningPolicy p=requirePolicyVersionCurrent(t,pattern);PatternQualitySnapshot q=latestQuality(t,patternId).orElseGet(()->refreshQuality(t,patternId));if(q.sampleCount()<p.minShadowSamples())reasons.add("MIN_SHADOW_SAMPLES_NOT_MET");if(q.successRate()<p.minActiveSuccessRate())reasons.add("MIN_ACTIVE_SUCCESS_RATE_NOT_MET");if(q.humanAcceptanceRate()<p.minActiveHumanAcceptanceRate())reasons.add("MIN_ACTIVE_HUMAN_ACCEPTANCE_NOT_MET");if(p.maxP95LatencyMs()!=null&&q.p95LatencyMs()!=null&&q.p95LatencyMs()>p.maxP95LatencyMs())reasons.add("MAX_P95_LATENCY_EXCEEDED");for(String cap:pattern.capabilityKeys())if(!canonicalKeyActive(t,cap))reasons.add("CAPABILITY_DRIFT:"+cap);}
        else if("SHADOW".equals(target)){if(!"DEGRADED".equals(pattern.status()))reasons.add("RESHADOW_REQUIRES_DEGRADED");}
        else if(!"RETIRED".equals(target))reasons.add("UNSUPPORTED_HUMAN_TRANSITION");if(!reasons.isEmpty())return promotionDecision(t,pattern.candidateId(),patternId,pattern.status(),target,"REJECTED",reasons);OffsetDateTime now=OffsetDateTime.now();int v=pattern.version()+1;LearningPolicy currentPolicy="SHADOW".equals(target)?requireActivePolicy(t):null;jdbc.update("update routing_patterns set status=:status,version=:version,learning_policy_id=case when :status='SHADOW' then :policy else learning_policy_id end,learning_policy_version=case when :status='SHADOW' then :policyVersion else learning_policy_version end,activated_at=case when :status='ACTIVE' then :at else activated_at end,degraded_at=case when :status='DEGRADED' then :at when :status='SHADOW' then null else degraded_at end,updated_at=:at where tenant_id=:tenant and pattern_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",patternId).addValue("status",target).addValue("version",v).addValue("policy",currentPolicy==null?pattern.learningPolicyId():currentPolicy.policyId()).addValue("policyVersion",currentPolicy==null?pattern.learningPolicyVersion():currentPolicy.version()).addValue("at",now));RoutingPattern saved=requirePattern(t,patternId);appendPatternVersion(saved,why);return promotionDecision(t,saved.candidateId(),patternId,pattern.status(),target,"APPROVED",List.of("HUMAN_GOVERNANCE_TRANSITION","FAST_PATH_STEP_GOVERNANCE_STILL_REQUIRED"));}

    @Transactional
    public DriftObservation evaluateDrift(String tenantId,String patternId){String t=tenant(tenantId);bind(t);RoutingPattern pattern=requirePattern(t,patternId);List<String> reasons=new ArrayList<>();LearningPolicy current=activePolicy(t).orElse(null);LearningPolicy p=current;if(current==null||!current.policyId().equals(pattern.learningPolicyId())||current.version()!=pattern.learningPolicyVersion())reasons.add("LEARNING_POLICY_DRIFT");PatternQualitySnapshot q;if(current==null){q=latestQuality(t,patternId).orElse(new PatternQualitySnapshot("none",t,patternId,1,0,0,0,null,List.of(),OffsetDateTime.now()));}else{q=refreshQualityAgainstPolicy(t,pattern,current);}if(q.sampleCount()==0)reasons.add("NO_POST_PROMOTION_OUTCOME_EVIDENCE");else if(p!=null){if(q.successRate()<p.minActiveSuccessRate())reasons.add("SUCCESS_RATE_DRIFT");if(q.humanAcceptanceRate()<p.minActiveHumanAcceptanceRate())reasons.add("HUMAN_ACCEPTANCE_DRIFT");if(p.maxP95LatencyMs()!=null&&q.p95LatencyMs()!=null&&q.p95LatencyMs()>p.maxP95LatencyMs())reasons.add("LATENCY_DRIFT");}for(String cap:pattern.capabilityKeys())if(!canonicalKeyActive(t,cap))reasons.add("CAPABILITY_DRIFT:"+cap);String result=q.sampleCount()==0&&reasons.size()==1&&reasons.contains("NO_POST_PROMOTION_OUTCOME_EVIDENCE")?"INSUFFICIENT_EVIDENCE":reasons.isEmpty()?"NO_DRIFT":"DRIFT_DETECTED";boolean degraded=false;if("DRIFT_DETECTED".equals(result)&&"ACTIVE".equals(pattern.status())){jdbc.update("update routing_patterns set status='DEGRADED',version=version+1,degraded_at=:at,updated_at=:at where tenant_id=:tenant and pattern_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",patternId).addValue("at",OffsetDateTime.now()));appendPatternVersion(requirePattern(t,patternId),"AUTOMATIC_FAIL_SAFE_DRIFT_DEGRADATION");degraded=true;reasons.add("ACTIVE_PATTERN_AUTOMATICALLY_DEGRADED");}String did="drift-"+UUID.randomUUID();jdbc.update("insert into pattern_drift_observations(tenant_id,drift_id,pattern_id,result,reason_codes_json,quality_snapshot_id,pattern_degraded,observed_at) values(:tenant,:did,:pattern,:result,cast(:reasons as jsonb),:quality,:degraded,:at)",new MapSqlParameterSource("tenant",t).addValue("did",did).addValue("pattern",patternId).addValue("result",result).addValue("reasons",write(reasons)).addValue("quality","none".equals(q.snapshotId())?null:q.snapshotId()).addValue("degraded",degraded).addValue("at",OffsetDateTime.now()));return latestDrift(t,patternId).orElseThrow();}

    @Transactional
    public FastPathResolutionDecision resolveFastPath(String tenantId,FastPathResolutionRequest req){String t=tenant(tenantId);bind(t);if(req==null)throw new IllegalArgumentException("Fast Path resolution request is required");if(req.requiredCapabilities()==null||req.requiredCapabilities().isEmpty())throw new IllegalArgumentException("requiredCapabilities must not be empty");List<String> keys=new ArrayList<>();for(CapabilityRequirement r:req.requiredCapabilities()){if(r==null)continue;String code=required(r.capabilityCode(),"capabilityCode"),op=required(r.operation(),"operation").toUpperCase(Locale.ROOT);validateCanonicalCapability(t,code,op);keys.add(code+"#"+op);}Collections.sort(keys);String sig=signature(req.classification(),keys);List<RoutingPattern> matches=jdbc.query("select * from routing_patterns where tenant_id=:tenant and problem_signature=:signature and status='ACTIVE'",new MapSqlParameterSource("tenant",t).addValue("signature",sig),new PatternMapper());String result;RoutingPattern p=null;List<String> reasons=new ArrayList<>();if(matches.isEmpty()){result="NO_ACTIVE_PATTERN";reasons.add("FALLBACK_ADAPTIVE_PATH");}else if(matches.size()>1){result="PATTERN_STALE";reasons.add("MULTIPLE_ACTIVE_PATTERNS_FAIL_CLOSED");}else{p=matches.get(0);boolean stale=false;LearningPolicy current=activePolicy(t).orElse(null);if(current==null||!current.policyId().equals(p.learningPolicyId())||current.version()!=p.learningPolicyVersion()){stale=true;reasons.add("LEARNING_POLICY_DRIFT");}for(String key:p.capabilityKeys())if(!canonicalKeyActive(t,key)){stale=true;reasons.add("CAPABILITY_DRIFT:"+key);}if(stale){result="PATTERN_STALE";degradeForStaleFastPath(t,p,"FAST_PATH_CAPABILITY_DRIFT");reasons.add("FALLBACK_ADAPTIVE_PATH");p=null;}else{result="ACTIVE_PATTERN_MATCHED";reasons.add("TRIAGE_AND_PLANNER_MAY_BE_SKIPPED");reasons.add("WHO_MAY_WHO_SHOULD_HOW_REMAIN_MANDATORY_PER_STEP");}}
        String did="fast-path-"+UUID.randomUUID();jdbc.update("insert into fast_path_resolution_decisions(tenant_id,decision_id,problem_signature,result,pattern_id,pattern_version,plan_template_json,reason_codes_json,decided_at) values(:tenant,:did,:signature,:result,:pattern,:version,cast(:plan as jsonb),cast(:reasons as jsonb),:at)",new MapSqlParameterSource("tenant",t).addValue("did",did).addValue("signature",sig).addValue("result",result).addValue("pattern",p==null?null:p.patternId()).addValue("version",p==null?null:p.version()).addValue("plan",p==null?null:write(p.planTemplate())).addValue("reasons",write(reasons)).addValue("at",OffsetDateTime.now()));return new FastPathResolutionDecision(did,t,sig,result,p==null?null:p.patternId(),p==null?null:p.version(),p==null?Map.of():p.planTemplate(),reasons,OffsetDateTime.now());}

    @Transactional(readOnly=true) public List<PatternPromotionDecision> promotionDecisions(String tenantId,int limit){String t=tenant(tenantId);bind(t);return jdbc.query("select * from pattern_promotion_decisions where tenant_id=:tenant order by decided_at desc,decision_id desc limit :limit",new MapSqlParameterSource("tenant",t).addValue("limit",limit(limit)),(rs,n)->new PatternPromotionDecision(rs.getString("decision_id"),t,rs.getString("candidate_id"),rs.getString("pattern_id"),rs.getString("from_status"),rs.getString("requested_status"),rs.getString("result"),readStrings(rs.getString("reason_codes_json")),rs.getString("actor_ref"),rs.getObject("decided_at",OffsetDateTime.class)));}
    @Transactional(readOnly=true) public List<PatternQualitySnapshot> qualitySnapshots(String tenantId,String patternId,int limit){String t=tenant(tenantId);bind(t);return jdbc.query("select * from pattern_quality_snapshots where tenant_id=:tenant and pattern_id=:id order by observed_at desc,snapshot_id desc limit :limit",new MapSqlParameterSource("tenant",t).addValue("id",required(patternId,"patternId")).addValue("limit",limit(limit)),new QualityMapper());}
    @Transactional(readOnly=true) public List<DriftObservation> driftObservations(String tenantId,String patternId,int limit){String t=tenant(tenantId);bind(t);return jdbc.query("select * from pattern_drift_observations where tenant_id=:tenant and pattern_id=:id order by observed_at desc,drift_id desc limit :limit",new MapSqlParameterSource("tenant",t).addValue("id",required(patternId,"patternId")).addValue("limit",limit(limit)),new DriftMapper());}

    private PatternQualitySnapshot refreshQualityAgainstPolicy(String t,RoutingPattern pattern,LearningPolicy p){List<ExecutionOutcomeEvidence> outs=jdbc.query("select * from execution_outcome_evidence where tenant_id=:tenant and problem_signature=:signature and recorded_at>=:since order by recorded_at desc,outcome_id desc limit :limit",new MapSqlParameterSource("tenant",t).addValue("signature",pattern.problemSignature()).addValue("since",pattern.createdAt()).addValue("limit",p.driftWindowSize()),new OutcomeMapper());int n=outs.size(),success=0,accepted=0;List<Long> lat=new ArrayList<>();for(var o:outs){if(o.executionSucceeded())success++;if(o.humanAccepted())accepted++;if(o.latencyMs()!=null)lat.add(o.latencyMs());}String sid="quality-"+UUID.randomUUID();Long p95=p95(lat);jdbc.update("insert into pattern_quality_snapshots(tenant_id,snapshot_id,pattern_id,window_size,sample_count,success_rate,human_acceptance_rate,p95_latency_ms,outcome_ids_json,observed_at) values(:tenant,:sid,:pattern,:window,:samples,:success,:acceptance,:p95,cast(:ids as jsonb),:at)",new MapSqlParameterSource("tenant",t).addValue("sid",sid).addValue("pattern",pattern.patternId()).addValue("window",p.driftWindowSize()).addValue("samples",n).addValue("success",rate(success,n)).addValue("acceptance",rate(accepted,n)).addValue("p95",p95).addValue("ids",write(outs.stream().map(ExecutionOutcomeEvidence::outcomeId).toList())).addValue("at",OffsetDateTime.now()));return latestQuality(t,pattern.patternId()).orElseThrow();}

    private void refreshCandidate(String t,ExecutionOutcomeEvidence out,Map<String,Object> template){List<ExecutionOutcomeEvidence> all=jdbc.query("select * from execution_outcome_evidence where tenant_id=:tenant and problem_signature=:signature order by recorded_at",new MapSqlParameterSource("tenant",t).addValue("signature",out.problemSignature()),new OutcomeMapper());int n=all.size(),success=0,accept=0;List<Long> lat=new ArrayList<>();List<String> cases=new ArrayList<>();for(var o:all){if(o.executionSucceeded())success++;if(o.humanAccepted())accept++;if(o.latencyMs()!=null)lat.add(o.latencyMs());cases.add(o.caseId());}RoutingPatternCandidate old=findCandidateBySignature(t,out.problemSignature()).orElse(null);boolean samePlan=old==null||Objects.equals(old.planTemplate(),template);if(old!=null&&"AMBIGUOUS_PLAN".equals(old.status()))samePlan=false;LearningPolicy p=activePolicy(t).orElse(null);String status="OBSERVING";if(!samePlan)status="AMBIGUOUS_PLAN";else if(p!=null&&n>=p.minCandidateSamples()&&rate(success,n)>=p.minCandidateSuccessRate()&&rate(accept,n)>=p.minCandidateHumanAcceptanceRate()&&(p.maxP95LatencyMs()==null||p95(lat)==null||p95(lat)<=p.maxP95LatencyMs()))status="CANDIDATE_READY";String id=old==null?"candidate-"+UUID.randomUUID():old.candidateId();OffsetDateTime first=old==null?out.recordedAt():old.firstObservedAt();jdbc.update("""
        insert into routing_pattern_candidates(tenant_id,candidate_id,problem_signature,signature_version,classification,capability_keys_json,plan_template_json,sample_count,success_rate,human_acceptance_rate,p95_latency_ms,status,evidence_case_ids_json,first_observed_at,last_observed_at)
        values(:tenant,:id,:signature,:sv,:classification,cast(:keys as jsonb),cast(:plan as jsonb),:n,:success,:accept,:p95,:status,cast(:cases as jsonb),:first,:last)
        on conflict(tenant_id,problem_signature) do update set sample_count=excluded.sample_count,success_rate=excluded.success_rate,human_acceptance_rate=excluded.human_acceptance_rate,p95_latency_ms=excluded.p95_latency_ms,status=case when routing_pattern_candidates.status='PROMOTED' then 'PROMOTED' else excluded.status end,evidence_case_ids_json=excluded.evidence_case_ids_json,last_observed_at=excluded.last_observed_at
        """,new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("signature",out.problemSignature()).addValue("sv",SIGNATURE_VERSION).addValue("classification",out.classification()).addValue("keys",write(out.capabilityKeys())).addValue("plan",write(old==null?template:old.planTemplate())).addValue("n",n).addValue("success",rate(success,n)).addValue("accept",rate(accept,n)).addValue("p95",p95(lat)).addValue("status",status).addValue("cases",write(cases)).addValue("first",first).addValue("last",out.recordedAt()));}

    private Map<String,Object> planTemplate(String t,String plan,int rev){List<RawPlanStep> raw=jdbc.query("select step_id,capability_requirement_json,depends_on_json,purpose,required,sequence_hint from execution_plan_revision_steps where tenant_id=:tenant and plan_id=:plan and revision=:revision order by coalesce(sequence_hint,2147483647),step_id",new MapSqlParameterSource("tenant",t).addValue("plan",plan).addValue("revision",rev),(rs,n)->new RawPlanStep(rs.getString("step_id"),readMap(rs.getString("capability_requirement_json")),readStrings(rs.getString("depends_on_json")),rs.getString("purpose"),rs.getBoolean("required"),(Integer)rs.getObject("sequence_hint")));if(raw.isEmpty())throw new IllegalArgumentException("Plan revision has no semantic steps");Map<String,String> stable=new LinkedHashMap<>();for(int i=0;i<raw.size();i++)stable.put(raw.get(i).stepId(),String.format(Locale.ROOT,"S%03d",i+1));List<Map<String,Object>> steps=new ArrayList<>();for(RawPlanStep r:raw){Map<String,Object> m=new LinkedHashMap<>();m.put("stepId",stable.get(r.stepId()));m.put("requiredCapability",r.requirement());m.put("dependsOn",r.dependsOn().stream().map(d->stable.getOrDefault(d,"UNKNOWN_DEPENDENCY")).sorted().toList());m.put("purpose",r.purpose());m.put("required",r.required());if(r.sequenceHint()!=null)m.put("sequenceHint",r.sequenceHint());steps.add(m);}return Map.of("contract","phase10-semantic-plan-template-v1","steps",steps,"executionRule","EACH_STEP_MUST_REEVALUATE_WHO_MAY_WHO_SHOULD_HOW");}
    private List<String> capabilityKeys(Map<String,Object> template){List<String> out=new ArrayList<>();Object o=template.get("steps");if(o instanceof List<?> l)for(Object x:l)if(x instanceof Map<?,?> m){Object r=m.get("requiredCapability");if(r instanceof Map<?,?> rm){String c=Objects.toString(rm.get("capabilityCode"),"").trim(),op=Objects.toString(rm.get("operation"),"").trim().toUpperCase(Locale.ROOT);if(!c.isBlank()&&!op.isBlank())out.add(c+"#"+op);}}Collections.sort(out);return List.copyOf(out);}
    private String signature(String classification,List<String> keys){try{String base=Objects.toString(classification,"").trim().toUpperCase(Locale.ROOT)+"|"+String.join("|",new TreeSet<>(keys));byte[] h=MessageDigest.getInstance("SHA-256").digest(base.getBytes(StandardCharsets.UTF_8));return HexFormat.of().formatHex(h);}catch(Exception e){throw new IllegalStateException("Unable to calculate problem signature",e);}}
    private boolean canonicalKeyActive(String t,String key){int i=key.lastIndexOf('#');if(i<=0)return false;String cap=key.substring(0,i),op=key.substring(i+1);try{validateCanonicalCapability(t,cap,op);return true;}catch(IllegalArgumentException e){return false;}}
    private void validateCanonicalCapability(String t,String cap,String op){Integer n=jdbc.queryForObject("select count(*) from capability_definitions where tenant_id=:tenant and capability_code=:cap and status='ACTIVE' and jsonb_exists(operations_json, cast(:op as text))",new MapSqlParameterSource("tenant",t).addValue("cap",cap).addValue("op",op),Integer.class);if(n==null||n!=1)throw new IllegalArgumentException("Canonical Capability is not ACTIVE or operation is unsupported: "+cap+"#"+op);}
    private LearningPolicy requireActivePolicy(String t){return activePolicy(t).orElseThrow(()->new IllegalArgumentException("ACTIVE Learning Policy is required"));}
    private Optional<LearningPolicy> activePolicy(String t){try{return Optional.of(jdbc.queryForObject("select * from learning_policies where tenant_id=:tenant and status='ACTIVE'",new MapSqlParameterSource("tenant",t),new LearningPolicyMapper()));}catch(EmptyResultDataAccessException e){return Optional.empty();}}
    private LearningPolicy requirePolicyVersionCurrent(String t,RoutingPattern pattern){LearningPolicy p=requireActivePolicy(t);if(!p.policyId().equals(pattern.learningPolicyId())||p.version()!=pattern.learningPolicyVersion())throw new IllegalArgumentException("Pattern Learning Policy evidence is stale; return pattern to SHADOW under current policy");return p;}
    private Optional<LearningPolicy> findPolicy(String t,String id){try{return Optional.of(jdbc.queryForObject("select * from learning_policies where tenant_id=:tenant and policy_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",id),new LearningPolicyMapper()));}catch(EmptyResultDataAccessException e){return Optional.empty();}}
    private RoutingPatternCandidate requireCandidate(String t,String id){try{return jdbc.queryForObject("select * from routing_pattern_candidates where tenant_id=:tenant and candidate_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",id),new CandidateMapper());}catch(EmptyResultDataAccessException e){throw new IllegalArgumentException("Routing Pattern Candidate not found: "+id);}}
    private Optional<RoutingPatternCandidate> findCandidateBySignature(String t,String sig){try{return Optional.of(jdbc.queryForObject("select * from routing_pattern_candidates where tenant_id=:tenant and problem_signature=:signature",new MapSqlParameterSource("tenant",t).addValue("signature",sig),new CandidateMapper()));}catch(EmptyResultDataAccessException e){return Optional.empty();}}
    private RoutingPattern requirePattern(String t,String id){try{return jdbc.queryForObject("select * from routing_patterns where tenant_id=:tenant and pattern_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",id),new PatternMapper());}catch(EmptyResultDataAccessException e){throw new IllegalArgumentException("Routing Pattern not found: "+id);}}
    private Optional<ExecutionOutcomeEvidence> findOutcomeByCase(String t,String cid){try{return Optional.of(jdbc.queryForObject("select * from execution_outcome_evidence where tenant_id=:tenant and case_id=:case",new MapSqlParameterSource("tenant",t).addValue("case",cid),new OutcomeMapper()));}catch(EmptyResultDataAccessException e){return Optional.empty();}}
    private Optional<PatternQualitySnapshot> latestQuality(String t,String pattern){try{return Optional.of(jdbc.queryForObject("select * from pattern_quality_snapshots where tenant_id=:tenant and pattern_id=:id order by observed_at desc,snapshot_id desc limit 1",new MapSqlParameterSource("tenant",t).addValue("id",pattern),new QualityMapper()));}catch(EmptyResultDataAccessException e){return Optional.empty();}}
    private Optional<DriftObservation> latestDrift(String t,String pattern){try{return Optional.of(jdbc.queryForObject("select * from pattern_drift_observations where tenant_id=:tenant and pattern_id=:id order by observed_at desc,drift_id desc limit 1",new MapSqlParameterSource("tenant",t).addValue("id",pattern),new DriftMapper()));}catch(EmptyResultDataAccessException e){return Optional.empty();}}
    private PatternPromotionDecision promotionDecision(String t,String candidate,String pattern,String from,String target,String result,List<String> reasons){String id="promotion-"+UUID.randomUUID();OffsetDateTime at=OffsetDateTime.now();jdbc.update("insert into pattern_promotion_decisions(tenant_id,decision_id,candidate_id,pattern_id,from_status,requested_status,result,reason_codes_json,actor_ref,decided_at) values(:tenant,:id,:candidate,:pattern,:from,:target,:result,cast(:reasons as jsonb),:actor,:at)",new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("candidate",candidate).addValue("pattern",pattern).addValue("from",from).addValue("target",target).addValue("result",result).addValue("reasons",write(reasons)).addValue("actor",actor()).addValue("at",at));return new PatternPromotionDecision(id,t,candidate,pattern,from,target,result,reasons,actor(),at);}
    private void degradePatternsForPolicyChange(String t,String policyId,int currentVersion,String reason){List<RoutingPattern> affected=jdbc.query("select * from routing_patterns where tenant_id=:tenant and learning_policy_id=:policy and status in ('SHADOW','ACTIVE')",new MapSqlParameterSource("tenant",t).addValue("policy",policyId),new PatternMapper());for(RoutingPattern p:affected){OffsetDateTime at=OffsetDateTime.now();jdbc.update("update routing_patterns set status='DEGRADED',version=version+1,degraded_at=:at,updated_at=:at where tenant_id=:tenant and pattern_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",p.patternId()).addValue("at",at));appendPatternVersion(requirePattern(t,p.patternId()),reason+"; currentPolicyVersion="+currentVersion);}}

    private void degradeForStaleFastPath(String t,RoutingPattern p,String reason){if(!"ACTIVE".equals(p.status()))return;OffsetDateTime at=OffsetDateTime.now();jdbc.update("update routing_patterns set status='DEGRADED',version=version+1,degraded_at=:at,updated_at=:at where tenant_id=:tenant and pattern_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",p.patternId()).addValue("at",at));appendPatternVersion(requirePattern(t,p.patternId()),reason);}
    private void appendPolicyVersion(LearningPolicy p,String reason){jdbc.update("insert into learning_policy_versions(tenant_id,policy_id,version,snapshot_json,change_reason,actor_ref,created_at) values(:tenant,:id,:version,cast(:snapshot as jsonb),:reason,:actor,:at)",new MapSqlParameterSource("tenant",p.tenantId()).addValue("id",p.policyId()).addValue("version",p.version()).addValue("snapshot",write(p)).addValue("reason",required(reason,"changeReason")).addValue("actor",actor()).addValue("at",OffsetDateTime.now()));}
    private void appendPatternVersion(RoutingPattern p,String reason){jdbc.update("insert into routing_pattern_versions(tenant_id,pattern_id,version,snapshot_json,change_reason,actor_ref,created_at) values(:tenant,:id,:version,cast(:snapshot as jsonb),:reason,:actor,:at)",new MapSqlParameterSource("tenant",p.tenantId()).addValue("id",p.patternId()).addValue("version",p.version()).addValue("snapshot",write(p)).addValue("reason",required(reason,"changeReason")).addValue("actor",actor()).addValue("at",OffsetDateTime.now()));}
    private Map<String,Object> one(String sql,String t,String id){try{return jdbc.queryForMap(sql,new MapSqlParameterSource("tenant",t).addValue("id",id));}catch(EmptyResultDataAccessException e){throw new IllegalArgumentException("Referenced authoritative record not found: "+id);}}
    private void validatePolicy(LearningPolicy p){if(!p.requireHumanApprovalForPromotion())throw new IllegalArgumentException("Phase 10 requires Human Governance for every pattern promotion");if(p.minCandidateSamples()<1||p.minShadowSamples()<1||p.driftWindowSize()<1)throw new IllegalArgumentException("Learning sample/window limits must be >= 1");for(double d:List.of(p.minCandidateSuccessRate(),p.minCandidateHumanAcceptanceRate(),p.minActiveSuccessRate(),p.minActiveHumanAcceptanceRate()))if(d<0||d>1)throw new IllegalArgumentException("Learning rates must be between 0 and 1");if(p.maxP95LatencyMs()!=null&&p.maxP95LatencyMs()<0)throw new IllegalArgumentException("maxP95LatencyMs must be >= 0");}
    private String policyStatus(String s){String v=blank(s)?"DRAFT":s.trim().toUpperCase(Locale.ROOT);if(!POLICY_STATUSES.contains(v))throw new IllegalArgumentException("Unsupported Learning Policy status: "+v);return v;}
    private String patternStatus(String s){String v=required(s,"status").toUpperCase(Locale.ROOT);if(!PATTERN_STATUSES.contains(v))throw new IllegalArgumentException("Unsupported Routing Pattern status: "+v);return v;}
    private String tenant(String s){return required(s,"tenantId");} private void bind(String t){IamTenantContextHolder.current().ifPresent(c->{if(!t.equals(c.tenantId()))throw new IllegalArgumentException("Tenant mismatch");});}
    private String actor(){IamTenantExecutionContext c=IamTenantContextHolder.current().orElse(null);return c==null||blank(c.actorId())?"learning-fast-path":c.actorId();}
    private int limit(int n){return Math.max(1,Math.min(n,500));} private boolean blank(String s){return s==null||s.isBlank();} private String required(String s,String n){if(blank(s))throw new IllegalArgumentException(n+" is required");return s.trim();} private String first(String a,String b){return !blank(a)?a:b;} private String str(Map<String,Object> m,String k){Object v=m.get(k);return v==null?null:v.toString();}
    private double rate(int n,int d){return d==0?0d:((double)n)/d;} private Long p95(List<Long> xs){if(xs==null||xs.isEmpty())return null;List<Long> a=new ArrayList<>(xs);Collections.sort(a);int i=(int)Math.ceil(a.size()*0.95)-1;return a.get(Math.max(0,Math.min(i,a.size()-1)));}
    private String write(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new IllegalArgumentException("Unable to serialize evidence",e);}} private Map<String,Object> readMap(String s){try{return s==null?Map.of():json.readValue(s,MAP);}catch(Exception e){throw new IllegalArgumentException("Invalid JSON evidence",e);}} private List<String> readStrings(String s){try{return s==null?List.of():json.readValue(s,STRINGS);}catch(Exception e){throw new IllegalArgumentException("Invalid JSON array evidence",e);}}

    private record RawPlanStep(String stepId,Map<String,Object> requirement,List<String> dependsOn,String purpose,boolean required,Integer sequenceHint){}
    private static final class LearningPolicyMapper implements RowMapper<LearningPolicy>{public LearningPolicy mapRow(ResultSet r,int n)throws SQLException{return new LearningPolicy(r.getString("policy_id"),r.getString("tenant_id"),r.getString("display_name"),r.getInt("min_candidate_samples"),r.getDouble("min_candidate_success_rate"),r.getDouble("min_candidate_human_acceptance_rate"),r.getInt("min_shadow_samples"),r.getDouble("min_active_success_rate"),r.getDouble("min_active_human_acceptance_rate"),(Long)r.getObject("max_p95_latency_ms"),r.getInt("drift_window_size"),r.getBoolean("require_human_approval_for_promotion"),r.getString("status"),r.getInt("version"),r.getObject("created_at",OffsetDateTime.class),r.getObject("updated_at",OffsetDateTime.class));}}
    private final class OutcomeMapper implements RowMapper<ExecutionOutcomeEvidence>{public ExecutionOutcomeEvidence mapRow(ResultSet r,int n)throws SQLException{return new ExecutionOutcomeEvidence(r.getString("outcome_id"),r.getString("tenant_id"),r.getString("case_id"),r.getString("run_id"),r.getString("plan_id"),r.getInt("plan_revision"),r.getString("problem_signature"),r.getString("signature_version"),r.getString("classification"),readStrings(r.getString("capability_keys_json")),r.getBoolean("execution_succeeded"),r.getBoolean("human_accepted"),(Long)r.getObject("latency_ms"),(Long)r.getObject("token_usage"),r.getObject("estimated_cost")==null?null:((Number)r.getObject("estimated_cost")).doubleValue(),r.getString("human_decision"),r.getString("accountable_ref"),r.getObject("recorded_at",OffsetDateTime.class));}}
    private final class CandidateMapper implements RowMapper<RoutingPatternCandidate>{public RoutingPatternCandidate mapRow(ResultSet r,int n)throws SQLException{return new RoutingPatternCandidate(r.getString("candidate_id"),r.getString("tenant_id"),r.getString("problem_signature"),r.getString("signature_version"),r.getString("classification"),readStrings(r.getString("capability_keys_json")),readMap(r.getString("plan_template_json")),r.getInt("sample_count"),r.getDouble("success_rate"),r.getDouble("human_acceptance_rate"),(Long)r.getObject("p95_latency_ms"),r.getString("status"),readStrings(r.getString("evidence_case_ids_json")),r.getObject("first_observed_at",OffsetDateTime.class),r.getObject("last_observed_at",OffsetDateTime.class));}}
    private final class PatternMapper implements RowMapper<RoutingPattern>{public RoutingPattern mapRow(ResultSet r,int n)throws SQLException{return new RoutingPattern(r.getString("pattern_id"),r.getString("tenant_id"),r.getString("candidate_id"),r.getString("problem_signature"),r.getString("signature_version"),r.getString("classification"),readStrings(r.getString("capability_keys_json")),readMap(r.getString("plan_template_json")),r.getString("status"),r.getInt("version"),r.getString("learning_policy_id"),r.getInt("learning_policy_version"),r.getObject("activated_at",OffsetDateTime.class),r.getObject("degraded_at",OffsetDateTime.class),r.getObject("created_at",OffsetDateTime.class),r.getObject("updated_at",OffsetDateTime.class));}}
    private final class QualityMapper implements RowMapper<PatternQualitySnapshot>{public PatternQualitySnapshot mapRow(ResultSet r,int n)throws SQLException{return new PatternQualitySnapshot(r.getString("snapshot_id"),r.getString("tenant_id"),r.getString("pattern_id"),r.getInt("window_size"),r.getInt("sample_count"),r.getDouble("success_rate"),r.getDouble("human_acceptance_rate"),(Long)r.getObject("p95_latency_ms"),readStrings(r.getString("outcome_ids_json")),r.getObject("observed_at",OffsetDateTime.class));}}
    private final class DriftMapper implements RowMapper<DriftObservation>{public DriftObservation mapRow(ResultSet r,int n)throws SQLException{return new DriftObservation(r.getString("drift_id"),r.getString("tenant_id"),r.getString("pattern_id"),r.getString("result"),readStrings(r.getString("reason_codes_json")),r.getString("quality_snapshot_id"),r.getBoolean("pattern_degraded"),r.getObject("observed_at",OffsetDateTime.class));}}
}
