package com.opensocket.aievent.core.capability;

import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantContextHolder;
import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantExecutionContext;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

/**
 * MRS A0-R5 Plan Admission authority.
 *
 * <p>This service authorizes the maximum binding boundary that a frozen Plan Step may enter.
 * It never ranks providers, selects a runtime instance, creates an Assignment, chooses HOW,
 * or sends network I/O. Runtime callers must stay inside the resulting step-scoped envelope.</p>
 */
@Service
public class PlanAdmissionService {
    private static final Set<String> POLICY_STATUS=Set.of("DRAFT","ACTIVE","DISABLED","RETIRED");
    private static final Set<String> BINDING_CLASSES=Set.of("LOCAL_DETERMINISTIC","LOCAL_AGENT","EXTERNAL_TOOL","EXTERNAL_AGENT");
    private static final Set<String> SIDE_EFFECTS=Set.of("NONE","READ","WRITE");
    private static final List<String> SENSITIVITY=List.of("PUBLIC","INTERNAL","CONFIDENTIAL","RESTRICTED","CRITICAL");
    private static final TypeReference<List<String>> STRING_LIST=new TypeReference<>(){};
    private static final TypeReference<Map<String,Object>> OBJECT_MAP=new TypeReference<>(){};

    private final NamedParameterJdbcTemplate jdbc;
    private final ObjectMapper json;
    private final DelegationGovernanceService delegation;

    public PlanAdmissionService(NamedParameterJdbcTemplate jdbc,ObjectMapper json,DelegationGovernanceService delegation){
        this.jdbc=jdbc;this.json=json;this.delegation=delegation;
    }

    @Transactional(readOnly=true)
    public List<PlanAdmissionPolicy> listPolicies(String tenantId,String status,int limit){
        String t=tenant(tenantId);bind(t);MapSqlParameterSource p=new MapSqlParameterSource("tenant",t).addValue("limit",Math.max(1,Math.min(limit<=0?100:limit,500)));
        String w=" where tenant_id=:tenant";if(!blank(status)){w+=" and status=:status";p.addValue("status",policyStatus(status));}
        return jdbc.query("select * from plan_admission_policies"+w+" order by policy_id limit :limit",p,(rs,n)->policy(rs));
    }

    @Transactional
    public PlanAdmissionPolicy upsertPolicy(String tenantId,String policyId,PlanAdmissionPolicy request,String reason){
        String t=tenant(tenantId);bind(t);if(request==null)throw new IllegalArgumentException("Plan Admission Policy request body is required");
        String id=required(first(policyId,request.policyId()),"policyId"),status=policyStatus(request.status());
        PlanAdmissionPolicy old=findPolicy(t,id).orElse(null);if(old!=null&&blank(reason))throw new IllegalArgumentException("X-Change-Reason is required when changing an existing Plan Admission Policy");
        if("ACTIVE".equals(status)){Integer c=jdbc.queryForObject("select count(*) from plan_admission_policies where tenant_id=:tenant and status='ACTIVE' and policy_id<>:id",new MapSqlParameterSource("tenant",t).addValue("id",id),Integer.class);if(c!=null&&c>0)throw new IllegalArgumentException("Only one ACTIVE Plan Admission Policy is allowed per Tenant");}
        List<String> classes=normalizeSet(request.allowedBindingClasses(),BINDING_CLASSES,"allowedBindingClasses");
        List<String> data=upperList(request.allowedDataClasses());List<String> regions=trimList(request.allowedRegions());
        String maxSensitivity=normalizeSensitivity(first(request.maxSensitivityLevel(),"INTERNAL"));String maxSideEffect=normalizeSideEffect(first(request.maxSideEffect(),"READ"));
        int candidates=Math.max(1,Math.min(request.maxCandidateBindingsPerStep()<=0?200:request.maxCandidateBindingsPerStep(),5000));long ttl=Math.max(30,Math.min(request.envelopeTtlSeconds()<=0?900:request.envelopeTtlSeconds(),86400));
        int version=old==null?1:old.version()+1;OffsetDateTime now=OffsetDateTime.now(),created=old==null?now:old.createdAt();
        MapSqlParameterSource p=new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("name",required(request.displayName(),"displayName"))
          .addValue("candidates",candidates).addValue("ttl",ttl).addValue("classes",write(classes)).addValue("data",write(data)).addValue("sensitivity",maxSensitivity)
          .addValue("egress",request.externalEgressAllowed()).addValue("regions",write(regions)).addValue("side",maxSideEffect)
          .addValue("security",required(request.securityCeilingRef(),"securityCeilingRef")).addValue("dataPolicy",required(request.dataPolicyRef(),"dataPolicyRef"))
          .addValue("egressPolicy",required(request.egressPolicyRef(),"egressPolicyRef")).addValue("residency",required(request.residencyConstraintRef(),"residencyConstraintRef"))
          .addValue("status",status).addValue("version",version).addValue("created",created).addValue("updated",now);
        jdbc.update("""
          insert into plan_admission_policies(tenant_id,policy_id,display_name,max_candidate_bindings_per_step,envelope_ttl_seconds,allowed_binding_classes_json,allowed_data_classes_json,max_sensitivity_level,external_egress_allowed,allowed_regions_json,max_side_effect,security_ceiling_ref,data_policy_ref,egress_policy_ref,residency_constraint_ref,status,version,created_at,updated_at)
          values(:tenant,:id,:name,:candidates,:ttl,cast(:classes as jsonb),cast(:data as jsonb),:sensitivity,:egress,cast(:regions as jsonb),:side,:security,:dataPolicy,:egressPolicy,:residency,:status,:version,:created,:updated)
          on conflict(tenant_id,policy_id) do update set display_name=excluded.display_name,max_candidate_bindings_per_step=excluded.max_candidate_bindings_per_step,envelope_ttl_seconds=excluded.envelope_ttl_seconds,allowed_binding_classes_json=excluded.allowed_binding_classes_json,allowed_data_classes_json=excluded.allowed_data_classes_json,max_sensitivity_level=excluded.max_sensitivity_level,external_egress_allowed=excluded.external_egress_allowed,allowed_regions_json=excluded.allowed_regions_json,max_side_effect=excluded.max_side_effect,security_ceiling_ref=excluded.security_ceiling_ref,data_policy_ref=excluded.data_policy_ref,egress_policy_ref=excluded.egress_policy_ref,residency_constraint_ref=excluded.residency_constraint_ref,status=excluded.status,version=excluded.version,updated_at=excluded.updated_at
          """,p);
        PlanAdmissionPolicy saved=findPolicy(t,id).orElseThrow();
        jdbc.update("insert into plan_admission_policy_versions(tenant_id,policy_id,version,snapshot_json,change_reason,actor_ref,created_at) values(:tenant,:id,:version,cast(:snapshot as jsonb),:reason,:actor,:at)",new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("version",version).addValue("snapshot",write(saved)).addValue("reason",old==null?"INITIAL_CREATE":reason).addValue("actor",actor()).addValue("at",now));
        if(old!=null){revokePolicyEnvelopes(t,id,old.version(),"PLAN_ADMISSION_POLICY_CHANGED");}
        return saved;
    }

    @Transactional
    public PlanAdmissionResult admit(String tenantId,String planId,Integer requestedRevision){
        String t=tenant(tenantId);bind(t);PlanHeader plan=plan(t,required(planId,"planId"));if(!"SEMANTICALLY_VALIDATED".equals(plan.status()))throw new IllegalArgumentException("Only a SEMANTICALLY_VALIDATED Plan may enter Plan Admission");
        int revision=requestedRevision==null?plan.currentRevision():requestedRevision;if(revision!=plan.currentRevision())throw new IllegalArgumentException("Plan Admission must evaluate the current frozen Plan revision");
        PlanAdmissionPolicy policy=activePolicy(t).orElse(null);List<Step> steps=steps(t,plan.planId(),revision);if(steps.isEmpty())throw new IllegalArgumentException("Validated Plan revision contains no Steps");
        String decisionId="plan-admission-"+UUID.randomUUID();OffsetDateTime now=OffsetDateTime.now();String snapshot=policy==null?null:"plan-admission-policy:"+policy.policyId()+":v"+policy.version();
        if(policy==null){PlanAdmissionDecision d=persistDecision(t,decisionId,plan.planId(),revision,"POLICY_NOT_CONFIGURED",null,steps.size(),0,steps.size(),0,0,0,List.of("PLAN_ADMISSION_POLICY_NOT_CONFIGURED"),now);return new PlanAdmissionResult(d,List.of());}
        RuntimeRequesterContext requester=resolveRequester(t,plan.taskRef(),"plan-admission:"+plan.planId()+":"+revision);
        revokePlanEnvelopes(t,plan.planId(),revision,"SUPERSEDED_BY_READMISSION");
        int admittedSteps=0,deniedSteps=0,waitingSteps=0,candidateCount=0,admittedCount=0;List<String> overallReasons=new ArrayList<>();List<StepDecision> stepDecisions=new ArrayList<>();
        for(Step s:steps){StepDecision sd=evaluateStep(t,plan,revision,s,policy,requester,decisionId);stepDecisions.add(sd);candidateCount+=sd.evaluations().size();admittedCount+=sd.admitted().size();if(!sd.admitted().isEmpty())admittedSteps++;else if(sd.waiting())waitingSteps++;else deniedSteps++;overallReasons.addAll(sd.stepReasons());}
        String result=deniedSteps>0?"DENIED":waitingSteps>0?"WAITING_APPROVAL":"ADMITTED";
        PlanAdmissionDecision decision=persistDecision(t,decisionId,plan.planId(),revision,result,policy,steps.size(),admittedSteps,deniedSteps,waitingSteps,candidateCount,admittedCount,dedup(overallReasons),now);
        for(StepDecision sd:stepDecisions)persistEvaluations(t,decision,sd);
        List<BindingAuthorizationEnvelope> envelopes=new ArrayList<>();if("ADMITTED".equals(result)){for(StepDecision sd:stepDecisions)envelopes.add(issueEnvelope(t,decision,policy,sd,now));}
        return new PlanAdmissionResult(decision,envelopes);
    }

    @Transactional(readOnly=true)
    public List<PlanAdmissionDecision> decisions(String tenantId,String planId,int limit){String t=tenant(tenantId);bind(t);return jdbc.query("select * from plan_admission_decisions where tenant_id=:tenant and plan_id=:plan order by decided_at desc,decision_id desc limit :limit",new MapSqlParameterSource("tenant",t).addValue("plan",required(planId,"planId")).addValue("limit",Math.max(1,Math.min(limit<=0?100:limit,500))),(rs,n)->decision(rs));}
    @Transactional(readOnly=true)
    public List<BindingAuthorizationEnvelope> envelopes(String tenantId,String planId,Integer revision){String t=tenant(tenantId);bind(t);MapSqlParameterSource p=new MapSqlParameterSource("tenant",t).addValue("plan",required(planId,"planId"));String w=" where tenant_id=:tenant and plan_id=:plan";if(revision!=null){w+=" and plan_revision=:revision";p.addValue("revision",revision);}return jdbc.query("select * from binding_authorization_envelopes"+w+" order by plan_revision desc,step_id,envelope_id",p,(rs,n)->envelope(rs));}
    @Transactional(readOnly=true)
    public List<PlanAdmissionBindingEvaluation> evaluations(String tenantId,String decisionId,String stepId,int limit){String t=tenant(tenantId);bind(t);MapSqlParameterSource p=new MapSqlParameterSource("tenant",t).addValue("decision",required(decisionId,"decisionId")).addValue("limit",Math.max(1,Math.min(limit<=0?200:limit,1000)));String w=" where tenant_id=:tenant and decision_id=:decision";if(!blank(stepId)){w+=" and step_id=:step";p.addValue("step",stepId.trim());}return jdbc.query("select * from plan_admission_binding_evaluations"+w+" order by step_id,binding_id limit :limit",p,(rs,n)->evaluation(rs));}

    @Transactional
    public BindingAuthorizationEnvelope revokeEnvelope(String tenantId,String envelopeId,String reason){String t=tenant(tenantId);bind(t);String id=required(envelopeId,"envelopeId"),why=required(reason,"reason");OffsetDateTime at=OffsetDateTime.now();BindingAuthorizationEnvelope before=requireEnvelope(t,id);if(!"ACTIVE".equals(before.status()))return before;jdbc.update("update binding_authorization_envelopes set status='REVOKED',revocation_version=revocation_version+1,authorization_epoch=authorization_epoch+1,revoked_at=:at,revocation_reason=:reason where tenant_id=:tenant and envelope_id=:id and status='ACTIVE'",new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("at",at).addValue("reason",why));BindingAuthorizationEnvelope after=requireEnvelope(t,id);appendEnvelopeEvent(t,after,"REVOKED",before.status(),why,Map.of());return after;}

    @Transactional(readOnly=true)
    public PlanAdmissionDecision requireCurrentAdmission(String tenantId,String planId,int revision){String t=tenant(tenantId);bind(t);try{PlanAdmissionDecision d=jdbc.queryForObject("select * from plan_admission_decisions where tenant_id=:tenant and plan_id=:plan and plan_revision=:revision order by decided_at desc,decision_id desc limit 1",new MapSqlParameterSource("tenant",t).addValue("plan",planId).addValue("revision",revision),(rs,n)->decision(rs));if(d==null||!"ADMITTED".equals(d.result()))throw new IllegalArgumentException("PLAN_ADMISSION_REQUIRED");return d;}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("PLAN_ADMISSION_REQUIRED");}}
    @Transactional(readOnly=true)
    public BindingAuthorizationEnvelope requireActiveEnvelope(String tenantId,String planId,int revision,String stepId){String t=tenant(tenantId);bind(t);try{BindingAuthorizationEnvelope e=jdbc.queryForObject("select e.* from binding_authorization_envelopes e join plan_admission_decisions d on d.tenant_id=e.tenant_id and d.decision_id=e.decision_id where e.tenant_id=:tenant and e.plan_id=:plan and e.plan_revision=:revision and e.step_id=:step and e.status='ACTIVE' and e.valid_until>now() and d.result='ADMITTED' order by e.issued_at desc,e.envelope_id desc limit 1",new MapSqlParameterSource("tenant",t).addValue("plan",planId).addValue("revision",revision).addValue("step",stepId),(rs,n)->envelope(rs));if(e==null)throw new IllegalArgumentException("ACTIVE_BINDING_AUTHORIZATION_ENVELOPE_REQUIRED");return e;}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("ACTIVE_BINDING_AUTHORIZATION_ENVELOPE_REQUIRED");}}
    @Transactional(readOnly=true)
    public List<String> admittedBindingIds(String tenantId,String envelopeId){String t=tenant(tenantId);bind(t);BindingAuthorizationEnvelope e=requireEnvelope(t,envelopeId);if(!"ACTIVE".equals(e.status())||e.validUntil()==null||!e.validUntil().isAfter(OffsetDateTime.now()))throw new IllegalArgumentException("BINDING_AUTHORIZATION_ENVELOPE_NOT_ACTIVE");return e.admittedBindingIds();}
    @Transactional(readOnly=true)
    public void assertBindingAdmitted(String tenantId,String envelopeId,String bindingId,String capabilityCode){String t=tenant(tenantId);bind(t);BindingAuthorizationEnvelope e=requireEnvelope(t,envelopeId);if(!"ACTIVE".equals(e.status())||!e.validUntil().isAfter(OffsetDateTime.now()))throw new IllegalArgumentException("BINDING_AUTHORIZATION_ENVELOPE_NOT_ACTIVE");if(!e.capabilityCode().equals(capabilityCode)||!e.admittedBindingIds().contains(bindingId))throw new IllegalArgumentException("BINDING_OUTSIDE_PLAN_ADMISSION_ENVELOPE");}

    private StepDecision evaluateStep(String t,PlanHeader plan,int revision,Step step,PlanAdmissionPolicy policy,RuntimeRequesterContext requester,String decisionId){
        List<String> hard=new ArrayList<>();CapabilityDef cap=capability(t,step.requirement().capabilityCode());String op=upper(step.requirement().operation());
        if(!"ACTIVE".equals(cap.status()))hard.add("CAPABILITY_NOT_ACTIVE");if(step.requirement().capabilityCode()==null||!cap.code().equals(step.requirement().capabilityCode()))hard.add("CAPABILITY_MISMATCH");if(!cap.operations().isEmpty()&&!cap.operations().contains(op))hard.add("CAPABILITY_OPERATION_NOT_SUPPORTED");
        String dataClass=upper(first(step.requirement().dataClassification(),"INTERNAL"));if(!policy.allowedDataClasses().isEmpty()&&!policy.allowedDataClasses().contains(dataClass))hard.add("DATA_CLASS_NOT_ALLOWED");if(rankSensitivity(first(requester.sensitivityLevel(),dataClass))>rankSensitivity(policy.maxSensitivityLevel()))hard.add("SENSITIVITY_EXCEEDS_PLAN_ADMISSION_POLICY");if(rankSide(step.sideEffect())>rankSide(policy.maxSideEffect()))hard.add("SIDE_EFFECT_EXCEEDS_PLAN_ADMISSION_POLICY");
        if("COMPENSATABLE".equals(step.writeSemantics())&&!compensationValid(t,step.compensationBindingId()))hard.add("COMPENSATION_BINDING_NOT_APPROVED");
        if(!requiredInputPresent(cap.inputSchema(),step.requirement().inputContext()))hard.add("INPUT_SCHEMA_REQUIRED_FIELD_MISSING");
        FlowConstraint flowConstraint=flowConstraint(t,plan.taskRef(),step.requirement().capabilityCode());
        List<Candidate> candidates=candidates(t,step.requirement()).stream().filter(c->flowConstraint.allows(c,bindingClass(c))).toList();
        if(!flowConstraint.allowedPools().isEmpty()) hard.add("FLOW_CANDIDATE_POOL_CONSTRAINT_REQUIRES_ROUTER_SUPPORT");
        if(candidates.size()>policy.maxCandidateBindingsPerStep())hard.add("CANDIDATE_SET_EXCEEDS_PLAN_ADMISSION_POLICY");
        List<CandidateEvaluation> evals=new ArrayList<>();if(!hard.isEmpty()){for(Candidate c:candidates)evaluationsDenied(evals,c,hard);return new StepDecision(step,List.of(),evals,false,dedup(hard));}
        boolean waiting=false;List<CandidateEvaluation> admitted=new ArrayList<>();
        for(Candidate c:candidates){List<String> reasons=new ArrayList<>();String clazz=bindingClass(c),trust=first(str(c.metadata(),"trustDomainRef"),"provider:"+c.providerId()),region=str(c.metadata(),"processingRegion");
            if(!policy.allowedBindingClasses().contains(clazz))reasons.add("BINDING_CLASS_NOT_ALLOWED");if(clazz.startsWith("EXTERNAL")&&!policy.externalEgressAllowed())reasons.add("EXTERNAL_EGRESS_DENIED");if(!policy.allowedRegions().isEmpty()&&(blank(region)||!policy.allowedRegions().contains(region)))reasons.add("PROCESSING_REGION_NOT_ALLOWED");if(!activeExecutionAdapter(t,c.providerId()))reasons.add("ACTIVE_EXECUTION_ADAPTER_REQUIRED");if(clazz.startsWith("EXTERNAL")&&!activeCredential(t,c.providerId()))reasons.add("ACTIVE_EXTERNAL_CREDENTIAL_REQUIRED");
            DelegationAuthorizationDecision auth=null;if(reasons.isEmpty()){auth=delegation.evaluateRuntime(t,new DelegationAuthorizationRequest(step.requirement(),c.bindingId(),requester.principalType(),requester.departmentId(),requester.groupIds(),requester.roleCodes(),"WRITE".equals(step.sideEffect())?"WRITE":"READ",requester.sensitivityLevel(),null,requester.delegationDepth(),requester.agentCalls(),null,0));if("WAITING_APPROVAL".equals(auth.result())){waiting=true;reasons.addAll(auth.reasonCodes());}else if(!"PASS".equals(auth.result()))reasons.addAll(auth.reasonCodes());}
            boolean nonCompensatableWrite="WRITE".equals(step.sideEffect())&&"NON_COMPENSATABLE".equals(step.writeSemantics());
            if(reasons.isEmpty()&&nonCompensatableWrite){waiting=true;reasons.add("NON_COMPENSATABLE_WRITE_REQUIRES_PER_EXECUTION_APPROVAL");}
            String result=reasons.isEmpty()?"ADMITTED":((auth!=null&&"WAITING_APPROVAL".equals(auth.result()))||nonCompensatableWrite)?"WAITING_APPROVAL":"DENIED";CandidateEvaluation ce=new CandidateEvaluation(c,clazz,trust,result,auth==null?null:auth.decisionId(),dedup(reasons));evals.add(ce);if("ADMITTED".equals(result))admitted.add(ce);
        }
        if(admitted.isEmpty()&&evals.stream().anyMatch(e->"WAITING_APPROVAL".equals(e.result())))waiting=true;
        List<String> reasons=admitted.isEmpty()?List.of(waiting?"STEP_WAITING_APPROVAL":"NO_ADMITTED_BINDING"):List.of("STEP_ADMITTED");return new StepDecision(step,admitted,evals,waiting,reasons);
    }

    private void evaluationsDenied(List<CandidateEvaluation> out,Candidate c,List<String> reasons){out.add(new CandidateEvaluation(c,bindingClass(c),first(str(c.metadata(),"trustDomainRef"),"provider:"+c.providerId()),"DENIED",null,dedup(reasons)));}
    private void persistEvaluations(String t,PlanAdmissionDecision d,StepDecision sd){OffsetDateTime at=OffsetDateTime.now();for(CandidateEvaluation e:sd.evaluations()){jdbc.update("insert into plan_admission_binding_evaluations(tenant_id,evaluation_id,decision_id,plan_id,plan_revision,step_id,capability_code,capability_version,binding_id,provider_id,provider_type,binding_class,trust_domain_ref,result,authorization_decision_id,reason_codes_json,evaluated_at) values(:tenant,:id,:decision,:plan,:revision,:step,:cap,:cv,:binding,:provider,:ptype,:class,:trust,:result,:auth,cast(:reasons as jsonb),:at)",new MapSqlParameterSource("tenant",t).addValue("id","plan-admission-eval-"+UUID.randomUUID()).addValue("decision",d.decisionId()).addValue("plan",d.planId()).addValue("revision",d.planRevision()).addValue("step",sd.step().stepId()).addValue("cap",sd.step().requirement().capabilityCode()).addValue("cv",capability(t,sd.step().requirement().capabilityCode()).version()).addValue("binding",e.candidate().bindingId()).addValue("provider",e.candidate().providerId()).addValue("ptype",e.candidate().providerType()).addValue("class",e.bindingClass()).addValue("trust",e.trustDomainRef()).addValue("result",e.result()).addValue("auth",e.authorizationDecisionId()).addValue("reasons",write(e.reasons())).addValue("at",at));}}
    private BindingAuthorizationEnvelope issueEnvelope(String t,PlanAdmissionDecision d,PlanAdmissionPolicy p,StepDecision sd,OffsetDateTime at){String id="binding-auth-envelope-"+UUID.randomUUID();CapabilityDef cap=capability(t,sd.step().requirement().capabilityCode());List<String> ids=sd.admitted().stream().map(x->x.candidate().bindingId()).distinct().sorted().toList();List<String> classes="WRITE".equals(sd.step().sideEffect())&&"NON_COMPENSATABLE".equals(sd.step().writeSemantics())?List.of():sd.admitted().stream().map(CandidateEvaluation::bindingClass).distinct().sorted().toList();List<String> trusts=sd.admitted().stream().map(CandidateEvaluation::trustDomainRef).filter(Objects::nonNull).distinct().sorted().toList();OffsetDateTime until=at.plusSeconds(p.envelopeTtlSeconds());jdbc.update("insert into binding_authorization_envelopes(tenant_id,envelope_id,decision_id,plan_id,plan_revision,step_id,capability_code,capability_version,admitted_binding_ids_json,admitted_binding_classes_json,admitted_trust_domain_refs_json,max_side_effect,security_ceiling_ref,data_policy_ref,egress_policy_ref,residency_constraint_ref,policy_snapshot_ref,status,issued_at,valid_until) values(:tenant,:id,:decision,:plan,:revision,:step,:cap,:cv,cast(:ids as jsonb),cast(:classes as jsonb),cast(:trusts as jsonb),:side,:security,:data,:egress,:residency,:snapshot,'ACTIVE',:at,:until)",new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("decision",d.decisionId()).addValue("plan",d.planId()).addValue("revision",d.planRevision()).addValue("step",sd.step().stepId()).addValue("cap",cap.code()).addValue("cv",cap.version()).addValue("ids",write(ids)).addValue("classes",write(classes)).addValue("trusts",write(trusts)).addValue("side",sd.step().sideEffect()).addValue("security",p.securityCeilingRef()).addValue("data",p.dataPolicyRef()).addValue("egress",p.egressPolicyRef()).addValue("residency",p.residencyConstraintRef()).addValue("snapshot",d.policySnapshotRef()).addValue("at",at).addValue("until",until));BindingAuthorizationEnvelope e=requireEnvelope(t,id);appendEnvelopeEvent(t,e,"ISSUED",null,"PLAN_ADMITTED",Map.of("admittedBindingCount",ids.size()));return e;}

    private PlanAdmissionDecision persistDecision(String t,String id,String plan,int rev,String result,PlanAdmissionPolicy p,int steps,int admitted,int denied,int waiting,int candidates,int admittedBindings,List<String> reasons,OffsetDateTime at){String policyId=p==null?null:p.policyId();Integer pv=p==null?null:p.version();String snapshot=p==null?null:"plan-admission-policy:"+policyId+":v"+pv;jdbc.update("insert into plan_admission_decisions(tenant_id,decision_id,plan_id,plan_revision,result,policy_id,policy_version,policy_snapshot_ref,step_count,admitted_step_count,denied_step_count,waiting_approval_step_count,candidate_binding_count,admitted_binding_count,reason_codes_json,actor_ref,decided_at) values(:tenant,:id,:plan,:rev,:result,:policy,:pv,:snapshot,:steps,:admitted,:denied,:waiting,:candidates,:bindings,cast(:reasons as jsonb),:actor,:at)",new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("plan",plan).addValue("rev",rev).addValue("result",result).addValue("policy",policyId).addValue("pv",pv).addValue("snapshot",snapshot).addValue("steps",steps).addValue("admitted",admitted).addValue("denied",denied).addValue("waiting",waiting).addValue("candidates",candidates).addValue("bindings",admittedBindings).addValue("reasons",write(dedup(reasons))).addValue("actor",actor()).addValue("at",at));return jdbc.queryForObject("select * from plan_admission_decisions where tenant_id=:tenant and decision_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",id),(rs,n)->decision(rs));}

    private List<Candidate> candidates(String t,CapabilityRequirement req){return jdbc.query("""
      select b.binding_id,b.provider_id,p.provider_type,b.supported_operations_json,b.trust_status,b.stale_after,p.catalog_status,p.metadata_json
      from capability_bindings b join capability_providers p on p.tenant_id=b.tenant_id and p.provider_id=b.provider_id
      where b.tenant_id=:tenant and b.capability_code=:cap and b.trust_status='APPROVED' and p.catalog_status='REGISTERED' and (b.stale_after is null or b.stale_after>now())
      order by b.binding_id
      """,new MapSqlParameterSource("tenant",t).addValue("cap",req.capabilityCode()),(rs,n)->new Candidate(rs.getString("binding_id"),rs.getString("provider_id"),rs.getString("provider_type"),readStrings(rs.getString("supported_operations_json")),readMap(rs.getString("metadata_json")))).stream().filter(c->c.operations().isEmpty()||c.operations().contains(upper(req.operation()))).toList();}
    private String bindingClass(Candidate c){return switch(c.providerType()){case "INTERNAL_SERVICE"->"LOCAL_DETERMINISTIC";case "MANAGED_AGENT"->"LOCAL_AGENT";case "REMOTE_A2A_AGENT"->"EXTERNAL_AGENT";case "MCP_TOOL"->"LOCAL".equalsIgnoreCase(str(c.metadata(),"trustBoundary"))?"LOCAL_DETERMINISTIC":"EXTERNAL_TOOL";default->"EXTERNAL_AGENT";};}
    private boolean activeExecutionAdapter(String t,String provider){Integer n=jdbc.queryForObject("select count(*) from execution_adapter_registrations where tenant_id=:tenant and provider_id=:provider and status='ACTIVE'",new MapSqlParameterSource("tenant",t).addValue("provider",provider),Integer.class);return n!=null&&n>0;}
    private boolean activeCredential(String t,String provider){Integer n=jdbc.queryForObject("select count(*) from execution_adapter_registrations where tenant_id=:tenant and provider_id=:provider and status='ACTIVE' and credential_ref is not null and btrim(credential_ref)<>''",new MapSqlParameterSource("tenant",t).addValue("provider",provider),Integer.class);return n!=null&&n>0;}
    private boolean compensationValid(String t,String binding){if(blank(binding))return false;Integer n=jdbc.queryForObject("select count(*) from capability_bindings b join capability_providers p on p.tenant_id=b.tenant_id and p.provider_id=b.provider_id where b.tenant_id=:tenant and b.binding_id=:binding and b.trust_status='APPROVED' and p.catalog_status='REGISTERED'",new MapSqlParameterSource("tenant",t).addValue("binding",binding),Integer.class);return n!=null&&n>0;}
    private boolean requiredInputPresent(Map<String,Object> schema,Map<String,Object> input){Object r=schema.get("required");if(!(r instanceof List<?> req))return true;for(Object x:req)if(x!=null&&!input.containsKey(String.valueOf(x)))return false;return true;}

    private FlowConstraint flowConstraint(String t,String taskRef,String capabilityCode){String task=normalizeTaskRef(taskRef);if(blank(task))return FlowConstraint.NONE;try{return jdbc.queryForObject("""
      select c.allowed_agent_pool_ids_json,c.allowed_binding_ids_json,c.allowed_binding_classes_json,c.excluded_binding_ids_json
      from flow_match_decisions d join flow_candidate_constraints c on c.tenant_id=d.tenant_id and c.flow_id=d.flow_id
       and (c.rule_id is null or c.rule_id=d.matched_rule_id) and c.capability_code=:cap and c.status='ACTIVE'
      where d.tenant_id=:tenant and d.task_id=:task and d.match_result='MATCHED' and d.decision_source='A0_R3_FLOW_MATCH_AUTHORITY' and d.decision_authority_version='A0R3_FLOW_MATCH_AUTHORITY_V1'
      order by c.version desc,c.constraint_id limit 1
      """,new MapSqlParameterSource("tenant",t).addValue("task",task).addValue("cap",capabilityCode),(rs,n)->new FlowConstraint(readStrings(rs.getString("allowed_agent_pool_ids_json")),readStrings(rs.getString("allowed_binding_ids_json")),readStrings(rs.getString("allowed_binding_classes_json")),readStrings(rs.getString("excluded_binding_ids_json"))));}catch(EmptyResultDataAccessException ex){return FlowConstraint.NONE;}}

    private RuntimeRequesterContext resolveRequester(String t,String taskRef,String runId){String task=normalizeTaskRef(taskRef);if(blank(task))throw new IllegalArgumentException("PLAN_TASK_REF_REQUIRED_FOR_REQUESTER_CONTEXT");Map<String,Object> row=one("select origin_principal_type,origin_principal_id,requester_department_id,requester_group_id,sensitivity_level,site_id,plant_id,hop_count from tasks where tenant_id=:tenant and task_id=:id",t,task);String raw=str(row,"origin_principal_type"),pid=str(row,"origin_principal_id");if(blank(raw)||blank(pid))throw new IllegalArgumentException("TASK_ORIGIN_PRINCIPAL_PROVENANCE_REQUIRED");String type=mapPrincipalType(raw),dept=null;List<String> groups=List.of(),roles=List.of();if("HUMAN".equals(type)){validateHuman(t,pid);dept=currentPrimaryDepartment(t,pid);groups=currentGroups(t,pid);roles=currentRoles(t,"USER",pid,groups);}else if("SERVICE_ACCOUNT".equals(type)){Map<String,Object> sa=one("select status,owner_department_id from token_service_accounts where tenant_id=:tenant and service_account_id=:id",t,pid);if(!"ACTIVE".equals(str(sa,"status")))throw new IllegalArgumentException("SERVICE_ACCOUNT_NOT_ACTIVE");dept=str(sa,"owner_department_id");roles=currentRoles(t,"SERVICE_ACCOUNT",pid,List.of());}else if("AGENT".equals(type)){Map<String,Object> a=one("select approval_status,enabled,owner_department_id,owner_group_id from agent_profiles where tenant_id=:tenant and agent_id=:id",t,pid);if(!Boolean.TRUE.equals(a.get("enabled"))||!"APPROVED".equals(str(a,"approval_status")))throw new IllegalArgumentException("AGENT_NOT_CURRENTLY_APPROVED");dept=str(a,"owner_department_id");String g=str(a,"owner_group_id");groups=blank(g)?List.of():List.of(g);}else if(!"SYSTEM".equals(type))throw new IllegalArgumentException("UNSUPPORTED_RUNTIME_REQUESTER_PRINCIPAL_TYPE:"+raw);Integer calls=jdbc.queryForObject("select count(*) from plan_execution_attempts where tenant_id=:tenant and run_id=:run",new MapSqlParameterSource("tenant",t).addValue("run",runId),Integer.class);int depth=row.get("hop_count") instanceof Number n?n.intValue():0;return new RuntimeRequesterContext(type,pid,dept,groups,roles,first(str(row,"sensitivity_level"),"INTERNAL"),str(row,"site_id"),str(row,"plant_id"),Math.max(0,depth),calls==null?0:calls);}
    private void validateHuman(String t,String user){Integer c=jdbc.queryForObject("select count(*) from iam_users u join org_tenant_memberships m on m.user_id=u.user_id and m.tenant_id=:tenant where u.user_id=:id and u.status='ACTIVE' and m.status='ACTIVE' and (m.expires_at is null or m.expires_at>now())",new MapSqlParameterSource("tenant",t).addValue("id",user),Integer.class);if(c==null||c==0)throw new IllegalArgumentException("HUMAN_REQUESTER_NOT_CURRENTLY_ACTIVE");}
    private String currentPrimaryDepartment(String t,String user){try{return jdbc.queryForObject("select department_id from org_department_memberships where tenant_id=:tenant and user_id=:id and status='ACTIVE' and is_primary=true and effective_at<=now() and (expires_at is null or expires_at>now()) limit 1",new MapSqlParameterSource("tenant",t).addValue("id",user),String.class);}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("HUMAN_REQUESTER_PRIMARY_DEPARTMENT_REQUIRED");}}
    private List<String> currentGroups(String t,String user){return jdbc.queryForList("select group_id from org_group_memberships where tenant_id=:tenant and user_id=:id and status='ACTIVE' and effective_at<=now() and (expires_at is null or expires_at>now()) order by group_id",new MapSqlParameterSource("tenant",t).addValue("id",user),String.class);}
    private List<String> currentRoles(String t,String ptype,String pid,List<String> groups){LinkedHashSet<String> out=new LinkedHashSet<>();out.addAll(jdbc.queryForList("select distinct r.role_code from rbac_principal_role_bindings b join rbac_roles r on r.role_id=b.role_id where (b.tenant_id=:tenant or b.tenant_id is null) and b.principal_type=:ptype and b.principal_id=:pid and b.status='ACTIVE' and b.effective_at<=now() and (b.expires_at is null or b.expires_at>now()) and r.status='ACTIVE'",new MapSqlParameterSource("tenant",t).addValue("ptype",ptype).addValue("pid",pid),String.class));if("USER".equals(ptype)&&!groups.isEmpty())out.addAll(jdbc.queryForList("select distinct r.role_code from rbac_principal_role_bindings b join rbac_roles r on r.role_id=b.role_id where (b.tenant_id=:tenant or b.tenant_id is null) and b.principal_type='GROUP' and b.principal_id in (:groups) and b.status='ACTIVE' and b.effective_at<=now() and (b.expires_at is null or b.expires_at>now()) and r.status='ACTIVE'",new MapSqlParameterSource("tenant",t).addValue("groups",groups),String.class));return List.copyOf(out);}

    private PlanHeader plan(String t,String id){Map<String,Object> m=one("select plan_id,status,current_revision,task_ref from execution_plans where tenant_id=:tenant and plan_id=:id",t,id);return new PlanHeader(str(m,"plan_id"),str(m,"status"),((Number)m.get("current_revision")).intValue(),str(m,"task_ref"));}
    private List<Step> steps(String t,String plan,int revision){return jdbc.query("select * from execution_plan_revision_steps where tenant_id=:tenant and plan_id=:plan and revision=:revision order by coalesce(sequence_hint,2147483647),step_id",new MapSqlParameterSource("tenant",t).addValue("plan",plan).addValue("revision",revision),(rs,n)->new Step(rs.getString("step_id"),readRequirement(rs.getString("capability_requirement_json")),rs.getString("side_effect"),rs.getString("write_semantics"),rs.getString("compensation_binding_id"),rs.getInt("max_binding_fallback")));}
    private CapabilityDef capability(String t,String code){try{return jdbc.queryForObject("select capability_code,version,status,operations_json,input_schema_json,data_classes_json from capability_definitions where tenant_id=:tenant and capability_code=:code",new MapSqlParameterSource("tenant",t).addValue("code",required(code,"capabilityCode")),(rs,n)->new CapabilityDef(rs.getString("capability_code"),rs.getInt("version"),rs.getString("status"),upperList(readStrings(rs.getString("operations_json"))),readMap(rs.getString("input_schema_json")),upperList(readStrings(rs.getString("data_classes_json")))));}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("CANONICAL_CAPABILITY_NOT_FOUND:"+code);}}
    private Optional<PlanAdmissionPolicy> activePolicy(String t){try{return Optional.ofNullable(jdbc.queryForObject("select * from plan_admission_policies where tenant_id=:tenant and status='ACTIVE'",new MapSqlParameterSource("tenant",t),(rs,n)->policy(rs)));}catch(EmptyResultDataAccessException ex){return Optional.empty();}}
    private Optional<PlanAdmissionPolicy> findPolicy(String t,String id){try{return Optional.ofNullable(jdbc.queryForObject("select * from plan_admission_policies where tenant_id=:tenant and policy_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",id),(rs,n)->policy(rs)));}catch(EmptyResultDataAccessException ex){return Optional.empty();}}
    private BindingAuthorizationEnvelope requireEnvelope(String t,String id){try{return jdbc.queryForObject("select * from binding_authorization_envelopes where tenant_id=:tenant and envelope_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",id),(rs,n)->envelope(rs));}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("Binding Authorization Envelope not found: "+id);}}
    private void revokePlanEnvelopes(String t,String plan,int revision,String reason){List<String> ids=jdbc.queryForList("select envelope_id from binding_authorization_envelopes where tenant_id=:tenant and plan_id=:plan and plan_revision=:revision and status='ACTIVE'",new MapSqlParameterSource("tenant",t).addValue("plan",plan).addValue("revision",revision),String.class);for(String id:ids)revokeEnvelope(t,id,reason);}
    private void revokePolicyEnvelopes(String t,String policyId,int oldVersion,String reason){List<String> ids=jdbc.queryForList("select e.envelope_id from binding_authorization_envelopes e join plan_admission_decisions d on d.tenant_id=e.tenant_id and d.decision_id=e.decision_id where e.tenant_id=:tenant and e.status='ACTIVE' and d.policy_id=:policy and d.policy_version<=:version",new MapSqlParameterSource("tenant",t).addValue("policy",policyId).addValue("version",oldVersion),String.class);for(String id:ids)revokeEnvelope(t,id,reason);}
    private void appendEnvelopeEvent(String t,BindingAuthorizationEnvelope e,String type,String from,String reason,Map<String,Object> evidence){jdbc.update("insert into binding_authorization_envelope_events(tenant_id,event_id,envelope_id,event_type,from_status,to_status,revocation_version,reason_code,actor_ref,evidence_json,occurred_at) values(:tenant,:event,:envelope,:type,:from,:to,:version,:reason,:actor,cast(:evidence as jsonb),:at)",new MapSqlParameterSource("tenant",t).addValue("event","binding-envelope-event-"+UUID.randomUUID()).addValue("envelope",e.envelopeId()).addValue("type",type).addValue("from",from).addValue("to",e.status()).addValue("version",e.revocationVersion()).addValue("reason",reason).addValue("actor",actor()).addValue("evidence",write(evidence)).addValue("at",OffsetDateTime.now()));}

    private PlanAdmissionPolicy policy(java.sql.ResultSet rs)throws java.sql.SQLException{return new PlanAdmissionPolicy(rs.getString("tenant_id"),rs.getString("policy_id"),rs.getString("display_name"),rs.getInt("max_candidate_bindings_per_step"),rs.getLong("envelope_ttl_seconds"),readStrings(rs.getString("allowed_binding_classes_json")),readStrings(rs.getString("allowed_data_classes_json")),rs.getString("max_sensitivity_level"),rs.getBoolean("external_egress_allowed"),readStrings(rs.getString("allowed_regions_json")),rs.getString("max_side_effect"),rs.getString("security_ceiling_ref"),rs.getString("data_policy_ref"),rs.getString("egress_policy_ref"),rs.getString("residency_constraint_ref"),rs.getString("status"),rs.getInt("version"),rs.getObject("created_at",OffsetDateTime.class),rs.getObject("updated_at",OffsetDateTime.class));}
    private PlanAdmissionDecision decision(java.sql.ResultSet rs)throws java.sql.SQLException{return new PlanAdmissionDecision(rs.getString("decision_id"),rs.getString("tenant_id"),rs.getString("plan_id"),rs.getInt("plan_revision"),rs.getString("result"),rs.getString("policy_id"),(Integer)rs.getObject("policy_version"),rs.getString("policy_snapshot_ref"),rs.getInt("step_count"),rs.getInt("admitted_step_count"),rs.getInt("denied_step_count"),rs.getInt("waiting_approval_step_count"),rs.getInt("candidate_binding_count"),rs.getInt("admitted_binding_count"),readStrings(rs.getString("reason_codes_json")),rs.getString("actor_ref"),rs.getObject("decided_at",OffsetDateTime.class));}
    private BindingAuthorizationEnvelope envelope(java.sql.ResultSet rs)throws java.sql.SQLException{return new BindingAuthorizationEnvelope(rs.getString("envelope_id"),rs.getString("tenant_id"),rs.getString("decision_id"),rs.getString("plan_id"),rs.getInt("plan_revision"),rs.getString("step_id"),rs.getString("capability_code"),rs.getInt("capability_version"),readStrings(rs.getString("admitted_binding_ids_json")),readStrings(rs.getString("admitted_binding_classes_json")),readStrings(rs.getString("admitted_trust_domain_refs_json")),rs.getString("max_side_effect"),rs.getString("security_ceiling_ref"),rs.getString("data_policy_ref"),rs.getString("egress_policy_ref"),rs.getString("residency_constraint_ref"),rs.getString("policy_snapshot_ref"),rs.getLong("authorization_epoch"),rs.getLong("revocation_version"),rs.getString("status"),rs.getObject("issued_at",OffsetDateTime.class),rs.getObject("valid_until",OffsetDateTime.class),rs.getObject("revoked_at",OffsetDateTime.class),rs.getString("revocation_reason"));}
    private PlanAdmissionBindingEvaluation evaluation(java.sql.ResultSet rs)throws java.sql.SQLException{return new PlanAdmissionBindingEvaluation(rs.getString("evaluation_id"),rs.getString("tenant_id"),rs.getString("decision_id"),rs.getString("plan_id"),rs.getInt("plan_revision"),rs.getString("step_id"),rs.getString("capability_code"),rs.getInt("capability_version"),rs.getString("binding_id"),rs.getString("provider_id"),rs.getString("provider_type"),rs.getString("binding_class"),rs.getString("trust_domain_ref"),rs.getString("result"),rs.getString("authorization_decision_id"),readStrings(rs.getString("reason_codes_json")),rs.getObject("evaluated_at",OffsetDateTime.class));}

    private void bind(String t){IamTenantExecutionContext c=IamTenantContextHolder.current().orElse(null);if(c!=null&&!"INSTANCE".equalsIgnoreCase(c.tenantId())&&!t.equals(c.tenantId()))throw new IllegalArgumentException("Tenant context mismatch for Plan Admission");jdbc.getJdbcTemplate().queryForObject("select set_config('app.current_tenant_id', ?, true)",String.class,t);jdbc.getJdbcTemplate().queryForObject("select set_config('app.current_actor_id', ?, true)",String.class,actor());}
    private String actor(){IamTenantExecutionContext c=IamTenantContextHolder.current().orElse(null);return c==null||blank(c.actorId())?"plan-admission-runtime":c.actorId();}
    private String mapPrincipalType(String v){String x=upper(v);return switch(x){case "HUMAN","USER"->"HUMAN";case "SERVICE_ACCOUNT","MACHINE"->"SERVICE_ACCOUNT";case "AGENT"->"AGENT";case "SYSTEM"->"SYSTEM";default->x;};}
    private String normalizeTaskRef(String v){if(blank(v))return null;String x=v.trim();return x.startsWith("task:")?x.substring(5):x;}
    private String tenant(String v){return required(v,"tenantId");}private String required(String v,String f){if(blank(v))throw new IllegalArgumentException(f+" is required");return v.trim();}private boolean blank(String v){return v==null||v.isBlank();}private String first(String a,String b){return !blank(a)?a:b;}private String upper(String v){return blank(v)?"":v.trim().toUpperCase(Locale.ROOT);}private String policyStatus(String v){String x=upper(first(v,"DRAFT"));if(!POLICY_STATUS.contains(x))throw new IllegalArgumentException("Unsupported Plan Admission Policy status: "+x);return x;}private String normalizeSensitivity(String v){String x=upper(v);if(!SENSITIVITY.contains(x))throw new IllegalArgumentException("Unsupported sensitivity: "+x);return x;}private String normalizeSideEffect(String v){String x=upper(v);if(!SIDE_EFFECTS.contains(x))throw new IllegalArgumentException("Unsupported sideEffect: "+x);return x;}private int rankSensitivity(String v){int i=SENSITIVITY.indexOf(normalizeSensitivity(first(v,"INTERNAL")));return i<0?SENSITIVITY.size():i;}private int rankSide(String v){return switch(normalizeSideEffect(v)){case "NONE"->0;case "READ"->1;default->2;};}
    private List<String> normalizeSet(List<String> in,Set<String> allowed,String field){List<String> out=upperList(in);for(String v:out)if(!allowed.contains(v))throw new IllegalArgumentException(field+" contains unsupported value: "+v);return out;}private List<String> upperList(List<String> in){if(in==null)return List.of();return in.stream().filter(Objects::nonNull).map(this::upper).filter(s->!s.isBlank()).distinct().sorted().toList();}private List<String> trimList(List<String> in){if(in==null)return List.of();return in.stream().filter(Objects::nonNull).map(String::trim).filter(s->!s.isBlank()).distinct().sorted().toList();}private List<String> dedup(Collection<String> in){return in==null?List.of():in.stream().filter(Objects::nonNull).filter(s->!s.isBlank()).distinct().toList();}
    private Map<String,Object> one(String sql,String t,String id){try{return jdbc.queryForMap(sql,new MapSqlParameterSource("tenant",t).addValue("id",id));}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("Referenced Plan Admission resource not found: "+id);}}private String str(Map<String,Object> m,String k){Object v=m.get(k);return v==null?null:String.valueOf(v);}private String write(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalArgumentException("Plan Admission evidence cannot be serialized",e);}}private List<String> readStrings(String v){try{return blank(v)?List.of():json.readValue(v,STRING_LIST);}catch(Exception e){throw new IllegalStateException("Plan Admission list cannot be read",e);}}private Map<String,Object> readMap(String v){try{return blank(v)?Map.of():json.readValue(v,OBJECT_MAP);}catch(Exception e){throw new IllegalStateException("Plan Admission object cannot be read",e);}}private CapabilityRequirement readRequirement(String v){try{return json.readValue(v,CapabilityRequirement.class);}catch(Exception e){throw new IllegalStateException("CapabilityRequirement cannot be read",e);}}

    private record PlanHeader(String planId,String status,int currentRevision,String taskRef){}
    private record Step(String stepId,CapabilityRequirement requirement,String sideEffect,String writeSemantics,String compensationBindingId,int maxBindingFallback){}
    private record CapabilityDef(String code,int version,String status,List<String> operations,Map<String,Object> inputSchema,List<String> dataClasses){}
    private record Candidate(String bindingId,String providerId,String providerType,List<String> operations,Map<String,Object> metadata){}
    private record CandidateEvaluation(Candidate candidate,String bindingClass,String trustDomainRef,String result,String authorizationDecisionId,List<String> reasons){}
    private record StepDecision(Step step,List<CandidateEvaluation> admitted,List<CandidateEvaluation> evaluations,boolean waiting,List<String> stepReasons){}
    private record FlowConstraint(List<String> allowedPools,List<String> allowedBindingIds,List<String> allowedClasses,List<String> excludedBindingIds){
        static final FlowConstraint NONE=new FlowConstraint(List.of(),List.of(),List.of(),List.of());
        FlowConstraint { allowedPools=allowedPools==null?List.of():List.copyOf(allowedPools);allowedBindingIds=allowedBindingIds==null?List.of():List.copyOf(allowedBindingIds);allowedClasses=allowedClasses==null?List.of():List.copyOf(allowedClasses);excludedBindingIds=excludedBindingIds==null?List.of():List.copyOf(excludedBindingIds); }
        boolean allows(Candidate c,String clazz){return !excludedBindingIds.contains(c.bindingId())&&(allowedBindingIds.isEmpty()||allowedBindingIds.contains(c.bindingId()))&&(allowedClasses.isEmpty()||allowedClasses.contains(clazz));}
    }
}
