package com.opensocket.aievent.core.capability;

import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantContextHolder;
import com.opensocket.aievent.core.iam.persistence.tenant.IamTenantExecutionContext;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

/**
 * MRS A0-R6 shadow cutover service.
 *
 * <p>Consumes only a current A0-R5 ADMITTED step-scoped BindingAuthorizationEnvelope, applies
 * current runtime eligibility, captures replayable routing features, selects Binding/Pool, and
 * records a SHADOW_ONLY execution target. It never writes task_assignments, acquires a lease,
 * generates fencing, persists DispatchIntent, or sends network traffic.</p>
 */
@Service
public class RoutingAuthorityCutoverService {
    private static final TypeReference<List<String>> STRING_LIST=new TypeReference<>(){};
    private static final TypeReference<Map<String,Object>> OBJECT_MAP=new TypeReference<>(){};
    private final NamedParameterJdbcTemplate jdbc; private final ObjectMapper json; private final PlanAdmissionService admission;
    public RoutingAuthorityCutoverService(NamedParameterJdbcTemplate jdbc,ObjectMapper json,PlanAdmissionService admission){this.jdbc=jdbc;this.json=json;this.admission=admission;}

    @Transactional
    public RoutingAuthorityShadowResult evaluateShadow(String tenantId,String planId,RoutingAuthorityShadowRequest request){
        String t=tenant(tenantId),p=required(planId,"planId");bind(t);if(request==null)throw new IllegalArgumentException("Routing shadow request body is required");
        PlanHeader plan=plan(t,p);int rev=request.planRevision()==null?plan.currentRevision():request.planRevision();if(rev!=plan.currentRevision())throw new IllegalArgumentException("A0-R6 must evaluate the current frozen Plan revision");
        admission.requireCurrentAdmission(t,p,rev);String stepId=required(request.stepId(),"stepId");BindingAuthorizationEnvelope env=admission.requireActiveEnvelope(t,p,rev,stepId);Step step=step(t,p,rev,stepId);
        RoutingProfile profile=profile(t,required(request.routingProfileId(),"routingProfileId"));if(!"ACTIVE".equals(profile.status()))throw new IllegalArgumentException("Routing Profile must be ACTIVE");
        if(!env.capabilityCode().equals(step.requirement().capabilityCode()))throw new IllegalArgumentException("R5 envelope capability does not match frozen Plan Step");
        String taskId=taskId(plan.taskRef());FlowContext flow=flowContext(t,taskId);FlowConstraint flowConstraint=flowConstraint(t,flow,step.requirement().capabilityCode());
        List<Candidate> candidates=candidates(t,env,step,flowConstraint);List<CandidateEval> evaluated=new ArrayList<>();
        for(Candidate c:candidates)evaluated.add(evaluateCandidate(profile,c));
        List<CandidateEval> eligible=evaluated.stream().filter(x->"ELIGIBLE".equals(x.result())).toList();
        String eligibilityId="routing-eligibility-"+UUID.randomUUID();Map<String,Integer> summary=exclusionSummary(evaluated);String setDigest=digest(evaluated.stream().map(CandidateEval::digestMaterial).toList());OffsetDateTime now=OffsetDateTime.now();
        String eligibilityResult=eligible.isEmpty()?"NO_ELIGIBLE_CANDIDATE":"ELIGIBLE_SET";
        persistEligibility(t,eligibilityId,p,rev,stepId,taskId,env,step,profile,evaluated,summary,setDigest,eligibilityResult,now);
        List<EligibilityCandidateEvaluation> publicEvals=persistCandidateEvaluations(t,eligibilityId,evaluated,now);
        RoutingFeatureSnapshot snapshot=persistFeatureSnapshot(t,eligibilityId,profile,evaluated,now);
        R6RoutingDecision routing=persistRoutingDecision(t,p,rev,stepId,env,step,profile,eligibilityId,snapshot,eligible,now);
        ExecutionAssignmentShadow assignment=routing.selectedBindingId()==null?null:persistShadowAssignment(t,taskId,p,rev,stepId,routing,eligible,now);
        FlowRoutingMigrationState state=flow.flowId()==null?null:flowMigrationState(t,flow.flowId());LegacyAssignment legacy=legacyAssignment(t,taskId);
        boolean equivalent=assignment!=null&&legacy!=null&&Objects.equals(assignment.selectedAgentId(),legacy.agentId())&&Objects.equals(assignment.agentPoolId(),legacy.poolId());
        EligibilityDecision decision=new EligibilityDecision(eligibilityId,t,p,rev,stepId,taskId,env.envelopeId(),env.capabilityCode(),env.capabilityVersion(),step.requirement().operation(),profile.profileId(),profile.version(),evaluated.size(),eligible.size(),evaluated.size()-eligible.size(),eligibilityResult,summary,setDigest,env.policySnapshotRef(),now);
        return new RoutingAuthorityShadowResult(decision,publicEvals,snapshot,routing,assignment,state,legacy==null?null:legacy.assignmentId(),legacy==null?null:legacy.agentId(),legacy==null?null:legacy.poolId(),equivalent);
    }

    @Transactional
    public RebindingAdmissionDecision evaluateRebinding(String tenantId,String planId,RebindingAdmissionRequest request){
        String t=tenant(tenantId),p=required(planId,"planId");bind(t);if(request==null)throw new IllegalArgumentException("Rebinding request body is required");PlanHeader plan=plan(t,p);int rev=request.planRevision()==null?plan.currentRevision():request.planRevision();String stepId=required(request.stepId(),"stepId");
        admission.requireCurrentAdmission(t,p,rev);BindingAuthorizationEnvelope env=admission.requireActiveEnvelope(t,p,rev,stepId);Step step=step(t,p,rev,stepId);CandidateIdentity identity=candidateIdentity(t,required(request.requestedBindingId(),"requestedBindingId"));
        String clazz=bindingClass(identity.providerType(),identity.metadata());List<String> reasons=new ArrayList<>();String result;
        boolean nonComp="WRITE".equals(step.sideEffect())&&"NON_COMPENSATABLE".equals(step.writeSemantics());
        if(nonComp){result="FULL_PLAN_ADMISSION_REQUIRED";reasons.add("NON_COMPENSATABLE_WRITE_REQUIRES_PER_EXECUTION_APPROVAL");}
        else if(env.admittedBindingIds().contains(identity.bindingId())){result="FAST_FALLBACK_ALLOWED";reasons.add("NAMED_BINDING_ALREADY_ADMITTED");}
        else if(env.admittedBindingClasses().contains(clazz)){result="REBINDING_ADMISSION_REQUIRED";reasons.add("BINDING_CLASS_ADMITTED_BUT_BINDING_NOT_NAMED");}
        else{result="FULL_PLAN_ADMISSION_REQUIRED";reasons.add("BINDING_CLASS_OUTSIDE_ENVELOPE");}
        if(!env.capabilityCode().equals(identity.capabilityCode())){result="DENIED";reasons=List.of("CAPABILITY_MISMATCH");}
        String id="rebinding-admission-"+UUID.randomUUID();OffsetDateTime at=OffsetDateTime.now();jdbc.update("insert into rebinding_admission_decisions(tenant_id,decision_id,plan_id,plan_revision,step_id,envelope_id,requested_binding_id,requested_binding_class,side_effect,write_semantics,result,reason_codes_json,evaluated_at) values(:tenant,:id,:plan,:rev,:step,:env,:binding,:class,:side,:write,:result,cast(:reasons as jsonb),:at)",new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("plan",p).addValue("rev",rev).addValue("step",stepId).addValue("env",env.envelopeId()).addValue("binding",identity.bindingId()).addValue("class",clazz).addValue("side",step.sideEffect()).addValue("write",step.writeSemantics()).addValue("result",result).addValue("reasons",write(reasons)).addValue("at",at));
        return new RebindingAdmissionDecision(id,t,p,rev,stepId,env.envelopeId(),identity.bindingId(),clazz,step.sideEffect(),step.writeSemantics(),result,reasons,at);
    }

    @Transactional(readOnly=true)
    public List<Map<String,Object>> trace(String tenantId,String planId,int limit){String t=tenant(tenantId);bind(t);return jdbc.queryForList("select * from routing_authority_shadow_trace_v205 where tenant_id=:tenant and plan_id=:plan order by assigned_at desc nulls last limit :limit",new MapSqlParameterSource("tenant",t).addValue("plan",required(planId,"planId")).addValue("limit",Math.max(1,Math.min(limit<=0?100:limit,500))));}

    @Transactional
    public FlowRoutingMigrationState setFlowMigrationState(String tenantId,String flowId,String state,String reason){String t=tenant(tenantId),f=required(flowId,"flowId"),next=upper(state);bind(t);if(!Set.of("LEGACY_AUTHORITATIVE","SHADOW").contains(next))throw new IllegalArgumentException("A0-R6 permits only LEGACY_AUTHORITATIVE or SHADOW; NEW_AUTHORITATIVE requires a later cutover gate");if(blank(reason))throw new IllegalArgumentException("X-Change-Reason is required");FlowRoutingMigrationState old=flowMigrationState(t,f);int version=old==null?1:old.version()+1;OffsetDateTime at=OffsetDateTime.now();jdbc.update("insert into flow_routing_migration_state(tenant_id,flow_id,migration_state,version,change_reason,changed_by,changed_at) values(:tenant,:flow,:state,:version,:reason,:actor,:at) on conflict(tenant_id,flow_id) do update set migration_state=excluded.migration_state,version=excluded.version,change_reason=excluded.change_reason,changed_by=excluded.changed_by,changed_at=excluded.changed_at",new MapSqlParameterSource("tenant",t).addValue("flow",f).addValue("state",next).addValue("version",version).addValue("reason",reason.trim()).addValue("actor",actor()).addValue("at",at));jdbc.update("insert into flow_routing_migration_events(tenant_id,event_id,flow_id,from_state,to_state,version,reason,actor_ref,occurred_at) values(:tenant,:id,:flow,:from,:to,:version,:reason,:actor,:at)",new MapSqlParameterSource("tenant",t).addValue("id","flow-routing-migration-"+UUID.randomUUID()).addValue("flow",f).addValue("from",old==null?null:old.migrationState()).addValue("to",next).addValue("version",version).addValue("reason",reason.trim()).addValue("actor",actor()).addValue("at",at));return flowMigrationState(t,f);}

    @Transactional(readOnly=true)
    public List<FlowRoutingMigrationState> migrationStates(String tenantId,int limit){String t=tenant(tenantId);bind(t);return jdbc.query("select * from flow_routing_migration_state where tenant_id=:tenant order by flow_id limit :limit",new MapSqlParameterSource("tenant",t).addValue("limit",Math.max(1,Math.min(limit<=0?100:limit,500))),(rs,n)->new FlowRoutingMigrationState(rs.getString("tenant_id"),rs.getString("flow_id"),rs.getString("migration_state"),rs.getInt("version"),rs.getString("change_reason"),rs.getString("changed_by"),rs.getObject("changed_at",OffsetDateTime.class)));}

    private CandidateEval evaluateCandidate(RoutingProfile p,Candidate c){List<String> reasons=new ArrayList<>();if(!"APPROVED".equals(c.trustStatus()))reasons.add("BINDING_NOT_APPROVED");if(!"REGISTERED".equals(c.providerStatus()))reasons.add("PROVIDER_NOT_REGISTERED");if(c.staleAfter()!=null&&!c.staleAfter().isAfter(OffsetDateTime.now()))reasons.add("BINDING_STALE");if(c.adapterId()==null)reasons.add("NO_ACTIVE_EXECUTION_ADAPTER");if(c.observationId()==null)reasons.add("NO_ELIGIBILITY_OBSERVATION");else{if(!c.available())reasons.add("PROVIDER_NOT_AVAILABLE");if(!c.healthy())reasons.add("PROVIDER_NOT_HEALTHY");if(!c.capacityAvailable())reasons.add("NO_CAPACITY");if(c.observationExpiresAt()!=null&&!c.observationExpiresAt().isAfter(OffsetDateTime.now()))reasons.add("ELIGIBILITY_OBSERVATION_EXPIRED");if(p.minQualityScore()!=null&&(c.quality()==null||c.quality().compareTo(p.minQualityScore())<0))reasons.add("QUALITY_BELOW_PROFILE");if(p.minReliabilityScore()!=null&&(c.reliability()==null||c.reliability().compareTo(p.minReliabilityScore())<0))reasons.add("RELIABILITY_BELOW_PROFILE");if(p.maxP95LatencyMs()!=null&&(c.latency()==null||c.latency()>p.maxP95LatencyMs()))reasons.add("LATENCY_ABOVE_PROFILE");if(p.maxEstimatedCost()!=null&&(c.cost()==null||c.cost().compareTo(p.maxEstimatedCost())>0))reasons.add("COST_ABOVE_PROFILE");if(p.maxLoadPercent()!=null&&(c.load()==null||c.load().compareTo(p.maxLoadPercent())>0))reasons.add("LOAD_ABOVE_PROFILE");}
        Map<String,BigDecimal> dims=scoreDimensions(c);BigDecimal total=reasons.isEmpty()?weighted(p.weights(),dims):null;return new CandidateEval(c,reasons.isEmpty()?"ELIGIBLE":"EXCLUDED",List.copyOf(reasons),dims,total);}
    private Map<String,BigDecimal> scoreDimensions(Candidate c){Map<String,BigDecimal> m=new LinkedHashMap<>();m.put("QUALITY",nz(c.quality()));m.put("RELIABILITY",nz(c.reliability()));m.put("LATENCY",c.latency()==null?BigDecimal.ZERO:BigDecimal.valueOf(10000.0/(100.0+c.latency())).min(BigDecimal.valueOf(100)));m.put("COST",c.cost()==null?BigDecimal.ZERO:BigDecimal.valueOf(100).divide(BigDecimal.ONE.add(c.cost().max(BigDecimal.ZERO)),6,RoundingMode.HALF_UP));m.put("LOAD",c.load()==null?BigDecimal.ZERO:BigDecimal.valueOf(100).subtract(c.load()).max(BigDecimal.ZERO));m.put("LOCALITY",nz(c.locality()));return Map.copyOf(m);}
    private BigDecimal weighted(Map<String,Integer> weights,Map<String,BigDecimal> dims){if(weights==null||weights.isEmpty())return BigDecimal.ZERO;long denom=weights.values().stream().filter(Objects::nonNull).mapToLong(Integer::longValue).sum();if(denom<=0)return BigDecimal.ZERO;BigDecimal total=BigDecimal.ZERO;for(var e:weights.entrySet())total=total.add(dims.getOrDefault(e.getKey(),BigDecimal.ZERO).multiply(BigDecimal.valueOf(e.getValue()==null?0:e.getValue())));return total.divide(BigDecimal.valueOf(denom),6,RoundingMode.HALF_UP);}

    private void persistEligibility(String t,String id,String plan,int rev,String step,String task,BindingAuthorizationEnvelope env,Step s,RoutingProfile p,List<CandidateEval> evals,Map<String,Integer> summary,String digest,String result,OffsetDateTime at){jdbc.update("insert into routing_eligibility_decisions(tenant_id,decision_id,plan_id,plan_revision,step_id,task_id,envelope_id,capability_code,capability_version,operation,routing_profile_id,routing_profile_version,candidate_count,eligible_count,excluded_count,result,exclusion_summary_json,candidate_evaluation_set_digest,policy_snapshot_ref,evaluated_at) values(:tenant,:id,:plan,:rev,:step,:task,:env,:cap,:cv,:op,:profile,:pv,:count,:eligible,:excluded,:result,cast(:summary as jsonb),:digest,:snapshot,:at)",new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("plan",plan).addValue("rev",rev).addValue("step",step).addValue("task",task).addValue("env",env.envelopeId()).addValue("cap",env.capabilityCode()).addValue("cv",env.capabilityVersion()).addValue("op",upper(s.requirement().operation())).addValue("profile",p.profileId()).addValue("pv",p.version()).addValue("count",evals.size()).addValue("eligible",evals.stream().filter(x->"ELIGIBLE".equals(x.result())).count()).addValue("excluded",evals.stream().filter(x->"EXCLUDED".equals(x.result())).count()).addValue("result",result).addValue("summary",write(summary)).addValue("digest",digest).addValue("snapshot",env.policySnapshotRef()).addValue("at",at));}
    private List<EligibilityCandidateEvaluation> persistCandidateEvaluations(String t,String decision,List<CandidateEval> evals,OffsetDateTime at){List<EligibilityCandidateEvaluation> out=new ArrayList<>();for(CandidateEval e:evals){String id="routing-candidate-eval-"+UUID.randomUUID();Candidate c=e.c();jdbc.update("insert into routing_eligibility_candidate_evaluations(tenant_id,evaluation_id,decision_id,binding_id,provider_id,provider_type,binding_class,agent_pool_id,observation_id,result,reason_codes_json,score_dimensions_json,normalized_weighted_score,evaluated_at) values(:tenant,:id,:decision,:binding,:provider,:ptype,:class,:pool,:obs,:result,cast(:reasons as jsonb),cast(:scores as jsonb),:score,:at)",new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("decision",decision).addValue("binding",c.bindingId()).addValue("provider",c.providerId()).addValue("ptype",c.providerType()).addValue("class",c.bindingClass()).addValue("pool",c.agentPoolId()).addValue("obs",c.observationId()).addValue("result",e.result()).addValue("reasons",write(e.reasons())).addValue("scores",write(e.dims())).addValue("score",e.score()).addValue("at",at));out.add(new EligibilityCandidateEvaluation(id,c.bindingId(),c.providerId(),c.providerType(),c.bindingClass(),c.agentPoolId(),c.observationId(),e.result(),e.reasons(),e.dims(),e.score()));}return List.copyOf(out);}
    private RoutingFeatureSnapshot persistFeatureSnapshot(String t,String eligibility,RoutingProfile p,List<CandidateEval> evals,OffsetDateTime at){String id="routing-feature-"+UUID.randomUUID();Map<String,Object> availability=new LinkedHashMap<>(),load=new LinkedHashMap<>();for(CandidateEval e:evals){Candidate c=e.c();availability.put(c.bindingId(),Map.of("available",c.available(),"healthy",c.healthy(),"capacityAvailable",c.capacityAvailable(),"observationId",Objects.toString(c.observationId(),"")));load.put(c.bindingId(),Map.of("loadPercent",c.load()==null?"UNKNOWN":c.load(),"agentPoolId",Objects.toString(c.agentPoolId(),"")));}String catalogVersion=digest(evals.stream().map(x->x.c().bindingId()+":"+x.c().providerId()+":"+x.c().trustStatus()).toList());jdbc.update("insert into routing_feature_snapshots(tenant_id,snapshot_id,eligibility_decision_id,candidate_catalog_version,metric_as_of,quality_model_version,pool_health_revision,availability_snapshot_json,load_snapshot_json,pricing_version,routing_profile_id,routing_profile_version,scoring_config_version,captured_at) values(:tenant,:id,:eligibility,:catalog,:metric,'DIRECT_OBSERVATION_V1',:pool,cast(:availability as jsonb),cast(:load as jsonb),'OBSERVED_COST_V1',:profile,:pv,'A0R6_WEIGHTED_V1',:at)",new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("eligibility",eligibility).addValue("catalog",catalogVersion).addValue("metric",at).addValue("pool","POOL_HEALTH@"+at).addValue("availability",write(availability)).addValue("load",write(load)).addValue("profile",p.profileId()).addValue("pv",p.version()).addValue("at",at));return new RoutingFeatureSnapshot(id,t,eligibility,catalogVersion,at,"DIRECT_OBSERVATION_V1","POOL_HEALTH@"+at,availability,load,"OBSERVED_COST_V1",p.profileId(),p.version(),"A0R6_WEIGHTED_V1",at);}
    private R6RoutingDecision persistRoutingDecision(String t,String plan,int rev,String step,BindingAuthorizationEnvelope env,Step s,RoutingProfile p,String eligibility,RoutingFeatureSnapshot snap,List<CandidateEval> eligible,OffsetDateTime at){CandidateEval winner=eligible.stream().sorted(Comparator.comparing(CandidateEval::score,Comparator.nullsLast(Comparator.reverseOrder())).thenComparing(x->x.c().bindingId())).findFirst().orElse(null);String result=winner==null?"NO_ELIGIBLE_PROVIDER":"SELECTED";List<String> reasons=winner==null?List.of("NO_ELIGIBLE_PROVIDER"):List.of("R5_ENVELOPE_CONSTRAINED","WHO_SHOULD_SELECTED","STABLE_BINDING_KEY_TIE_BREAK");String id="provider-routing-r6-"+UUID.randomUUID();Candidate c=winner==null?null:winner.c();List<Map<String,Object>> evidence=eligible.stream().map(x->Map.<String,Object>of("bindingId",x.c().bindingId(),"providerId",x.c().providerId(),"score",x.score()==null?BigDecimal.ZERO:x.score(),"eligibilityResult",x.result())).toList();jdbc.update("insert into provider_routing_decisions(tenant_id,decision_id,decision_mode,result,capability_code,operation,routing_profile_id,routing_profile_version,selected_binding_id,selected_provider_id,reason_codes_json,candidates_json,evaluated_at,plan_id,plan_revision,step_id,binding_authorization_envelope_id,eligibility_decision_id,routing_feature_snapshot_ref,selected_agent_pool_id,authority_mode) values(:tenant,:id,'PREVIEW',:result,:cap,:op,:profile,:pv,:binding,:provider,cast(:reasons as jsonb),cast(:candidates as jsonb),:at,:plan,:rev,:step,:env,:eligibility,:snapshot,:pool,'SHADOW')",new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("result",result).addValue("cap",env.capabilityCode()).addValue("op",upper(s.requirement().operation())).addValue("profile",p.profileId()).addValue("pv",p.version()).addValue("binding",c==null?null:c.bindingId()).addValue("provider",c==null?null:c.providerId()).addValue("reasons",write(reasons)).addValue("candidates",write(evidence)).addValue("at",at).addValue("plan",plan).addValue("rev",rev).addValue("step",step).addValue("env",env.envelopeId()).addValue("eligibility",eligibility).addValue("snapshot",snap.snapshotId()).addValue("pool",c==null?null:c.agentPoolId()));return new R6RoutingDecision(id,t,result,plan,rev,step,env.envelopeId(),eligibility,snap.snapshotId(),env.capabilityCode(),upper(s.requirement().operation()),p.profileId(),p.version(),c==null?null:c.bindingId(),c==null?null:c.providerId(),c==null?null:c.agentPoolId(),reasons,"SHADOW",at);}
    private ExecutionAssignmentShadow persistShadowAssignment(String t,String task,String plan,int rev,String step,R6RoutingDecision routing,List<CandidateEval> eligible,OffsetDateTime at){Candidate c=eligible.stream().filter(x->Objects.equals(x.c().bindingId(),routing.selectedBindingId())).map(CandidateEval::c).findFirst().orElseThrow();String id="execution-assignment-shadow-"+UUID.randomUUID();String agent=c.providerType().equals("MANAGED_AGENT")?stripPrefix(c.providerRef(),"agent:"):value(c.adapterConfig(),"agentId",stripPrefix(c.providerRef(),"agent:"));String session=value(c.adapterConfig(),"sessionId",c.adapterType().equals("MANAGED_AGENT_NETTY")?c.runtimeRef():null);String peer=value(c.adapterConfig(),"peerInterfaceId",c.adapterType().equals("REMOTE_A2A")?c.runtimeRef():null);String mcp=value(c.adapterConfig(),"mcpServerId",c.adapterType().equals("MCP_TOOL")?c.runtimeRef():null);Map<String,Object> load=Map.of("loadPercent",c.load()==null?"UNKNOWN":c.load(),"observationId",Objects.toString(c.observationId(),""));jdbc.update("insert into execution_assignment_shadows(tenant_id,assignment_id,task_id,plan_id,plan_revision,step_id,routing_decision_id,binding_id,provider_id,agent_pool_id,selected_agent_id,selected_session_id,selected_peer_interface_id,selected_mcp_server_id,selected_adapter_id,assignment_reason,runtime_load_snapshot_json,attempt_number,authority_mode,side_effect_allowed,assigned_at,outcome) values(:tenant,:id,:task,:plan,:rev,:step,:routing,:binding,:provider,:pool,:agent,:session,:peer,:mcp,:adapter,'R6_SHADOW_RUNTIME_TARGET_SELECTION',cast(:load as jsonb),1,'SHADOW_ONLY',false,:at,'SHADOW_EVALUATED')",new MapSqlParameterSource("tenant",t).addValue("id",id).addValue("task",task).addValue("plan",plan).addValue("rev",rev).addValue("step",step).addValue("routing",routing.decisionId()).addValue("binding",c.bindingId()).addValue("provider",c.providerId()).addValue("pool",c.agentPoolId()).addValue("agent",agent).addValue("session",session).addValue("peer",peer).addValue("mcp",mcp).addValue("adapter",c.adapterId()).addValue("load",write(load)).addValue("at",at));return new ExecutionAssignmentShadow(id,t,task,plan,rev,step,routing.decisionId(),c.bindingId(),c.providerId(),c.agentPoolId(),agent,session,peer,mcp,c.adapterId(),"R6_SHADOW_RUNTIME_TARGET_SELECTION",load,1,null,"SHADOW_ONLY",false,at,null,"SHADOW_EVALUATED");}

    private List<Candidate> candidates(String t,BindingAuthorizationEnvelope env,Step step,FlowConstraint fc){if(env.admittedBindingIds().isEmpty())return List.of();MapSqlParameterSource p=new MapSqlParameterSource("tenant",t).addValue("ids",env.admittedBindingIds());List<Candidate> rows=jdbc.query("""
      select b.binding_id,b.capability_code,b.provider_id,b.supported_operations_json,b.trust_status,b.stale_after,
             p.provider_type,p.provider_ref,p.catalog_status,p.metadata_json,
             o.observation_id,o.available,o.healthy,o.capacity_available,o.quality_score,o.reliability_score,o.p95_latency_ms,o.estimated_cost,o.load_percent,o.locality_score,o.expires_at,
             a.adapter_id,a.adapter_type,a.runtime_ref,a.configuration_json,
             (select min(apm.pool_id) from agent_pool_members apm join agent_pools ap on ap.tenant_id=apm.tenant_id and ap.pool_id=apm.pool_id and ap.status='ACTIVE' where apm.tenant_id=b.tenant_id and apm.agent_id=regexp_replace(p.provider_ref,'^agent:','') and apm.member_status='ACTIVE') as agent_pool_id
        from capability_bindings b join capability_providers p on p.tenant_id=b.tenant_id and p.provider_id=b.provider_id
        left join lateral (select * from provider_eligibility_observations x where x.tenant_id=b.tenant_id and x.binding_id=b.binding_id order by x.observed_at desc,x.observation_id desc limit 1) o on true
        left join lateral (select * from execution_adapter_registrations x where x.tenant_id=b.tenant_id and x.provider_id=b.provider_id and x.status='ACTIVE' order by x.selection_priority,x.adapter_id limit 1) a on true
       where b.tenant_id=:tenant and b.binding_id in (:ids) order by b.binding_id
      """,p,(rs,n)->new Candidate(rs.getString("binding_id"),rs.getString("capability_code"),rs.getString("provider_id"),rs.getString("provider_type"),rs.getString("provider_ref"),rs.getString("catalog_status"),readStrings(rs.getString("supported_operations_json")),rs.getString("trust_status"),rs.getObject("stale_after",OffsetDateTime.class),readMap(rs.getString("metadata_json")),rs.getString("agent_pool_id"),rs.getString("observation_id"),rs.getBoolean("available"),rs.getBoolean("healthy"),rs.getBoolean("capacity_available"),rs.getBigDecimal("quality_score"),rs.getBigDecimal("reliability_score"),(Long)rs.getObject("p95_latency_ms"),rs.getBigDecimal("estimated_cost"),rs.getBigDecimal("load_percent"),rs.getBigDecimal("locality_score"),rs.getObject("expires_at",OffsetDateTime.class),rs.getString("adapter_id"),rs.getString("adapter_type"),rs.getString("runtime_ref"),readMap(rs.getString("configuration_json"))));
        String op=upper(step.requirement().operation());return rows.stream().filter(c->env.capabilityCode().equals(c.capabilityCode())).filter(c->c.operations().isEmpty()||c.operations().contains(op)).filter(c->fc.allows(c)).map(c->c.withBindingClass(bindingClass(c.providerType(),c.metadata()))).toList();}
    private FlowConstraint flowConstraint(String t,FlowContext f,String cap){if(f==null||f.flowId()==null)return FlowConstraint.NONE;List<Map<String,Object>> rows=jdbc.queryForList("select * from flow_candidate_constraints where tenant_id=:tenant and flow_id=:flow and capability_code=:cap and status='ACTIVE' and (rule_id is null or rule_id=:rule) order by version desc,constraint_id",new MapSqlParameterSource("tenant",t).addValue("flow",f.flowId()).addValue("rule",f.ruleId()).addValue("cap",cap));if(rows.isEmpty())return FlowConstraint.NONE;Set<String> pools=new LinkedHashSet<>(),ids=new LinkedHashSet<>(),classes=new LinkedHashSet<>(),excluded=new LinkedHashSet<>();for(Map<String,Object> r:rows){pools.addAll(readStrings(str(r,"allowed_agent_pool_ids_json")));ids.addAll(readStrings(str(r,"allowed_binding_ids_json")));classes.addAll(readStrings(str(r,"allowed_binding_classes_json")));excluded.addAll(readStrings(str(r,"excluded_binding_ids_json")));}return new FlowConstraint(List.copyOf(pools),List.copyOf(ids),List.copyOf(classes),List.copyOf(excluded));}
    private FlowContext flowContext(String t,String task){if(blank(task))return new FlowContext(null,null);try{return jdbc.queryForObject("select flow_id,matched_rule_id from flow_match_decisions where tenant_id=:tenant and task_id=:task and match_result='MATCHED' order by decided_at desc limit 1",new MapSqlParameterSource("tenant",t).addValue("task",task),(rs,n)->new FlowContext(rs.getString("flow_id"),rs.getString("matched_rule_id")));}catch(EmptyResultDataAccessException ex){return new FlowContext(null,null);}}
    private LegacyAssignment legacyAssignment(String t,String task){if(blank(task))return null;try{return jdbc.queryForObject("select assignment_id,agent_id,coalesce(assigned_pool_id,target_pool_id) pool_id from task_assignments where task_id=:task order by created_at desc limit 1",new MapSqlParameterSource("task",task),(rs,n)->new LegacyAssignment(rs.getString("assignment_id"),rs.getString("agent_id"),rs.getString("pool_id")));}catch(EmptyResultDataAccessException ex){return null;}}
    private FlowRoutingMigrationState flowMigrationState(String t,String flow){if(blank(flow))return null;try{return jdbc.queryForObject("select * from flow_routing_migration_state where tenant_id=:tenant and flow_id=:flow",new MapSqlParameterSource("tenant",t).addValue("flow",flow),(rs,n)->new FlowRoutingMigrationState(rs.getString("tenant_id"),rs.getString("flow_id"),rs.getString("migration_state"),rs.getInt("version"),rs.getString("change_reason"),rs.getString("changed_by"),rs.getObject("changed_at",OffsetDateTime.class)));}catch(EmptyResultDataAccessException ex){return new FlowRoutingMigrationState(t,flow,"LEGACY_AUTHORITATIVE",0,"IMPLICIT_R6_DEFAULT","system",null);}}
    private RoutingProfile profile(String t,String id){try{return jdbc.queryForObject("select * from routing_profiles where tenant_id=:tenant and profile_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",id),(rs,n)->new RoutingProfile(rs.getString("tenant_id"),rs.getString("profile_id"),rs.getString("display_name"),rs.getString("description"),rs.getString("profile_type"),rs.getString("status"),readIntMap(rs.getString("weights_json")),rs.getBigDecimal("min_quality_score"),rs.getBigDecimal("min_reliability_score"),(Long)rs.getObject("max_p95_latency_ms"),rs.getBigDecimal("max_estimated_cost"),rs.getBigDecimal("max_load_percent"),(Integer)rs.getObject("max_observation_age_seconds"),rs.getInt("version"),rs.getObject("created_at",OffsetDateTime.class),rs.getObject("updated_at",OffsetDateTime.class)));}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("Routing Profile does not exist: "+id);}}
    private PlanHeader plan(String t,String id){try{return jdbc.queryForObject("select plan_id,current_revision,task_ref from execution_plans where tenant_id=:tenant and plan_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",id),(rs,n)->new PlanHeader(rs.getString("plan_id"),rs.getInt("current_revision"),rs.getString("task_ref")));}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("Execution Plan does not exist: "+id);}}
    private Step step(String t,String p,int rev,String id){try{return jdbc.queryForObject("select capability_requirement_json,side_effect,write_semantics from execution_plan_revision_steps where tenant_id=:tenant and plan_id=:plan and revision=:rev and step_id=:step",new MapSqlParameterSource("tenant",t).addValue("plan",p).addValue("rev",rev).addValue("step",id),(rs,n)->new Step(id,readRequirement(rs.getString("capability_requirement_json")),rs.getString("side_effect"),rs.getString("write_semantics")));}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("Execution Plan Step does not exist: "+id);}}
    private CandidateIdentity candidateIdentity(String t,String id){try{return jdbc.queryForObject("select b.binding_id,b.capability_code,p.provider_type,p.metadata_json from capability_bindings b join capability_providers p on p.tenant_id=b.tenant_id and p.provider_id=b.provider_id where b.tenant_id=:tenant and b.binding_id=:id",new MapSqlParameterSource("tenant",t).addValue("id",id),(rs,n)->new CandidateIdentity(rs.getString("binding_id"),rs.getString("capability_code"),rs.getString("provider_type"),readMap(rs.getString("metadata_json"))));}catch(EmptyResultDataAccessException ex){throw new IllegalArgumentException("Capability Binding does not exist: "+id);}}

    private Map<String,Integer> exclusionSummary(List<CandidateEval> xs){Map<String,Integer> m=new TreeMap<>();for(CandidateEval x:xs)for(String r:x.reasons())m.merge(r,1,Integer::sum);return Map.copyOf(m);}private String bindingClass(String type,Map<String,Object> meta){return switch(type){case "INTERNAL_SERVICE"->"LOCAL_DETERMINISTIC";case "MANAGED_AGENT"->"LOCAL_AGENT";case "REMOTE_A2A_AGENT"->"EXTERNAL_AGENT";case "MCP_TOOL"->"LOCAL".equalsIgnoreCase(str(meta,"trustBoundary"))?"LOCAL_DETERMINISTIC":"EXTERNAL_TOOL";default->"EXTERNAL_AGENT";};}
    private BigDecimal nz(BigDecimal v){return v==null?BigDecimal.ZERO:v.max(BigDecimal.ZERO).min(BigDecimal.valueOf(100));}private String value(Map<String,Object> m,String key,String fallback){String v=str(m,key);return blank(v)?fallback:v;}private String stripPrefix(String v,String prefix){if(blank(v))return null;return v.startsWith(prefix)?v.substring(prefix.length()):v;}private String taskId(String ref){if(blank(ref))return null;return ref.startsWith("task:")?ref.substring(5):ref;}
    private String digest(Object value){try{byte[] bytes=json.writeValueAsString(value).getBytes(StandardCharsets.UTF_8);byte[] h=MessageDigest.getInstance("SHA-256").digest(bytes);return HexFormat.of().formatHex(h);}catch(Exception e){throw new IllegalStateException("Unable to digest routing evidence",e);}}private String write(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalStateException("Unable to serialize routing evidence",e);}}private List<String> readStrings(String v){try{return blank(v)?List.of():json.readValue(v,STRING_LIST);}catch(Exception e){return List.of();}}private Map<String,Object> readMap(String v){try{return blank(v)?Map.of():json.readValue(v,OBJECT_MAP);}catch(Exception e){return Map.of();}}private Map<String,Integer> readIntMap(String v){Map<String,Object> raw=readMap(v);Map<String,Integer> out=new LinkedHashMap<>();for(var e:raw.entrySet())out.put(e.getKey(),Integer.parseInt(String.valueOf(e.getValue())));return Map.copyOf(out);}private CapabilityRequirement readRequirement(String v){try{return json.readValue(v,CapabilityRequirement.class);}catch(Exception e){throw new IllegalStateException("CapabilityRequirement cannot be read",e);}}
    private String str(Map<String,?> m,String k){Object v=m==null?null:m.get(k);return v==null?null:String.valueOf(v);}private String upper(String v){return blank(v)?"":v.trim().toUpperCase(Locale.ROOT).replace(' ','_');}private boolean blank(String v){return v==null||v.isBlank();}private String required(String v,String f){if(blank(v))throw new IllegalArgumentException(f+" is required");return v.trim();}private String tenant(String v){return required(v,"tenantId");}
    private void bind(String t){IamTenantExecutionContext c=IamTenantContextHolder.current().orElse(null);if(c!=null&&!"INSTANCE".equalsIgnoreCase(c.tenantId())&&!t.equals(c.tenantId()))throw new IllegalArgumentException("Tenant context mismatch for Routing Authority");jdbc.getJdbcTemplate().queryForObject("select set_config('app.current_tenant_id', ?, true)",String.class,t);jdbc.getJdbcTemplate().queryForObject("select set_config('app.current_actor_id', ?, true)",String.class,actor());}private String actor(){IamTenantExecutionContext c=IamTenantContextHolder.current().orElse(null);return c==null||blank(c.actorId())?"a0-r6-routing-shadow":c.actorId();}

    private record PlanHeader(String planId,int currentRevision,String taskRef){} private record Step(String stepId,CapabilityRequirement requirement,String sideEffect,String writeSemantics){} private record FlowContext(String flowId,String ruleId){} private record LegacyAssignment(String assignmentId,String agentId,String poolId){} private record CandidateIdentity(String bindingId,String capabilityCode,String providerType,Map<String,Object> metadata){}
    private record FlowConstraint(List<String> allowedPools,List<String> allowedIds,List<String> allowedClasses,List<String> excludedIds){static final FlowConstraint NONE=new FlowConstraint(List.of(),List.of(),List.of(),List.of());boolean allows(Candidate c){return !excludedIds.contains(c.bindingId())&&(allowedIds.isEmpty()||allowedIds.contains(c.bindingId()))&&(allowedClasses.isEmpty()||allowedClasses.contains(c.bindingClass()))&&(allowedPools.isEmpty()||(!blankStatic(c.agentPoolId())&&allowedPools.contains(c.agentPoolId())));}private static boolean blankStatic(String v){return v==null||v.isBlank();}}
    private record Candidate(String bindingId,String capabilityCode,String providerId,String providerType,String providerRef,String providerStatus,List<String> operations,String trustStatus,OffsetDateTime staleAfter,Map<String,Object> metadata,String agentPoolId,String observationId,boolean available,boolean healthy,boolean capacityAvailable,BigDecimal quality,BigDecimal reliability,Long latency,BigDecimal cost,BigDecimal load,BigDecimal locality,OffsetDateTime observationExpiresAt,String adapterId,String adapterType,String runtimeRef,Map<String,Object> adapterConfig,String bindingClass){Candidate(String bindingId,String capabilityCode,String providerId,String providerType,String providerRef,String providerStatus,List<String> operations,String trustStatus,OffsetDateTime staleAfter,Map<String,Object> metadata,String agentPoolId,String observationId,boolean available,boolean healthy,boolean capacityAvailable,BigDecimal quality,BigDecimal reliability,Long latency,BigDecimal cost,BigDecimal load,BigDecimal locality,OffsetDateTime observationExpiresAt,String adapterId,String adapterType,String runtimeRef,Map<String,Object> adapterConfig){this(bindingId,capabilityCode,providerId,providerType,providerRef,providerStatus,operations,trustStatus,staleAfter,metadata,agentPoolId,observationId,available,healthy,capacityAvailable,quality,reliability,latency,cost,load,locality,observationExpiresAt,adapterId,adapterType,runtimeRef,adapterConfig,null);}Candidate withBindingClass(String c){return new Candidate(bindingId,capabilityCode,providerId,providerType,providerRef,providerStatus,operations,trustStatus,staleAfter,metadata,agentPoolId,observationId,available,healthy,capacityAvailable,quality,reliability,latency,cost,load,locality,observationExpiresAt,adapterId,adapterType,runtimeRef,adapterConfig,c);}}
    private record CandidateEval(Candidate c,String result,List<String> reasons,Map<String,BigDecimal> dims,BigDecimal score){String digestMaterial(){return c.bindingId()+"|"+c.providerId()+"|"+result+"|"+reasons+"|"+score;}}
}
