package com.opensocket.aievent.core.integration.issue;
import java.time.OffsetDateTime; import java.util.*; import java.util.concurrent.ConcurrentHashMap;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.context.annotation.Profile; import org.springframework.stereotype.Repository;
@Repository @Profile("!prod") @ConditionalOnProperty(prefix="integration-sync",name="store",havingValue="MEMORY",matchIfMissing=true)
public class InMemoryIssueSyncRepository implements IssueSyncRepository {
 private final Map<String,IssueRelationship> relationships=new ConcurrentHashMap<>(); private final Map<String,IntegrationOutboxEntry> outbox=new ConcurrentHashMap<>(); private final Map<String,IntegrationInboxEntry> inbox=new ConcurrentHashMap<>(); private final Map<String,IntegrationSyncAttempt> attempts=new ConcurrentHashMap<>(); private final Map<String,IntegrationDeadLetter> dead=new ConcurrentHashMap<>(); private final Map<String,IntegrationConflict> conflicts=new ConcurrentHashMap<>(); private final Map<String,IntegrationCircuitBreaker> circuits=new ConcurrentHashMap<>(); private String k(String t,String id){return t+":"+id;}
 public IssueRelationship saveRelationship(IssueRelationship v){relationships.put(k(v.tenantId(),v.relationshipId()),v);return v;} public Optional<IssueRelationship> findRelationship(String t,String id){return Optional.ofNullable(relationships.get(k(t,id)));} public List<IssueRelationship> listRelationships(String t,String link,int n){return relationships.values().stream().filter(v->t.equals(v.tenantId())&&(link==null||link.equals(v.fromTaskIssueLinkId())||link.equals(v.toTaskIssueLinkId()))).sorted(Comparator.comparing(IssueRelationship::createdAt).reversed()).limit(n).toList();}
 public List<String> listDueTenants(OffsetDateTime now,int n){return outbox.values().stream().filter(v->(v.status()==IntegrationOutboxStatus.PENDING||v.status()==IntegrationOutboxStatus.FAILED_RETRYABLE)&&!v.nextAttemptAt().isAfter(now)&&(v.claimUntil()==null||v.claimUntil().isBefore(now))).map(IntegrationOutboxEntry::tenantId).distinct().sorted().limit(n).toList();}
 public IntegrationOutboxEntry saveOutbox(IntegrationOutboxEntry v){outbox.put(k(v.tenantId(),v.outboxId()),v);return v;} public Optional<IntegrationOutboxEntry> findOutbox(String t,String id){return Optional.ofNullable(outbox.get(k(t,id)));} public Optional<IntegrationOutboxEntry> findOutboxByIdempotencyKey(String t,String key){return outbox.values().stream().filter(v->t.equals(v.tenantId())&&key.equals(v.idempotencyKey())).findFirst();} public List<IntegrationOutboxEntry> claimDue(String t,String w,OffsetDateTime now,OffsetDateTime until,int n){List<IntegrationOutboxEntry> r=new ArrayList<>();outbox.values().stream().filter(v->t.equals(v.tenantId())&&(v.status()==IntegrationOutboxStatus.PENDING||v.status()==IntegrationOutboxStatus.FAILED_RETRYABLE)&&!v.nextAttemptAt().isAfter(now)&&(v.claimUntil()==null||v.claimUntil().isBefore(now))).sorted(Comparator.comparingInt(IntegrationOutboxEntry::priority).thenComparing(IntegrationOutboxEntry::createdAt)).limit(n).forEach(v->{var x=new IntegrationOutboxEntry(v.tenantId(),v.outboxId(),v.aggregateType(),v.aggregateId(),v.taskId(),v.taskIssueLinkId(),v.issueRelationshipId(),v.connectionId(),v.projectMappingId(),v.operationType(),v.eventType(),v.payloadJson(),v.payloadHash(),v.idempotencyKey(),IntegrationOutboxStatus.CLAIMED,v.priority(),v.attemptCount(),v.maxAttempts(),v.nextAttemptAt(),w,until,v.lastErrorCode(),v.lastErrorMessage(),v.correlationId(),v.causationId(),v.createdAt(),now,v.completedAt());saveOutbox(x);r.add(x);});return r;}
 public IntegrationInboxEntry saveInbox(IntegrationInboxEntry v){inbox.put(k(v.tenantId(),v.inboxId()),v);return v;} public Optional<IntegrationInboxEntry> findInboxByProviderEvent(String t,String c,String e){return inbox.values().stream().filter(v->t.equals(v.tenantId())&&c.equals(v.connectionId())&&e.equals(v.providerEventId())).findFirst();} public List<IntegrationInboxEntry> listInbox(String t,int n){return inbox.values().stream().filter(v->t.equals(v.tenantId())).sorted(Comparator.comparing(IntegrationInboxEntry::receivedAt).reversed()).limit(n).toList();}
 public IntegrationSyncAttempt saveAttempt(IntegrationSyncAttempt v){attempts.put(k(v.tenantId(),v.attemptId()),v);return v;} public List<IntegrationSyncAttempt> listAttempts(String t,String o,int n){return attempts.values().stream().filter(v->t.equals(v.tenantId())&&o.equals(v.outboxId())).sorted(Comparator.comparingInt(IntegrationSyncAttempt::attemptNo)).limit(n).toList();}
 public IntegrationDeadLetter saveDeadLetter(IntegrationDeadLetter v){dead.put(k(v.tenantId(),v.deadLetterId()),v);return v;} public Optional<IntegrationDeadLetter> findDeadLetter(String t,String id){return Optional.ofNullable(dead.get(k(t,id)));} public Optional<IntegrationDeadLetter> findDeadLetterByOutbox(String t,String o){return dead.values().stream().filter(v->t.equals(v.tenantId())&&o.equals(v.outboxId())).findFirst();} public List<IntegrationDeadLetter> listDeadLetters(String t,IntegrationDeadLetterStatus s,int n){return dead.values().stream().filter(v->t.equals(v.tenantId())&&(s==null||s==v.status())).sorted(Comparator.comparing(IntegrationDeadLetter::openedAt).reversed()).limit(n).toList();}
 public IntegrationConflict saveConflict(IntegrationConflict v){conflicts.put(k(v.tenantId(),v.conflictId()),v);return v;} public Optional<IntegrationConflict> findConflict(String t,String id){return Optional.ofNullable(conflicts.get(k(t,id)));} public List<IntegrationConflict> listConflicts(String t,IntegrationConflictStatus s,int n){return conflicts.values().stream().filter(v->t.equals(v.tenantId())&&(s==null||s==v.status())).sorted(Comparator.comparing(IntegrationConflict::detectedAt).reversed()).limit(n).toList();}
 public IntegrationCircuitBreaker saveCircuitBreaker(IntegrationCircuitBreaker v){circuits.put(k(v.tenantId(),v.connectionId()),v);return v;} public Optional<IntegrationCircuitBreaker> findCircuitBreaker(String t,String c,String m){return Optional.ofNullable(circuits.get(k(t,c)));} public String mode(){return "MEMORY";}
}
