package com.opensocket.aievent.core.integration.issue;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import com.opensocket.aievent.core.issue.*;
import com.opensocket.aievent.core.task.*;
import com.opensocket.aievent.core.integration.identity.*;

@Service
public class IssueProjectionService implements IssueRelayProjectionMaterializer {
 private final TaskRepository tasks; private final TaskIssueLinkRepository links; private final IssueSyncRepository sync;
 private com.opensocket.aievent.core.integration.issue.projection.IssueProjectionStateService projectionStates; private IntegrationIdentityRepository identities; private ProjectionOutboxReliabilityService outboxReliability;
 public IssueProjectionService(TaskRepository tasks,TaskIssueLinkRepository links,IssueSyncRepository sync){this.tasks=tasks;this.links=links;this.sync=sync;}
 @Autowired(required=false) public void setIntegrationIdentityRepository(IntegrationIdentityRepository value){this.identities=value;}
 @Autowired(required=false) public void setProjectionStates(com.opensocket.aievent.core.integration.issue.projection.IssueProjectionStateService value){this.projectionStates=value;}
 @Autowired(required=false) public void setOutboxReliability(ProjectionOutboxReliabilityService value){this.outboxReliability=value;}

@Transactional public IssueProjectionResult createProjection(String tenantId,String taskId,IssueProjectionCommand command,String idempotencyKey,String correlationId){
  throw new IllegalStateException("LEGACY_EXTERNAL_ISSUE_PROJECTION_AUTHORITY_RETIRED");
    }

 @Transactional public IssueRelationship createRelationship(String tenantId,String fromLinkId,String toLinkId,IssueRelationshipType type,String idempotencyKey,String correlationId){
  throw new IllegalStateException("LEGACY_ISSUE_RELATION_AUTHORITY_RETIRED_USE_A2A");
    }

 @Override @Transactional public void materializeRelay(com.opensocket.aievent.core.integration.issue.projection.CrossProjectIssueRelay relay,
                                                    com.opensocket.aievent.core.integration.identity.IntegrationProjectMapping targetMapping,
                                                    com.opensocket.aievent.core.integration.identity.IntegrationConnection targetConnection,
                                                    String targetIssueId,String targetIssueUrl){
  throw new IllegalStateException("LEGACY_ISSUE_RELAY_RETIRED_USE_A2A");
    }

 @Transactional public WebhookReceipt receiveWebhook(String tenantId,String connectionId,String providerType,String providerEventId,String eventType,String externalProjectId,String externalIssueId,String externalStatus,boolean signatureVerified,String payloadJson,String correlationId){
  String tenant=req(tenantId,"tenantId"),connection=req(connectionId,"connectionId"),event=req(providerEventId,"providerEventId"),payload=validJson(payloadJson);String h=hash(payload);Optional<IntegrationInboxEntry> existing=sync.findInboxByProviderEvent(tenant,connection,event);
  if(existing.isPresent()){if(!h.equals(existing.get().payloadHash())){createReplayConflict(tenant,connection,externalProjectId,externalIssueId,existing.get().inboxId(),externalStatus,correlationId);throw new IllegalStateException(IssueSyncReasonCode.WEBHOOK_REPLAY_CONFLICT.name());}return new WebhookReceipt(existing.get(),true,false);}
  OffsetDateTime now=now();IntegrationInboxEntry inbox=new IntegrationInboxEntry(tenant,"inbox-"+UUID.randomUUID(),connection,nvl(providerType,"UNKNOWN"),event,nvl(eventType,"ISSUE_UPDATED"),externalProjectId,externalIssueId,signatureVerified,payload,h,signatureVerified?IntegrationInboxStatus.RECEIVED:IntegrationInboxStatus.REJECTED,0,now,signatureVerified?null:now,signatureVerified?null:IssueSyncReasonCode.WEBHOOK_SIGNATURE_INVALID.name(),signatureVerified?null:"Webhook signature verification failed.",nvl(correlationId,"corr-"+UUID.randomUUID()));sync.saveInbox(inbox);if(!signatureVerified)throw new IllegalStateException(IssueSyncReasonCode.WEBHOOK_SIGNATURE_INVALID.name());observeExternalStatus(tenant,inbox,externalStatus);return new WebhookReceipt(inbox,false,false);
 }

 @Transactional public List<IntegrationOutboxEntry> claimDue(String tenantId,String workerId,int limit){String tenant=req(tenantId,"tenantId");OffsetDateTime now=now();return sync.claimDue(tenant,req(workerId,"workerId"),now,now.plusMinutes(2),Math.max(1,Math.min(limit,100)));}

 @Transactional public IntegrationOutboxEntry startAttempt(String tenantId,String outboxId,String workerId){IntegrationOutboxEntry o=outbox(tenantId,outboxId);circuitAllows(o);OffsetDateTime now=now();IntegrationOutboxEntry v=copyOutbox(o,IntegrationOutboxStatus.IN_PROGRESS,o.attemptCount(),o.nextAttemptAt(),workerId,o.claimUntil(),null,null,null,now);IntegrationOutboxEntry saved=sync.saveOutbox(v);if(!blank(o.taskIssueLinkId())){TaskIssueLink l=link(o.tenantId(),o.taskIssueLinkId());if(IntegrationSyncStatus.PENDING.name().equals(l.getSyncStatus())||IntegrationSyncStatus.FAILED_RETRYABLE.name().equals(l.getSyncStatus())||IntegrationSyncStatus.FAILED_PERMANENT.name().equals(l.getSyncStatus())){l.setSyncStatus(IntegrationSyncStatus.IN_PROGRESS.name());l.setResourceVersion(l.getResourceVersion()+1);l.setUpdatedAt(now);links.save(l);}}return saved;}

 @Transactional public IntegrationOutboxEntry deferClaim(String tenantId,String outboxId,String workerId,String reasonCode,String reasonMessage){IntegrationOutboxEntry o=outbox(tenantId,outboxId);OffsetDateTime now=now();IntegrationOutboxEntry deferred=copyOutbox(o,IntegrationOutboxStatus.FAILED_RETRYABLE,o.attemptCount(),now.plusMinutes(5),null,null,nvl(reasonCode,IssueSyncReasonCode.INTEGRATION_CIRCUIT_OPEN.name()),reasonMessage,null,now);return sync.saveOutbox(deferred);}

 @Transactional public IntegrationOutboxEntry complete(String tenantId,String outboxId,String workerId,ProviderSyncResult result){IntegrationOutboxEntry o=ensureInProgress(tenantId,outboxId,workerId);if(result==null||!result.success())throw new IllegalArgumentException("successful Provider result is required");OffsetDateTime now=now();int attempt=o.attemptCount()+1;sync.saveAttempt(new IntegrationSyncAttempt(o.tenantId(),"sync-attempt-"+UUID.randomUUID(),o.outboxId(),attempt,workerId,"SUCCEEDED",result.providerStatus(),o.payloadHash(),result.responseSummary(),false,null,null,now,now,o.correlationId()));IntegrationOutboxEntry done=copyOutbox(o,IntegrationOutboxStatus.COMPLETED,attempt,o.nextAttemptAt(),null,null,null,null,now,now);sync.saveOutbox(done);updateLinkSuccess(o,result,now);if(projectionStates!=null&&!blank(o.taskIssueLinkId()))projectionStates.recordObservedSuccessByTaskIssueLink(o.tenantId(),o.taskIssueLinkId(),hash(nvl(result.responseSummary(),"provider-success")));closeCircuit(o,now);return done;}

 @Transactional public IntegrationOutboxEntry fail(String tenantId,String outboxId,String workerId,ProviderSyncResult result){IntegrationOutboxEntry o=ensureInProgress(tenantId,outboxId,workerId);if(result==null||result.success())throw new IllegalArgumentException("failed Provider result is required");OffsetDateTime now=now();int attempt=o.attemptCount()+1;sync.saveAttempt(new IntegrationSyncAttempt(o.tenantId(),"sync-attempt-"+UUID.randomUUID(),o.outboxId(),attempt,workerId,"FAILED",result.providerStatus(),o.payloadHash(),result.responseSummary(),result.retryable(),result.errorCode(),result.errorMessage(),now,now,o.correlationId()));boolean retry=result.retryable()&&attempt<o.maxAttempts();IntegrationOutboxStatus status=retry?IntegrationOutboxStatus.FAILED_RETRYABLE:IntegrationOutboxStatus.DEAD_LETTER;OffsetDateTime next=retry?now.plusSeconds(Math.min(3600L,(long)Math.pow(2,Math.min(attempt,10))*5L)):o.nextAttemptAt();IntegrationOutboxEntry failed=copyOutbox(o,status,attempt,next,null,null,result.errorCode(),result.errorMessage(),null,now);sync.saveOutbox(failed);updateLinkFailure(o,retry,result,now);if(projectionStates!=null&&!blank(o.taskIssueLinkId()))projectionStates.recordFailureByTaskIssueLink(o.tenantId(),o.taskIssueLinkId(),result.errorCode(),result.errorMessage(),retry);recordCircuitFailure(o,result.errorCode(),now);if(!retry){sync.saveDeadLetter(new IntegrationDeadLetter(o.tenantId(),"dead-letter-"+UUID.randomUUID(),o.outboxId(),o.taskId(),o.taskIssueLinkId(),o.operationType(),o.payloadJson(),o.payloadHash(),nvl(result.errorCode(),IssueSyncReasonCode.INTEGRATION_SYNC_DEAD_LETTERED.name()),result.errorMessage(),attempt,IntegrationDeadLetterStatus.OPEN,now,null,null,null,null,o.correlationId()));}return failed;}

 @Transactional public IntegrationOutboxEntry skipNotConfigured(String tenantId,String outboxId,String workerId,String reasonCode,String reasonMessage){IntegrationOutboxEntry o=claimedForTerminalSkip(tenantId,outboxId,workerId);OffsetDateTime now=now();int attempt=o.attemptCount()+1;String code=nvl(reasonCode,IssueSyncReasonCode.ISSUE_PROVIDER_NOT_CONFIGURED.name());String message=nvl(reasonMessage,"No governed Issue Provider is configured for this projection; terminal side-effect was skipped.");sync.saveAttempt(new IntegrationSyncAttempt(o.tenantId(),"sync-attempt-"+UUID.randomUUID(),o.outboxId(),attempt,workerId,"SKIPPED",null,o.payloadHash(),message,false,code,message,now,now,o.correlationId()));IntegrationOutboxEntry skipped=copyOutbox(o,IntegrationOutboxStatus.SKIPPED,attempt,o.nextAttemptAt(),null,null,code,message,now,now);sync.saveOutbox(skipped);updateLinkSkipped(o,message,now);return skipped;}

 @Transactional public IntegrationOutboxEntry retryDeadLetter(String tenantId,String deadLetterId,String actorId,String reason,String correlationId){return retryDeadLetter(tenantId,deadLetterId,actorId,reason,correlationId,"manual-retry:"+deadLetterId+":"+UUID.randomUUID());}
 @Transactional public IntegrationOutboxEntry retryDeadLetter(String tenantId,String deadLetterId,String actorId,String reason,String correlationId,String idempotencyKey){String tenant=req(tenantId,"tenantId");IntegrationDeadLetter d=sync.findDeadLetter(tenant,req(deadLetterId,"deadLetterId")).orElseThrow(()->new IllegalArgumentException("Dead letter not found: "+deadLetterId));if(d.status()!=IntegrationDeadLetterStatus.OPEN&&d.status()!=IntegrationDeadLetterStatus.RETRIED)throw new IllegalStateException("Dead letter is not replayable.");String key=req(idempotencyKey,"idempotencyKey");Optional<IntegrationOutboxEntry> prior=sync.findOutboxByIdempotencyKey(tenant,key);if(prior.isPresent())return prior.get();OffsetDateTime now=now();IntegrationOutboxEntry original=outbox(tenant,d.outboxId());IntegrationOutboxEntry retry=new IntegrationOutboxEntry(tenant,"outbox-"+UUID.randomUUID(),original.aggregateType(),original.aggregateId(),d.taskId(),d.taskIssueLinkId(),original.issueRelationshipId(),original.connectionId(),original.projectMappingId(),d.operationType(),original.eventType(),d.payloadJson(),d.payloadHash(),key,IntegrationOutboxStatus.PENDING,original.priority(),0,original.maxAttempts(),now,null,null,null,null,nvl(correlationId,original.correlationId()),original.outboxId(),now,now,null);sync.saveOutbox(retry);if(outboxReliability!=null)outboxReliability.register(retry);sync.saveDeadLetter(new IntegrationDeadLetter(tenant,d.deadLetterId(),d.outboxId(),d.taskId(),d.taskIssueLinkId(),d.operationType(),d.payloadJson(),d.payloadHash(),d.failureCode(),d.failureMessage(),d.attemptCount(),IntegrationDeadLetterStatus.RETRIED,d.openedAt(),now,null,actorId,reason,d.correlationId()));if(d.taskIssueLinkId()!=null){TaskIssueLink l=link(tenant,d.taskIssueLinkId());l.setSyncStatus(IntegrationSyncStatus.PENDING.name());l.setResourceVersion(l.getResourceVersion()+1);l.setUpdatedAt(now);links.save(l);}return retry;}

 @Transactional public IntegrationConflict resolveConflict(String tenantId,String conflictId,String actorId,String action,String reason){String tenant=req(tenantId,"tenantId");IntegrationConflict c=sync.findConflict(tenant,req(conflictId,"conflictId")).orElseThrow(()->new IllegalArgumentException("Conflict not found: "+conflictId));OffsetDateTime now=now();IntegrationConflict r=new IntegrationConflict(tenant,c.conflictId(),c.taskId(),c.taskIssueLinkId(),c.inboxId(),c.conflictType(),c.taskStatus(),c.externalIssueStatus(),c.detailJson(),IntegrationConflictStatus.RESOLVED,c.detectedAt(),now,req(actorId,"actorId"),req(action,"resolutionAction"),reason,c.correlationId());sync.saveConflict(r);if(c.taskIssueLinkId()!=null){TaskIssueLink l=link(tenant,c.taskIssueLinkId());l.setConflictStatus("RESOLVED");l.setResourceVersion(l.getResourceVersion()+1);l.setUpdatedAt(now);links.save(l);}return r;}

 @Transactional public IssueRelationship materializeRelay(String tenantId,TaskIssueLink source,TaskIssueLink target,IssueRelationshipType type,String idempotencyKey,String correlationId){
  throw new IllegalStateException("LEGACY_ISSUE_RELAY_RETIRED_USE_A2A");
    }

 public List<TaskIssueLink> taskIssues(String tenant,String task){return links.findAllByTenantAndTaskId(req(tenant,"tenantId"),req(task,"taskId"));}
 public List<IssueRelationship> relationships(String tenant,String link,int limit){return sync.listRelationships(req(tenant,"tenantId"),link,Math.max(1,limit));}
 public List<IntegrationDeadLetter> deadLetters(String tenant,IntegrationDeadLetterStatus status,int limit){return sync.listDeadLetters(req(tenant,"tenantId"),status,Math.max(1,limit));}
 public List<IntegrationConflict> conflicts(String tenant,IntegrationConflictStatus status,int limit){return sync.listConflicts(req(tenant,"tenantId"),status,Math.max(1,limit));}
 public List<IntegrationInboxEntry> inbox(String tenant,int limit){return sync.listInbox(req(tenant,"tenantId"),Math.max(1,limit));}
 public List<IntegrationSyncAttempt> attempts(String tenant,String outbox,int limit){return sync.listAttempts(req(tenant,"tenantId"),req(outbox,"outboxId"),Math.max(1,limit));}

 private void observeExternalStatus(String tenant,IntegrationInboxEntry inbox,String externalStatus){if(blank(inbox.externalIssueId()))return;Optional<TaskIssueLink> found=links.findByExternalIssue(tenant,inbox.connectionId(),inbox.externalProjectId(),inbox.externalIssueId());if(found.isEmpty())return;TaskIssueLink l=found.get();l.setLastProviderEventId(inbox.providerEventId());l.setIssueStatus(externalStatus);l.setResourceVersion(l.getResourceVersion()+1);l.setUpdatedAt(now());TaskRecord t=task(tenant,l.getTaskId());if(isClosed(externalStatus)&&t.getStatus()!=null&&!t.getStatus().isTerminal()){l.setSyncStatus(IntegrationSyncStatus.CONFLICT.name());l.setConflictStatus("OPEN");IntegrationConflict c=new IntegrationConflict(tenant,"conflict-"+UUID.randomUUID(),t.getTaskId(),l.getLinkId(),inbox.inboxId(),IssueSyncReasonCode.EXTERNAL_ISSUE_CLOSED_TASK_ACTIVE.name(),t.getStatus().name(),externalStatus,json(Map.of("authority","OpenDispatch","action","Task status was not changed")),IntegrationConflictStatus.OPEN,now(),null,null,null,null,inbox.correlationId());sync.saveConflict(c);if(projectionStates!=null)projectionStates.recordConflictByTaskIssueLink(tenant,l.getLinkId(),hash(nvl(externalStatus,"UNKNOWN")),"External Issue status drift did not change Task authority.");}links.save(l);}
 private void createReplayConflict(String tenant,String connection,String project,String issue,String inboxId,String status,String corr){links.findByExternalIssue(tenant,connection,project,issue).ifPresent(l->{TaskRecord t=task(tenant,l.getTaskId());sync.saveConflict(new IntegrationConflict(tenant,"conflict-"+UUID.randomUUID(),t.getTaskId(),l.getLinkId(),inboxId,IssueSyncReasonCode.WEBHOOK_REPLAY_CONFLICT.name(),t.getStatus()==null?null:t.getStatus().name(),status,json(Map.of("providerEventReplay","payload hash mismatch")),IntegrationConflictStatus.OPEN,now(),null,null,null,null,corr));});}
 private IntegrationOutboxEntry claimedForTerminalSkip(String tenant,String id,String worker){IntegrationOutboxEntry o=outbox(tenant,id);String expected=req(worker,"workerId");if(o.status()!=IntegrationOutboxStatus.CLAIMED&&o.status()!=IntegrationOutboxStatus.IN_PROGRESS)throw new IllegalStateException("INTEGRATION_OUTBOX_NOT_CLAIMED_FOR_SKIP:"+o.status());if(!blank(o.claimedBy())&&!expected.equals(o.claimedBy()))throw new IllegalStateException("INTEGRATION_OUTBOX_CLAIM_OWNER_MISMATCH");return o;}
 private IntegrationOutboxEntry ensureInProgress(String tenant,String id,String worker){IntegrationOutboxEntry o=outbox(tenant,id);return o.status()==IntegrationOutboxStatus.IN_PROGRESS?o:startAttempt(tenant,id,worker);}
 private void updateLinkSuccess(IntegrationOutboxEntry o,ProviderSyncResult r,OffsetDateTime now){if(blank(o.taskIssueLinkId()))return;TaskIssueLink l=link(o.tenantId(),o.taskIssueLinkId());l.setExternalIssueId(nvl(r.externalIssueId(),l.getExternalIssueId()));l.setExternalIssueKey(nvl(r.externalIssueKey(),l.getExternalIssueKey()));l.setExternalIssueUrl(nvl(r.externalIssueUrl(),l.getExternalIssueUrl()));l.setIssueId(l.getExternalIssueId());l.setIssueUrl(l.getExternalIssueUrl());l.setIssueStatus(nvl(r.externalIssueStatus(),l.getIssueStatus()));l.setLinkState(TaskIssueLink.LINK_EXTERNAL_CONFIRMED);l.setSyncStatus(IntegrationSyncStatus.SYNCED.name());l.setLastSyncedAt(now);l.setSyncError(null);l.setIssueRetryable(false);l.setResourceVersion(l.getResourceVersion()+1);l.setUpdatedAt(now);links.save(l);if(!blank(o.issueRelationshipId()))sync.findRelationship(o.tenantId(),o.issueRelationshipId()).ifPresent(rel->sync.saveRelationship(new IssueRelationship(rel.tenantId(),rel.relationshipId(),rel.fromTaskIssueLinkId(),rel.toTaskIssueLinkId(),rel.relationshipType(),r.providerRelationId(),IntegrationSyncStatus.SYNCED,rel.payloadHash(),rel.idempotencyKey(),null,null,rel.resourceVersion()+1,rel.createdAt(),now)));}
 private void updateLinkFailure(IntegrationOutboxEntry o,boolean retry,ProviderSyncResult r,OffsetDateTime now){if(blank(o.taskIssueLinkId()))return;TaskIssueLink l=link(o.tenantId(),o.taskIssueLinkId());l.setSyncStatus((retry?IntegrationSyncStatus.FAILED_RETRYABLE:IntegrationSyncStatus.FAILED_PERMANENT).name());l.setIssueRetryable(retry);l.setSyncError(r.errorMessage());l.setResourceVersion(l.getResourceVersion()+1);l.setUpdatedAt(now);links.save(l);}
 private void updateLinkSkipped(IntegrationOutboxEntry o,String message,OffsetDateTime now){if(blank(o.taskIssueLinkId()))return;TaskIssueLink l=link(o.tenantId(),o.taskIssueLinkId());l.setSyncStatus(IntegrationSyncStatus.DISABLED.name());l.setIssueRetryable(false);l.setSyncError(message);l.setResourceVersion(l.getResourceVersion()+1);l.setUpdatedAt(now);links.save(l);}
 private void circuitAllows(IntegrationOutboxEntry o){if(blank(o.connectionId()))return;sync.findCircuitBreaker(o.tenantId(),o.connectionId(),o.projectMappingId()).ifPresent(c->{if(c.state()==IntegrationCircuitState.OPEN&&(c.nextProbeAt()==null||c.nextProbeAt().isAfter(now())))throw new IllegalStateException(IssueSyncReasonCode.INTEGRATION_CIRCUIT_OPEN.name());});}
 private void recordCircuitFailure(IntegrationOutboxEntry o,String code,OffsetDateTime now){if(blank(o.connectionId()))return;IntegrationCircuitBreaker c=sync.findCircuitBreaker(o.tenantId(),o.connectionId(),o.projectMappingId()).orElse(new IntegrationCircuitBreaker(o.tenantId(),o.connectionId(),o.projectMappingId(),IntegrationCircuitState.CLOSED,0,5,null,null,null,null,null,now));int failures=c.consecutiveFailures()+1;boolean open=failures>=c.failureThreshold();sync.saveCircuitBreaker(new IntegrationCircuitBreaker(c.tenantId(),c.connectionId(),c.projectMappingId(),open?IntegrationCircuitState.OPEN:IntegrationCircuitState.CLOSED,failures,c.failureThreshold(),open?now:c.openedAt(),open?now.plusMinutes(5):c.nextProbeAt(),c.lastSuccessAt(),now,code,now));}
 private void closeCircuit(IntegrationOutboxEntry o,OffsetDateTime now){if(blank(o.connectionId()))return;IntegrationCircuitBreaker c=sync.findCircuitBreaker(o.tenantId(),o.connectionId(),o.projectMappingId()).orElse(new IntegrationCircuitBreaker(o.tenantId(),o.connectionId(),o.projectMappingId(),IntegrationCircuitState.CLOSED,0,5,null,null,null,null,null,now));sync.saveCircuitBreaker(new IntegrationCircuitBreaker(c.tenantId(),c.connectionId(),c.projectMappingId(),IntegrationCircuitState.CLOSED,0,c.failureThreshold(),null,null,now,c.lastFailureAt(),null,now));}
 private IntegrationOutboxEntry copyOutbox(IntegrationOutboxEntry o,IntegrationOutboxStatus status,int attempts,OffsetDateTime next,String worker,OffsetDateTime claim,String code,String message,OffsetDateTime completed,OffsetDateTime updated){return new IntegrationOutboxEntry(o.tenantId(),o.outboxId(),o.aggregateType(),o.aggregateId(),o.taskId(),o.taskIssueLinkId(),o.issueRelationshipId(),o.connectionId(),o.projectMappingId(),o.operationType(),o.eventType(),o.payloadJson(),o.payloadHash(),o.idempotencyKey(),status,o.priority(),attempts,o.maxAttempts(),next,worker,claim,code,message,o.correlationId(),o.causationId(),o.createdAt(),updated,completed);}
 private IntegrationOperationType operation(IssueProjectionStrategy s){return switch(s){case APPEND_TO_PARENT_ISSUE->IntegrationOperationType.ISSUE_COMMENT_APPEND;case LINK_EXISTING_ISSUE->IntegrationOperationType.ISSUE_LINK_EXISTING;default->IntegrationOperationType.ISSUE_CREATE;};}
 private String event(IntegrationOperationType o){return switch(o){case ISSUE_COMMENT_APPEND->"ISSUE_COMMENT_APPEND_REQUESTED";case ISSUE_RELATION_CREATE->"ISSUE_RELATION_CREATE_REQUESTED";case ISSUE_LINK_EXISTING->"ISSUE_LINK_EXISTING_REQUESTED";default->"ISSUE_CREATE_REQUESTED";};}

 private void applyScopeSnapshot(TaskIssueLink link,TaskRecord task,OffsetDateTime at){
  if(link==null||task==null)throw new IllegalArgumentException("Task Issue scope source is required");
  link.setOwnerDepartmentId(task.getOwnerDepartmentId());link.setOwnerGroupId(task.getOwnerGroupId());
  link.setRequesterDepartmentId(task.getRequesterDepartmentId());link.setRequesterGroupId(task.getRequesterGroupId());
  link.setExecutorDepartmentId(task.getExecutorDepartmentId());link.setExecutorGroupId(task.getExecutorGroupId());
  boolean resolved=(task.getOwnerDepartmentId()!=null&&!task.getOwnerDepartmentId().isBlank()&&!"UNASSIGNED".equalsIgnoreCase(task.getOwnerDepartmentId()))||task.getOwnerGroupId()!=null;
  link.setScopeStatus(resolved?"RESOLVED":"UNRESOLVED");link.setScopeSourceType("TASK");link.setScopeSourceId(task.getTaskId());
  link.setScopeSourceVersion(task.getVersion());link.setScopeInheritedAt(at);
  if(!resolved)throw new IllegalStateException("RS5_ISSUE_SCOPE_UNRESOLVED");
 }

 private void applyExternal(TaskIssueLink l,Map<String,Object> p){l.setExternalIssueId(text(p.get("externalIssueId")));l.setExternalIssueKey(nvl(text(p.get("externalIssueKey")),text(p.get("issueKey"))));l.setExternalIssueUrl(text(p.get("externalIssueUrl")));l.setIssueId(l.getExternalIssueId());l.setIssueUrl(l.getExternalIssueUrl());l.setIssueStatus(text(p.get("externalIssueStatus")));}
 private TaskRecord task(String t,String id){return tasks.findByTenantAndId(t,id).orElseThrow(()->new IllegalArgumentException("Task not found: "+id));} private TaskIssueLink link(String t,String id){return links.findByTenantAndLinkId(t,id).orElseThrow(()->new IllegalArgumentException("Task-Issue Link not found: "+id));} private IntegrationOutboxEntry outbox(String t,String id){return sync.findOutbox(req(t,"tenantId"),req(id,"outboxId")).orElseThrow(()->new IllegalArgumentException("Outbox item not found: "+id));}
 private MappingBinding mappingBinding(String tenant,String mappingId){if(blank(mappingId))return new MappingBinding(1,null);if(identities==null)throw new IllegalStateException("PROJECT_MAPPING_REPOSITORY_REQUIRED");var m=identities.findMapping(tenant,mappingId).orElseThrow(()->new IllegalArgumentException("Project Mapping not found: "+mappingId));if(m.lifecycleStatus()!=ProjectMappingLifecycle.ACTIVE)throw new IllegalStateException("PROJECT_MAPPING_NOT_ACTIVE");return new MappingBinding(m.mappingVersion(),m.metadataSchemaHash());} private record MappingBinding(int version,String schemaHash){}
 private String stableId(String prefix,String value){return prefix+hash(String.valueOf(value)).substring(0,32);}
 private boolean isClosed(String s){return s!=null&&Set.of("CLOSED","DONE","RESOLVED","CANCELLED").contains(s.trim().toUpperCase(Locale.ROOT));} private OffsetDateTime now(){return OffsetDateTime.now(ZoneOffset.UTC);} private String req(String v,String n){if(blank(v))throw new IllegalArgumentException(n+" is required");return v.trim();} private boolean blank(String v){return v==null||v.isBlank();} private String nvl(String v,String d){return blank(v)?d:v;} private String text(Object v){return v==null?null:String.valueOf(v);}
 private String validJson(String s){String v=blank(s)?"{}":s.trim();if(!(v.startsWith("{")||v.startsWith("[")))throw new IllegalArgumentException("Webhook payload must be JSON.");return v;}
 private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private String json(Object v){if(v==null)return "null";if(v instanceof String s)return "\""+s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n")+"\"";if(v instanceof Number||v instanceof Boolean)return String.valueOf(v);if(v instanceof Map<?,?> m){TreeMap<String,Object> sorted=new TreeMap<>();m.forEach((k,x)->sorted.put(String.valueOf(k),x));StringJoiner j=new StringJoiner(",","{","}");sorted.forEach((k,x)->j.add(json(k)+":"+json(x)));return j.toString();}if(v instanceof Iterable<?> it){StringJoiner j=new StringJoiner(",","[","]");for(Object x:it)j.add(json(x));return j.toString();}return json(String.valueOf(v));}
}
