package com.opensocket.aievent.core.integration.issue;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import com.opensocket.aievent.core.integration.issue.projection.*;import com.opensocket.aievent.core.integration.identity.*;
@Service public class ProjectionOutboxReliabilityService {
 private final ProjectionOutboxReliabilityRepository repository; private final IssueProjectionStateRepository projections; private final IntegrationIdentityRepository identities;
 public ProjectionOutboxReliabilityService(ProjectionOutboxReliabilityRepository repository,IssueProjectionStateRepository projections,IntegrationIdentityRepository identities){this.repository=repository;this.projections=projections;this.identities=identities;}
 @Transactional public ProjectionOutboxReliability register(IntegrationOutboxEntry outbox){return repository.find(outbox.tenantId(),outbox.outboxId()).orElseGet(()->{IssueProjectionState s=outbox.taskIssueLinkId()==null?null:projections.findByTaskIssueLink(outbox.tenantId(),outbox.taskIssueLinkId()).orElse(null);String projectionId=s==null?outbox.aggregateId():s.projectionId();long sequence=s==null?1:s.operationSequence();long version=s==null?1:s.projectionVersion();int mapping=s==null?1:s.projectMappingVersion();String canonical=s==null?outbox.payloadHash():nvl(s.canonicalDocumentHash(),outbox.payloadHash());String credential=credentialVersion(outbox);String fingerprint=hash(projectionId+"|"+sequence+"|"+version+"|"+canonical+"|"+mapping+"|"+credential);String marker="opendispatch:"+projectionId+":"+sequence+":"+version;OffsetDateTime now=now();return repository.save(new ProjectionOutboxReliability(outbox.tenantId(),outbox.outboxId(),projectionId,sequence,version,canonical,mapping,credential,fingerprint,ProjectionOutboxReliabilityStatus.PENDING,null,null,null,null,1,now,null,"READBACK_ON_UNCERTAIN",marker,null,null,null,null,null,now,now));});}
 @Transactional public List<ProjectionOutboxReliability> claimDue(String workerId,int limit){return repository.claimDue(req(workerId,"workerId"),now(),now().plusSeconds(90),Math.max(1,Math.min(limit,100)));}
 @Transactional public ProjectionOutboxReliability transition(ProjectionOutboxReliability current,ProjectionOutboxReliabilityStatus status,String workerId,String errorCode,String errorMessage,OffsetDateTime retryAt,OffsetDateTime rateLimitReset,String attemptId){OffsetDateTime now=now();if(current.status()!=ProjectionOutboxReliabilityStatus.DEAD_LETTER&&current.claimOwner()!=null&&!current.claimOwner().equals(workerId))throw new IllegalStateException("PROJECTION_OUTBOX_CLAIM_OWNER_MISMATCH");boolean retainClaim=status==ProjectionOutboxReliabilityStatus.SENDING||status==ProjectionOutboxReliabilityStatus.SENT||status==ProjectionOutboxReliabilityStatus.VERIFYING;String owner=retainClaim?current.claimOwner():null;String token=retainClaim?current.claimTokenHash():null;OffsetDateTime until=retainClaim?current.claimUntil():null;OffsetDateTime heartbeat=retainClaim?current.heartbeatAt():null;OffsetDateTime sent=(status==ProjectionOutboxReliabilityStatus.SENT||status==ProjectionOutboxReliabilityStatus.VERIFYING)?now:(status==ProjectionOutboxReliabilityStatus.FAILED_RETRYABLE?null:current.sentAt());ProjectionOutboxReliability next=new ProjectionOutboxReliability(current.tenantId(),current.outboxId(),current.projectionId(),current.operationSequence(),current.projectionVersion(),current.canonicalDocumentHash(),current.mappingVersion(),current.credentialVersion(),current.providerRequestFingerprint(),status,owner,token,until,heartbeat,current.rowVersion()+1,retryAt,rateLimitReset,current.verificationMode(),current.externalIdempotencyMarker(),attemptId,errorCode,safe(errorMessage),sent,status==ProjectionOutboxReliabilityStatus.ACKNOWLEDGED?now:current.acknowledgedAt(),current.createdAt(),now);return repository.saveExpectedVersion(next,current.rowVersion());}
 public boolean heartbeat(ProjectionOutboxReliability value,String workerId){return repository.heartbeat(value.tenantId(),value.outboxId(),workerId,value.claimTokenHash(),value.rowVersion(),now(),now().plusSeconds(90));}
 public int nextAttemptNo(String tenantId,String outboxId){return repository.listAttempts(req(tenantId,"tenantId"),req(outboxId,"outboxId"),500).size()+1;}
 public ProjectionProviderAttemptEvidence appendAttempt(ProjectionOutboxReliability w,int attemptNo,String workerId,String status,ProviderSyncResult result,OffsetDateTime retryAt,OffsetDateTime started,OffsetDateTime completed,String correlation){String id="provider-attempt-"+hash(w.outboxId()+"|"+attemptNo+"|"+w.providerRequestFingerprint()).substring(0,32);return repository.appendAttempt(new ProjectionProviderAttemptEvidence(w.tenantId(),id,w.outboxId(),w.projectionId(),attemptNo,w.operationSequence(),w.projectionVersion(),w.canonicalDocumentHash(),w.mappingVersion(),w.credentialVersion(),w.providerRequestFingerprint(),w.externalIdempotencyMarker(),workerId,status,result==null?null:result.providerStatus(),result!=null&&result.retryable(),result==null?null:result.errorCode(),result==null?null:safe(result.responseSummary()),retryAt,started,completed,correlation));}
 public ProjectionReadbackEvidence appendReadback(ProjectionOutboxReliability w,ProjectionProviderReadbackResult r,String correlation){OffsetDateTime now=now();String id="readback-"+hash(w.outboxId()+"|"+w.rowVersion()+"|"+now).substring(0,32);return repository.appendReadback(new ProjectionReadbackEvidence(w.tenantId(),id,w.outboxId(),w.projectionId(),w.externalIdempotencyMarker(),r.status(),r.externalIssueId(),r.externalIssueKey(),r.observedFingerprint(),r.reasonCode(),safe(r.safeSummary()),now,correlation));}
 public List<ProjectionOutboxReliability> list(String tenant,ProjectionOutboxReliabilityStatus status,int limit){return repository.list(req(tenant,"tenantId"),status,limit);} public List<ProjectionProviderAttemptEvidence> attempts(String t,String o,int l){return repository.listAttempts(req(t,"tenantId"),req(o,"outboxId"),l);} public List<ProjectionReadbackEvidence> readbacks(String t,String o,int l){return repository.listReadbacks(req(t,"tenantId"),req(o,"outboxId"),l);}

 private String credentialVersion(IntegrationOutboxEntry outbox){if(outbox.projectMappingId()==null||outbox.projectMappingId().isBlank())return "NO_MAPPING";IntegrationProjectMapping m=identities.findMapping(outbox.tenantId(),outbox.projectMappingId()).orElse(null);if(m==null)return "MAPPING_NOT_FOUND";String principal=switch(outbox.operationType()){case ISSUE_COMMENT_APPEND,ISSUE_RELAY_BACKLINK->m.commentPrincipalId();case ISSUE_RELATION_CREATE->m.relationPrincipalId();default->m.createPrincipalId();};if(principal==null||principal.isBlank())return "PRINCIPAL_UNBOUND";return identities.listCredentials(outbox.tenantId(),principal,200).stream().filter(c->c.status()==IntegrationCredentialStatus.ACTIVE||c.status()==IntegrationCredentialStatus.GRACE_PERIOD).max(Comparator.comparingLong(IntegrationCredentialMetadata::version)).map(c->nvl(c.secretVersion(),"credential-v"+c.version())).orElse("CREDENTIAL_NOT_ACTIVE");}
 private OffsetDateTime now(){return OffsetDateTime.now(ZoneOffset.UTC);} private String req(String v,String n){if(v==null||v.isBlank())throw new IllegalArgumentException(n+" is required");return v.trim();} private String nvl(String v,String d){return v==null||v.isBlank()?d:v;} private String safe(String v){if(v==null)return null;String s=v.replaceAll("(?i)(authorization|password|secret|token|credential)\\s*[:=]\\s*[^,;\\s]+","$1=[REDACTED]");return s.length()>1000?s.substring(0,1000):s;} private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
