package com.opensocket.aievent.core.issuetracking.application.relay;
import java.time.OffsetDateTime; import java.util.*; import java.util.concurrent.ConcurrentHashMap; import com.opensocket.aievent.core.issuetracking.relay.*;
public final class InMemoryRelayGovernanceRepository implements RelayGovernanceRepository { private final Map<String,CanonicalIssueRelation> relations=new ConcurrentHashMap<>();private final Map<String,RelayTopology> topologies=new ConcurrentHashMap<>();private final Map<String,RelayEdge> edges=new ConcurrentHashMap<>();private final Map<String,RelayCompensation> compensations=new ConcurrentHashMap<>();private final Map<String,RelayEvent> events=new ConcurrentHashMap<>();private String k(String t,String id){return t+"|"+id;}
 public CanonicalIssueRelation saveRelation(CanonicalIssueRelation v){relations.put(k(v.tenantId(),v.relationId()),v);return v;} public boolean saveRelationExpectedVersion(CanonicalIssueRelation v,long e){return relations.compute(k(v.tenantId(),v.relationId()),(x,o)->o!=null&&o.version()==e?v:o)==v;} public Optional<CanonicalIssueRelation> findRelation(String t,String id){return Optional.ofNullable(relations.get(k(t,id)));} public List<CanonicalIssueRelation> listRelations(String t,CanonicalRelationStatus s,int n){return relations.values().stream().filter(v->v.tenantId().equals(t)&&(s==null||v.status()==s)).limit(n).toList();}
 public RelayTopology saveTopology(RelayTopology v){topologies.put(k(v.tenantId(),v.topologyId()),v);return v;} public boolean saveTopologyExpectedVersion(RelayTopology v,long e){return topologies.compute(k(v.tenantId(),v.topologyId()),(x,o)->o!=null&&o.version()==e?v:o)==v;} public Optional<RelayTopology> findTopology(String t,String id){return Optional.ofNullable(topologies.get(k(t,id)));} public List<RelayTopology> listTopologies(String t,RelayTopologyStatus s,int n){return topologies.values().stream().filter(v->v.tenantId().equals(t)&&(s==null||v.status()==s)).limit(n).toList();}
 public RelayEdge saveEdge(RelayEdge v){edges.put(k(v.tenantId(),v.edgeId()),v);return v;} public boolean saveEdgeExpectedVersion(RelayEdge v,long e){return edges.compute(k(v.tenantId(),v.edgeId()),(x,o)->o!=null&&o.version()==e?v:o)==v;} public Optional<RelayEdge> findEdge(String t,String id){return Optional.ofNullable(edges.get(k(t,id)));} public List<RelayEdge> listEdges(String t,String top,RelayEdgeStatus s,int n){return edges.values().stream().filter(v->v.tenantId().equals(t)&&(top==null||top.isBlank()||v.topologyId().equals(top))&&(s==null||v.status()==s)).limit(n).toList();} public List<RelayEdge> claimDueEdges(String t,OffsetDateTime due,int n){return edges.values().stream().filter(v->v.tenantId().equals(t)&&(v.status()==RelayEdgeStatus.READY||v.status()==RelayEdgeStatus.RETRY_WAITING)&&(v.nextAttemptAt()==null||!v.nextAttemptAt().isAfter(due))).limit(n).toList();}
 public RelayCompensation saveCompensation(RelayCompensation v){compensations.put(k(v.tenantId(),v.compensationId()),v);return v;} public boolean saveCompensationExpectedVersion(RelayCompensation v,long e){return compensations.compute(k(v.tenantId(),v.compensationId()),(x,o)->o!=null&&o.version()==e?v:o)==v;} public Optional<RelayCompensation> findCompensation(String t,String id){return Optional.ofNullable(compensations.get(k(t,id)));} public List<RelayCompensation> listCompensations(String t,String top,RelayCompensationStatus s,int n){return compensations.values().stream().filter(v->v.tenantId().equals(t)&&(top==null||top.isBlank()||v.topologyId().equals(top))&&(s==null||v.status()==s)).limit(n).toList();}
 public RelayEvent appendEvent(RelayEvent v){events.put(k(v.tenantId(),v.eventId()),v);return v;} public Optional<RelayEvent> latestEvent(String t,String type,String id){return events.values().stream().filter(v->v.tenantId().equals(t)&&v.aggregateType().equals(type)&&v.aggregateId().equals(id)).max(Comparator.comparing(RelayEvent::occurredAt).thenComparing(RelayEvent::eventId));} public List<RelayEvent> listEvents(String t,String type,String id,int n){return events.values().stream().filter(v->v.tenantId().equals(t)&&v.aggregateType().equals(type)&&v.aggregateId().equals(id)).sorted(Comparator.comparing(RelayEvent::occurredAt).reversed()).limit(n).toList();} public String mode(){return "IN_MEMORY";}
}
