'use client';

import { useCallback, useEffect, useState } from 'react';
import { useAuth } from '@/components/auth/AuthProvider';
import { accessManagementApi } from '@/lib/api/accessManagementApi';
import type { IdentityAudit, SecurityPolicies, Session, User } from '@/lib/iam/types';
import { formatIamError } from '@/lib/iam/errorPresentation';
import { useAccessManagement } from '../AccessManagementProvider';
import { AuditReasonInput, EmptyState, ErrorNotice, Panel, StatusPill, SuccessNotice, TenantRequired } from '../ui';

export function SecurityAuditConsole(){
 const{hasPermission}=useAuth();const{scopeTenantId}=useAccessManagement();const[users,setUsers]=useState<User[]>([]);const[sessions,setSessions]=useState<Session[]>([]);const[audit,setAudit]=useState<IdentityAudit[]>([]);const[subjectId,setSubjectId]=useState('');const[eventType,setEventType]=useState('');const[policies,setPolicies]=useState<SecurityPolicies|null>(null);const[policyKind,setPolicyKind]=useState<'password'|'mfa'|'session'|'token'>('password');const[policyJson,setPolicyJson]=useState('{}');const[policyReason,setPolicyReason]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!scopeTenantId)return;setError('');try{const requests:[Promise<{items:User[]}>,Promise<{items:Session[]}>,Promise<{items:IdentityAudit[]}>]=[accessManagementApi.tenantUsers(scopeTenantId,250),hasPermission('security.session.read')?accessManagementApi.sessions(scopeTenantId,200,'',subjectId):Promise.resolve({items:[]}),hasPermission('audit.identity.read')?accessManagementApi.audit(scopeTenantId,200,'',eventType):Promise.resolve({items:[]})];const[u,s,a]=await Promise.all(requests);setUsers(u.items);setSessions(s.items);setAudit(a.items);if(hasPermission('security.policy.read')){const p=await accessManagementApi.securityPolicies();setPolicies(p);setPolicyJson(JSON.stringify(p[policyKind],null,2));}}catch(cause){setError(formatIamError(cause,'Unable to load security and audit evidence.'));}},[scopeTenantId,subjectId,eventType,hasPermission,policyKind]);useEffect(()=>{void load();},[load]);
 async function savePolicy(){if(!policies)return;setBusy(true);setError('');setNotice('');try{const value=JSON.parse(policyJson) as Record<string,unknown>;const updated=await accessManagementApi.updateSecurityPolicy(policyKind,value,policies.version,policyReason);setPolicies(updated);setPolicyJson(JSON.stringify(updated[policyKind],null,2));setPolicyReason('');setNotice(`${policyKind} policy updated.`);}catch(cause){setError(formatIamError(cause,'Unable to update security policy.'));}finally{setBusy(false);}}
 async function revoke(session:Session){setBusy(true);setError('');setNotice('');try{await accessManagementApi.revokeSession(scopeTenantId,session.sessionId,session.version,'Session revoked after security review in unified Access Management.');setNotice('Session revoked.');await load();}catch(cause){setError(formatIamError(cause,'Unable to revoke Session.'));}finally{setBusy(false);}}
 if(!scopeTenantId)return <TenantRequired/>;
 return <div className="space-y-5"><ErrorNotice message={error}/><SuccessNotice message={notice}/>{policies&&hasPermission('security.policy.read')?<Panel title="Tenant Security Policies" description="Password, MFA, Session and Token controls are managed through the same canonical Access Management API."><div className="grid gap-3 md:grid-cols-[12rem_1fr]"><select value={policyKind} onChange={event=>{const kind=event.target.value as 'password'|'mfa'|'session'|'token';setPolicyKind(kind);setPolicyJson(JSON.stringify(policies[kind],null,2));}} className="h-fit rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="password">Password</option><option value="mfa">MFA</option><option value="session">Session</option><option value="token">Token</option></select><div><textarea aria-label={`${policyKind} policy JSON`} value={policyJson} onChange={event=>setPolicyJson(event.target.value)} rows={12} className="w-full rounded-xl border border-slate-300 bg-slate-950 p-3 font-mono text-xs text-emerald-200"/>{hasPermission('security.policy.manage')?<div className="mt-3 space-y-3"><AuditReasonInput value={policyReason} onChange={setPolicyReason}/><button type="button" disabled={busy||policyReason.trim().length<8} onClick={()=>void savePolicy()} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white disabled:opacity-40">Update policy</button></div>:<p className="mt-3 text-xs font-semibold text-slate-500">Read-only access</p>}</div></div></Panel>:null}<Panel title="Active Sessions" description="Inspect authentication methods, network context and expiry. Revocation requires the canonical security.session.revoke permission." actions={<select value={subjectId} onChange={event=>setSubjectId(event.target.value)} className="min-w-64 rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All users</option>{users.map(user=><option key={user.userId} value={user.userId}>{user.displayName}</option>)}</select>}>
 {sessions.length?<div className="overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Subject</th><th className="p-3">Methods</th><th className="p-3">Network / client</th><th className="p-3">Last seen</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{sessions.map(session=><tr key={session.sessionId} className="border-t"><td className="p-3 font-bold">{users.find(user=>user.userId===session.subjectId)?.displayName??session.subjectId}<div className="text-xs text-slate-500">{session.sessionId}</div></td><td className="p-3 text-xs">{session.methods.join(', ')}</td><td className="p-3 text-xs">{session.ipAddress}<div className="max-w-72 truncate text-slate-500">{session.userAgent}</div></td><td className="p-3 text-xs">{session.lastSeenAt}</td><td className="p-3"><StatusPill value={session.status}/></td><td className="p-3">{hasPermission('security.session.revoke')?<button disabled={busy||session.status!=='ACTIVE'} onClick={()=>void revoke(session)} className="rounded-lg border border-rose-300 px-3 py-1.5 text-xs font-black text-rose-900 disabled:opacity-40">Revoke</button>:null}</td></tr>)}</tbody></table></div>:<EmptyState>No Sessions match the filter.</EmptyState>}
 </Panel>
 <Panel title="Identity & Authorization Audit" description="Immutable evidence for authentication, permission decisions and administrative writes." actions={<input value={eventType} onChange={event=>setEventType(event.target.value)} placeholder="Filter event type" className="rounded-xl border border-slate-300 px-3 py-2 text-sm"/>}>
 {audit.length?<div className="space-y-3">{audit.map(event=><div key={event.eventId} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-2"><b>{event.eventType}</b><span className="text-xs text-slate-500">{event.occurredAt}</span></div><div className="mt-2 grid gap-2 text-xs text-slate-600 sm:grid-cols-2"><p><b>Actor:</b> {event.actorType} {event.actorId}</p><p><b>Target:</b> {event.targetType} {event.targetId}</p><p><b>Permission:</b> {event.permission||'—'}</p><p><b>Decision:</b> {event.decisionId||'—'}</p><p className="sm:col-span-2"><b>Reason:</b> {event.reason||'—'}</p><p className="sm:col-span-2"><b>Correlation:</b> {event.correlationId||'—'}</p></div></div>)}</div>:<EmptyState>No audit events match the filter.</EmptyState>}
 </Panel></div>;
}
