'use client';

import type { FormEvent } from 'react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useAuth } from '@/components/auth/AuthProvider';
import { accessManagementApi } from '@/lib/api/accessManagementApi';
import type { Department, IssuedToken, ServiceAccount, TokenSummary, User } from '@/lib/iam/types';
import { formatIamError } from '@/lib/iam/errorPresentation';
import { useAccessManagement } from '../AccessManagementProvider';
import { AuditReasonInput, EmptyState, ErrorNotice, Panel, StatusPill, SuccessNotice, TenantRequired } from '../ui';

const field=(data:FormData,name:string)=>String(data.get(name)??'').trim();
const list=(value:string)=>value.split(/[\n,]/).map(item=>item.trim()).filter(Boolean);

export function ServiceAccountsConsole(){
  const { hasPermission }=useAuth();
  const { scopeTenantId }=useAccessManagement();
  const [accounts,setAccounts]=useState<ServiceAccount[]>([]); const [tokens,setTokens]=useState<TokenSummary[]>([]);
  const [users,setUsers]=useState<User[]>([]); const [departments,setDepartments]=useState<Department[]>([]);
  const [issued,setIssued]=useState<IssuedToken|null>(null); const [ack,setAck]=useState(false);
  const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false);
  const activeAccounts=useMemo(()=>accounts.filter(item=>item.status==='ACTIVE'),[accounts]);
  const load=useCallback(async()=>{if(!scopeTenantId)return;setError('');try{const [a,t,u,d]=await Promise.all([accessManagementApi.serviceAccounts(),accessManagementApi.tokens(),accessManagementApi.tenantUsers(scopeTenantId,200),accessManagementApi.departments(scopeTenantId,0,250)]);setAccounts(a.items);setTokens(t.items);setUsers(u.items);setDepartments(d.items);}catch(cause){setError(formatIamError(cause,'Unable to load Service Accounts and tokens.'));}},[scopeTenantId]);
  useEffect(()=>{void load();},[load]);
  async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setError('');setNotice('');try{await action();setNotice(success);await load();}catch(cause){setError(formatIamError(cause,'Security credential action failed.'));}finally{setBusy(false);}}
  async function createAccount(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);await run(()=>accessManagementApi.createServiceAccount({name:field(data,'name'),description:field(data,'description'),ownerUserId:field(data,'ownerUserId'),ownerDepartmentId:field(data,'ownerDepartmentId'),restrictions:{permissions:list(field(data,'permissions')),audiences:list(field(data,'audiences')),apiPrefixes:list(field(data,'apiPrefixes')),allowedCidrs:list(field(data,'cidrs'))},tokenMaxTtlSeconds:Number(field(data,'tokenMaxTtlSeconds')),maxActiveTokens:Number(field(data,'maxActiveTokens')),rateLimitPerMinute:Number(field(data,'rateLimitPerMinute')),nextReviewAt:new Date(field(data,'nextReviewAt')).toISOString()},field(data,'auditReason')), 'Service Account created with a server-generated stable ID.');form.reset();}
  async function issue(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const kind=field(data,'kind');const value={name:field(data,'name'),ttlSeconds:Number(field(data,'ttlSeconds')),scope:{permissions:list(field(data,'permissions')),audiences:list(field(data,'audiences')),apiPrefixes:list(field(data,'apiPrefixes')),allowedCidrs:list(field(data,'cidrs'))}};setBusy(true);setError('');try{const result=kind==='PERSONAL'?await accessManagementApi.issuePersonalToken(value,field(data,'auditReason')):await accessManagementApi.issueServiceToken(field(data,'serviceAccountId'),value,field(data,'auditReason'));setIssued(result);setAck(false);await load();}catch(cause){setError(formatIamError(cause,'Unable to issue token.'));}finally{setBusy(false);}}
  if(!scopeTenantId)return <TenantRequired/>;
  return <div className="space-y-5"><ErrorNotice message={error}/><SuccessNotice message={notice}/>
    {issued?<Panel title="One-time token display" description="OpenDispatch stores only a hash, prefix and last four characters. Save this secret in an approved vault before closing."><textarea readOnly value={issued.token} rows={4} className="w-full rounded-xl bg-slate-950 p-4 font-mono text-xs text-emerald-200"/><label className="mt-3 flex gap-2 text-sm font-bold"><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/>I saved the token in an approved secret store.</label><button disabled={!ack} onClick={()=>setIssued(null)} className="mt-3 rounded-xl bg-slate-950 px-4 py-2 font-black text-white disabled:opacity-40">Close one-time display</button></Panel>:null}
    <div className="grid gap-5 xl:grid-cols-2">
      <Panel title="Service Accounts" description="Non-human identities have an active User owner, Department owner, bounded permissions and scheduled review.">{accounts.length?<div className="space-y-2">{accounts.map(account=><div key={account.serviceAccountId} className="rounded-xl border border-slate-200 p-3"><div className="flex items-start justify-between gap-3"><div><b>{account.name}</b><p className="text-xs text-slate-500">{account.serviceAccountId}</p></div><StatusPill value={account.status}/></div><p className="mt-2 text-xs text-slate-600">Owner {users.find(user=>user.userId===account.ownerUserId)?.displayName??account.ownerUserId} · Department {departments.find(department=>department.departmentId===account.ownerDepartmentId)?.name??account.ownerDepartmentId} · Risk {account.riskLevel}</p></div>)}</div>:<EmptyState>No Service Accounts exist in this Tenant.</EmptyState>}</Panel>
      {hasPermission('security.token.manage')?<Panel title="Create Service Account" description="IDs are generated from the Idempotency-Key. Operators choose owners by name rather than entering database identifiers."><form onSubmit={createAccount} className="space-y-3"><input name="name" required placeholder="Service Account name" className="w-full rounded-xl border border-slate-300 px-3 py-2"/><textarea name="description" placeholder="Purpose" className="w-full rounded-xl border border-slate-300 px-3 py-2"/><select name="ownerUserId" required className="w-full rounded-xl border border-slate-300 px-3 py-2"><option value="">Select active owner User</option>{users.filter(user=>user.status==='ACTIVE').map(user=><option key={user.userId} value={user.userId}>{user.displayName} ({user.username})</option>)}</select><select name="ownerDepartmentId" required className="w-full rounded-xl border border-slate-300 px-3 py-2"><option value="">Select owner Department</option>{departments.filter(department=>department.status==='ACTIVE').map(department=><option key={department.departmentId} value={department.departmentId}>{department.name}</option>)}</select><textarea name="permissions" required placeholder="Allowed permission codes" className="w-full rounded-xl border border-slate-300 px-3 py-2"/><textarea name="audiences" required placeholder="Allowed audiences" className="w-full rounded-xl border border-slate-300 px-3 py-2"/><textarea name="apiPrefixes" required placeholder="Allowed API prefixes" className="w-full rounded-xl border border-slate-300 px-3 py-2"/><textarea name="cidrs" required placeholder="Allowed CIDRs" className="w-full rounded-xl border border-slate-300 px-3 py-2"/><div className="grid grid-cols-3 gap-2"><input name="tokenMaxTtlSeconds" type="number" defaultValue="2592000" min="60" required className="rounded-xl border border-slate-300 px-3 py-2"/><input name="maxActiveTokens" type="number" defaultValue="2" min="1" max="10" required className="rounded-xl border border-slate-300 px-3 py-2"/><input name="rateLimitPerMinute" type="number" defaultValue="60" min="1" required className="rounded-xl border border-slate-300 px-3 py-2"/></div><input name="nextReviewAt" type="datetime-local" required className="w-full rounded-xl border border-slate-300 px-3 py-2"/><AuditReasonInput/><button disabled={busy} className="w-full rounded-xl bg-blue-700 px-4 py-3 font-black text-white disabled:bg-slate-300">Create Service Account</button></form></Panel>:null}
    </div>
    <div className="grid gap-5 xl:grid-cols-2"><Panel title="Access Tokens" description="Token secrets are shown once. Existing records expose only prefix and last four characters.">{tokens.length?<div className="space-y-2">{tokens.map(token=><div key={token.tokenId} className="rounded-xl border border-slate-200 p-3"><div className="flex items-start justify-between"><div><b>{token.name}</b><p className="text-xs text-slate-500">{token.prefix}••••{token.last4} · {token.tokenType}</p></div><StatusPill value={token.status}/></div>{token.status==='ACTIVE'&&hasPermission('security.token.manage')?<button disabled={busy} onClick={()=>void run(()=>accessManagementApi.revokeToken(token.tokenId,'Token revoked from canonical Access Management after credential review.'),'Token revoked.')} className="mt-2 rounded-lg border border-rose-300 px-3 py-1 text-xs font-black text-rose-700">Revoke</button>:null}</div>)}</div>:<EmptyState>No tokens exist in this Tenant.</EmptyState>}</Panel>
      {hasPermission('security.token.manage')?<Panel title="Issue Token"><form onSubmit={issue} className="space-y-3"><select name="kind" className="w-full rounded-xl border border-slate-300 px-3 py-2"><option value="SERVICE">Service Account token</option><option value="PERSONAL">Personal token</option></select><select name="serviceAccountId" className="w-full rounded-xl border border-slate-300 px-3 py-2"><option value="">Select Service Account</option>{activeAccounts.map(account=><option key={account.serviceAccountId} value={account.serviceAccountId}>{account.name}</option>)}</select><input name="name" required placeholder="Token name" className="w-full rounded-xl border border-slate-300 px-3 py-2"/><input name="ttlSeconds" type="number" min="60" defaultValue="86400" required className="w-full rounded-xl border border-slate-300 px-3 py-2"/><textarea name="permissions" required placeholder="Permission codes" className="w-full rounded-xl border border-slate-300 px-3 py-2"/><textarea name="audiences" required placeholder="Audiences" className="w-full rounded-xl border border-slate-300 px-3 py-2"/><textarea name="apiPrefixes" required placeholder="API prefixes" className="w-full rounded-xl border border-slate-300 px-3 py-2"/><textarea name="cidrs" required placeholder="Allowed CIDRs" className="w-full rounded-xl border border-slate-300 px-3 py-2"/><AuditReasonInput/><button disabled={busy} className="w-full rounded-xl bg-blue-700 px-4 py-3 font-black text-white disabled:bg-slate-300">Issue Token</button></form></Panel>:null}</div>
  </div>;
}
