package com.opensocket.aievent.core.integration.issue.webhook;
public enum ExternalIssueConflictEventType {
 CONFLICT_CREATED, INVESTIGATION_STARTED, POLICY_SELECTED, RESOLUTION_STARTED, RESOLUTION_FAILED,
 VERIFICATION_STARTED, VERIFICATION_PASSED, VERIFICATION_FAILED, WAIT_HUMAN, IGNORED, RESOLVED, REOPENED, SUPERSEDED
}
