package com.opensocket.aievent.core.resourceaccess.api;
import com.opensocket.aievent.core.resourceaccess.contract.*;import java.time.Instant;import java.util.Map;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.http.MediaType;import org.springframework.web.bind.annotation.*;
/** Returns an opaque governed content handle, never storage references, Provider URLs or credentials. */
@RestController @RequestMapping(path="/api/resource-access/artifacts/attachments",produces=MediaType.APPLICATION_JSON_VALUE)
@ConditionalOnProperty(prefix="resource-access",name={"enabled","attachment-enabled"},havingValue="true")
public final class AttachmentArtifactController {private final AttachmentAccessPort attachments;private final ResourceAuthorizationApiContextPort contexts;public AttachmentArtifactController(AttachmentAccessPort a,ResourceAuthorizationApiContextPort c){attachments=a;contexts=c;}
 @PostMapping(path="/{resourceType}/{resourceId}/download-grants",consumes=MediaType.APPLICATION_JSON_VALUE)
    public AttachmentGrantView grant(@PathVariable ResourceType resourceType,@PathVariable String resourceId,@RequestBody AttachmentBody body){var c=contexts.current();ResourceRef ref=new ResourceRef(c.authentication().activeTenant().tenantId(),resourceType,required(resourceId,"resourceId"));AttachmentDownloadGrant g=attachments.authorizeDownload(new AttachmentDownloadCommand(ref,required(body.purpose(),"purpose"),c.correlationId(),Map.of()));return new AttachmentGrantView(g.attachmentRef(),g.filename(),g.contentType(),g.sizeBytes(),g.sha256(),g.readDecisionId(),g.downloadDecisionId(),g.runtimeLeaseId(),g.fencingVersion(),g.contentHandle().handleId(),g.contentHandle().expiresAt(),g.issuedAt());}
 public record AttachmentBody(String purpose){} public record AttachmentGrantView(ResourceRef attachmentRef,String filename,String contentType,long sizeBytes,String sha256,String readDecisionId,String downloadDecisionId,String runtimeLeaseId,long fencingVersion,String contentHandleId,Instant handleExpiresAt,Instant issuedAt){}
 private static String required(String v,String f){if(v==null||v.isBlank())throw new IllegalArgumentException(f+" is required");return v.trim();}}
