export const coreAdminEndpoints = {
  dashboardSnapshot: (tenantId: string) => `/admin/tenants/${encodeURIComponent(tenantId)}/dashboard/snapshot`,
  agentsRuntimeView: (tenantId: string) => `/admin/tenants/${encodeURIComponent(tenantId)}/agents/runtime-view`,
  tasksRuntimeView: (tenantId: string) => `/admin/tenants/${encodeURIComponent(tenantId)}/tasks/runtime-view`,
  taskDetail: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}`,
  taskFinalizationAuthority: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/finalization-authority`,
  taskFlowMatchAuthority: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/flow-match-authority`,
  taskFinalizationRetry: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/finalization-authority/retry`,
  taskFinalizationRecovery: '/admin/tasks/finalization-recovery',
  taskRuntimeView: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/runtime-view`,
  taskOperationsView: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/operations-view`,
  taskCaseTimeline: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/case-timeline`,
  taskIssueDedup: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/issue-dedup`,
  taskIssueLinkReconcile: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/issue-link/reconcile`,
  taskRetry: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/retry`,
  taskCancel: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/cancel`,
  taskReassign: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/reassign`,
  taskCommands: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/commands`,
  taskDispatchRequests: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/dispatch-requests`,
  taskDispatchAttemptHistory: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/dispatch-attempt-history`,
  taskDispatchLedger: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/dispatch-ledger`,
  taskCallbackInbox: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/callback-inbox`,
  taskCallbackInboxSummary: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/callback-inbox/summary`,
  taskRoutingDecisions: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/routing-decisions`,
  taskTimeline: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/timeline`,
  taskDispatchEvidence: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/dispatch-evidence`,
  taskRuntimeVerification: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/runtime-verification`,
  taskDispatchContractReadiness: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/dispatch-contract-readiness`,
  taskRepairDispatchContract: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/repair-dispatch-contract`,
  taskA2AClassificationContract: '/admin/tasks/a2a-classification/contract',
  taskClassificationResult: (taskId: string) => `/api/agent/tasks/${encodeURIComponent(taskId)}/classification-result`,
  adapterActions: '/api/adapter-actions',
  adapterActionsByTask: (taskId: string) => `/api/adapter-actions/task/${encodeURIComponent(taskId)}`,
  adapterActionsByStatus: (status: string) => `/api/adapter-actions/status/${encodeURIComponent(status)}`,
  adapterActionExecute: (actionId: string) => `/api/adapter-actions/${encodeURIComponent(actionId)}/execute`,
  adapterActionExecuteRetry: (actionId: string) => `/api/adapter-actions/${encodeURIComponent(actionId)}/execute-retry`,
  adapterActionRetry: (actionId: string) => `/api/adapter-actions/${encodeURIComponent(actionId)}/retry`,
  adapterActionExecutePending: '/api/adapter-actions/execute-pending',
  adapterActionExecutorAudit: '/api/adapter-actions/executor-audit',
  adapterActionsMetadata: '/api/adapter-actions/metadata',
  taskFailureQueue: '/admin/tasks/failure-queue',
  taskManualRetry: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/manual-retry`,
  taskDeadLetter: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/dead-letter`,
  taskEscalate: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/escalate`,
  recoveryMetrics: '/admin/recovery/metrics',
  recoveryRunbook: '/admin/recovery/runbook',
  recoveryApprovalRequests: '/admin/recovery/approval-requests',
  recoveryApprovalRequest: (approvalId: string) => `/admin/recovery/approval-requests/${encodeURIComponent(approvalId)}`,
  recoveryApprovalApprove: (approvalId: string) => `/admin/recovery/approval-requests/${encodeURIComponent(approvalId)}/approve`,
  recoveryApprovalReject: (approvalId: string) => `/admin/recovery/approval-requests/${encodeURIComponent(approvalId)}/reject`,
  recoveryApprovalCancel: (approvalId: string) => `/admin/recovery/approval-requests/${encodeURIComponent(approvalId)}/cancel`,
  recoveryClearRuntimeBackoff: (agentId: string) => `/admin/recovery/actions/agents/${encodeURIComponent(agentId)}/clear-runtime-backoff`,
  recoveryTriggerTaskNow: (taskId: string) => `/admin/recovery/actions/tasks/${encodeURIComponent(taskId)}/recover-now`,
  recoveryTaskDeadLetter: (taskId: string) => `/admin/recovery/actions/tasks/${encodeURIComponent(taskId)}/dead-letter`,
  recoveryTaskRestoreDeadLetter: (taskId: string) => `/admin/recovery/actions/tasks/${encodeURIComponent(taskId)}/restore-dead-letter`,
  recoveryDispatchDeadLetter: (dispatchRequestId: string) => `/admin/recovery/actions/dispatch-requests/${encodeURIComponent(dispatchRequestId)}/dead-letter`,
  recoveryDispatchRestoreDeadLetter: (dispatchRequestId: string) => `/admin/recovery/actions/dispatch-requests/${encodeURIComponent(dispatchRequestId)}/restore-dead-letter`,
  dispatchRequests: '/admin/dispatch-requests',
  dispatchSimulation: '/admin/dispatch/simulate',
  callbackInboxRecent: '/admin/callbacks/inbox/recent',
  dispatchRequestCallbackInbox: (dispatchRequestId: string) => `/admin/dispatch-requests/${encodeURIComponent(dispatchRequestId)}/callback-inbox`,
  dispatchRequestCallbackInboxSummary: (dispatchRequestId: string) => `/admin/dispatch-requests/${encodeURIComponent(dispatchRequestId)}/callback-inbox/summary`,
  dispatchRequestRetry: (dispatchRequestId: string) => `/admin/dispatch-requests/${encodeURIComponent(dispatchRequestId)}/retry`,
  securityEvents: (tenantId: string) => `/admin/tenants/${encodeURIComponent(tenantId)}/security-events`,
  agentSecurityEvents: '/admin/agent-security-events',
  agentGovernanceSummary: (tenantId: string) => `/admin/tenants/${encodeURIComponent(tenantId)}/agent-governance/summary`,
  agentGovernanceMetadata: '/admin/agent-governance/metadata',
  agentGovernanceTableDiagnostics: '/admin/agent-governance/table-diagnostics',
  agentEnrollments: '/admin/agent-enrollments',
  agentEnrollmentApprove: (enrollmentId: string) => `/admin/agent-enrollments/${encodeURIComponent(enrollmentId)}/approve`,
  agentEnrollmentReject: (enrollmentId: string) => `/admin/agent-enrollments/${encodeURIComponent(enrollmentId)}/reject`,
  agents: '/admin/agents',
  agentSetup: '/admin/agents/setup',
  agentSetupReadiness: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/setup-readiness`,
  agentOperationalView: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/operational-view`,
  agentLatestAuthFailure: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/latest-auth-failure`,
  agentConnectionRepairActions: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/connection-repair-actions`,
  agentConnectionRepairActionExecute: (agentId: string, actionCode: string) => `/admin/agents/${encodeURIComponent(agentId)}/connection-repair-actions/${encodeURIComponent(actionCode)}`,
  agentDetail: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}`,
  agentUpdate: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}`,
  agentEnable: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/enable`,
  agentDisable: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/disable`,
  agentSuspend: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/suspend`,
  agentRevoke: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/revoke`,
  agentApprove: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/approve`,
  agentCredentialIssue: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/credentials/issue`,
  agentDisconnect: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/disconnect`,
  agentDisconnectAll: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/disconnect-all`,
  agentRuntimeDisconnectReconcile: '/admin/agents/runtime-disconnect/reconcile',
  agentDuplicateRuntimeEnforce: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/security/duplicate-runtime/enforce`,
  agentDuplicateRuntimeResolve: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/security/duplicate-runtime/resolve`,
  agentSecurityEnforcementPolicy: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/security/enforcement-policy`,
  agentSecurityEnforcementPolicies: '/admin/agent-security-enforcement-policies',
  defaultSecurityEnforcementPolicy: '/admin/agent-security-enforcement-policies/default',
  agentSkills: '/admin/agent-skills',
  agentSkillsMetadata: '/admin/agent-skills/metadata',
  agentSkill: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}`,
  agentSkillVersions: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/versions`,
  agentSkillDraftVersion: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/versions/draft`,
  agentSkillVersionAction: (skillCode: string, version: number, action: 'submit' | 'approve' | 'reject' | 'publish' | 'rollback') => `/admin/agent-skills/${encodeURIComponent(skillCode)}/versions/${encodeURIComponent(String(version))}/${action}`,
  agentSkillAudit: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/audit`,
  agentSkillVersionDiff: (skillCode: string, version: number) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/versions/${encodeURIComponent(String(version))}/diff`,
  agentSkillVersionImpact: (skillCode: string, version: number) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/versions/${encodeURIComponent(String(version))}/impact`,
  agentSkillApprovalPolicy: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/approval-policy`,
  agentSkillsDrift: '/admin/agent-skills/drift',
  agentSkillsDriftPolicyEvaluate: '/admin/agent-skills/drift/policy-evaluate',
  agentSkillDeprecationPlan: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/deprecation-plan`,
  agentSkillDeprecationAnalyze: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/deprecation-plan/analyze`,
  agentSkillDependencyGraph: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/dependency-graph`,
  agentSkillDependencies: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/dependencies`,
  agentSkillFleetRemediationProposal: '/admin/agent-skills/drift/remediation-proposals',
  agentSkillRemediationProposal: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/skills/remediation-proposal`,
  agentRemediationProposal: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/remediation/proposal`,
  agentRemediationWorkflows: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/remediation/workflows`,
  agentRemediationWorkflow: (agentId: string, workflowId: string) => `/admin/agents/${encodeURIComponent(agentId)}/remediation/workflows/${encodeURIComponent(workflowId)}`,
  agentRemediationWorkflowApprove: (agentId: string, workflowId: string) => `/admin/agents/${encodeURIComponent(agentId)}/remediation/workflows/${encodeURIComponent(workflowId)}/approve`,
  agentRemediationWorkflowReject: (agentId: string, workflowId: string) => `/admin/agents/${encodeURIComponent(agentId)}/remediation/workflows/${encodeURIComponent(workflowId)}/reject`,
  agentRemediationWorkflowCancel: (agentId: string, workflowId: string) => `/admin/agents/${encodeURIComponent(agentId)}/remediation/workflows/${encodeURIComponent(workflowId)}/cancel`,
  agentRemediationWorkflowExecute: (agentId: string, workflowId: string) => `/admin/agents/${encodeURIComponent(agentId)}/remediation/workflows/${encodeURIComponent(workflowId)}/execute`,
  agentRemediationWorkflowStaleLeases: '/admin/remediation/workflow-leases/stale',
  agentRemediationWorkflowRecoveredLeases: '/admin/remediation/workflow-leases/recovered',
  agentRemediationWorkflowRecoverStaleLeases: '/admin/remediation/workflow-leases/recover-stale',
  agentSkillEvaluation: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/skills/evaluate`,
  agentSkillDrift: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/skills/drift`,
  dispatchContractResolve: '/admin/dispatch-contracts/resolve',
  dispatchRecipes: '/admin/dispatch-recipes',
  dispatchRecipe: (recipeCode: string) => `/admin/dispatch-recipes/${encodeURIComponent(recipeCode)}`,
  dispatchRecipeTemplates: '/admin/dispatch-recipes/templates',
  dispatchRecipeEvaluate: (recipeCode: string) => `/admin/dispatch-recipes/${encodeURIComponent(recipeCode)}/evaluate`,
  taskCapabilityResolve: '/admin/task-capabilities/resolve',
  dispatchReadinessEvaluate: '/admin/dispatch-readiness/evaluate',
  dispatchReadinessTemplates: '/admin/dispatch-readiness/templates',
  eventIntake: '/api/events/intake',
  agentApprovedSkills: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/skills/approved`,
  agentSkillSyncApprovedCapabilities: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/skills/sync-approved-capabilities`,
  agentRuntimeCapabilityProfile: (agentId: string) => `/api/agents/${encodeURIComponent(agentId)}/runtime/capability-profile`,
  agentRuntimeDescriptor: (agentId: string) => `/api/agents/${encodeURIComponent(agentId)}/runtime/descriptor`,
  agentRuntimeCapabilities: (agentId: string) => `/api/agents/${encodeURIComponent(agentId)}/runtime/capabilities`,
  agentRuntimeLoad: (agentId: string) => `/api/agents/${encodeURIComponent(agentId)}/runtime/load`,
  runtimeResources: '/admin/runtime-resources',
  runtimeResource: (runtimeId: string) => `/admin/runtime-resources/${encodeURIComponent(runtimeId)}`,
  agentRuntimeBindings: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-bindings`,
  agentRuntimeBindingActivate: (agentId: string, bindingId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-bindings/${encodeURIComponent(bindingId)}/activate`,
  agentRuntimeBindingPause: (agentId: string, bindingId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-bindings/${encodeURIComponent(bindingId)}/pause`,
  agentRuntimeBindingResume: (agentId: string, bindingId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-bindings/${encodeURIComponent(bindingId)}/resume`,
  agentRuntimeBindingRevoke: (agentId: string, bindingId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-bindings/${encodeURIComponent(bindingId)}/revoke`,
  runtimeFeatures: '/admin/runtime-features',
  runtimeFeature: (featureCode: string) => `/admin/runtime-features/${encodeURIComponent(featureCode)}`,
  canonicalCapabilities: '/admin/capability-definitions',
  canonicalCapability: (capabilityCode: string) => `/admin/capability-definitions/${encodeURIComponent(capabilityCode)}`,
  capabilityRequirementsByServiceCode: (serviceCode: string) => `/admin/capability-definitions/requirements/by-service-code/${encodeURIComponent(serviceCode)}`,
  capabilityProviders: '/admin/capability-provider-registry/providers',
  capabilityProvider: (providerId: string) => `/admin/capability-provider-registry/providers/${encodeURIComponent(providerId)}`,
  capabilityBindings: '/admin/capability-provider-registry/bindings',
  capabilityBinding: (bindingId: string) => `/admin/capability-provider-registry/bindings/${encodeURIComponent(bindingId)}`,
  capabilityBindingTrustEvents: (bindingId: string) => `/admin/capability-provider-registry/bindings/${encodeURIComponent(bindingId)}/trust-events`,
  delegationPolicies: '/admin/delegation-governance/policies',
  delegationPolicy: (policyId: string) => `/admin/delegation-governance/policies/${encodeURIComponent(policyId)}`,
  delegationPolicyVersions: (policyId: string) => `/admin/delegation-governance/policies/${encodeURIComponent(policyId)}/versions`,
  delegationPolicyAuditEvents: (policyId: string) => `/admin/delegation-governance/policies/${encodeURIComponent(policyId)}/audit-events`,
  delegationAuthorizationPreview: '/admin/delegation-governance/evaluate-preview',
  providerRoutingProfiles: '/admin/provider-routing/profiles',
  providerRoutingProfile: (profileId: string) => `/admin/provider-routing/profiles/${encodeURIComponent(profileId)}`,
  providerRoutingProfileVersions: (profileId: string) => `/admin/provider-routing/profiles/${encodeURIComponent(profileId)}/versions`,
  providerRoutingEligibilityObservations: '/admin/provider-routing/eligibility-observations',
  providerRoutingPreview: '/admin/provider-routing/evaluate-preview',
  providerRoutingDecisions: '/admin/provider-routing/decisions',
  routingAuthorityShadowEvaluate: (planId: string) => `/admin/routing-authority/plans/${encodeURIComponent(planId)}/shadow-evaluate`,
  routingAuthorityRebindingAdmission: (planId: string) => `/admin/routing-authority/plans/${encodeURIComponent(planId)}/rebinding-admission`,
  routingAuthorityTrace: (planId: string) => `/admin/routing-authority/plans/${encodeURIComponent(planId)}/trace`,
  routingAuthorityFlowMigrationStates: '/admin/routing-authority/flows/migration-state',
  routingAuthorityFlowMigrationState: (flowId: string) => `/admin/routing-authority/flows/${encodeURIComponent(flowId)}/migration-state`,
  executionSafetyFlowAuthority: (flowId: string) => `/admin/execution-safety/flows/${encodeURIComponent(flowId)}/authority`,
  executionSafetyPrepare: (planId: string) => `/admin/execution-safety/plans/${encodeURIComponent(planId)}/prepare`,
  executionSafetyHandoffNext: '/admin/execution-safety/intents/handoff-next',
  executionSafetyRecentIntents: '/admin/execution-safety/intents/recent',
  executionSafetyTrace: (planId: string) => `/admin/execution-safety/plans/${encodeURIComponent(planId)}/trace`,
  runtimeAcceptanceEvidence: '/admin/runtime-acceptance/evidence',
  runtimeAcceptanceSummary: '/admin/runtime-acceptance/summary',
  runtimeAcceptanceRuns: '/admin/runtime-acceptance/runs',
  runtimeAcceptanceDigestKeys: '/admin/runtime-acceptance/digest-keys',
  runtimeAcceptancePayloadDisposition: (payloadHandle: string) => `/admin/runtime-acceptance/payloads/${encodeURIComponent(payloadHandle)}/disposition`,
  productionFoundationSummary: '/admin/production-foundation/summary',
  productionFoundationCutoverRuns: '/admin/production-foundation/cutover-runs',
  productionFoundationCandidates: '/admin/production-foundation/candidates',
  productionFoundationCandidateCertify: (candidateId: string) => `/admin/production-foundation/candidates/${encodeURIComponent(candidateId)}/certify`,
  productionFoundationCandidateActivate: (candidateId: string) => `/admin/production-foundation/candidates/${encodeURIComponent(candidateId)}/activate`,
  productionFoundationCandidateRevoke: (candidateId: string) => `/admin/production-foundation/candidates/${encodeURIComponent(candidateId)}/revoke`,
  productionFoundationFlowAuthority: (flowId: string) => `/admin/production-foundation/flows/${encodeURIComponent(flowId)}/authority`,
  executionAdapters: '/admin/execution-adapters',
  executionAdapter: (adapterId: string) => `/admin/execution-adapters/${encodeURIComponent(adapterId)}`,
  executionAdapterVersions: (adapterId: string) => `/admin/execution-adapters/${encodeURIComponent(adapterId)}/versions`,
  executionAdapterResolvePreview: '/admin/execution-adapters/resolve-preview',
  executionAdapterResolutions: '/admin/execution-adapters/resolutions/evidence',
  semanticTriagePolicies: '/admin/semantic-triage/policies',
  semanticTriagePolicy: (policyId: string) => `/admin/semantic-triage/policies/${encodeURIComponent(policyId)}`,
  semanticTriagePolicyVersions: (policyId: string) => `/admin/semantic-triage/policies/${encodeURIComponent(policyId)}/versions`,
  semanticTriageResolvePreview: '/admin/semantic-triage/resolve-preview',
  semanticTriageProposal: (requestId: string) => `/admin/semantic-triage/requests/${encodeURIComponent(requestId)}/proposals`,
  semanticTriageRequests: '/admin/semantic-triage/requests',
  semanticTriageProposals: '/admin/semantic-triage/proposals',
  semanticTriageDecisions: '/admin/semantic-triage/decisions',
  executionPlanPolicies: '/admin/execution-plans/policies',
  executionPlanPolicy: (policyId: string) => `/admin/execution-plans/policies/${encodeURIComponent(policyId)}`,
  executionPlanPolicyVersions: (policyId: string) => `/admin/execution-plans/policies/${encodeURIComponent(policyId)}/versions`,
  executionPlanResolvePreview: '/admin/execution-plans/resolve-preview',
  executionPlanProposal: (requestId: string) => `/admin/execution-plans/requests/${encodeURIComponent(requestId)}/proposals`,
  executionPlanAmendment: (planId: string) => `/admin/execution-plans/${encodeURIComponent(planId)}/amendments`,
  executionPlans: '/admin/execution-plans',
  executionPlan: (planId: string) => `/admin/execution-plans/${encodeURIComponent(planId)}`,
  executionPlanRevisions: (planId: string) => `/admin/execution-plans/${encodeURIComponent(planId)}/revisions`,
  executionPlanRequests: '/admin/execution-plans/requests',
  executionPlanProposals: '/admin/execution-plans/proposals',
  executionPlanDecisions: '/admin/execution-plans/decisions',
  planExecutionPolicies: '/admin/plan-executions/policies',
  planExecutionPolicy: (policyId: string) => `/admin/plan-executions/policies/${encodeURIComponent(policyId)}`,
  planExecutionPolicyVersions: (policyId: string) => `/admin/plan-executions/policies/${encodeURIComponent(policyId)}/versions`,
  planExecutionRuns: '/admin/plan-executions/runs',
  planExecutionRun: (runId: string) => `/admin/plan-executions/runs/${encodeURIComponent(runId)}`,
  planExecutionSteps: (runId: string) => `/admin/plan-executions/runs/${encodeURIComponent(runId)}/steps`,
  planExecutionStepAuthority: (runId: string, stepId: string) => `/admin/plan-executions/runs/${encodeURIComponent(runId)}/steps/${encodeURIComponent(stepId)}/authority`,
  planExecutionStepSubmit: (runId: string, stepId: string) => `/admin/plan-executions/runs/${encodeURIComponent(runId)}/steps/${encodeURIComponent(stepId)}/submit`,
  planExecutionStepComplete: (runId: string, stepId: string) => `/admin/plan-executions/runs/${encodeURIComponent(runId)}/steps/${encodeURIComponent(stepId)}/complete`,
  planExecutionStepRetry: (runId: string, stepId: string) => `/admin/plan-executions/runs/${encodeURIComponent(runId)}/steps/${encodeURIComponent(stepId)}/retry`,
  planExecutionCancel: (runId: string) => `/admin/plan-executions/runs/${encodeURIComponent(runId)}/cancel`,
  planExecutionAttempts: (runId: string) => `/admin/plan-executions/runs/${encodeURIComponent(runId)}/attempts`,
  planExecutionArtifacts: (runId: string) => `/admin/plan-executions/runs/${encodeURIComponent(runId)}/artifacts`,
  planExecutionEvents: (runId: string) => `/admin/plan-executions/runs/${encodeURIComponent(runId)}/events`,
  planExecutionSweepTimeouts: '/admin/plan-executions/sweep-timeouts',
  caseConvergenceAggregationDefinitions: '/admin/case-convergence/aggregation-definitions',
  caseConvergenceAggregationDefinition: (aggregationId: string) => `/admin/case-convergence/aggregation-definitions/${encodeURIComponent(aggregationId)}`,
  caseConvergenceAggregationDefinitionVersions: (aggregationId: string) => `/admin/case-convergence/aggregation-definitions/${encodeURIComponent(aggregationId)}/versions`,
  caseConvergenceAggregationPrepare: '/admin/case-convergence/aggregation/prepare-preview',
  caseConvergenceAggregationDecisions: '/admin/case-convergence/aggregation/decisions',
  caseConvergenceCases: '/admin/case-convergence/cases',
  caseConvergenceCase: (caseId: string) => `/admin/case-convergence/cases/${encodeURIComponent(caseId)}`,
  caseConvergenceCaseReview: (caseId: string) => `/admin/case-convergence/cases/${encodeURIComponent(caseId)}/review`,
  caseConvergenceCaseArtifacts: (caseId: string) => `/admin/case-convergence/cases/${encodeURIComponent(caseId)}/artifacts`,
  caseConvergenceCaseProjections: (caseId: string) => `/admin/case-convergence/cases/${encodeURIComponent(caseId)}/issue-projections`,
  caseConvergenceCaseEvents: (caseId: string) => `/admin/case-convergence/cases/${encodeURIComponent(caseId)}/events`,
  learningFastPathPolicies: '/admin/learning-fast-path/policies',
  learningFastPathPolicy: (policyId: string) => `/admin/learning-fast-path/policies/${encodeURIComponent(policyId)}`,
  learningFastPathPolicyVersions: (policyId: string) => `/admin/learning-fast-path/policies/${encodeURIComponent(policyId)}/versions`,
  learningFastPathOutcomeFromCase: (caseId: string) => `/admin/learning-fast-path/outcomes/from-case/${encodeURIComponent(caseId)}`,
  learningFastPathOutcomes: '/admin/learning-fast-path/outcomes',
  learningFastPathCandidates: '/admin/learning-fast-path/candidates',
  learningFastPathCandidateShadow: (candidateId: string) => `/admin/learning-fast-path/candidates/${encodeURIComponent(candidateId)}/promote-shadow`,
  learningFastPathPatterns: '/admin/learning-fast-path/patterns',
  learningFastPathPatternVersions: (patternId: string) => `/admin/learning-fast-path/patterns/${encodeURIComponent(patternId)}/versions`,
  learningFastPathPatternTransition: (patternId: string) => `/admin/learning-fast-path/patterns/${encodeURIComponent(patternId)}/transition`,
  learningFastPathPatternQualityRefresh: (patternId: string) => `/admin/learning-fast-path/patterns/${encodeURIComponent(patternId)}/quality/refresh`,
  learningFastPathPatternQuality: (patternId: string) => `/admin/learning-fast-path/patterns/${encodeURIComponent(patternId)}/quality`,
  learningFastPathPatternDriftEvaluate: (patternId: string) => `/admin/learning-fast-path/patterns/${encodeURIComponent(patternId)}/drift/evaluate`,
  learningFastPathPatternDrift: (patternId: string) => `/admin/learning-fast-path/patterns/${encodeURIComponent(patternId)}/drift`,
  learningFastPathResolvePreview: '/admin/learning-fast-path/fast-path/resolve-preview',
  learningFastPathPromotionDecisions: '/admin/learning-fast-path/promotion-decisions',
  fastPathRuntimePolicies: '/admin/fast-path-runtime/policies',
  fastPathRuntimePolicy: (policyId: string) => `/admin/fast-path-runtime/policies/${encodeURIComponent(policyId)}`,
  fastPathRuntimePolicyVersions: (policyId: string) => `/admin/fast-path-runtime/policies/${encodeURIComponent(policyId)}/versions`,
  fastPathRuntimeShadowComparisons: '/admin/fast-path-runtime/shadow-comparisons',
  fastPathRuntimePatternCertifications: (patternId: string) => `/admin/fast-path-runtime/patterns/${encodeURIComponent(patternId)}/certifications`,
  fastPathRuntimeCertifications: '/admin/fast-path-runtime/certifications',
  fastPathRuntimeDecisions: '/admin/fast-path-runtime/decisions',
  runtimeStepAuthorityPolicies: '/admin/runtime-step-authority/policies',
  runtimeStepAuthorityPolicy: (policyId: string) => `/admin/runtime-step-authority/policies/${encodeURIComponent(policyId)}`,
  runtimeStepAuthorityPolicyVersions: (policyId: string) => `/admin/runtime-step-authority/policies/${encodeURIComponent(policyId)}/versions`,
  runtimeStepAuthorityDecisions: '/admin/runtime-step-authority/decisions',
  planExecutionStepAutomateAuthority: (runId: string, stepId: string) => `/admin/plan-executions/runs/${encodeURIComponent(runId)}/steps/${encodeURIComponent(stepId)}/automate-authority`,
  capabilities: '/admin/capabilities',
  capability: (capabilityCode: string) => `/admin/capabilities/${encodeURIComponent(capabilityCode)}`,
  dispatchPoliciesV2: '/admin/dispatch-policies',
  dispatchPolicyV2: (policyCode: string) => `/admin/dispatch-policies/${encodeURIComponent(policyCode)}`,
  dispatchPolicyScopes: (policyCode: string) => `/admin/dispatch-policies/${encodeURIComponent(policyCode)}/scopes`,
  dispatchPolicyRequiredCapabilities: (policyCode: string) => `/admin/dispatch-policies/${encodeURIComponent(policyCode)}/required-capabilities`,
  dispatchPolicyRequiredRuntimeFeatures: (policyCode: string) => `/admin/dispatch-policies/${encodeURIComponent(policyCode)}/required-runtime-features`,
  dispatchPolicyQualityRules: (policyCode: string) => `/admin/dispatch-policies/${encodeURIComponent(policyCode)}/quality-rules`,
  dispatchPolicyScoringRules: (policyCode: string) => `/admin/dispatch-policies/${encodeURIComponent(policyCode)}/scoring-rules`,
  dispatchTaskDefinitions: '/admin/dispatch-task-definitions',
  dispatchTaskDefinition: (definitionId: string) => `/admin/dispatch-task-definitions/${encodeURIComponent(definitionId)}`,
  dispatchTaskDefinitionImpactPreview: (definitionId: string) => `/admin/dispatch-task-definitions/${encodeURIComponent(definitionId)}/impact-preview`,
  dispatchTaskDefinitionActivate: (definitionId: string) => `/admin/dispatch-task-definitions/${encodeURIComponent(definitionId)}/activate`,
  dispatchTaskDefinitionRetire: (definitionId: string) => `/admin/dispatch-task-definitions/${encodeURIComponent(definitionId)}/retire`,
  dispatchTaskDefinitionMerge: (definitionId: string) => `/admin/dispatch-task-definitions/${encodeURIComponent(definitionId)}/merge`,

  sourceSystems: '/admin/source-systems',
  sourceSystem: (sourceSystemId: string) => `/admin/source-systems/${encodeURIComponent(sourceSystemId)}`,
  sourceSystemRegistrations: (sourceSystemId: string) => `/admin/source-systems/${encodeURIComponent(sourceSystemId)}/registrations`,
  sourceSystemRegistration: (sourceSystemId: string, registrationId: string) => `/admin/source-systems/${encodeURIComponent(sourceSystemId)}/registrations/${encodeURIComponent(registrationId)}`,

  dispatchFlows: '/admin/dispatch-flows',
  dispatchFlowAgentOptions: '/admin/dispatch-flows/agent-options',
  agentPools: '/admin/dispatch-flows/agent-pools',
  agentPool: (poolId: string) => `/admin/dispatch-flows/agent-pools/${encodeURIComponent(poolId)}`,
  dispatchFlowsByAgent: (agentId: string) => `/admin/dispatch-flows/by-agent/${encodeURIComponent(agentId)}`,
  dispatchFlow: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}`,
  dispatchFlowRealTestEvent: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/test-event`,
  dispatchFlowDryRun: '/admin/dispatch-flows/dry-run',
  dispatchFlowScopedDryRun: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/dry-run`,
  dispatchFlowReadiness: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/readiness`,
  dispatchFlowRules: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/rules`,
  dispatchFlowRuleConflicts: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/rule-conflicts`,
  dispatchFlowCapabilityBridge: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/capability-migration/compatibility-bridge`,
  dispatchFlowCapabilityBridgeRefresh: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/capability-migration/compatibility-bridge/refresh`,
  dispatchFlowLegacyEquivalence: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/capability-migration/legacy-equivalence`,
  dispatchFlowLegacyEquivalenceEvaluate: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/capability-migration/legacy-equivalence/evaluate`,
  dispatchFlowLegacyEquivalenceReadiness: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/capability-migration/legacy-equivalence/readiness`,
  dispatchFlowLegacyEquivalenceBackfill: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/capability-migration/legacy-equivalence/backfill`,
  dispatchFlowSkills: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/skills`,
  dispatchFlowAgents: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/agents`,
  dispatchFlowAgentPreview: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/agents/preview`,
  dispatchFlowRulePreview: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/rules/preview`,
  dispatchFlowTrace: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/trace`,
  dispatchFlowTestExternal: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/test-external`,
  dispatchFlowTestA2a: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/test-a2a`,
  dispatchFlowTestResult: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/test-result`,
  dispatchFlowTestChain: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/test-chain`,
  dispatchContractSourceSystems: '/admin/dispatch-contracts/source-systems',
  dispatchContractBootstrap: '/admin/dispatch-contracts/bootstrap',
  dispatchContractReadiness: '/admin/dispatch-contracts/readiness',
  dispatchContractInspect: '/admin/dispatch-contracts/inspect',
  dispatchContractTrace: '/admin/dispatch-contracts/trace',
  dispatchContractTestTask: '/admin/dispatch-contracts/test-task',
  advancedSelectionStrategyContracts: '/admin/selection-strategies/advanced/contracts',
  agentPoolCapabilityPolicies: '/admin/agent-pool-policies/capabilities',
  agentPoolCapabilityPolicy: (targetPoolId: string) => `/admin/agent-pool-policies/capabilities/${encodeURIComponent(targetPoolId)}`,
  advisoryRecommendations: '/admin/recommendations/advisory',
  advisoryRecommendationsGenerate: '/admin/recommendations/advisory/generate',
  advisoryRecommendationAccept: (recommendationId: string) => `/admin/recommendations/advisory/${encodeURIComponent(recommendationId)}/accept`,
  advisoryRecommendationReject: (recommendationId: string) => `/admin/recommendations/advisory/${encodeURIComponent(recommendationId)}/reject`,
  agentQualityDaily: (agentId: string) => `/admin/quality/agents/${encodeURIComponent(agentId)}/daily`,
  agentQualityWindows: (agentId: string) => `/admin/quality/agents/${encodeURIComponent(agentId)}/windows`,
  runtimeQualityDaily: (runtimeId: string) => `/admin/quality/runtime/${encodeURIComponent(runtimeId)}/daily`,
  supplyProfileQualitySnapshots: '/admin/quality/supply-profiles',
  supplyProfileQualitySnapshot: (profileCode: string) => `/admin/supply-profiles/${encodeURIComponent(profileCode)}/quality-snapshot`,
  supplyProfiles: '/admin/supply-profiles',
  supplyProfile: (profileCode: string) => `/admin/supply-profiles/${encodeURIComponent(profileCode)}`,
  agentSupplyProfiles: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/supply-profiles`,
  assignmentProfiles: '/admin/assignment-profiles',
  assignmentProfile: (profileCode: string) => `/admin/assignment-profiles/${encodeURIComponent(profileCode)}`,
  assignmentProfilePolicies: (profileCode: string) => `/admin/assignment-profiles/${encodeURIComponent(profileCode)}/policies`,
  assignmentProfileCapabilities: (profileCode: string) => `/admin/assignment-profiles/${encodeURIComponent(profileCode)}/capabilities`,
  assignmentProfileRelationshipMap: (profileCode: string) => `/admin/assignment-profiles/${encodeURIComponent(profileCode)}/relationship-map`,
  assignmentProfileImpactPreview: (profileCode: string) => `/admin/assignment-profiles/${encodeURIComponent(profileCode)}/impact-preview`,
  assignmentProfilePolicy: (profileCode: string, policyCode: string) => `/admin/assignment-profiles/${encodeURIComponent(profileCode)}/policies/${encodeURIComponent(policyCode)}`,
  assignmentProfileCapability: (profileCode: string, capabilityCode: string) => `/admin/assignment-profiles/${encodeURIComponent(profileCode)}/capabilities/${encodeURIComponent(capabilityCode)}`, 
  agentCapabilities: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/capabilities`,
  agentCapabilityRemove: (agentId: string, assignmentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/capabilities/${encodeURIComponent(assignmentId)}/remove`,
  agentCapabilityDelete: (agentId: string, assignmentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/capabilities/${encodeURIComponent(assignmentId)}`,
  agentCapabilityApprove: (agentId: string, assignmentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/capabilities/${encodeURIComponent(assignmentId)}/approve`,
  agentCapabilitySuspend: (agentId: string, assignmentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/capabilities/${encodeURIComponent(assignmentId)}/suspend`,
  agentCapabilityResume: (agentId: string, assignmentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/capabilities/${encodeURIComponent(assignmentId)}/resume`,
  agentCapabilityRevoke: (agentId: string, assignmentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/capabilities/${encodeURIComponent(assignmentId)}/revoke`,
  agentRuntimeFeatureObservations: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features/observations`,
  agentRuntimeFeatureTrusts: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features/trust`,
  agentRuntimeFeatureObserve: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features`,
  agentRuntimeFeatureVerify: (agentId: string, trustId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features/${encodeURIComponent(trustId)}/verify`,
  agentRuntimeFeatureTrust: (agentId: string, trustId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features/${encodeURIComponent(trustId)}/trust`,
  agentRuntimeFeatureSuspend: (agentId: string, trustId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features/${encodeURIComponent(trustId)}/suspend`,
  agentRuntimeFeatureResume: (agentId: string, trustId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features/${encodeURIComponent(trustId)}/resume`,
  agentRuntimeFeatureRevoke: (agentId: string, trustId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features/${encodeURIComponent(trustId)}/revoke`,
  agentQualifications: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/qualifications`,
  agentQualificationRemove: (agentId: string, qualificationId: string) => `/admin/agents/${encodeURIComponent(agentId)}/qualifications/${encodeURIComponent(qualificationId)}`,
  agentQualificationApprove: (agentId: string, qualificationId: string) => `/admin/agents/${encodeURIComponent(agentId)}/qualifications/${encodeURIComponent(qualificationId)}/approve`,
  agentQualificationSuspend: (agentId: string, qualificationId: string) => `/admin/agents/${encodeURIComponent(agentId)}/qualifications/${encodeURIComponent(qualificationId)}/suspend`,
  agentQualificationResume: (agentId: string, qualificationId: string) => `/admin/agents/${encodeURIComponent(agentId)}/qualifications/${encodeURIComponent(qualificationId)}/resume`,
  agentQualificationRevoke: (agentId: string, qualificationId: string) => `/admin/agents/${encodeURIComponent(agentId)}/qualifications/${encodeURIComponent(qualificationId)}/revoke`,
  agentEnterpriseGovernance: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/enterprise-governance`,
  agentDispatchEligibility: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/dispatch-eligibility`,
  agentDispatchEligibilityForTask: (agentId: string, taskId: string) => `/admin/agents/${encodeURIComponent(agentId)}/dispatch-eligibility?taskId=${encodeURIComponent(taskId)}`,
  taskDispatchRequirements: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/dispatch-requirements`,
  taskEligibleAgents: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/eligible-agents`,
  taskEligibleAgentsV2: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/eligible-agents-v2`,
  enforceObservabilitySnapshot: '/admin/enforce/observability',
  enforceRoutingAuditSearch: '/admin/enforce/routing-audit',
  enforceOperatorIncidents: '/admin/enforce/incidents',
  enforceLegacyFinalReport: '/admin/enforce/legacy-final-report',
  enforceArtifactRetention: '/admin/enforce/artifact-retention'
} as const;

export const nettyRuntimeEndpoints = {
  health: '/api/admin/health',
  metrics: '/api/admin/metrics',
  runtimeSnapshot: '/api/admin/runtime/snapshot',
  runtimeLocal: '/api/admin/runtime/local',
  runtimeAgents: '/api/admin/runtime/agents',
  runtimeAgentsCluster: '/api/admin/runtime/agents?scope=cluster',
  runtimeSessions: '/api/websocket/sessions',
  runtimeRejectedConnections: '/api/admin/runtime/rejected-connections',
  runtimeDelivery: '/api/admin/runtime/delivery',
  runtimeCallbackRelay: '/api/admin/runtime/callback-relay',
  runtimeSlo: '/api/admin/runtime/slo',
  runtimeInbound: '/api/admin/runtime/inbound',
  runtimeStream: '/api/admin/runtime/stream',
  clusterNodes: '/api/admin/cluster/nodes',
  clusterTopology: '/api/admin/cluster/topology',
  clusterOverviewV2: '/api/cluster/overview',
  clusterNodesV2: '/api/cluster/nodes',
  clusterRuntimeMetricsV2: '/api/cluster/runtime-metrics',
  clusterPeersV2: '/api/cluster/peers',
  clusterAgentsV2: '/api/cluster/agents',
  clusterAgentsByNodeV2: '/api/cluster/agents/by-node',
  clusterStateLocalV2: '/api/cluster/state/local',
  clusterNodeDetail: (nodeId: string) => `/api/admin/cluster/nodes/${encodeURIComponent(nodeId)}`,
  clusterNodeAgents: (nodeId: string) => `/api/admin/cluster/nodes/${encodeURIComponent(nodeId)}/agents`,
  clusterNodeDrain: (nodeId: string) => `/api/admin/cluster/nodes/${encodeURIComponent(nodeId)}/drain`,
  clusterNodeResume: (nodeId: string) => `/api/admin/cluster/nodes/${encodeURIComponent(nodeId)}/resume`,
  agents: '/api/admin/agents',
  agentDetail: (agentId: string) => `/api/admin/agents/${encodeURIComponent(agentId)}`,
  agentPing: (agentId: string) => `/api/admin/agents/${encodeURIComponent(agentId)}/ping`,
  agentDisconnect: (agentId: string) => `/api/admin/agents/${encodeURIComponent(agentId)}/disconnect`,
  events: '/api/admin/events',
  eventDetail: (eventId: string) => `/api/admin/events/${encodeURIComponent(eventId)}`,
  traceDetail: (traceId: string) => `/api/admin/traces/${encodeURIComponent(traceId)}`
} as const;

/**
 * Backward-compatible Netty endpoint object used by the existing pages.
 * New P3B pages should prefer coreAdminEndpoints or nettyRuntimeEndpoints directly.
 */
export const adminEndpoints = nettyRuntimeEndpoints;
