export const coreAdminEndpoints = {
  dashboardSnapshot: '/admin/dashboard/snapshot',
  agentsRuntimeView: '/admin/agents/runtime-view',
  tasksRuntimeView: '/admin/tasks/runtime-view',
  taskDetail: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}`,
  taskRuntimeView: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/runtime-view`,
  taskCaseTimeline: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/case-timeline`,
  taskRetry: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/retry`,
  taskCancel: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/cancel`,
  taskReassign: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/reassign`,
  taskDispatchRequests: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/dispatch-requests`,
  taskDispatchAttemptHistory: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/dispatch-attempt-history`,
  taskDispatchLedger: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/dispatch-ledger`,
  taskCallbackInbox: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/callback-inbox`,
  taskCallbackInboxSummary: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/callback-inbox/summary`,
  taskRoutingDecisions: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/routing-decisions`,
  taskTimeline: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/timeline`,
  taskDispatchEvidence: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/dispatch-evidence`,
  taskRuntimeVerification: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/runtime-verification`,
  taskDispatchContractReadiness: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/dispatch-contract-readiness`,
  taskRepairDispatchContract: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/repair-dispatch-contract`,
  taskClassificationResult: (taskId: string) => `/api/agent/tasks/${encodeURIComponent(taskId)}/classification-result`,
  adapterActions: '/api/adapter-actions',
  adapterActionsByTask: (taskId: string) => `/api/adapter-actions/task/${encodeURIComponent(taskId)}`,
  adapterActionsByStatus: (status: string) => `/api/adapter-actions/status/${encodeURIComponent(status)}`,
  adapterActionExecute: (actionId: string) => `/api/adapter-actions/${encodeURIComponent(actionId)}/execute`,
  adapterActionExecuteRetry: (actionId: string) => `/api/adapter-actions/${encodeURIComponent(actionId)}/execute-retry`,
  adapterActionRetry: (actionId: string) => `/api/adapter-actions/${encodeURIComponent(actionId)}/retry`,
  adapterActionExecutePending: '/api/adapter-actions/execute-pending',
  adapterActionExecutorAudit: '/api/adapter-actions/executor-audit',
  adapterActionsMetadata: '/api/adapter-actions/metadata',
  issueTrackingRedmineDiagnostics: '/api/adapter-actions/issue-tracking/redmine/diagnostics',
  issueTrackingRedmineTestConnection: '/api/adapter-actions/issue-tracking/redmine/test-connection',
  issueTrackingRedmineProjects: '/api/adapter-actions/issue-tracking/redmine/projects',
  issueTrackingRedmineTrackers: '/api/adapter-actions/issue-tracking/redmine/trackers',
  issueTrackingRedmineTestIssue: '/api/adapter-actions/issue-tracking/redmine/test-issue',
  taskFailureQueue: '/admin/tasks/failure-queue',
  taskManualRetry: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/manual-retry`,
  taskDeadLetter: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/dead-letter`,
  taskEscalate: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/escalate`,
  recoveryMetrics: '/admin/recovery/metrics',
  recoveryRunbook: '/admin/recovery/runbook',
  recoveryApprovalRequests: '/admin/recovery/approval-requests',
  recoveryApprovalRequest: (approvalId: string) => `/admin/recovery/approval-requests/${encodeURIComponent(approvalId)}`,
  recoveryApprovalApprove: (approvalId: string) => `/admin/recovery/approval-requests/${encodeURIComponent(approvalId)}/approve`,
  recoveryApprovalReject: (approvalId: string) => `/admin/recovery/approval-requests/${encodeURIComponent(approvalId)}/reject`,
  recoveryApprovalCancel: (approvalId: string) => `/admin/recovery/approval-requests/${encodeURIComponent(approvalId)}/cancel`,
  recoveryClearRuntimeBackoff: (agentId: string) => `/admin/recovery/actions/agents/${encodeURIComponent(agentId)}/clear-runtime-backoff`,
  recoveryTriggerTaskNow: (taskId: string) => `/admin/recovery/actions/tasks/${encodeURIComponent(taskId)}/recover-now`,
  recoveryTaskDeadLetter: (taskId: string) => `/admin/recovery/actions/tasks/${encodeURIComponent(taskId)}/dead-letter`,
  recoveryTaskRestoreDeadLetter: (taskId: string) => `/admin/recovery/actions/tasks/${encodeURIComponent(taskId)}/restore-dead-letter`,
  recoveryDispatchDeadLetter: (dispatchRequestId: string) => `/admin/recovery/actions/dispatch-requests/${encodeURIComponent(dispatchRequestId)}/dead-letter`,
  recoveryDispatchRestoreDeadLetter: (dispatchRequestId: string) => `/admin/recovery/actions/dispatch-requests/${encodeURIComponent(dispatchRequestId)}/restore-dead-letter`,
  dispatchRequests: '/admin/dispatch-requests',
  callbackInboxRecent: '/admin/callbacks/inbox/recent',
  dispatchRequestCallbackInbox: (dispatchRequestId: string) => `/admin/dispatch-requests/${encodeURIComponent(dispatchRequestId)}/callback-inbox`,
  dispatchRequestCallbackInboxSummary: (dispatchRequestId: string) => `/admin/dispatch-requests/${encodeURIComponent(dispatchRequestId)}/callback-inbox/summary`,
  dispatchRequestRetry: (dispatchRequestId: string) => `/admin/dispatch-requests/${encodeURIComponent(dispatchRequestId)}/retry`,
  securityEvents: '/admin/security-events',
  agentSecurityEvents: '/admin/agent-security-events',
  agentGovernanceSummary: '/admin/agent-governance/summary',
  agentGovernanceMetadata: '/admin/agent-governance/metadata',
  agentGovernanceTableDiagnostics: '/admin/agent-governance/table-diagnostics',
  agentEnrollments: '/admin/agent-enrollments',
  agentEnrollmentApprove: (enrollmentId: string) => `/admin/agent-enrollments/${encodeURIComponent(enrollmentId)}/approve`,
  agentEnrollmentReject: (enrollmentId: string) => `/admin/agent-enrollments/${encodeURIComponent(enrollmentId)}/reject`,
  agents: '/admin/agents',
  agentSetup: '/admin/agents/setup',
  agentSetupReadiness: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/setup-readiness`,
  agentOperationalView: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/operational-view`,
  agentLatestAuthFailure: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/latest-auth-failure`,
  agentConnectionRepairActions: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/connection-repair-actions`,
  agentConnectionRepairActionExecute: (agentId: string, actionCode: string) => `/admin/agents/${encodeURIComponent(agentId)}/connection-repair-actions/${encodeURIComponent(actionCode)}`,
  agentDetail: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}`,
  agentUpdate: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}`,
  agentEnable: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/enable`,
  agentDisable: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/disable`,
  agentSuspend: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/suspend`,
  agentRevoke: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/revoke`,
  agentApprove: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/approve`,
  agentCredentialIssue: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/credentials/issue`,
  agentDisconnect: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/disconnect`,
  agentDisconnectAll: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/disconnect-all`,
  agentRuntimeDisconnectReconcile: '/admin/agents/runtime-disconnect/reconcile',
  agentDuplicateRuntimeEnforce: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/security/duplicate-runtime/enforce`,
  agentDuplicateRuntimeResolve: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/security/duplicate-runtime/resolve`,
  agentSecurityEnforcementPolicy: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/security/enforcement-policy`,
  agentSecurityEnforcementPolicies: '/admin/agent-security-enforcement-policies',
  defaultSecurityEnforcementPolicy: '/admin/agent-security-enforcement-policies/default',
  agentSkills: '/admin/agent-skills',
  agentSkillsMetadata: '/admin/agent-skills/metadata',
  agentSkill: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}`,
  agentSkillVersions: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/versions`,
  agentSkillDraftVersion: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/versions/draft`,
  agentSkillVersionAction: (skillCode: string, version: number, action: 'submit' | 'approve' | 'reject' | 'publish' | 'rollback') => `/admin/agent-skills/${encodeURIComponent(skillCode)}/versions/${encodeURIComponent(String(version))}/${action}`,
  agentSkillAudit: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/audit`,
  agentSkillVersionDiff: (skillCode: string, version: number) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/versions/${encodeURIComponent(String(version))}/diff`,
  agentSkillVersionImpact: (skillCode: string, version: number) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/versions/${encodeURIComponent(String(version))}/impact`,
  agentSkillApprovalPolicy: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/approval-policy`,
  agentSkillsDrift: '/admin/agent-skills/drift',
  agentSkillsDriftPolicyEvaluate: '/admin/agent-skills/drift/policy-evaluate',
  agentSkillDeprecationPlan: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/deprecation-plan`,
  agentSkillDeprecationAnalyze: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/deprecation-plan/analyze`,
  agentSkillDependencyGraph: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/dependency-graph`,
  agentSkillDependencies: (skillCode: string) => `/admin/agent-skills/${encodeURIComponent(skillCode)}/dependencies`,
  agentSkillFleetRemediationProposal: '/admin/agent-skills/drift/remediation-proposals',
  agentSkillRemediationProposal: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/skills/remediation-proposal`,
  agentRemediationProposal: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/remediation/proposal`,
  agentRemediationWorkflows: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/remediation/workflows`,
  agentRemediationWorkflow: (agentId: string, workflowId: string) => `/admin/agents/${encodeURIComponent(agentId)}/remediation/workflows/${encodeURIComponent(workflowId)}`,
  agentRemediationWorkflowApprove: (agentId: string, workflowId: string) => `/admin/agents/${encodeURIComponent(agentId)}/remediation/workflows/${encodeURIComponent(workflowId)}/approve`,
  agentRemediationWorkflowReject: (agentId: string, workflowId: string) => `/admin/agents/${encodeURIComponent(agentId)}/remediation/workflows/${encodeURIComponent(workflowId)}/reject`,
  agentRemediationWorkflowCancel: (agentId: string, workflowId: string) => `/admin/agents/${encodeURIComponent(agentId)}/remediation/workflows/${encodeURIComponent(workflowId)}/cancel`,
  agentRemediationWorkflowExecute: (agentId: string, workflowId: string) => `/admin/agents/${encodeURIComponent(agentId)}/remediation/workflows/${encodeURIComponent(workflowId)}/execute`,
  agentRemediationWorkflowStaleLeases: '/admin/remediation/workflow-leases/stale',
  agentRemediationWorkflowRecoveredLeases: '/admin/remediation/workflow-leases/recovered',
  agentRemediationWorkflowRecoverStaleLeases: '/admin/remediation/workflow-leases/recover-stale',
  agentSkillEvaluation: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/skills/evaluate`,
  agentSkillDrift: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/skills/drift`,
  dispatchContractResolve: '/admin/dispatch-contracts/resolve',
  dispatchRecipes: '/admin/dispatch-recipes',
  dispatchRecipe: (recipeCode: string) => `/admin/dispatch-recipes/${encodeURIComponent(recipeCode)}`,
  dispatchRecipeTemplates: '/admin/dispatch-recipes/templates',
  dispatchRecipeEvaluate: (recipeCode: string) => `/admin/dispatch-recipes/${encodeURIComponent(recipeCode)}/evaluate`,
  taskCapabilityResolve: '/admin/task-capabilities/resolve',
  dispatchReadinessEvaluate: '/admin/dispatch-readiness/evaluate',
  dispatchReadinessTemplates: '/admin/dispatch-readiness/templates',
  eventIntake: '/api/events/intake',
  agentApprovedSkills: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/skills/approved`,
  agentSkillSyncApprovedCapabilities: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/skills/sync-approved-capabilities`,
  agentRuntimeCapabilityProfile: (agentId: string) => `/api/agents/${encodeURIComponent(agentId)}/runtime/capability-profile`,
  agentRuntimeDescriptor: (agentId: string) => `/api/agents/${encodeURIComponent(agentId)}/runtime/descriptor`,
  agentRuntimeCapabilities: (agentId: string) => `/api/agents/${encodeURIComponent(agentId)}/runtime/capabilities`,
  agentRuntimeLoad: (agentId: string) => `/api/agents/${encodeURIComponent(agentId)}/runtime/load`,
  runtimeResources: '/admin/runtime-resources',
  runtimeResource: (runtimeId: string) => `/admin/runtime-resources/${encodeURIComponent(runtimeId)}`,
  agentRuntimeBindings: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-bindings`,
  agentRuntimeBindingActivate: (agentId: string, bindingId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-bindings/${encodeURIComponent(bindingId)}/activate`,
  agentRuntimeBindingPause: (agentId: string, bindingId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-bindings/${encodeURIComponent(bindingId)}/pause`,
  agentRuntimeBindingResume: (agentId: string, bindingId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-bindings/${encodeURIComponent(bindingId)}/resume`,
  agentRuntimeBindingRevoke: (agentId: string, bindingId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-bindings/${encodeURIComponent(bindingId)}/revoke`,
  runtimeFeatures: '/admin/runtime-features',
  runtimeFeature: (featureCode: string) => `/admin/runtime-features/${encodeURIComponent(featureCode)}`,
  capabilities: '/admin/capabilities',
  capability: (capabilityCode: string) => `/admin/capabilities/${encodeURIComponent(capabilityCode)}`,
  dispatchPoliciesV2: '/admin/dispatch-policies',
  dispatchPolicyV2: (policyCode: string) => `/admin/dispatch-policies/${encodeURIComponent(policyCode)}`,
  dispatchPolicyScopes: (policyCode: string) => `/admin/dispatch-policies/${encodeURIComponent(policyCode)}/scopes`,
  dispatchPolicyRequiredCapabilities: (policyCode: string) => `/admin/dispatch-policies/${encodeURIComponent(policyCode)}/required-capabilities`,
  dispatchPolicyRequiredRuntimeFeatures: (policyCode: string) => `/admin/dispatch-policies/${encodeURIComponent(policyCode)}/required-runtime-features`,
  dispatchPolicyQualityRules: (policyCode: string) => `/admin/dispatch-policies/${encodeURIComponent(policyCode)}/quality-rules`,
  dispatchPolicyScoringRules: (policyCode: string) => `/admin/dispatch-policies/${encodeURIComponent(policyCode)}/scoring-rules`,
  dispatchTaskDefinitions: '/admin/dispatch-task-definitions',
  dispatchTaskDefinition: (definitionId: string) => `/admin/dispatch-task-definitions/${encodeURIComponent(definitionId)}`,
  dispatchTaskDefinitionImpactPreview: (definitionId: string) => `/admin/dispatch-task-definitions/${encodeURIComponent(definitionId)}/impact-preview`,
  dispatchTaskDefinitionActivate: (definitionId: string) => `/admin/dispatch-task-definitions/${encodeURIComponent(definitionId)}/activate`,
  dispatchTaskDefinitionRetire: (definitionId: string) => `/admin/dispatch-task-definitions/${encodeURIComponent(definitionId)}/retire`,
  dispatchTaskDefinitionMerge: (definitionId: string) => `/admin/dispatch-task-definitions/${encodeURIComponent(definitionId)}/merge`,

  sourceSystems: '/admin/source-systems',
  sourceSystem: (sourceSystemId: string) => `/admin/source-systems/${encodeURIComponent(sourceSystemId)}`,

  dispatchFlows: '/admin/dispatch-flows',
  dispatchFlowAgentOptions: '/admin/dispatch-flows/agent-options',
  agentPools: '/admin/dispatch-flows/agent-pools',
  agentPool: (poolId: string) => `/admin/dispatch-flows/agent-pools/${encodeURIComponent(poolId)}`,
  dispatchFlowsByAgent: (agentId: string) => `/admin/dispatch-flows/by-agent/${encodeURIComponent(agentId)}`,
  dispatchFlow: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}`,
  dispatchFlowRealTestEvent: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/test-event`,
  dispatchFlowDryRun: '/admin/dispatch-flows/dry-run',
  dispatchFlowScopedDryRun: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/dry-run`,
  dispatchFlowReadiness: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/readiness`,
  dispatchFlowRules: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/rules`,
  dispatchFlowSkills: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/skills`,
  dispatchFlowAgents: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/agents`,
  dispatchFlowAgentPreview: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/agents/preview`,
  dispatchFlowRulePreview: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/rules/preview`,
  dispatchFlowTrace: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/trace`,
  dispatchFlowTestExternal: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/test-external`,
  dispatchFlowTestA2a: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/test-a2a`,
  dispatchFlowTestResult: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/test-result`,
  dispatchFlowTestChain: (flowId: string) => `/admin/dispatch-flows/${encodeURIComponent(flowId)}/test-chain`,
  dispatchContractSourceSystems: '/admin/dispatch-contracts/source-systems',
  dispatchContractBootstrap: '/admin/dispatch-contracts/bootstrap',
  dispatchContractReadiness: '/admin/dispatch-contracts/readiness',
  dispatchContractInspect: '/admin/dispatch-contracts/inspect',
  dispatchContractTrace: '/admin/dispatch-contracts/trace',
  dispatchContractTestTask: '/admin/dispatch-contracts/test-task',
  agentQualityDaily: (agentId: string) => `/admin/quality/agents/${encodeURIComponent(agentId)}/daily`,
  agentQualityWindows: (agentId: string) => `/admin/quality/agents/${encodeURIComponent(agentId)}/windows`,
  runtimeQualityDaily: (runtimeId: string) => `/admin/quality/runtime/${encodeURIComponent(runtimeId)}/daily`,
  supplyProfileQualitySnapshots: '/admin/quality/supply-profiles',
  supplyProfileQualitySnapshot: (profileCode: string) => `/admin/supply-profiles/${encodeURIComponent(profileCode)}/quality-snapshot`,
  supplyProfiles: '/admin/supply-profiles',
  supplyProfile: (profileCode: string) => `/admin/supply-profiles/${encodeURIComponent(profileCode)}`,
  agentSupplyProfiles: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/supply-profiles`,
  assignmentProfiles: '/admin/assignment-profiles',
  assignmentProfile: (profileCode: string) => `/admin/assignment-profiles/${encodeURIComponent(profileCode)}`,
  assignmentProfilePolicies: (profileCode: string) => `/admin/assignment-profiles/${encodeURIComponent(profileCode)}/policies`,
  assignmentProfileCapabilities: (profileCode: string) => `/admin/assignment-profiles/${encodeURIComponent(profileCode)}/capabilities`,
  assignmentProfileRelationshipMap: (profileCode: string) => `/admin/assignment-profiles/${encodeURIComponent(profileCode)}/relationship-map`,
  assignmentProfileImpactPreview: (profileCode: string) => `/admin/assignment-profiles/${encodeURIComponent(profileCode)}/impact-preview`,
  assignmentProfilePolicy: (profileCode: string, policyCode: string) => `/admin/assignment-profiles/${encodeURIComponent(profileCode)}/policies/${encodeURIComponent(policyCode)}`,
  assignmentProfileCapability: (profileCode: string, capabilityCode: string) => `/admin/assignment-profiles/${encodeURIComponent(profileCode)}/capabilities/${encodeURIComponent(capabilityCode)}`, 
  certificationProfiles: '/admin/certification-profiles',
  certificationTimeoutScan: '/admin/certifications/scan-timeouts',
  agentCertifications: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/certifications`,
  runAgentCertification: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/certifications/run`,
  passAgentCertification: (agentId: string, runId: string) => `/admin/agents/${encodeURIComponent(agentId)}/certifications/${encodeURIComponent(runId)}/pass`,
  failAgentCertification: (agentId: string, runId: string) => `/admin/agents/${encodeURIComponent(agentId)}/certifications/${encodeURIComponent(runId)}/fail`,
  timeoutAgentCertification: (agentId: string, runId: string) => `/admin/agents/${encodeURIComponent(agentId)}/certifications/${encodeURIComponent(runId)}/timeout`,
  agentCapabilities: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/capabilities`,
  agentCapabilityRemove: (agentId: string, assignmentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/capabilities/${encodeURIComponent(assignmentId)}/remove`,
  agentCapabilityDelete: (agentId: string, assignmentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/capabilities/${encodeURIComponent(assignmentId)}`,
  agentCapabilityApprove: (agentId: string, assignmentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/capabilities/${encodeURIComponent(assignmentId)}/approve`,
  agentCapabilitySuspend: (agentId: string, assignmentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/capabilities/${encodeURIComponent(assignmentId)}/suspend`,
  agentCapabilityResume: (agentId: string, assignmentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/capabilities/${encodeURIComponent(assignmentId)}/resume`,
  agentCapabilityRevoke: (agentId: string, assignmentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/capabilities/${encodeURIComponent(assignmentId)}/revoke`,
  agentRuntimeFeatureObservations: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features/observations`,
  agentRuntimeFeatureTrusts: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features/trust`,
  agentRuntimeFeatureObserve: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features`,
  agentRuntimeFeatureVerify: (agentId: string, trustId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features/${encodeURIComponent(trustId)}/verify`,
  agentRuntimeFeatureTrust: (agentId: string, trustId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features/${encodeURIComponent(trustId)}/trust`,
  agentRuntimeFeatureSuspend: (agentId: string, trustId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features/${encodeURIComponent(trustId)}/suspend`,
  agentRuntimeFeatureResume: (agentId: string, trustId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features/${encodeURIComponent(trustId)}/resume`,
  agentRuntimeFeatureRevoke: (agentId: string, trustId: string) => `/admin/agents/${encodeURIComponent(agentId)}/runtime-features/${encodeURIComponent(trustId)}/revoke`,
  agentQualifications: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/qualifications`,
  agentQualificationRemove: (agentId: string, qualificationId: string) => `/admin/agents/${encodeURIComponent(agentId)}/qualifications/${encodeURIComponent(qualificationId)}`,
  agentQualificationApprove: (agentId: string, qualificationId: string) => `/admin/agents/${encodeURIComponent(agentId)}/qualifications/${encodeURIComponent(qualificationId)}/approve`,
  agentQualificationSuspend: (agentId: string, qualificationId: string) => `/admin/agents/${encodeURIComponent(agentId)}/qualifications/${encodeURIComponent(qualificationId)}/suspend`,
  agentQualificationResume: (agentId: string, qualificationId: string) => `/admin/agents/${encodeURIComponent(agentId)}/qualifications/${encodeURIComponent(qualificationId)}/resume`,
  agentQualificationRevoke: (agentId: string, qualificationId: string) => `/admin/agents/${encodeURIComponent(agentId)}/qualifications/${encodeURIComponent(qualificationId)}/revoke`,
  agentEnterpriseGovernance: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/enterprise-governance`,
  agentDispatchEligibility: (agentId: string) => `/admin/agents/${encodeURIComponent(agentId)}/dispatch-eligibility`,
  agentDispatchEligibilityForTask: (agentId: string, taskId: string) => `/admin/agents/${encodeURIComponent(agentId)}/dispatch-eligibility?taskId=${encodeURIComponent(taskId)}`,
  taskDispatchRequirements: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/dispatch-requirements`,
  taskEligibleAgents: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/eligible-agents`,
  taskEligibleAgentsV2: (taskId: string) => `/admin/tasks/${encodeURIComponent(taskId)}/eligible-agents-v2`,
  enforceObservabilitySnapshot: '/admin/enforce/observability',
  enforceRoutingAuditSearch: '/admin/enforce/routing-audit',
  enforceOperatorIncidents: '/admin/enforce/incidents',
  enforceLegacyFinalReport: '/admin/enforce/legacy-final-report',
  enforceArtifactRetention: '/admin/enforce/artifact-retention'
} as const;

export const nettyRuntimeEndpoints = {
  health: '/api/admin/health',
  metrics: '/api/admin/metrics',
  runtimeSnapshot: '/api/admin/runtime/snapshot',
  runtimeLocal: '/api/admin/runtime/local',
  runtimeAgents: '/api/admin/runtime/agents',
  runtimeAgentsCluster: '/api/admin/runtime/agents?scope=cluster',
  runtimeSessions: '/api/websocket/sessions',
  runtimeRejectedConnections: '/api/admin/runtime/rejected-connections',
  runtimeDelivery: '/api/admin/runtime/delivery',
  runtimeCallbackRelay: '/api/admin/runtime/callback-relay',
  runtimeSlo: '/api/admin/runtime/slo',
  runtimeInbound: '/api/admin/runtime/inbound',
  runtimeStream: '/api/admin/runtime/stream',
  clusterNodes: '/api/admin/cluster/nodes',
  clusterTopology: '/api/admin/cluster/topology',
  clusterOverviewV2: '/api/cluster/overview',
  clusterNodesV2: '/api/cluster/nodes',
  clusterRuntimeMetricsV2: '/api/cluster/runtime-metrics',
  clusterPeersV2: '/api/cluster/peers',
  clusterAgentsV2: '/api/cluster/agents',
  clusterAgentsByNodeV2: '/api/cluster/agents/by-node',
  clusterStateLocalV2: '/api/cluster/state/local',
  clusterNodeDetail: (nodeId: string) => `/api/admin/cluster/nodes/${encodeURIComponent(nodeId)}`,
  clusterNodeAgents: (nodeId: string) => `/api/admin/cluster/nodes/${encodeURIComponent(nodeId)}/agents`,
  clusterNodeDrain: (nodeId: string) => `/api/admin/cluster/nodes/${encodeURIComponent(nodeId)}/drain`,
  clusterNodeResume: (nodeId: string) => `/api/admin/cluster/nodes/${encodeURIComponent(nodeId)}/resume`,
  agents: '/api/admin/agents',
  agentDetail: (agentId: string) => `/api/admin/agents/${encodeURIComponent(agentId)}`,
  agentPing: (agentId: string) => `/api/admin/agents/${encodeURIComponent(agentId)}/ping`,
  agentDisconnect: (agentId: string) => `/api/admin/agents/${encodeURIComponent(agentId)}/disconnect`,
  events: '/api/admin/events',
  eventDetail: (eventId: string) => `/api/admin/events/${encodeURIComponent(eventId)}`,
  traceDetail: (traceId: string) => `/api/admin/traces/${encodeURIComponent(traceId)}`
} as const;

/**
 * Backward-compatible Netty endpoint object used by the existing pages.
 * New P3B pages should prefer coreAdminEndpoints or nettyRuntimeEndpoints directly.
 */
export const adminEndpoints = nettyRuntimeEndpoints;
