package com.opensocket.aievent.core.integration.identity;

import static org.junit.jupiter.api.Assertions.*;
import java.time.OffsetDateTime; import java.util.*; import org.junit.jupiter.api.Test;
class IntegrationIdentityServiceTest {
 @Test void scopedProbeActivatesPrincipalAndResolvesMostSpecificMapping(){var repo=new InMemoryIntegrationIdentityRepository();var service=service(repo,List.of());seed(service);saveAndProbe(service,"default",mapping("ERP",null,null,100,false));saveAndProbe(service,"specific",mapping("MES","MES","REPAIR",10,false));enable(service,"default",mapping("ERP",null,null,100,true));enable(service,"specific",mapping("MES","MES","REPAIR",10,true));assertEquals("specific",service.resolve(new MappingResolutionRequest("tenant-a","jira","ERP",null,"ERP","MES","REPAIR")).mappingId());}
 @Test void rawSecretLookingValueIsRejected(){var service=service(new InMemoryIntegrationIdentityRepository(),List.of());seedConnectionAndPrincipal(service);assertThrows(IllegalArgumentException.class,()->service.addCredential("tenant-a","erp-principal","bad",credential("abcdefghijklmnopqrstuvwxyz")));}
 @Test void overPrivilegedPrincipalRequiresExpiringOverride(){var repo=new InMemoryIntegrationIdentityRepository();var service=service(repo,List.of("PROVIDER_ADMINISTRATOR"));seed(service);service.saveMapping("tenant-a","blocked",mapping("ERP",null,null,100,false),null);service.probe("tenant-a","erp-principal","blocked","corr");assertThrows(IllegalStateException.class,()->service.saveMapping("tenant-a","blocked",mapping("ERP",null,null,100,true),2L));service.grantSecurityOverride("tenant-a","override-1",new IntegrationSecurityOverride(null,null,"erp-principal","blocked","OVER_PRIVILEGED_MAPPING","Temporary approved test","security-admin",null,OffsetDateTime.now().plusHours(1),null,null,null,"corr",0,null,null));service.saveMapping("tenant-a","blocked",mapping("ERP",null,null,100,true),2L);assertTrue(service.mapping("tenant-a","blocked").enabled());}
 @Test void rotationKeepsOldCredentialActiveUntilProbeThenEntersGrace(){var repo=new InMemoryIntegrationIdentityRepository();var service=service(repo,List.of());seed(service);service.rotateCredential("tenant-a","erp-principal","credential","credential-v2",credential("vault://tenant-a/jira/erp-v2"));assertEquals(IntegrationCredentialStatus.ACTIVE,repo.findCredential("tenant-a","credential").orElseThrow().status());assertEquals("PENDING_PROBE",repo.listRotationEvents("tenant-a","erp-principal",10).getFirst().status());service.probe("tenant-a","erp-principal",null,"rotation-probe");assertEquals(IntegrationCredentialStatus.ACTIVE,repo.findCredential("tenant-a","credential-v2").orElseThrow().status());assertEquals(IntegrationCredentialStatus.GRACE_PERIOD,repo.findCredential("tenant-a","credential").orElseThrow().status());assertEquals("ACTIVE_GRACE_PERIOD",repo.listRotationEvents("tenant-a","erp-principal",10).getFirst().status());}
 @Test void perProjectPrincipalCannotAccessMesProject(){var repo=new InMemoryIntegrationIdentityRepository();var service=service(repo,List.of());seedConnectionAndPrincipal(service);service.addCredential("tenant-a","erp-principal","credential",credential("vault://tenant-a/jira/erp"));service.savePrincipalScope("tenant-a","erp-principal",new IntegrationPrincipalScope(null,null,IntegrationIsolationMode.PER_PROJECT,"ERP",List.of("ERP"),List.of(IntegrationOperation.values()),List.of("*"),true,0,null,null),null);service.probe("tenant-a","erp-principal",null,"corr");assertThrows(IllegalStateException.class,()->service.saveMapping("tenant-a","mes",mapping("MES",null,null,100,false),null));}
 private static IntegrationIdentityService service(InMemoryIntegrationIdentityRepository repo,List<String> elevated){return new IntegrationIdentityService(repo,(c,p,k,m)->{var r=new EnumMap<IntegrationPermissionCapability,PermissionProbeResultStatus>(IntegrationPermissionCapability.class);for(var cap:IntegrationPermissionCapability.values())r.put(cap,PermissionProbeResultStatus.GRANTED);return new PermissionProbeObservation(r,elevated,"ok");});}
 private static void seedConnectionAndPrincipal(IntegrationIdentityService s){s.saveConnection("tenant-a","jira",new IntegrationConnection(null,null,IntegrationProviderType.JIRA,"Jira","https://jira.example","SELF_HOSTED",null,IntegrationConnectionStatus.DRAFT,10000,null,null,null,false,0,null,null),null);s.savePrincipal("tenant-a","jira","erp-principal",new IntegrationPrincipal(null,null,null,"ERP",IntegrationPrincipalType.SERVICE_ACCOUNT,"ERP",null,"manufacturing",null,IntegrationPrincipalStatus.DRAFT,IntegrationRiskLevel.UNKNOWN,Map.of(),List.of(),null,0,null,null),null);}
 private static void seed(IntegrationIdentityService s){seedConnectionAndPrincipal(s);s.addCredential("tenant-a","erp-principal","credential",credential("vault://tenant-a/jira/erp"));s.savePrincipalScope("tenant-a","erp-principal",new IntegrationPrincipalScope(null,null,IntegrationIsolationMode.PER_TRUST_ZONE,"manufacturing",List.of("ERP","MES"),List.of(IntegrationOperation.values()),List.of("*"),true,0,null,null),null);s.probe("tenant-a","erp-principal",null,"corr");}
 private static void saveAndProbe(IntegrationIdentityService s,String id,IntegrationProjectMapping m){s.saveMapping("tenant-a",id,m,null);s.probe("tenant-a","erp-principal",id,"probe-"+id);}
 private static void enable(IntegrationIdentityService s,String id,IntegrationProjectMapping m){s.saveMapping("tenant-a",id,m,2L);}
 private static IntegrationCredentialMetadata credential(String ref){return new IntegrationCredentialMetadata(null,null,null,IntegrationAuthType.API_TOKEN,ref,"v1","1234",OffsetDateTime.now(),null,null,null,IntegrationCredentialStatus.PENDING_VALIDATION,0,null,null);}
 private static IntegrationProjectMapping mapping(String project,String source,String task,int priority,boolean enabled){return new IntegrationProjectMapping(null,null,"jira","ERP",null,"ERP",source,task,project,null,"Task",null,"erp-principal","erp-principal","erp-principal",null,null,null,null,null,null,ProjectMappingStatus.VALID,priority,project.equals("ERP"),enabled,0,null,null);}
}
