package com.opensocket.aievent.core.api;

import com.opensocket.aievent.core.capability.A2APeerRegistryService;
import com.opensocket.aievent.core.capability.A2APeerTrustEvidenceService;
import com.opensocket.aievent.core.capability.A2APeerProcessingAttestationService;
import com.opensocket.aievent.core.capability.A2APeerInterfaceContractService;
import com.opensocket.aievent.core.capability.A2ATrustAssurancePolicyService;
import com.opensocket.aievent.core.capability.A2AVersionPolicyService;
import com.opensocket.aievent.core.capability.A2APeerErrorMappingService;
import com.opensocket.aievent.core.capability.A2AInterfaceConformanceService;
import com.opensocket.aievent.core.capability.A2AExternalF0SecurityService;
import com.opensocket.aievent.core.resourceaccess.runtime.ScopedBusinessResourceAccessCoordinator;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.web.bind.annotation.*;

/** Stage 7/8 external A2A peer governance. This API manages trust; it is not a runtime target selector. */
@RestController
@RequestMapping("/admin/a2a-peers")
public class A2APeerRegistryController {
    private final A2APeerRegistryService service; private final A2APeerTrustEvidenceService trustEvidence; private final A2ATrustAssurancePolicyService assurance; private final A2APeerProcessingAttestationService processingAttestations; private final A2APeerInterfaceContractService interfaceContracts; private final A2AVersionPolicyService versionPolicies; private final A2APeerErrorMappingService errorMappings; private final A2AInterfaceConformanceService conformance; private final A2AExternalF0SecurityService f0Security; private final ObjectProvider<ScopedBusinessResourceAccessCoordinator> scoped;
    public A2APeerRegistryController(A2APeerRegistryService service,A2APeerTrustEvidenceService trustEvidence,A2ATrustAssurancePolicyService assurance,A2APeerProcessingAttestationService processingAttestations,A2APeerInterfaceContractService interfaceContracts,A2AVersionPolicyService versionPolicies,A2APeerErrorMappingService errorMappings,A2AInterfaceConformanceService conformance,A2AExternalF0SecurityService f0Security,ObjectProvider<ScopedBusinessResourceAccessCoordinator> scoped){this.service=service;this.trustEvidence=trustEvidence;this.assurance=assurance;this.processingAttestations=processingAttestations;this.interfaceContracts=interfaceContracts;this.versionPolicies=versionPolicies;this.errorMappings=errorMappings;this.conformance=conformance;this.f0Security=f0Security;this.scoped=scoped;}
    @GetMapping public List<Map<String,Object>> peers(@RequestParam(required=false)String tenantId){return service.peers(tenant(tenantId));}
    @PutMapping("/{peerId}") public Map<String,Object> upsert(@PathVariable String peerId,@RequestParam(required=false)String tenantId,@RequestBody Map<String,Object> body){return service.upsertPeer(tenant(tenantId),peerId,str(body,"displayName"),str(body,"agentCardUrl"));}
    @PostMapping("/{peerId}/refresh-agent-card") public Map<String,Object> refresh(@PathVariable String peerId,@RequestParam(required=false)String tenantId){return service.refreshAgentCard(tenant(tenantId),peerId);}
    @PostMapping("/{peerId}/activate") public Map<String,Object> activate(@PathVariable String peerId,@RequestParam(required=false)String tenantId){String t=tenant(tenantId);service.activatePeer(t,peerId);return Map.of("peerId",peerId,"status","ACTIVE");}
    @GetMapping("/{peerId}/interfaces") public List<Map<String,Object>> interfaces(@PathVariable String peerId,@RequestParam(required=false)String tenantId){return service.interfaces(tenant(tenantId),peerId);}
    @PostMapping("/interfaces/{interfaceId}/approve") public Map<String,Object> approve(@PathVariable String interfaceId,@RequestParam(required=false)String tenantId,@RequestBody(required=false)Map<String,Object> body){return service.approveInterface(tenant(tenantId),interfaceId,body==null?null:str(body,"trustStatus"));}
    @GetMapping("/interfaces/{interfaceId}/contract") public Map<String,Object> interfaceContract(@PathVariable String interfaceId,@RequestParam(required=false)String tenantId){return interfaceContracts.explain(tenant(tenantId),interfaceId);}
    @PutMapping("/interfaces/{interfaceId}/contract") public Map<String,Object> configureInterfaceContract(@PathVariable String interfaceId,@RequestParam(required=false)String tenantId,@RequestBody Map<String,Object> body){return interfaceContracts.configure(tenant(tenantId),interfaceId,str(body,"endpointRegion"),listOfStrings(body,"securitySchemeRefs"),listOfStrings(body,"requiredExtensions"),listOfStrings(body,"supportedExtensions"),str(body,"outboundDestinationPolicyRef"),integer(body,"priority"));}
    @PostMapping("/interfaces/{interfaceId}/operational-state") public Map<String,Object> interfaceOperationalState(@PathVariable String interfaceId,@RequestParam(required=false)String tenantId,@RequestBody Map<String,Object> body){return interfaceContracts.operationalState(tenant(tenantId),interfaceId,str(body,"healthStatus"),str(body,"conformanceStatus"),str(body,"circuitState"));}
    @GetMapping("/conformance/profiles") public List<Map<String,Object>> conformanceProfiles(@RequestParam(required=false)String tenantId){return conformance.profiles(tenant(tenantId));}
    @GetMapping("/conformance/profiles/{profileId}") public Map<String,Object> conformanceProfile(@PathVariable String profileId,@RequestParam(required=false)String tenantId){return conformance.profile(tenant(tenantId),profileId);}
    @PutMapping("/conformance/profiles/{profileId}") public Map<String,Object> upsertConformanceProfile(@PathVariable String profileId,@RequestParam(required=false)String tenantId,@RequestBody Map<String,Object> body){return conformance.upsertDraft(tenant(tenantId),profileId,str(body,"displayName"),str(body,"description"),listOfStrings(body,"requiredChecks"),integer(body,"validForSeconds"),integer(body,"maxAgentCardAgeSeconds"));}
    @PostMapping("/conformance/profiles/{profileId}/activate") public Map<String,Object> activateConformanceProfile(@PathVariable String profileId,@RequestParam(required=false)String tenantId){return conformance.activateProfile(tenant(tenantId),profileId);}
    @GetMapping("/interfaces/{interfaceId}/conformance") public Map<String,Object> interfaceConformance(@PathVariable String interfaceId,@RequestParam(required=false)String tenantId){return conformance.explain(tenant(tenantId),interfaceId);}
    @GetMapping("/interfaces/{interfaceId}/conformance/runs") public List<Map<String,Object>> interfaceConformanceRuns(@PathVariable String interfaceId,@RequestParam(required=false)String tenantId){return conformance.runs(tenant(tenantId),interfaceId);}
    @PostMapping("/interfaces/{interfaceId}/conformance/run") public Map<String,Object> runInterfaceConformance(@PathVariable String interfaceId,@RequestParam(required=false)String tenantId){return conformance.run(tenant(tenantId),interfaceId);}
    @GetMapping("/interfaces/{interfaceId}/credential-bindings") public List<Map<String,Object>> credentialBindings(@PathVariable String interfaceId,@RequestParam(required=false)String tenantId){return f0Security.credentialBindings(tenant(tenantId),interfaceId);}
    @PutMapping("/interfaces/{interfaceId}/credential-bindings/{bindingId}") public Map<String,Object> upsertCredentialBinding(@PathVariable String interfaceId,@PathVariable String bindingId,@RequestParam(required=false)String tenantId,@RequestBody Map<String,Object> body){return f0Security.upsertCredentialDraft(tenant(tenantId),interfaceId,bindingId,str(body,"securitySchemeRef"),str(body,"credentialType"),str(body,"secretRef"),str(body,"headerName"),str(body,"authScheme"));}
    @PostMapping("/interfaces/{interfaceId}/credential-bindings/{bindingId}/validate") public Map<String,Object> validateCredentialBinding(@PathVariable String interfaceId,@PathVariable String bindingId,@RequestParam(required=false)String tenantId){return f0Security.validateCredential(tenant(tenantId),bindingId);}
    @PostMapping("/interfaces/{interfaceId}/credential-bindings/{bindingId}/activate") public Map<String,Object> activateCredentialBinding(@PathVariable String interfaceId,@PathVariable String bindingId,@RequestParam(required=false)String tenantId){return f0Security.activateCredential(tenant(tenantId),bindingId);}
    @PostMapping("/interfaces/{interfaceId}/credential-bindings/{bindingId}/retire") public Map<String,Object> retireCredentialBinding(@PathVariable String interfaceId,@PathVariable String bindingId,@RequestParam(required=false)String tenantId){return f0Security.retireCredential(tenant(tenantId),bindingId);}
    @GetMapping("/outbound-policies") public List<Map<String,Object>> outboundPolicies(@RequestParam(required=false)String tenantId){return f0Security.outboundPolicies(tenant(tenantId));}
    @GetMapping("/outbound-policies/{policyId}") public Map<String,Object> outboundPolicy(@PathVariable String policyId,@RequestParam(required=false)String tenantId){return f0Security.outboundPolicy(tenant(tenantId),policyId);}
    @PutMapping("/outbound-policies/{policyId}") public Map<String,Object> upsertOutboundPolicy(@PathVariable String policyId,@RequestParam(required=false)String tenantId,@RequestBody Map<String,Object> body){return f0Security.upsertOutboundPolicyDraft(tenant(tenantId),policyId,str(body,"displayName"),str(body,"description"),listOfStrings(body,"allowedSchemes"),listOfStrings(body,"allowlistHostSuffixes"),listOfStrings(body,"allowlistCidrs"),bool(body,"denyPrivateAddresses"),bool(body,"denyLoopbackAddresses"),bool(body,"denyLinkLocalAddresses"),bool(body,"denyCloudMetadataEndpoints"),integer(body,"maxRedirects"),bool(body,"followRedirectSameOriginOnly"),bool(body,"dnsRebindingProtection"),integer(body,"connectTimeoutMs"),integer(body,"readTimeoutMs"),str(body,"requiredTlsVersion"),listOfStrings(body,"certificatePins"));}
    @PostMapping("/outbound-policies/{policyId}/activate") public Map<String,Object> activateOutboundPolicy(@PathVariable String policyId,@RequestParam(required=false)String tenantId){return f0Security.activateOutboundPolicy(tenant(tenantId),policyId);}
    @PostMapping("/outbound-policies/{policyId}/retire") public Map<String,Object> retireOutboundPolicy(@PathVariable String policyId,@RequestParam(required=false)String tenantId){return f0Security.retireOutboundPolicy(tenant(tenantId),policyId);}
    @GetMapping("/{peerId}/trust-evidence") public List<Map<String,Object>> trustEvidence(@PathVariable String peerId,@RequestParam(required=false)String tenantId,@RequestParam(defaultValue="false")boolean activeOnly){return trustEvidence.evidence(tenant(tenantId),peerId,activeOnly);}
    @PostMapping("/{peerId}/trust-evidence") public Map<String,Object> recordTrustEvidence(@PathVariable String peerId,@RequestParam(required=false)String tenantId,@RequestBody Map<String,Object> body){return trustEvidence.record(tenant(tenantId),peerId,str(body,"subjectType"),str(body,"interfaceId"),str(body,"evidenceType"),str(body,"issuer"),str(body,"source"),str(body,"evidenceRef"),str(body,"evidenceDigest"),map(body,"details"),time(body,"observedAt"),time(body,"validFrom"),time(body,"validUntil"));}
    @PostMapping("/{peerId}/trust-evidence/{evidenceId}/revoke") public Map<String,Object> revokeTrustEvidence(@PathVariable String peerId,@PathVariable String evidenceId,@RequestParam(required=false)String tenantId,@RequestBody Map<String,Object> body){return trustEvidence.revoke(tenant(tenantId),peerId,evidenceId,str(body,"reason"));}
    @GetMapping("/trust-assurance/policies") public List<Map<String,Object>> assurancePolicies(@RequestParam(required=false)String tenantId){return assurance.policies(tenant(tenantId));}
    @GetMapping("/trust-assurance/policies/{policyId}") public Map<String,Object> assurancePolicy(@PathVariable String policyId,@RequestParam(required=false)String tenantId){return assurance.policy(tenant(tenantId),policyId);}
    @PutMapping("/trust-assurance/policies/{policyId}") public Map<String,Object> upsertAssurancePolicy(@PathVariable String policyId,@RequestParam(required=false)String tenantId,@RequestBody Map<String,Object> body){return assurance.upsertDraft(tenant(tenantId),policyId,str(body,"displayName"),str(body,"description"),listOfMaps(body,"rules"));}
    @PostMapping("/trust-assurance/policies/{policyId}/activate") public Map<String,Object> activateAssurancePolicy(@PathVariable String policyId,@RequestParam(required=false)String tenantId){return assurance.activate(tenant(tenantId),policyId);}
    @GetMapping("/{peerId}/trust-assurance") public Map<String,Object> trustAssurance(@PathVariable String peerId,@RequestParam(required=false)String interfaceId,@RequestParam(required=false)String tenantId){return assurance.explain(tenant(tenantId),peerId,interfaceId);}
    @GetMapping("/{peerId}/processing-attestations") public List<Map<String,Object>> processingAttestations(@PathVariable String peerId,@RequestParam(required=false)String tenantId,@RequestParam(defaultValue="false")boolean currentOnly){return processingAttestations.attestations(tenant(tenantId),peerId,currentOnly);}
    @PostMapping("/{peerId}/processing-attestations") public Map<String,Object> recordProcessingAttestation(@PathVariable String peerId,@RequestParam(required=false)String tenantId,@RequestBody Map<String,Object> body){return processingAttestations.record(tenant(tenantId),peerId,str(body,"attestationType"),str(body,"processingRegion"),str(body,"storageRegion"),str(body,"issuer"),str(body,"source"),str(body,"evidenceRef"),str(body,"evidenceDigest"),map(body,"details"),time(body,"validFrom"),time(body,"validUntil"));}
    @PostMapping("/{peerId}/processing-attestations/{attestationId}/verify") public Map<String,Object> verifyProcessingAttestation(@PathVariable String peerId,@PathVariable String attestationId,@RequestParam(required=false)String tenantId,@RequestBody(required=false)Map<String,Object> body){return processingAttestations.verify(tenant(tenantId),peerId,attestationId,body==null?null:str(body,"note"));}
    @PostMapping("/{peerId}/processing-attestations/{attestationId}/revoke") public Map<String,Object> revokeProcessingAttestation(@PathVariable String peerId,@PathVariable String attestationId,@RequestParam(required=false)String tenantId,@RequestBody Map<String,Object> body){return processingAttestations.revoke(tenant(tenantId),peerId,attestationId,str(body,"reason"));}
    @GetMapping("/version-policies") public List<Map<String,Object>> versionPolicies(@RequestParam(required=false)String tenantId){return versionPolicies.policies(tenant(tenantId));}
    @GetMapping("/version-policies/{policyId}") public Map<String,Object> versionPolicy(@PathVariable String policyId,@RequestParam(required=false)String tenantId){return versionPolicies.policy(tenant(tenantId),policyId);}
    @PutMapping("/version-policies/{policyId}") public Map<String,Object> upsertVersionPolicy(@PathVariable String policyId,@RequestParam(required=false)String tenantId,@RequestBody Map<String,Object> body){return versionPolicies.upsertDraft(tenant(tenantId),policyId,str(body,"displayName"),str(body,"description"),str(body,"preferredVersion"),str(body,"minAcceptedVersion"),str(body,"maxAcceptedVersion"),listOfStrings(body,"deprecatedVersions"),listOfMaps(body,"legacyAllowlist"));}
    @PostMapping("/version-policies/{policyId}/activate") public Map<String,Object> activateVersionPolicy(@PathVariable String policyId,@RequestParam(required=false)String tenantId){return versionPolicies.activate(tenant(tenantId),policyId);}
    @GetMapping("/interfaces/{interfaceId}/version-policy") public Map<String,Object> interfaceVersionPolicy(@PathVariable String interfaceId,@RequestParam(required=false)String tenantId){var e=versionPolicies.evaluateInterface(tenant(tenantId),interfaceId);return Map.of("policyId",e.policyId()==null?"":e.policyId(),"protocolVersion",e.protocolVersion(),"decision",e.decision(),"allowed",e.allowed());}
    @GetMapping("/{peerId}/error-mappings") public List<Map<String,Object>> errorMappings(@PathVariable String peerId,@RequestParam(required=false)String tenantId){return errorMappings.overrides(tenant(tenantId),peerId);}
    @GetMapping("/{peerId}/error-mappings/{overrideId}") public Map<String,Object> errorMapping(@PathVariable String peerId,@PathVariable String overrideId,@RequestParam(required=false)String tenantId){return errorMappings.override(tenant(tenantId),peerId,overrideId);}
    @PutMapping("/{peerId}/error-mappings/{overrideId}") public Map<String,Object> upsertErrorMapping(@PathVariable String peerId,@PathVariable String overrideId,@RequestParam(required=false)String tenantId,@RequestBody Map<String,Object> body){return errorMappings.upsertDraft(tenant(tenantId),peerId,overrideId,str(body,"interfaceId"),str(body,"operationScope"),str(body,"remoteErrorCode"),integer(body,"httpStatus"),str(body,"canonicalErrorClass"),str(body,"canonicalErrorCode"),str(body,"reason"));}
    @PostMapping("/{peerId}/error-mappings/{overrideId}/activate") public Map<String,Object> activateErrorMapping(@PathVariable String peerId,@PathVariable String overrideId,@RequestParam(required=false)String tenantId){return errorMappings.activate(tenant(tenantId),peerId,overrideId);}
    @PostMapping("/{peerId}/error-mappings/{overrideId}/retire") public Map<String,Object> retireErrorMapping(@PathVariable String peerId,@PathVariable String overrideId,@RequestParam(required=false)String tenantId){return errorMappings.retire(tenant(tenantId),peerId,overrideId);}
    @GetMapping("/{peerId}/error-mappings/explain") public Map<String,Object> explainErrorMapping(@PathVariable String peerId,@RequestParam(required=false)String tenantId,@RequestParam(required=false)String interfaceId,@RequestParam(defaultValue="ANY")String operation,@RequestParam(required=false)Integer httpStatus,@RequestParam(required=false)String remoteErrorCode){return errorMappings.explain(tenant(tenantId),peerId,interfaceId,operation,httpStatus,remoteErrorCode);}
    @PutMapping("/provider-links/{providerId}") public Map<String,Object> link(@PathVariable String providerId,@RequestParam(required=false)String tenantId,@RequestBody Map<String,Object> body){return service.linkProvider(tenant(tenantId),providerId,str(body,"peerId"),str(body,"interfaceId"));}
    private String tenant(String requested){var g=scoped.getIfAvailable();if(g==null){if(requested==null||requested.isBlank())throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,"tenantId is required");return requested.trim();}String active=g.activeTenantId();if(requested!=null&&!requested.isBlank()&&!active.equals(requested.trim()))throw new StandardApiException(StandardApiErrorCode.FORBIDDEN,"Tenant query parameters cannot switch workspace authority.");return active;}
    private static String str(Map<String,Object> m,String k){Object v=m==null?null:m.get(k);return v==null?null:String.valueOf(v);}
    @SuppressWarnings("unchecked") private static Map<String,Object> map(Map<String,Object> m,String k){Object v=m==null?null:m.get(k);return v instanceof Map<?,?> ? (Map<String,Object>)v : Map.of();}
    @SuppressWarnings("unchecked") private static List<Map<String,Object>> listOfMaps(Map<String,Object> m,String k){Object v=m==null?null:m.get(k);if(!(v instanceof List<?> list))return List.of();java.util.ArrayList<Map<String,Object>> out=new java.util.ArrayList<>();for(Object item:list)if(item instanceof Map<?,?>)out.add((Map<String,Object>)item);return List.copyOf(out);}
    private static List<String> listOfStrings(Map<String,Object> m,String k){Object v=m==null?null:m.get(k);if(!(v instanceof List<?> list))return List.of();java.util.ArrayList<String> out=new java.util.ArrayList<>();for(Object item:list)if(item!=null&&!String.valueOf(item).isBlank())out.add(String.valueOf(item));return List.copyOf(out);}
    private static Integer integer(Map<String,Object> m,String k){Object v=m==null?null:m.get(k);if(v==null)return null;if(v instanceof Number n)return n.intValue();return Integer.valueOf(String.valueOf(v));}
    private static Boolean bool(Map<String,Object> m,String k){Object v=m==null?null:m.get(k);if(v==null)return null;if(v instanceof Boolean b)return b;return Boolean.valueOf(String.valueOf(v));}
    private static java.time.OffsetDateTime time(Map<String,Object> m,String k){String v=str(m,k);return v==null||v.isBlank()?null:java.time.OffsetDateTime.parse(v);}
}
