package com.opensocket.aievent.core.api;

import com.opensocket.aievent.core.capability.*;import com.opensocket.aievent.core.resourceaccess.runtime.ScopedBusinessResourceAccessCoordinator;import java.util.List;import org.springframework.beans.factory.ObjectProvider;import org.springframework.web.bind.annotation.*;

/** Phase 9 Artifact aggregation / canonical Case administration API. No external issue materialization occurs here. */
@RestController
@RequestMapping("/admin/case-convergence")
public class CaseConvergenceController {
    private final CaseConvergenceService service;private final ObjectProvider<ScopedBusinessResourceAccessCoordinator> scopedAccess;
    public CaseConvergenceController(CaseConvergenceService service,ObjectProvider<ScopedBusinessResourceAccessCoordinator> scopedAccess){this.service=service;this.scopedAccess=scopedAccess;}
    @GetMapping("/aggregation-definitions") public List<AggregationDefinition> definitions(@RequestParam(required=false)String tenantId,@RequestParam(required=false)String status,@RequestParam(defaultValue="100")int limit){return service.definitions(effectiveTenant(tenantId),status,limit);}
    @PutMapping("/aggregation-definitions/{aggregationId}") public AggregationDefinition upsert(@PathVariable String aggregationId,@RequestParam(required=false)String tenantId,@RequestHeader(name="X-Change-Reason",required=false)String reason,@RequestBody(required=false)AggregationDefinition request){try{return service.upsertDefinition(effectiveTenant(tenantId),aggregationId,request,reason);}catch(IllegalArgumentException ex){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,ex.getMessage());}}
    @GetMapping("/aggregation-definitions/{aggregationId}/versions") public List<AggregationDefinitionVersion> versions(@PathVariable String aggregationId,@RequestParam(required=false)String tenantId){return service.definitionVersions(effectiveTenant(tenantId),aggregationId);}
    @PostMapping("/aggregation/prepare-preview") public AggregationPreparationDecision prepare(@RequestParam(required=false)String tenantId,@RequestBody(required=false)AggregationPreparationRequest request){try{return service.prepare(effectiveTenant(tenantId),request);}catch(IllegalArgumentException ex){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,ex.getMessage());}}
    @GetMapping("/aggregation/decisions") public List<AggregationPreparationDecision> decisions(@RequestParam(required=false)String tenantId,@RequestParam(required=false)String runId,@RequestParam(defaultValue="100")int limit){return service.preparationDecisions(effectiveTenant(tenantId),runId,limit);}
    @PostMapping("/cases") public EnterpriseCaseRecord converge(@RequestParam(required=false)String tenantId,@RequestBody(required=false)CaseConvergenceRequest request){try{return service.convergeCase(effectiveTenant(tenantId),request);}catch(IllegalArgumentException ex){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,ex.getMessage());}}
    @GetMapping("/cases") public List<EnterpriseCaseRecord> cases(@RequestParam(required=false)String tenantId,@RequestParam(required=false)String status,@RequestParam(required=false)String afterCaseId,@RequestParam(defaultValue="100")int limit){return service.cases(effectiveTenant(tenantId),status,afterCaseId,limit);}
    @GetMapping("/cases/{caseId}") public EnterpriseCaseRecord get(@PathVariable String caseId,@RequestParam(required=false)String tenantId){try{return service.caseById(effectiveTenant(tenantId),caseId);}catch(IllegalArgumentException ex){throw new StandardApiException(StandardApiErrorCode.NOT_FOUND,ex.getMessage());}}
    @PostMapping("/cases/{caseId}/review") public EnterpriseCaseRecord review(@PathVariable String caseId,@RequestParam(required=false)String tenantId,@RequestBody(required=false)CaseReviewRequest request){try{return service.reviewCase(effectiveTenant(tenantId),caseId,request);}catch(IllegalArgumentException ex){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,ex.getMessage());}}
    @GetMapping("/cases/{caseId}/artifacts") public List<CaseArtifactLink> artifacts(@PathVariable String caseId,@RequestParam(required=false)String tenantId){return service.caseArtifacts(effectiveTenant(tenantId),caseId);}
    @PostMapping("/cases/{caseId}/issue-projections") public CaseIssueProjection projection(@PathVariable String caseId,@RequestParam(required=false)String tenantId,@RequestBody(required=false)CaseIssueProjectionRequest request){try{return service.recordProjectionIntent(effectiveTenant(tenantId),caseId,request);}catch(IllegalArgumentException ex){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,ex.getMessage());}}
    @GetMapping("/cases/{caseId}/issue-projections") public List<CaseIssueProjection> projections(@PathVariable String caseId,@RequestParam(required=false)String tenantId){return service.projections(effectiveTenant(tenantId),caseId);}
    @GetMapping("/cases/{caseId}/events") public List<CaseEvent> events(@PathVariable String caseId,@RequestParam(required=false)String tenantId,@RequestParam(defaultValue="200")int limit){return service.events(effectiveTenant(tenantId),caseId,limit);}
    private String effectiveTenant(String requested){var guard=scopedAccess.getIfAvailable();if(guard==null){if(requested==null||requested.isBlank())throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,"tenantId is required");return requested.trim();}String active=guard.activeTenantId();if(requested!=null&&!requested.isBlank()&&!active.equals(requested.trim()))throw new StandardApiException(StandardApiErrorCode.FORBIDDEN,"Tenant query parameters cannot switch workspace authority. Use the active authenticated Tenant.");return active;}
}
