package com.opensocket.aievent.core.api;

import com.opensocket.aievent.core.capability.*;
import com.opensocket.aievent.core.resourceaccess.runtime.ScopedBusinessResourceAccessCoordinator;
import java.util.List;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.web.bind.annotation.*;

/** Phase 8 governed Plan execution administration API. Runtime mode requires runtime WHO MAY/WHO SHOULD/HOW evidence. */
@RestController
@RequestMapping("/admin/plan-executions")
public class GovernedPlanExecutionController {
    private final GovernedPlanExecutionService service;private final ObjectProvider<ScopedBusinessResourceAccessCoordinator> scopedAccess;
    public GovernedPlanExecutionController(GovernedPlanExecutionService service,ObjectProvider<ScopedBusinessResourceAccessCoordinator> scopedAccess){this.service=service;this.scopedAccess=scopedAccess;}
    @GetMapping("/policies") public List<PlanExecutionPolicy> policies(@RequestParam(required=false)String tenantId,@RequestParam(required=false)String status,@RequestParam(defaultValue="100")int limit){return service.listPolicies(effectiveTenant(tenantId),status,limit);}
    @PutMapping("/policies/{policyId}") public PlanExecutionPolicy upsertPolicy(@PathVariable String policyId,@RequestParam(required=false)String tenantId,@RequestHeader(name="X-Change-Reason",required=false)String reason,@RequestBody(required=false)PlanExecutionPolicy request){try{return service.upsertPolicy(effectiveTenant(tenantId),policyId,request,reason);}catch(IllegalArgumentException ex){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,ex.getMessage());}}
    @GetMapping("/policies/{policyId}/versions") public List<PlanExecutionPolicyVersion> versions(@PathVariable String policyId,@RequestParam(required=false)String tenantId){return service.policyVersions(effectiveTenant(tenantId),policyId);}
    @PostMapping("/runs") public PlanExecutionRun start(@RequestParam(required=false)String tenantId,@RequestBody(required=false)PlanExecutionStartRequest request){try{return service.startRun(effectiveTenant(tenantId),request);}catch(IllegalArgumentException ex){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,ex.getMessage());}}
    @GetMapping("/runs") public List<PlanExecutionRun> runs(@RequestParam(required=false)String tenantId,@RequestParam(required=false)String status,@RequestParam(required=false)String afterRunId,@RequestParam(defaultValue="100")int limit){return service.listRuns(effectiveTenant(tenantId),status,afterRunId,limit);}
    @GetMapping("/runs/{runId}") public PlanExecutionRun run(@PathVariable String runId,@RequestParam(required=false)String tenantId){return service.findRun(effectiveTenant(tenantId),runId).orElseThrow(()->new StandardApiException(StandardApiErrorCode.NOT_FOUND,"Plan execution run not found"));}
    @GetMapping("/runs/{runId}/steps") public List<GovernedPlanExecutionStep> steps(@PathVariable String runId,@RequestParam(required=false)String tenantId){return service.steps(effectiveTenant(tenantId),runId);}
    @PostMapping("/runs/{runId}/steps/{stepId}/authority") public GovernedPlanExecutionStep authority(@PathVariable String runId,@PathVariable String stepId,@RequestParam(required=false)String tenantId,@RequestBody(required=false)PlanStepAuthorityRequest request){try{return service.attachAuthority(effectiveTenant(tenantId),runId,stepId,request);}catch(IllegalArgumentException ex){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,ex.getMessage());}}
    @PostMapping("/runs/{runId}/steps/{stepId}/automate-authority") public RuntimeStepAuthorityAutomationResult automateAuthority(@PathVariable String runId,@PathVariable String stepId,@RequestParam(required=false)String tenantId){try{return service.automateAuthority(effectiveTenant(tenantId),runId,stepId);}catch(IllegalArgumentException ex){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,ex.getMessage());}}
    @PostMapping("/runs/{runId}/steps/{stepId}/submit") public PlanExecutionAttempt submit(@PathVariable String runId,@PathVariable String stepId,@RequestParam(required=false)String tenantId,@RequestBody(required=false)PlanStepSubmitRequest request){try{return service.submitStep(effectiveTenant(tenantId),runId,stepId,request);}catch(IllegalArgumentException ex){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,ex.getMessage());}}
    @PostMapping("/runs/{runId}/steps/{stepId}/complete") public GovernedPlanExecutionStep complete(@PathVariable String runId,@PathVariable String stepId,@RequestParam(required=false)String tenantId,@RequestBody(required=false)PlanStepCompletionRequest request){try{return service.completeStep(effectiveTenant(tenantId),runId,stepId,request);}catch(IllegalArgumentException ex){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,ex.getMessage());}}
    @PostMapping("/runs/{runId}/steps/{stepId}/retry") public GovernedPlanExecutionStep retry(@PathVariable String runId,@PathVariable String stepId,@RequestParam(required=false)String tenantId,@RequestBody(required=false)PlanStepRetryRequest request){try{return service.retryStep(effectiveTenant(tenantId),runId,stepId,request);}catch(IllegalArgumentException ex){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,ex.getMessage());}}
    @PostMapping("/runs/{runId}/cancel") public PlanExecutionRun cancel(@PathVariable String runId,@RequestParam(required=false)String tenantId,@RequestBody(required=false)PlanExecutionCancelRequest request){try{return service.cancelRun(effectiveTenant(tenantId),runId,request);}catch(IllegalArgumentException ex){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,ex.getMessage());}}
    @PostMapping("/sweep-timeouts") public int sweep(@RequestParam(required=false)String tenantId){return service.sweepTimeouts(effectiveTenant(tenantId));}
    @GetMapping("/runs/{runId}/attempts") public List<PlanExecutionAttempt> attempts(@PathVariable String runId,@RequestParam(required=false)String tenantId,@RequestParam(required=false)String stepId,@RequestParam(defaultValue="100")int limit){return service.attempts(effectiveTenant(tenantId),runId,stepId,limit);}
    @GetMapping("/runs/{runId}/artifacts") public List<PlanExecutionArtifact> artifacts(@PathVariable String runId,@RequestParam(required=false)String tenantId,@RequestParam(required=false)String stepId,@RequestParam(defaultValue="100")int limit){return service.artifacts(effectiveTenant(tenantId),runId,stepId,limit);}
    @GetMapping("/runs/{runId}/events") public List<PlanExecutionEvent> events(@PathVariable String runId,@RequestParam(required=false)String tenantId,@RequestParam(defaultValue="200")int limit){return service.events(effectiveTenant(tenantId),runId,limit);}
    private String effectiveTenant(String requested){var guard=scopedAccess.getIfAvailable();if(guard==null){if(requested==null||requested.isBlank())throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,"tenantId is required");return requested.trim();}String active=guard.activeTenantId();if(requested!=null&&!requested.isBlank()&&!active.equals(requested.trim()))throw new StandardApiException(StandardApiErrorCode.FORBIDDEN,"Tenant query parameters cannot switch workspace authority. Use the active authenticated Tenant.");return active;}
}
