package com.opensocket.aievent.core.api;

import com.opensocket.aievent.core.http.context.*;
import com.opensocket.aievent.core.integration.identity.IntegrationOperation;
import com.opensocket.aievent.core.integration.issue.*;
import com.opensocket.aievent.core.issue.*;
import com.opensocket.aievent.core.resourceaccess.contract.*;
import com.opensocket.aievent.core.resourceaccess.runtime.IntegrationResourceAccessCoordinator;
import com.opensocket.aievent.core.resourceaccess.runtime.ScopedBusinessResourceAccessCoordinator;
import com.opensocket.aievent.core.resourceaccess.runtime.ScopedIssueQueryService;
import java.time.OffsetDateTime; import java.util.*;
import org.slf4j.*; import org.springframework.beans.factory.annotation.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;

/** Issue projection API with P4RA-F link/conflict/dead-letter enforcement and redacted operational views. */
@RestController @RequestMapping
public class IssueProjectionController {
 private static final Logger log=LoggerFactory.getLogger(IssueProjectionController.class);
 private final IssueProjectionService service; private final IssueSyncRepository sync; private final TaskIssueLinkRepository links;
 @Autowired(required=false) private IntegrationResourceAccessCoordinator resourceAccess;
 @Autowired(required=false) private ScopedBusinessResourceAccessCoordinator scopedBusinessAccess;
 @Autowired(required=false) private ScopedIssueQueryService scopedIssueQueries;
 @Value("${resource-access.integration-enabled:false}") private boolean integrationEnabled;
 @Value("${resource-access.external-write-enabled:false}") private boolean externalWriteEnabled;
 @Value("${resource-access.enforcement-mode:OFF}") private ResourceAccessEnforcementMode mode=ResourceAccessEnforcementMode.OFF;
 public IssueProjectionController(IssueProjectionService service,IssueSyncRepository sync,TaskIssueLinkRepository links){this.service=service;this.sync=sync;this.links=links;}

 @GetMapping("/api/issues") public List<IssueView> issues(@RequestParam(defaultValue="100")int limit){List<TaskIssueLink> scoped;if(scopedBusinessAccess==null)scoped=filter(run(()->links.recent(tenant(),limit)),TaskIssueLink::getLinkId,ResourceType.TASK_ISSUE_LINK,"integration.issue.link.read",VisibilityLevel.STANDARD,"RS5_ISSUE_LIST_COMPAT");else scoped=requireScopedIssueQueries().recent(scopedBusinessAccess.plan("integration.issue.link.read",ResourceType.TASK_ISSUE_LINK,VisibilityLevel.STANDARD,"RS5_ISSUE_LIST"),limit);return scoped.stream().map(IssueView::from).toList();}
 @GetMapping("/api/issues/{linkId}") public IssueView issue(@PathVariable String linkId){authorizeCanonicalIssue(linkId,"integration.issue.link.read",ResourceAction.ActionKind.READ,false,VisibilityLevel.STANDARD,"RS5_ISSUE_DETAIL");return IssueView.from(link(linkId));}
 @GetMapping("/api/tasks/{taskId}/issues") public List<TaskIssueLink> issues(@PathVariable String taskId,@RequestParam(defaultValue="100")int limit){if(scopedBusinessAccess==null){List<TaskIssueLink> values=run(()->service.taskIssues(tenant(),taskId));return filter(values,TaskIssueLink::getLinkId,ResourceType.TASK_ISSUE_LINK,"integration.issue.link.read",VisibilityLevel.STANDARD,"TASK_ISSUE_LINK_LIST");}return requireScopedIssueQueries().byTask(scopedBusinessAccess.plan("integration.issue.link.read",ResourceType.TASK_ISSUE_LINK,VisibilityLevel.STANDARD,"RS5_TASK_ISSUE_LIST"),taskId,limit);}
 @GetMapping("/api/task-issues/{linkId}/relationships") public List<IssueRelationship> relationships(@PathVariable String linkId,@RequestParam(defaultValue="200")int limit){authorizeCanonicalIssue(linkId,"integration.issue.link.read",ResourceAction.ActionKind.READ,false,VisibilityLevel.STANDARD,"TASK_ISSUE_RELATIONSHIP_LIST");return run(()->service.relationships(tenant(),linkId,limit));}
 @PostMapping("/api/task-issues/{linkId}/relationships") public IssueRelationship relationship(@PathVariable String linkId,@RequestHeader("Idempotency-Key")String key,@RequestBody RelationshipRequest body){throw new ResponseStatusException(HttpStatus.GONE,"LEGACY_ISSUE_RELATION_AUTHORITY_RETIRED_USE_A2A: Provider-side Issue relationship projection is retired. Use A2A for cross-domain collaboration.");}
 @PostMapping("/api/integrations/webhooks/{connectionId}/{providerType}") public WebhookReceipt legacyWebhookDisabled(){throw new ResponseStatusException(HttpStatus.GONE,"Legacy Webhook ingress is disabled. Use /api/external/provider-webhooks/{endpointToken}.");}

 /** Worker APIs remain Service Identity enforcement scope for P4RA-G. */
 @PostMapping("/internal/integration-sync/outbox/claim") public List<IntegrationOutboxEntry> claim(@RequestBody ClaimRequest body){return run(()->service.claimDue(tenant(),body.workerId(),body.limit()));}
 @PostMapping("/internal/integration-sync/outbox/{outboxId}/start") public IntegrationOutboxEntry start(@PathVariable String outboxId,@RequestBody WorkerRequest body){return run(()->service.startAttempt(tenant(),outboxId,body.workerId()));}
 @PostMapping("/internal/integration-sync/outbox/{outboxId}/complete") public IntegrationOutboxEntry complete(@PathVariable String outboxId,@RequestBody ProviderResultRequest body){return run(()->service.complete(tenant(),outboxId,body.workerId(),body.result()));}
 @PostMapping("/internal/integration-sync/outbox/{outboxId}/fail") public IntegrationOutboxEntry fail(@PathVariable String outboxId,@RequestBody ProviderResultRequest body){return run(()->service.fail(tenant(),outboxId,body.workerId(),body.result()));}

 @GetMapping("/api/integrations/sync/dead-letters") public List<DeadLetterMetadataView> deadLetters(@RequestParam(required=false)IntegrationDeadLetterStatus status,@RequestParam(defaultValue="200")int limit){List<IntegrationDeadLetter> values=run(()->service.deadLetters(tenant(),status,limit));return filter(values,IntegrationDeadLetter::deadLetterId,ResourceType.ISSUE_DEAD_LETTER,"integration.issue.dead-letter.read",VisibilityLevel.METADATA,"ISSUE_DEAD_LETTER_LIST").stream().map(DeadLetterMetadataView::from).toList();}
 @PostMapping("/api/integrations/sync/dead-letters/{deadLetterId}/retry") public IntegrationOutboxEntry retry(@PathVariable String deadLetterId,@RequestHeader("Idempotency-Key")String key,@RequestBody(required=false)ReasonRequest body){String idem=required(key,"Idempotency-Key");IntegrationDeadLetter d=sync.findDeadLetter(tenant(),deadLetterId).orElseThrow(()->bad("Dead letter not found."));IntegrationOutboxEntry original=sync.findOutbox(tenant(),d.outboxId()).orElseThrow(()->bad("Outbox item not found."));if(original.operationType()==IntegrationOperationType.ISSUE_RELATION_CREATE||original.operationType()==IntegrationOperationType.ISSUE_RELAY_BACKLINK)throw new ResponseStatusException(HttpStatus.GONE,"LEGACY_ISSUE_RELAY_RETIRED_USE_A2A: Legacy relation/relay dead letters cannot be replayed.");externalWrite(ResourceType.ISSUE_DEAD_LETTER,deadLetterId,"integration.issue.dead-letter.retry",ResourceAction.ActionKind.EXECUTE,VisibilityLevel.SENSITIVE,"ISSUE_DEAD_LETTER_RETRY",original.projectMappingId(),operation(original.operationType()),idem);ReasonRequest b=body==null?new ReasonRequest(null,null):body;return run(()->service.retryDeadLetter(tenant(),deadLetterId,operator(),b.reason(),correlation(),idem));}
 @GetMapping("/api/integrations/sync/conflicts") public List<ConflictMetadataView> conflicts(@RequestParam(required=false)IntegrationConflictStatus status,@RequestParam(defaultValue="200")int limit){List<IntegrationConflict> values=run(()->service.conflicts(tenant(),status,limit));return filter(values,IntegrationConflict::conflictId,ResourceType.ISSUE_CONFLICT,"integration.issue.conflict.read",VisibilityLevel.SENSITIVE,"ISSUE_CONFLICT_LIST").stream().map(ConflictMetadataView::from).toList();}
 @PostMapping("/api/integrations/sync/conflicts/{conflictId}/resolve") public IntegrationConflict resolve(@PathVariable String conflictId,@RequestHeader("Idempotency-Key")String key,@RequestBody ReasonRequest body){throw new ResponseStatusException(HttpStatus.GONE,"LEGACY_ISSUE_CONFLICT_ARBITRATION_RETIRED: Integration conflicts are historical evidence only; Redmine owns external Issue state.");}
 @GetMapping("/api/integrations/sync/inbox") public List<InboxMetadataView> inbox(@RequestParam(defaultValue="200")int limit){List<IntegrationInboxEntry> values=run(()->service.inbox(tenant(),limit));return filter(values,IntegrationInboxEntry::connectionId,ResourceType.ISSUE_CONNECTION,"integration.issue.connection.read",VisibilityLevel.METADATA,"ISSUE_INBOX_LIST").stream().map(InboxMetadataView::from).toList();}
 @GetMapping("/api/integrations/sync/outbox/{outboxId}/attempts") public List<IntegrationSyncAttempt> attempts(@PathVariable String outboxId,@RequestParam(defaultValue="200")int limit){IntegrationOutboxEntry out=sync.findOutbox(tenant(),outboxId).orElseThrow(()->bad("Outbox item not found."));if(out.taskIssueLinkId()!=null)authorize(ResourceType.TASK_ISSUE_LINK,out.taskIssueLinkId(),"integration.issue.link.read",ResourceAction.ActionKind.READ,false,VisibilityLevel.SENSITIVE,"ISSUE_SYNC_ATTEMPT_LIST");return run(()->service.attempts(tenant(),outboxId,limit));}

 private ScopedIssueQueryService requireScopedIssueQueries(){if(scopedIssueQueries==null)throw new IllegalStateException("RS5 scoped Issue query service is unavailable");return scopedIssueQueries;}
 private void authorizeCanonicalIssue(String linkId,String permission,ResourceAction.ActionKind kind,boolean sideEffect,VisibilityLevel visibility,String purpose){if(scopedBusinessAccess!=null){scopedBusinessAccess.authorize(ResourceType.TASK_ISSUE_LINK,required(linkId,"linkId"),permission,kind,sideEffect,visibility,purpose);return;}authorize(ResourceType.TASK_ISSUE_LINK,linkId,permission,kind,sideEffect,visibility,purpose);}
 private void externalWrite(ResourceType type,String id,String permission,ResourceAction.ActionKind kind,VisibilityLevel visibility,String purpose,String mappingId,IntegrationOperation operation,String idempotency){if(!integrationEnabled||!externalWriteEnabled)return;if(resourceAccess==null)throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"Resource Access Integration guard is unavailable.");try{resourceAccess.authorizeExternalWrite(type,id,permission,kind,visibility,purpose,required(mappingId,"projectMappingId"),operation,idempotency,true,true);}catch(RuntimeException e){if(mode==ResourceAccessEnforcementMode.OFF||mode==ResourceAccessEnforcementMode.SHADOW||mode==ResourceAccessEnforcementMode.READ_ENFORCE){log.warn("external_write_shadow_resolution_failed purpose={} resource={} error={}",purpose,id,e.getMessage());return;}throw e;}}
 private void authorize(ResourceType type,String id,String permission,ResourceAction.ActionKind kind,boolean sideEffect,VisibilityLevel visibility,String purpose){if(!integrationEnabled)return;if(resourceAccess==null)throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"Resource Access Integration guard is unavailable.");resourceAccess.authorize(type,required(id,"resourceId"),permission,kind,sideEffect,visibility,purpose);}
 private <T>List<T> filter(List<T> values,java.util.function.Function<T,String> id,ResourceType type,String permission,VisibilityLevel visibility,String purpose){if(!integrationEnabled||mode==ResourceAccessEnforcementMode.OFF)return values;if(resourceAccess==null){if(mode==ResourceAccessEnforcementMode.SHADOW||mode==ResourceAccessEnforcementMode.WRITE_ENFORCE){log.warn("issue_resource_shadow_guard_unavailable purpose={}",purpose);return values;}throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"Resource Access Integration guard is unavailable.");}List<T> allowed=new ArrayList<>();for(T value:values){try{var d=resourceAccess.authorize(type,id.apply(value),permission,ResourceAction.ActionKind.READ,false,visibility,purpose);if(mode==ResourceAccessEnforcementMode.READ_ENFORCE||mode==ResourceAccessEnforcementMode.FULL_ENFORCE){if(d.effect()==DecisionEffect.ALLOW&&d.mode()==AuthorizationDecisionMode.FORMAL)allowed.add(value);}else allowed.add(value);}catch(RuntimeException e){if(mode==ResourceAccessEnforcementMode.SHADOW||mode==ResourceAccessEnforcementMode.WRITE_ENFORCE){log.warn("issue_resource_shadow_deny purpose={} resource={}",purpose,id.apply(value));allowed.add(value);}else throw e;}}return allowed;}
 private TaskIssueLink link(String id){return links.findByTenantAndLinkId(tenant(),id).orElseThrow(()->bad("Task-Issue Link not found."));}
 private static IntegrationOperation operation(IntegrationOperationType t){return switch(t){case ISSUE_CREATE,ISSUE_LINK_EXISTING->IntegrationOperation.CREATE;case ISSUE_COMMENT_APPEND->IntegrationOperation.COMMENT;case ISSUE_RELATION_CREATE,ISSUE_RELAY_BACKLINK->IntegrationOperation.RELATION;case ISSUE_STATUS_OBSERVE->IntegrationOperation.UPDATE;};}
 private String tenant(){return required(context().tenantId(),"tenantId");} private String operator(){return required(context().operatorId(),"operatorId");} private String correlation(){String c=context().correlationId();return c==null||c.isBlank()?UUID.randomUUID().toString():c;} private OpenDispatchRequestContext context(){return OpenDispatchRequestContextHolder.current().orElseThrow(()->bad("Request context is required."));}
 private String required(String v,String n){if(v==null||v.isBlank())throw bad(n+" is required.");return v.trim();} private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);} private <T>T run(Op<T> op){try{return op.get();}catch(ResponseStatusException e){throw e;}catch(IllegalArgumentException e){throw bad(e.getMessage());}catch(IllegalStateException e){throw new ResponseStatusException(HttpStatus.CONFLICT,e.getMessage());}} @FunctionalInterface private interface Op<T>{T get();}
 public record IssueView(String linkId,String taskId,String providerType,String externalProjectId,String externalIssueId,String externalIssueKey,String externalIssueUrl,String issueStatus,String syncStatus,String ownerDepartmentId,String ownerGroupId,String requesterDepartmentId,String requesterGroupId,String executorDepartmentId,String executorGroupId,String scopeStatus,String scopeSourceType,String scopeSourceId,Long scopeSourceVersion,OffsetDateTime scopeInheritedAt,OffsetDateTime createdAt,OffsetDateTime updatedAt){static IssueView from(TaskIssueLink v){return new IssueView(v.getLinkId(),v.getTaskId(),v.getProviderType(),v.getExternalProjectId(),v.getExternalIssueId(),v.getExternalIssueKey(),v.getExternalIssueUrl(),v.getIssueStatus(),v.getSyncStatus(),v.getOwnerDepartmentId(),v.getOwnerGroupId(),v.getRequesterDepartmentId(),v.getRequesterGroupId(),v.getExecutorDepartmentId(),v.getExecutorGroupId(),v.getScopeStatus(),v.getScopeSourceType(),v.getScopeSourceId(),v.getScopeSourceVersion(),v.getScopeInheritedAt(),v.getCreatedAt(),v.getUpdatedAt());}}
 public record DeadLetterMetadataView(String tenantId,String deadLetterId,String outboxId,String taskId,String taskIssueLinkId,IntegrationOperationType operationType,String payloadHash,String failureCode,int attemptCount,IntegrationDeadLetterStatus status,OffsetDateTime openedAt,OffsetDateTime retriedAt,OffsetDateTime resolvedAt,String correlationId){static DeadLetterMetadataView from(IntegrationDeadLetter v){return new DeadLetterMetadataView(v.tenantId(),v.deadLetterId(),v.outboxId(),v.taskId(),v.taskIssueLinkId(),v.operationType(),v.payloadHash(),v.failureCode(),v.attemptCount(),v.status(),v.openedAt(),v.retriedAt(),v.resolvedAt(),v.correlationId());}}
 public record ConflictMetadataView(String tenantId,String conflictId,String taskId,String taskIssueLinkId,String conflictType,String taskStatus,String externalIssueStatus,IntegrationConflictStatus status,OffsetDateTime detectedAt,OffsetDateTime resolvedAt,String correlationId){static ConflictMetadataView from(IntegrationConflict v){return new ConflictMetadataView(v.tenantId(),v.conflictId(),v.taskId(),v.taskIssueLinkId(),v.conflictType(),v.taskStatus(),v.externalIssueStatus(),v.status(),v.detectedAt(),v.resolvedAt(),v.correlationId());}}
 public record InboxMetadataView(String tenantId,String inboxId,String connectionId,String providerEventId,String eventType,String externalProjectId,String externalIssueId,String payloadHash,IntegrationInboxStatus status,OffsetDateTime receivedAt,String correlationId){static InboxMetadataView from(IntegrationInboxEntry v){return new InboxMetadataView(v.tenantId(),v.inboxId(),v.connectionId(),v.providerEventId(),v.eventType(),v.externalProjectId(),v.externalIssueId(),v.payloadHash(),v.status(),v.receivedAt(),v.correlationId());}}
 public record RelationshipRequest(String targetLinkId,IssueRelationshipType relationshipType){} public record WebhookRequest(String eventType,String externalProjectId,String externalIssueId,String externalIssueStatus,String payloadJson){} public record ClaimRequest(String workerId,int limit){} public record WorkerRequest(String workerId){} public record ProviderResultRequest(String workerId,ProviderSyncResult result){} public record ReasonRequest(String action,String reason){}
}
