package com.opensocket.aievent.core.api;

import com.opensocket.aievent.core.capability.*;
import com.opensocket.aievent.core.resourceaccess.runtime.ScopedBusinessResourceAccessCoordinator;
import java.util.List;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.web.bind.annotation.*;

/** Phase 10 Outcome learning / governed Fast Path administration. No runtime dispatch occurs here. */
@RestController
@RequestMapping("/admin/learning-fast-path")
public class LearningFastPathController {
    private final LearningFastPathService service; private final ObjectProvider<ScopedBusinessResourceAccessCoordinator> scopedAccess;
    public LearningFastPathController(LearningFastPathService service,ObjectProvider<ScopedBusinessResourceAccessCoordinator> scopedAccess){this.service=service;this.scopedAccess=scopedAccess;}
    @GetMapping("/policies") public List<LearningPolicy> policies(@RequestParam(required=false)String tenantId,@RequestParam(required=false)String status,@RequestParam(defaultValue="100")int limit){return service.policies(effectiveTenant(tenantId),status,limit);}
    @PutMapping("/policies/{policyId}") public LearningPolicy upsertPolicy(@PathVariable String policyId,@RequestParam(required=false)String tenantId,@RequestHeader(name="X-Change-Reason",required=false)String reason,@RequestBody(required=false)LearningPolicy body){try{return service.upsertPolicy(effectiveTenant(tenantId),policyId,body,reason);}catch(IllegalArgumentException e){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,e.getMessage());}}
    @GetMapping("/policies/{policyId}/versions") public List<LearningPolicyVersion> policyVersions(@PathVariable String policyId,@RequestParam(required=false)String tenantId){return service.policyVersions(effectiveTenant(tenantId),policyId);}
    @PostMapping("/outcomes/from-case/{caseId}") public ExecutionOutcomeEvidence recordOutcome(@PathVariable String caseId,@RequestParam(required=false)String tenantId){try{return service.recordOutcome(effectiveTenant(tenantId),caseId);}catch(IllegalArgumentException e){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,e.getMessage());}}
    @GetMapping("/outcomes") public List<ExecutionOutcomeEvidence> outcomes(@RequestParam(required=false)String tenantId,@RequestParam(required=false)String problemSignature,@RequestParam(defaultValue="100")int limit){return service.outcomes(effectiveTenant(tenantId),problemSignature,limit);}
    @GetMapping("/candidates") public List<RoutingPatternCandidate> candidates(@RequestParam(required=false)String tenantId,@RequestParam(required=false)String status,@RequestParam(defaultValue="100")int limit){return service.candidates(effectiveTenant(tenantId),status,limit);}
    @PostMapping("/candidates/{candidateId}/promote-shadow") public PatternPromotionDecision promoteShadow(@PathVariable String candidateId,@RequestParam(required=false)String tenantId,@RequestBody(required=false)PatternPromotionRequest body){try{return service.promoteCandidateToShadow(effectiveTenant(tenantId),candidateId,body==null?null:body.reason());}catch(IllegalArgumentException e){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,e.getMessage());}}
    @GetMapping("/patterns") public List<RoutingPattern> patterns(@RequestParam(required=false)String tenantId,@RequestParam(required=false)String status,@RequestParam(defaultValue="100")int limit){return service.patterns(effectiveTenant(tenantId),status,limit);}
    @GetMapping("/patterns/{patternId}/versions") public List<RoutingPatternVersion> patternVersions(@PathVariable String patternId,@RequestParam(required=false)String tenantId){return service.patternVersions(effectiveTenant(tenantId),patternId);}
    @PostMapping("/patterns/{patternId}/quality/refresh") public PatternQualitySnapshot refreshQuality(@PathVariable String patternId,@RequestParam(required=false)String tenantId){try{return service.refreshQuality(effectiveTenant(tenantId),patternId);}catch(IllegalArgumentException e){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,e.getMessage());}}
    @GetMapping("/patterns/{patternId}/quality") public List<PatternQualitySnapshot> quality(@PathVariable String patternId,@RequestParam(required=false)String tenantId,@RequestParam(defaultValue="100")int limit){return service.qualitySnapshots(effectiveTenant(tenantId),patternId,limit);}
    @PostMapping("/patterns/{patternId}/transition") public PatternPromotionDecision transition(@PathVariable String patternId,@RequestParam(required=false)String tenantId,@RequestBody(required=false)PatternPromotionRequest body){try{return service.transitionPattern(effectiveTenant(tenantId),patternId,body);}catch(IllegalArgumentException e){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,e.getMessage());}}
    @PostMapping("/patterns/{patternId}/drift/evaluate") public DriftObservation drift(@PathVariable String patternId,@RequestParam(required=false)String tenantId){try{return service.evaluateDrift(effectiveTenant(tenantId),patternId);}catch(IllegalArgumentException e){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,e.getMessage());}}
    @GetMapping("/patterns/{patternId}/drift") public List<DriftObservation> drifts(@PathVariable String patternId,@RequestParam(required=false)String tenantId,@RequestParam(defaultValue="100")int limit){return service.driftObservations(effectiveTenant(tenantId),patternId,limit);}
    @PostMapping("/fast-path/resolve-preview") public FastPathResolutionDecision fastPath(@RequestParam(required=false)String tenantId,@RequestBody(required=false)FastPathResolutionRequest body){try{return service.resolveFastPath(effectiveTenant(tenantId),body);}catch(IllegalArgumentException e){throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,e.getMessage());}}
    @GetMapping("/promotion-decisions") public List<PatternPromotionDecision> promotions(@RequestParam(required=false)String tenantId,@RequestParam(defaultValue="100")int limit){return service.promotionDecisions(effectiveTenant(tenantId),limit);}
    private String effectiveTenant(String requested){var guard=scopedAccess.getIfAvailable();if(guard==null){if(requested==null||requested.isBlank())throw new StandardApiException(StandardApiErrorCode.BAD_REQUEST,"tenantId is required");return requested.trim();}String active=guard.activeTenantId();if(requested!=null&&!requested.isBlank()&&!active.equals(requested.trim()))throw new StandardApiException(StandardApiErrorCode.FORBIDDEN,"Tenant query parameters cannot switch workspace authority. Use the active authenticated Tenant.");return active;}
}
