package com.opensocket.aievent.core.api;
import java.util.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import com.opensocket.aievent.core.http.context.*;import com.opensocket.aievent.core.issuetracking.application.recovery.*;import com.opensocket.aievent.core.issuetracking.recovery.*;
/** Phase 3I operator API for ordered lanes, readback recovery, reconciliation and circuit governance. */
@RestController @RequestMapping("/api/integrations/projection-recovery")
public class ProjectionRecoveryGovernanceController {
 private final OrderedProjectionLaneService lanes;private final OrderedProjectionWorkerService worker;private final ProjectionRecoveryService recovery;private final ProjectionReconciliationService reconciliation;private final ProviderHealthService health;private final ProjectionRecoveryRepository repository;
 public ProjectionRecoveryGovernanceController(OrderedProjectionLaneService lanes,OrderedProjectionWorkerService worker,ProjectionRecoveryService recovery,ProjectionReconciliationService reconciliation,ProviderHealthService health,ProjectionRecoveryRepository repository){this.lanes=lanes;this.worker=worker;this.recovery=recovery;this.reconciliation=reconciliation;this.health=health;this.repository=repository;}
 @GetMapping("/lanes") public List<OrderedProjectionLane> lanes(@RequestParam(required=false)ProjectionLaneStatus status,@RequestParam(defaultValue="200")int limit){return run(()->lanes.list(tenant(),status,limit));}
 @GetMapping("/lanes/{laneId}/work") public List<OrderedProjectionWork> work(@PathVariable String laneId,@RequestParam(required=false)ProjectionWorkStatus status,@RequestParam(defaultValue="500")int limit){return run(()->lanes.work(tenant(),laneId,status,limit));}
 @GetMapping("/lanes/{laneId}/events") public List<ProjectionRecoveryEvent> laneEvents(@PathVariable String laneId,@RequestParam(defaultValue="200")int limit){return run(()->repository.listEvents(tenant(),"PROJECTION_LANE",laneId,lim(limit)));}
 @PostMapping("/lanes/{laneId}/generations") public OrderedProjectionLane nextGeneration(@PathVariable String laneId,@RequestHeader("If-Match")String ifMatch,@RequestBody GovernedReason body){return run(()->lanes.nextGeneration(tenant(),laneId,version(ifMatch),actor(),required(body.reason(),"reason"),correlation()));}
 @PostMapping("/work") public OrderedProjectionWork enqueue(@RequestHeader("Idempotency-Key")String key,@RequestBody EnqueueRequest b){return run(()->lanes.enqueue(tenant(),required(b.aggregateKey(),"aggregateKey"),Objects.requireNonNull(b.laneType(),"laneType is required"),required(b.connectionId(),"connectionId"),text(b.projectMappingId()),Objects.requireNonNull(b.operationType(),"operationType is required"),required(b.aggregateId(),"aggregateId"),text(b.outboxId()),text(b.projectionId()),required(b.payloadHash(),"payloadHash"),text(b.coalesceKey()),text(b.dependsOnWorkId()),b.maxQueueDepth(),b.maxAttempts(),actor(),correlation()));}
 @PostMapping("/work/recover-expired-claims") public Map<String,Integer> recoverExpiredClaims(@RequestBody RecoverExpiredClaimsRequest body){return run(()->Map.of("recovered",worker.recoverExpiredClaims(tenant(),body.limit(),actor(),required(body.reason(),"reason"),correlation())));}
 @PostMapping("/work/{workId}/recover") public ProjectionRecoveryCase recover(@PathVariable String workId,@RequestBody GovernedReason body){return run(()->recovery.recover(tenant(),workId,actor(),required(body.reason(),"reason"),correlation()));}
 @GetMapping("/cases") public List<ProjectionRecoveryCase> cases(@RequestParam(required=false)ProjectionRecoveryCaseStatus status,@RequestParam(defaultValue="200")int limit){return run(()->recovery.list(tenant(),status,limit));}
 @GetMapping("/cases/{caseId}/events") public List<ProjectionRecoveryEvent> caseEvents(@PathVariable String caseId,@RequestParam(defaultValue="200")int limit){return run(()->repository.listEvents(tenant(),"RECOVERY_CASE",caseId,lim(limit)));}
 @PostMapping("/cases/{caseId}/repair") public ProjectionRecoveryCase repair(@PathVariable String caseId,@RequestHeader("If-Match")String ifMatch,@RequestHeader("Idempotency-Key")String key,@RequestBody RepairRequest body){return run(()->recovery.repair(tenant(),caseId,version(ifMatch),body.dryRun(),required(key,"Idempotency-Key"),actor(),required(body.reason(),"reason"),correlation()));}
 @GetMapping("/reconciliation-runs") public List<ProjectionReconciliationRun> runs(@RequestParam(required=false)ReconciliationRunStatus status,@RequestParam(defaultValue="200")int limit){return run(()->reconciliation.list(tenant(),status,limit));}
 @PostMapping("/reconciliation-runs") public ProjectionReconciliationRun requestRun(@RequestHeader("Idempotency-Key")String key,@RequestBody ReconciliationRequest b){return run(()->reconciliation.request(tenant(),required(b.connectionId(),"connectionId"),text(b.projectMappingId()),required(b.scopeType(),"scopeType"),text(b.scopeId()),b.dryRun(),actor(),correlation()));}
 @PostMapping("/reconciliation-runs/{runId}/drifts") public ProjectionRecoveryCase recordDrift(@PathVariable String runId,@RequestHeader("If-Match")String ifMatch,@RequestBody ReconciliationDriftRequest b){return run(()->reconciliation.recordDrift(tenant(),runId,version(ifMatch),Objects.requireNonNull(b.caseType(),"caseType is required"),text(b.laneId()),text(b.workId()),text(b.projectionId()),text(b.externalIssueId()),text(b.expectedHash()),text(b.observedHash()),actor(),required(b.reason(),"reason"),correlation()));}
 @PostMapping("/reconciliation-runs/{runId}/complete") public ProjectionReconciliationRun completeRun(@PathVariable String runId,@RequestHeader("If-Match")String ifMatch,@RequestBody ReconciliationCompleteRequest b){return run(()->reconciliation.complete(tenant(),runId,version(ifMatch),b.scannedCount(),b.repairedCount(),b.failedCount(),actor(),required(b.reason(),"reason"),correlation()));}
 @GetMapping("/provider-health") public List<ProviderHealthState> health(@RequestParam(required=false)ProviderHealthStatus status,@RequestParam(defaultValue="200")int limit){return run(()->health.list(tenant(),status,limit));}
 private OpenDispatchRequestContext context(){return OpenDispatchRequestContextHolder.current().orElseThrow(()->bad("Request context is required."));}private String tenant(){return required(context().tenantId(),"tenantId");}private String actor(){return required(context().operatorId(),"actorId");}private String correlation(){return text(context().correlationId()).isBlank()?UUID.randomUUID().toString():text(context().correlationId());}private String required(String s,String n){if(s==null||s.isBlank())throw bad(n+" is required.");return s.trim();}private String text(String s){return s==null?"":s.trim();}private int lim(int n){return Math.max(1,Math.min(n,1000));}private long version(String s){try{long v=Long.parseLong(required(s,"If-Match").replace("W/","").replace("\"","").trim());if(v<1)throw new NumberFormatException();return v;}catch(NumberFormatException ex){throw bad("If-Match must contain a positive row version.");}}private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private <T>T run(Op<T> op){try{return op.get();}catch(ResponseStatusException ex){throw ex;}catch(IllegalArgumentException ex){throw bad(ex.getMessage());}catch(IllegalStateException ex){throw new ResponseStatusException(HttpStatus.CONFLICT,ex.getMessage());}}@FunctionalInterface private interface Op<T>{T get();}
 public record GovernedReason(String reason){}public record RecoverExpiredClaimsRequest(int limit,String reason){}public record ReconciliationDriftRequest(ProjectionRecoveryCaseType caseType,String laneId,String workId,String projectionId,String externalIssueId,String expectedHash,String observedHash,String reason){}public record ReconciliationCompleteRequest(int scannedCount,int repairedCount,int failedCount,String reason){}public record RepairRequest(boolean dryRun,String reason){}public record ReconciliationRequest(String connectionId,String projectMappingId,String scopeType,String scopeId,boolean dryRun){}public record EnqueueRequest(String aggregateKey,ProjectionLaneType laneType,String connectionId,String projectMappingId,ProjectionOperationType operationType,String aggregateId,String outboxId,String projectionId,String payloadHash,String coalesceKey,String dependsOnWorkId,int maxQueueDepth,int maxAttempts){}
}
