package com.opensocket.aievent.core.api;
import java.util.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import com.opensocket.aievent.core.http.context.*;import com.opensocket.aievent.core.integration.issue.*;
@RestController @RequestMapping("/api/integrations/projection-outbox") public class ProjectionOutboxReliabilityController {
 private final ProjectionOutboxReliabilityService service; private final IssueProjectionService projectionService; private final IssueSyncRepository sync; public ProjectionOutboxReliabilityController(ProjectionOutboxReliabilityService service,IssueProjectionService projectionService,IssueSyncRepository sync){this.service=service;this.projectionService=projectionService;this.sync=sync;}
 @GetMapping public List<ProjectionOutboxReliability> list(@RequestParam(required=false)ProjectionOutboxReliabilityStatus status,@RequestParam(defaultValue="200")int limit){return service.list(tenant(),status,limit);}
 @GetMapping("/{outboxId}/attempts") public List<ProjectionProviderAttemptEvidence> attempts(@PathVariable String outboxId,@RequestParam(defaultValue="200")int limit){return service.attempts(tenant(),outboxId,limit);}
 @GetMapping("/{outboxId}/readbacks") public List<ProjectionReadbackEvidence> readbacks(@PathVariable String outboxId,@RequestParam(defaultValue="200")int limit){return service.readbacks(tenant(),outboxId,limit);}
 @PostMapping("/{outboxId}/replay") public ProjectionOutboxReliability replay(@PathVariable String outboxId,@RequestHeader("Idempotency-Key")String key,@RequestBody(required=false) ReplayRequest body){if(key==null||key.isBlank())throw bad("Idempotency-Key is required.");if(body==null||body.reason()==null||body.reason().isBlank())throw bad("Audit reason is required.");String t=tenant();IntegrationDeadLetter dead=sync.findDeadLetterByOutbox(t,outboxId).orElseThrow(()->bad("Dead Letter not found for Outbox."));IntegrationOutboxEntry retry=projectionService.retryDeadLetter(t,dead.deadLetterId(),operator(),body.reason().trim(),ctx().correlationId(),key.trim());return service.register(retry);}
 private String tenant(){return req(ctx().tenantId(),"tenantId");} private String operator(){return req(ctx().operatorId(),"operatorId");} private OpenDispatchRequestContext ctx(){return OpenDispatchRequestContextHolder.current().orElseThrow(()->bad("Request context is required."));} private String req(String v,String n){if(v==null||v.isBlank())throw bad(n+" is required.");return v.trim();} private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);} public record ReplayRequest(String reason){}
}
