/**
 * Task-domain type facade.
 *
 * Task product surfaces should depend on this boundary rather than the
 * all-domain compatibility barrel.
 */
export type {
  CoreTaskStatus,
  CoreDispatchStatus,
  CoreDispatchEventStage,
  CoreTaskRecord,
  CoreDispatchRequest,
  CoreTaskIssueTracking,
  CoreTaskIssueDedupSummary,
  CoreTaskRuntimeSnapshot,
  CoreTaskRuntimeView,
  CoreAgentCandidateScore,
  CoreDispatchUserFacingError,
  CoreRoutingDecisionRecord,
} from '@/lib/types/domains/taskModel';
export type {
  CoreTaskDispatchRequirementProfile,
  CoreTaskDispatchRequirements,
  CoreEligibleAgentCandidate,
  CoreTaskEligibleAgentsResponse,
  CoreDispatchEligibilityV2BlockingReason,
  CoreDispatchEligibilityV2ScoreBreakdown,
  CoreDispatchEligibilityV2PolicyMatch,
  CoreDispatchEligibilityV2Candidate,
  CoreDispatchEligibilityV2Response,
} from '@/lib/types/domains/taskEligibility';
export type {
  CoreTaskRemediationCommandType,
  CoreTaskRemediationCommandRequest,
  CoreTaskCommandSnapshot,
  CoreTaskCommandAudit,
  CoreTaskRemediationCommandResult,
  CoreRecoveryGovernanceActionRequest,
  CoreRecoveryGovernanceAuditSummary,
  CoreRecoveryGovernanceActionResult,
  CoreDispatchTimelineEvent,
  CoreDispatchTimelineResponse,
  CoreTaskCaseTimelineStepView,
  CoreTaskCaseTimelineView,
  CoreTaskDispatchEvidenceStage,
  CoreTaskDispatchRecoveryAction,
  CoreTaskDispatchContractRepairRequest,
  CoreTaskDispatchEvidenceView,
  CoreTaskRuntimeVerificationStep,
  CoreTaskRuntimeVerificationView,
  CoreAdminFailureQueueItem,
  CoreAdminFailureQueueResponse,
  CoreTaskA2AClassificationFlowContract,
  CoreTaskClassificationRequest,
  CoreTaskClassificationResult,
  CoreTaskFailureDomain,
  CoreTaskLineageEventType,
  CoreTaskLineageEvidence,
  CoreTaskOperationsSectionStatus,
  CoreTaskOperationsSection,
  CoreTaskOperationsOverviewPayload,
  CoreTaskOperationsExecutionPayload,
  CoreIssuePolicyDecisionView,
  CoreAdapterExecutorAuditView,
  CoreTaskOperationsIssuePayload,
  CoreTaskOperationsRelationshipsPayload,
  CoreTaskOperationsView,
  CoreTaskFinalizationStep,
  CoreTaskConditionAuthority,
  CoreTaskCanonicalStateAuthority,
  CoreTaskFinalizationAuthorityView,
  CoreTaskFinalizationRecoveryItem,
  CoreFlowRuleEvaluationEvidence,
  CoreTaskFlowMatchDecisionAuthority,
  CoreTaskFlowEvaluationSetAuthority,
  CoreTaskIssuePolicyAuthority,
  CoreTaskFlowMatchAuthorityView,
  CoreTaskDispatchContractResolveRequest,
  CoreTaskDispatchContractResolveResult,
  CoreDispatchRecipe,
  CoreDispatchRecipeEvaluationRequest,
  CoreTaskCapabilityResolveRequest,
  CoreTaskCapabilityResolveResult,
  CoreDispatchRecipeEvaluationResult,
  CoreDispatchReadinessStatus,
  CoreDispatchReadinessFixAction,
  CoreDispatchReadinessCheck,
  CoreDispatchReadinessEvaluationRequest,
  CoreDispatchReadinessEvaluationResult,
  CoreDispatchReadinessScenarioTemplate,
  CoreDispatchReadinessTemplates,
  CoreDispatchContractReadinessCheck,
  CoreDispatchContractReadinessRequest,
  CoreDispatchContractReadinessResponse,
  CoreDispatchSourceSystemOption,
  CoreDispatchContractBootstrapRequest,
  CoreDispatchContractChainInspectionRequest,
  CoreDispatchContractChainInspectionItem,
  CoreDispatchContractChainInspectionResponse,
  CoreDispatchContractTraceRequest,
  CoreDispatchContractTraceResponse,
  CoreDispatchContractTestTaskRequest,
  CoreDispatchContractTestTaskResponse,
  CoreDispatchContractBootstrapResponse,
} from '@/lib/types/domains/taskOperations';
export type {
  CoreCallbackInboxEntry,
  CoreCallbackInboxSummary,
  CoreDispatchAttemptHistoryRecord,
  CoreDispatchAttemptLedger,
  CoreDispatchAttemptLedgerEvent,
} from '@/lib/types/domains/taskRuntime';
