import { coreApiGet, coreApiPost } from '@/lib/api/coreClient';
import { createIdempotencyKey } from '@/lib/utils/uuid';

export interface GovernancePage<T>{items:T[];nextCursor:string;totalCount:number}
export interface ResourceGovernanceSummary{activeGrants:number;grantsExpiringSoon:number;activeDenies:number;openOrphans:number;overdueReviewItems:number;activeReviewCampaigns:number;shadowMismatches24h:number;staleDescriptors:number;measuredAt:string}
export interface ScopeGrantView{grantId:string;principalType:string;principalId:string;permissionCode:string;resourceType:string;scopeType:string;scopeRefId:string;visibilityLevel:string;state:string;grantSource:string;grantReason?:string;createdBy:string;approvedBy:string;validFrom:string;validTo?:string|null;version:number;updatedAt:string}
export interface ExplicitDenyView{denyId:string;principalType:string;principalId:string;permissionCode:string;resourceType:string;scopeType:string;scopeRefId:string;severity:string;state:string;denyReason:string;createdBy:string;approvedBy:string;validFrom:string;validTo?:string|null;version:number;updatedAt:string}
export interface OrphanView{repairId:string;resourceType:string;resourceId:string;resourceKey:string;repairStatus:string;reasonCode:string;assignedTo:string;proposedOwnerDepartmentId:string;proposedOwnerGroupId:string;proposedStewardUserId:string;resourceVersion:number;version:number;detectedAt:string;updatedAt:string}
export interface ResourceParticipantView{participantId:string;participantType:string;participantRefId:string;participantRole:string;visibilityLevel:string;allowedPermissions:string[];status:string;validFrom:string;validTo?:string|null}
export interface ResourceGovernanceOverview{resourceType:string;resourceId:string;resourceKey:string;ownerDepartmentId:string;ownerGroupId:string;stewardUserId:string;requesterDepartmentId:string;executorDepartmentId:string;sensitivityLevel:string;maximumVisibility:string;visibilityPolicyId:string;securityState:string;projectionStatus:string;resourceVersion:number;participantVersion:number;activeGrantCount:number;activeDenyCount:number;accessReviewStatus:string;participants:ResourceParticipantView[];sourceResolvedAt?:string|null;lastProjectedAt?:string|null;lastReconciledAt?:string|null}
export type AccessReviewCampaignStatus='DRAFT'|'ACTIVE'|'COMPLETED'|'CANCELLED';
export type AccessReviewItemStatus='OPEN'|'CONFIRMED'|'REDUCED'|'REVOKED'|'OWNER_MISSING'|'EXPIRED'|'ESCALATED';
export interface AccessReviewCampaign{campaignId:string;campaignName:string;description:string;resourceTypeFilter:string;principalTypeFilter:string;status:AccessReviewCampaignStatus;createdBy:string;activatedBy:string;completedBy:string;dueAt:string;totalItems:number;openItems:number;version:number;createdAt:string;updatedAt:string}
export interface AccessReviewItem{itemId:string;campaignId:string;sourceType:string;sourceId:string;principalType:string;principalId:string;permissionCode:string;resourceType:string;scopeType:string;scopeRefId:string;riskLevel:string;status:AccessReviewItemStatus;reviewerId:string;decisionReason:string;actionRequired:boolean;version:number;dueAt:string;reviewedAt?:string|null;createdAt:string;updatedAt:string}
export interface OrphanRepairImpactPreview{repairId:string;resourceType:string;resourceId:string;resourceKey:string;expectedResourceVersion:number;currentSecurityState:string;proposedOwnerDepartmentId:string;proposedOwnerGroupId:string;proposedStewardUserId:string;participantCount:number;activeGrantCount:number;activeDenyCount:number;childResourceCount:number;highRisk:boolean;warning:string;evaluatedAt:string}
export interface AuthorizationReason{code:string;category:string;safeMessage:string;evidenceRefs:string[]}
export interface AuthorizationDecision{decisionId:string;effect:string;mode:string;permissionCode:string;resourceRef:{tenantId:string;resourceType:string;resourceId:string};grantedVisibility:string;matchedRoleBindingIds:string[];matchedScopeGrantIds:string[];matchedParticipantIds:string[];matchedOwnershipEvidence:string[];matchedDenyIds:string[];matchedScopeSources:string[];policyVersion:Record<string,unknown>;securityEpoch:Record<string,unknown>;descriptorHash:string;runtimeLeaseId:string;reasons:AuthorizationReason[];evaluatedAt:string;shadowOnly:boolean;cacheable:boolean;cacheTtl?:string|number}

export type ScopePrincipalType='USER'|'DEPARTMENT'|'GROUP'|'SERVICE_ACCOUNT';
export type ScopeType='TENANT'|'DEPARTMENT'|'DEPARTMENT_SUBTREE'|'GROUP'|'RESOURCE'|'RESOURCE_TREE'|'TASK_CHAIN'|'PARTICIPANT'|'OWNER'|'CREATED_BY_ME'|'ASSIGNED_TO_ME'|'AUDIT_WINDOW'|'EXPLICIT_SET';
export type VisibilityLevel='NONE'|'METADATA'|'SUMMARY'|'STANDARD'|'SENSITIVE'|'FULL'|'SECRET_METADATA';
export type ResourceActionKind='READ'|'CREATE'|'UPDATE'|'DELETE'|'APPROVE'|'EXPORT'|'DOWNLOAD'|'MANAGE'|'EXECUTE';

function key(prefix:string){return createIdempotencyKey(prefix)}
const governanceBase='/api/resource-access/governance';
const administrationBase='/api/resource-access';

export const getGovernanceSummary=()=>coreApiGet<ResourceGovernanceSummary>(`${governanceBase}/summary`);
export const listGovernanceGrants=(options:{state?:string;search?:string;cursor?:string;limit?:number}={})=>coreApiGet<GovernancePage<ScopeGrantView>>(`${governanceBase}/grants`,options);
export const listGovernanceDenies=(options:{state?:string;search?:string;cursor?:string;limit?:number}={})=>coreApiGet<GovernancePage<ExplicitDenyView>>(`${governanceBase}/denies`,options);
export const listOrphans=(options:{status?:string;search?:string;cursor?:string;limit?:number}={})=>coreApiGet<GovernancePage<OrphanView>>(`${governanceBase}/orphans`,options);
export const getResourceOverview=(resourceType:string,resourceId:string)=>coreApiGet<ResourceGovernanceOverview>(`${governanceBase}/resources/${encodeURIComponent(resourceType)}/${encodeURIComponent(resourceId)}`);
export const listReviewCampaigns=(options:{status?:string;cursor?:string;limit?:number}={})=>coreApiGet<GovernancePage<AccessReviewCampaign>>(`${governanceBase}/reviews`,options);
export const createReviewCampaign=(body:{campaignId:string;campaignName:string;description:string;resourceTypeFilter?:string;principalTypeFilter?:string;dueAt:string})=>coreApiPost<AccessReviewCampaign>(`${governanceBase}/reviews`,body,{headers:{'Idempotency-Key':key('access-review-create')}});
export const transitionReviewCampaign=(campaignId:string,action:'activate'|'complete'|'cancel',version:number,reason:string)=>coreApiPost<AccessReviewCampaign>(`${governanceBase}/reviews/${encodeURIComponent(campaignId)}/${action}`,undefined,{headers:{'If-Match':String(version),'Idempotency-Key':key(`access-review-${action}`),'X-Audit-Reason':reason}});
export const listReviewItems=(campaignId:string,options:{status?:string;cursor?:string;limit?:number}={})=>coreApiGet<GovernancePage<AccessReviewItem>>(`${governanceBase}/reviews/${encodeURIComponent(campaignId)}/items`,options);
export const decideReviewItem=(campaignId:string,itemId:string,version:number,decision:AccessReviewItemStatus,reason:string)=>coreApiPost<AccessReviewItem>(`${governanceBase}/reviews/${encodeURIComponent(campaignId)}/items/${encodeURIComponent(itemId)}/decision`,{decision,reason},{headers:{'If-Match':String(version),'Idempotency-Key':key('access-review-decision')}});
export interface OrphanOwnerBody{resourceType:string;resourceId:string;ownerDepartmentId?:string;ownerGroupId?:string;stewardUserId?:string;expectedResourceVersion:number}
export const previewOrphanRepair=(repairId:string,body:OrphanOwnerBody,reason:string)=>coreApiPost<OrphanRepairImpactPreview>(`${governanceBase}/orphans/${encodeURIComponent(repairId)}/preview`,body,{headers:{'Idempotency-Key':key('orphan-preview'),'X-Audit-Reason':reason}});
export const assignOrphanOwner=(repairId:string,body:OrphanOwnerBody,reason:string)=>coreApiPost(`${governanceBase}/orphans/${encodeURIComponent(repairId)}/assign-owner`,body,{headers:{'If-Match':String(body.expectedResourceVersion),'Idempotency-Key':key('orphan-assign'),'X-Audit-Reason':reason}});

export interface CreateScopeGrantInput{grantId:string;principalType:ScopePrincipalType;principalId:string;permissionCode:string;resourceType:string;scopeType:ScopeType;scopeRefId?:string;visibilityLevel:VisibilityLevel;validFrom:string;validTo?:string|null;grantSource:'MANUAL'|'RESOURCE_SHARE'|'MIGRATION_COMPATIBILITY'|'BREAK_GLASS'|'SYSTEM_POLICY';grantReason:string}
export const createScopeGrant=(body:CreateScopeGrantInput)=>coreApiPost<ScopeGrantView>(`${administrationBase}/grants`,body,{headers:{'Idempotency-Key':key('scope-grant-create')}});
export const transitionScopeGrant=(grantId:string,action:'submit'|'approve'|'suspend'|'revoke',version:number,reason:string)=>coreApiPost<ScopeGrantView>(`${administrationBase}/grants/${encodeURIComponent(grantId)}/${action}`,undefined,{headers:{'If-Match':String(version),'Idempotency-Key':key(`scope-grant-${action}`),'X-Audit-Reason':reason}});

export interface CreateExplicitDenyInput{denyId:string;principalType:ScopePrincipalType;principalId:string;permissionCode?:string;resourceType:string;scopeType:ScopeType;scopeRefId?:string;denyReason:string;severity:'LOW'|'MEDIUM'|'HIGH'|'CRITICAL';validFrom:string;validTo?:string|null}
export const createExplicitDeny=(body:CreateExplicitDenyInput)=>coreApiPost<ExplicitDenyView>(`${administrationBase}/denies`,body,{headers:{'Idempotency-Key':key('scope-deny-create')}});
export const transitionExplicitDeny=(denyId:string,action:'submit'|'approve'|'revoke',version:number,reason:string)=>coreApiPost<ExplicitDenyView>(`${administrationBase}/denies/${encodeURIComponent(denyId)}/${action}`,undefined,{headers:{'If-Match':String(version),'Idempotency-Key':key(`scope-deny-${action}`),'X-Audit-Reason':reason}});

export interface DecisionInput{permissionCode:string;resourceType:string;resourceId:string;actionKind:ResourceActionKind;sideEffecting:boolean;requestedVisibility:VisibilityLevel;purpose:string;operationPhase?:string;targetPrincipalType?:'USER'|'SERVICE_ACCOUNT'|'GROUP'|'INSTANCE_ROOT'|'SYSTEM_SERVICE';targetPrincipalId?:string}
export const explainDecision=(input:DecisionInput)=>coreApiPost<AuthorizationDecision>('/api/resource-access/decisions/explain',{...input,operationPhase:input.operationPhase??'START'});
export const simulateDecision=(input:DecisionInput)=>coreApiPost<AuthorizationDecision>('/api/resource-access/decisions/simulate',{...input,targetPrincipalType:input.targetPrincipalType??'USER',targetPrincipalId:input.targetPrincipalId});
