package com.opensocket.aievent.core.iam.api.application.service;
import com.opensocket.aievent.core.iam.api.context.IamApiRequestContext;
import com.opensocket.aievent.core.iam.api.idempotency.IamIdempotencyExecutor;
import com.opensocket.aievent.core.iam.api.request.*;
import com.opensocket.aievent.core.iam.api.response.*;
import com.opensocket.aievent.core.iam.rbac.application.command.entrypoint.*;
import com.opensocket.aievent.core.iam.rbac.application.command.manifest.RegisterApplicationPermissionManifestCommand;
import com.opensocket.aievent.core.iam.rbac.application.command.shadow.*;
import com.opensocket.aievent.core.iam.rbac.application.port.in.EntryPointAuthorityAdministrationPort;
import com.opensocket.aievent.core.iam.rbac.domain.entrypoint.EntryPointAuthorityState;
import com.opensocket.aievent.core.iam.rbac.domain.manifest.PermissionManifestRegistrationEntry;
import java.util.*;
public final class IamEntryPointAuthorityAdministrationService {
 private static final String INSTANCE="INSTANCE";private final EntryPointAuthorityAdministrationPort port;private final IamIdempotencyExecutor idempotency;
 public IamEntryPointAuthorityAdministrationService(EntryPointAuthorityAdministrationPort p,IamIdempotencyExecutor i){port=p;idempotency=i;}
 public List<EntryPointAuthorityResponse> entries(String text,String state,String owner,int limit){return port.entries(text,state,owner,limit).stream().map(EntryPointAuthorityResponse::from).toList();}
 public EntryPointBurnDownSummaryResponse summary(){return EntryPointBurnDownSummaryResponse.from(port.summary());}
 public List<LegacyAuthorityMappingResponse> mappings(String status,int limit){return port.mappings(status,limit).stream().map(LegacyAuthorityMappingResponse::from).toList();}
 public List<EntryPointBypassResponse> bypasses(String status,int limit){return port.bypasses(status,limit).stream().map(EntryPointBypassResponse::from).toList();}
 public EntryPointAuthorityResponse updateEntry(String id,UpdateEntryPointAuthorityRequest r,long v,IamApiRequestContext c){String key=c.requireIdempotencyKey();String reason=c.requireAuditReason();return idempotency.execute(INSTANCE,c.actorId(),"permission.entry-point.update",key,r,200,EntryPointAuthorityResponse.class,()->EntryPointAuthorityResponse.from(port.updateEntryPoint(new UpdateEntryPointAuthorityCommand(id,r.ownerModule(),EntryPointAuthorityState.valueOf(r.authorityState().toUpperCase(Locale.ROOT)),opt(r.targetPermissionCode()),opt(r.legacyAuthorityType()),r.legacyAuthorities(),r.resourceType(),r.resourceResolverId(),opt(r.exemptionReason()),Optional.ofNullable(r.migrationDeadline()),v,c.actorId(),c.correlationId(),reason,c.requestedAt()))));}
 public LegacyAuthorityMappingResponse updateMapping(String id,UpdateLegacyAuthorityMappingRequest r,long v,IamApiRequestContext c){String key=c.requireIdempotencyKey();String reason=c.requireAuditReason();return idempotency.execute(INSTANCE,c.actorId(),"permission.legacy-mapping.update",key,r,200,LegacyAuthorityMappingResponse.class,()->LegacyAuthorityMappingResponse.from(port.updateMapping(new UpdateLegacyAuthorityMappingCommand(id,opt(r.targetPermissionCode()),r.ownerModule(),r.status(),Optional.ofNullable(r.migrationDeadline()),r.notes()==null?"":r.notes(),v,c.actorId(),c.correlationId(),reason,c.requestedAt()))));}
 public EntryPointBypassResponse createBypass(CreateEntryPointBypassRequest r,IamApiRequestContext c){String key=c.requireIdempotencyKey();String reason=c.requireAuditReason();return idempotency.execute(INSTANCE,c.actorId(),"permission.entry-point-bypass.create",key,r,201,EntryPointBypassResponse.class,()->EntryPointBypassResponse.from(port.createBypass(new CreateEntryPointBypassCommand(UUID.randomUUID().toString(),r.entryPointId(),r.ownerId(),r.reason(),r.replacement(),r.expiresAt(),c.actorId(),c.correlationId(),reason,c.requestedAt()))));}
 public EntryPointBypassResponse revokeBypass(String id,RevokeEntryPointBypassRequest r,long v,IamApiRequestContext c){String key=c.requireIdempotencyKey();String reason=c.requireAuditReason();return idempotency.execute(INSTANCE,c.actorId(),"permission.entry-point-bypass.revoke",key,r,200,EntryPointBypassResponse.class,()->EntryPointBypassResponse.from(port.revokeBypass(new RevokeEntryPointBypassCommand(id,v,r.reason(),c.actorId(),c.correlationId(),reason,c.requestedAt()))));}
 public List<ApplicationPermissionManifestResponse> manifests(int limit){return port.manifests(limit).stream().map(ApplicationPermissionManifestResponse::from).toList();}
 public ApplicationPermissionManifestResponse manifest(String id){return ApplicationPermissionManifestResponse.from(port.manifest(id));}
 public List<ApplicationPermissionManifestEntryResponse> manifestEntries(String id,String driftStatus,int limit){return port.manifestEntries(id,driftStatus,limit).stream().map(ApplicationPermissionManifestEntryResponse::from).toList();}
 public PermissionManifestDriftSummaryResponse manifestDrift(String id){return PermissionManifestDriftSummaryResponse.from(port.manifestDrift(id));}
 public List<PermissionCoverageEvidenceResponse> coverageEvidence(int limit){return port.coverageEvidence(limit).stream().map(PermissionCoverageEvidenceResponse::from).toList();}
 public ApplicationPermissionManifestResponse registerManifest(RegisterApplicationPermissionManifestRequest r,IamApiRequestContext c){
  String key=c.requireIdempotencyKey();String reason=c.requireAuditReason();
  return idempotency.execute(INSTANCE,c.actorId(),"permission.manifest.register",key,r,201,ApplicationPermissionManifestResponse.class,()->{
   var stats=r.statistics();var binding=r.catalogBinding();
   List<PermissionManifestRegistrationEntry> entries=r.entries().stream().map(e->new PermissionManifestRegistrationEntry(
     e.entryPointId(),e.entryPointType(),e.ownerModule(),e.displayName(),opt(e.routePattern()),opt(e.httpMethod()),e.authorityState(),
     e.protectionMode(),e.coverageStatus(),opt(e.permissionCode()),e.legacyAuthorities(),e.resourceType(),e.resourceResolverId(),
     e.scopeRequired(),opt(e.exemptionReason()),e.sourceRef(),e.sourceHash(),e.descriptorHash())).toList();
   return ApplicationPermissionManifestResponse.from(port.registerManifest(new RegisterApplicationPermissionManifestCommand(
     UUID.randomUUID().toString(),r.applicationId(),r.environment(),r.buildVersion(),r.manifestRevision(),r.schemaVersion(),
     r.contentHash(),binding.revisionId(),binding.revisionCode(),r.sourceInventoryRevision(),stats.entryCount(),
     stats.protectedEntryCount(),stats.coveredEntryCount(),stats.coveragePercent(),stats.targetPermissionCount(),
     stats.legacyAuthorityCount(),stats.exemptCount(),stats.delegatedCount(),stats.uncoveredCount(),entries,
     c.actorId(),c.correlationId(),reason,c.requestedAt())));
  });
 }
 public List<ShadowObservationResponse> shadowObservations(String tenantId,String domainCode,String category,int limit){return port.shadowObservations(tenantId,domainCode,category,limit).stream().map(ShadowObservationResponse::from).toList();}
 public ShadowObservationSummaryResponse shadowSummary(String tenantId,String domainCode){return ShadowObservationSummaryResponse.from(port.shadowSummary(tenantId,domainCode));}
 public List<ShadowMismatchCaseResponse> mismatchCases(String tenantId,String domainCode,String status,int limit){return port.mismatchCases(tenantId,domainCode,status,limit).stream().map(ShadowMismatchCaseResponse::from).toList();}
 public ShadowMismatchCaseResponse createMismatchCase(CreateMismatchCaseRequest r,IamApiRequestContext c){String key=c.requireIdempotencyKey(),reason=c.requireAuditReason();return idempotency.execute(INSTANCE,c.actorId(),"permission.mismatch-case.create",key,r,201,ShadowMismatchCaseResponse.class,()->ShadowMismatchCaseResponse.from(port.createMismatchCase(new CreateMismatchCaseCommand(UUID.randomUUID().toString(),r.tenantId(),r.comparisonId(),opt(r.entryPointId()),r.ownerId(),r.slaDueAt(),r.title(),c.actorId(),c.correlationId(),reason,c.requestedAt()))));}
 public ShadowMismatchCaseResponse updateMismatchCase(String id,UpdateMismatchCaseRequest r,long version,IamApiRequestContext c){String key=c.requireIdempotencyKey(),reason=c.requireAuditReason();return idempotency.execute(INSTANCE,c.actorId(),"permission.mismatch-case.update",key,r,200,ShadowMismatchCaseResponse.class,()->ShadowMismatchCaseResponse.from(port.updateMismatchCase(new UpdateMismatchCaseCommand(id,r.status(),r.severity(),r.ownerId(),r.slaDueAt(),opt(r.resolution()),version,c.actorId(),c.correlationId(),reason,c.requestedAt()))));}
 public ShadowMismatchWaiverResponse createMismatchWaiver(String id,CreateMismatchWaiverRequest r,IamApiRequestContext c){String key=c.requireIdempotencyKey(),reason=c.requireAuditReason();return idempotency.execute(INSTANCE,c.actorId(),"permission.mismatch-waiver.create",key,r,201,ShadowMismatchWaiverResponse.class,()->ShadowMismatchWaiverResponse.from(port.createMismatchWaiver(new CreateMismatchWaiverCommand(UUID.randomUUID().toString(),id,r.reason(),r.expiresAt(),c.actorId(),c.correlationId(),reason,c.requestedAt()))));}
 public ShadowRegressionEvidenceResponse addRegressionEvidence(String id,AddRegressionEvidenceRequest r,IamApiRequestContext c){String key=c.requireIdempotencyKey(),reason=c.requireAuditReason();return idempotency.execute(INSTANCE,c.actorId(),"permission.regression-evidence.create",key,r,201,ShadowRegressionEvidenceResponse.class,()->ShadowRegressionEvidenceResponse.from(port.addRegressionEvidence(new AddRegressionEvidenceCommand(UUID.randomUUID().toString(),id,r.testReference(),r.result(),r.detailsJson()==null?"{}":r.detailsJson(),c.actorId(),c.correlationId(),reason,c.requestedAt()))));}
 public List<DomainReadinessEvidenceResponse> domainReadiness(String tenantId,String domainCode,int limit){return port.domainReadiness(tenantId,domainCode,limit).stream().map(DomainReadinessEvidenceResponse::from).toList();}
 public DomainReadinessEvidenceResponse evaluateDomainReadiness(EvaluateDomainReadinessRequest r,IamApiRequestContext c){String key=c.requireIdempotencyKey(),reason=c.requireAuditReason();return idempotency.execute(INSTANCE,c.actorId(),"permission.domain-readiness.evaluate",key,r,201,DomainReadinessEvidenceResponse.class,()->DomainReadinessEvidenceResponse.from(port.evaluateDomainReadiness(new EvaluateDomainReadinessCommand(r.tenantId(),r.domainCode(),r.windowStartedAt(),r.windowEndedAt(),c.actorId(),c.correlationId(),reason))));}
 public List<Phase6EligibilityEvidenceResponse> phase6Eligibility(String tenantId,int limit){return port.phase6Eligibility(tenantId,limit).stream().map(Phase6EligibilityEvidenceResponse::from).toList();}
 public Phase6EligibilityEvidenceResponse evaluatePhase6Eligibility(EvaluatePhase6EligibilityRequest r,IamApiRequestContext c){String key=c.requireIdempotencyKey(),reason=c.requireAuditReason();return idempotency.execute(INSTANCE,c.actorId(),"permission.phase6-eligibility.evaluate",key,r,201,Phase6EligibilityEvidenceResponse.class,()->Phase6EligibilityEvidenceResponse.from(port.evaluatePhase6Eligibility(new EvaluatePhase6EligibilityCommand(r.tenantId(),c.actorId(),c.correlationId(),reason))));}
 private Optional<String> opt(String v){return v==null||v.isBlank()?Optional.empty():Optional.of(v.trim());} public ShadowPipelineReadinessResponse shadowPipelineReadiness(){return ShadowPipelineReadinessResponse.from(port.shadowPipelineReadiness());}
 public ShadowStorageReadinessResponse shadowStorageReadiness(){return ShadowStorageReadinessResponse.from(port.shadowStorageReadiness());}
 public List<ShadowRetentionRunResponse> shadowRetentionRuns(int limit){return port.shadowRetentionRuns(limit).stream().map(ShadowRetentionRunResponse::from).toList();}
 public String processShadowPipeline(ProcessShadowPipelineRequest r,IamApiRequestContext c){String key=c.requireIdempotencyKey(),reason=c.requireAuditReason();return idempotency.execute(INSTANCE,c.actorId(),"permission.shadow-pipeline.process",key,r,200,String.class,()->port.processShadowPipeline("api:"+c.actorId(),r.batchSize(),c.actorId(),c.correlationId(),reason));}
 public ShadowRetentionRunResponse runShadowRetention(RunShadowRetentionRequest r,IamApiRequestContext c){String key=c.requireIdempotencyKey(),reason=c.requireAuditReason();return idempotency.execute(INSTANCE,c.actorId(),"permission.shadow-retention.run",key,r,201,ShadowRetentionRunResponse.class,()->ShadowRetentionRunResponse.from(port.runShadowRetention(new RunShadowRetentionCommand(c.actorId(),c.correlationId(),reason))));}
 public List<Phase5RuntimeCertificationEvidenceResponse> phase5RuntimeCertificationEvidence(int limit){return port.phase5RuntimeCertificationEvidence(limit).stream().map(Phase5RuntimeCertificationEvidenceResponse::from).toList();}
 public Phase5RuntimeCertificationEvidenceResponse generatePhase5RuntimeCertificationEvidence(GeneratePhase5RuntimeCertificationRequest r,IamApiRequestContext c){String key=c.requireIdempotencyKey(),reason=c.requireAuditReason();return idempotency.execute(INSTANCE,c.actorId(),"permission.runtime-certification.generate",key,r,201,Phase5RuntimeCertificationEvidenceResponse.class,()->Phase5RuntimeCertificationEvidenceResponse.from(port.generatePhase5RuntimeCertificationEvidence(new GeneratePhase5RuntimeCertificationCommand(r.sourceVersion(),r.postgresqlCleanStatus(),r.postgresqlUpgradeStatus(),r.applicationContextStatus(),r.adminUiBuildStatus(),r.playwrightStatus(),r.loadTestStatus(),r.pipelineStatus(),r.evidenceJson(),c.actorId(),c.correlationId(),reason))));}

}
