package com.opensocket.aievent.core.task.authority;

/** A0-R2 reasons that authorize entry into FINALIZING. */
public enum TerminalizationReason {
    PLAN_COMPLETED, PLAN_FAILED, USER_CANCELLED, KILL_SWITCHED, POLICY_REVOKED,
    BUDGET_EXHAUSTED, CAPACITY_TIMEOUT, APPROVAL_EXPIRED, RESIDENCY_DENIED,
    FLOW_CONFIGURATION_ERROR, REMOTE_UNRESOLVED, LOCAL_UNRESOLVED, RUNTIME_FATAL, MANUAL_ABORT
}
