package com.opensocket.aievent.core.integration.issue.webhook;
import static org.assertj.core.api.Assertions.assertThat;
import java.nio.charset.StandardCharsets; import java.time.*; import java.util.*; import java.util.concurrent.atomic.AtomicInteger; import javax.crypto.Mac; import javax.crypto.spec.SecretKeySpec;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.support.StaticListableBeanFactory; import org.springframework.mock.web.*;
import com.opensocket.aievent.core.integration.identity.*; import tools.jackson.databind.ObjectMapper;
class ProviderWebhookAuthenticationFilterTest {
 private static final String TOKEN="opaque-endpoint-token",SECRET="filter-test-secret",PATH="/api/external/provider-webhooks/"+TOKEN;
 private InMemoryIntegrationIdentityRepository identities; private CountingEndpointRepository endpoints; private ProviderWebhookAuthenticationFilter filter;
 @BeforeEach void setup(){var now=OffsetDateTime.now();identities=new InMemoryIntegrationIdentityRepository();identities.saveConnection(new IntegrationConnection("tenant-a","conn-a",IntegrationProviderType.JIRA,"Jira","https://jira.example","CLOUD",null,IntegrationConnectionStatus.ACTIVE,10000,null,null,null,true,1,now,now));identities.savePrincipal(new IntegrationPrincipal("tenant-a","principal-a","conn-a","Webhook",IntegrationPrincipalType.SERVICE_ACCOUNT,null,null,"zone-a",null,IntegrationPrincipalStatus.ACTIVE,IntegrationRiskLevel.LOW,Map.of(),List.of(),now,1,now,now));identities.savePrincipalScope(new IntegrationPrincipalScope("tenant-a","principal-a",IntegrationIsolationMode.PER_PROJECT,"ERP",List.of("ERP"),List.of(IntegrationOperation.WEBHOOK),List.of("*"),true,1,now,now));identities.saveCredential(new IntegrationCredentialMetadata("tenant-a","cred-a","principal-a",IntegrationAuthType.WEBHOOK_HMAC,"env://TEST","v1","1234",now.minusMinutes(1),now.plusDays(1),null,null,IntegrationCredentialStatus.ACTIVE,1,now,now));endpoints=new CountingEndpointRepository(new IntegrationWebhookEndpoint("tenant-a","endpoint-a",sha(TOKEN),"conn-a","principal-a",IntegrationProviderType.JIRA,IntegrationWebhookEndpointStatus.ACTIVE,"HMAC_SHA256_V1",2048,20,300,1,now,now));var factory=new StaticListableBeanFactory();factory.addBean("resolver",new IntegrationSecretResolver(){public ResolvedIntegrationSecret resolve(IntegrationCredentialMetadata c){return new ResolvedIntegrationSecret(SECRET.toCharArray());}public String mode(){return "TEST";}public boolean supports(IntegrationCredentialMetadata c){return true;}});var props=new ProviderWebhookSecurityProperties();props.setClockSkewSeconds(30);filter=new ProviderWebhookAuthenticationFilter(endpoints,identities,new HmacProviderWebhookSignatureVerifier(factory.getBeanProvider(IntegrationSecretResolver.class)),new ProviderWebhookRateLimiter(),props,new ObjectMapper());}
 @Test void validRequestIgnoresCallerTenantAndReservesNonce()throws Exception{var request=request(body("ISSUE-1","ERP"),"nonce-1");request.addHeader("X-Tenant-Id","evil-tenant");var response=new MockHttpServletResponse();var chain=new MockFilterChain();filter.doFilter(request,response,chain);assertThat(response.getStatus()).isEqualTo(200);assertThat(chain.getRequest()).isNotNull();assertThat(endpoints.reservations.get()).isEqualTo(1);var principal=(ProviderWebhookMachinePrincipal)chain.getRequest().getAttribute(ProviderWebhookAuthenticationFilter.MACHINE_PRINCIPAL_ATTRIBUTE);assertThat(principal.tenantId()).isEqualTo("tenant-a");}
 @Test void bodyOrIssueMutationInvalidatesSignatureBeforeNonceReservation()throws Exception{String original=body("ISSUE-1","ERP");var request=request(original,"nonce-2");request.setContent(body("ISSUE-2","ERP").getBytes(StandardCharsets.UTF_8));var response=new MockHttpServletResponse();filter.doFilter(request,response,new MockFilterChain());assertThat(response.getStatus()).isEqualTo(401);assertThat(endpoints.reservations.get()).isZero();}
 @Test void expiredTimestampAndOutOfScopeProjectFailWithoutNonceReservation()throws Exception{var expired=request(body("ISSUE-1","ERP"),"nonce-3");expired.removeHeader("X-Webhook-Timestamp");expired.addHeader("X-Webhook-Timestamp",OffsetDateTime.now(ZoneOffset.UTC).minusHours(1).toString());resign(expired);var r1=new MockHttpServletResponse();filter.doFilter(expired,r1,new MockFilterChain());assertThat(r1.getStatus()).isEqualTo(401);var scoped=request(body("ISSUE-1","MES"),"nonce-4");var r2=new MockHttpServletResponse();filter.doFilter(scoped,r2,new MockFilterChain());assertThat(r2.getStatus()).isEqualTo(403);assertThat(endpoints.reservations.get()).isZero();}
 @Test void duplicateNonceAndOversizedBodyAreRejected()throws Exception{var first=request(body("ISSUE-1","ERP"),"same-nonce");filter.doFilter(first,new MockHttpServletResponse(),new MockFilterChain());var second=request(body("ISSUE-1","ERP"),"same-nonce");var replay=new MockHttpServletResponse();filter.doFilter(second,replay,new MockFilterChain());assertThat(replay.getStatus()).isEqualTo(409);endpoints.value=new IntegrationWebhookEndpoint("tenant-a","endpoint-a",sha(TOKEN),"conn-a","principal-a",IntegrationProviderType.JIRA,IntegrationWebhookEndpointStatus.ACTIVE,"HMAC_SHA256_V1",32,20,300,1,OffsetDateTime.now(),OffsetDateTime.now());var large=request(body("ISSUE-12345678901234567890","ERP"),"large");var tooLarge=new MockHttpServletResponse();filter.doFilter(large,tooLarge,new MockFilterChain());assertThat(tooLarge.getStatus()).isEqualTo(413);}
 @Test void futureTimestampInvalidContentTypeAndUnknownEndpointAreRejected()throws Exception{var future=request(body("ISSUE-1","ERP"),"future");future.removeHeader("X-Webhook-Timestamp");future.addHeader("X-Webhook-Timestamp",OffsetDateTime.now(ZoneOffset.UTC).plusMinutes(5).toString());resign(future);var r1=new MockHttpServletResponse();filter.doFilter(future,r1,new MockFilterChain());assertThat(r1.getStatus()).isEqualTo(401);var type=request(body("ISSUE-1","ERP"),"type");type.setContentType("text/plain");var r2=new MockHttpServletResponse();filter.doFilter(type,r2,new MockFilterChain());assertThat(r2.getStatus()).isEqualTo(415);var unknown=request(body("ISSUE-1","ERP"),"unknown");unknown.setRequestURI("/api/external/provider-webhooks/unknown-token");var r3=new MockHttpServletResponse();filter.doFilter(unknown,r3,new MockFilterChain());assertThat(r3.getStatus()).isEqualTo(401);assertThat(endpoints.reservations.get()).isZero();}
 @Test void inactiveConnectionIsRejectedBeforeNonceReservation()throws Exception{var now=OffsetDateTime.now();identities.saveConnection(new IntegrationConnection("tenant-a","conn-a",IntegrationProviderType.JIRA,"Jira","https://jira.example","CLOUD",null,IntegrationConnectionStatus.DISABLED,10000,null,null,null,false,2,now,now));var request=request(body("ISSUE-1","ERP"),"inactive");var response=new MockHttpServletResponse();filter.doFilter(request,response,new MockFilterChain());assertThat(response.getStatus()).isEqualTo(403);assertThat(endpoints.reservations.get()).isZero();}
 @Test void inactivePrincipalIsRejectedBeforeNonceReservation()throws Exception{var now=OffsetDateTime.now();identities.savePrincipal(new IntegrationPrincipal("tenant-a","principal-a","conn-a","Webhook",IntegrationPrincipalType.SERVICE_ACCOUNT,null,null,"zone-a",null,IntegrationPrincipalStatus.DISABLED,IntegrationRiskLevel.LOW,Map.of(),List.of(),now,2,now,now));var request=request(body("ISSUE-1","ERP"),"inactive-principal");var response=new MockHttpServletResponse();filter.doFilter(request,response,new MockFilterChain());assertThat(response.getStatus()).isEqualTo(403);assertThat(endpoints.reservations.get()).isZero();}
 private MockHttpServletRequest request(String body,String nonce)throws Exception{var r=new MockHttpServletRequest("POST",PATH);r.setRequestURI(PATH);r.setContentType("application/json");r.setContent(body.getBytes(StandardCharsets.UTF_8));r.addHeader("X-Provider-Event-Id","evt-1");r.addHeader("X-Webhook-Timestamp",OffsetDateTime.now(ZoneOffset.UTC).toString());r.addHeader("X-Webhook-Nonce",nonce);r.addHeader("X-Correlation-Id","corr-1");resign(r);return r;}
 private void resign(MockHttpServletRequest r)throws Exception{r.removeHeader("X-Webhook-Signature");String digest=sha(new String(r.getContentAsByteArray(),StandardCharsets.UTF_8));var signing=new ProviderWebhookSigningRequest("POST",PATH,"conn-a","JIRA",r.getHeader("X-Provider-Event-Id"),r.getHeader("X-Webhook-Timestamp"),r.getHeader("X-Webhook-Nonce"),digest);Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(SECRET.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));r.addHeader("X-Webhook-Signature","sha256="+HexFormat.of().formatHex(mac.doFinal(signing.signingInput().getBytes(StandardCharsets.UTF_8))));}
 private String body(String issue,String project){return "{\"eventType\":\"ISSUE_UPDATED\",\"externalProjectId\":\""+project+"\",\"externalIssueId\":\""+issue+"\",\"externalIssueKey\":\"ERP-1\",\"externalIssueStatus\":\"OPEN\",\"observedDocumentJson\":\"{}\"}";}
 private static String sha(String v){try{return HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new RuntimeException(e);}}
 private static final class CountingEndpointRepository implements IntegrationWebhookEndpointRepository {private IntegrationWebhookEndpoint value;private final Set<String> nonces=new HashSet<>();private final AtomicInteger reservations=new AtomicInteger();CountingEndpointRepository(IntegrationWebhookEndpoint v){value=v;}public IntegrationWebhookEndpoint save(IntegrationWebhookEndpoint v){value=v;return v;}public Optional<IntegrationWebhookEndpoint> find(String t,String id){return Optional.of(value);}public Optional<IntegrationWebhookEndpoint> findByTokenHash(String h){return value.endpointTokenHash().equals(h)?Optional.of(value):Optional.empty();}public List<IntegrationWebhookEndpoint> list(String t,String c,int n){return List.of(value);}public boolean reserveNonce(String t,String c,String e,String h,OffsetDateTime x,String corr){if(!nonces.add(h))return false;reservations.incrementAndGet();return true;}public int deleteExpiredNonces(OffsetDateTime b,int n){return 0;}public String mode(){return "TEST";}}
}
