package com.opensocket.aievent.database.persistence.issuesync.dao;
import java.time.OffsetDateTime; import java.util.List; import org.apache.ibatis.annotations.*; import com.opensocket.aievent.database.persistence.issuesync.po.*;
@Mapper public interface IssueSyncDao {
 int upsertRelationship(@Param("value") IssueRelationshipPo value); IssueRelationshipPo findRelationship(@Param("tenantId")String tenantId,@Param("relationshipId")String relationshipId); List<IssueRelationshipPo> listRelationships(@Param("tenantId")String tenantId,@Param("linkId")String linkId,@Param("limit")int limit);
 List<String> listDueTenants(@Param("now")OffsetDateTime now,@Param("limit")int limit);
 int upsertOutbox(@Param("value") IntegrationOutboxPo value); IntegrationOutboxPo findOutbox(@Param("tenantId")String tenantId,@Param("outboxId")String outboxId); IntegrationOutboxPo findOutboxByIdempotencyKey(@Param("tenantId")String tenantId,@Param("idempotencyKey")String key); List<IntegrationOutboxPo> claimDue(@Param("tenantId")String tenantId,@Param("workerId")String workerId,@Param("now")OffsetDateTime now,@Param("claimUntil")OffsetDateTime claimUntil,@Param("limit")int limit);
 int upsertInbox(@Param("value") IntegrationInboxPo value); IntegrationInboxPo findInboxByProviderEvent(@Param("tenantId")String tenantId,@Param("connectionId")String connectionId,@Param("providerEventId")String eventId); List<IntegrationInboxPo> listInbox(@Param("tenantId")String tenantId,@Param("limit")int limit);
 int insertAttempt(@Param("value") IntegrationSyncAttemptPo value); List<IntegrationSyncAttemptPo> listAttempts(@Param("tenantId")String tenantId,@Param("outboxId")String outboxId,@Param("limit")int limit);
 int upsertDeadLetter(@Param("value") IntegrationDeadLetterPo value); IntegrationDeadLetterPo findDeadLetter(@Param("tenantId")String tenantId,@Param("deadLetterId")String id); IntegrationDeadLetterPo findDeadLetterByOutbox(@Param("tenantId")String tenantId,@Param("outboxId")String outboxId); List<IntegrationDeadLetterPo> listDeadLetters(@Param("tenantId")String tenantId,@Param("status")String status,@Param("limit")int limit);
 int upsertConflict(@Param("value") IntegrationConflictPo value); IntegrationConflictPo findConflict(@Param("tenantId")String tenantId,@Param("conflictId")String id); List<IntegrationConflictPo> listConflicts(@Param("tenantId")String tenantId,@Param("status")String status,@Param("limit")int limit);
 int upsertCircuitBreaker(@Param("value") IntegrationCircuitBreakerPo value); IntegrationCircuitBreakerPo findCircuitBreaker(@Param("tenantId")String tenantId,@Param("connectionId")String connectionId,@Param("mappingId")String mappingId);
}
