package com.opensocket.aievent.core.iam.persistence.dao;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

public interface IamRbacDao {

    Map<String,Object> findActiveCatalogRevision();
    Long findActiveCatalogRevisionPointerVersion();
    Map<String,Object> findCatalogRevision(@Param("revisionId") String revisionId);
    List<Map<String,Object>> findCatalogRevisions();
    int countDraftCatalogRevisions();
    Long nextCatalogRevisionNumber();
    int insertCatalogRevision(@Param("row") Map<String,Object> row);
    int cloneCatalogEntries(@Param("sourceRevisionId") String sourceRevisionId,@Param("targetRevisionId") String targetRevisionId,@Param("actorId") String actorId,@Param("at") Instant at);
    int cloneCatalogAliases(@Param("sourceRevisionId") String sourceRevisionId,@Param("targetRevisionId") String targetRevisionId,@Param("actorId") String actorId,@Param("at") Instant at);
    List<Map<String,Object>> findCatalogDefinitions(@Param("revisionId") String revisionId);
    Map<String,Object> findCatalogDefinition(@Param("revisionId") String revisionId,@Param("permissionCode") String permissionCode);
    int insertCatalogDefinition(@Param("row") Map<String,Object> row);
    int updateCatalogDefinition(@Param("row") Map<String,Object> row,@Param("expectedVersion") long expectedVersion);
    int deleteCatalogDefinition(@Param("revisionId") String revisionId,@Param("permissionCode") String permissionCode,@Param("expectedVersion") long expectedVersion);
    List<Map<String,Object>> findCatalogAliases(@Param("revisionId") String revisionId);
    Map<String,Object> findCatalogAlias(@Param("revisionId") String revisionId,@Param("aliasCode") String aliasCode);
    int insertCatalogAlias(@Param("row") Map<String,Object> row);
    int updateCatalogAlias(@Param("row") Map<String,Object> row,@Param("expectedVersion") long expectedVersion);
    int deleteCatalogAlias(@Param("revisionId") String revisionId,@Param("aliasCode") String aliasCode,@Param("expectedVersion") long expectedVersion);
    List<String> findRoleReferencedPermissionCodes();
    int insertCatalogChangeEvent(@Param("row") Map<String,Object> row);
    int publishCatalogRevision(@Param("revisionId") String revisionId,@Param("contentHash") String contentHash,@Param("actorId") String actorId,@Param("at") Instant at,@Param("expectedVersion") long expectedVersion);
    int supersedeCatalogRevision(@Param("revisionId") String revisionId,@Param("actorId") String actorId,@Param("at") Instant at,@Param("expectedVersion") long expectedVersion);
    String setCatalogPublicationContext(@Param("revisionId") String revisionId);
    int upsertActivePermissionDefinition(@Param("row") Map<String,Object> row);
    int activateCatalogRevision(@Param("revisionId") String revisionId,@Param("actorId") String actorId,@Param("at") Instant at,@Param("expectedVersion") long expectedVersion);
    int insertCatalogPublication(@Param("row") Map<String,Object> row);
    List<Map<String,Object>> findCatalogPublications(@Param("limit") int limit);
    Map<String,Object> findPermissionByCode(@Param("permissionCode") String permissionCode);
    List<Map<String,Object>> findPermissionsByCodes(@Param("permissionCodes") List<String> permissionCodes);
    List<String> findActivePermissionCodes();
    String setPermissionReadinessContext(@Param("actorId") String actorId,@Param("correlationId") String correlationId,@Param("auditReason") String auditReason);
    List<Map<String,Object>> findEntryPoints(@Param("text") String text,@Param("state") String state,@Param("ownerModule") String ownerModule,@Param("limit") int limit);
    Map<String,Object> findEntryPoint(@Param("entryPointId") String entryPointId);
    Map<String,Object> summarizeEntryPoints();
    int updateEntryPoint(@Param("row") Map<String,Object> row,@Param("expectedVersion") long expectedVersion);
    List<Map<String,Object>> findLegacyAuthorityMappings(@Param("status") String status,@Param("limit") int limit);
    Map<String,Object> findLegacyAuthorityMapping(@Param("mappingId") String mappingId);
    int updateLegacyAuthorityMapping(@Param("row") Map<String,Object> row,@Param("expectedVersion") long expectedVersion);
    List<Map<String,Object>> findEntryPointBypasses(@Param("status") String status,@Param("limit") int limit);
    Map<String,Object> findEntryPointBypass(@Param("bypassId") String bypassId);
    int insertEntryPointBypass(@Param("row") Map<String,Object> row);
    int revokeEntryPointBypass(@Param("bypassId") String bypassId,@Param("expectedVersion") long expectedVersion,@Param("actorId") String actorId,@Param("reason") String reason,@Param("at") Instant at);
    List<Map<String,Object>> findApplicationManifests(@Param("limit") int limit);
    Map<String,Object> findApplicationManifest(@Param("manifestId") String manifestId);
    List<Map<String,Object>> findApplicationManifestEntries(@Param("manifestId") String manifestId,@Param("driftStatus") String driftStatus,@Param("limit") int limit);
    Map<String,Object> summarizeApplicationManifestDrift(@Param("manifestId") String manifestId);
    List<Map<String,Object>> findPermissionCoverageEvidence(@Param("limit") int limit);
    int insertApplicationManifest(@Param("row") Map<String,Object> row);
    int insertApplicationManifestEntry(@Param("row") Map<String,Object> row);
    String activateApplicationManifest(@Param("manifestId") String manifestId,@Param("actorId") String actorId,@Param("correlationId") String correlationId,@Param("auditReason") String auditReason);

    List<Map<String,Object>> findShadowObservations(@Param("tenantId") String tenantId,@Param("domainCode") String domainCode,@Param("category") String category,@Param("limit") int limit);
    Map<String,Object> summarizeShadowObservations(@Param("tenantId") String tenantId,@Param("domainCode") String domainCode);
    Map<String,Object> findShadowObservation(@Param("tenantId") String tenantId,@Param("comparisonId") String comparisonId);
    List<Map<String,Object>> findShadowMismatchCases(@Param("tenantId") String tenantId,@Param("domainCode") String domainCode,@Param("status") String status,@Param("limit") int limit);
    Map<String,Object> findShadowMismatchCase(@Param("caseId") String caseId);
    int insertShadowMismatchCase(@Param("row") Map<String,Object> row);
    int updateShadowMismatchCase(@Param("row") Map<String,Object> row,@Param("expectedVersion") long expectedVersion);
    int insertShadowMismatchWaiver(@Param("row") Map<String,Object> row);
    Map<String,Object> findShadowMismatchWaiver(@Param("waiverId") String waiverId);
    int insertShadowRegressionEvidence(@Param("row") Map<String,Object> row);
    Map<String,Object> findShadowRegressionEvidence(@Param("evidenceId") String evidenceId);
    List<Map<String,Object>> findDomainReadinessEvidence(@Param("tenantId") String tenantId,@Param("domainCode") String domainCode,@Param("limit") int limit);
    String evaluateDomainReadiness(@Param("tenantId") String tenantId,@Param("domainCode") String domainCode,@Param("windowStartedAt") Instant windowStartedAt,@Param("windowEndedAt") Instant windowEndedAt,@Param("actorId") String actorId,@Param("correlationId") String correlationId,@Param("auditReason") String auditReason);
    Map<String,Object> findDomainReadinessEvidenceById(@Param("evidenceId") String evidenceId);
    List<Map<String,Object>> findPhase6EligibilityEvidence(@Param("tenantId") String tenantId,@Param("limit") int limit);
    String evaluatePhase6Eligibility(@Param("tenantId") String tenantId,@Param("actorId") String actorId,@Param("correlationId") String correlationId,@Param("auditReason") String auditReason);
    Map<String,Object> findPhase6EligibilityEvidenceById(@Param("evidenceId") String evidenceId);
    Map<String,Object> findShadowPipelineReadiness();
    Map<String,Object> findShadowStorageReadiness();
    List<Map<String,Object>> findShadowRetentionRuns(@Param("limit") int limit);
    String processShadowPipeline(@Param("workerId") String workerId,@Param("batchSize") int batchSize,@Param("actorId") String actorId,@Param("correlationId") String correlationId,@Param("auditReason") String auditReason);
    String runShadowRetention(@Param("actorId") String actorId,@Param("auditReason") String auditReason,@Param("correlationId") String correlationId);
    Map<String,Object> findShadowRetentionRun(@Param("runId") String runId);
    List<Map<String,Object>> findPhase5RuntimeCertificationEvidence(@Param("limit") int limit);
    String generatePhase5RuntimeCertificationEvidence(@Param("sourceVersion") String sourceVersion,@Param("postgresqlCleanStatus") String postgresqlCleanStatus,@Param("postgresqlUpgradeStatus") String postgresqlUpgradeStatus,@Param("applicationContextStatus") String applicationContextStatus,@Param("adminUiBuildStatus") String adminUiBuildStatus,@Param("playwrightStatus") String playwrightStatus,@Param("loadTestStatus") String loadTestStatus,@Param("pipelineStatus") String pipelineStatus,@Param("evidenceJson") String evidenceJson,@Param("actorId") String actorId,@Param("auditReason") String auditReason,@Param("correlationId") String correlationId);
    Map<String,Object> findPhase5RuntimeCertificationEvidenceById(@Param("evidenceId") String evidenceId);
    Map<String,Object> findRoleById(@Param("tenantId") String tenantId,@Param("roleId") String roleId);
    Map<String,Object> findRoleByCode(@Param("tenantId") String tenantId,@Param("roleCode") String roleCode);
    List<Map<String,Object>> findRolesByIds(@Param("tenantId") String tenantId,@Param("roleIds") List<String> roleIds);
    int insertRole(@Param("row") Map<String,Object> row);
    int updateRole(@Param("row") Map<String,Object> row,@Param("expectedVersion") long expectedVersion);
    List<Map<String,Object>> findRolePermissions(@Param("tenantId") String tenantId,@Param("roleIds") List<String> roleIds);
    int insertRolePermission(@Param("row") Map<String,Object> row);
    int deleteRolePermissions(@Param("tenantId") String tenantId,@Param("roleId") String roleId);
    Map<String,Object> findBindingById(@Param("tenantId") String tenantId,@Param("bindingId") String bindingId);
    List<Map<String,Object>> findEffectiveBindings(@Param("tenantId") String tenantId,@Param("principalKeys") List<String> principalKeys,@Param("at") Instant at);
    int insertBinding(@Param("row") Map<String,Object> row);
    int updateBinding(@Param("row") Map<String,Object> row,@Param("expectedVersion") long expectedVersion);
    long findPolicyVersion(@Param("tenantId") String tenantId);
    List<String> findActiveGroupIds(@Param("tenantId") String tenantId,@Param("userId") String userId,@Param("at") Instant at);
    List<String> findEffectiveDepartmentIds(@Param("tenantId") String tenantId,@Param("userId") String userId,@Param("at") Instant at);
    int insertDecisionAudit(@Param("row") Map<String,Object> row);
    int insertShadowDecision(@Param("row") Map<String,Object> row);
    int upsertShadowAggregate(@Param("row") Map<String,Object> row);

    List<String> findActiveUserIdsForGroup(@Param("tenantId") String tenantId,@Param("groupId") String groupId,@Param("at") Instant at);
    List<String> findActiveUserIdsForDepartment(@Param("tenantId") String tenantId,@Param("departmentId") String departmentId,@Param("at") Instant at);
    List<Map<String,Object>> findActiveSeparationOfDutiesRules(@Param("tenantId") String tenantId);
    boolean r7ScopesOverlap(@Param("tenantId") String tenantId,@Param("leftType") String leftType,@Param("leftId") String leftId,@Param("rightType") String rightType,@Param("rightId") String rightId);
    boolean r7ScopeContains(@Param("tenantId") String tenantId,@Param("containerType") String containerType,@Param("containerId") String containerId,@Param("candidateType") String candidateType,@Param("candidateId") String candidateId);
    Map<String,Object> findRbacApproval(@Param("tenantId") String tenantId,@Param("approvalId") String approvalId);
    List<Map<String,Object>> findRbacApprovals(@Param("tenantId") String tenantId,@Param("status") String status,@Param("limit") int limit);
    int insertRbacApproval(@Param("row") Map<String,Object> row);
    int updateRbacApproval(@Param("row") Map<String,Object> row,@Param("expectedVersion") long expectedVersion);
    int insertRbacChangeEvidence(@Param("row") Map<String,Object> row);
}
