package com.opensocket.aievent.core.uicapability.core;

import com.opensocket.aievent.core.resourceaccess.contract.ResourceAction;
import com.opensocket.aievent.core.resourceaccess.contract.ResourceType;
import com.opensocket.aievent.core.resourceaccess.contract.VisibilityLevel;
import com.opensocket.aievent.core.uicapability.contract.UiActionDefinition;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;

/** Generated from release/phase7a0-ui-action-catalog.json. Do not expose this complete map to browsers. */
public final class CanonicalUiActionCatalogResolver implements UiActionCatalogResolver {
    private final Map<String, ResolvedUiAction> actions;
    public CanonicalUiActionCatalogResolver() {
        Map<String, ResolvedUiAction> actions = new LinkedHashMap<>();
        register(actions, new UiActionDefinition("task.detail.view", "TASKS", "TASK", "task.read", VisibilityLevel.STANDARD, "RSC_PAGE_BOOTSTRAP", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("task.detail.update", "TASKS", "TASK", "task.update", VisibilityLevel.STANDARD, "RSC_PAGE_BOOTSTRAP", "MODERATE", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.UPDATE, true);
        register(actions, new UiActionDefinition("task.remediation.execute", "TASKS", "TASK", "task.update", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "MODERATE", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("task.retry.execute", "TASKS", "TASK", "task.update", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "MODERATE", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("task.cancel.execute", "TASKS", "TASK", "task.update", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "HIGH", "HIGH_RISK_MUTATION", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("task.reassign.execute", "TASKS", "TASK", "task.update", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "MODERATE", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("task.recovery.execute", "TASKS", "TASK", "task.update", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "HIGH", "HIGH_RISK_MUTATION", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("task.dead-letter.execute", "TASKS", "TASK", "task.update", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "HIGH", "HIGH_RISK_MUTATION", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("task.dead-letter.restore", "TASKS", "TASK", "task.update", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "HIGH", "HIGH_RISK_MUTATION", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("task.escalate.execute", "TASKS", "TASK", "task.update", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "MODERATE", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("task.issue-sync.retry", "TASKS", "TASK", "task.update", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "MODERATE", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("task.handoff.retry", "TASKS", "TASK", "task.update", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "HIGH", "SENSITIVE_CONTEXT_RELEASE", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("task.a2a-result.reconcile", "TASKS", "TASK", "task.update", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "HIGH", "CONFLICT_RESOLUTION", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("task.a2a-request.create", "A2A", "TASK", "a2a.request.create", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "MODERATE", "", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.CREATE, true);
        register(actions, new UiActionDefinition("task.attachment.read", "TASKS", "TASK_ATTACHMENT", "task.attachment.read", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("task.attachment.download", "TASKS", "TASK_ATTACHMENT", "task.attachment.download", VisibilityLevel.FULL, "RESOURCE_CONTEXT", "MODERATE", "SENSITIVE_DOWNLOAD", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.DOWNLOAD, false);
        register(actions, new UiActionDefinition("task.participant.manage", "TASKS", "TASK", "task.participant.manage", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "MODERATE", "", "RESOURCE_OWNER_OR_DEPARTMENT_ADMIN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("a2a.request.read", "A2A", "A2A_REQUEST", "a2a.request.read", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("a2a.request.create", "A2A", "A2A_REQUEST", "a2a.request.create", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "MODERATE", "", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.CREATE, true);
        register(actions, new UiActionDefinition("a2a.request.cancel", "A2A", "A2A_REQUEST", "a2a.request.cancel", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "HIGH", "HIGH_RISK_MUTATION", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("a2a.request.execute", "A2A", "A2A_REQUEST", "a2a.request.execute", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "HIGH", "HIGH_RISK_MUTATION", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("a2a.approval.read", "A2A", "A2A_APPROVAL", "a2a.approval.read", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("a2a.approval.approve", "A2A", "A2A_APPROVAL", "a2a.approval.approve", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "HIGH", "APPROVAL_ASSURANCE", "SEPARATION_OF_DUTIES", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.APPROVE, true);
        register(actions, new UiActionDefinition("a2a.approval.reject", "A2A", "A2A_APPROVAL", "a2a.approval.reject", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "MODERATE", "", "SEPARATION_OF_DUTIES", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.APPROVE, true);
        register(actions, new UiActionDefinition("a2a.context.preview", "A2A", "TASK_CONTEXT_SNAPSHOT", "a2a.context.preview", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("a2a.context.release", "A2A", "TASK_CONTEXT_SNAPSHOT", "a2a.context.release", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "HIGH", "SENSITIVE_CONTEXT_RELEASE", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("a2a.result.read", "A2A", "TASK_RESULT", "a2a.result.read", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("agent.pool.manage", "AGENTS", "AGENT_POOL", "agent.pool.manage", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "MODERATE", "", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("agent.runtime.diagnose", "AGENTS", "AGENT", "agent.runtime.diagnose", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("agent.credential.rotate", "AGENTS", "AGENT_CREDENTIAL_METADATA", "agent.credential.rotate", VisibilityLevel.SECRET_METADATA, "RESOURCE_CONTEXT", "CRITICAL", "CREDENTIAL_ROTATION", "DUAL_APPROVAL", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("integration.connection.read", "ISSUE_TRACKING", "ISSUE_CONNECTION", "integration.connection.read", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("integration.connection.manage", "ISSUE_TRACKING", "ISSUE_CONNECTION", "integration.connection.manage", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "HIGH", "INTEGRATION_ADMIN", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("integration.connection.test", "ISSUE_TRACKING", "ISSUE_CONNECTION", "integration.connection.test", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "MODERATE", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("integration.issue.read", "ISSUE_TRACKING", "TASK_ISSUE_LINK", "integration.issue.read", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("integration.issue.create", "ISSUE_TRACKING", "TASK_ISSUE_LINK", "integration.issue.create", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "MODERATE", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.CREATE, true);
        register(actions, new UiActionDefinition("integration.issue.comment", "ISSUE_TRACKING", "TASK_ISSUE_LINK", "integration.issue.comment", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "MODERATE", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.UPDATE, true);
        register(actions, new UiActionDefinition("integration.issue.conflict.read", "ISSUE_TRACKING", "ISSUE_CONFLICT", "integration.issue.conflict.read", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("integration.issue.conflict.resolve", "ISSUE_TRACKING", "ISSUE_CONFLICT", "integration.issue.conflict.resolve", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "HIGH", "CONFLICT_RESOLUTION", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("integration.issue.mapping.read", "ISSUE_TRACKING", "ISSUE_PROJECT_MAPPING", "integration.issue.mapping.read", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("integration.issue.mapping.update", "ISSUE_TRACKING", "ISSUE_PROJECT_MAPPING", "integration.issue.mapping.update", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "HIGH", "INTEGRATION_ADMIN", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.UPDATE, true);
        register(actions, new UiActionDefinition("integration.issue.credential.rotate", "ISSUE_TRACKING", "ISSUE_CREDENTIAL_METADATA", "integration.issue.credential.rotate", VisibilityLevel.SECRET_METADATA, "RESOURCE_CONTEXT", "CRITICAL", "CREDENTIAL_ROTATION", "DUAL_APPROVAL", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("identity.user.read", "IDENTITY_ACCESS", "USER", "identity.user.read", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("identity.user.create", "IDENTITY_ACCESS", "USER", "identity.user.create", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "MODERATE", "", "TENANT_ADMIN_POLICY", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.CREATE, true);
        register(actions, new UiActionDefinition("identity.user.update", "IDENTITY_ACCESS", "USER", "identity.user.update", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "MODERATE", "", "TENANT_ADMIN_POLICY", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.UPDATE, true);
        register(actions, new UiActionDefinition("identity.role.read", "IDENTITY_ACCESS", "ROLE", "identity.role.read", VisibilityLevel.STANDARD, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("identity.role.manage", "IDENTITY_ACCESS", "ROLE", "identity.role.manage", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "HIGH", "ROLE_ADMIN", "DUAL_APPROVAL", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("resource.scope.read", "IDENTITY_ACCESS", "TENANT", "resource.scope.read", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("resource.scope.grant", "IDENTITY_ACCESS", "TENANT", "resource.scope.grant", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "CRITICAL", "ACCESS_GRANT", "DUAL_APPROVAL", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("resource.scope.revoke", "IDENTITY_ACCESS", "TENANT", "resource.scope.revoke", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "CRITICAL", "ACCESS_REVOKE", "DUAL_APPROVAL", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("resource.deny.read", "IDENTITY_ACCESS", "TENANT", "resource.deny.read", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("resource.deny.create", "IDENTITY_ACCESS", "TENANT", "resource.deny.create", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "CRITICAL", "EXPLICIT_DENY", "DUAL_APPROVAL", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.CREATE, true);
        register(actions, new UiActionDefinition("resource.deny.revoke", "IDENTITY_ACCESS", "TENANT", "resource.deny.revoke", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "CRITICAL", "EXPLICIT_DENY", "DUAL_APPROVAL", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("resource.ownership.transfer", "IDENTITY_ACCESS", "TENANT", "resource.ownership.transfer", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "CRITICAL", "OWNERSHIP_TRANSFER", "DUAL_APPROVAL", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("resource.review.read", "IDENTITY_ACCESS", "TENANT", "resource.review.read", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("resource.review.manage", "IDENTITY_ACCESS", "TENANT", "resource.review.manage", VisibilityLevel.SENSITIVE, "RESOURCE_CONTEXT", "HIGH", "ACCESS_REVIEW", "SEPARATION_OF_DUTIES", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("resource.decision.explain", "IDENTITY_ACCESS", "TENANT", "resource.decision.explain", VisibilityLevel.SENSITIVE, "ADMIN_EXPLAIN", "MODERATE", "", "", "NONE", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("resource.release.read", "OPERATIONS", "TENANT", "resource.release.read", VisibilityLevel.SENSITIVE, "ENFORCEMENT_UNIT", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("resource.release.transition", "OPERATIONS", "TENANT", "resource.release.transition", VisibilityLevel.SENSITIVE, "ENFORCEMENT_UNIT", "CRITICAL", "ENFORCEMENT_CUTOVER", "DUAL_APPROVAL", "NONE", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("resource.release.rollback", "OPERATIONS", "TENANT", "resource.release.rollback", VisibilityLevel.SENSITIVE, "ENFORCEMENT_UNIT", "CRITICAL", "ENFORCEMENT_ROLLBACK", "DUAL_APPROVAL", "NONE", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("integration.issue.sync.retry", "ISSUE_TRACKING", "TASK_ISSUE_LINK", "integration.issue.retry", VisibilityLevel.STANDARD, "ISSUE_SYNC_QUEUE", "MODERATE", "", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("integration.issue.dead-letter.retry", "ISSUE_TRACKING", "ISSUE_DEAD_LETTER", "integration.issue.dead-letter.retry", VisibilityLevel.SENSITIVE, "ISSUE_DEAD_LETTER", "HIGH", "ISSUE_RECOVERY", "POLICY_DRIVEN", "NONE", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("agent.service-scope.assign", "AGENTS", "AGENT_SERVICE_SCOPE", "agent.manage", VisibilityLevel.SENSITIVE, "AGENT_SERVICE_SCOPE", "HIGH", "AGENT_GOVERNANCE", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("agent.runtime-binding.manage", "AGENTS", "AGENT", "agent.manage", VisibilityLevel.SENSITIVE, "AGENT_RUNTIME_BINDING", "HIGH", "AGENT_GOVERNANCE", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("agent.disable.execute", "AGENTS", "AGENT", "agent.manage", VisibilityLevel.SENSITIVE, "AGENT_GOVERNANCE", "HIGH", "AGENT_GOVERNANCE", "POLICY_DRIVEN", "NONE", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("agent.suspend.execute", "AGENTS", "AGENT", "agent.suspend", VisibilityLevel.SENSITIVE, "AGENT_GOVERNANCE", "CRITICAL", "AGENT_SECURITY", "DUAL_APPROVAL", "NONE", "ACTIVE"), ResourceAction.ActionKind.EXECUTE, true);
        register(actions, new UiActionDefinition("identity.role.bundle.read", "IDENTITY_ACCESS", "ROLE", "identity.role.read", VisibilityLevel.STANDARD, "ROLE_PERMISSION_BUNDLE", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("identity.role.bundle.manage", "IDENTITY_ACCESS", "ROLE", "identity.role_permission.manage", VisibilityLevel.SENSITIVE, "ROLE_PERMISSION_BUNDLE", "HIGH", "ROLE_ADMIN", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("permission.catalog.read", "IDENTITY_ACCESS", "ROLE", "permission.catalog.read", VisibilityLevel.STANDARD, "PERMISSION_CATALOG", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("permission.catalog.manage", "IDENTITY_ACCESS", "ROLE", "permission.catalog.manage", VisibilityLevel.SENSITIVE, "PERMISSION_CATALOG", "HIGH", "CATALOG_ADMIN", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("permission.catalog.publish", "IDENTITY_ACCESS", "ROLE", "permission.catalog.publish", VisibilityLevel.SENSITIVE, "PERMISSION_CATALOG_PUBLICATION", "CRITICAL", "CATALOG_PUBLICATION", "DUAL_APPROVAL", "NONE", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("resource.scope.approve", "RESOURCE_ACCESS", "TENANT", "resource.scope.approve", VisibilityLevel.SENSITIVE, "RESOURCE_SCOPE_LIFECYCLE", "CRITICAL", "RESOURCE_ACCESS_ADMIN", "DUAL_APPROVAL", "NONE", "ACTIVE"), ResourceAction.ActionKind.APPROVE, true);
        register(actions, new UiActionDefinition("resource.deny.approve", "RESOURCE_ACCESS", "TENANT", "resource.deny.approve", VisibilityLevel.SENSITIVE, "RESOURCE_DENY_LIFECYCLE", "CRITICAL", "RESOURCE_ACCESS_ADMIN", "DUAL_APPROVAL", "NONE", "ACTIVE"), ResourceAction.ActionKind.APPROVE, true);
        register(actions, new UiActionDefinition("resource.access-request.prepare", "RESOURCE_ACCESS", "TENANT", "resource.scope.read", VisibilityLevel.METADATA, "ACCESS_REQUEST_PREPARATION", "LOW", "", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("resource.access-review.decision", "RESOURCE_ACCESS", "TENANT", "resource.review.manage", VisibilityLevel.SENSITIVE, "ACCESS_REVIEW", "HIGH", "RESOURCE_ACCESS_ADMIN", "POLICY_DRIVEN", "NONE", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("resource.ownership.preview", "RESOURCE_ACCESS", "TENANT", "resource.ownership.transfer", VisibilityLevel.SENSITIVE, "OWNERSHIP_TRANSFER", "HIGH", "RESOURCE_ACCESS_ADMIN", "POLICY_DRIVEN", "NONE", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("resource.orphan.repair", "RESOURCE_ACCESS", "TENANT", "resource.orphan.repair", VisibilityLevel.SENSITIVE, "ORPHAN_REPAIR", "CRITICAL", "RESOURCE_ACCESS_ADMIN", "DUAL_APPROVAL", "NONE", "ACTIVE"), ResourceAction.ActionKind.MANAGE, true);
        register(actions, new UiActionDefinition("operations.workspace.read", "OPERATIONS", "TENANT", "audit.read", VisibilityLevel.METADATA, "OPERATIONS_WORKSPACE", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("task.export.prepare", "OPERATIONS", "TASK", "task.export", VisibilityLevel.SENSITIVE, "RESOURCE_EXPORT", "CRITICAL", "SENSITIVE_EXPORT", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXPORT, true);
        register(actions, new UiActionDefinition("issue.export.prepare", "OPERATIONS", "ISSUE_CONTEXT_SNAPSHOT", "integration.issue.export", VisibilityLevel.SENSITIVE, "RESOURCE_EXPORT", "CRITICAL", "SENSITIVE_EXPORT", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.EXPORT, true);
        register(actions, new UiActionDefinition("issue.attachment.read", "OPERATIONS", "ISSUE_ATTACHMENT", "integration.issue.attachment.read", VisibilityLevel.STANDARD, "ATTACHMENT_SECURITY", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("issue.attachment.download", "OPERATIONS", "ISSUE_ATTACHMENT", "integration.issue.attachment.download", VisibilityLevel.FULL, "ATTACHMENT_SECURITY", "CRITICAL", "SENSITIVE_DOWNLOAD", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.DOWNLOAD, false);
        register(actions, new UiActionDefinition("operations.background-job.read", "OPERATIONS", "TENANT", "audit.read", VisibilityLevel.SENSITIVE, "BACKGROUND_JOB_AUTHORIZATION", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("operations.bulk.preview", "OPERATIONS", "TENANT", "audit.read", VisibilityLevel.SENSITIVE, "BULK_OPERATION_PREVIEW", "MODERATE", "", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("operations.audit.read", "OPERATIONS", "TENANT", "audit.read", VisibilityLevel.SENSITIVE, "AUDIT_TIMELINE", "LOW", "", "", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        register(actions, new UiActionDefinition("operations.support-diagnostic.read", "OPERATIONS", "TENANT", "audit.read", VisibilityLevel.SENSITIVE, "SUPPORT_DIAGNOSTIC", "MODERATE", "", "POLICY_DRIVEN", "STANDARD_TEMPORARY", "ACTIVE"), ResourceAction.ActionKind.READ, false);
        this.actions = Map.copyOf(actions);
    }
    @Override public Optional<ResolvedUiAction> resolve(String uiActionId) {
        return Optional.ofNullable(actions.get(uiActionId));
    }
    public int size() { return actions.size(); }
    private static void register(Map<String, ResolvedUiAction> target, UiActionDefinition definition,
                                 ResourceAction.ActionKind kind, boolean sideEffecting) {
        ResourceType type = ResourceType.valueOf(definition.resourceType());
        ResolvedUiAction action = new ResolvedUiAction(definition, type,
                new ResourceAction(definition.canonicalPermissionCode(), kind, sideEffecting));
        if (target.put(definition.uiActionId(), action) != null) {
            throw new IllegalStateException("duplicate uiActionId: " + definition.uiActionId());
        }
    }
}
