'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { businessIssuesAdminApi, type BusinessIssueView } from '@/lib/api/domains/businessIssuesAdminApi';
import { RefreshButton } from '@/components/common/RefreshButton';
import { LoadingBox } from '@/components/common/LoadingBox';
import { EmptyState } from '@/components/common/EmptyState';
import { formatDateTime } from '@/lib/utils/format';
import { BeginnerGuideButton, OwnershipAccessCard } from '@/components/resource-scope/EnterpriseAccessUi';
import { RightDrawer } from '@/components/ui/RightDrawer';
import { SearchField } from '@/components/access-management/shared/beginnerUi';
import { useAuth } from '@/components/auth/AuthProvider';
import { accessManagementApi } from '@/lib/api/accessManagementApi';
import type { Department, Group } from '@/lib/iam/types';

function scopeKey(issue: BusinessIssueView): string { if(issue.ownerDepartmentId)return `DEPARTMENT:${issue.ownerDepartmentId}`; if(issue.ownerGroupId)return `GROUP:${issue.ownerGroupId}`; return issue.scopeStatus==='RESOLVED'?'TENANT':'UNRESOLVED'; }

export function BusinessIssueConsole(){
  const { activeTenantId: selectedTenantId } = useAuth();
  const emptyDepartmentPage = { items: [] as Department[], page: 0, size: 0, hasMore: false, totalCount: 0 };
  const emptyGroupPage = { items: [] as Group[], page: 0, size: 0, hasMore: false, totalCount: 0 };
  const [issues,setIssues]=useState<BusinessIssueView[]>([]); const [loading,setLoading]=useState(true);
  const [error,setError]=useState<string|null>(null); const [updated,setUpdated]=useState<string>();
  const [departments,setDepartments]=useState<Department[]>([]); const [groups,setGroups]=useState<Group[]>([]);
  const [query,setQuery]=useState(''); const [scopeFilter,setScopeFilter]=useState('ALL'); const [selected,setSelected]=useState<BusinessIssueView|null>(null);
  const departmentName=(id?:string|null)=>departments.find((item)=>item.departmentId===id)?.name??id??'Unknown Department';
  const groupName=(id?:string|null)=>groups.find((item)=>item.groupId===id)?.name??id??'Unknown Group';
  const ownership=(issue:BusinessIssueView)=>issue.ownerDepartmentId?`Department · ${departmentName(issue.ownerDepartmentId)}`:issue.ownerGroupId?`Group · ${groupName(issue.ownerGroupId)}`:issue.scopeStatus==='RESOLVED'?'Tenant-wide':'Scope unresolved';
  async function reload(){setLoading(true);setError(null);try{const [rows,departmentPage,groupPage]=await Promise.all([businessIssuesAdminApi.list(),selectedTenantId?accessManagementApi.departments(selectedTenantId,0,200,'','ACTIVE').catch(()=>emptyDepartmentPage):Promise.resolve(emptyDepartmentPage),selectedTenantId?accessManagementApi.groups(selectedTenantId,0,200,'','','ACTIVE').catch(()=>emptyGroupPage):Promise.resolve(emptyGroupPage)]);setIssues(rows);setDepartments(departmentPage.items??[]);setGroups(groupPage.items??[]);setUpdated(new Date().toISOString());}catch(e){setError(e instanceof Error?e.message:'Failed to load Business Issues.');}finally{setLoading(false);}}
  useEffect(()=>{void reload();},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const scopeOptions=useMemo(()=>{const m=new Map<string,string>();for(const issue of issues)m.set(scopeKey(issue),ownership(issue));return [...m.entries()].filter(([key])=>key!=='UNRESOLVED').sort((a,b)=>a[1].localeCompare(b[1]));},[issues,departments,groups]); // eslint-disable-line react-hooks/exhaustive-deps
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();return issues.filter((issue)=>(scopeFilter==='ALL'||scopeKey(issue)===scopeFilter)&&(!q||[issue.externalIssueKey,issue.externalIssueId,issue.taskId,issue.externalProjectId,issue.providerType,issue.issueStatus].some((v)=>String(v??'').toLowerCase().includes(q))));},[issues,query,scopeFilter]);
  return <main className="space-y-5">
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="text-xs font-black uppercase tracking-wide text-blue-700">Canonical scoped projection</div><h1 className="mt-1 text-2xl font-black text-slate-950">Business Issues</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-600">Review Jira/Redmine projections from one authorized list. Open the Issue in a side panel for Task links, ownership and access explanation instead of navigating through separate integration consoles.</p></div><div className="flex flex-wrap gap-2"><BeginnerGuideButton title="Business Issues in three steps" description="External tracker permissions never replace OpenDispatch authorization." steps={[{title:'Find the Issue',description:'Search by external key, Task, project or provider, and narrow to an accessible scope if needed.'},{title:'Open the Issue drawer',description:'Review Task origin, current operational collaboration and canonical ownership without leaving the list.'},{title:'Follow the nearby Task link',description:'If you need operational remediation, open the source Task directly. Jira/Redmine remains only the projection target.'}]} /><RefreshButton refreshing={loading} lastUpdatedAt={updated} onRefresh={()=>void reload()} /></div></div><div className="mt-5 grid gap-3 md:grid-cols-[minmax(0,1fr)_20rem]"><SearchField id="business-issue-search" value={query} onChange={setQuery} placeholder="Search issue key, Task, project or provider"/><select value={scopeFilter} onChange={(e)=>setScopeFilter(e.target.value)} className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm font-semibold"><option value="ALL">All accessible scopes</option>{scopeOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div></section>
    {error?<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-900">{error}</div>:null}
    {loading?<LoadingBox label="Loading authorized Business Issues..." />:null}
    {!loading&&visible.length===0?<EmptyState title="No Business Issues in this view" description="Try another accessible scope or search. Unresolved historical Issue ownership remains fail-closed until remediated." />:null}
    <section className="space-y-3">{visible.map(issue=><article key={issue.linkId} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black text-slate-950">{issue.externalIssueKey||issue.externalIssueId||'Business Issue'}</h2><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-800">{ownership(issue)}</span>{issue.providerType?<span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-700">{issue.providerType}</span>:null}</div><div className="mt-3 flex flex-wrap gap-3 text-sm text-slate-600"><span><b>Status:</b> {issue.issueStatus||issue.syncStatus||'—'}</span><span><b>Project:</b> {issue.externalProjectId||'—'}</span>{issue.updatedAt?<span><b>Updated:</b> {formatDateTime(issue.updatedAt)}</span>:null}</div></div><button type="button" onClick={()=>setSelected(issue)} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-black text-slate-700 hover:bg-slate-50">Open issue</button></div></article>)}</section>
    <RightDrawer open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.externalIssueKey||selected?.externalIssueId||'Business Issue'} description="OpenDispatch keeps the canonical Task scope authoritative even when the Issue is projected to Jira or Redmine." widthClassName="max-w-3xl">
      {selected?<div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-3"><div className="text-xs font-black text-slate-500">Status</div><div className="mt-1 font-black">{selected.issueStatus||selected.syncStatus||'—'}</div></div><div className="rounded-xl bg-slate-50 p-3"><div className="text-xs font-black text-slate-500">Provider / Project</div><div className="mt-1 font-black">{selected.providerType||'—'} · {selected.externalProjectId||'—'}</div></div></div><OwnershipAccessCard resourceType="TASK_ISSUE_LINK" resourceId={selected.linkId} permissionCode="integration.issue.link.read" purpose="Explain Business Issue access from the unified Issues workspace." primaryOwner={ownership(selected)} operationalScopes={[selected.requesterDepartmentId?`Requester · ${departmentName(selected.requesterDepartmentId)}`:null,selected.executorDepartmentId?`Executor · ${departmentName(selected.executorDepartmentId)}`:null].filter(Boolean) as string[]} provenance={`Primary scope snapshot from ${selected.scopeSourceType||'TASK'} ${selected.scopeSourceId||selected.taskId}${selected.scopeSourceVersion?` · v${selected.scopeSourceVersion}`:''}. Operational scope follows governed Task collaboration without changing the primary owner.`} managementHref="/access-management?workspace=access" managementLabel="Review access"/><div className="flex flex-wrap gap-2"><Link href={`/tasks/${encodeURIComponent(selected.taskId)}`} className="rounded-xl bg-blue-700 px-4 py-2 text-sm font-black text-white">Open source Task</Link><Link href="/settings/issue-tracking" className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-black text-slate-700">Issue tracking settings</Link></div><details className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-xs text-slate-600"><summary className="cursor-pointer font-black text-slate-800">Technical details for support</summary><div className="mt-3 space-y-1"><div>Link ID: {selected.linkId}</div><div>Task ID: {selected.taskId}</div><div>External Issue ID: {selected.externalIssueId||'—'}</div></div></details></div>:null}
    </RightDrawer>
  </main>;
}
