'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { LoadingBox } from '@/components/common/LoadingBox';
import { EmptyState } from '@/components/common/EmptyState';
import { RefreshButton } from '@/components/common/RefreshButton';
import { RightDrawer } from '@/components/ui/RightDrawer';
import { SearchField } from '@/components/access-management/shared/beginnerUi';
import { useUiEntitlements } from '@/lib/navigation/useUiEntitlements';
import { actionAllowed } from '@/lib/navigation/uiEntitlements';
import { formatDateTime } from '@/lib/utils/format';
import { securityIncidentApi, type ApplySecurityControlRequest, type SecurityIncidentCase, type SecurityIncidentDetails, type SecurityIncidentSeverity, type SecurityIncidentTargetType } from '@/lib/api/domains/securityIncidentApi';

const TARGET_ACTIONS:Record<SecurityIncidentTargetType,string[]>={
  CREDENTIAL:['THROTTLE','SUSPEND','REVOKE'], SERVICE_ACCOUNT:['THROTTLE','SUSPEND'], AGENT:['SUSPEND','REVOKE'], TASK:['HOLD','BLOCK_RETRY','CANCEL','REASSIGN','FORCE_FAIL'], SOURCE_SYSTEM:['QUARANTINE'],
};
function badge(value:string){return value==='CRITICAL'||value==='OPEN'?'bg-rose-50 text-rose-800':value==='HIGH'||value==='CONTAINED'?'bg-amber-50 text-amber-800':value==='RESOLVED'?'bg-emerald-50 text-emerald-800':'bg-slate-100 text-slate-700';}

export function SecurityIncidentConsole(){
  const searchParams=useSearchParams(); const entitlements=useUiEntitlements(); const canOperate=actionAllowed(entitlements.value,'issues-events.operate');
  const [items,setItems]=useState<SecurityIncidentCase[]>([]); const [selected,setSelected]=useState<SecurityIncidentDetails|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [updated,setUpdated]=useState<string>(); const [query,setQuery]=useState(''); const [status,setStatus]=useState(''); const [severity,setSeverity]=useState('');
  const [createOpen,setCreateOpen]=useState(false); const [title,setTitle]=useState(''); const [caseSeverity,setCaseSeverity]=useState<SecurityIncidentSeverity>('HIGH'); const [summary,setSummary]=useState(''); const [rootTaskId,setRootTaskId]=useState(''); const [sourceSystemId,setSourceSystemId]=useState('');
  const [targetType,setTargetType]=useState<SecurityIncidentTargetType>('CREDENTIAL'); const [targetId,setTargetId]=useState(''); const [action,setAction]=useState('THROTTLE'); const [limit,setLimit]=useState('60'); const [reason,setReason]=useState(''); const [releaseReason,setReleaseReason]=useState(''); const [resolutionReason,setResolutionReason]=useState(''); const [busy,setBusy]=useState(false);
  async function reload(){setLoading(true);setError(null);try{setItems(await securityIncidentApi.list(status||undefined,severity||undefined,200));setUpdated(new Date().toISOString());}catch(e){setError(e instanceof Error?e.message:'Failed to load Security Incidents.');}finally{setLoading(false);}}
  useEffect(()=>{void reload();},[status,severity]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{const taskId=searchParams.get('taskId');if(taskId){setRootTaskId(taskId);if(searchParams.get('action')==='open')setCreateOpen(true);}},[searchParams]);
  async function open(item:SecurityIncidentCase){try{setSelected(await securityIncidentApi.detail(item.caseId));}catch(e){setError(e instanceof Error?e.message:'Failed to open Security Incident.');}}
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();return items.filter(i=>!q||[i.caseId,i.title,i.summary,i.rootTaskId,i.sourceSystemId,i.ownerDepartmentId,i.ownerGroupId].some(v=>String(v??'').toLowerCase().includes(q)));},[items,query]);
  async function createCase(){if(!title.trim())return;setBusy(true);setError(null);try{const created=await securityIncidentApi.create({title:title.trim(),severity:caseSeverity,summary:summary.trim()||undefined,rootTaskId:rootTaskId.trim()||undefined,sourceSystemId:sourceSystemId.trim()||undefined});setCreateOpen(false);setTitle('');setSummary('');setRootTaskId('');setSourceSystemId('');await reload();await open(created);}catch(e){setError(e instanceof Error?e.message:'Failed to create Security Incident.');}finally{setBusy(false);}}
  async function applyControl(){if(!selected||!targetId.trim()||!reason.trim())return;setBusy(true);setError(null);try{const payload:ApplySecurityControlRequest={targetType,targetId:targetId.trim(),action:action as ApplySecurityControlRequest['action'],reason:reason.trim()};if(action==='THROTTLE')payload.limitPerMinute=Math.max(1,Number(limit)||1);setSelected(await securityIncidentApi.apply(selected.incident.caseId,payload));setReason('');await reload();}catch(e){setError(e instanceof Error?e.message:'Containment action failed.');}finally{setBusy(false);}}
  async function release(controlId:string){if(!selected||!releaseReason.trim())return;setBusy(true);try{setSelected(await securityIncidentApi.release(selected.incident.caseId,controlId,releaseReason.trim()));setReleaseReason('');await reload();}catch(e){setError(e instanceof Error?e.message:'Failed to release control.');}finally{setBusy(false);}}
  async function resolve(){if(!selected||!resolutionReason.trim())return;setBusy(true);try{await securityIncidentApi.resolve(selected.incident.caseId,resolutionReason.trim());setResolutionReason('');setSelected(await securityIncidentApi.detail(selected.incident.caseId));await reload();}catch(e){setError(e instanceof Error?e.message:'Failed to resolve case.');}finally{setBusy(false);}}
  function selectTarget(next:SecurityIncidentTargetType){setTargetType(next);setAction(TARGET_ACTIONS[next][0]);}
  return <main className="space-y-5">
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="text-xs font-black uppercase tracking-wide text-rose-700">Governed containment workspace</div><h1 className="mt-1 text-2xl font-black text-slate-950">Security Incidents</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-600">Investigate provenance and apply the smallest safe blast radius. Controls only narrow existing authority; they never create RBAC permission.</p></div><div className="flex gap-2">{canOperate?<button type="button" onClick={()=>setCreateOpen(true)} className="rounded-xl bg-rose-700 px-4 py-2 text-sm font-black text-white">Open incident</button>:null}<RefreshButton refreshing={loading} lastUpdatedAt={updated} onRefresh={()=>void reload()}/></div></div><div className="mt-5 grid gap-3 md:grid-cols-[minmax(0,1fr)_12rem_12rem]"><SearchField id="security-incident-search" value={query} onChange={setQuery} placeholder="Search case, Task, Source System or ownership"/><select className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm font-semibold" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All status</option><option>OPEN</option><option>CONTAINED</option><option>RESOLVED</option></select><select className="rounded-xl border border-slate-300 px-3 py-2.5 text-sm font-semibold" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All severity</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></div></section>
    {error?<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-900">{error}</div>:null}{loading?<LoadingBox label="Loading governed Security Incidents..."/>:null}{!loading&&!visible.length?<EmptyState title="No Security Incidents in this view" description="Open a case from suspicious Task, Credential, Agent or Source System evidence when containment is required."/>:null}
    <section className="space-y-3">{visible.map(item=><article key={item.caseId} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black text-slate-950">{item.title}</h2><span className={`rounded-full px-3 py-1 text-xs font-black ${badge(item.severity)}`}>{item.severity}</span><span className={`rounded-full px-3 py-1 text-xs font-black ${badge(item.status)}`}>{item.status}</span></div><div className="mt-3 flex flex-wrap gap-3 text-sm text-slate-600"><span><b>Case:</b> {item.caseId}</span>{item.rootTaskId?<span><b>Root Task:</b> {item.rootTaskId}</span>:null}{item.sourceSystemId?<span><b>Source:</b> {item.sourceSystemId}</span>:null}<span><b>Owner:</b> {item.ownerDepartmentId||'Tenant'}{item.ownerGroupId?` / ${item.ownerGroupId}`:''}</span></div></div><button type="button" onClick={()=>void open(item)} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-black">Investigate</button></div></article>)}</section>
    <RightDrawer open={createOpen} onClose={()=>setCreateOpen(false)} title="Open Security Incident" description="Link the case to canonical evidence. Ownership is server-derived from the linked resource."><div className="space-y-3"><input className="w-full rounded-xl border border-slate-300 px-3 py-2" placeholder="Incident title" value={title} onChange={e=>setTitle(e.target.value)}/><select className="w-full rounded-xl border border-slate-300 px-3 py-2" value={caseSeverity} onChange={e=>setCaseSeverity(e.target.value as SecurityIncidentSeverity)}><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><textarea className="w-full rounded-xl border border-slate-300 px-3 py-2" placeholder="Summary" value={summary} onChange={e=>setSummary(e.target.value)}/><input className="w-full rounded-xl border border-slate-300 px-3 py-2" placeholder="Root Task ID (recommended)" value={rootTaskId} onChange={e=>setRootTaskId(e.target.value)}/><input className="w-full rounded-xl border border-slate-300 px-3 py-2" placeholder="Source System ID (optional)" value={sourceSystemId} onChange={e=>setSourceSystemId(e.target.value)}/><button disabled={busy||!title.trim()} onClick={()=>void createCase()} className="w-full rounded-xl bg-rose-700 px-4 py-2 font-black text-white disabled:opacity-50">Create governed case</button></div></RightDrawer>
    <RightDrawer open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.incident.title||'Security Incident'} description="Contain at Credential or Task first when possible; escalate only when evidence justifies a wider blast radius." widthClassName="max-w-4xl">{selected?<div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2"><Info label="Status" value={`${selected.incident.severity} · ${selected.incident.status}`}/><Info label="Ownership" value={`${selected.incident.ownerDepartmentId||'Tenant'}${selected.incident.ownerGroupId?` / ${selected.incident.ownerGroupId}`:''}`}/><Info label="Root Task" value={selected.incident.rootTaskId||'—'}/><Info label="Source System" value={selected.incident.sourceSystemId||'—'}/></div><div className="flex flex-wrap gap-2">{selected.incident.rootTaskId?<Link href={`/tasks/${encodeURIComponent(selected.incident.rootTaskId)}`} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-black">Open root Task</Link>:null}{canOperate&&selected.incident.status!=='RESOLVED'?<><input value={resolutionReason} onChange={e=>setResolutionReason(e.target.value)} placeholder="Required resolution reason" className="rounded-xl border border-emerald-200 px-3 py-2 text-sm"/><button onClick={()=>void resolve()} disabled={busy||!resolutionReason.trim()} className="rounded-xl border border-emerald-300 px-3 py-2 text-sm font-black text-emerald-800 disabled:opacity-50">Resolve case</button></>:null}</div>
      {canOperate&&selected.incident.status!=='RESOLVED'?<section className="rounded-2xl border border-rose-200 bg-rose-50 p-4"><h3 className="font-black text-rose-950">Apply containment</h3><p className="mt-1 text-xs text-rose-800">Use the narrowest target that stops the risk. Credential ownership is resolved server-side; operators never provide a parent identity for authorization.</p><div className="mt-3 grid gap-2 md:grid-cols-2"><select className="rounded-xl border border-rose-200 bg-white px-3 py-2" value={targetType} onChange={e=>selectTarget(e.target.value as SecurityIncidentTargetType)}>{Object.keys(TARGET_ACTIONS).map(v=><option key={v}>{v}</option>)}</select><select className="rounded-xl border border-rose-200 bg-white px-3 py-2" value={action} onChange={e=>setAction(e.target.value)}>{TARGET_ACTIONS[targetType].map(v=><option key={v}>{v}</option>)}</select><input className="rounded-xl border border-rose-200 px-3 py-2" placeholder="Target ID" value={targetId} onChange={e=>setTargetId(e.target.value)}/>{action==='THROTTLE'?<input type="number" min={1} className="rounded-xl border border-rose-200 px-3 py-2" placeholder="Requests / minute" value={limit} onChange={e=>setLimit(e.target.value)}/>:null}<input className="rounded-xl border border-rose-200 px-3 py-2 md:col-span-2" placeholder="Required operator reason" value={reason} onChange={e=>setReason(e.target.value)}/></div><button disabled={busy||!targetId.trim()||!reason.trim()} onClick={()=>void applyControl()} className="mt-3 rounded-xl bg-rose-700 px-4 py-2 text-sm font-black text-white disabled:opacity-50">Apply control</button></section>:null}
      <section><h3 className="font-black text-slate-950">Containment controls</h3><div className="mt-2 space-y-2">{selected.controls.length?selected.controls.map(c=><div key={c.controlId} className="rounded-xl border border-slate-200 p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><b>{c.controlType} · {c.targetType} · {c.targetId}</b><span>{c.status}</span></div><p className="mt-1 text-slate-600">{c.reason}{c.limitPerMinute?` · ${c.limitPerMinute}/min`:''}</p>{canOperate&&c.status==='ACTIVE'?<div className="mt-2 flex flex-wrap gap-2"><input value={releaseReason} onChange={e=>setReleaseReason(e.target.value)} placeholder="Required release reason" className="rounded-lg border border-slate-300 px-2 py-1 text-xs"/><button disabled={!releaseReason.trim()||busy} onClick={()=>void release(c.controlId)} className="text-xs font-black text-blue-700 disabled:opacity-50">Release control</button></div>:null}</div>):<p className="text-sm text-slate-500">No containment controls.</p>}</div></section>
      <section><h3 className="font-black text-slate-950">Immutable control evidence</h3><div className="mt-2 space-y-2">{selected.actions.map(a=><div key={a.actionId} className="rounded-xl bg-slate-50 p-3 text-xs text-slate-700"><b>{a.actionType} · {a.targetType} · {a.targetId}</b><div className="mt-1">{formatDateTime(a.occurredAt)} · Actor {a.actorId}</div><div className="mt-1">{a.reason}</div>{a.authorizationDecisionId?<div className="mt-1 font-mono">Decision {a.authorizationDecisionId}</div>:null}</div>)}</div></section></div>:null}</RightDrawer>
  </main>;
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><div className="text-xs font-black text-slate-500">{label}</div><div className="mt-1 break-all font-black text-slate-900">{value}</div></div>;}
