package com.opensocket.aievent.core.dispatch;

public enum RedispatchFailureType {
    AGENT_DISCONNECTED,
    RUNTIME_UNAUTHORIZED,
    CAPACITY_EXCEEDED,
    TEMPORARY_NETWORK_ERROR,
    BUSINESS_VALIDATION_FAILED,
    AGENT_EXECUTION_FAILED_RETRYABLE,
    AGENT_EXECUTION_FAILED_NON_RETRYABLE,
    MAX_RETRY_EXCEEDED,
    GOVERNANCE_REVOKED_DURING_EXECUTION,
    STALE_CALLBACK_REJECTED,
    UNKNOWN
}
