'use client';

import Link from 'next/link';
import type { ReactNode } from 'react';
import { ErrorNotice, Panel, SuccessNotice, TenantRequired } from '../ui';
import { AddPersonWizard } from './AddPersonWizard';
import { EffectiveAccessExplanation } from './EffectiveAccessExplanation';
import { AuditReasonSelector, ContextLink, FieldLabel, HierarchySelectField, HumanStatus, MultiSelectCards, SearchField, SelectField, isAuditReasonValid } from '../shared/beginnerUi';
import { WorkspaceModal } from '../shared/workspaceUi';
import { GuidedEmptyState, ReadOnlyBoundary, TechnicalDetails } from '../shared/acceptanceUi';
import type { Membership, UserAccessOverview, UserInvitationStatus, PeopleBulkActionResult } from '@/lib/iam/types';
import { usePeopleWorkspaceController, type DetailTab, type BulkAction } from './usePeopleWorkspaceController';
import { generateTemporaryPassword } from '@/lib/iam/temporaryPassword';

export function PeopleWorkspace() {
  const controller = usePeopleWorkspaceController();
  if (controller.mode === 'tenant-required') return <TenantRequired />;
  if (controller.mode === 'add-person') return <AddPersonWizard tenantId={controller.scopeTenantId} tenantName={controller.tenantName} departments={controller.departments} groups={controller.groups} roles={controller.roles} onCancel={() => controller.setShowAddPerson(false)} onComplete={controller.handleOnboardingComplete} />;
  const { scopeTenantId, tenantName, people, departments, groups, roles, filters, nextCursor, hasMore, selectedId, overview, invitation, federationLinks, federationProviders, linkOpen, linkProviderId, linkSubject, linkUpstreamEmail, linkReason, unlinkTarget, tab, selectedIds, bulkAction, bulkOpen, bulkDepartmentId, bulkGroupIds, bulkResult, editOpen, editDisplayName, editEmail, organizationOpen, removeOpen, ownershipTransferOpen, ownershipSearch, ownershipCandidates, ownershipTargetId, ownershipReason, ownershipTransferResult, pendingSecurityAction, credentialDeliveryMethod, passwordResetMode, temporaryPassword, confirmTemporaryPassword, oneTimeSetupUrl, primaryDepartmentDraft, groupDraft, groupSearch, actionReason, loading, detailLoading, busy, error, notice, membershipByUser, selected, tenantMembership, departmentMemberships, groupMemberships, readiness, primaryDepartmentName, groupNames, responsibilityNames, canAssignAccess, canCreatePeople, canUpdatePeople, canTransferMachineOwnership, canManageMembership, canManageTenantMembership, canViewFederation, canManageFederation, manageableDepartmentOptions, manageableGroupOptions, hasAppliedFilters, filteredGroupOptions, setFilters, setSelectedIds, setShowAddPerson, setBulkAction, setBulkOpen, setBulkDepartmentId, setBulkGroupIds, setBulkResult, setEditOpen, setEditDisplayName, setEditEmail, setOrganizationOpen, setRemoveOpen, setOwnershipTransferOpen, setOwnershipSearch, setOwnershipCandidates, setOwnershipTargetId, setOwnershipReason, setOwnershipTransferResult, setPendingSecurityAction, setCredentialDeliveryMethod, setPasswordResetMode, setTemporaryPassword, setConfirmTemporaryPassword, setOneTimeSetupUrl, setPrimaryDepartmentDraft, setGroupDraft, setGroupSearch, setActionReason, setTab, setLinkOpen, setLinkProviderId, setLinkSubject, setLinkUpstreamEmail, setLinkReason, setUnlinkTarget, loadPeople, searchOwnershipReceivers, transferMachineOwnership, applyFilters, clearFilters, selectPerson, openExternalLink, createExternalLink, confirmUnlink, openEditPerson, openOrganizationEditor, saveOrganizationRelationships, removePersonFromTenant, savePersonProfile, securityActionTier, securityActionLabel, openSecurityAction, runPersonAction, changeMembershipStatus, bulkAuditTier, organizationBulkAction, bulkTargetValid, executeBulkAction } = controller;
  return (
    <div className="space-y-5">
      <ErrorNotice message={error} />
      <SuccessNotice message={notice} />
      <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
        <div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between">
          <div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-700">People</p><h2 className="mt-1 text-xl font-black text-slate-950">People in {tenantName}</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-600">Search and filter on the server, manage workspace membership from the same person record, and use governed bulk actions for common administration work.</p></div>
          {canCreatePeople ? <button type="button" onClick={() => setShowAddPerson(true)} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-black text-white">+ Add person</button> : <ReadOnlyBoundary description="You can inspect People within your effective scope, but you cannot create or admit a Person in this workspace." />}
        </div>
        <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
          <FieldLabel htmlFor="people-text" label="Search"><SearchField id="people-text" value={filters.text} onChange={(value) => setFilters((current) => ({ ...current, text: value }))} placeholder="Name, username or email" /></FieldLabel>
          <FieldLabel htmlFor="people-account-status" label="Account status"><SelectField id="people-account-status" value={filters.accountStatus} onChange={(value) => setFilters((current) => ({ ...current, accountStatus: value }))} options={[{ value: 'ACTIVE', label: 'Ready / active' }, { value: 'PENDING_ACTIVATION', label: 'Invitation pending' }, { value: 'PASSWORD_RESET_REQUIRED', label: 'Password setup required' }, { value: 'MFA_ENROLLMENT_REQUIRED', label: 'MFA setup required' }, { value: 'LOCKED', label: 'Locked' }, { value: 'SUSPENDED', label: 'Suspended' }, { value: 'DISABLED', label: 'Disabled' }]} placeholder="All account statuses" /></FieldLabel>
          <FieldLabel htmlFor="people-signin-state" label="Sign-in readiness"><SelectField id="people-signin-state" value={filters.signInState} onChange={(value) => setFilters((current) => ({ ...current, signInState: value }))} options={[{ value: 'READY', label: 'Local sign-in ready' }, { value: 'SSO_MANAGED', label: 'Enterprise SSO ready' }, { value: 'SETUP_REQUIRED', label: 'Password / activation required' }, { value: 'MFA_REQUIRED', label: 'MFA enrollment required' }, { value: 'LOCKED', label: 'Locked' }, { value: 'SUSPENDED', label: 'Suspended' }, { value: 'DISABLED', label: 'Disabled' }]} placeholder="All sign-in states" /></FieldLabel>
          <FieldLabel htmlFor="people-membership-status" label="Workspace membership"><SelectField id="people-membership-status" value={filters.membershipStatus} onChange={(value) => setFilters((current) => ({ ...current, membershipStatus: value }))} options={[{ value: 'ACTIVE', label: 'Active' }, { value: 'INVITED', label: 'Invited' }, { value: 'SUSPENDED', label: 'Suspended' }, { value: 'REMOVED', label: 'Removed' }]} placeholder="All membership statuses" /></FieldLabel>
          <FieldLabel htmlFor="people-department" label="Department"><SelectField id="people-department" value={filters.departmentId} onChange={(value) => setFilters((current) => ({ ...current, departmentId: value }))} options={[{ value: '__UNASSIGNED__', label: 'Unassigned' }, ...departments.map((item) => ({ value: item.departmentId, label: item.name }))]} placeholder="All Departments" /></FieldLabel>
          <FieldLabel htmlFor="people-group" label="Group"><SelectField id="people-group" value={filters.groupId} onChange={(value) => setFilters((current) => ({ ...current, groupId: value }))} options={groups.map((item) => ({ value: item.groupId, label: item.name }))} placeholder="All Groups" /></FieldLabel>
          <FieldLabel htmlFor="people-responsibility" label="Responsibility"><SelectField id="people-responsibility" value={filters.roleId} onChange={(value) => setFilters((current) => ({ ...current, roleId: value }))} options={roles.filter((item) => item.status === 'ACTIVE').map((item) => ({ value: item.roleId, label: item.roleName }))} placeholder="All responsibilities" /></FieldLabel>
          <div className="flex items-end gap-2 md:col-span-2"><button type="button" onClick={applyFilters} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white">Apply filters</button><button type="button" onClick={clearFilters} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-black text-slate-700">Clear</button></div>
        </div>
      </section>

      <div className="grid gap-5 xl:grid-cols-[minmax(360px,.8fr)_minmax(0,1.2fr)]">
        <Panel title="People directory" description="Results use cursor pagination and retain the selected person in the URL.">
          {selectedIds.length ? <div className="mb-3 flex flex-wrap items-center justify-between gap-2 rounded-2xl border border-blue-200 bg-blue-50 p-3"><p className="text-sm font-black text-blue-950">{selectedIds.length} selected</p><button type="button" onClick={() => { setBulkDepartmentId(''); setBulkGroupIds([]); setActionReason(organizationBulkAction ? 'Organization restructuring' : bulkAction === 'RESEND_INVITATION' ? 'New employee onboarding' : bulkAction === 'REVOKE_SESSIONS' ? '' : 'Security remediation'); setBulkResult(null); setBulkOpen(true); }} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-black text-white">Bulk action</button></div> : null}
          <div className="space-y-2">
            {people.map((person) => {
              const membership = membershipByUser.get(person.userId);
              const checked = selectedIds.includes(person.userId);
              return <div key={person.userId} className={`flex gap-3 rounded-2xl border p-3 ${selectedId === person.userId ? 'border-blue-500 bg-blue-50' : 'border-slate-200 bg-white'}`}><input type="checkbox" aria-label={`Select ${person.displayName}`} checked={checked} onChange={() => setSelectedIds((current) => checked ? current.filter((id) => id !== person.userId) : [...current, person.userId])} className="mt-1 size-4"/><button type="button" onClick={() => selectPerson(person.userId)} className="min-w-0 flex-1 text-left"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-black text-slate-950">{person.displayName}</p><p className="mt-1 truncate text-xs text-slate-500">{person.username}{person.email ? ` · ${person.email}` : ''}</p><div className="mt-2 flex flex-wrap gap-1.5"><span className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-2 py-1 text-xs font-black uppercase tracking-wide text-slate-700">Account <HumanStatus value={person.status} /></span><span className="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2 py-1 text-xs font-black uppercase tracking-wide text-blue-800">Sign-in <HumanStatus value={person.signInState || person.status} /></span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-black uppercase tracking-wide text-slate-600">Workspace {membership?.status?.replaceAll('_',' ') ?? 'unknown'}</span><span className={`rounded-full px-2 py-1 text-xs font-black uppercase tracking-wide ${person.accessReadiness === 'READY' ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-800'}`}>Access {person.responsibilitySummary || person.accessReadiness?.replaceAll('_',' ') || 'NONE'}</span></div></div></div></button></div>;
            })}
            {!loading && people.length === 0 ? hasAppliedFilters ? <GuidedEmptyState title="No people match these filters" description="The directory is scoped by your current Tenant and authorization. No visible Person matches all selected filters." nextStep="Clear filters, then narrow the directory one filter at a time." primaryAction={<button type="button" onClick={clearFilters} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white">Clear filters</button>} /> : <GuidedEmptyState title="No people yet" description="Add the first Person to this workspace before assigning organization, responsibilities or sign-in setup." nextStep={canCreatePeople ? 'Create a Person, then confirm Department / Group placement and sign-in readiness.' : 'A People administrator must add the first Person before this directory contains records.'} primaryAction={canCreatePeople ? <button type="button" onClick={() => setShowAddPerson(true)} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-black text-white">Add first person</button> : undefined} /> : null}
            {loading ? <p className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">Loading people…</p> : null}
            {hasMore ? <button type="button" disabled={loading} onClick={() => { void loadPeople(nextCursor, true); }} className="w-full rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-black text-slate-700 disabled:opacity-50">Load more</button> : null}
          </div>
        </Panel>

        <Panel title={selected?.displayName ?? 'Person details'} description={selected ? `${selected.username}${selected.email ? ` · ${selected.email}` : ''}` : 'Select a person from the directory.'} actions={selected ? <div className="flex flex-wrap gap-2">{canUpdatePeople ? <button type="button" onClick={openEditPerson} className="rounded-xl border border-slate-300 px-3 py-2 text-xs font-black text-slate-800">Edit person</button> : null}{canManageMembership ? <button type="button" onClick={openOrganizationEditor} className="rounded-xl border border-blue-300 px-3 py-2 text-xs font-black text-blue-800">Change organization</button> : null}{canManageTenantMembership ? <button type="button" onClick={() => { setActionReason(''); setRemoveOpen(true); }} className="rounded-xl border border-rose-300 px-3 py-2 text-xs font-black text-rose-800">Remove from workspace…</button> : null}{canAssignAccess ? <Link href={`/admin/tenants/${encodeURIComponent(scopeTenantId)}/access?principalType=USER&principalId=${encodeURIComponent(selected.userId)}`} className="rounded-xl bg-slate-950 px-3 py-2 text-xs font-black text-white">Assign responsibility</Link> : null}</div> : undefined}>
          {!selected ? <GuidedEmptyState title="Choose a person" description="Select someone from the directory to review workspace membership, organization, responsibilities and authentication readiness in one place." nextStep="Use Search or filters when the directory is large; the selected Person remains in the URL for safe handoff." /> : <div>
            <div className="flex flex-wrap gap-2 border-b border-slate-200 pb-3" role="tablist" aria-label="Person details">{(['OVERVIEW','MEMBERSHIP','ORGANIZATION','ACCESS','SECURITY'] as DetailTab[]).map((item) => <button key={item} type="button" role="tab" aria-selected={tab === item} onClick={() => setTab(item)} className={`rounded-xl px-3 py-2 text-xs font-black ${tab === item ? 'bg-blue-700 text-white' : 'bg-slate-100 text-slate-700'}`}>{item[0]}{item.slice(1).toLowerCase()}</button>)}</div>
            {detailLoading ? <p className="mt-4 rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">Loading person details…</p> : null}
            {!detailLoading && tab === 'OVERVIEW' ? <div className="mt-4 space-y-4">
              <SignInReadinessPanel readiness={readiness} invitation={invitation} onOpenSecurity={() => setTab('SECURITY')} />
              <div className="grid gap-3 md:grid-cols-2">
                <InfoCard label="Sign-in readiness" value={<HumanStatus value={readiness?.signInState ?? selected.signInState ?? selected.status} />} />
                <InfoCard label="Authentication" value={readiness?.authenticationMethod === 'LOCAL' ? 'Local account' : readiness?.authenticationMethod || selected.authenticationMethod || 'Local account'} />
                <InfoCard label="Account status" value={<HumanStatus value={selected.status} />} />
                <InfoCard label="Workspace membership" value={tenantMembership ? <HumanStatus value={tenantMembership.status} /> : 'Not found'} />
                <InfoCard label="Workspace access readiness" value={<HumanStatus value={selected.accessReadiness || (overview?.effectiveAccess.permissions.length ? 'READY' : 'NO_RESPONSIBILITY')} />} />
                <InfoCard label="Password" value={readiness ? humanPasswordState(readiness.passwordState) : 'Unavailable'} />
                <InfoCard label="MFA" value={readiness ? humanMfaState(readiness.mfaState, readiness.mfaType) : 'Unavailable'} />
                <InfoCard label="Last successful sign-in" value={readiness?.lastSuccessfulLogin ? new Date(readiness.lastSuccessfulLogin).toLocaleString() : 'Never'} />
                <InfoCard label="Account source" value={selected.creationMode.replaceAll('_',' ')} />
              </div>
              {(selected.accessReadiness && selected.accessReadiness !== 'READY') || (!selected.accessReadiness && !(overview?.effectiveAccess.permissions.length)) ? <GuidedEmptyState title={selected.accessReadiness === 'NO_EFFECTIVE_PERMISSION' ? 'Responsibility has no effective permission' : 'No application responsibility assigned'} description={selected.accessReadiness === 'NO_EFFECTIVE_PERMISSION' ? 'A Responsibility relationship exists, but it currently produces no effective business permission for this Person.' : 'The identity and workspace membership are valid, but this Person has no business workspace access. My Account remains available for identity self-service.'} nextStep={canAssignAccess ? 'Assign an appropriate Responsibility, then review Effective UI Access before handoff.' : 'Ask an Access administrator to assign a Responsibility.'} primaryAction={canAssignAccess ? <Link href={`/admin/tenants/${encodeURIComponent(scopeTenantId)}/access?principalType=USER&principalId=${encodeURIComponent(selected.userId)}`} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white">Assign responsibility</Link> : undefined} tone="warning" /> : null}
              <section className="rounded-2xl border border-slate-200 bg-white p-4">
                <div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-slate-950">Work & access</h3><p className="mt-1 text-xs leading-5 text-slate-500">Common relationships are shown here so you can manage them next to the person instead of searching for another administration page.</p></div></div>
                <div className="mt-4 divide-y divide-slate-100">
                  <NearbyField label="Department" value={primaryDepartmentName} action={canManageMembership ? 'Change' : 'Review'} onClick={() => canManageMembership ? openOrganizationEditor() : setTab('ORGANIZATION')} />
                  <NearbyField label="Groups" value={groupNames.length ? groupNames.slice(0, 3).join(', ') + (groupNames.length > 3 ? ` +${groupNames.length - 3}` : '') : 'No Groups'} action={canManageMembership ? 'Change' : 'Review'} onClick={() => canManageMembership ? openOrganizationEditor() : setTab('ORGANIZATION')} />
                  <NearbyField label="Responsibilities" value={responsibilityNames.length ? responsibilityNames.slice(0, 3).join(', ') + (responsibilityNames.length > 3 ? ` +${responsibilityNames.length - 3}` : '') : 'No effective responsibilities'} action="Review" onClick={() => setTab('ACCESS')} />
                  <NearbyField label="Sign-in security" value={readiness?.signInReady ? 'Ready' : 'Setup required'} action="Review" onClick={() => setTab('SECURITY')} />
                </div>
              </section>
            </div> : null}
            {!detailLoading && tab === 'MEMBERSHIP' ? <div className="mt-4 space-y-4"><section className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-black text-slate-950">Workspace membership</h3><p className="mt-1 text-xs text-slate-500">Source: {tenantMembership?.role || 'Unknown'}{tenantMembership?.employeeId ? ` · Employee ${tenantMembership.employeeId}` : ''}</p></div>{tenantMembership ? <HumanStatus value={tenantMembership.status} /> : null}</div>{tenantMembership ? <dl className="mt-4 grid gap-3 sm:grid-cols-2"><Definition label="Sign-in home workspace" value={tenantMembership.primary ? 'Yes' : 'No'} /><Definition label="Effective" value={new Date(tenantMembership.effectiveAt).toLocaleString()} /><Definition label="Expires" value={tenantMembership.expiresAt ? new Date(tenantMembership.expiresAt).toLocaleString() : 'No planned expiry'} /><Definition label="Employee / contractor number" value={tenantMembership.employeeId || 'Not set'} /></dl> : <GuidedEmptyState title="No active workspace membership" description="This global Person exists, but no workspace membership is available here." nextStep={canManageTenantMembership ? 'Re-admit the Person through Add Person so previous Department, Group and direct Responsibility relationships do not reactivate automatically.' : 'Ask a workspace membership administrator to re-admit this Person.'} tone="warning" />}{tenantMembership ? <TechnicalDetails className="mt-4"><p className="break-all">Membership ID: {tenantMembership.membershipId}</p></TechnicalDetails> : null}<div className="mt-4"><AuditReasonSelector idPrefix="membership-action" value={actionReason} onChange={setActionReason} tier="ELEVATED" /></div>{tenantMembership && canManageTenantMembership ? <div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={() => { void changeMembershipStatus('ACTIVE'); }} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-black text-white">Activate</button><button type="button" disabled={busy} onClick={() => { void changeMembershipStatus('SUSPENDED'); }} className="rounded-lg bg-amber-700 px-3 py-2 text-xs font-black text-white">Suspend</button><button type="button" disabled={busy} onClick={() => { setActionReason(''); setRemoveOpen(true); }} className="rounded-lg border border-rose-300 px-3 py-2 text-xs font-black text-rose-900">Remove from workspace…</button></div> : null}</section></div> : null}
            {!detailLoading && tab === 'ORGANIZATION' ? <div className="mt-4 space-y-4">{canManageMembership ? <div className="flex justify-end"><button type="button" onClick={openOrganizationEditor} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-black text-white">Change Department / Groups</button></div> : null}<div className="grid gap-4 lg:grid-cols-2"><MembershipList title="Departments" items={departmentMemberships} names={new Map(departments.map((item) => [item.departmentId,item.name]))} tenantId={scopeTenantId} type="DEPARTMENT" canManage={canManageMembership} onManage={openOrganizationEditor} /><MembershipList title="Groups" items={groupMemberships} names={new Map(groups.map((item) => [item.groupId,item.name]))} tenantId={scopeTenantId} type="GROUP" canManage={canManageMembership} onManage={openOrganizationEditor} /></div></div> : null}
            {!detailLoading && tab === 'ACCESS' ? <div className="mt-4"><EffectiveAccessExplanation tenantId={scopeTenantId} person={selected} access={overview?.effectiveAccess ?? null} roles={roles} groups={groups} departments={departments} /></div> : null}
            {!detailLoading && tab === 'SECURITY' ? <div className="mt-4 space-y-4">
              <SignInReadinessPanel readiness={readiness} invitation={invitation} />
              <MachineOwnershipImpactPanel impact={overview?.machineOwnershipImpact ?? null} canTransfer={canTransferMachineOwnership} onTransfer={() => { setOwnershipTransferResult(null); setOwnershipTargetId(''); setOwnershipCandidates([]); setOwnershipSearch(''); setOwnershipTransferOpen(true); }} />
              <section className="rounded-2xl border border-slate-200 p-4">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div><h3 className="font-black text-slate-950">Authentication</h3><p className="mt-1 text-xs leading-5 text-slate-500">Password, MFA and setup status are calculated from the canonical identity and authentication state.</p></div>
                  {readiness ? <HumanStatus value={readiness.signInState} /> : null}
                </div>
                {readiness ? <dl className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
                  <Definition label="Authentication method" value={humanAuthenticationMethod(readiness.authenticationMethod)} />
                  <Definition label="Sign-in readiness" value={readiness.signInState.replaceAll('_', ' ')} />
                  <Definition label="Password" value={humanPasswordState(readiness.passwordState)} />
                  <Definition label="Password last changed" value={readiness.passwordChangedAt ? new Date(readiness.passwordChangedAt).toLocaleString() : 'Never'} />
                  <Definition label="MFA" value={humanMfaState(readiness.mfaState, readiness.mfaType)} />
                  <Definition label="MFA verified" value={readiness.mfaVerifiedAt ? new Date(readiness.mfaVerifiedAt).toLocaleString() : 'Not enrolled'} />
                  <Definition label="Recovery codes remaining" value={String(readiness.recoveryCodesRemaining ?? 0)} />
                  <Definition label="Last successful sign-in" value={readiness.lastSuccessfulLogin ? new Date(readiness.lastSuccessfulLogin).toLocaleString() : 'Never'} />
                  <Definition label="Active sessions" value={String(readiness.activeSessionCount ?? 0)} />
                  <Definition label="Failed sign-ins" value={String(readiness.failedLoginCount ?? 0)} />
                  <Definition label="Locked until" value={readiness.lockedUntil ? new Date(readiness.lockedUntil).toLocaleString() : 'Not locked'} />
                </dl> : <GuidedEmptyState title="Sign-in readiness is unavailable" description="OpenDispatch could not project the authentication lifecycle for this Person. Do not assume the account is ready." nextStep="Retry the Person view, then review Security & Audit if the status remains unavailable." tone="warning" />}
              </section>
              <section className="rounded-2xl border border-slate-200 p-4">
                <div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-slate-950">Account setup delivery</h3><p className="mt-1 text-xs text-slate-500">Token issuance and delivery are tracked separately. A generated token is not treated as delivered until the selected channel succeeds.</p></div>{readiness ? <HumanStatus value={readiness.deliveryStatus || 'NOT_ISSUED'} /> : null}</div>
                {readiness ? <dl className="mt-4 grid gap-3 sm:grid-cols-2"><Definition label="Delivery method" value={readiness.deliveryMethod ? readiness.deliveryMethod.replaceAll('_',' ') : 'Not selected'} /><Definition label="Delivery reference" value={readiness.deliveryReference || 'Not delivered'} /><Definition label="Setup token state" value={readiness.setupState || 'NOT_ISSUED'} /><Definition label="Delivery failure" value={readiness.deliveryFailureCode || 'None'} /></dl> : null}
                {readiness?.setupExpiresAt ? <p className="mt-3 text-xs font-semibold text-slate-600">Current setup credential expires {new Date(readiness.setupExpiresAt).toLocaleString()}.</p> : null}
              </section>
              {canViewFederation ? <section className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-black text-slate-950">Enterprise identities</h3><p className="mt-1 text-xs leading-5 text-slate-500">External subjects authenticate this same canonical Person. Workspace membership and Responsibility assignments remain managed in OpenDispatch.</p></div>{canManageFederation?<button type="button" onClick={openExternalLink} className="rounded-xl border border-blue-300 px-3 py-2 text-xs font-black text-blue-800">Link identity</button>:null}</div><div className="mt-3 space-y-2">{federationLinks.map((link)=><div key={link.credentialLinkId} className="rounded-xl bg-slate-50 p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-black text-slate-900">{link.providerCode || link.providerType}</p><p className="mt-1 text-xs text-slate-500">{link.upstreamEmail || link.upstreamUsername || 'External subject linked'} · {link.lastAuthenticatedAt?`last used ${new Date(link.lastAuthenticatedAt).toLocaleString()}`:'not used yet'}</p><details className="mt-2 text-xs text-slate-500"><summary className="cursor-pointer font-bold">Technical identity</summary><p className="mt-1 break-all">Issuer: {link.issuerUri}</p><p className="mt-1 break-all">Subject: {link.externalSubject}</p></details></div><div className="flex items-center gap-2"><HumanStatus value={link.status}/>{canManageFederation&&link.status==='ACTIVE'?<button type="button" onClick={()=>{setLinkReason('');setUnlinkTarget(link);}} className="rounded-lg border border-rose-300 px-2.5 py-1.5 text-xs font-black text-rose-800">Unlink</button>:null}</div></div></div>)}{!federationLinks.length?<GuidedEmptyState title="No enterprise identity linked" description="This Person can continue with Local authentication, or a governed OIDC provider can link the same canonical identity." nextStep={canManageFederation ? 'Link an approved external identity here, or configure verified-email / JIT policy in Security → Enterprise Sign-in.' : 'A federation administrator can link an approved provider when enterprise SSO is required.'} primaryAction={canManageFederation ? <button type="button" onClick={openExternalLink} className="rounded-xl border border-blue-300 bg-white px-3 py-2 text-xs font-black text-blue-800">Link enterprise identity</button> : undefined} />:null}</div></section> : null}
              <section className="rounded-2xl border border-slate-200 p-4">
                <h3 className="font-black text-slate-950">Security actions</h3>
                <p className="mt-1 text-xs leading-5 text-slate-500">Use guided recovery actions. OpenDispatch never displays a person’s existing password or MFA secret to administrators.</p>
                <div className="mt-3 flex flex-wrap gap-2">
                  <button type="button" disabled={busy} onClick={() => openSecurityAction(selected.status === 'SUSPENDED' ? 'REACTIVATE' : 'SUSPEND')} className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-black text-white">{selected.status === 'SUSPENDED' ? 'Reactivate account' : 'Suspend account'}</button>
                  {readiness?.authenticationMethod?.includes('LOCAL') ? <button type="button" disabled={busy} onClick={() => openSecurityAction('RESET_PASSWORD')} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-black">{readiness?.passwordState === 'NOT_CONFIGURED' ? 'Set up password access' : 'Reset password'}</button> : null}
                  {readiness?.authenticationMethod?.includes('LOCAL') && readiness?.mfaState === 'ACTIVE' ? <button type="button" disabled={busy} onClick={() => openSecurityAction('RESET_MFA')} className="rounded-lg border border-amber-300 px-3 py-2 text-xs font-black text-amber-900">Reset local MFA and require re-enrollment</button> : null}
                  {Boolean(overview?.sessions.length) ? <button type="button" disabled={busy} onClick={() => openSecurityAction('REVOKE_SESSIONS')} className="rounded-lg border border-rose-300 px-3 py-2 text-xs font-black text-rose-900">Revoke sessions</button> : null}
                  {invitation?.canResend ? <button type="button" disabled={busy} onClick={() => openSecurityAction('RESEND_INVITATION')} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-black text-white">Resend invitation</button> : null}
                  {invitation?.canRevoke ? <button type="button" disabled={busy} onClick={() => openSecurityAction('REVOKE_INVITATION')} className="rounded-lg border border-rose-300 px-3 py-2 text-xs font-black text-rose-900">Revoke invitation</button> : null}
                </div>
              </section>
              <section className="rounded-2xl border border-slate-200 p-4"><h3 className="font-black text-slate-950">Sessions</h3><div className="mt-3 space-y-2">{overview?.sessions.map((session) => <div key={session.sessionId} className="rounded-xl bg-slate-50 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black">{session.userAgent || session.methods.join(', ')}</p><p className="mt-1 text-xs text-slate-500">{session.ipAddress} · {new Date(session.lastSeenAt).toLocaleString()}</p></div><HumanStatus value={session.status} /></div></div>)}{!overview?.sessions.length ? <GuidedEmptyState title="No active sessions" description="This Person has no current OpenDispatch session in this workspace." nextStep="If sign-in readiness is Ready, the next successful sign-in will appear here." /> : null}</div></section>
            </div> : null}
          </div>}
        </Panel>
      </div>

      <WorkspaceModal open={ownershipTransferOpen} title={`Transfer machine & Agent ownership from ${selected?.displayName ?? 'person'}`} description="Move accountable Service Account ownership, Agent Business Owner and Agent Technical Steward responsibilities in one tenant-scoped transaction before suspending or disabling this Person." onClose={() => setOwnershipTransferOpen(false)} width="max-w-3xl">
        <div className="space-y-4">
          {ownershipTransferResult ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950"><p className="font-black">Ownership transfer completed</p><p className="mt-1">Service Accounts: {ownershipTransferResult.serviceAccountsUpdated} · Agent business owners: {ownershipTransferResult.agentBusinessOwnersUpdated} · Agent stewards: {ownershipTransferResult.agentTechnicalStewardsUpdated}</p><p className="mt-1 text-xs">Transfer ID: {ownershipTransferResult.transferId}</p></div> : null}
          <div>
            <FieldLabel htmlFor="ownership-receiver-search" label="New accountable owner" help="Search the active People directory. The receiver must be active in every affected ownership Department." required>
              <div className="flex gap-2"><input id="ownership-receiver-search" value={ownershipSearch} onChange={(event) => setOwnershipSearch(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); void searchOwnershipReceivers(); } }} placeholder="Name, username or email" className="min-w-0 flex-1 rounded-xl border border-slate-300 px-3 py-2.5"/><button type="button" disabled={busy} onClick={() => void searchOwnershipReceivers()} className="rounded-xl border border-blue-300 px-4 py-2 text-sm font-black text-blue-700 disabled:opacity-50">Search</button></div>
            </FieldLabel>
            <div className="mt-3 max-h-56 space-y-2 overflow-y-auto">{ownershipCandidates.map((candidate) => <button type="button" key={candidate.userId} onClick={() => setOwnershipTargetId(candidate.userId)} className={`w-full rounded-xl border p-3 text-left ${ownershipTargetId === candidate.userId ? 'border-blue-500 bg-blue-50' : 'border-slate-200 bg-white hover:border-blue-300'}`}><p className="text-sm font-black text-slate-950">{candidate.displayName}</p><p className="mt-1 text-xs text-slate-500">{candidate.username} · {candidate.email}</p></button>)}</div>
          </div>
          <AuditReasonSelector idPrefix="machine-ownership-transfer" value={ownershipReason} onChange={setOwnershipReason} tier="ELEVATED"/>
          <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-950">This operation changes accountability only. It does not grant the receiver Agent, Task or Machine permissions; canonical RBAC remains authoritative.</div>
          <div className="flex justify-end gap-2"><button type="button" onClick={() => setOwnershipTransferOpen(false)} className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-black">Close</button><button type="button" disabled={busy || !ownershipTargetId || !isAuditReasonValid(ownershipReason, 'ELEVATED') || Boolean(ownershipTransferResult)} onClick={() => void transferMachineOwnership()} className="rounded-xl bg-amber-700 px-4 py-2 text-sm font-black text-white disabled:bg-slate-300">Transfer ownership</button></div>
        </div>
      </WorkspaceModal>

      <WorkspaceModal open={editOpen} title="Edit person" description="Update business profile information. Username and the internal identity remain stable identifiers." onClose={() => setEditOpen(false)}>
        <div className="space-y-4">
          <FieldLabel htmlFor="person-edit-name" label="Display name" required><input id="person-edit-name" value={editDisplayName} onChange={(event) => setEditDisplayName(event.target.value)} className="w-full rounded-xl border border-slate-300 px-3 py-2.5" /></FieldLabel>
          <FieldLabel htmlFor="person-edit-email" label="Email"><input id="person-edit-email" type="email" value={editEmail} onChange={(event) => setEditEmail(event.target.value)} className="w-full rounded-xl border border-slate-300 px-3 py-2.5" /></FieldLabel>
          <AuditReasonSelector idPrefix="person-edit" value={actionReason} onChange={setActionReason} />
          <div className="flex justify-end gap-2"><button type="button" onClick={() => setEditOpen(false)} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-black">Cancel</button><button type="button" disabled={busy || !editDisplayName.trim() || !isAuditReasonValid(actionReason, 'ROUTINE')} onClick={() => { void savePersonProfile(); }} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-black text-white disabled:bg-slate-300">Save person</button></div>
        </div>
      </WorkspaceModal>

      <WorkspaceModal open={organizationOpen} title={`Change organization for ${selected?.displayName ?? 'person'}`} description="Choose the Primary Department and Group memberships here. Changes are audited and effective access is recalculated automatically." onClose={() => setOrganizationOpen(false)} width="max-w-4xl">
        <div className="space-y-5">
          <FieldLabel htmlFor="person-primary-department" label="Primary Department" help="Choose the person’s home Department, or leave it empty to keep the Person in this workspace as Unassigned.">
            <HierarchySelectField id="person-primary-department" value={primaryDepartmentDraft} onChange={setPrimaryDepartmentDraft} options={manageableDepartmentOptions} placeholder="Unassigned — choose a Department when ready" />
          </FieldLabel>
          <section className="rounded-2xl border border-slate-200 p-4">
            <div><h3 className="font-black text-slate-950">Groups</h3><p className="mt-1 text-xs leading-5 text-slate-500">Select every Group this person should belong to. Unchecked Groups will be removed when you save.</p></div>
            <div className="mt-3"><SearchField id="person-group-search" value={groupSearch} onChange={setGroupSearch} placeholder="Search Groups" /></div>
            <div className="mt-3"><MultiSelectCards options={filteredGroupOptions} selected={groupDraft} onChange={setGroupDraft} emptyMessage="No manageable Groups match this search." /></div>
          </section>
          <AuditReasonSelector idPrefix="person-organization" value={actionReason} onChange={setActionReason} />
          <div className="flex justify-end gap-2"><button type="button" onClick={() => setOrganizationOpen(false)} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-black">Cancel</button><button type="button" disabled={busy || !isAuditReasonValid(actionReason, 'ROUTINE')} onClick={() => { void saveOrganizationRelationships(); }} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-black text-white disabled:bg-slate-300">Save organization</button></div>
        </div>
      </WorkspaceModal>

      <WorkspaceModal open={Boolean(pendingSecurityAction)} title={pendingSecurityAction ? securityActionLabel(pendingSecurityAction) : 'Security action'} description="Review the action and record the appropriate business justification before the canonical security mutation is submitted." onClose={() => setPendingSecurityAction(null)}>
        {pendingSecurityAction ? <div className="space-y-4">
          <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6 text-slate-700"><b className="block text-slate-950">{selected?.displayName}</b><span>{securityActionLabel(pendingSecurityAction)}</span></div>
          {pendingSecurityAction === 'RESET_PASSWORD' ? <FieldLabel htmlFor="password-reset-method" label="Password reset method" help="A temporary password is the fastest option for administrator-created accounts. A secure setup link remains available for invitation-style recovery." required><SelectField id="password-reset-method" value={passwordResetMode} onChange={(value) => { setPasswordResetMode(value as 'TEMPORARY_PASSWORD'|'SETUP_LINK'); setTemporaryPassword(''); setConfirmTemporaryPassword(''); }} options={[{ value: 'TEMPORARY_PASSWORD', label: 'Set temporary password', description: 'Set a one-time password now. The person must replace it at next sign-in before normal access.' }, { value: 'SETUP_LINK', label: 'Issue secure setup link', description: 'Send or securely hand off a one-time link so the person creates their own password.' }]} /></FieldLabel> : null}
          {pendingSecurityAction === 'RESET_PASSWORD' && passwordResetMode === 'TEMPORARY_PASSWORD' ? <div className="space-y-3 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-end gap-2"><div className="min-w-0 flex-1"><FieldLabel htmlFor="temporary-password" label="Temporary password" help="At least 14 characters. OpenDispatch hashes it immediately and never returns or stores the plaintext value." required><input id="temporary-password" type="password" autoComplete="new-password" value={temporaryPassword} onChange={(event) => setTemporaryPassword(event.target.value)} className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm" /></FieldLabel></div><button type="button" onClick={() => { const generated = generateTemporaryPassword(); setTemporaryPassword(generated); setConfirmTemporaryPassword(generated); }} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-xs font-black">Generate</button><button type="button" disabled={!temporaryPassword} onClick={() => { void navigator.clipboard.writeText(temporaryPassword); }} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-xs font-black disabled:opacity-50">Copy</button></div><FieldLabel htmlFor="temporary-password-confirm" label="Confirm temporary password" required><input id="temporary-password-confirm" type="password" autoComplete="new-password" value={confirmTemporaryPassword} onChange={(event) => setConfirmTemporaryPassword(event.target.value)} className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm" /></FieldLabel>{temporaryPassword && temporaryPassword.length < 14 ? <p className="text-xs font-semibold text-rose-700">Use at least 14 characters.</p> : null}{confirmTemporaryPassword && temporaryPassword !== confirmTemporaryPassword ? <p className="text-xs font-semibold text-rose-700">The confirmation does not match.</p> : null}<div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs leading-5 text-blue-950"><b className="block">Next sign-in is restricted.</b>The temporary credential forces password replacement before normal APIs are available. After replacement, TOTP MFA enrollment must complete before normal access is issued.</div></div> : null}
          {((pendingSecurityAction === 'RESET_PASSWORD' && passwordResetMode === 'SETUP_LINK') || pendingSecurityAction === 'RESEND_INVITATION') ? <FieldLabel htmlFor="credential-delivery-method" label="Setup delivery" help="Email requires configured SMTP. Manual secure handoff returns a one-time link only in this response." required><SelectField id="credential-delivery-method" value={credentialDeliveryMethod} onChange={(value) => setCredentialDeliveryMethod(value as 'EMAIL'|'MANUAL')} options={[{ value: 'MANUAL', label: 'Manual secure handoff', description: 'Generate a one-time setup link for delivery through a trusted company channel.' }, { value: 'EMAIL', label: 'Email', description: selected?.email ? `Send to ${selected.email}` : 'Requires an email address on the person record.' }]} /></FieldLabel> : null}
          {((pendingSecurityAction === 'RESET_PASSWORD' && passwordResetMode === 'SETUP_LINK') || pendingSecurityAction === 'RESEND_INVITATION') && credentialDeliveryMethod === 'EMAIL' && !selected?.email ? <div className="rounded-2xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold text-amber-900">Add an email address to this person or choose manual secure handoff.</div> : null}
          <AuditReasonSelector idPrefix="person-security-confirm" value={actionReason} onChange={setActionReason} tier={securityActionTier(pendingSecurityAction)} />
          <div className="flex justify-end gap-2"><button type="button" onClick={() => setPendingSecurityAction(null)} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-black">Cancel</button><button type="button" disabled={busy || !isAuditReasonValid(actionReason, securityActionTier(pendingSecurityAction)) || (pendingSecurityAction === 'RESET_PASSWORD' && passwordResetMode === 'TEMPORARY_PASSWORD' && (temporaryPassword.length < 14 || temporaryPassword !== confirmTemporaryPassword)) || (((pendingSecurityAction === 'RESET_PASSWORD' && passwordResetMode === 'SETUP_LINK') || pendingSecurityAction === 'RESEND_INVITATION') && credentialDeliveryMethod === 'EMAIL' && !selected?.email)} onClick={() => { const action = pendingSecurityAction; setPendingSecurityAction(null); void runPersonAction(action); }} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white disabled:bg-slate-300">Confirm action</button></div>
        </div> : null}
      </WorkspaceModal>

      <WorkspaceModal open={linkOpen} title="Link enterprise identity" description="Use the immutable external subject from the selected identity provider. This links authentication only; it does not grant a Role, Department, Group or data scope." onClose={()=>{setLinkOpen(false);setLinkReason('');}}><div className="space-y-4"><FieldLabel htmlFor="external-provider" label="Identity provider" required><SelectField id="external-provider" value={linkProviderId} onChange={setLinkProviderId} options={federationProviders.filter((item)=>item.status==='ACTIVE').map((item)=>({value:item.providerId,label:item.displayName,description:item.issuerUri}))}/></FieldLabel><FieldLabel htmlFor="external-subject" label="External subject (sub)" help="Use the provider's stable immutable subject, not a display name." required><input id="external-subject" value={linkSubject} onChange={(event)=>setLinkSubject(event.target.value)} className="w-full rounded-xl border border-slate-300 px-3 py-2.5"/></FieldLabel><FieldLabel htmlFor="external-email" label="Observed upstream email"><input id="external-email" type="email" value={linkUpstreamEmail} onChange={(event)=>setLinkUpstreamEmail(event.target.value)} className="w-full rounded-xl border border-slate-300 px-3 py-2.5"/></FieldLabel><AuditReasonSelector idPrefix="external-link" value={linkReason} onChange={setLinkReason} tier="HIGH_RISK"/><div className="flex justify-end gap-2"><button type="button" onClick={()=>setLinkOpen(false)} className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-black">Cancel</button><button type="button" disabled={busy||!linkProviderId||!linkSubject.trim()||!isAuditReasonValid(linkReason,'HIGH_RISK')} onClick={()=>{void createExternalLink();}} className="rounded-xl bg-blue-700 px-4 py-2 text-sm font-black text-white disabled:bg-slate-300">Link identity</button></div></div></WorkspaceModal>
      <WorkspaceModal open={Boolean(unlinkTarget)} title="Unlink enterprise identity" description="The external identity will stop authenticating this Person. Local credentials, other external links and immutable audit evidence are unaffected." onClose={()=>{setUnlinkTarget(null);setLinkReason('');}}><div className="space-y-4"><div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-950"><b>{unlinkTarget?.providerCode}</b><p className="mt-1 break-all">{unlinkTarget?.externalSubject}</p></div><AuditReasonSelector idPrefix="external-unlink" value={linkReason} onChange={setLinkReason} tier="HIGH_RISK"/><div className="flex justify-end gap-2"><button type="button" onClick={()=>setUnlinkTarget(null)} className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-black">Cancel</button><button type="button" disabled={busy||!isAuditReasonValid(linkReason,'HIGH_RISK')} onClick={()=>{void confirmUnlink();}} className="rounded-xl bg-rose-700 px-4 py-2 text-sm font-black text-white disabled:bg-slate-300">Unlink identity</button></div></div></WorkspaceModal>

      <WorkspaceModal open={Boolean(oneTimeSetupUrl)} title="One-time account setup link" description="This URL is returned only for explicit manual secure handoff. Copy it now; OpenDispatch does not persist the plaintext token or URL." onClose={() => setOneTimeSetupUrl('')}>
        {oneTimeSetupUrl ? <div className="space-y-4"><div className="rounded-2xl border border-amber-300 bg-amber-50 p-4"><p className="break-all rounded-xl bg-white p-3 font-mono text-xs text-amber-950">{oneTimeSetupUrl}</p><p className="mt-2 text-xs leading-5 text-amber-900">Deliver this link through a trusted company channel. The person uses it to create their password and then completes MFA enrollment themselves.</p></div><div className="flex justify-end gap-2"><button type="button" onClick={() => { void navigator.clipboard.writeText(oneTimeSetupUrl); }} className="rounded-xl border border-amber-400 px-4 py-2.5 text-sm font-black text-amber-950">Copy link</button><button type="button" onClick={() => setOneTimeSetupUrl('')} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white">Done</button></div></div> : null}
      </WorkspaceModal>

      <WorkspaceModal open={removeOpen} title={`Remove ${selected?.displayName ?? 'person'} from ${tenantName}`} description="This removes the person from this Tenant without erasing audit history. The identity may still belong to another Tenant." onClose={() => setRemoveOpen(false)}>
        <div className="space-y-4"><div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm leading-6 text-rose-950"><b className="block">Remove workspace access</b><p className="mt-1">The person will disappear from current People and organization lists for this Tenant. Their global sign-in identity is retained for audit and can be re-added later; previous Department/Group placement and direct responsibilities will not reactivate automatically.</p></div><AuditReasonSelector idPrefix="remove-person" value={actionReason} onChange={setActionReason} tier="HIGH_RISK" /><div className="flex justify-end gap-2"><button type="button" onClick={() => setRemoveOpen(false)} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-black">Cancel</button><button type="button" disabled={busy || !isAuditReasonValid(actionReason, 'HIGH_RISK')} onClick={() => { void removePersonFromTenant(); }} className="rounded-xl bg-rose-700 px-4 py-2.5 text-sm font-black text-white disabled:bg-slate-300">Remove from workspace</button></div></div>
      </WorkspaceModal>

      <WorkspaceModal open={bulkOpen} title={bulkResult ? `Bulk operation ${bulkResult.bulkOperationId}` : `Bulk action for ${selectedIds.length} people`} description="One server-side bulk command performs authorization, idempotent per-Person execution, audit correlation and result reconciliation. Each Person keeps an independent transaction boundary, so successful items remain committed when another item conflicts or is denied." onClose={() => { setBulkOpen(false); setBulkResult(null); }} width="max-w-4xl">
        <div className="space-y-4">
          {bulkResult ? <BulkResultSummary result={bulkResult} onDone={() => { setBulkOpen(false); setBulkResult(null); }} /> : <>
          <FieldLabel htmlFor="bulk-action" label="Action">
            <SelectField id="bulk-action" value={bulkAction} onChange={(value) => { const next = value as BulkAction; setBulkAction(next); setBulkDepartmentId(''); setBulkGroupIds([]); setActionReason(next === 'MOVE_DEPARTMENT' || next === 'ADD_GROUPS' || next === 'REMOVE_GROUPS' ? 'Organization restructuring' : next === 'RESEND_INVITATION' ? 'New employee onboarding' : next === 'REVOKE_SESSIONS' ? '' : 'Security remediation'); }} options={[
              { value: 'MOVE_DEPARTMENT', label: 'Move Primary Department / leave Unassigned' },
              { value: 'ADD_GROUPS', label: 'Add selected people to Groups' },
              { value: 'REMOVE_GROUPS', label: 'Remove selected people from Groups' },
              { value: 'SUSPEND', label: 'Suspend accounts' },
              { value: 'REACTIVATE', label: 'Reactivate accounts' },
              { value: 'REVOKE_SESSIONS', label: 'Revoke all sessions' },
              { value: 'RESEND_INVITATION', label: 'Resend invitations' },
            ]} />
          </FieldLabel>
          {bulkAction === 'MOVE_DEPARTMENT' ? <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
            <FieldLabel htmlFor="bulk-department" label="New Primary Department" help="Choose Unassigned to end the current Primary Department relationship without deleting the Person.">
              <SelectField id="bulk-department" value={bulkDepartmentId} onChange={setBulkDepartmentId} placeholder="Unassigned — no Primary Department" options={manageableDepartmentOptions.map((option) => ({ value: option.value, label: option.label }))} />
            </FieldLabel>
            <p className="mt-3 text-xs leading-5 text-slate-600">Moving a Primary Department immediately changes Department-inherited Role Bindings and resource visibility for each Person. Direct User roles and Group memberships are not changed.</p>
          </div> : null}
          {bulkAction === 'ADD_GROUPS' || bulkAction === 'REMOVE_GROUPS' ? <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
            <p className="text-sm font-black text-slate-950">{bulkAction === 'ADD_GROUPS' ? 'Groups to add' : 'Groups to remove'}</p>
            <p className="mt-1 text-xs leading-5 text-slate-600">Select one or more Groups. Existing relationships are left unchanged when the requested add/remove is already satisfied.</p>
            <div className="mt-3"><MultiSelectCards options={manageableGroupOptions.map((option) => ({ value: option.value, label: option.label, description: option.description }))} selected={bulkGroupIds} onChange={setBulkGroupIds} emptyMessage="No Groups are available within your effective management scope." /></div>
          </div> : null}
          {organizationBulkAction ? <div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-xs leading-5 text-blue-950"><b className="block">Authorization remains per Person</b>The server validates the destination and every Person/source relationship against your current Department / Group scope. A bulk selection never widens authorization.</div> : null}
          <AuditReasonSelector idPrefix="bulk-people" value={actionReason} onChange={setActionReason} tier={bulkAuditTier} />
          <div className="flex justify-end gap-2"><button type="button" onClick={() => { setBulkOpen(false); setBulkResult(null); }} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-black">Cancel</button><button type="button" disabled={busy || !bulkTargetValid || !isAuditReasonValid(actionReason, bulkAuditTier)} onClick={() => { void executeBulkAction(); }} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-black text-white disabled:bg-slate-300">Run server-side bulk action</button></div>
          </>}
        </div>
      </WorkspaceModal>
    </div>
  );
}


function BulkResultSummary({ result, onDone }: { result: PeopleBulkActionResult; onDone: () => void }) {
  return <div className="space-y-4">
    <div className="grid gap-3 sm:grid-cols-4">
      <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Succeeded</p><p className="mt-1 text-2xl font-black text-emerald-700">{result.succeededCount}</p></div>
      <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Skipped</p><p className="mt-1 text-2xl font-black text-slate-700">{result.skippedCount}</p></div>
      <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Failed</p><p className="mt-1 text-2xl font-black text-rose-700">{result.failedCount}</p></div>
      <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Governed changes</p><p className="mt-1 text-2xl font-black text-blue-700">{result.changedCount}</p></div>
    </div>
    <div className="rounded-2xl border border-slate-200 bg-white">
      <div className="border-b border-slate-200 px-4 py-3"><p className="text-sm font-black text-slate-950">Per-person reconciliation</p><p className="mt-1 text-xs text-slate-500">Execution policy: {result.executionPolicy}. Retry only failed items after following the remediation guidance.</p></div>
      <div className="max-h-[420px] divide-y divide-slate-100 overflow-y-auto">{result.results.map((item) => <div key={item.userId} className="grid gap-2 px-4 py-3 md:grid-cols-[minmax(0,1fr)_110px_minmax(0,1.5fr)]"><div><p className="font-black text-slate-900">{item.displayName}</p><p className="mt-1 text-xs text-slate-500">{item.userId}</p></div><div><HumanStatus value={item.outcome} /><p className="mt-1 text-xs text-slate-500">{item.changedCount} change(s)</p></div><div><p className="text-sm text-slate-700">{item.message}</p>{item.code ? <p className="mt-1 font-mono text-xs text-slate-500">{item.code}</p> : null}{item.remediation ? <p className="mt-2 text-xs font-semibold text-blue-800">Next: {item.remediation}</p> : null}</div></div>)}</div>
    </div>
    <div className="flex justify-end"><button type="button" onClick={onDone} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-black text-white">Done</button></div>
  </div>;
}



function humanSignInState(state: string): string {
  if (state === 'READY') return '✓ Local sign-in ready';
  if (state === 'SSO_MANAGED') return '✓ Enterprise SSO ready';
  if (state === 'SSO_LINK_REQUIRED') return 'Enterprise identity link required';
  if (state === 'SETUP_REQUIRED') return 'Password / activation required';
  if (state === 'MFA_REQUIRED') return 'MFA enrollment required';
  if (state === 'LOCKED') return 'Account locked';
  if (state === 'SUSPENDED') return 'Account suspended';
  if (state === 'DISABLED') return 'Account disabled';
  return state ? state.replaceAll('_', ' ') : 'Setup required';
}

function humanAuthenticationMethod(method: string): string {
  if (method === 'LOCAL') return 'Local OpenDispatch account';
  if (method === 'OIDC') return 'Enterprise OIDC';
  if (method === 'LOCAL+OIDC') return 'Local account + Enterprise OIDC';
  return method ? method.replaceAll('_',' ').replaceAll('+',' + ') : 'Unknown';
}

function humanPasswordState(state: string): string {
  if (state === 'CONFIGURED') return 'Configured';
  if (state === 'CHANGE_REQUIRED') return 'Change required';
  if (state === 'NOT_CONFIGURED') return 'Not configured';
  return state ? state.replaceAll('_', ' ').toLowerCase() : 'Unknown';
}

function humanMfaState(state: string, type?: string | null): string {
  if (state === 'ACTIVE') return type ? `${type.replaceAll('_', ' ')} enrolled` : 'Enrolled';
  if (state === 'PENDING') return 'Enrollment in progress';
  if (state === 'NOT_ENROLLED') return 'Not enrolled';
  return state ? state.replaceAll('_', ' ').toLowerCase() : 'Unknown';
}

function MachineOwnershipImpactPanel({ impact, canTransfer, onTransfer }: Readonly<{ impact: UserAccessOverview['machineOwnershipImpact'] | null; canTransfer: boolean; onTransfer: () => void }>) {
  if (!impact) return null;
  const total = impact.serviceAccountCount + impact.agentBusinessOwnerCount + impact.agentTechnicalStewardCount;
  return <section className={`rounded-2xl border p-4 ${impact.hasBlockingOwnership ? 'border-amber-300 bg-amber-50' : 'border-slate-200 bg-white'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-black text-slate-950">Machine & Agent ownership</h3><p className="mt-1 text-xs leading-5 text-slate-600">Accountable ownership must be transferred before this Person can be suspended or disabled. Ownership is responsibility metadata; authorization still uses RBAC.</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-black uppercase ${impact.hasBlockingOwnership ? 'bg-amber-200 text-amber-900' : 'bg-emerald-100 text-emerald-800'}`}>{impact.hasBlockingOwnership ? 'Transfer required' : 'No blocking ownership'}</span></div><dl className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Definition label="Service Accounts" value={String(impact.serviceAccountCount)} /><Definition label="Agent business owner" value={String(impact.agentBusinessOwnerCount)} /><Definition label="Agent technical steward" value={String(impact.agentTechnicalStewardCount)} /><Definition label="Review required" value={String(impact.ownershipReviewRequiredCount)} /></dl>{total > 0 ? <div className="mt-3 flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-semibold text-amber-900">Transfer these responsibilities before changing this Person to a non-active account state.</p>{canTransfer ? <button type="button" onClick={onTransfer} className="rounded-xl bg-amber-700 px-3 py-2 text-xs font-black text-white">Transfer ownership</button> : <span className="text-xs font-semibold text-slate-600">User update + Machine Access management permission is required.</span>}</div> : null}</section>;
}

function SignInReadinessPanel({ readiness, invitation, onOpenSecurity }: Readonly<{ readiness: UserAccessOverview['authenticationReadiness'] | null; invitation: UserInvitationStatus | null; onOpenSecurity?: () => void }>) {
  if (!readiness) return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600">Sign-in readiness is unavailable.</div>;
  const ready = readiness.signInState === 'READY' || readiness.signInState === 'SSO_MANAGED';
  const labels: Record<string,string> = {
    ACTIVATE_ACCOUNT: 'Accept the account invitation',
    SET_PASSWORD: 'Create a sign-in password',
    CHANGE_PASSWORD: 'Change the temporary password',
    ENROLL_MFA: 'Enroll an authenticator',
    REACTIVATE_ACCOUNT: 'Reactivate the account',
  };
  return <section className={`rounded-2xl border p-4 ${ready ? 'border-emerald-200 bg-emerald-50' : 'border-amber-200 bg-amber-50'}`}>
    <div className="flex flex-wrap items-start justify-between gap-3">
      <div><p className={`text-xs font-black uppercase tracking-wide ${ready ? 'text-emerald-700' : 'text-amber-700'}`}>Sign-in readiness</p><h3 className={`mt-1 text-lg font-black ${ready ? 'text-emerald-950' : 'text-amber-950'}`}>{humanSignInState(readiness.signInState)}</h3><p className="mt-1 text-xs font-bold text-slate-700">Identity account: {readiness.accountStatus.replaceAll('_',' ')} · Password: {humanPasswordState(readiness.passwordState)} · MFA: {humanMfaState(readiness.mfaState, readiness.mfaType)}</p></div>
      {onOpenSecurity ? <button type="button" onClick={onOpenSecurity} className="rounded-xl border border-current px-3 py-2 text-xs font-black">Security details →</button> : null}
    </div>
    {!ready ? <div className="mt-3"><p className="text-sm font-semibold text-amber-950">Complete these actions before normal sign-in is ready:</p><ul className="mt-2 space-y-1 text-sm text-amber-900">{readiness.blockingActions.map((action) => <li key={action}>• {labels[action] ?? action.replaceAll('_',' ')}</li>)}</ul>{readiness.deliveryStatus === 'FAILED' ? <p className="mt-2 rounded-xl bg-white/70 p-2 text-xs font-black text-rose-800">Setup delivery failed: {readiness.deliveryFailureCode || 'Review the configured delivery channel.'}</p> : null}{invitation?.canResend ? <p className="mt-2 text-xs font-semibold text-amber-800">An administrator can resend the invitation from Security.</p> : null}</div> : <p className="mt-2 text-sm text-emerald-900">{readiness.signInState === 'SSO_MANAGED' ? 'Enterprise authentication is linked. Provider authentication is trusted only as identity evidence; OpenDispatch still enforces account status, workspace membership and authorization.' : 'Password and MFA requirements are satisfied for this account.'}</p>}
  </section>;
}

function NearbyField({ label, value, action, onClick }: Readonly<{ label: string; value: string; action: string; onClick: () => void }>) { return <div className="flex flex-col gap-2 py-3 first:pt-0 last:pb-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-sm font-bold text-slate-900">{value}</p></div><button type="button" onClick={onClick} className="self-start text-xs font-black text-blue-700 hover:underline sm:self-auto">{action} →</button></div>; }
function InfoCard({ label, value }: Readonly<{ label: string; value: ReactNode }>) { return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">{label}</p><div className="mt-2 text-sm font-black text-slate-950">{value}</div></div>; }
function Definition({ label, value }: Readonly<{ label: string; value: string }>) { return <div><dt className="text-xs font-black uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 break-all text-sm font-semibold text-slate-900">{value}</dd></div>; }
function MembershipList({ title, items, names, tenantId, type, canManage, onManage }: Readonly<{ title: string; items: Membership[]; names: Map<string,string>; tenantId: string; type: 'DEPARTMENT'|'GROUP'; canManage: boolean; onManage: () => void }>) { return <section className="rounded-2xl border border-slate-200 p-4"><h3 className="font-black text-slate-950">{title}</h3><div className="mt-3 space-y-2">{items.map((membership) => <div key={membership.membershipId} className="rounded-xl bg-slate-50 p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-black text-slate-900">{names.get(membership.resourceId) ?? membership.resourceId}</p><p className="mt-1 text-xs text-slate-500">{type === 'DEPARTMENT' ? membership.primary ? 'Primary Department' : 'Additional Department' : membership.role === 'LEAD' ? 'Group lead' : 'Group member'}</p></div><ContextLink href={`/admin/tenants/${encodeURIComponent(tenantId)}/organization?type=${type}&id=${encodeURIComponent(membership.resourceId)}&tab=MEMBERS`}>Open</ContextLink></div></div>)}{items.length === 0 ? <GuidedEmptyState title={`No ${title.toLowerCase()} assigned`} description={`This Person does not currently belong to any ${type === 'DEPARTMENT' ? 'Department' : 'Group'} visible in your scope.`} nextStep={canManage ? `Use Change Department / Groups to add ${type === 'DEPARTMENT' ? 'the primary Department' : 'working Groups'}.` : 'A membership administrator can update this relationship.'} primaryAction={canManage ? <button type="button" onClick={onManage} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-black text-white">Change organization</button> : undefined} /> : null}</div></section>; }
