package com.opensocket.aievent.core.resourceaccess.core;

import static org.junit.jupiter.api.Assertions.*;
import com.opensocket.aievent.core.iam.security.contract.AuthenticationAssurance;
import com.opensocket.aievent.core.iam.security.contract.AuthenticationContext;
import com.opensocket.aievent.core.iam.security.contract.PrincipalRef;
import com.opensocket.aievent.core.iam.security.contract.SubjectRef;
import com.opensocket.aievent.core.iam.security.contract.TenantRef;
import com.opensocket.aievent.core.resourceaccess.contract.*;
import java.time.*;import java.util.*;
import org.junit.jupiter.api.Test;

class DefaultResourceAuthorizationServiceTest {
 private static final Instant NOW=Instant.parse("2026-07-28T00:00:00Z");
 @Test void explicitDenyOverridesTenantPermissionAndGrant(){Fixture f=new Fixture();f.denies=List.of(deny());AuthorizationDecision d=f.service().evaluate(f.request(OperationPhase.START,SecurityEpoch.ZERO,VisibilityLevel.SUMMARY));assertEquals(DecisionEffect.DENY,d.effect());assertTrue(d.matchedDenyIds().contains("deny-1"));assertEquals(ResourceDecisionReasonCodes.EXPLICIT_DENY_MATCHED,d.reasons().getFirst().code());}
 @Test void tenantPermissionWithClearanceAllowsAndCachesInsideSameEpoch(){Fixture f=new Fixture();AuthorizationDecision first=f.service().evaluate(f.request(OperationPhase.START,SecurityEpoch.ZERO,VisibilityLevel.SUMMARY));AuthorizationDecision second=f.service().evaluate(f.request(OperationPhase.START,SecurityEpoch.ZERO,VisibilityLevel.SUMMARY));assertEquals(DecisionEffect.ALLOW,first.effect());assertEquals(VisibilityLevel.FULL,first.grantedVisibility());assertTrue(second.reasons().stream().anyMatch(r->r.code().equals(ResourceDecisionReasonCodes.AUTHORIZATION_CACHE_HIT)));assertEquals(2,f.audits.size());}
 @Test void staleRuntimeEpochFailsClosedBeforeAllowEvaluation(){Fixture f=new Fixture();f.epoch=new SecurityEpoch(1,2,3,4,5,6);AuthorizationDecision d=f.service().evaluate(f.request(OperationPhase.HEARTBEAT,SecurityEpoch.ZERO,VisibilityLevel.SUMMARY));assertEquals(DecisionEffect.DENY,d.effect());assertEquals(ResourceDecisionReasonCodes.RESOURCE_SECURITY_EPOCH_STALE,d.reasons().getFirst().code());}
 @Test void simulationIsMarkedNonExecutable(){Fixture f=new Fixture();AuthenticationContext actor=f.auth();AuthorizationDecision d=f.service().simulate(new AuthorizationSimulationRequest(actor,f.principal,TenantRef.tenant("T1"),new ResourceAction("task.read",ResourceAction.ActionKind.READ,false),f.ref,VisibilityLevel.SUMMARY,"preview","sim-1",SecurityEpoch.ZERO,Map.of()));assertEquals(AuthorizationDecisionMode.SIMULATION,d.mode());assertTrue(d.shadowOnly());assertFalse(d.cacheable());}
 @Test void shadowDenyIsNonExecutableAndAlwaysCompared(){Fixture f=new Fixture();f.denies=List.of(deny());AuthorizationDecision d=f.service(ResourceAccessEnforcementMode.SHADOW).evaluate(f.request(OperationPhase.START,SecurityEpoch.ZERO,VisibilityLevel.SUMMARY));assertEquals(AuthorizationDecisionMode.SHADOW,d.mode());assertTrue(d.shadowOnly());assertEquals(1,f.comparisons.size());assertEquals(ShadowMismatchCategory.LEGACY_NOT_AVAILABLE,f.comparisons.getFirst().category());}
 @Test void descriptorFailureInShadowModeRemainsNonExecutableAndAudited(){Fixture f=new Fixture();AuthorizationDecision d=f.service(ResourceAccessEnforcementMode.SHADOW,(r,c)->Optional.empty()).evaluate(f.request(OperationPhase.START,SecurityEpoch.ZERO,VisibilityLevel.SUMMARY));assertEquals(DecisionEffect.DENY,d.effect());assertTrue(d.shadowOnly());assertEquals(1,f.audits.size());assertEquals(1,f.comparisons.size());}
 @Test void departmentMembershipDoesNotBroadenRoleBindingScope(){Fixture f=new Fixture();f.permissionScopeType="DEPARTMENT";f.permissionScopeId="D1";f.departments=Set.of("D1","D2");f.ownerDepartment="D2";AuthorizationDecision d=f.service().evaluate(f.request(OperationPhase.START,SecurityEpoch.ZERO,VisibilityLevel.SUMMARY));assertEquals(DecisionEffect.DENY,d.effect());assertEquals(ResourceDecisionReasonCodes.RESOURCE_SCOPE_NOT_MATCHED,d.reasons().getFirst().code());}
 @Test void explicitResourceGrantCanCreateNarrowCrossBoundaryException(){Fixture f=new Fixture();f.permissionScopeType="DEPARTMENT";f.permissionScopeId="D1";f.departments=Set.of("D1","D2");f.ownerDepartment="D2";f.grants=List.of(new ScopeGrantRecord("T1","grant-1",ScopePrincipalType.USER,"U1","task.read",ResourceType.TASK,ScopeType.RESOURCE,"TASK-1",VisibilityLevel.FULL,NOW.minusSeconds(1),null,ScopeGrantSource.MANUAL,"Approved exception","admin","approver",ScopeGrantState.ACTIVE,"grant-idem",1,NOW,NOW));AuthorizationDecision d=f.service().evaluate(f.request(OperationPhase.START,SecurityEpoch.ZERO,VisibilityLevel.SUMMARY));assertEquals(DecisionEffect.ALLOW,d.effect());assertTrue(d.matchedScopeGrantIds().contains("grant-1"));}
 @Test void organizationalGrantCannotBypassRoleBindingScope(){Fixture f=new Fixture();f.permissionScopeType="DEPARTMENT";f.permissionScopeId="D1";f.departments=Set.of("D1","D2");f.ownerDepartment="D2";f.grants=List.of(new ScopeGrantRecord("T1","grant-org",ScopePrincipalType.USER,"U1","task.read",ResourceType.TASK,ScopeType.DEPARTMENT,"D2",VisibilityLevel.FULL,NOW.minusSeconds(1),null,ScopeGrantSource.MANUAL,"Organization share","admin","approver",ScopeGrantState.ACTIVE,"grant-org-idem",1,NOW,NOW));AuthorizationDecision d=f.service().evaluate(f.request(OperationPhase.START,SecurityEpoch.ZERO,VisibilityLevel.SUMMARY));assertEquals(DecisionEffect.DENY,d.effect());assertEquals(ResourceDecisionReasonCodes.RESOURCE_SCOPE_NOT_MATCHED,d.reasons().getFirst().code());}
 @Test void groupParticipantOnlyMatchesWhenRoleBindingScopeMatchesSameGroup(){Fixture f=new Fixture();f.permissionScopeType="GROUP";f.permissionScopeId="G1";f.groups=Set.of("G1","G2");f.ownerDepartment="";f.participants=List.of(new ResourceParticipantProjection("p-g1",f.ref,ResourceParticipantType.GROUP,"G1",ResourceParticipantRole.REQUESTER,VisibilityLevel.STANDARD,List.of("task.read"),NOW.minusSeconds(1),null,DescriptorAuthority.TASK_DOMAIN,1,ResourceParticipantStatus.ACTIVE));AuthorizationDecision d=f.service().evaluate(f.request(OperationPhase.START,SecurityEpoch.ZERO,VisibilityLevel.SUMMARY));assertEquals(DecisionEffect.ALLOW,d.effect());}
 @Test void cacheKeyEpochChangeCannotReuseOldAllow(){var cache=new InMemoryResourceAuthorizationCache(100);ResourceAuthorizationCacheKey one=new ResourceAuthorizationCacheKey("T1","USER","U1","task.read",ResourceType.TASK,"TASK-1",VisibilityLevel.SUMMARY,PolicyVersion.ZERO,SecurityEpoch.ZERO);AuthorizationDecision decision=new Fixture().service().evaluate(new Fixture().request(OperationPhase.START,SecurityEpoch.ZERO,VisibilityLevel.SUMMARY));cache.put(one,decision,NOW.plusSeconds(30));ResourceAuthorizationCacheKey two=new ResourceAuthorizationCacheKey("T1","USER","U1","task.read",ResourceType.TASK,"TASK-1",VisibilityLevel.SUMMARY,PolicyVersion.ZERO,new SecurityEpoch(0,0,0,1,0,0));assertTrue(cache.get(two,NOW).isEmpty());}
 private static ExplicitDenyRecord deny(){return new ExplicitDenyRecord("T1","deny-1",ScopePrincipalType.USER,"U1","task.read",ResourceType.TASK,ScopeType.TENANT,"T1","incident",DenySeverity.CRITICAL,NOW.minusSeconds(1),null,"admin","approver",ScopeDenyState.ACTIVE,"deny-idem",1,NOW,NOW);}
 private static final class Fixture implements ResourceDecisionEvidenceRepository{
  final PrincipalRef principal=new PrincipalRef(PrincipalRef.PrincipalType.USER,"U1");final ResourceRef ref=new ResourceRef("T1",ResourceType.TASK,"TASK-1");List<ExplicitDenyRecord>denies=List.of();List<ScopeGrantRecord>grants=List.of();List<ResourceParticipantProjection>participants=List.of();Set<String>departments=Set.of("D1");Set<String>groups=Set.of();String ownerDepartment="D1";String ownerGroup="";String permissionScopeType="TENANT";String permissionScopeId="T1";SecurityEpoch epoch=SecurityEpoch.ZERO;final List<AuthorizationDecisionAuditRecord>audits=new ArrayList<>();final List<ShadowDecisionComparison>comparisons=new ArrayList<>();
  DefaultResourceAuthorizationService service(){return service(ResourceAccessEnforcementMode.FULL_ENFORCE);}
  DefaultResourceAuthorizationService service(ResourceAccessEnforcementMode mode){ResourceDescriptor descriptor=new ResourceDescriptor(ref,"TASK-1",new OwnershipDescriptor(ownerDepartment,ownerGroup,"","","","",1),null,ref,new VisibilityDescriptor(SensitivityLevel.CONFIDENTIAL,VisibilityLevel.FULL,"",PolicyVersion.ZERO),ResourceSecurityState.NORMAL,0,1,DescriptorAuthority.TASK_DOMAIN,"hash-1",NOW);return service(mode,(r,c)->Optional.of(descriptor));}
  DefaultResourceAuthorizationService service(ResourceAccessEnforcementMode mode,java.util.function.BiFunction<ResourceRef,DescriptorResolutionContext,Optional<ResourceDescriptor>> lookup){ResourceDescriptorResolverPort resolver=new ResourceDescriptorResolverPort(){public boolean supports(ResourceType t){return t==ResourceType.TASK;}public Optional<ResourceDescriptor>resolve(ResourceRef r,DescriptorResolutionContext c){return lookup.apply(r,c);}};AuthoritativeResourceDescriptorService descriptors=new AuthoritativeResourceDescriptorService(new DefaultResourceCatalog(),List.of(resolver));ResourcePermissionAuthorityPort permission=(r,s)->new ResourcePermissionDecision(true,"AUTH_PERMISSION_GRANTED",Set.of("binding-1"),Set.of("role-1"),permissionScopeType,permissionScopeId);return new DefaultResourceAuthorizationService(descriptors,this,permission,new InMemoryResourceAuthorizationCache(100),Optional.empty(),mode,Duration.ofSeconds(30),Duration.ofSeconds(5),Clock.fixed(NOW,ZoneOffset.UTC));}
  AuthenticationContext auth(){return new AuthenticationContext(new SubjectRef(SubjectRef.IdentityType.HUMAN_USER,"U1"),principal,TenantRef.tenant("T1"),Optional.empty(),AuthenticationAssurance.passwordOnly(NOW),com.opensocket.aievent.core.iam.security.contract.SecurityEpoch.ZERO,Optional.empty(),NOW.minusSeconds(60),NOW.plusSeconds(3600));}
  com.opensocket.aievent.core.resourceaccess.contract.AuthorizationRequest request(OperationPhase phase,SecurityEpoch presented,VisibilityLevel visibility){return new com.opensocket.aievent.core.resourceaccess.contract.AuthorizationRequest(principal,auth(),TenantRef.tenant("T1"),new ResourceAction("task.read",ResourceAction.ActionKind.READ,false),ref,visibility,RequestChannel.REST,"test",phase,"","corr-1",presented,Map.of());}
  public List<ScopeGrantRecord>findEffectiveScopeGrants(String t,Set<PolicyPrincipalRef>p,String permission,ResourceType type,Instant at){return grants;}
  public List<ExplicitDenyRecord>findEffectiveExplicitDenies(String t,Set<PolicyPrincipalRef>p,String permission,ResourceType type,Instant at){return denies;}
  public List<ResourceParticipantProjection>findEffectiveParticipants(ResourceRef r,Instant at){return participants;}
  public Optional<PrincipalClearanceRecord>findEffectiveClearance(String t,PolicyPrincipalRef p,Instant at){return Optional.of(new PrincipalClearanceRecord("T1","c1",ScopePrincipalType.USER,"U1",SensitivityLevel.CONFIDENTIAL,NOW.minusSeconds(1),null,ClearanceStatus.ACTIVE,"approver","test",1,NOW,NOW));}
  public Optional<VisibilityPolicyRecord>findActiveVisibilityPolicy(String t,ResourceType type){return Optional.empty();}
  public PrincipalScopeSnapshot resolvePrincipalScope(String t,PrincipalRef p,Instant at){return new PrincipalScopeSnapshot(t,departments,groups,0);}
  public boolean departmentContains(String t,String a,String d){return a.equals(d);}
  public PolicyVersion currentPolicyVersion(String t){return new PolicyVersion(1,1,"p1");}
  public SecurityEpoch currentSecurityEpoch(String t,PrincipalRef p,ResourceRef r){return epoch;}
  public void appendDecision(AuthorizationDecisionAuditRecord r){audits.add(r);}
  public void appendShadowComparison(ShadowDecisionComparison c){comparisons.add(c);}
 }
}
