import { beginnerStatusDescription, beginnerStatusLabel, normalizeCode } from '@/lib/dispatch-readiness/labels';
import { getStatusHelp } from '@/lib/help/statusHelp';

type StatusTone = "success" | "warning" | "danger" | "neutral" | "info";

const statusToneMap: Record<string, StatusTone> = {
  RUNNING: "success",
  ONLINE: "success",
  SELF: "success",
  REMOTE: "info",
  CONNECTED: "success",
  HEALTHY: "success",
  READY: "success",
  AUTHORIZED: "success",
  SUCCESS: "success",
  UP: "success",
  OK: "success",
  CORE_OK: "success",
  NETTY_OK: "success",
  CORE_PARTIAL: "warning",
  NETTY_PARTIAL: "warning",
  CORE_UNAVAILABLE: "danger",
  NETTY_UNAVAILABLE: "danger",

  AGENT_AUTH: "info",
  AGENT_SESSION: "info",
  DELIVERY: "info",
  CALLBACK: "info",
  SECURITY: "warning",
  TASK: "info",
  CLUSTER: "info",
  METRICS: "info",
  SYSTEM: "neutral",
  OTHER: "neutral",
  SYNCED: "success",
  STATIC_SEED: "success",
  CLUSTER_WIDE: "success",
  CLUSTER_AGGREGATED: "success",
  ACTIVE: "success",
  APPROVED: "success",
  ENABLED: "success",
  NORMAL: "success",
  PENDING_REVIEW: "warning",
  REGISTERED: "info",
  RUNTIME_OBSERVED: "info",
  OBSERVED: "info",
  NOT_OBSERVED: "neutral",
  REJECTED: "danger",
  SUSPENDED: "danger",
  QUARANTINED: "danger",
  COMPROMISED: "danger",
  NO_CORE_PROFILE: "danger",
  NO_PROFILE: "neutral",
  NO_ENROLLMENT: "neutral",

  PROFILE_REGISTERED: "info",
  PROFILE_PENDING_REVIEW: "warning",
  PROFILE_APPROVED: "success",
  PROFILE_REJECTED: "danger",
  PROFILE_SUSPENDED: "danger",
  PROFILE_REVOKED: "danger",
  PROFILE_UNKNOWN: "neutral",
  ENROLLMENT_REGISTERED: "info",
  ENROLLMENT_PENDING_REVIEW: "warning",
  ENROLLMENT_APPROVED: "success",
  ENROLLMENT_REJECTED: "danger",
  ENROLLMENT_UNKNOWN: "neutral",
  RUNTIME_ONLY_UNGOVERNED: "danger",
  CREDENTIAL_ACTIVE: "success",
  CREDENTIAL_MISSING: "danger",
  CREDENTIAL_EXPIRED: "danger",
  CREDENTIAL_REVOKED: "danger",
  CREDENTIAL_UNKNOWN: "warning",
  AUTH_UNKNOWN: "warning",
  AUTH_DENIED: "danger",
  AUTH_REVOKED: "danger",
  AUTH_UNVERIFIED: "warning",
  AUTH_DISCONNECTED_BY_POLICY: "danger",
  AUTH_OTHER: "warning",
  PROFILE_NOT_APPROVED: "warning",
  PROFILE_DISABLED: "neutral",
  RISK_BLOCKED: "danger",
  CREDENTIAL_NOT_ACTIVE: "danger",
  RUNTIME_OFFLINE: "danger",
  MISSING: "warning",
  ACCEPT_TASKS: "success",
  LEADER: "success",
  INFO: "info",
  FOLLOWER: "info",
  DISCOVERED: "info",
  STATIC_PEER: "info",
  UDP_DISCOVERY: "info",
  DOCKER_NETWORK: "info",
  HEARTBEAT: "info",
  STANDALONE: "info",
  OPEN: "success",
  ROUTED: "success",
  COMPLETED: "success",
  DELIVERED: "success",
  CALLBACK_RECEIVED: "success",
  IDLE: "info",
  RECEIVED: "info",
  ASSIGNED: "info",
  DISPATCHED: "info",
  ACKED: "info",
  MOCK: "info",
  BUSY: "warning",
  WARN: "warning",
  NOT_READY: "warning",
  WAITING: "warning",
  WARNING: "warning",
  LOCAL_SCOPE: "warning",
  LOCAL_EVENT_SCOPE: "warning",
  LOCAL_REALTIME_SCOPE: "warning",
  LOCAL_TRACE_SCOPE: "warning",
  AVAILABLE: "success",
  UNAVAILABLE: "warning",
  CLUSTER_API: "success",
  LOCAL_API: "warning",
  STALE: "warning",
  DEGRADED: "warning",
  DRAINING: "warning",
  STARTING: "warning",
  CONNECTING: "warning",
  RECONNECTING: "warning",
  PENDING: "warning",
  WAITING_APPROVAL: "warning",
  DISPATCH_REQUESTED: "warning",
  DELIVERING: "warning",
  RETRY_PENDING: "warning",
  REASSIGNING: "warning",
  UNVERIFIED: "warning",
  PROCESSING: "warning",
  DOWN: "danger",
  OFFLINE: "danger",
  ERROR: "danger",
  FAILED: "danger",
  TIMEOUT: "danger",
  DELIVERY_FAILED: "danger",
  DEAD_LETTER: "danger",
  DENIED: "danger",
  REVOKED: "danger",
  EXPIRED: "danger",
  DISCONNECTED_BY_POLICY: "danger",
  LOST: "danger",
  CLOSED: "danger",
  SKIPPED: "neutral",
  DRAINED: "neutral",
  NO_NEW_TASKS: "neutral",
  MAINTENANCE: "neutral",
  DISABLED: "neutral",
  CANCELLED: "neutral",
  HIGH: "danger",
  MEDIUM: "warning",
  LOW: "success",
  EXECUTABLE: "success",
  REVIEW_ONLY: "warning",
  NOT_LINKED: "neutral",
  SYNC_PENDING: "warning",
  SYNC_FAILED: "danger",
  WAITING_AGENT: "warning",
  QUEUED: "warning",
  BLOCKED: "danger",
  RUNTIME_NOT_REPORTED: "warning",
  NOT_USABLE: "neutral",
  UNKNOWN: "neutral",
  LEAVING: "neutral",
};

const toneClassMap: Record<StatusTone, string> = {
  success: "border-emerald-200 bg-emerald-50 text-emerald-700",
  warning: "border-amber-200 bg-amber-50 text-amber-700",
  danger: "border-rose-200 bg-rose-50 text-rose-700",
  neutral: "border-slate-200 bg-slate-100 text-slate-700",
  info: "border-blue-200 bg-blue-50 text-blue-700",
};

export function StatusBadge({
  status,
  label,
  title,
}: Readonly<{ status: string; label?: string; title?: string }>) {
  const normalized = normalizeCode(status);
  const tone = statusToneMap[normalized] ?? "neutral";
  const display = label ?? beginnerStatusLabel(normalized);
  const centralizedHelp = getStatusHelp(normalized);
  const tooltip = title ?? (centralizedHelp
    ? `${centralizedHelp.description}${centralizedHelp.operatorAction ? ` 下一步：${centralizedHelp.operatorAction}` : ''} code: ${normalized || '-'}`
    : `${beginnerStatusDescription(normalized)} code: ${normalized || '-'}`);
  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-semibold ${toneClassMap[tone]}`}
      title={tooltip}
    >
      <span>{display}</span>
      {!label && normalized && display !== normalized ? <span className="font-mono text-[10px] opacity-60">{normalized}</span> : null}
    </span>
  );
}
