package com.opensocket.aievent.core.resourceaccess.enforcement;

import com.opensocket.aievent.core.resourceaccess.contract.*;
import com.opensocket.aievent.core.resourceaccess.core.ResourceDecisionEvidenceRepository;
import com.opensocket.aievent.core.resourceaccess.core.ResourceFieldPolicySelector;
import com.opensocket.aievent.core.resourceaccess.core.ResourcePolicyScale;
import java.time.Clock;
import java.util.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

/** P4RA-G governed attachment release. It never returns Provider URLs or credential material. */
@Component
@ConditionalOnProperty(prefix="resource-access",name="attachment-enabled",havingValue="true")
public final class DefaultAttachmentAccessService implements AttachmentAccessPort {
 private final ResourceAccessEnforcementPort enforcement;private final ResourceEnforcementContextPort contexts;private final RuntimeAuthorizationLeasePort leases;private final ResourceDecisionEvidenceRepository evidence;private final List<ResourceAttachmentAuthorityPort> authorities;private final AttachmentContentGatewayPort content;private final AttachmentAccessAuditPort audit;private final long maximumBytes;private final Set<String> allowedMimePrefixes;private final Clock clock;
 public DefaultAttachmentAccessService(ResourceAccessEnforcementPort enforcement,ResourceEnforcementContextPort contexts,RuntimeAuthorizationLeasePort leases,ResourceDecisionEvidenceRepository evidence,List<ResourceAttachmentAuthorityPort> authorities,AttachmentContentGatewayPort content,AttachmentAccessAuditPort audit,@Value("${resource-access.attachment.maximum-bytes:52428800}") long maximumBytes,@Value("${resource-access.attachment.allowed-mime-prefixes:application/pdf,image/,text/plain,application/json,application/zip}") String allowedMimePrefixes,Clock resourceAccessClock){this.enforcement=Objects.requireNonNull(enforcement);this.contexts=Objects.requireNonNull(contexts);this.leases=Objects.requireNonNull(leases);this.evidence=Objects.requireNonNull(evidence);this.authorities=List.copyOf(authorities);this.content=Objects.requireNonNull(content);this.audit=Objects.requireNonNull(audit);this.maximumBytes=Math.max(1,maximumBytes);this.allowedMimePrefixes=parse(allowedMimePrefixes);this.clock=Objects.requireNonNull(resourceAccessClock);}
 @Override public AttachmentDownloadGrant authorizeDownload(AttachmentDownloadCommand command){
  ResourceEnforcementContext context=contexts.current();validateTrustedContext(command.attachmentRef(),command.correlationId(),context);String readPermission=readPermission(command.attachmentRef().resourceType());String downloadPermission=downloadPermission(command.attachmentRef().resourceType());
  AuthorizationDecision read=enforcement.authorize(new ResourceEnforcementCommand(new ResourceAction(readPermission,ResourceAction.ActionKind.READ,false),command.attachmentRef(),VisibilityLevel.SENSITIVE,RequestChannel.REST,command.purpose(),OperationPhase.START,SecurityEpoch.ZERO,command.trustedFlowContext()));
  AuthorizationDecision download=enforcement.authorize(new ResourceEnforcementCommand(new ResourceAction(downloadPermission,ResourceAction.ActionKind.DOWNLOAD,true),command.attachmentRef(),VisibilityLevel.SENSITIVE,RequestChannel.REST,command.purpose(),OperationPhase.BEFORE_CONTEXT_READ,read.securityEpoch(),command.trustedFlowContext()));
  executable(read,"ATTACHMENT_READ_NOT_EXECUTABLE");executable(download,"ATTACHMENT_DOWNLOAD_NOT_EXECUTABLE");ResourceAttachmentMetadata metadata=resolve(command.attachmentRef());validateMetadata(metadata);validateFieldPolicy(metadata,download);
  AuthorizationRequest leaseRequest=new AuthorizationRequest(context.authentication().principal(),context.authentication(),context.authentication().activeTenant(),new ResourceAction(downloadPermission,ResourceAction.ActionKind.DOWNLOAD,true),metadata.attachmentRef(),VisibilityLevel.SENSITIVE,RequestChannel.REST,command.purpose(),OperationPhase.START,"",context.correlationId(),download.securityEpoch(),command.trustedFlowContext());RuntimeAuthorizationLease lease=leases.issue(leaseRequest,download);
  try{AttachmentContentHandle handle=content.createHandle(metadata,download.decisionId(),lease.leaseId(),lease.expiresAt());AttachmentDownloadGrant grant=new AttachmentDownloadGrant(metadata.attachmentRef(),metadata.filename(),metadata.contentType(),metadata.sizeBytes(),metadata.sha256(),read.decisionId(),download.decisionId(),lease.leaseId(),lease.fencingVersion(),handle,clock.instant());audit.append(grant,context.authentication().principal().principalId(),command.purpose(),command.correlationId());return grant;}catch(RuntimeException ex){leases.revoke(metadata.attachmentRef().tenantId(),lease.leaseId(),"ATTACHMENT_HANDLE_ISSUANCE_FAILED",command.correlationId());throw ex;}
 }
 private static void validateTrustedContext(ResourceRef ref,String correlation,ResourceEnforcementContext context){if(!ref.tenantId().equals(context.authentication().activeTenant().tenantId()))throw new IllegalArgumentException("ATTACHMENT_TENANT_CONTEXT_MISMATCH");if(!correlation.equals(context.correlationId()))throw new IllegalArgumentException("ATTACHMENT_CORRELATION_CONTEXT_MISMATCH");}
 private ResourceAttachmentMetadata resolve(ResourceRef ref){List<ResourceAttachmentMetadata> matches=new ArrayList<>();for(ResourceAttachmentAuthorityPort authority:authorities){Optional<ResourceAttachmentMetadata> candidate=authority.find(ref);if(candidate.isPresent())matches.add(candidate.get());}if(matches.isEmpty())throw new IllegalArgumentException("ATTACHMENT_AUTHORITY_NOT_FOUND");if(matches.size()!=1)throw new IllegalStateException("ATTACHMENT_AUTHORITY_AMBIGUOUS");return matches.get(0);}
 private void validateMetadata(ResourceAttachmentMetadata m){if(m.malwareStatus()!=AttachmentMalwareStatus.CLEAN)throw new IllegalStateException("ATTACHMENT_MALWARE_STATUS_BLOCKED:"+m.malwareStatus());if(!m.contentAvailable())throw new IllegalStateException("ATTACHMENT_CONTENT_UNAVAILABLE");if(m.sizeBytes()>maximumBytes)throw new IllegalStateException("ATTACHMENT_SIZE_POLICY_EXCEEDED");if(allowedMimePrefixes.stream().noneMatch(p->m.contentType().startsWith(p)))throw new IllegalStateException("ATTACHMENT_MIME_POLICY_DENIED");if(m.legalHold())throw new IllegalStateException("RESOURCE_LEGAL_HOLD_RESTRICTED");}
 private void validateFieldPolicy(ResourceAttachmentMetadata m,AuthorizationDecision decision){VisibilityPolicyRecord policy=evidence.findActiveVisibilityPolicy(m.attachmentRef().tenantId(),m.attachmentRef().resourceType()).orElseThrow(()->new IllegalStateException("ATTACHMENT_FIELD_POLICY_REQUIRED"));VisibilityFieldRule rule=ResourceFieldPolicySelector.select(policy,"attachment.content").orElseThrow(()->new IllegalStateException("ATTACHMENT_CONTENT_FIELD_POLICY_REQUIRED"));if(!rule.downloadAllowed())throw new IllegalStateException("ATTACHMENT_DOWNLOAD_POLICY_DENIED");if(!ResourcePolicyScale.visibilityCovers(decision.grantedVisibility(),rule.minimumVisibilityLevel()))throw new IllegalStateException("ATTACHMENT_VISIBILITY_INSUFFICIENT");}
 private static void executable(AuthorizationDecision d,String reason){if(d.mode()!=AuthorizationDecisionMode.FORMAL||d.effect()!=DecisionEffect.ALLOW||d.shadowOnly())throw new IllegalStateException(reason);}
 private static String readPermission(ResourceType type){return switch(type){case TASK_ATTACHMENT->"task.attachment.read";case ISSUE_ATTACHMENT->"integration.issue.attachment.read";default->throw new IllegalArgumentException("Unsupported attachment resource type");};}
 private static String downloadPermission(ResourceType type){return switch(type){case TASK_ATTACHMENT->"task.attachment.download";case ISSUE_ATTACHMENT->"integration.issue.attachment.download";default->throw new IllegalArgumentException("Unsupported attachment resource type");};}
 private static Set<String> parse(String value){Set<String> out=new LinkedHashSet<>();for(String v:(value==null?"":value).split(",")){String n=v.trim().toLowerCase(Locale.ROOT);if(!n.isBlank())out.add(n);}if(out.isEmpty())throw new IllegalArgumentException("At least one attachment MIME prefix is required");return Set.copyOf(out);}
}
