package com.opensocket.aievent.core.integration.handoff;

public enum HandoffDomainEventType {
    HANDOFF_SNAPSHOT_CREATED,
    HANDOFF_SNAPSHOT_APPROVED,
    HANDOFF_SNAPSHOT_REJECTED,
    HANDOFF_SNAPSHOT_SUPERSEDED,
    HANDOFF_RESULT_SNAPSHOT_CREATED,
    HANDOFF_DISPATCH_RELEASE_REQUESTED,
    HANDOFF_DISPATCH_RELEASED,
    HANDOFF_RECONCILIATION_REQUIRED,
    HANDOFF_RECONCILED
}
