package com.opensocket.aievent.core.iam.runtime.projection;

import com.opensocket.aievent.core.iam.api.application.port.IamAdministrationProjectionPort;
import com.opensocket.aievent.core.iam.api.pagination.*;
import com.opensocket.aievent.core.iam.api.response.*;
import com.opensocket.aievent.core.iam.persistence.dao.IamApiRuntimeDao;
import com.opensocket.aievent.core.iam.persistence.tenant.*;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.Instant;import java.util.*;import java.util.function.Supplier;
import org.springframework.transaction.support.TransactionTemplate;

public final class MybatisIamAdministrationProjectionAdapter implements IamAdministrationProjectionPort {
 private final IamApiRuntimeDao dao;private final SignedCursorCodec cursors;private final TransactionTemplate transactions;
 public MybatisIamAdministrationProjectionAdapter(IamApiRuntimeDao d,SignedCursorCodec c,TransactionTemplate t){dao=d;cursors=c;transactions=t;}
 public CursorPage<UserResponse> platformUsers(String text,String status,String tenantId,int limit,String cursor){String hash=hash(text,status,tenantId);String after=after(cursor,"INSTANCE","platform-users",hash);List<Map<String,Object>>rows=transactions.execute(x->dao.listPlatformUsers(text,status,tenantId,after,limit+1));return cursorPage(rows,limit,"INSTANCE","platform-users",hash,"userId",this::user);}
 public Optional<UserResponse> platformUser(String id){return transactions.execute(x->Optional.ofNullable(dao.findPlatformUser(id)).map(this::user));}
 public CursorPage<PlatformTenantMembershipResponse> platformMemberships(String user,int limit,String cursor){String hash=hash(user);String after=after(cursor,"INSTANCE","platform-memberships",hash);List<Map<String,Object>>rows=transactions.execute(x->dao.listPlatformMemberships(user,after,limit+1));return cursorPage(rows,limit,"INSTANCE","platform-memberships",hash,"tenantId",this::platformMembership);}
 public CursorPage<UserResponse> users(String tenant,String text,String status,String membershipStatus,String roleId,String departmentId,String groupId,String signInState,int limit,String cursor){String hash=hash(text,status,membershipStatus,roleId,departmentId,groupId,signInState);String after=after(cursor,tenant,"users",hash);List<Map<String,Object>> rows=inTenant(tenant,"projection:users",()->dao.listUsers(tenant,text,status,membershipStatus,roleId,departmentId,groupId,signInState,after,limit+1));return cursorPage(rows,limit,tenant,"users",hash,"userId",this::user);}
 public CursorPage<UserResponse> usersWithin(String tenant,Set<String> departmentIds,Set<String> groupIds,String text,String status,String membershipStatus,String roleId,String departmentId,String groupId,String signInState,int limit,String cursor){Set<String>depts=departmentIds==null?Set.of():Set.copyOf(departmentIds);Set<String>groups=groupIds==null?Set.of():Set.copyOf(groupIds);String hash=hash(text,status,membershipStatus,roleId,departmentId,groupId,signInState,String.join(",",new TreeSet<>(depts)),String.join(",",new TreeSet<>(groups)));String after=after(cursor,tenant,"users-scoped",hash);if(depts.isEmpty()&&groups.isEmpty())return new CursorPage<>(List.of(),"",false);List<Map<String,Object>> rows=inTenant(tenant,"projection:users-scoped",()->dao.listUsersWithin(tenant,depts,groups,text,status,membershipStatus,roleId,departmentId,groupId,signInState,after,limit+1));return cursorPage(rows,limit,tenant,"users-scoped",hash,"userId",this::user);}
 public CursorPage<UserResponse> availableUsers(String tenant,String text,int limit,String cursor){String hash=hash(text);String after=after(cursor,tenant,"available-users",hash);List<Map<String,Object>> rows=inTenant(tenant,"projection:available-users",()->dao.listAvailableUsers(tenant,text,after,limit+1));return cursorPage(rows,limit,tenant,"available-users",hash,"userId",this::user);}
 public Optional<UserResponse> user(String tenant,String id){return inTenant(tenant,"projection:user",()->Optional.ofNullable(dao.findTenantUser(tenant,id)).map(this::user));}
 public UserOrganizationScopeResponse userOrganizationScope(String tenant,String userId){List<Map<String,Object>>rows=inTenant(tenant,"projection:user-organization-scope",()->dao.findActiveUserOrganizationScopes(tenant,userId));Set<String>departments=new LinkedHashSet<>();Set<String>groups=new LinkedHashSet<>();for(Map<String,Object>row:rows){String type=s(row,"scopeType"),id=s(row,"scopeId");if("DEPARTMENT".equals(type)&&!id.isBlank())departments.add(id);else if("GROUP".equals(type)&&!id.isBlank())groups.add(id);}return new UserOrganizationScopeResponse(tenant,userId,departments,groups);}
 public UserAuthenticationReadinessResponse userAuthenticationReadiness(String tenant,String userId){Map<String,Object>r=inTenant(tenant,"projection:user-authentication-readiness",()->dao.findUserAuthenticationReadiness(tenant,userId));if(r==null)throw new IllegalArgumentException("IDENTITY_USER_NOT_FOUND");String account=s(r,"accountStatus"),password=s(r,"passwordState"),mfa=s(r,"mfaState"),federated=s(r,"federatedProviderType");boolean sso=!federated.isBlank();List<String>blocking=new ArrayList<>();if(!sso){if("PENDING_ACTIVATION".equals(account))blocking.add("ACTIVATE_ACCOUNT");if("NOT_CONFIGURED".equals(password))blocking.add("SET_PASSWORD");else if("CHANGE_REQUIRED".equals(password))blocking.add("CHANGE_PASSWORD");if("MFA_ENROLLMENT_REQUIRED".equals(account)||"PENDING".equals(mfa))blocking.add("ENROLL_MFA");}if(Set.of("SUSPENDED","DISABLED","LOCKED","DELETED").contains(account))blocking.add("REACTIVATE_ACCOUNT");boolean locked="LOCKED".equals(account)||(i(r,"lockedUntil")!=null&&i(r,"lockedUntil").isAfter(Instant.now()));boolean federationEligible=sso&&Set.of("ACTIVE","PENDING_ACTIVATION","PASSWORD_RESET_REQUIRED","MFA_ENROLLMENT_REQUIRED").contains(account);String signInState=locked?"LOCKED":"SUSPENDED".equals(account)?"SUSPENDED":Set.of("DISABLED","DELETED").contains(account)?"DISABLED":federationEligible?"SSO_MANAGED":"NOT_CONFIGURED".equals(password)||Set.of("PENDING_ACTIVATION","PASSWORD_RESET_REQUIRED").contains(account)?"SETUP_REQUIRED":"MFA_ENROLLMENT_REQUIRED".equals(account)||"PENDING".equals(mfa)?"MFA_REQUIRED":"ACTIVE".equals(account)&&"CONFIGURED".equals(password)?"READY":"SETUP_REQUIRED";boolean ready=("READY".equals(signInState)&&"ACTIVE".equals(account)||"SSO_MANAGED".equals(signInState))&&blocking.isEmpty();String method=sso?("NOT_CONFIGURED".equals(password)?federated:"LOCAL+"+federated):"LOCAL";return new UserAuthenticationReadinessResponse(tenant,userId,method,account,signInState,ready,password,i(r,"passwordChangedAt"),i(r,"passwordExpiresAt"),mfa,s(r,"mfaType"),i(r,"mfaVerifiedAt"),l(r,"recoveryCodesRemaining"),i(r,"lastSuccessfulLogin"),l(r,"failedLoginCount"),i(r,"lockedUntil"),l(r,"activeSessionCount"),s(r,"setupState"),i(r,"setupExpiresAt"),s(r,"deliveryMethod"),s(r,"deliveryStatus"),s(r,"deliveryReference"),s(r,"deliveryFailureCode"),blocking);}
 public MachineOwnershipImpactResponse machineOwnershipImpact(String tenant,String userId){Map<String,Object>r=inTenant(tenant,"projection:machine-ownership-impact",()->dao.findMachineOwnershipImpact(tenant,userId));long sa=r==null?0:l(r,"serviceAccountCount"),owner=r==null?0:l(r,"agentBusinessOwnerCount"),steward=r==null?0:l(r,"agentTechnicalStewardCount"),review=r==null?0:l(r,"ownershipReviewRequiredCount");return new MachineOwnershipImpactResponse(sa,owner,steward,review,sa+owner+steward>0);}
 public OffsetPage<TenantResponse> tenants(int page,int size,String text,String status){List<Map<String,Object>> rows=inTenant("INSTANCE","projection:tenants",()->dao.listTenants(text,status,page*size,size+1));return offset(rows,page,size,this::tenant);}
 public TenantWorkspaceSummaryResponse tenantWorkspaceSummary(String tenant){Map<String,Object>r=inTenant(tenant,"projection:tenant-workspace-summary",()->dao.tenantWorkspaceSummary(tenant));return new TenantWorkspaceSummaryResponse(s(r,"tenantId"),l(r,"activePeople"),l(r,"tenantAdministratorCount"),l(r,"pendingInvitations"),l(r,"signInSetupRequiredCount"),l(r,"mfaEnrolledPeople"),l(r,"suspendedPeople"),l(r,"peopleWithoutDepartment"),l(r,"departmentCount"),l(r,"departmentsWithoutManager"),l(r,"groupCount"),l(r,"activeRoleCount"),l(r,"activeBindingCount"),l(r,"expiringBindingCount"));}
 public OffsetPage<DepartmentResponse> departments(String tenant,int page,int size,String text,String status){return offset(inTenant(tenant,"projection:departments",()->dao.listDepartments(tenant,text,status,page*size,size+1)),page,size,this::department);}
 public OffsetPage<DepartmentResponse> departmentsWithin(String tenant,Set<String> ids,int page,int size,String text,String status){if(ids==null||ids.isEmpty())return new OffsetPage<>(List.of(),page,size,false,0L);return offset(inTenant(tenant,"projection:departments-scoped",()->dao.listDepartmentsWithin(tenant,ids,text,status,page*size,size+1)),page,size,this::department);}
 public Set<String> departmentIdsWithinSubtrees(String tenant,Set<String> roots){if(roots==null||roots.isEmpty())return Set.of();return Set.copyOf(inTenant(tenant,"projection:department-subtrees",()->dao.listDepartmentIdsWithinSubtrees(tenant,roots)));}
 public OffsetPage<GroupResponse> groups(String tenant,int page,int size,String text,String type,String status){return offset(inTenant(tenant,"projection:groups",()->dao.listGroups(tenant,text,type,status,page*size,size+1)),page,size,this::group);}
 public OffsetPage<GroupResponse> groupsWithin(String tenant,Set<String> ids,int page,int size,String text,String type,String status){if(ids==null||ids.isEmpty())return new OffsetPage<>(List.of(),page,size,false,0L);return offset(inTenant(tenant,"projection:groups-scoped",()->dao.listGroupsWithin(tenant,ids,text,type,status,page*size,size+1)),page,size,this::group);}
 public OrganizationRetirementPreviewResponse departmentRetirementPreview(String tenant,String departmentId){Map<String,Object>r=inTenant(tenant,"projection:department-retirement-preview",()->dao.departmentRetirementPreview(tenant,departmentId));if(r==null)throw new IllegalArgumentException("DEPARTMENT_NOT_FOUND");return retirementPreview(r);}
 public OrganizationRetirementPreviewResponse groupRetirementPreview(String tenant,String groupId){Map<String,Object>r=inTenant(tenant,"projection:group-retirement-preview",()->dao.groupRetirementPreview(tenant,groupId));if(r==null)throw new IllegalArgumentException("GROUP_NOT_FOUND");return retirementPreview(r);}
 public CursorPage<MembershipResponse> memberships(String tenant,String user,int limit,String cursor){String hash=hash(user);String after=after(cursor,tenant,"memberships",hash);List<Map<String,Object>>rows=inTenant(tenant,"projection:memberships",()->dao.listMemberships(tenant,user,after,limit+1));return cursorPage(rows,limit,tenant,"memberships",hash,"membershipId",this::membership);}
 public Optional<MembershipResponse> membership(String tenant,String membershipId){return inTenant(tenant,"projection:membership",()->Optional.ofNullable(dao.findMembership(tenant,membershipId)).map(this::membership));}
 public CursorPage<MembershipResponse> tenantMemberships(String tenant,int limit,String cursor){String hash=hash(tenant);String after=after(cursor,tenant,"tenant-members",hash);List<Map<String,Object>>rows=inTenant(tenant,"projection:tenant-members",()->dao.listTenantMemberships(tenant,after,limit+1));return cursorPage(rows,limit,tenant,"tenant-members",hash,"membershipId",this::membership);}
 public CursorPage<MembershipResponse> departmentMembers(String tenant,String department,int limit,String cursor){String hash=hash(department);String after=after(cursor,tenant,"department-members",hash);List<Map<String,Object>>rows=inTenant(tenant,"projection:department-members",()->dao.listDepartmentMembers(tenant,department,after,limit+1));return cursorPage(rows,limit,tenant,"department-members",hash,"membershipId",this::membership);}
 public CursorPage<MembershipResponse> groupMembers(String tenant,String group,int limit,String cursor){String hash=hash(group);String after=after(cursor,tenant,"group-members",hash);List<Map<String,Object>>rows=inTenant(tenant,"projection:group-members",()->dao.listGroupMembers(tenant,group,after,limit+1));return cursorPage(rows,limit,tenant,"group-members",hash,"membershipId",this::membership);}
 public CursorPage<UserResponse> eligibleDepartmentManagers(String tenant,String department,String text,int limit,String cursor){String hash=hash(department,text);String after=after(cursor,tenant,"eligible-department-managers",hash);List<Map<String,Object>>rows=inTenant(tenant,"projection:eligible-department-managers",()->dao.listEligibleDepartmentManagers(tenant,department,text,after,limit+1));return cursorPage(rows,limit,tenant,"eligible-department-managers",hash,"userId",this::user);}
 public OffsetPage<RoleResponse> roles(String tenant,int page,int size,String text,String type,String status){return offset(inTenant(tenant,"projection:roles",()->dao.listRoles(tenant,text,type,status,page*size,size+1)),page,size,this::role);}
 public OffsetPage<ResponsibilityTemplateResponse> responsibilityTemplates(String tenant,int page,int size,String text,String status,String risk,String scope){return offset(inTenant(tenant,"projection:responsibility-templates",()->dao.listResponsibilityTemplates(tenant,text,status,risk,scope,page*size,size+1)),page,size,this::responsibilityTemplate);}
 public CursorPage<AccessAssignmentResponse> accessAssignments(String tenant,String text,String status,String principalType,String scopeType,String lifecycle,int limit,String cursor){String hash=hash(text,status,principalType,scopeType,lifecycle);String after=after(cursor,tenant,"access-assignments",hash);List<Map<String,Object>>rows=inTenant(tenant,"projection:access-assignments",()->dao.listAccessAssignments(tenant,text,status,principalType,scopeType,lifecycle,after,limit+1));return cursorPage(rows,limit,tenant,"access-assignments",hash,"bindingId",this::accessAssignment);}
 public AccessLifecycleSummaryResponse accessLifecycleSummary(String tenant){Map<String,Object>r=inTenant(tenant,"projection:access-lifecycle-summary",()->dao.accessLifecycleSummary(tenant));return new AccessLifecycleSummaryResponse(s(r,"tenantId"),l(r,"activeAssignments"),l(r,"expiringAssignments"),l(r,"expiredAssignments"),l(r,"scheduledAssignments"),l(r,"pendingApprovals"),l(r,"criticalAssignments"),l(r,"reviewDueAssignments"),l(r,"orphanAssignments"));}
 public CursorPage<AccessReviewCandidateResponse> accessReviewCandidates(String tenant,String reason,String risk,int limit,String cursor){String hash=hash(reason,risk);String after=after(cursor,tenant,"access-review-candidates",hash);List<Map<String,Object>>rows=inTenant(tenant,"projection:access-review-candidates",()->dao.listAccessReviewCandidates(tenant,reason,risk,after,limit+1));return cursorPage(rows,limit,tenant,"access-review-candidates",hash,"bindingId",this::accessReviewCandidate);}
 public SecurityWorkspaceSummaryResponse securityWorkspaceSummary(String tenant){Map<String,Object>r=inTenant(tenant,"projection:security-workspace-summary",()->dao.securityWorkspaceSummary(tenant));return new SecurityWorkspaceSummaryResponse(s(r,"tenantId"),l(r,"activeSessions"),l(r,"sessionsExpiringSoon"),l(r,"activeServiceAccounts"),l(r,"serviceAccountsReviewDue"),l(r,"activeTokens"),l(r,"tokensExpiringSoon"),l(r,"dormantTokens"),l(r,"deniedDecisions24h"),l(r,"administrativeChanges24h"));}
 public CredentialGovernanceCatalogResponse credentialGovernanceCatalog(String tenant){return inTenant(tenant,"projection:credential-governance-catalog",()->new CredentialGovernanceCatalogResponse(dao.listCredentialApiProducts().stream().map(this::credentialProduct).toList(),dao.listCredentialAudiences().stream().map(this::credentialAudience).toList(),dao.listCredentialMachineScopes().stream().map(this::credentialMachineScope).toList(),dao.listCredentialSourceSystems(tenant).stream().map(this::credentialSourceSystem).toList()));}
 public CursorPage<HumanReadableAuditResponse> humanReadableAudit(String tenant,String category,String outcome,int limit,String cursor){String hash=hash(category,outcome);String after=after(cursor,tenant,"human-readable-audit",hash);List<Map<String,Object>>rows=inTenant(tenant,"projection:human-readable-audit",()->dao.listHumanReadableAudit(tenant,category,outcome,after,limit+1));return cursorPage(rows,limit,tenant,"human-readable-audit",hash,"eventId",this::humanReadableAuditEvent);}
 public CursorPage<SecurityPolicyRevisionResponse> securityPolicyRevisions(String tenant,String kind,int limit,String cursor){String hash=hash(kind);String after=after(cursor,tenant,"security-policy-revisions",hash);List<Map<String,Object>>rows=inTenant(tenant,"projection:security-policy-revisions",()->dao.listSecurityPolicyRevisions(tenant,kind,after,limit+1));return cursorPage(rows,limit,tenant,"security-policy-revisions",hash,"revisionId",this::securityPolicyRevision);}
 public OffsetPage<RoleResponse> platformRoles(int page,int size,String text,String type,String status){return offset(transactions.execute(x->dao.listPlatformRoles(text,type,status,page*size,size+1)),page,size,this::role);}
 public OffsetPage<PermissionResponse> permissions(int page,int size,String text,String scope){return offset(transactions.execute(s->dao.listPermissions(text,scope,page*size,size+1)),page,size,this::permission);}
 public List<PermissionResponse> rolePermissions(String tenant,String roleId){if(tenant==null||tenant.isBlank())return transactions.execute(x->dao.listRolePermissions(null,roleId)).stream().map(this::permission).toList();return inTenant(tenant,"projection:role-permissions",()->dao.listRolePermissions(tenant,roleId)).stream().map(this::permission).toList();}
 public CursorPage<RoleBindingResponse> roleBindings(String tenant,String roleId,String principal,int limit,String cursor){String scope=tenant==null||tenant.isBlank()?"INSTANCE":tenant;String hash=hash(roleId,principal);String after=after(cursor,scope,"bindings",hash);List<Map<String,Object>>rows=tenant==null||tenant.isBlank()?transactions.execute(x->dao.listRoleBindings(null,roleId,principal,after,limit+1)):inTenant(tenant,"projection:bindings",()->dao.listRoleBindings(tenant,roleId,principal,after,limit+1));return cursorPage(rows,limit,scope,"bindings",hash,"bindingId",this::binding);}
 public CursorPage<SessionResponse> sessions(String tenant,String subject,int limit,String cursor){String hash=hash(subject);String after=after(cursor,tenant,"sessions",hash);List<Map<String,Object>>rows=inTenant(tenant,"projection:sessions",()->dao.listSessions(tenant,subject,after,limit+1));return cursorPage(rows,limit,tenant,"sessions",hash,"sessionId",this::session);}
 public CursorPage<ServiceAccountResponse> serviceAccounts(String tenant,int limit,String cursor,String status){String hash=hash(status);String after=after(cursor,tenant,"service-accounts",hash);List<Map<String,Object>>rows=inTenant(tenant,"projection:service-accounts",()->dao.listServiceAccounts(tenant,status,after,limit+1));return cursorPage(rows,limit,tenant,"service-accounts",hash,"serviceAccountId",this::serviceAccount);}
 public CursorPage<ServiceAccountCredentialResponse> serviceAccountCredentials(String tenant,String serviceAccountId,int limit,String cursor,String status){String hash=hash(serviceAccountId,status);String after=after(cursor,tenant,"service-account-credentials",hash);List<Map<String,Object>>rows=inTenant(tenant,"projection:service-account-credentials",()->dao.listServiceAccountCredentials(tenant,serviceAccountId,status,after,limit+1));return cursorPage(rows,limit,tenant,"service-account-credentials",hash,"credentialId",this::serviceAccountCredential);}
 public CursorPage<TokenSummaryResponse> tokens(String tenant,String principal,int limit,String cursor,String status){String hash=hash(principal,status);String after=after(cursor,tenant,"tokens",hash);List<Map<String,Object>>rows=inTenant(tenant,"projection:tokens",()->dao.listTokens(tenant,principal,status,after,limit+1));return cursorPage(rows,limit,tenant,"tokens",hash,"tokenId",this::token);}
 public CursorPage<IdentityAuditResponse> identityAudit(String tenant,int limit,String cursor,String event,String actor,String target){String hash=hash(event,actor,target);String after=after(cursor,tenant,"identity-audit",hash);List<Map<String,Object>>rows=inTenant(tenant,"projection:audit",()->dao.listIdentityAudit(tenant,event,actor,target,after,limit+1));return cursorPage(rows,limit,tenant,"identity-audit",hash,"eventId",this::audit);}
 private <T> T inTenant(String tenant,String actor,Supplier<T> action){return IamTenantContextHolder.withContext(new IamTenantExecutionContext(tenant,actor),()->transactions.execute(s->action.get()));}
 private String after(String cursor,String tenant,String resource,String filter){if(cursor==null||cursor.isBlank())return "";return cursors.decode(cursor,tenant,resource,filter).lastUniqueId();}
 private <T>CursorPage<T> cursorPage(List<Map<String,Object>> rows,int limit,String tenant,String resource,String filter,String id,java.util.function.Function<Map<String,Object>,T> mapper){boolean more=rows.size()>limit;List<Map<String,Object>> page=more?rows.subList(0,limit):rows;String next="";if(more&&!page.isEmpty()){String last=s(page.get(page.size()-1),id);next=cursors.encode(new CursorPayload(tenant,resource,id,"ASC",last,last,filter,Instant.EPOCH));}return new CursorPage<>(page.stream().map(mapper).toList(),next,more);}
 private <T>OffsetPage<T> offset(List<Map<String,Object>> rows,int page,int size,java.util.function.Function<Map<String,Object>,T> mapper){boolean more=rows.size()>size;List<Map<String,Object>> values=more?rows.subList(0,size):rows;return new OffsetPage<>(values.stream().map(mapper).toList(),page,size,more,null);}
 private PlatformTenantMembershipResponse platformMembership(Map<String,Object>r){return new PlatformTenantMembershipResponse(s(r,"userId"),s(r,"tenantId"),s(r,"tenantCode"),s(r,"tenantName"),s(r,"membershipStatus"),s(r,"tenantStatus"),i(r,"expiresAt"),b(r,"defaultTenant"),s(r,"membershipSource"),l(r,"membershipVersion"),i(r,"updatedAt"));}
 private UserResponse user(Map<String,Object>r){return new UserResponse(s(r,"userId"),s(r,"username"),s(r,"email"),s(r,"displayName"),s(r,"status"),s(r,"creationMode"),i(r,"createdAt"),i(r,"updatedAt"),l(r,"version"),defaultIfBlank(s(r,"authenticationMethod"),"LOCAL"),defaultIfBlank(s(r,"signInState"),signInFromAccount(s(r,"status"))),s(r,"passwordState"),s(r,"mfaState"),defaultIfBlank(s(r,"deliveryStatus"),"NOT_ISSUED"),defaultIfBlank(s(r,"accessReadiness"),"NO_RESPONSIBILITY"),s(r,"responsibilitySummary"));}
 private static String defaultIfBlank(String value,String fallback){return value==null||value.isBlank()?fallback:value;}
 private static String signInFromAccount(String status){return switch(status){case "ACTIVE"->"READY";case "MFA_ENROLLMENT_REQUIRED"->"MFA_REQUIRED";case "LOCKED"->"LOCKED";case "SUSPENDED"->"SUSPENDED";case "DISABLED","DELETED"->"DISABLED";default->"SETUP_REQUIRED";};}
 private TenantResponse tenant(Map<String,Object>r){return new TenantResponse(s(r,"tenantId"),s(r,"tenantCode"),s(r,"tenantName"),s(r,"legalName"),s(r,"status"),s(r,"timezone"),s(r,"locale"),s(r,"dataRegion"),i(r,"createdAt"),i(r,"updatedAt"),l(r,"version"));}
 private DepartmentResponse department(Map<String,Object>r){return new DepartmentResponse(s(r,"tenantId"),s(r,"departmentId"),s(r,"code"),s(r,"name"),s(r,"parentDepartmentId"),s(r,"managerUserId"),s(r,"status"),n(r,"displayOrder"),i(r,"createdAt"),i(r,"updatedAt"),l(r,"version"));}
 private GroupResponse group(Map<String,Object>r){return new GroupResponse(s(r,"tenantId"),s(r,"groupId"),s(r,"code"),s(r,"name"),s(r,"type"),s(r,"parentGroupId"),s(r,"ownerDepartmentId"),s(r,"status"),s(r,"description"),i(r,"createdAt"),i(r,"updatedAt"),l(r,"version"));}
 private OrganizationRetirementPreviewResponse retirementPreview(Map<String,Object>r){long source=l(r,"sourceSystemCount"),flow=l(r,"dispatchFlowCount"),pool=l(r,"agentPoolCount"),a2a=l(r,"a2aPolicyCount"),hard=source+flow+pool+a2a;return new OrganizationRetirementPreviewResponse(s(r,"tenantId"),s(r,"organizationType"),s(r,"organizationId"),s(r,"organizationName"),l(r,"peopleCount"),l(r,"primaryPeopleCount"),l(r,"childCount"),l(r,"ownedGroupCount"),l(r,"activeRoleBindingCount"),source,flow,pool,a2a,hard,hard==0);}
 private MembershipResponse membership(Map<String,Object>r){return new MembershipResponse(s(r,"membershipId"),s(r,"membershipType"),s(r,"tenantId"),s(r,"userId"),s(r,"resourceId"),s(r,"role"),s(r,"status"),b(r,"primary"),i(r,"effectiveAt"),i(r,"expiresAt"),l(r,"version"),s(r,"employeeId"));}
 private RoleResponse role(Map<String,Object>r){return new RoleResponse(s(r,"roleId"),s(r,"tenantId"),s(r,"roleCode"),s(r,"roleName"),s(r,"description"),s(r,"roleType"),s(r,"status"),b(r,"systemManaged"),i(r,"createdAt"),i(r,"updatedAt"),l(r,"version"));}
 private ResponsibilityTemplateResponse responsibilityTemplate(Map<String,Object>r){return new ResponsibilityTemplateResponse(s(r,"roleId"),s(r,"tenantId"),s(r,"roleCode"),s(r,"roleName"),s(r,"description"),s(r,"roleType"),s(r,"status"),b(r,"systemManaged"),s(r,"riskLevel"),b(r,"reviewRequired"),i(r,"nextReviewAt"),l(r,"permissionCount"),l(r,"assignmentCount"),l(r,"activeAssignmentCount"),l(r,"expiringAssignmentCount"),set(s(r,"allowedScopesCsv")),set(s(r,"capabilitiesCsv")),set(s(r,"allowedPrincipalsCsv")),l(r,"version"));}
 private AccessAssignmentResponse accessAssignment(Map<String,Object>r){return new AccessAssignmentResponse(s(r,"bindingId"),s(r,"principalType"),s(r,"principalId"),s(r,"principalName"),s(r,"roleId"),s(r,"roleCode"),s(r,"roleName"),s(r,"riskLevel"),s(r,"scopeType"),s(r,"scopeId"),s(r,"scopeName"),i(r,"effectiveAt"),i(r,"expiresAt"),s(r,"status"),s(r,"lifecycleStatus"),b(r,"reviewRequired"),i(r,"nextReviewAt"),l(r,"version"));}
 private AccessReviewCandidateResponse accessReviewCandidate(Map<String,Object>r){return new AccessReviewCandidateResponse(s(r,"bindingId"),s(r,"principalType"),s(r,"principalId"),s(r,"principalName"),s(r,"roleId"),s(r,"roleCode"),s(r,"roleName"),s(r,"riskLevel"),s(r,"scopeType"),s(r,"scopeId"),s(r,"scopeName"),i(r,"effectiveAt"),i(r,"expiresAt"),i(r,"nextReviewAt"),i(r,"lastReviewedAt"),s(r,"reviewReason"),l(r,"version"));}
 private CredentialApiProductResponse credentialProduct(Map<String,Object>r){return new CredentialApiProductResponse(s(r,"productCode"),s(r,"displayName"),s(r,"description"),set(s(r,"audiencesCsv")),set(s(r,"apiPrefixesCsv")));}
 private CredentialAudienceResponse credentialAudience(Map<String,Object>r){return new CredentialAudienceResponse(s(r,"audienceCode"),s(r,"displayName"),s(r,"description"));}
 private CredentialMachineScopeResponse credentialMachineScope(Map<String,Object>r){return new CredentialMachineScopeResponse(s(r,"scopeCode"),s(r,"displayName"),s(r,"description"));}
 private CredentialSourceSystemResponse credentialSourceSystem(Map<String,Object>r){return new CredentialSourceSystemResponse(s(r,"sourceSystemId"),s(r,"displayName"),s(r,"description"),s(r,"status"));}
 private HumanReadableAuditResponse humanReadableAuditEvent(Map<String,Object>r){return new HumanReadableAuditResponse(s(r,"eventId"),s(r,"category"),s(r,"action"),s(r,"summary"),s(r,"actorId"),s(r,"actorName"),s(r,"targetType"),s(r,"targetId"),s(r,"targetName"),s(r,"outcome"),s(r,"reason"),s(r,"correlationId"),i(r,"occurredAt"),s(r,"technicalEvidence"));}
 private SecurityPolicyRevisionResponse securityPolicyRevision(Map<String,Object>r){return new SecurityPolicyRevisionResponse(s(r,"revisionId"),s(r,"tenantId"),s(r,"policyKind"),l(r,"policyVersion"),s(r,"policyJson"),s(r,"actorId"),s(r,"auditReason"),s(r,"correlationId"),i(r,"createdAt"));}
 private PermissionResponse permission(Map<String,Object>r){return new PermissionResponse(s(r,"permissionCode"),s(r,"displayName"),s(r,"description"),set(s(r,"allowedScopesCsv")),b(r,"systemManaged"));}
 private RoleBindingResponse binding(Map<String,Object>r){return new RoleBindingResponse(s(r,"bindingId"),s(r,"principalType"),s(r,"principalId"),s(r,"roleId"),s(r,"scopeType"),s(r,"scopeId"),i(r,"effectiveAt"),i(r,"expiresAt"),s(r,"status"),l(r,"version"));}
 private SessionResponse session(Map<String,Object>r){return new SessionResponse(s(r,"sessionId"),s(r,"subjectType"),s(r,"subjectId"),s(r,"tenantId"),set(s(r,"methodsCsv")),i(r,"createdAt"),i(r,"lastSeenAt"),i(r,"idleExpiresAt"),i(r,"absoluteExpiresAt"),s(r,"ipAddress"),s(r,"userAgent"),s(r,"status"),l(r,"version"));}
 private ServiceAccountResponse serviceAccount(Map<String,Object>r){return new ServiceAccountResponse(s(r,"tenantId"),s(r,"serviceAccountId"),s(r,"name"),s(r,"description"),s(r,"ownerUserId"),s(r,"ownerDepartmentId"),s(r,"responsibilityBindingId"),s(r,"responsibilityRoleId"),set(s(r,"permissionsCsv")),set(s(r,"audiencesCsv")),set(s(r,"apiPrefixesCsv")),set(s(r,"cidrsCsv")),set(s(r,"machineScopesCsv")),set(s(r,"sourceSystemsCsv")),l(r,"tokenMaxTtlSeconds"),n(r,"maxActiveTokens"),l(r,"credentialMaxTtlSeconds"),n(r,"maxActiveCredentials"),n(r,"rateLimitPerMinute"),i(r,"nextReviewAt"),s(r,"riskLevel"),s(r,"status"),l(r,"version"));}
 private ServiceAccountCredentialResponse serviceAccountCredential(Map<String,Object>r){return new ServiceAccountCredentialResponse(s(r,"tenantId"),s(r,"credentialId"),s(r,"serviceAccountId"),s(r,"credentialType"),s(r,"name"),s(r,"clientId"),s(r,"last4"),s(r,"status"),i(r,"issuedAt"),i(r,"expiresAt"),i(r,"lastUsedAt"),i(r,"rotationGraceExpiresAt"),l(r,"useCount"),l(r,"version"));}
 private TokenSummaryResponse token(Map<String,Object>r){return new TokenSummaryResponse(s(r,"tokenId"),s(r,"tokenType"),s(r,"principalType"),s(r,"principalId"),s(r,"name"),s(r,"prefix"),s(r,"last4"),s(r,"status"),i(r,"issuedAt"),i(r,"expiresAt"),i(r,"lastUsedAt"),l(r,"version"));}
 private IdentityAuditResponse audit(Map<String,Object>r){return new IdentityAuditResponse(s(r,"eventId"),s(r,"eventType"),s(r,"actorType"),s(r,"actorId"),s(r,"targetType"),s(r,"targetId"),s(r,"tenantId"),s(r,"permission"),s(r,"decisionId"),s(r,"correlationId"),s(r,"reason"),i(r,"occurredAt"));}
 private static String hash(String...v){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(String.join("\u001f",v==null?new String[0]:java.util.Arrays.stream(v).map(x->x==null?"":x).toArray(String[]::new)).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private static String s(Map<String,Object>r,String k){Object v=r.get(k);return v==null?"":String.valueOf(v);}private static long l(Map<String,Object>r,String k){Object v=r.get(k);return v instanceof Number n?n.longValue():Long.parseLong(String.valueOf(v));}private static int n(Map<String,Object>r,String k){Object v=r.get(k);return v instanceof Number n?n.intValue():Integer.parseInt(String.valueOf(v));}private static boolean b(Map<String,Object>r,String k){Object v=r.get(k);return v instanceof Boolean x?x:Boolean.parseBoolean(String.valueOf(v));}private static Instant i(Map<String,Object>r,String k){Object v=r.get(k);if(v==null)return null;if(v instanceof Instant x)return x;if(v instanceof java.time.OffsetDateTime x)return x.toInstant();if(v instanceof java.sql.Timestamp x)return x.toInstant();return Instant.parse(String.valueOf(v));}private static Set<String> set(String v){return v==null||v.isBlank()?Set.of():Set.copyOf(Arrays.asList(v.split("\u001f",-1)));}
}
