package com.opensocket.aievent.core.iam.organization.domain;

public final class OrganizationReasonCode {
    public static final String VERSION_CONFLICT = "ORGANIZATION_VERSION_CONFLICT";
    public static final String CROSS_TENANT_REFERENCE = "ORGANIZATION_CROSS_TENANT_REFERENCE";
    public static final String INVALID_STATUS_TRANSITION = "ORGANIZATION_INVALID_STATUS_TRANSITION";
    public static final String DEPARTMENT_CYCLE_DETECTED = "DEPARTMENT_CYCLE_DETECTED";
    public static final String DEPARTMENT_MAX_DEPTH_EXCEEDED = "DEPARTMENT_MAX_DEPTH_EXCEEDED";
    public static final String DEPARTMENT_PARENT_NOT_FOUND = "DEPARTMENT_PARENT_NOT_FOUND";
    public static final String DEPARTMENT_PARENT_DISABLED = "DEPARTMENT_PARENT_DISABLED";
    public static final String PRINCIPAL_TYPE_UNSUPPORTED = "ORGANIZATION_PRINCIPAL_TYPE_UNSUPPORTED";
    public static final String PRIMARY_DEPARTMENT_CONFLICT = "PRIMARY_DEPARTMENT_CONFLICT";
    public static final String PRIMARY_DEPARTMENT_REPLACEMENT_REQUIRED = "PRIMARY_DEPARTMENT_REPLACEMENT_REQUIRED";
    public static final String PRIMARY_DEPARTMENT_REPLACEMENT_INVALID = "PRIMARY_DEPARTMENT_REPLACEMENT_INVALID";
    public static final String OFFICIAL_MANAGER_TENANT_MEMBERSHIP_REQUIRED = "OFFICIAL_MANAGER_TENANT_MEMBERSHIP_REQUIRED";
    public static final String ACTIVE_TENANT_MEMBERSHIP_REQUIRED = "ACTIVE_TENANT_MEMBERSHIP_REQUIRED";
    public static final String TENANT_MEMBERSHIP_NOT_ASSIGNABLE = "TENANT_MEMBERSHIP_NOT_ASSIGNABLE";
    public static final String TENANT_MEMBERSHIP_ALREADY_EXISTS = "TENANT_MEMBERSHIP_ALREADY_EXISTS";
    public static final String DEPARTMENT_ID_CONFLICT = "DEPARTMENT_ID_CONFLICT";
    public static final String DEPARTMENT_CODE_CONFLICT = "DEPARTMENT_CODE_CONFLICT";
    public static final String GROUP_ID_CONFLICT = "GROUP_ID_CONFLICT";
    public static final String GROUP_CODE_CONFLICT = "GROUP_CODE_CONFLICT";
    public static final String OFFICIAL_MANAGER_ASSIGNMENT_BLOCKS_USER_STATUS = "OFFICIAL_MANAGER_ASSIGNMENT_BLOCKS_USER_STATUS";
    public static final String DEPARTMENT_DISABLE_BLOCKED = "DEPARTMENT_DISABLE_BLOCKED";
    public static final String GROUP_CYCLE_DETECTED = "GROUP_CYCLE_DETECTED";
    public static final String GROUP_OWNER_DEPARTMENT_DISABLED = "GROUP_OWNER_DEPARTMENT_DISABLED";
    public static final String GROUP_DISABLE_BLOCKED = "GROUP_DISABLE_BLOCKED";

    private OrganizationReasonCode() { }
}
