'use client';
import { useCallback,useEffect,useState } from 'react';
import { useAuth } from '@/components/auth/AuthProvider';
import { ErrorBox } from '@/components/common/ErrorBox';
import { HighRiskActionDialog } from '@/components/iam/HighRiskActionDialog';
import { ResourceAccessShell } from './ResourceAccessShell';
import { ResourceAccessBadge } from './ResourceAccessBadge';
import { VirtualizedGovernanceList } from './VirtualizedGovernanceList';
import { OrphanRepairSafetyPanel } from '@/components/phase7e/OrphanRepairSafetyPanel';
import { OwnershipTransferImpactPanel } from '@/components/phase7e/OwnershipTransferImpactPanel';
import { assignOrphanOwner,listOrphans,previewOrphanRepair,type OrphanOwnerBody,type OrphanRepairImpactPreview,type OrphanView } from '@/lib/api/domains/resourceAccessApi';

export function OrphanRepairWorkspace(){
 const {hasPermission}=useAuth();
 const [items,setItems]=useState<OrphanView[]>([]);const [selected,setSelected]=useState<OrphanView|null>(null);
 const [search,setSearch]=useState('');const [nextCursor,setNextCursor]=useState('');const [total,setTotal]=useState(0);
 const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const load=useCallback(async(reset=true,cursor='')=>{setBusy(true);setError('');try{const page=await listOrphans({status:'OPEN',search,cursor:reset?'':cursor,limit:100});setItems(current=>reset?page.items:[...current,...page.items]);setNextCursor(page.nextCursor??'');setTotal(page.totalCount);if(reset)setSelected(current=>current?page.items.find(v=>v.repairId===current.repairId)??null:null)}catch(e){setError(text(e))}finally{setBusy(false)}},[search]);
 useEffect(()=>{void load(true)},[load]);
 return <ResourceAccessShell title="Orphan Resources" description="Resources without a canonical owner fail closed. Preview the blast radius, then assign ownership through the originating Domain authority with optimistic locking and immutable evidence."><OrphanRepairSafetyPanel/>{message?<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-900">{message}</div>:null}{error?<ErrorBox message={error}/>:null}<section className="rounded-2xl border border-slate-200 bg-white p-4"><form className="flex gap-3" onSubmit={e=>{e.preventDefault();void load(true)}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search resource ID, key, or repair ID" className="flex-1 rounded-xl border border-slate-300 px-4 py-2.5"/><button disabled={busy} className="rounded-xl bg-slate-900 px-5 py-2.5 font-black text-white disabled:opacity-50">Search</button></form><p className="mt-3 text-xs font-semibold text-slate-500">{items.length.toLocaleString()} loaded of {total.toLocaleString()} · virtualized, Tenant-bound cursor query</p></section><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_24rem]"><div className="space-y-3"><VirtualizedGovernanceList items={items} getItemKey={item=>item.repairId} height={680} rowHeight={104} renderRow={item=><button type="button" onClick={()=>setSelected(item)} className={`grid h-full w-full grid-cols-[minmax(0,1fr)_auto] items-center gap-4 rounded-xl border p-4 text-left shadow-sm ${selected?.repairId===item.repairId?'border-rose-300 bg-rose-50':'border-slate-200 bg-white'}`}><div className="min-w-0"><div className="flex flex-wrap gap-2"><span className="truncate font-black text-slate-950">{item.resourceType} · {item.resourceKey||item.resourceId}</span><ResourceAccessBadge value={item.repairStatus}/></div><p className="mt-1 truncate text-xs text-slate-500">{item.repairId} · {item.reasonCode}</p></div><div className="text-right text-xs text-slate-500">Resource v{item.resourceVersion}<br/>Case v{item.version}</div></button>}/>{nextCursor?<button type="button" disabled={busy} onClick={()=>void load(false,nextCursor)} className="w-full rounded-xl border border-indigo-300 bg-indigo-50 px-4 py-3 font-black text-indigo-800 disabled:opacity-50">Load next page</button>:null}</div>{selected?<RepairPanel item={selected} canRepair={hasPermission('resource.orphan.repair')} busy={busy} onBusy={setBusy} onError={setError} onApplied={async()=>{setMessage('Canonical ownership assigned. Resource projection and security epoch were refreshed.');setSelected(null);await load(true)}}/>:<aside className="sticky top-24 h-fit rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6 text-sm text-slate-500">Select an orphan resource to prepare an impact preview.</aside>}</div></ResourceAccessShell>;
}

function RepairPanel({item,canRepair,busy,onBusy,onError,onApplied}:Readonly<{item:OrphanView;canRepair:boolean;busy:boolean;onBusy:(v:boolean)=>void;onError:(v:string)=>void;onApplied:()=>Promise<void>}>){
 const [department,setDepartment]=useState(item.proposedOwnerDepartmentId||'');const [group,setGroup]=useState(item.proposedOwnerGroupId||'');const [steward,setSteward]=useState(item.proposedStewardUserId||'');const [reason,setReason]=useState('');const [preview,setPreview]=useState<OrphanRepairImpactPreview|null>(null);const [confirm,setConfirm]=useState(false);
 const body:OrphanOwnerBody={resourceType:item.resourceType,resourceId:item.resourceId,ownerDepartmentId:department||undefined,ownerGroupId:group||undefined,stewardUserId:steward||undefined,expectedResourceVersion:item.resourceVersion};
 async function runPreview(){onBusy(true);onError('');try{setPreview(await previewOrphanRepair(item.repairId,body,reason))}catch(e){onError(text(e))}finally{onBusy(false)}}
 async function apply(auditReason:string){onBusy(true);onError('');try{await assignOrphanOwner(item.repairId,body,auditReason);setConfirm(false);await onApplied()}catch(e){onError(text(e))}finally{onBusy(false)}}
 function change(setter:(v:string)=>void,value:string){setter(value);setPreview(null)}
 return <><section className="sticky top-24 rounded-2xl border border-rose-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-2"><h2 className="font-black text-slate-950">Ownership Repair</h2><ResourceAccessBadge value="ORPHANED"/></div><p className="mt-2 break-all text-xs text-slate-500">{item.resourceType} / {item.resourceId}</p><div className="mt-4 space-y-3"><Field label="Owner department" value={department} onChange={v=>change(setDepartment,v)}/><Field label="Owner group" value={group} onChange={v=>change(setGroup,v)}/><Field label="Steward user" value={steward} onChange={v=>change(setSteward,v)}/><label className="block text-sm font-black text-slate-700">Preview reason<textarea value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 min-h-20 w-full rounded-xl border border-slate-300 px-3 py-2 font-normal"/></label><button type="button" disabled={busy||(!department&&!group&&!steward)||reason.trim().length<12} onClick={()=>void runPreview()} className="w-full rounded-xl border border-indigo-300 bg-indigo-50 px-4 py-3 font-black text-indigo-800 disabled:opacity-50">Impact Preview</button>{preview?<div className={`rounded-xl border p-4 text-sm ${preview.highRisk?'border-rose-300 bg-rose-50 text-rose-950':'border-emerald-200 bg-emerald-50 text-emerald-950'}`}><div className="font-black">{preview.highRisk?'High-risk repair':'Controlled repair'}</div><p className="mt-1 leading-5">{preview.warning}</p><dl className="mt-3 grid grid-cols-2 gap-2 text-xs"><Stat label="Participants" value={preview.participantCount}/><Stat label="Active grants" value={preview.activeGrantCount}/><Stat label="Active denies" value={preview.activeDenyCount}/><Stat label="Child resources" value={preview.childResourceCount}/></dl><OwnershipTransferImpactPanel participantCount={preview.participantCount} activeGrantCount={preview.activeGrantCount} activeDenyCount={preview.activeDenyCount} childResourceCount={preview.childResourceCount}/></div>:null}<button type="button" disabled={busy||!preview||!canRepair} onClick={()=>setConfirm(true)} className="w-full rounded-xl bg-rose-700 px-4 py-3 font-black text-white disabled:opacity-40">Assign canonical owner</button>{!canRepair?<p className="text-xs font-semibold text-slate-500">You have preview access but not <code>resource.orphan.repair</code>.</p>:null}</div></section><HighRiskActionDialog open={confirm} title="Assign canonical owner" description={`Apply the reviewed ownership change to ${item.resourceType}/${item.resourceId}. The backend re-runs impact preview, checks optimistic version ${item.resourceVersion}, updates the Domain authority, refreshes projection, and records immutable evidence.`} confirmation="ASSIGN_OWNER" running={busy} onCancel={()=>setConfirm(false)} onConfirm={reasonText=>void apply(reasonText)}/></>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-sm font-black text-slate-700">{label}<input value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5 font-normal"/></label>}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-lg bg-white/70 p-2"><dt className="font-semibold opacity-70">{label}</dt><dd className="mt-1 text-lg font-black">{value}</dd></div>}
function text(e:unknown){return e instanceof Error?e.message:'The operation failed.'}
