'use client';
import { useCallback,useEffect,useState } from 'react';
import { useAuth } from '@/components/auth/AuthProvider';
import { ErrorBox } from '@/components/common/ErrorBox';
import { HighRiskActionDialog } from '@/components/iam/HighRiskActionDialog';
import { ResourceAccessShell } from './ResourceAccessShell';
import { ResourceAccessBadge } from './ResourceAccessBadge';
import { ResourcePolicyCreateDialog } from './ResourcePolicyCreateDialog';
import { VirtualizedGovernanceList } from './VirtualizedGovernanceList';
import { listGovernanceDenies,listGovernanceGrants,transitionExplicitDeny,transitionScopeGrant,type ExplicitDenyView,type ScopeGrantView } from '@/lib/api/domains/resourceAccessApi';

type Mode='grants'|'denies';
type PolicyItem=ScopeGrantView|ExplicitDenyView;
type TransitionAction='submit'|'approve'|'suspend'|'revoke';
interface PendingAction{item:PolicyItem;action:TransitionAction}

export function ResourcePolicyList({mode}:Readonly<{mode:Mode}>){
 const {hasPermission,user}=useAuth();
 const [items,setItems]=useState<PolicyItem[]>([]);
 const [nextCursor,setNextCursor]=useState('');
 const [total,setTotal]=useState(0);
 const [state,setState]=useState('');
 const [search,setSearch]=useState('');
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');
 const [message,setMessage]=useState('');
 const [selected,setSelected]=useState<PolicyItem|null>(null);
 const [showCreate,setShowCreate]=useState(false);
 const [pending,setPending]=useState<PendingAction|null>(null);
 const load=useCallback(async(reset=true,cursor='')=>{setBusy(true);setError('');try{const options={state,search,cursor:reset?'':cursor,limit:100};const page=mode==='grants'?await listGovernanceGrants(options):await listGovernanceDenies(options);setItems(current=>reset?page.items:[...current,...page.items]);setNextCursor(page.nextCursor??'');setTotal(page.totalCount);if(reset)setSelected(current=>current? page.items.find(item=>policyId(mode,item)===policyId(mode,current))??null:null)}catch(e){setError(e instanceof Error?e.message:'Unable to load Resource Access policy records.')}finally{setBusy(false)}},[mode,search,state]);
 useEffect(()=>{void load(true)},[load,mode,state]);
 const title=mode==='grants'?'Scope Grants':'Explicit Denies';
 const canCreate=mode==='grants'?hasPermission('resource.scope.grant'):hasPermission('resource.deny.create');
 async function perform(reason:string){if(!pending)return;setBusy(true);setError('');setMessage('');try{const version=pending.item.version;const id=policyId(mode,pending.item);if(mode==='grants')await transitionScopeGrant(id,pending.action,version,reason);else await transitionExplicitDeny(id,pending.action as Exclude<TransitionAction,'suspend'>,version,reason);setMessage(`${pending.action} recorded. A fresh governance query has been loaded.`);setPending(null);await load(true)}catch(e){setError(e instanceof Error?e.message:'Policy transition failed.')}finally{setBusy(false)}}
 return <ResourceAccessShell title={title} description={mode==='grants'?'Create and review Tenant-bound grants, visibility caps, lifecycle state, approval evidence, and expiration. A grant is policy data, not an executable authorization token.':'Create and review explicit deny evidence. A matching active deny has precedence over every allow source.'}>
  {message?<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-900">{message}</div>:null}{error?<ErrorBox message={error}/>:null}
  <section className="rounded-2xl border border-slate-200 bg-white p-4"><form className="grid gap-3 md:grid-cols-[1fr_14rem_auto_auto]" onSubmit={e=>{e.preventDefault();void load(true)}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search principal, permission, resource, or scope" className="rounded-xl border border-slate-300 px-4 py-2.5"/><select value={state} onChange={e=>setState(e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5"><option value="">All lifecycle states</option>{(mode==='grants'?['DRAFT','PENDING_APPROVAL','ACTIVE','SUSPENDED','EXPIRED','REVOKED']:['DRAFT','PENDING_APPROVAL','ACTIVE','EXPIRED','REVOKED']).map(v=><option key={v}>{v}</option>)}</select><button disabled={busy} className="rounded-xl bg-indigo-700 px-5 py-2.5 font-black text-white disabled:opacity-50">{busy?'Loading…':'Search'}</button>{canCreate?<button type="button" onClick={()=>setShowCreate(true)} className="rounded-xl border border-indigo-300 bg-indigo-50 px-5 py-2.5 font-black text-indigo-800">New draft</button>:<span className="rounded-xl bg-slate-100 px-4 py-2.5 text-center text-sm font-bold text-slate-500">Read only</span>}</form><div className="mt-3 flex items-center justify-between text-xs font-semibold text-slate-500"><span>{items.length.toLocaleString()} loaded of {total.toLocaleString()}</span><span>Virtualized list · scope-aware cursor pagination</span></div></section>
  <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_24rem]"><div className="space-y-3"><VirtualizedGovernanceList items={items} getItemKey={item=>policyId(mode,item)} renderRow={item=><button type="button" onClick={()=>setSelected(item)} className={`h-full w-full rounded-xl text-left ${selected&&policyId(mode,selected)===policyId(mode,item)?'ring-2 ring-indigo-400':''}`}><PolicyRow mode={mode} item={item}/></button>}/>{nextCursor?<button type="button" disabled={busy} onClick={()=>void load(false,nextCursor)} className="w-full rounded-xl border border-indigo-300 bg-indigo-50 px-4 py-3 font-black text-indigo-800 disabled:opacity-50">Load next page</button>:null}</div><PolicyActionPanel mode={mode} item={selected} userId={user?.userId??''} authenticatedAt={user?.authenticatedAt} hasPermission={hasPermission} onAction={(action)=>selected&&setPending({item:selected,action})}/></div>
  <ResourcePolicyCreateDialog mode={mode} open={showCreate} onClose={()=>setShowCreate(false)} onCreated={()=>{setMessage('Policy draft created. Submit it for independent approval when ready.');void load(true)}}/>
  <HighRiskActionDialog open={!!pending} title={`${pending?.action??''} ${mode==='grants'?'Scope Grant':'Explicit Deny'}`} description={actionDescription(mode,pending)} confirmation={confirmation(mode,pending?.action)} running={busy} onCancel={()=>setPending(null)} onConfirm={reason=>void perform(reason)}/>
 </ResourceAccessShell>;
}

function PolicyActionPanel({mode,item,userId,authenticatedAt,hasPermission,onAction}:Readonly<{mode:Mode;item:PolicyItem|null;userId:string;authenticatedAt?:string;hasPermission:(...permissions:string[])=>boolean;onAction:(action:TransitionAction)=>void}>){if(!item)return <aside className="sticky top-24 h-fit rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6 text-sm text-slate-500">Select a policy record to inspect lifecycle evidence and available actions.</aside>;const state=item.state;const creator=item.createdBy===userId;const actions:TransitionAction[]=[];if(state==='DRAFT'&&hasPermission(mode==='grants'?'resource.scope.grant':'resource.deny.create'))actions.push('submit');if(state==='PENDING_APPROVAL'&&hasPermission(mode==='grants'?'resource.scope.approve':'resource.deny.approve'))actions.push('approve');if(mode==='grants'&&state==='ACTIVE'&&hasPermission('resource.scope.suspend'))actions.push('suspend');if(['DRAFT','PENDING_APPROVAL','ACTIVE','SUSPENDED'].includes(state)&&hasPermission(mode==='grants'?'resource.scope.revoke':'resource.deny.revoke'))actions.push('revoke');return <aside className="sticky top-24 h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-2"><h2 className="font-black text-slate-950">Lifecycle controls</h2><ResourceAccessBadge value={state}/></div><dl className="mt-4 space-y-3 text-sm"><Fact label="Record" value={policyId(mode,item)}/><Fact label="Created by" value={item.createdBy}/><Fact label="Approved by" value={item.approvedBy||'Not approved'}/><Fact label="Version" value={String(item.version)}/><Fact label="Authenticated at" value={authenticatedAt?new Date(authenticatedAt).toLocaleString():'Session evidence unavailable'}/></dl><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-950"><b>SoD and step-up:</b> the creator cannot approve the same record. Backend authorization and recent MFA policy remain authoritative; this UI never claims MFA completion.</div>{creator&&state==='PENDING_APPROVAL'?<p className="mt-3 rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-black text-rose-800">Independent approver required. You created this record.</p>:null}<div className="mt-4 grid gap-2">{actions.map(action=><button key={action} type="button" disabled={action==='approve'&&creator} onClick={()=>onAction(action)} className={`rounded-xl px-4 py-2.5 text-sm font-black disabled:cursor-not-allowed disabled:opacity-40 ${action==='approve'?'bg-emerald-700 text-white':action==='revoke'?'bg-rose-700 text-white':'border border-indigo-300 bg-indigo-50 text-indigo-800'}`}>{actionLabel(action)}</button>)}{!actions.length?<span className="rounded-xl bg-slate-100 p-3 text-center text-xs font-bold text-slate-500">No permitted lifecycle action.</span>:null}</div></aside>}
function PolicyRow({mode,item}:Readonly<{mode:Mode;item:PolicyItem}>){const grant=mode==='grants'?item as ScopeGrantView:null;const deny=mode==='denies'?item as ExplicitDenyView:null;return <article className="grid h-full grid-cols-[minmax(0,1fr)_auto] items-center gap-4 rounded-xl border border-slate-200 bg-white px-4 py-3 shadow-sm"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="truncate font-black text-slate-950">{grant?.grantId??deny?.denyId}</span><ResourceAccessBadge value={item.state}/>{deny?<ResourceAccessBadge value={deny.severity}/>:null}{grant?<ResourceAccessBadge value={grant.visibilityLevel}/>:null}</div><p className="mt-1 truncate text-sm font-semibold text-slate-700">{item.principalType} · {item.principalId} · {item.permissionCode||'All permissions'}</p><p className="mt-1 truncate text-xs text-slate-500">{item.resourceType} · {item.scopeType}{item.scopeRefId?` · ${item.scopeRefId}`:''}{deny?` · ${deny.denyReason}`:''}</p></div><div className="text-right text-xs text-slate-500"><div>v{item.version}</div><div className="mt-1">{item.validTo?`Ends ${new Date(item.validTo).toLocaleDateString()}`:'No expiry'}</div></div></article>}
function Fact({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-black uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 break-all font-semibold text-slate-800">{value}</dd></div>}
function policyId(mode:Mode,item:PolicyItem){return mode==='grants'?(item as ScopeGrantView).grantId:(item as ExplicitDenyView).denyId}
function actionLabel(action:TransitionAction){return ({submit:'Submit for approval',approve:'Approve independently',suspend:'Suspend grant',revoke:'Revoke permanently'})[action]}
function confirmation(mode:Mode,action?:TransitionAction){return `${(action??'CONFIRM').toUpperCase()}_${mode==='grants'?'GRANT':'DENY'}`}
function actionDescription(mode:Mode,pending:PendingAction|null){if(!pending)return '';const noun=mode==='grants'?'grant':'deny';if(pending.action==='approve')return `Activate this ${noun} after independent review. The backend verifies actor identity, permission, optimistic version, SoD, and applicable recent-authentication policy.`;if(pending.action==='revoke')return `Permanently revoke this ${noun}. Existing authorization cache namespaces will be invalidated by policy epoch changes.`;return `${actionLabel(pending.action)}. An immutable lifecycle audit reason is required.`}
