package com.opensocket.aievent.core.issuetracking.recovery;
import java.time.OffsetDateTime; import java.util.*;
public interface ProjectionRecoveryRepository {
 OrderedProjectionLane saveLane(OrderedProjectionLane value); boolean saveLaneExpectedVersion(OrderedProjectionLane value,long expectedVersion); Optional<OrderedProjectionLane> findLane(String tenantId,String laneId); Optional<OrderedProjectionLane> findLaneByAggregate(String tenantId,String aggregateKey,ProjectionLaneType laneType); List<OrderedProjectionLane> listLanes(String tenantId,ProjectionLaneStatus status,int limit);
 OrderedProjectionWork saveWork(OrderedProjectionWork value); boolean saveWorkExpectedVersion(OrderedProjectionWork value,long expectedVersion); Optional<OrderedProjectionWork> findWork(String tenantId,String workId); List<OrderedProjectionWork> listWork(String tenantId,String laneId,ProjectionWorkStatus status,int limit); List<OrderedProjectionWork> claimDueWork(String tenantId,OffsetDateTime dueAt,int limit); List<OrderedProjectionWork> listExpiredClaims(String tenantId,OffsetDateTime dueAt,int limit); List<OrderedProjectionWork> findCoalescible(String tenantId,String laneId,String coalesceKey,long generation,int limit);
 ProjectionRecoveryCase saveCase(ProjectionRecoveryCase value); boolean saveCaseExpectedVersion(ProjectionRecoveryCase value,long expectedVersion); Optional<ProjectionRecoveryCase> findCase(String tenantId,String caseId); Optional<ProjectionRecoveryCase> findOpenCase(String tenantId,String workId,ProjectionRecoveryCaseType type); List<ProjectionRecoveryCase> listCases(String tenantId,ProjectionRecoveryCaseStatus status,int limit);
 ProjectionReconciliationRun saveRun(ProjectionReconciliationRun value); boolean saveRunExpectedVersion(ProjectionReconciliationRun value,long expectedVersion); Optional<ProjectionReconciliationRun> findRun(String tenantId,String runId); List<ProjectionReconciliationRun> listRuns(String tenantId,ReconciliationRunStatus status,int limit);
 ProviderHealthState saveHealth(ProviderHealthState value); boolean saveHealthExpectedVersion(ProviderHealthState value,long expectedVersion); Optional<ProviderHealthState> findHealth(String tenantId,String connectionId,String projectMappingId); List<ProviderHealthState> listHealth(String tenantId,ProviderHealthStatus status,int limit);
 ProjectionRecoveryEvent appendEvent(ProjectionRecoveryEvent value); Optional<ProjectionRecoveryEvent> latestEvent(String tenantId,String aggregateType,String aggregateId); List<ProjectionRecoveryEvent> listEvents(String tenantId,String aggregateType,String aggregateId,int limit);
 default String mode(){return "CUSTOM";}
}
