package com.opensocket.aievent.core.a2a.core;

import java.util.List;
import java.util.Optional;
import com.opensocket.aievent.core.a2a.*;

/** Generated by scripts/phase2c/generate_phase2c_contracts.py. */
public final class A2ATransitionCatalog {
    private static final List<A2ATransitionRule> RULES = List.of(
        new A2ATransitionRule(
                "REQUEST_START_VALIDATION", A2ARequestStatus.REQUESTED, A2AOperationalStage.REQUESTED,
                A2ATransitionCommand.START_VALIDATION, A2ARequestStatus.VALIDATING, A2AOperationalStage.VALIDATING,
                A2ATransitionPermission.A2A_REQUEST_CREATE, "A2A_REQUEST", A2ATransitionEvidenceType.REQUEST_COMMAND,
                "Start directional A2A validation.", "A2A_VALIDATION_STARTED", A2ATransitionFailureHandling.REJECT_COMMAND,
                A2ATransitionTimeoutPolicy.REQUEST_EXPIRY, false),
        new A2ATransitionRule(
                "VALIDATION_REQUIRE_APPROVAL", A2ARequestStatus.VALIDATING, A2AOperationalStage.VALIDATING,
                A2ATransitionCommand.REQUIRE_APPROVAL, A2ARequestStatus.WAITING_APPROVAL, A2AOperationalStage.WAITING_APPROVAL,
                A2ATransitionPermission.A2A_REQUEST_CREATE, "A2A_REQUEST", A2ATransitionEvidenceType.POLICY_DECISION,
                "Directional policy requires approval.", "A2A_APPROVAL_REQUIRED", A2ATransitionFailureHandling.REJECT_COMMAND,
                A2ATransitionTimeoutPolicy.APPROVAL_EXPIRY, false),
        new A2ATransitionRule(
                "VALIDATION_AUTO_APPROVE", A2ARequestStatus.VALIDATING, A2AOperationalStage.VALIDATING,
                A2ATransitionCommand.APPROVE, A2ARequestStatus.APPROVED, A2AOperationalStage.APPROVED,
                A2ATransitionPermission.A2A_REQUEST_CREATE, "A2A_REQUEST", A2ATransitionEvidenceType.POLICY_DECISION,
                "Directional policy approved the request.", "A2A_VALIDATED", A2ATransitionFailureHandling.REJECT_COMMAND,
                A2ATransitionTimeoutPolicy.REQUEST_EXPIRY, false),
        new A2ATransitionRule(
                "APPROVAL_APPROVE", A2ARequestStatus.WAITING_APPROVAL, A2AOperationalStage.WAITING_APPROVAL,
                A2ATransitionCommand.APPROVE, A2ARequestStatus.APPROVED, A2AOperationalStage.APPROVED,
                A2ATransitionPermission.A2A_APPROVE, "A2A_APPROVE", A2ATransitionEvidenceType.APPROVAL_EVIDENCE,
                "Required distinct approvals were recorded.", "A2A_APPROVED", A2ATransitionFailureHandling.REJECT_COMMAND,
                A2ATransitionTimeoutPolicy.APPROVAL_EXPIRY, false),
        new A2ATransitionRule(
                "REQUEST_REJECT", A2ARequestStatus.REQUESTED, null,
                A2ATransitionCommand.REJECT, A2ARequestStatus.REJECTED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_REJECT, "A2A_REJECT", A2ATransitionEvidenceType.REQUEST_COMMAND,
                "A2A request was rejected.", "A2A_REJECTED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "VALIDATION_REJECT", A2ARequestStatus.VALIDATING, null,
                A2ATransitionCommand.REJECT, A2ARequestStatus.REJECTED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_REJECT, "A2A_REJECT", A2ATransitionEvidenceType.POLICY_DECISION,
                "A2A validation rejected the request.", "A2A_REJECTED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "APPROVAL_REJECT", A2ARequestStatus.WAITING_APPROVAL, null,
                A2ATransitionCommand.REJECT, A2ARequestStatus.REJECTED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_REJECT, "A2A_REJECT", A2ATransitionEvidenceType.APPROVAL_EVIDENCE,
                "A2A approval rejected the request.", "A2A_REJECTED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "APPROVED_BEGIN_CHILD_CREATION", A2ARequestStatus.APPROVED, A2AOperationalStage.APPROVED,
                A2ATransitionCommand.BEGIN_CHILD_CREATION, A2ARequestStatus.APPROVED, A2AOperationalStage.CHILD_TASK_CREATING,
                A2ATransitionPermission.A2A_CHILD_CREATE, "A2A_CHILD_CREATE", A2ATransitionEvidenceType.POLICY_DECISION,
                "Begin authoritative Child Task creation.", "A2A_CHILD_TASK_CREATION_STARTED", A2ATransitionFailureHandling.RECONCILE,
                A2ATransitionTimeoutPolicy.CHILD_TASK_CREATION_TIMEOUT, false),
        new A2ATransitionRule(
                "APPROVED_CHILD_CREATED", A2ARequestStatus.APPROVED, A2AOperationalStage.CHILD_TASK_CREATING,
                A2ATransitionCommand.CREATE_CHILD, A2ARequestStatus.CHILD_TASK_CREATED, A2AOperationalStage.CHILD_TASK_CREATED,
                A2ATransitionPermission.A2A_CHILD_CREATE, "A2A_CHILD_CREATE", A2ATransitionEvidenceType.TASK_AUTHORITY_RECEIPT,
                "Task Authority created the Child Task.", "A2A_CHILD_TASK_CREATED", A2ATransitionFailureHandling.RECONCILE,
                A2ATransitionTimeoutPolicy.CHILD_TASK_CREATION_TIMEOUT, false),
        new A2ATransitionRule(
                "CHILD_REQUEST_DISPATCH", A2ARequestStatus.CHILD_TASK_CREATED, A2AOperationalStage.CHILD_TASK_CREATED,
                A2ATransitionCommand.REQUEST_DISPATCH, A2ARequestStatus.CHILD_TASK_CREATED, A2AOperationalStage.DISPATCH_REQUESTED,
                A2ATransitionPermission.A2A_DISPATCH_REQUEST, "A2A_DISPATCH", A2ATransitionEvidenceType.DISPATCH_AUTHORITY_RECEIPT,
                "Dispatch Authority accepted the dispatch intent.", "A2A_DISPATCH_REQUESTED", A2ATransitionFailureHandling.RETRY_SAFE,
                A2ATransitionTimeoutPolicy.DISPATCH_TIMEOUT, false),
        new A2ATransitionRule(
                "CHILD_BLOCKED", A2ARequestStatus.CHILD_TASK_CREATED, null,
                A2ATransitionCommand.MARK_BLOCKED, A2ARequestStatus.CHILD_TASK_CREATED, A2AOperationalStage.BLOCKED,
                A2ATransitionPermission.A2A_DISPATCH_UPDATE, "A2A_BLOCK", A2ATransitionEvidenceType.DISPATCH_AUTHORITY_RECEIPT,
                "A2A dispatch is blocked.", "A2A_BLOCKED", A2ATransitionFailureHandling.RECONCILE,
                A2ATransitionTimeoutPolicy.RECONCILIATION_BACKOFF, false),
        new A2ATransitionRule(
                "CHILD_RECOVER_DISPATCH", A2ARequestStatus.CHILD_TASK_CREATED, A2AOperationalStage.BLOCKED,
                A2ATransitionCommand.RECOVER, A2ARequestStatus.CHILD_TASK_CREATED, A2AOperationalStage.DISPATCH_REQUESTED,
                A2ATransitionPermission.A2A_RECONCILE, "A2A_RECOVER", A2ATransitionEvidenceType.RECONCILIATION_EVIDENCE,
                "Reconciliation proved dispatch can resume.", "A2A_RECOVERED", A2ATransitionFailureHandling.RETRY_SAFE,
                A2ATransitionTimeoutPolicy.DISPATCH_TIMEOUT, true),
        new A2ATransitionRule(
                "CHILD_START_DISPATCH", A2ARequestStatus.CHILD_TASK_CREATED, A2AOperationalStage.DISPATCH_REQUESTED,
                A2ATransitionCommand.START_DISPATCH, A2ARequestStatus.DISPATCHING, A2AOperationalStage.DISPATCHING,
                A2ATransitionPermission.A2A_DISPATCH_UPDATE, "A2A_DISPATCH", A2ATransitionEvidenceType.DISPATCH_AUTHORITY_RECEIPT,
                "Dispatch worker claimed the intent.", "A2A_DISPATCHING", A2ATransitionFailureHandling.RECONCILE,
                A2ATransitionTimeoutPolicy.DISPATCH_TIMEOUT, false),
        new A2ATransitionRule(
                "CHILD_DIRECT_RUNNING", A2ARequestStatus.CHILD_TASK_CREATED, A2AOperationalStage.DISPATCH_REQUESTED,
                A2ATransitionCommand.MARK_RUNNING, A2ARequestStatus.RUNNING, A2AOperationalStage.RUNNING,
                A2ATransitionPermission.A2A_DISPATCH_UPDATE, "A2A_RUNTIME", A2ATransitionEvidenceType.RUNTIME_EVIDENCE,
                "Runtime evidence proves the Child Task is running.", "A2A_RUNNING", A2ATransitionFailureHandling.RECONCILE,
                A2ATransitionTimeoutPolicy.RESULT_TIMEOUT, false),
        new A2ATransitionRule(
                "DISPATCH_BLOCKED", A2ARequestStatus.DISPATCHING, null,
                A2ATransitionCommand.MARK_BLOCKED, A2ARequestStatus.DISPATCHING, A2AOperationalStage.BLOCKED,
                A2ATransitionPermission.A2A_DISPATCH_UPDATE, "A2A_BLOCK", A2ATransitionEvidenceType.DISPATCH_AUTHORITY_RECEIPT,
                "Dispatch execution is blocked.", "A2A_BLOCKED", A2ATransitionFailureHandling.RECONCILE,
                A2ATransitionTimeoutPolicy.RECONCILIATION_BACKOFF, false),
        new A2ATransitionRule(
                "DISPATCH_RECOVER", A2ARequestStatus.DISPATCHING, A2AOperationalStage.BLOCKED,
                A2ATransitionCommand.RECOVER, A2ARequestStatus.DISPATCHING, A2AOperationalStage.DISPATCHING,
                A2ATransitionPermission.A2A_RECONCILE, "A2A_RECOVER", A2ATransitionEvidenceType.RECONCILIATION_EVIDENCE,
                "Reconciliation proved dispatch can continue.", "A2A_RECOVERED", A2ATransitionFailureHandling.RETRY_SAFE,
                A2ATransitionTimeoutPolicy.DISPATCH_TIMEOUT, true),
        new A2ATransitionRule(
                "DISPATCH_RUNNING", A2ARequestStatus.DISPATCHING, null,
                A2ATransitionCommand.MARK_RUNNING, A2ARequestStatus.RUNNING, A2AOperationalStage.RUNNING,
                A2ATransitionPermission.A2A_DISPATCH_UPDATE, "A2A_RUNTIME", A2ATransitionEvidenceType.RUNTIME_EVIDENCE,
                "Runtime evidence proves the Child Task is running.", "A2A_RUNNING", A2ATransitionFailureHandling.RECONCILE,
                A2ATransitionTimeoutPolicy.RESULT_TIMEOUT, false),
        new A2ATransitionRule(
                "RUNNING_WAIT_RESULT", A2ARequestStatus.RUNNING, null,
                A2ATransitionCommand.WAIT_FOR_RESULT, A2ARequestStatus.RUNNING, A2AOperationalStage.WAITING_RESULT,
                A2ATransitionPermission.A2A_DISPATCH_UPDATE, "A2A_RESULT_WAIT", A2ATransitionEvidenceType.RUNTIME_EVIDENCE,
                "Execution completed its active work and is awaiting canonical Result evidence.", "A2A_WAITING_RESULT", A2ATransitionFailureHandling.RECONCILE,
                A2ATransitionTimeoutPolicy.RESULT_TIMEOUT, false),
        new A2ATransitionRule(
                "CHILD_COMPLETE", A2ARequestStatus.CHILD_TASK_CREATED, null,
                A2ATransitionCommand.COMPLETE, A2ARequestStatus.COMPLETED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_RESULT_ACCEPT, "A2A_RESULT", A2ATransitionEvidenceType.RESULT_EVIDENCE,
                "Canonical Result completed the A2A request.", "A2A_COMPLETED", A2ATransitionFailureHandling.QUARANTINE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "DISPATCH_COMPLETE", A2ARequestStatus.DISPATCHING, null,
                A2ATransitionCommand.COMPLETE, A2ARequestStatus.COMPLETED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_RESULT_ACCEPT, "A2A_RESULT", A2ATransitionEvidenceType.RESULT_EVIDENCE,
                "Canonical Result completed the A2A request.", "A2A_COMPLETED", A2ATransitionFailureHandling.QUARANTINE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "RUNNING_COMPLETE", A2ARequestStatus.RUNNING, null,
                A2ATransitionCommand.COMPLETE, A2ARequestStatus.COMPLETED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_RESULT_ACCEPT, "A2A_RESULT", A2ATransitionEvidenceType.RESULT_EVIDENCE,
                "Canonical Result completed the A2A request.", "A2A_COMPLETED", A2ATransitionFailureHandling.QUARANTINE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "CANCEL_REQUEST_COMPLETE_RACE", A2ARequestStatus.CANCEL_REQUESTED, null,
                A2ATransitionCommand.COMPLETE, A2ARequestStatus.COMPLETED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_RESULT_ACCEPT, "A2A_CANCEL_COMPLETE_RACE", A2ATransitionEvidenceType.RESULT_EVIDENCE,
                "Canonical Result occurred before the cancellation fencing cutoff and won the Cancel/Complete race.", "A2A_COMPLETED", A2ATransitionFailureHandling.QUARANTINE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "CANCEL_REQUEST_FAIL_RACE", A2ARequestStatus.CANCEL_REQUESTED, null,
                A2ATransitionCommand.FAIL, A2ARequestStatus.FAILED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_RESULT_ACCEPT, "A2A_CANCEL_COMPLETE_RACE", A2ATransitionEvidenceType.RESULT_EVIDENCE,
                "Canonical failure Result occurred before the cancellation fencing cutoff.", "A2A_FAILED", A2ATransitionFailureHandling.QUARANTINE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "APPROVED_FAIL", A2ARequestStatus.APPROVED, null,
                A2ATransitionCommand.FAIL, A2ARequestStatus.FAILED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_RECONCILE, "A2A_FAILURE", A2ATransitionEvidenceType.RECONCILIATION_EVIDENCE,
                "A2A coordination failed before Child Task creation completed.", "A2A_FAILED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "CHILD_FAIL", A2ARequestStatus.CHILD_TASK_CREATED, null,
                A2ATransitionCommand.FAIL, A2ARequestStatus.FAILED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_RESULT_ACCEPT, "A2A_FAILURE", A2ATransitionEvidenceType.RESULT_EVIDENCE,
                "A2A Child Task failed.", "A2A_FAILED", A2ATransitionFailureHandling.QUARANTINE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "DISPATCH_FAIL", A2ARequestStatus.DISPATCHING, null,
                A2ATransitionCommand.FAIL, A2ARequestStatus.FAILED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_RECONCILE, "A2A_FAILURE", A2ATransitionEvidenceType.DISPATCH_AUTHORITY_RECEIPT,
                "A2A dispatch failed permanently.", "A2A_FAILED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "RUNNING_FAIL", A2ARequestStatus.RUNNING, null,
                A2ATransitionCommand.FAIL, A2ARequestStatus.FAILED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_RESULT_ACCEPT, "A2A_FAILURE", A2ATransitionEvidenceType.RESULT_EVIDENCE,
                "Canonical Result failed the A2A request.", "A2A_FAILED", A2ATransitionFailureHandling.QUARANTINE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "REQUEST_CANCEL_EARLY", A2ARequestStatus.REQUESTED, null,
                A2ATransitionCommand.CANCEL, A2ARequestStatus.CANCELLED_CONFIRMED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_CANCEL, "A2A_CANCEL", A2ATransitionEvidenceType.REQUEST_COMMAND,
                "A2A request was cancelled before Child Task creation.", "A2A_CANCELLED_CONFIRMED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "VALIDATION_CANCEL_EARLY", A2ARequestStatus.VALIDATING, null,
                A2ATransitionCommand.CANCEL, A2ARequestStatus.CANCELLED_CONFIRMED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_CANCEL, "A2A_CANCEL", A2ATransitionEvidenceType.REQUEST_COMMAND,
                "A2A request was cancelled during validation.", "A2A_CANCELLED_CONFIRMED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "APPROVAL_CANCEL_EARLY", A2ARequestStatus.WAITING_APPROVAL, null,
                A2ATransitionCommand.CANCEL, A2ARequestStatus.CANCELLED_CONFIRMED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_CANCEL, "A2A_CANCEL", A2ATransitionEvidenceType.REQUEST_COMMAND,
                "A2A request was cancelled before approval.", "A2A_CANCELLED_CONFIRMED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "APPROVED_CANCEL_EARLY", A2ARequestStatus.APPROVED, null,
                A2ATransitionCommand.CANCEL, A2ARequestStatus.CANCELLED_CONFIRMED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_CANCEL, "A2A_CANCEL", A2ATransitionEvidenceType.REQUEST_COMMAND,
                "A2A request was cancelled before a runnable Child Task existed.", "A2A_CANCELLED_CONFIRMED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "CHILD_CANCEL_REQUEST", A2ARequestStatus.CHILD_TASK_CREATED, null,
                A2ATransitionCommand.CANCEL, A2ARequestStatus.CANCEL_REQUESTED, A2AOperationalStage.CANCEL_REQUESTED,
                A2ATransitionPermission.A2A_CANCEL, "A2A_CANCEL", A2ATransitionEvidenceType.CANCELLATION_EVIDENCE,
                "Cancellation intent was accepted and runtime acknowledgement is pending.", "A2A_CANCEL_REQUESTED", A2ATransitionFailureHandling.RECONCILE,
                A2ATransitionTimeoutPolicy.CANCELLATION_ACK_TIMEOUT, false),
        new A2ATransitionRule(
                "DISPATCH_CANCEL_REQUEST", A2ARequestStatus.DISPATCHING, null,
                A2ATransitionCommand.CANCEL, A2ARequestStatus.CANCEL_REQUESTED, A2AOperationalStage.CANCEL_REQUESTED,
                A2ATransitionPermission.A2A_CANCEL, "A2A_CANCEL", A2ATransitionEvidenceType.CANCELLATION_EVIDENCE,
                "Cancellation intent was accepted during dispatch.", "A2A_CANCEL_REQUESTED", A2ATransitionFailureHandling.RECONCILE,
                A2ATransitionTimeoutPolicy.CANCELLATION_ACK_TIMEOUT, false),
        new A2ATransitionRule(
                "RUNNING_CANCEL_REQUEST", A2ARequestStatus.RUNNING, null,
                A2ATransitionCommand.CANCEL, A2ARequestStatus.CANCEL_REQUESTED, A2AOperationalStage.CANCEL_REQUESTED,
                A2ATransitionPermission.A2A_CANCEL, "A2A_CANCEL", A2ATransitionEvidenceType.CANCELLATION_EVIDENCE,
                "Cancellation intent was accepted for a running Child Task.", "A2A_CANCEL_REQUESTED", A2ATransitionFailureHandling.RECONCILE,
                A2ATransitionTimeoutPolicy.CANCELLATION_ACK_TIMEOUT, false),
        new A2ATransitionRule(
                "CHILD_CANCEL_CONFIRMED_BY_RESULT", A2ARequestStatus.CHILD_TASK_CREATED, null,
                A2ATransitionCommand.CONFIRM_CANCEL, A2ARequestStatus.CANCELLED_CONFIRMED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_RESULT_ACCEPT, "A2A_RESULT", A2ATransitionEvidenceType.RESULT_EVIDENCE,
                "Canonical Result proved the Child Task was cancelled.", "A2A_CANCELLED_CONFIRMED", A2ATransitionFailureHandling.QUARANTINE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "DISPATCH_CANCEL_CONFIRMED_BY_RESULT", A2ARequestStatus.DISPATCHING, null,
                A2ATransitionCommand.CONFIRM_CANCEL, A2ARequestStatus.CANCELLED_CONFIRMED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_RESULT_ACCEPT, "A2A_RESULT", A2ATransitionEvidenceType.RESULT_EVIDENCE,
                "Canonical Result proved the dispatched Child Task was cancelled.", "A2A_CANCELLED_CONFIRMED", A2ATransitionFailureHandling.QUARANTINE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "RUNNING_CANCEL_CONFIRMED_BY_RESULT", A2ARequestStatus.RUNNING, null,
                A2ATransitionCommand.CONFIRM_CANCEL, A2ARequestStatus.CANCELLED_CONFIRMED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_RESULT_ACCEPT, "A2A_RESULT", A2ATransitionEvidenceType.RESULT_EVIDENCE,
                "Canonical Result proved the running Child Task was cancelled.", "A2A_CANCELLED_CONFIRMED", A2ATransitionFailureHandling.QUARANTINE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "CANCEL_CONFIRM", A2ARequestStatus.CANCEL_REQUESTED, null,
                A2ATransitionCommand.CONFIRM_CANCEL, A2ARequestStatus.CANCELLED_CONFIRMED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_CANCEL, "A2A_CANCEL_CONFIRM", A2ATransitionEvidenceType.CANCELLATION_EVIDENCE,
                "Runtime or local authority confirmed cancellation.", "A2A_CANCELLED_CONFIRMED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "CANCEL_UNCONFIRMED", A2ARequestStatus.CANCEL_REQUESTED, null,
                A2ATransitionCommand.MARK_BLOCKED, A2ARequestStatus.CANCELLED_UNCONFIRMED, A2AOperationalStage.BLOCKED,
                A2ATransitionPermission.A2A_RECONCILE, "A2A_CANCEL_CONFIRM", A2ATransitionEvidenceType.CANCELLATION_EVIDENCE,
                "Cancellation acknowledgement could not be proven.", "A2A_CANCELLED_UNCONFIRMED", A2ATransitionFailureHandling.WAIT_HUMAN,
                A2ATransitionTimeoutPolicy.RECONCILIATION_BACKOFF, false),
        new A2ATransitionRule(
                "CANCEL_ESCALATE_HUMAN", A2ARequestStatus.CANCELLED_UNCONFIRMED, null,
                A2ATransitionCommand.MARK_BLOCKED, A2ARequestStatus.WAIT_HUMAN, A2AOperationalStage.WAIT_HUMAN,
                A2ATransitionPermission.A2A_RECONCILE, "A2A_RECONCILE", A2ATransitionEvidenceType.RECONCILIATION_EVIDENCE,
                "Ambiguous cancellation requires governed human review.", "A2A_WAIT_HUMAN", A2ATransitionFailureHandling.WAIT_HUMAN,
                A2ATransitionTimeoutPolicy.RECONCILIATION_BACKOFF, false),
        new A2ATransitionRule(
                "HUMAN_CONFIRM_CANCEL", A2ARequestStatus.WAIT_HUMAN, null,
                A2ATransitionCommand.CONFIRM_CANCEL, A2ARequestStatus.CANCELLED_CONFIRMED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_RECONCILE, "A2A_HUMAN_RESOLUTION", A2ATransitionEvidenceType.RECONCILIATION_EVIDENCE,
                "Governed review confirmed cancellation.", "A2A_CANCELLED_CONFIRMED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, true),
        new A2ATransitionRule(
                "HUMAN_FAIL", A2ARequestStatus.WAIT_HUMAN, null,
                A2ATransitionCommand.FAIL, A2ARequestStatus.FAILED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_RECONCILE, "A2A_HUMAN_RESOLUTION", A2ATransitionEvidenceType.RECONCILIATION_EVIDENCE,
                "Governed review resolved the request as failed.", "A2A_FAILED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, true),
        new A2ATransitionRule(
                "REQUEST_EXPIRE", A2ARequestStatus.REQUESTED, null,
                A2ATransitionCommand.EXPIRE, A2ARequestStatus.EXPIRED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_EXPIRE, "A2A_EXPIRE", A2ATransitionEvidenceType.TIME_EVIDENCE,
                "A2A request expired.", "A2A_EXPIRED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "VALIDATION_EXPIRE", A2ARequestStatus.VALIDATING, null,
                A2ATransitionCommand.EXPIRE, A2ARequestStatus.EXPIRED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_EXPIRE, "A2A_EXPIRE", A2ATransitionEvidenceType.TIME_EVIDENCE,
                "A2A validation expired.", "A2A_EXPIRED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "APPROVAL_EXPIRE", A2ARequestStatus.WAITING_APPROVAL, null,
                A2ATransitionCommand.EXPIRE, A2ARequestStatus.EXPIRED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_EXPIRE, "A2A_EXPIRE", A2ATransitionEvidenceType.TIME_EVIDENCE,
                "A2A approval window expired.", "A2A_EXPIRED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, false),
        new A2ATransitionRule(
                "APPROVED_EXPIRE", A2ARequestStatus.APPROVED, null,
                A2ATransitionCommand.EXPIRE, A2ARequestStatus.EXPIRED, A2AOperationalStage.TERMINAL,
                A2ATransitionPermission.A2A_EXPIRE, "A2A_EXPIRE", A2ATransitionEvidenceType.TIME_EVIDENCE,
                "Approved A2A request expired before Child Task creation.", "A2A_EXPIRED", A2ATransitionFailureHandling.TERMINAL_FAILURE,
                A2ATransitionTimeoutPolicy.NONE, false)
    );

    private A2ATransitionCatalog() {}

    public static List<A2ATransitionRule> rules() {
        return RULES;
    }

    public static Optional<A2ATransitionRule> find(A2ARequestStatus status, A2AOperationalStage stage,
            A2ATransitionCommand command, A2ARequestStatus targetStatus) {
        Optional<A2ATransitionRule> exact = RULES.stream()
                .filter(rule -> rule.sourceStatus() == status)
                .filter(rule -> rule.sourceStage() == stage)
                .filter(rule -> rule.command() == command)
                .filter(rule -> rule.targetStatus() == targetStatus)
                .findFirst();
        if (exact.isPresent()) {
            return exact;
        }
        return RULES.stream()
                .filter(rule -> rule.sourceStatus() == status)
                .filter(rule -> rule.sourceStage() == null)
                .filter(rule -> rule.command() == command)
                .filter(rule -> rule.targetStatus() == targetStatus)
                .findFirst();
    }
}
