'use client';

import { useEffect, useMemo, useState } from 'react';
import { actionAllowed } from '@/lib/navigation/uiEntitlements';
import { useUiEntitlements } from '@/lib/navigation/useUiEntitlements';
import { configurationMigrationGovernanceApi, type ConfigurationInventoryDetail, type ConfigurationInventorySummary } from '@/lib/api/runtimeConfigurationApi';
import { CutoverWaveOperationsConsole } from '@/components/runtime-configuration/CutoverWaveOperationsConsole';
import { Button } from '@/components/ui/Button';

const STATUSES = ['', 'DISCOVERED','CLASSIFIED','OWNER_REVIEWED','ARCHITECTURE_APPROVED','MIGRATION_READY','MIGRATED','LEGACY_RETIRED'];
const AUTHORITIES = ['RUNTIME_TUNABLE','BOOTSTRAP_INFRA','SECURITY_INVARIANT','DOMAIN_CONFIG','SECRET_MATERIAL','TEST_RELEASE_CONFIG'];
const SCOPES = ['SYSTEM','COMPONENT','NODE_ROLE','TENANT','DEPARTMENT','SOURCE_SYSTEM','PROVIDER','FLOW','AGENT','USER'];
const RISKS = ['LOW','MEDIUM','HIGH','CRITICAL'];
const MUTABILITIES = ['HOT_IMMEDIATE','HOT_NEXT_CYCLE','RESTART_REQUIRED','IMMUTABLE'];
const CONSUMERS = ['RUNTIME_SNAPSHOT','DYNAMIC_SCHEDULER','STARTUP_BINDING','SPRING_CONDITION','DEPLOYMENT_ONLY'];

function Pill({ children }: Readonly<{children: React.ReactNode}>) { return <span className="rounded-full border border-slate-200 bg-slate-50 px-2 py-1 text-[11px] font-bold text-slate-700">{children}</span>; }
function Select({ value, onChange, values }: {value:string;onChange:(v:string)=>void;values:string[]}) { return <select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm">{values.map(v=><option key={v} value={v}>{v||'All'}</option>)}</select>; }

export function ConfigurationMigrationGovernanceConsole() {
  const entitlements = useUiEntitlements();
  const canEdit = actionAllowed(entitlements.value, 'runtime-configuration.edit');
  const canApprove = actionAllowed(entitlements.value, 'runtime-configuration.approve');
  const canPublish = actionAllowed(entitlements.value, 'runtime-configuration.publish');
  const [items,setItems]=useState<ConfigurationInventorySummary[]>([]); const [detail,setDetail]=useState<ConfigurationInventoryDetail|null>(null);
  const [status,setStatus]=useState(''); const [namespace,setNamespace]=useState(''); const [query,setQuery]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const [owner,setOwner]=useState(''); const [authority,setAuthority]=useState('RUNTIME_TUNABLE'); const [scope,setScope]=useState('COMPONENT'); const [risk,setRisk]=useState('MEDIUM'); const [mutability,setMutability]=useState('RESTART_REQUIRED'); const [consumer,setConsumer]=useState('STARTUP_BINDING'); const [adminEditable,setAdminEditable]=useState(false); const [requiresApproval,setRequiresApproval]=useState(true); const [reason,setReason]=useState('');

  const namespaces=useMemo(()=>Array.from(new Set(items.map(x=>x.namespace))).sort(),[items]);
  async function load(){setBusy(true);try{const data=await configurationMigrationGovernanceApi.list(status,namespace,query);setItems(data);setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function open(key:string){setBusy(true);try{const d=await configurationMigrationGovernanceApi.detail(key);setDetail(d);setOwner(d.governance.domainOwner??'');setAuthority(d.governance.authorityClass??'RUNTIME_TUNABLE');setScope(d.governance.scope??'COMPONENT');setRisk(d.governance.risk??'MEDIUM');setMutability(d.governance.mutability??'RESTART_REQUIRED');setConsumer(d.governance.consumerContract??'STARTUP_BINDING');setAdminEditable(d.governance.adminEditable??false);setRequiresApproval(d.governance.requiresApproval??true);setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  useEffect(()=>{void load();},[status,namespace]);
  async function act(fn:()=>Promise<ConfigurationInventoryDetail>,success:string){if(!reason.trim()){setError('Audit reason is required.');return;}setBusy(true);try{const d=await fn();setDetail(d);setMessage(success);setError('');setReason('');await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  const g=detail?.governance; const hash=detail?.observation.sourceObservationHash??''; const version=g?.version??0;

  return <div className="space-y-5">
    <div className="rounded-3xl border border-blue-200 bg-blue-50 p-5"><div className="text-xs font-black uppercase tracking-wide text-blue-700">Migration governance authority</div><h2 className="mt-1 text-xl font-black text-slate-950">Executable source first. Human review grants migration authority.</h2><p className="mt-2 text-sm leading-6 text-slate-700">Automated classification is advisory only. This console cannot create arbitrary configuration definitions, cannot bulk-approve observations, and cannot mark a key MIGRATED or LEGACY_RETIRED. Source drift invalidates prior review evidence.</p></div>
    <CutoverWaveOperationsConsole onGovernanceReload={load} />
    {error&&<div className="rounded-xl border border-rose-300 bg-rose-50 p-3 text-sm font-bold text-rose-800">{error}</div>}{message&&<div className="rounded-xl border border-emerald-300 bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{message}</div>}
    <div className="grid gap-3 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-4"><Select value={status} onChange={setStatus} values={STATUSES}/><select value={namespace} onChange={e=>setNamespace(e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All namespaces</option>{namespaces.map(n=><option key={n}>{n}</option>)}</select><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load();}} placeholder="Search configuration key" className="rounded-xl border border-slate-300 px-3 py-2 text-sm"/><Button type="button" disabled={busy} onClick={()=>void load()} tone="primary" size="sm">Search</Button></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(420px,0.9fr)]">
      <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><div className="text-xs font-black uppercase tracking-wide text-slate-500">Current source inventory</div><div className="mt-1 text-sm text-slate-600">{items.length} observations in current filter</div></div><div className="max-h-[760px] overflow-auto">{items.map(item=><button key={item.key} type="button" onClick={()=>void open(item.key)} className={`block w-full border-b border-slate-100 px-5 py-4 text-left hover:bg-slate-50 ${detail?.observation.key===item.key?'bg-blue-50':''}`}><div className="flex items-start justify-between gap-3"><div><div className="font-mono text-sm font-bold text-slate-950">{item.key}</div><div className="mt-1 text-xs text-slate-500">{item.namespace} · floor {item.mutabilityFloor}</div></div><Pill>{item.status}</Pill></div><div className="mt-2 flex flex-wrap gap-1">{item.reviewFlags.slice(0,4).map(f=><Pill key={f}>{f}</Pill>)}</div></button>)}</div></div>
      <div className="space-y-4">{!detail?<div className="rounded-3xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">Select one observation to review its source evidence and governance state.</div>:<>
        <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-black uppercase tracking-wide text-slate-500">Observation</div><h3 className="mt-1 break-all font-mono text-lg font-black">{detail.observation.key}</h3></div><Pill>{g?.status}</Pill></div><div className="mt-3 break-all rounded-xl bg-slate-50 p-3 font-mono text-[10px] text-slate-500">Source hash: {hash}</div><div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900"><b>Advisory only — not authority.</b><pre className="mt-2 whitespace-pre-wrap">{JSON.stringify(detail.observation.advisoryClassification,null,2)}</pre></div><div className="mt-3 flex flex-wrap gap-1">{detail.observation.reviewFlags.map(f=><Pill key={f}>{f}</Pill>)}</div></div>
        <div className={`rounded-3xl border p-5 shadow-sm ${detail.readiness.ready?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><div className="text-xs font-black uppercase tracking-wide">Migration Ready Gate</div><div className="mt-1 text-lg font-black">{detail.readiness.ready?'Ready for authorization':'Blocked'}</div>{detail.readiness.blockers.length>0&&<ul className="mt-3 list-disc space-y-1 pl-5 text-xs">{detail.readiness.blockers.map(b=><li key={b}>{b}</li>)}</ul>}{detail.definition&&<div className="mt-3 text-xs">Definition: <span className="font-mono">{detail.definition.sourceRef}</span> · migrationAuthorized={String(detail.definition.migrationAuthorized)}</div>}</div>
        {(g?.status==='DISCOVERED'||g?.status==='CLASSIFIED')&&canEdit&&<div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-black uppercase tracking-wide text-slate-500">Human classification</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><input value={owner} onChange={e=>setOwner(e.target.value)} placeholder="Domain owner" className="rounded-xl border border-slate-300 px-3 py-2 text-sm"/><Select value={authority} onChange={setAuthority} values={AUTHORITIES}/><Select value={scope} onChange={setScope} values={SCOPES}/><Select value={risk} onChange={setRisk} values={RISKS}/><Select value={mutability} onChange={setMutability} values={MUTABILITIES}/><Select value={consumer} onChange={setConsumer} values={CONSUMERS}/></div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={adminEditable} onChange={e=>setAdminEditable(e.target.checked)}/> Admin editable</label><label className="mt-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={requiresApproval} onChange={e=>setRequiresApproval(e.target.checked)}/> Approval required</label></div>}
        {(canEdit||canApprove||canPublish)&&g?.status!=='MIGRATED'&&g?.status!=='LEGACY_RETIRED'&&<div className="rounded-3xl border border-indigo-200 bg-indigo-50 p-5"><div className="text-xs font-black uppercase tracking-wide text-indigo-700">Audit reason</div><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3} className="mt-3 w-full rounded-xl border border-indigo-200 bg-white px-3 py-2 text-sm" placeholder="Explain the governance decision and evidence reviewed."/><div className="mt-3 flex flex-wrap gap-2">{(g?.status==='DISCOVERED'||g?.status==='CLASSIFIED')&&canEdit&&<Button disabled={busy} onClick={()=>void act(()=>configurationMigrationGovernanceApi.classify(detail.observation.key,{authorityClass:authority,domainOwner:owner,scope,risk,mutability,consumerContract:consumer,adminEditable,requiresApproval,expectedSourceObservationHash:hash,expectedVersion:version,reason:reason.trim()}),'Classification saved.')} tone="primary" size="xs">Save classification</Button>}{g?.status==='CLASSIFIED'&&canEdit&&<Button disabled={busy} onClick={()=>void act(()=>configurationMigrationGovernanceApi.ownerReview(detail.observation.key,hash,version,reason.trim()),'Owner review recorded.')} tone="primary" size="xs">Owner reviewed</Button>}{g?.status==='OWNER_REVIEWED'&&canApprove&&<Button disabled={busy} onClick={()=>void act(()=>configurationMigrationGovernanceApi.architectureApprove(detail.observation.key,hash,version,reason.trim()),'Architecture approval recorded.')} tone="success" size="xs">Architecture approve</Button>}{g?.status==='ARCHITECTURE_APPROVED'&&canPublish&&<Button disabled={busy||!detail.readiness.ready} onClick={()=>void act(()=>configurationMigrationGovernanceApi.authorizeMigration(detail.observation.key,hash,version,reason.trim()),'Migration Ready authorization recorded.')} tone="success" size="xs">Authorize MIGRATION_READY</Button>}</div></div>}
        <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-black uppercase tracking-wide text-slate-500">Append-only review history</div><div className="mt-3 space-y-2">{detail.events.length===0?<p className="text-sm text-slate-500">No human governance event yet.</p>:detail.events.map(e=><div key={e.eventId} className="rounded-xl border border-slate-100 bg-slate-50 p-3 text-xs"><div className="font-black">{e.eventType} · {e.fromStatus} → {e.toStatus}</div><div className="mt-1 text-slate-600">{e.actor} · {new Date(e.createdAt).toLocaleString()}</div><div className="mt-2">{e.reason}</div></div>)}</div></div>
      </>}</div>
    </div>
  </div>;
}
