package com.opensocket.aievent.core.integration.identity;
import java.util.List; import java.util.Optional;
public interface IntegrationIdentityRepository {
 IntegrationConnection saveConnection(IntegrationConnection value); Optional<IntegrationConnection> findConnection(String tenantId,String id); List<IntegrationConnection> listConnections(String tenantId,int limit); List<IntegrationConnection> listConnectionsAuthorized(String tenantId,IntegrationResourceScope scope,int limit);
 IntegrationPrincipal savePrincipal(IntegrationPrincipal value); Optional<IntegrationPrincipal> findPrincipal(String tenantId,String id); List<IntegrationPrincipal> listPrincipals(String tenantId,String connectionId,int limit); List<IntegrationPrincipal> listPrincipalsAuthorized(String tenantId,String connectionId,IntegrationResourceScope scope,int limit);
 IntegrationCredentialMetadata saveCredential(IntegrationCredentialMetadata value); Optional<IntegrationCredentialMetadata> findCredential(String tenantId,String id); List<IntegrationCredentialMetadata> listCredentials(String tenantId,String principalId,int limit); List<IntegrationCredentialMetadata> listCredentialsAuthorized(String tenantId,String principalId,IntegrationResourceScope scope,int limit);
 IntegrationProjectMapping saveMapping(IntegrationProjectMapping value); Optional<IntegrationProjectMapping> findMapping(String tenantId,String id); List<IntegrationProjectMapping> listMappings(String tenantId,String connectionId,int limit); List<IntegrationProjectMapping> listMappingsAuthorized(String tenantId,String connectionId,IntegrationResourceScope scope,int limit); List<IntegrationProjectMapping> resolutionCandidates(MappingResolutionRequest request);
 PermissionProbeResult saveProbe(PermissionProbeResult value); Optional<PermissionProbeResult> latestProbe(String tenantId,String principalId,String mappingId);
 CredentialRotationEvent saveRotationEvent(CredentialRotationEvent value); List<CredentialRotationEvent> listRotationEvents(String tenantId,String principalId,int limit);
 IntegrationPrincipalScope savePrincipalScope(IntegrationPrincipalScope value); Optional<IntegrationPrincipalScope> findPrincipalScope(String tenantId,String principalId); List<IntegrationPrincipalScope> listPrincipalScopes(String tenantId,String connectionId,int limit);
 IntegrationSecurityOverride saveSecurityOverride(IntegrationSecurityOverride value); Optional<IntegrationSecurityOverride> findSecurityOverride(String tenantId,String overrideId); List<IntegrationSecurityOverride> listSecurityOverrides(String tenantId,String principalId,String mappingId,int limit);
 IntegrationPermissionChangeEvent savePermissionChangeEvent(IntegrationPermissionChangeEvent value); List<IntegrationPermissionChangeEvent> listPermissionChangeEvents(String tenantId,String principalId,String mappingId,int limit);
 IntegrationProviderAuthorizationFailure saveAuthorizationFailure(IntegrationProviderAuthorizationFailure value); List<IntegrationProviderAuthorizationFailure> listAuthorizationFailures(String tenantId,String mappingId,int limit);
 ProviderMetadataSnapshot saveMetadataSnapshot(ProviderMetadataSnapshot value); Optional<ProviderMetadataSnapshot> findMetadataSnapshot(String tenantId,String snapshotId); Optional<ProviderMetadataSnapshot> latestMetadataSnapshot(String tenantId,String mappingId); List<ProviderMetadataSnapshot> listMetadataSnapshots(String tenantId,String mappingId,int limit);
 IntegrationProjectMappingVersion saveMappingVersion(IntegrationProjectMappingVersion value); Optional<IntegrationProjectMappingVersion> findMappingVersion(String tenantId,String mappingId,int mappingVersion); List<IntegrationProjectMappingVersion> listMappingVersions(String tenantId,String mappingId,int limit);
 CredentialBlastRadius blastRadius(String tenantId,String credentialId);
 String mode();
}
