'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { coreAdminApi } from '@/lib/api/coreAdminApi';
import { createIdempotencyKey } from '@/lib/utils/uuid';
import type { CoreAggregationDefinition,CoreAggregationPreparationDecision,CoreCanonicalCapabilityDefinition,CoreEnterpriseCaseRecord,CorePlanExecutionArtifact,CorePlanExecutionRun,CoreCaseArtifactLink,CoreCaseIssueProjection,CoreCaseEvent } from '@/lib/types/core';

const EMPTY:CoreAggregationDefinition={aggregationId:'default-root-cause-synthesis',displayName:'Root Cause Synthesis',aggregationCapabilityCode:'',operation:'ANALYZE',requiredInputCapabilities:[],minInputConfidence:0.5,allowPartialEvidence:false,requireHumanReviewOnPartial:true,status:'DRAFT',version:1};
export function CaseConvergenceConsole(){
 const [definitions,setDefinitions]=useState<CoreAggregationDefinition[]>([]),[definition,setDefinition]=useState<CoreAggregationDefinition>(EMPTY),[capabilities,setCapabilities]=useState<CoreCanonicalCapabilityDefinition[]>([]),[runs,setRuns]=useState<CorePlanExecutionRun[]>([]),[runId,setRunId]=useState(''),[artifacts,setArtifacts]=useState<CorePlanExecutionArtifact[]>([]),[selectedArtifactIds,setSelectedArtifactIds]=useState<string[]>([]),[decision,setDecision]=useState<CoreAggregationPreparationDecision|null>(null),[cases,setCases]=useState<CoreEnterpriseCaseRecord[]>([]),[caseId,setCaseId]=useState(''),[caseArtifacts,setCaseArtifacts]=useState<CoreCaseArtifactLink[]>([]),[projections,setProjections]=useState<CoreCaseIssueProjection[]>([]),[events,setEvents]=useState<CoreCaseEvent[]>([]),[aggregationArtifactId,setAggregationArtifactId]=useState(''),[classification,setClassification]=useState(''),[affectedResources,setAffectedResources]=useState(''),[status,setStatus]=useState('');
 const projectionKeyRef=useRef<{caseId:string,key:string}|null>(null);
 const selectedCase=useMemo(()=>cases.find(c=>c.caseId===caseId),[cases,caseId]);
 async function refresh(){try{const [d,c,r,cs]=await Promise.all([coreAdminApi.getAggregationDefinitions(undefined,'',100),coreAdminApi.getCanonicalCapabilities('ACTIVE',undefined,undefined,'',100),coreAdminApi.getPlanExecutionRuns(undefined,'',undefined,100),coreAdminApi.getEnterpriseCases(undefined,'',undefined,100)]);setDefinitions(d);setCapabilities(c);setRuns(r.filter(x=>x.status==='SUCCEEDED'||x.status==='PARTIAL_SUCCEEDED'));setCases(cs);if(!runId&&r.find(x=>x.status==='SUCCEEDED'||x.status==='PARTIAL_SUCCEEDED'))setRunId((r.find(x=>x.status==='SUCCEEDED'||x.status==='PARTIAL_SUCCEEDED'))!.runId);if(!caseId&&cs[0])setCaseId(cs[0].caseId);setStatus('')}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 async function refreshRun(id=runId){if(!id){setArtifacts([]);return}try{const a=await coreAdminApi.getPlanExecutionArtifacts(id,undefined,'',500);setArtifacts(a);setSelectedArtifactIds(a.map(x=>x.artifactId));if(!aggregationArtifactId&&a[0])setAggregationArtifactId(a[0].artifactId)}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 async function refreshCase(id=caseId){if(!id)return;try{const [a,p,e]=await Promise.all([coreAdminApi.getEnterpriseCaseArtifacts(id),coreAdminApi.getCaseIssueProjections(id),coreAdminApi.getEnterpriseCaseEvents(id)]);setCaseArtifacts(a);setProjections(p);setEvents(e)}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 // Initial catalog bootstrap intentionally runs once; state-driven refreshes are handled by the following effects/actions.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void refresh()},[]);
 // refreshRun accepts the authoritative run id; other captured values only initialize optional selections.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void refreshRun(runId)},[runId]);
 // refreshCase accepts the authoritative case id and is re-run only when that id changes.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void refreshCase(caseId)},[caseId]);
 async function saveDefinition(){try{const saved=await coreAdminApi.upsertAggregationDefinition(definition.aggregationId,definition,'',definitions.some(x=>x.aggregationId===definition.aggregationId)?'Phase 9 aggregation definition update':undefined);setDefinition(saved);await refresh();setStatus('Aggregation Definition saved. It names WHAT synthesis capability is required; no Provider/Agent/transport is selected.')}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 async function prepare(){try{const d=await coreAdminApi.prepareAggregation({aggregationId:definition.aggregationId,runId,artifactIds:selectedArtifactIds});setDecision(d);setStatus(d.result==='READY_FOR_CAPABILITY_EXECUTION'?'Aggregation WHAT prepared. The requirement must still traverse WHO CAN → WHO MAY → WHO SHOULD → HOW.':`Aggregation preparation: ${d.result}`)}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 async function converge(){try{if(!aggregationArtifactId){setStatus('Select the authoritative aggregation Artifact first.');return}const c=await coreAdminApi.convergeEnterpriseCase({runId,aggregationId:definition.aggregationId,aggregationArtifactId,classification:classification||undefined,affectedResources:affectedResources.split(',').map(x=>x.trim()).filter(Boolean),idempotencyKey:`case-${runId}-${aggregationArtifactId}`});setCaseId(c.caseId);await refresh();await refreshCase(c.caseId);setStatus('Canonical enterprise Case created. Root cause is aggregation-Artifact-derived; Child Tasks did not create external Issues.')}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 async function review(next:string){if(!caseId)return;try{await coreAdminApi.reviewEnterpriseCase(caseId,{status:next,humanDecision:next==='RESOLVED'?'Reviewed and accepted':'Under review',accountableRef:'human-review',reason:`Phase 9 ${next.toLowerCase()} review`});await refresh();await refreshCase();setStatus(`Case moved to ${next}. Root cause evidence was not rewritten.`)}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 async function addProjection(){if(!caseId)return;const pending=projectionKeyRef.current;const key=pending?.caseId===caseId?pending.key:createIdempotencyKey('case-issue-projection');projectionKeyRef.current={caseId,key};try{await coreAdminApi.recordCaseIssueProjection(caseId,{connectorType:'JIRA',targetRef:'project-placeholder',primaryProjection:projections.length===0,idempotencyKey:key});projectionKeyRef.current=null;await refreshCase();setStatus('Issue projection intent recorded only. No external Jira/GitLab/Redmine/SOC I/O occurred.')}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 return <div className="space-y-5">
  <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-black uppercase tracking-wide text-violet-700">Phase 9 · Execution Artifact Aggregation / Case Convergence</div><h2 className="mt-1 text-xl font-black">Evidence converges into one enterprise Case</h2><p className="mt-2 text-sm leading-6 text-slate-600">Aggregation consumes normalized Phase 8 Artifacts and names an <b>Aggregation Capability</b>, never an Aggregator Agent ID. Preparing aggregation does not select a Provider; the requirement must still traverse WHO CAN → WHO MAY → WHO SHOULD → HOW. A Case is the enterprise problem authority. Child Tasks never create independent Issues by default, and external Issues are 0..N projections.</p></section>
  <section className="grid gap-4 xl:grid-cols-2"><div className="rounded-3xl border bg-white p-5"><h3 className="font-black">Aggregation Definition</h3><div className="mt-3 grid gap-2"><input className="rounded-xl border p-2" value={definition.aggregationId} onChange={e=>setDefinition({...definition,aggregationId:e.target.value})}/><input className="rounded-xl border p-2" value={definition.displayName} onChange={e=>setDefinition({...definition,displayName:e.target.value})}/><select className="rounded-xl border p-2" value={definition.aggregationCapabilityCode} onChange={e=>setDefinition({...definition,aggregationCapabilityCode:e.target.value})}><option value="">Select Canonical aggregation capability…</option>{capabilities.map(c=><option key={c.capabilityCode} value={c.capabilityCode}>{c.capabilityCode}</option>)}</select><input className="rounded-xl border p-2" placeholder="Operation" value={definition.operation} onChange={e=>setDefinition({...definition,operation:e.target.value})}/><input className="rounded-xl border p-2" placeholder="Required input capabilities, comma separated" value={(definition.requiredInputCapabilities||[]).join(', ')} onChange={e=>setDefinition({...definition,requiredInputCapabilities:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/><select className="rounded-xl border p-2" value={definition.status} onChange={e=>setDefinition({...definition,status:e.target.value})}><option>DRAFT</option><option>ACTIVE</option><option>DISABLED</option><option>RETIRED</option></select></div><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={definition.allowPartialEvidence} onChange={e=>setDefinition({...definition,allowPartialEvidence:e.target.checked})}/> Allow partial evidence</label><button className="mt-3 rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white" onClick={()=>void saveDefinition()}>Save definition</button></div>
  <div className="rounded-3xl border bg-white p-5"><h3 className="font-black">Prepare Aggregation WHAT</h3><select className="mt-3 w-full rounded-xl border p-2" value={runId} onChange={e=>setRunId(e.target.value)}><option value="">Select terminal Plan run…</option>{runs.map(r=><option key={r.runId} value={r.runId}>{r.runId} · {r.status}</option>)}</select><div className="mt-3 max-h-56 overflow-auto rounded-xl border p-2">{artifacts.map(a=><label key={a.artifactId} className="flex gap-2 py-1 text-xs"><input type="checkbox" checked={selectedArtifactIds.includes(a.artifactId)} onChange={e=>setSelectedArtifactIds(e.target.checked?[...selectedArtifactIds,a.artifactId]:selectedArtifactIds.filter(x=>x!==a.artifactId))}/><span>{a.capabilityCode} · {a.artifactId}</span></label>)}</div><button className="mt-3 rounded-xl bg-violet-700 px-4 py-2 text-sm font-black text-white" onClick={()=>void prepare()}>Prepare aggregation</button><pre className="mt-3 max-h-52 overflow-auto rounded-2xl bg-slate-950 p-3 text-xs text-slate-100">{decision?JSON.stringify(decision,null,2):'No preparation decision yet.'}</pre></div></section>
  <section className="rounded-3xl border bg-white p-5"><h3 className="font-black">Converge to canonical Case</h3><div className="mt-3 grid gap-2 md:grid-cols-2"><select className="rounded-xl border p-2" value={aggregationArtifactId} onChange={e=>setAggregationArtifactId(e.target.value)}><option value="">Select authoritative aggregation Artifact…</option>{artifacts.map(a=><option key={a.artifactId} value={a.artifactId}>{a.capabilityCode} · {a.artifactId}</option>)}</select><input className="rounded-xl border p-2" placeholder="Classification" value={classification} onChange={e=>setClassification(e.target.value)}/><input className="rounded-xl border p-2 md:col-span-2" placeholder="Affected resources, comma separated" value={affectedResources} onChange={e=>setAffectedResources(e.target.value)}/></div><button className="mt-3 rounded-xl bg-emerald-700 px-4 py-2 text-sm font-black text-white" onClick={()=>void converge()}>Create canonical Case</button><p className="mt-2 text-xs text-slate-500">Root cause/confidence/recommended actions are derived from the selected aggregation Artifact. This action does not materialize an external Issue.</p></section>
  <section className="grid gap-4 xl:grid-cols-2"><div className="rounded-3xl border bg-white p-5"><h3 className="font-black">Cases</h3><select className="mt-3 w-full rounded-xl border p-2" value={caseId} onChange={e=>setCaseId(e.target.value)}><option value="">Select Case…</option>{cases.map(c=><option key={c.caseId} value={c.caseId}>{c.caseId} · {c.status}</option>)}</select>{selectedCase?<div className="mt-3 rounded-2xl bg-slate-50 p-4 text-sm"><div className="font-black">{selectedCase.classification||selectedCase.caseId}</div><div className="mt-2"><b>Root cause:</b> {selectedCase.rootCause||'Not provided by aggregation Artifact'}</div><div><b>Confidence:</b> {selectedCase.confidence??'n/a'}</div><div><b>Task:</b> {selectedCase.sourceTaskRef||'n/a'}</div><div><b>Trace:</b> {selectedCase.traceId}</div></div>:null}<div className="mt-3 flex flex-wrap gap-2"><button className="rounded-xl border px-3 py-2 text-sm font-black" onClick={()=>void review('UNDER_REVIEW')}>Under review</button><button className="rounded-xl border px-3 py-2 text-sm font-black" onClick={()=>void review('RESOLVED')}>Resolve</button><button className="rounded-xl border px-3 py-2 text-sm font-black" onClick={()=>void addProjection()}>Record issue projection intent</button></div></div><div className="rounded-3xl border bg-white p-5"><h3 className="font-black">Evidence & projections</h3><div className="mt-3 text-xs font-black text-slate-500">Case Artifact links</div><pre className="mt-1 max-h-40 overflow-auto rounded-2xl bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(caseArtifacts,null,2)}</pre><div className="mt-3 text-xs font-black text-slate-500">0..N external Issue projections</div><pre className="mt-1 max-h-40 overflow-auto rounded-2xl bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(projections,null,2)}</pre></div></section>
  <section className="rounded-3xl border bg-white p-5"><h3 className="font-black">Case audit events</h3><pre className="mt-3 max-h-72 overflow-auto rounded-2xl bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(events,null,2)}</pre></section>{status?<div className="rounded-2xl border bg-slate-50 p-3 text-sm">{status}</div>:null}
 </div>
}
