'use client';
import { useCallback, useEffect, useState } from 'react';
import { useAuth } from '@/components/auth/AuthProvider';
import { coreAdminApi } from '@/lib/api/coreAdminApi';
import type { CoreCapabilityProvider, CoreExecutionAdapterRegistration, CoreExecutionAdapterResolution, CoreExecutionAdapterVersion, CoreProviderRoutingDecision } from '@/lib/types/core';

const PAGE_SIZE=50;
const TYPES: Record<string,string[]> = { MANAGED_AGENT:['MANAGED_AGENT_NETTY'], REMOTE_A2A_AGENT:['REMOTE_A2A'], MCP_TOOL:['MCP_TOOL'], INTERNAL_SERVICE:['INTERNAL_SERVICE'] };
const PROTOCOLS: Record<string,string[]> = { MANAGED_AGENT_NETTY:['NETTY_TCP','NETTY_WEBSOCKET'], REMOTE_A2A:['A2A_JSON_RPC','A2A_GRPC','A2A_HTTP_JSON'], MCP_TOOL:['MCP_STREAMABLE_HTTP','MCP_SSE','MCP_STDIO'], INTERNAL_SERVICE:['INTERNAL_HTTP_JSON','INTERNAL_GRPC'] };
function msg(c:unknown,f:string){return c instanceof Error&&c.message?c.message:f;}
function empty():CoreExecutionAdapterRegistration{return {adapterId:'',providerId:'',providerType:'MANAGED_AGENT',adapterType:'MANAGED_AGENT_NETTY',protocol:'NETTY_TCP',status:'DRAFT',selectionPriority:100,configuration:{}};}

export function ExecutionAdapterConsole(){
 const {activeTenantId:tenantId}=useAuth(); const [providers,setProviders]=useState<CoreCapabilityProvider[]>([]); const [adapters,setAdapters]=useState<CoreExecutionAdapterRegistration[]>([]); const [draft,setDraft]=useState(empty()); const [reason,setReason]=useState(''); const [versions,setVersions]=useState<CoreExecutionAdapterVersion[]>([]); const [decisionId,setDecisionId]=useState(''); const [resolution,setResolution]=useState<CoreExecutionAdapterResolution>(); const [resolutions,setResolutions]=useState<CoreExecutionAdapterResolution[]>([]); const [recentRouting,setRecentRouting]=useState<CoreProviderRoutingDecision[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
 const load=useCallback(async()=>{if(!tenantId)return;try{setProviders(await coreAdminApi.getCapabilityProviders(undefined,'REGISTERED',undefined,tenantId,undefined,PAGE_SIZE));setAdapters(await coreAdminApi.getExecutionAdapters(undefined,undefined,undefined,tenantId,undefined,PAGE_SIZE));setRecentRouting(await coreAdminApi.getProviderRoutingDecisions(undefined,tenantId,20));setResolutions(await coreAdminApi.getExecutionAdapterResolutions(undefined,tenantId,20));}catch(c){setError(msg(c,'Unable to load Execution Adapter data.'));}},[tenantId]);
 useEffect(()=>{void load();},[load]);
 function chooseProvider(id:string){const p=providers.find(x=>x.providerId===id);if(!p)return;const at=(TYPES[p.providerType]??[])[0]??'';setDraft({...draft,providerId:p.providerId,providerType:p.providerType,adapterType:at,protocol:(PROTOCOLS[at]??[])[0]??'',runtimeRef:p.providerType==='MANAGED_AGENT'?p.providerRef:undefined,endpointRef:undefined,credentialRef:undefined});}
 async function save(){if(!tenantId||!draft.adapterId||!draft.providerId)return;setBusy(true);setError('');setNotice('');try{const s=await coreAdminApi.upsertExecutionAdapter(draft.adapterId,draft,tenantId,reason||undefined);setDraft(s);setReason('');setVersions(await coreAdminApi.getExecutionAdapterVersions(s.adapterId,tenantId));setNotice(`Execution Adapter ${s.adapterId} v${s.version??1} saved. HOW configuration does not authorize or rank the provider.`);await load();}catch(c){setError(msg(c,'Execution Adapter could not be saved.'));}finally{setBusy(false);}}
 async function resolve(){if(!tenantId||!decisionId)return;setBusy(true);setError('');setNotice('');try{const r=await coreAdminApi.resolveExecutionAdapterPreview({routingDecisionId:decisionId},tenantId);setResolution(r);setNotice('HOW resolution persisted. No Netty/A2A/MCP/Internal Service I/O was executed.');await load();}catch(c){setError(msg(c,'HOW resolution failed.'));}finally{setBusy(false);}}
 return <div className="space-y-5">
  <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="text-xs font-black uppercase tracking-wide text-blue-700">Phase 5 · HOW</div><h2 className="mt-1 text-xl font-black">Execution Adapter Convergence</h2><p className="mt-2 text-sm text-slate-600">A2A, MCP, Netty and Internal Service are execution mechanisms only. They never participate in WHAT, WHO CAN, WHO MAY or WHO SHOULD.</p><div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-xs font-bold text-amber-900">Resolution accepts only a persisted Phase 4 SELECTED routing decision. It does not accept targetDomain, targetPool, targetAgent or a caller-selected provider.</div></section>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</div>}
  <section className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-black">Adapter Registry</h3><p className="mt-1 text-xs text-slate-500">Endpoint and credential fields are opaque registry references only. Raw URLs, bearer tokens and passwords are rejected by Core.</p><div className="mt-4 grid gap-3 md:grid-cols-3">
   <label className="text-xs font-bold">Adapter ID<input className="mt-1 w-full rounded-xl border px-3 py-2" value={draft.adapterId} onChange={e=>setDraft({...draft,adapterId:e.target.value})}/></label>
   <label className="text-xs font-bold">REGISTERED Provider<select className="mt-1 w-full rounded-xl border px-3 py-2" value={draft.providerId} onChange={e=>chooseProvider(e.target.value)}><option value="">Choose…</option>{providers.map(p=><option key={p.providerId} value={p.providerId}>{p.displayName} · {p.providerType}</option>)}</select></label>
   <label className="text-xs font-bold">Adapter Type<select className="mt-1 w-full rounded-xl border px-3 py-2" value={draft.adapterType} onChange={e=>{const a=e.target.value;setDraft({...draft,adapterType:a,protocol:(PROTOCOLS[a]??[])[0]??''});}}>{(TYPES[draft.providerType]??[]).map(x=><option key={x}>{x}</option>)}</select></label>
   <label className="text-xs font-bold">Protocol<select className="mt-1 w-full rounded-xl border px-3 py-2" value={draft.protocol} onChange={e=>setDraft({...draft,protocol:e.target.value})}>{(PROTOCOLS[draft.adapterType]??[]).map(x=><option key={x}>{x}</option>)}</select></label>
   <label className="text-xs font-bold">Protocol Version<input className="mt-1 w-full rounded-xl border px-3 py-2" value={draft.protocolVersion??''} onChange={e=>setDraft({...draft,protocolVersion:e.target.value||undefined})}/></label>
   <label className="text-xs font-bold">Status<select className="mt-1 w-full rounded-xl border px-3 py-2" value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{['DRAFT','ACTIVE','SUSPENDED','RETIRED'].map(x=><option key={x}>{x}</option>)}</select></label>
   {draft.adapterType==='MANAGED_AGENT_NETTY'?<label className="text-xs font-bold md:col-span-2">Runtime Registry Ref<input className="mt-1 w-full rounded-xl border px-3 py-2" value={draft.runtimeRef??''} onChange={e=>setDraft({...draft,runtimeRef:e.target.value||undefined})}/></label>:<><label className="text-xs font-bold">Endpoint Registry Ref<input className="mt-1 w-full rounded-xl border px-3 py-2" value={draft.endpointRef??''} onChange={e=>setDraft({...draft,endpointRef:e.target.value||undefined})}/></label><label className="text-xs font-bold">Credential Registry Ref<input className="mt-1 w-full rounded-xl border px-3 py-2" value={draft.credentialRef??''} onChange={e=>setDraft({...draft,credentialRef:e.target.value||undefined})}/></label></>}
   <label className="text-xs font-bold">Selection Priority<input type="number" className="mt-1 w-full rounded-xl border px-3 py-2" value={draft.selectionPriority??100} onChange={e=>setDraft({...draft,selectionPriority:Number(e.target.value)})}/></label>
   <label className="text-xs font-bold md:col-span-3">Change reason<input className="mt-1 w-full rounded-xl border px-3 py-2" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required when modifying an existing adapter"/></label>
  </div><button disabled={busy} onClick={()=>void save()} className="mt-4 rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white disabled:opacity-50">Save Execution Adapter</button>
  {versions.length>0&&<div className="mt-3 text-xs text-slate-500">Immutable versions: {versions.map(v=>`v${v.version}`).join(' · ')}</div>}
  <div className="mt-5 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead><tr className="border-b"><th className="p-2">Adapter</th><th className="p-2">Provider</th><th className="p-2">Type</th><th className="p-2">Protocol</th><th className="p-2">Status</th><th className="p-2">Priority</th></tr></thead><tbody>{adapters.map(a=><tr key={a.adapterId} className="border-b cursor-pointer" onClick={()=>{setDraft(a);void(coreAdminApi.getExecutionAdapterVersions(a.adapterId,tenantId).then(setVersions));}}><td className="p-2 font-bold">{a.adapterId}</td><td className="p-2">{a.providerId}</td><td className="p-2">{a.adapterType}</td><td className="p-2">{a.protocol}</td><td className="p-2">{a.status}</td><td className="p-2">{a.selectionPriority}</td></tr>)}</tbody></table></div></section>
  <section className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-black">Resolve HOW without executing anything</h3><p className="mt-1 text-xs text-slate-500">Choose a persisted Phase 4 SELECTED routing decision. Phase 5 revalidates that WHO MAY evidence, Provider/Binding trust, Routing Profile and latest eligibility evidence are still current before resolving an ACTIVE adapter.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">Phase 4 routing decision<select className="mt-1 w-full rounded-xl border px-3 py-2" value={decisionId} onChange={e=>setDecisionId(e.target.value)}><option value="">Choose…</option>{recentRouting.filter(d=>d.result==='SELECTED').map(d=><option key={d.decisionId} value={d.decisionId}>{d.decisionId} · {d.selectedProviderId}</option>)}</select></label></div><button disabled={busy||!decisionId} onClick={()=>void resolve()} className="mt-4 rounded-xl bg-blue-700 px-4 py-2 text-sm font-black text-white disabled:opacity-50">Resolve HOW</button>
  {resolution&&<div className="mt-4 rounded-2xl border bg-slate-50 p-4 text-sm"><div className="font-black">{resolution.result}</div><div className="mt-2">Binding <b>{resolution.bindingId??'—'}</b> → Adapter <b>{resolution.adapterId??'—'}</b> → {resolution.adapterType??'—'} / {resolution.protocol??'—'}</div><div className="mt-1 text-xs text-slate-500">Reasons: {(resolution.reasonCodes??[]).join(', ')||'—'}</div></div>}
  <div className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-bold text-emerald-900">A2A/MCP/Netty is selected only here, after WHO SHOULD. This preview persists HOW evidence but performs no external I/O.</div></section>
  {resolutions.length>0&&<section className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-black">Recent HOW evidence</h3><div className="mt-3 space-y-2">{resolutions.map(r=><div key={r.resolutionId} className="rounded-xl border p-3 text-xs"><b>{r.result}</b> · {r.routingDecisionId} · {r.adapterType??'no adapter'} / {r.protocol??'—'}</div>)}</div></section>}
 </div>;
}
