'use client';

import { useCallback, useEffect, useState } from 'react';
import { useAuth } from '@/components/auth/AuthProvider';
import { coreAdminApi } from '@/lib/api/coreAdminApi';
import type { CoreExecutionSafetyPrepareResult, CoreFlowRoutingMigrationState } from '@/lib/types/core';

function msg(c: unknown, fallback: string) { return c instanceof Error && c.message ? c.message : fallback; }
function val(v: unknown) { return v === null || v === undefined || v === '' ? '—' : String(v); }

export function ExecutionSafetyAuthorityConsole() {
  const { activeTenantId: tenantId } = useAuth();
  const [flowId,setFlowId]=useState(''); const [authority,setAuthority]=useState<'LEGACY_AUTHORITATIVE'|'SHADOW'|'NEW_AUTHORITATIVE'>('SHADOW');
  const [reason,setReason]=useState(''); const [planId,setPlanId]=useState(''); const [revision,setRevision]=useState('');
  const [stepId,setStepId]=useState(''); const [profile,setProfile]=useState(''); const [ownerNode,setOwnerNode]=useState(''); const [ttl,setTtl]=useState('60');
  const [approval,setApproval]=useState(''); const [prepared,setPrepared]=useState<CoreExecutionSafetyPrepareResult>(); const [recent,setRecent]=useState<Record<string,unknown>[]>([]);
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('');

  const loadRecent=useCallback(async()=>{if(!tenantId)return;try{setRecent(await coreAdminApi.getExecutionSafetyRecentIntents(tenantId,50));}catch(c){setError(msg(c,'Unable to load execution-safety trace.'));}},[tenantId]);
  useEffect(()=>{void loadRecent();},[loadRecent]);

  async function changeAuthority(){if(!tenantId||!flowId.trim()||!reason.trim()){setError('Flow ID and audited change reason are required.');return;}setBusy(true);setError('');setNotice('');try{const r:CoreFlowRoutingMigrationState=await coreAdminApi.setExecutionSafetyFlowAuthority(flowId.trim(),{targetState:authority,reason:reason.trim()},tenantId);setNotice(`${r.flowId} is now ${r.migrationState}. NEW_AUTHORITATIVE remains per-Flow and requires R6 shadow evidence.`);}catch(c){setError(msg(c,'Flow execution authority change failed.'));}finally{setBusy(false);}}
  async function prepare(){if(!tenantId||!planId.trim()||!stepId.trim()||!profile.trim()||!ownerNode.trim()){setError('Plan ID, Step ID, Routing Profile and owner node are required.');return;}setBusy(true);setError('');setNotice('');try{const r=await coreAdminApi.prepareExecutionSafety(planId.trim(),{planRevision:revision?Number(revision):undefined,stepId:stepId.trim(),routingProfileId:profile.trim(),ownerNodeId:ownerNode.trim(),leaseTtlSeconds:ttl?Number(ttl):60,humanApprovalRef:approval.trim()||undefined,input:{}},tenantId);setPrepared(r);setNotice('Assignment + ExecutionLease + DispatchIntent committed atomically. No network send occurred in the prepare transaction.');await loadRecent();}catch(c){setError(msg(c,'Execution safety preparation failed.'));}finally{setBusy(false);}}
  async function handoff(){if(!tenantId)return;setBusy(true);setError('');setNotice('');try{const r=await coreAdminApi.handoffNextExecutionSafetyIntent(tenantId);setNotice(`Runtime outbox handoff: ${JSON.stringify(r)}`);await loadRecent();}catch(c){setError(msg(c,'DispatchIntent handoff failed.'));}finally{setBusy(false);}}

  return <div className="space-y-5">
    <section className="rounded-3xl border border-red-200 bg-red-50 p-5"><div className="text-xs font-black uppercase tracking-wide text-red-700">A0-R7 · controlled execution authority</div><h2 className="mt-1 text-xl font-black text-slate-950">Lease, fencing and durable DispatchIntent before any network send</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-700">NEW_AUTHORITATIVE is per Flow only, requires R6 shadow evidence, and Stage 8 controlled-live supports Managed Agent Netty only. MCP/A2A remain non-authoritative until their protocol runtime gates. Prepare commits canonical Assignment + Lease + Intent in one transaction; the existing dispatch worker sends only after the R7 pre-network guard revalidates authority, Envelope and fencing.</p></section>
    {(error||notice)&&<div className={`rounded-2xl border p-4 text-sm font-bold ${error?'border-red-200 bg-red-50 text-red-800':'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{error||notice}</div>}

    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">Per-Flow authority</h3><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-xs font-bold">Flow ID<input className="mt-1 w-full rounded-xl border px-3 py-2" value={flowId} onChange={e=>setFlowId(e.target.value)}/></label><label className="text-xs font-bold">Target state<select className="mt-1 w-full rounded-xl border px-3 py-2" value={authority} onChange={e=>setAuthority(e.target.value as typeof authority)}><option>LEGACY_AUTHORITATIVE</option><option>SHADOW</option><option>NEW_AUTHORITATIVE</option></select></label><label className="text-xs font-bold">Change reason<input className="mt-1 w-full rounded-xl border px-3 py-2" value={reason} onChange={e=>setReason(e.target.value)}/></label></div><button disabled={busy} onClick={()=>void changeAuthority()} className="mt-4 rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white disabled:opacity-50">Apply per-Flow authority</button></section>

    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">Prepare controlled execution</h3><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-xs font-bold">Plan ID<input className="mt-1 w-full rounded-xl border px-3 py-2" value={planId} onChange={e=>setPlanId(e.target.value)}/></label><label className="text-xs font-bold">Revision<input type="number" className="mt-1 w-full rounded-xl border px-3 py-2" value={revision} onChange={e=>setRevision(e.target.value)}/></label><label className="text-xs font-bold">Step ID<input className="mt-1 w-full rounded-xl border px-3 py-2" value={stepId} onChange={e=>setStepId(e.target.value)}/></label><label className="text-xs font-bold">Routing Profile<input className="mt-1 w-full rounded-xl border px-3 py-2" value={profile} onChange={e=>setProfile(e.target.value)}/></label><label className="text-xs font-bold">Owner Node ID<input className="mt-1 w-full rounded-xl border px-3 py-2" value={ownerNode} onChange={e=>setOwnerNode(e.target.value)}/></label><label className="text-xs font-bold">Lease TTL seconds<input type="number" className="mt-1 w-full rounded-xl border px-3 py-2" value={ttl} onChange={e=>setTtl(e.target.value)}/></label><label className="text-xs font-bold md:col-span-3">Human approval ref (required for unsafe remote non-idempotent WRITE)<input className="mt-1 w-full rounded-xl border px-3 py-2" value={approval} onChange={e=>setApproval(e.target.value)}/></label></div><div className="mt-4 flex gap-2"><button disabled={busy} onClick={()=>void prepare()} className="rounded-xl bg-red-700 px-4 py-2 text-sm font-black text-white disabled:opacity-50">Commit Assignment + Lease + Intent</button><button disabled={busy} onClick={()=>void handoff()} className="rounded-xl border px-4 py-2 text-sm font-black">Handoff next Intent to runtime outbox</button></div></section>

    {prepared&&<section className="rounded-3xl border border-emerald-200 bg-emerald-50 p-5"><h3 className="font-black">Prepared execution authority</h3><div className="mt-3 grid gap-2 text-sm md:grid-cols-2"><b>Assignment</b><span className="break-all">{prepared.executionAssignment.assignmentId}</span><b>Safety mode</b><span>{prepared.executionAssignment.executionSafetyMode}</span><b>Lease</b><span className="break-all">{prepared.executionLease.leaseId}</span><b>Fencing token</b><span>{prepared.executionLease.fencingToken}</span><b>Lease until</b><span>{prepared.executionLease.leaseUntil}</span><b>DispatchIntent</b><span className="break-all">{prepared.dispatchIntent.intentId}</span><b>Intent state</b><span>{prepared.dispatchIntent.status}</span><b>Flow authority</b><span>{prepared.cutoverState}</span></div></section>}

    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h3 className="font-black">Recent execution-safety evidence</h3><button onClick={()=>void loadRecent()} className="rounded-xl border px-3 py-2 text-xs font-black">Refresh</button></div><div className="mt-3 overflow-auto"><table className="min-w-full text-left text-xs"><thead><tr className="border-b"><th className="p-2">Created</th><th className="p-2">Flow</th><th className="p-2">Assignment</th><th className="p-2">Safety</th><th className="p-2">Fence</th><th className="p-2">Lease</th><th className="p-2">Intent</th></tr></thead><tbody>{recent.map((r,i)=><tr key={i} className="border-b"><td className="p-2">{val(r.created_at)}</td><td className="p-2">{val(r.flow_id)}</td><td className="p-2">{val(r.assignment_id)}</td><td className="p-2">{val(r.execution_safety_mode)}</td><td className="p-2">{val(r.fencing_token)}</td><td className="p-2">{val(r.lease_status)}</td><td className="p-2">{val(r.intent_status)}</td></tr>)}</tbody></table></div></section>
  </div>;
}
