'use client';
import { useEffect, useMemo, useState } from 'react';
import { coreAdminApi } from '@/lib/api/coreAdminApi';
import type { CoreExecutionPlan, CoreFastPathRuntimeCertification, CoreFastPathRuntimeDecision, CoreFastPathRuntimePolicy, CoreFastPathShadowComparison, CoreRoutingPattern } from '@/lib/types/core';

const pct=(n?:number)=>n==null?'—':`${(n*100).toFixed(1)}%`;
export function FastPathRuntimeConsole(){
  const [policies,setPolicies]=useState<CoreFastPathRuntimePolicy[]>([]); const [patterns,setPatterns]=useState<CoreRoutingPattern[]>([]); const [plans,setPlans]=useState<CoreExecutionPlan[]>([]); const [comparisons,setComparisons]=useState<CoreFastPathShadowComparison[]>([]); const [certs,setCerts]=useState<CoreFastPathRuntimeCertification[]>([]); const [decisions,setDecisions]=useState<CoreFastPathRuntimeDecision[]>([]); const [message,setMessage]=useState(''); const [busy,setBusy]=useState('');
  const [policyId,setPolicyId]=useState('default-fast-path-runtime'); const [patternId,setPatternId]=useState(''); const [planId,setPlanId]=useState('');
  const active=useMemo(()=>policies.find(p=>p.status==='ACTIVE'),[policies]);
  async function load(){const [p,rp,ep,sc,rc,rd]=await Promise.all([coreAdminApi.getFastPathRuntimePolicies(undefined,'',100),coreAdminApi.getRoutingPatterns(undefined,'',100),coreAdminApi.getExecutionPlans(undefined,'',undefined,100),coreAdminApi.getFastPathShadowComparisons(undefined,'',100),coreAdminApi.getFastPathRuntimeCertifications(undefined,'',100),coreAdminApi.getFastPathRuntimeDecisions(undefined,'',100)]);setPolicies(p);setPatterns(rp);setPlans(ep);setComparisons(sc);setCerts(rc);setDecisions(rd);}
  useEffect(()=>{load().catch(e=>setMessage(String(e)));},[]);
  async function run(key:string,fn:()=>Promise<unknown>){setBusy(key);setMessage('');try{await fn();await load();setMessage('Saved. Review the evidence below.');}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy('');}}
  const shadowPatterns=patterns.filter(p=>p.status==='SHADOW'); const activePatterns=patterns.filter(p=>p.status==='ACTIVE');
  return <div className="space-y-5">
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-black uppercase tracking-wide text-indigo-700">Phase 11 · Runtime Integration / Shadow / Certification</div><h2 className="mt-1 text-xl font-black">ACTIVE semantic pattern is not runtime authority</h2><p className="mt-2 text-sm leading-6 text-slate-600">Runtime use requires a current Human certification for the exact Pattern version and Runtime Policy version. SHADOW comparison only measures what the learned Plan would have proposed; it never changes the real Task, Provider selection, dispatch or result. Emergency kill switch always falls back to the Adaptive Path.</p></section>
    {message&&<div className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm">{message}</div>}
    <section className="grid gap-4 xl:grid-cols-2">
      <div className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-black">1. Runtime Policy & Kill Switch</h3><p className="mt-1 text-sm text-slate-600">These thresholds certify runtime use. They do not alter WHO MAY → WHO SHOULD → HOW.</p><input className="mt-3 w-full rounded-xl border p-2 text-sm" value={policyId} onChange={e=>setPolicyId(e.target.value)} /><div className="mt-3 flex flex-wrap gap-2"><button className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={!!busy} onClick={()=>run('policy',()=>coreAdminApi.upsertFastPathRuntimePolicy(policyId,{policyId,displayName:'Default Fast Path Runtime Policy',activeFastPathEnabled:true,shadowEvaluationEnabled:true,emergencyKillSwitch:false,minShadowComparisons:3,minShadowPlanMatchRate:.9,minShadowCapabilityCoverage:1,status:'ACTIVE'},'',active?'Update Phase 11 runtime policy':'Initial Phase 11 runtime policy'))}>{active?'Update active policy':'Create active policy'}</button>{active&&<button className="rounded-xl bg-red-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={!!busy} onClick={()=>run('kill',()=>coreAdminApi.upsertFastPathRuntimePolicy(active.policyId,{...active,emergencyKillSwitch:!active.emergencyKillSwitch},'',active.emergencyKillSwitch?'Human governance: clear emergency Fast Path kill switch':'Emergency governance: disable all Fast Path runtime'))}>{active.emergencyKillSwitch?'Clear kill switch':'Emergency kill switch'}</button>}</div>{active&&<div className={`mt-4 rounded-2xl p-3 text-sm ${active.emergencyKillSwitch?'bg-red-50 text-red-900':'bg-emerald-50 text-emerald-900'}`}><b>{active.displayName}</b><div>Runtime enabled: {String(active.activeFastPathEnabled)} · Shadow: {String(active.shadowEvaluationEnabled)} · Kill switch: {String(active.emergencyKillSwitch)}</div><div>Certification: {active.minShadowComparisons} comparisons · {pct(active.minShadowPlanMatchRate)} plan match · {pct(active.minShadowCapabilityCoverage)} capability coverage</div></div>}</div>
      <div className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-black">2. SHADOW comparison</h3><p className="mt-1 text-sm text-slate-600">Compare one SHADOW semantic pattern with the actual adaptive Plan. No runtime I/O occurs.</p><select className="mt-3 w-full rounded-xl border p-2 text-sm" value={patternId} onChange={e=>setPatternId(e.target.value)}><option value="">Choose SHADOW pattern</option>{shadowPatterns.map(p=><option key={p.patternId} value={p.patternId}>{p.patternId} · v{p.version}</option>)}</select><select className="mt-2 w-full rounded-xl border p-2 text-sm" value={planId} onChange={e=>setPlanId(e.target.value)}><option value="">Choose actual adaptive Plan</option>{plans.map(p=><option key={p.planId} value={p.planId}>{p.planId} · r{p.currentRevision}</option>)}</select><button className="mt-2 rounded-xl bg-indigo-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={!patternId||!planId||!!busy} onClick={()=>run('shadow',()=>coreAdminApi.compareFastPathShadow({patternId,actualPlanId:planId}))}>Record SHADOW comparison</button><div className="mt-3 text-xs text-slate-500">Comparisons: {comparisons.length}</div></div>
    </section>
    <section className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-black">3. Runtime Certification</h3><p className="mt-1 text-sm text-slate-600">Phase 10 ACTIVE is semantic governance only. Phase 11 Human certification is required before runtime can materialize a Fast Path Plan.</p><div className="mt-4 grid gap-3 lg:grid-cols-2">{activePatterns.map(p=>{const latest=certs.find(c=>c.patternId===p.patternId);return <div key={p.patternId} className="rounded-2xl border p-4"><div className="font-black">{p.patternId}</div><div className="text-xs text-slate-500">Pattern ACTIVE v{p.version}</div><div className="mt-2 text-sm">Runtime: {latest?.status||'NOT CERTIFIED'} {latest?`· pattern v${latest.patternVersion}`:''}</div><div className="mt-3 flex gap-2"><button className="rounded-xl bg-emerald-700 px-3 py-2 text-xs font-bold text-white" onClick={()=>run(`cert-${p.patternId}`,()=>coreAdminApi.certifyFastPathRuntime(p.patternId,{targetStatus:'CERTIFIED',reason:'Human runtime certification after SHADOW evidence'}))}>Certify exact version</button>{latest?.status==='CERTIFIED'&&<button className="rounded-xl bg-amber-600 px-3 py-2 text-xs font-bold text-white" onClick={()=>run(`suspend-${p.patternId}`,()=>coreAdminApi.certifyFastPathRuntime(p.patternId,{targetStatus:'SUSPENDED',reason:'Human runtime suspension'}))}>Suspend</button>}</div></div>})}</div></section>
    <section className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-black">4. Runtime decision evidence</h3><p className="mt-1 text-sm text-slate-600">The internal FastPathRuntimePort can materialize a fresh RUNTIME Plan and Phase 8 Run only when policy, Pattern and certification are current. Admin UI cannot force a runtime selection.</p><div className="mt-3 space-y-2">{decisions.slice(0,12).map(d=><div key={d.decisionId} className="rounded-2xl bg-slate-50 p-3 text-sm"><b>{d.result}</b> · {d.taskRef}<div className="text-xs text-slate-500">{d.patternId||'Adaptive fallback'} {d.runId?`· run ${d.runId}`:''}</div></div>)}</div></section>
    <section className="rounded-3xl border border-red-200 bg-red-50 p-5 text-red-950"><h3 className="font-black">Runtime invariant</h3><p className="mt-2 text-sm leading-6">Fast Path may skip repeated Triage and Planner only. It never reuses old WHO MAY → WHO SHOULD → HOW evidence. The materialized Plan creates a fresh Phase 8 RUNTIME run; each READY Step must obtain current authorization, routing and adapter evidence before it can dispatch.</p></section>
  </div>;
}
