'use client';

import { useEffect, useMemo, useState } from 'react';
import { coreAdminApi } from '@/lib/api/coreAdminApi';
import type { CoreEnterpriseCaseRecord, CoreExecutionOutcomeEvidence, CoreLearningPolicy, CoreRoutingPattern, CoreRoutingPatternCandidate } from '@/lib/types/core';

const pct=(n?:number)=>n==null?'—':`${(n*100).toFixed(1)}%`;
export function LearningFastPathConsole(){
  const [policies,setPolicies]=useState<CoreLearningPolicy[]>([]); const [cases,setCases]=useState<CoreEnterpriseCaseRecord[]>([]); const [outcomes,setOutcomes]=useState<CoreExecutionOutcomeEvidence[]>([]); const [candidates,setCandidates]=useState<CoreRoutingPatternCandidate[]>([]); const [patterns,setPatterns]=useState<CoreRoutingPattern[]>([]); const [busy,setBusy]=useState(''); const [message,setMessage]=useState('');
  const [policyId,setPolicyId]=useState('default-learning'); const [caseId,setCaseId]=useState(''); const [selectedCandidate,setSelectedCandidate]=useState(''); const [selectedPattern,setSelectedPattern]=useState('');
  const active=useMemo(()=>policies.find(x=>x.status==='ACTIVE'),[policies]);
  async function load(){const [p,c,o,rc,rp]=await Promise.all([coreAdminApi.getLearningPolicies(undefined,'',100),coreAdminApi.getEnterpriseCases(undefined,'',undefined,100),coreAdminApi.getLearningOutcomes(undefined,'',100),coreAdminApi.getRoutingPatternCandidates(undefined,'',100),coreAdminApi.getRoutingPatterns(undefined,'',100)]);setPolicies(p);setCases(c);setOutcomes(o);setCandidates(rc);setPatterns(rp);}
  useEffect(()=>{load().catch(e=>setMessage(String(e)));},[]);
  async function run(key:string,fn:()=>Promise<unknown>){setBusy(key);setMessage('');try{await fn();await load();setMessage('Saved. Review the evidence below.');}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy('');}}
  const resolvedCases=cases.filter(c=>['RESOLVED','CLOSED'].includes(c.status));
  return <div className="space-y-5">
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-black uppercase tracking-wide text-emerald-700">Phase 10 · Outcome Evidence / Learning Fast Path / Drift Governance</div><h2 className="mt-1 text-xl font-black">Experience may propose a Fast Path; it never rewrites routing authority</h2><p className="mt-2 text-sm leading-6 text-slate-600">Only human-accountable RESOLVED/CLOSED Cases enter learning. Pattern lifecycle is <b>OBSERVING → CANDIDATE → SHADOW → ACTIVE</b>. Promotion requires Human Governance. Drift may automatically degrade an ACTIVE pattern, but never promote one. An ACTIVE match selects only a semantic Plan template; every Step still traverses <b>WHO MAY → WHO SHOULD → HOW</b>.</p></section>
    {message&&<div className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700">{message}</div>}
    <section className="grid gap-4 xl:grid-cols-2">
      <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">1. Learning Policy</h3><p className="mt-1 text-sm text-slate-600">Thresholds are Tenant policy, never hard-coded enterprise assumptions.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><input className="rounded-xl border p-2 text-sm" value={policyId} onChange={e=>setPolicyId(e.target.value)} placeholder="Policy ID"/><button className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={!!busy} onClick={()=>run('policy',()=>coreAdminApi.upsertLearningPolicy(policyId,{policyId,displayName:'Default Learning Policy',minCandidateSamples:3,minCandidateSuccessRate:.9,minCandidateHumanAcceptanceRate:.9,minShadowSamples:3,minActiveSuccessRate:.9,minActiveHumanAcceptanceRate:.9,driftWindowSize:20,requireHumanApprovalForPromotion:true,status:'ACTIVE'},'',active?'Update Phase 10 learning thresholds':'Initial Phase 10 learning policy'))}>{busy==='policy'?'Saving…':active?'Update active policy':'Create active policy'}</button></div>{active&&<div className="mt-4 rounded-2xl bg-emerald-50 p-3 text-sm"><b>{active.displayName}</b><div>Candidate: {active.minCandidateSamples} samples · {pct(active.minCandidateSuccessRate)} success · {pct(active.minCandidateHumanAcceptanceRate)} human acceptance</div><div>Activation: {active.minShadowSamples} shadow samples · {pct(active.minActiveSuccessRate)} success</div></div>}</div>
      <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">2. Record accepted Case outcome</h3><p className="mt-1 text-sm text-slate-600">Token/cost are never invented. If no authoritative source exists they remain empty.</p><select className="mt-4 w-full rounded-xl border p-2 text-sm" value={caseId} onChange={e=>setCaseId(e.target.value)}><option value="">Choose RESOLVED/CLOSED Case</option>{resolvedCases.map(c=><option key={c.caseId} value={c.caseId}>{c.caseId} · {c.classification||'unclassified'} · {c.status}</option>)}</select><button className="mt-2 rounded-xl bg-blue-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={!caseId||!!busy} onClick={()=>run('outcome',()=>coreAdminApi.recordLearningOutcome(caseId))}>{busy==='outcome'?'Recording…':'Record outcome evidence'}</button><div className="mt-4 text-xs text-slate-500">Recorded outcomes: {outcomes.length}</div></div>
    </section>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">3. Routing Pattern Candidates</h3><p className="mt-1 text-sm text-slate-600">Candidates contain only problem signature + Canonical Capability Plan. No Provider, Agent, Pool, A2A, MCP, endpoint or credential is learned.</p><div className="mt-4 grid gap-3 lg:grid-cols-2">{candidates.map(c=><button key={c.candidateId} onClick={()=>setSelectedCandidate(c.candidateId)} className={`rounded-2xl border p-4 text-left ${selectedCandidate===c.candidateId?'border-blue-500 bg-blue-50':'border-slate-200'}`}><div className="font-black">{c.classification||'Unclassified'}</div><div className="mt-1 text-xs text-slate-500">{c.candidateId} · {c.status}</div><div className="mt-2 text-sm">Samples {c.sampleCount} · Success {pct(c.successRate)} · Human {pct(c.humanAcceptanceRate)}</div><div className="mt-2 text-xs text-slate-500">{(c.capabilityKeys||[]).join(', ')}</div></button>)}</div><button className="mt-3 rounded-xl bg-violet-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={!selectedCandidate||!!busy} onClick={()=>run('shadow',()=>coreAdminApi.promoteRoutingCandidateToShadow(selectedCandidate,'Human governance: validate candidate in SHADOW before activation'))}>{busy==='shadow'?'Promoting…':'Promote selected candidate to SHADOW'}</button></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">4. Governed Patterns & Drift</h3><div className="mt-4 grid gap-3 lg:grid-cols-2">{patterns.map(p=><button key={p.patternId} onClick={()=>setSelectedPattern(p.patternId)} className={`rounded-2xl border p-4 text-left ${selectedPattern===p.patternId?'border-emerald-500 bg-emerald-50':'border-slate-200'}`}><div className="font-black">{p.classification||'Semantic pattern'}</div><div className="mt-1 text-xs text-slate-500">{p.patternId} · {p.status} · v{p.version}</div><div className="mt-2 text-xs text-slate-500">{(p.capabilityKeys||[]).join(', ')}</div></button>)}</div><div className="mt-3 flex flex-wrap gap-2"><button className="rounded-xl border px-4 py-2 text-sm font-bold disabled:opacity-50" disabled={!selectedPattern||!!busy} onClick={()=>run('quality',()=>coreAdminApi.refreshRoutingPatternQuality(selectedPattern))}>Refresh quality</button><button className="rounded-xl bg-emerald-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={!selectedPattern||!!busy} onClick={()=>run('active',()=>coreAdminApi.transitionRoutingPattern(selectedPattern,{targetStatus:'ACTIVE',reason:'Human governance: shadow evidence satisfies activation thresholds'}))}>Promote SHADOW → ACTIVE</button><button className="rounded-xl bg-amber-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={!selectedPattern||!!busy} onClick={()=>run('drift',()=>coreAdminApi.evaluateRoutingPatternDrift(selectedPattern))}>Evaluate drift</button><button className="rounded-xl bg-slate-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={!selectedPattern||!!busy} onClick={()=>run('retire',()=>coreAdminApi.transitionRoutingPattern(selectedPattern,{targetStatus:'RETIRED',reason:'Human governance retirement'}))}>Retire</button></div></section>
    <section className="rounded-3xl border border-red-200 bg-red-50 p-5"><h3 className="font-black text-red-950">Runtime boundary</h3><p className="mt-2 text-sm leading-6 text-red-900">This Phase 10 console does <b>not</b> dispatch a Task and does not materialize a Fast Path into legacy routing rules. Fast Path resolution is semantic-template evidence only. Runtime integration must instantiate a fresh Plan revision and re-run current WHO MAY → WHO SHOULD → HOW for every Step. A DEGRADED/RETIRED pattern must fall back to the Adaptive Path.</p></section>
  </div>;
}
