'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
import { coreAdminApi } from '@/lib/api/coreAdminApi';
import { createIdempotencyKey } from '@/lib/utils/uuid';
import type { CoreExecutionPlanDecision,CoreGovernedPlanExecutionStep,CorePlanExecutionArtifact,CorePlanExecutionEvent,CorePlanExecutionPolicy,CorePlanExecutionRun } from '@/lib/types/core';

const EMPTY:CorePlanExecutionPolicy={policyId:'default-plan-execution-policy',displayName:'Default Governed Plan Execution Policy',maxAttemptsPerStep:3,defaultStepTimeoutSeconds:300,maxActiveSteps:8,requireArtifactOnSuccess:true,status:'DRAFT'};
export function PlanExecutionConsole(){
 const [policies,setPolicies]=useState<CorePlanExecutionPolicy[]>([]),[policy,setPolicy]=useState(EMPTY),[decisions,setDecisions]=useState<CoreExecutionPlanDecision[]>([]),[runs,setRuns]=useState<CorePlanExecutionRun[]>([]),[steps,setSteps]=useState<CoreGovernedPlanExecutionStep[]>([]),[artifacts,setArtifacts]=useState<CorePlanExecutionArtifact[]>([]),[events,setEvents]=useState<CorePlanExecutionEvent[]>([]);
 const [decisionId,setDecisionId]=useState(''),[runId,setRunId]=useState(''),[stepId,setStepId]=useState(''),[authId,setAuthId]=useState(''),[routingId,setRoutingId]=useState(''),[adapterId,setAdapterId]=useState(''),[finding,setFinding]=useState('Simulation normalized finding'),[status,setStatus]=useState('');
 const startKeyRef=useRef<string|null>(null),stepSubmitKeysRef=useRef<Record<string,string>>({});
 const selectedDecision=useMemo(()=>decisions.find(d=>d.decisionId===decisionId),[decisions,decisionId]);const active=policies.find(p=>p.status==='ACTIVE');
 async function refresh(){try{const [p,d,r]=await Promise.all([coreAdminApi.getPlanExecutionPolicies(undefined,'',100),coreAdminApi.getExecutionPlanDecisions(undefined,'',200),coreAdminApi.getPlanExecutionRuns(undefined,'',undefined,100)]);setPolicies(p);setDecisions(d.filter(x=>x.result==='PLAN_VALIDATED'&&!!x.planId));setRuns(r);if(!decisionId){const v=d.find(x=>x.result==='PLAN_VALIDATED'&&!!x.planId);if(v)setDecisionId(v.decisionId)}if(!runId&&r[0])setRunId(r[0].runId);setStatus('')}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 async function refreshRun(id=runId){if(!id)return;try{const [s,a,e]=await Promise.all([coreAdminApi.getPlanExecutionSteps(id),coreAdminApi.getPlanExecutionArtifacts(id),coreAdminApi.getPlanExecutionEvents(id)]);setSteps(s);setArtifacts(a);setEvents(e);if(!stepId){const ready=s.find(x=>x.state==='READY'||x.state==='DISPATCH_READY'||x.state==='RUNNING');if(ready)setStepId(ready.stepId)}}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 // Initial policy/decision/run bootstrap intentionally runs once.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void refresh()},[]);
 // refreshRun accepts the authoritative run id; captured step state only initializes selection.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void refreshRun(runId)},[runId]);
 async function savePolicy(){try{const saved=await coreAdminApi.upsertPlanExecutionPolicy(policy.policyId,policy,'',policies.some(p=>p.policyId===policy.policyId)?'Phase 8 policy update':undefined);setPolicy(saved);await refresh();setStatus('Plan Execution Policy saved. It limits runtime behavior but does not select or authorize Providers.')}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 async function start(){if(!selectedDecision?.planId){setStatus('Select a PLAN_VALIDATED decision first.');return}const key=startKeyRef.current??createIdempotencyKey('plan-simulation');startKeyRef.current=key;try{const r=await coreAdminApi.startPlanExecution({planId:selectedDecision.planId,planRevision:selectedDecision.planRevision,planDecisionId:selectedDecision.decisionId,executionMode:'SIMULATION',idempotencyKey:key});startKeyRef.current=null;setRunId(r.runId);await refresh();await refreshRun(r.runId);setStatus('Simulation run started from a frozen Plan revision. No external I/O has occurred.')}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 async function attach(){if(!runId||!stepId)return;try{await coreAdminApi.attachPlanStepAuthority(runId,stepId,{authorizationDecisionId:authId,routingDecisionId:routingId,adapterResolutionId:adapterId});await refreshRun();setStatus('WHO MAY → WHO SHOULD → HOW evidence attached. Step is DISPATCH_READY, not yet executed.')}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 async function submit(){if(!runId||!stepId)return;const logicalStep=`${runId}:${stepId}`;const key=stepSubmitKeysRef.current[logicalStep]??createIdempotencyKey('plan-step-simulation');stepSubmitKeysRef.current[logicalStep]=key;try{await coreAdminApi.submitPlanStep(runId,stepId,{idempotencyKey:key});delete stepSubmitKeysRef.current[logicalStep];await refreshRun();setStatus('Simulation submission recorded. No Netty/A2A/MCP/Internal Service I/O was executed.')}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 async function complete(){if(!runId||!stepId)return;try{await coreAdminApi.completePlanStep(runId,stepId,{result:'SUCCEEDED',finding,confidence:0.95,evidenceRefs:[`simulation://${runId}/${stepId}`],output:{normalized:true},dataClassification:'INTERNAL'});await refreshRun();await refresh();setStatus('Step completed with a normalized Artifact. Newly satisfied dependencies are released to READY.')}catch(e){setStatus(e instanceof Error?e.message:String(e))}}
 return <div className="space-y-5">
  <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-black uppercase tracking-wide text-emerald-700">Phase 8 · Governed Plan Execution / Fan-out / Fan-in</div><h2 className="mt-1 text-xl font-black">Dependency readiness is not execution authority</h2><p className="mt-2 text-sm leading-6 text-slate-600">A frozen Plan revision drives fan-out/fan-in. A Step becomes <b>READY</b> only when dependencies succeeded. Every attempt must still carry current WHO MAY → WHO SHOULD → HOW evidence. Retry clears that authority chain and requires fresh decisions. Fan-in passes normalized Artifact references instead of raw transport payloads.</p></section>
  <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-3xl border bg-white p-5"><h3 className="font-black">Execution Policy</h3><div className="mt-3 grid gap-2 md:grid-cols-2"><input className="rounded-xl border p-2" value={policy.policyId} onChange={e=>setPolicy({...policy,policyId:e.target.value})}/><select className="rounded-xl border p-2" value={policy.status} onChange={e=>setPolicy({...policy,status:e.target.value})}><option>DRAFT</option><option>ACTIVE</option><option>DISABLED</option><option>RETIRED</option></select><label className="text-sm">Max attempts<input type="number" className="mt-1 w-full rounded-xl border p-2" value={policy.maxAttemptsPerStep} onChange={e=>setPolicy({...policy,maxAttemptsPerStep:Number(e.target.value)})}/></label><label className="text-sm">Step timeout seconds<input type="number" className="mt-1 w-full rounded-xl border p-2" value={policy.defaultStepTimeoutSeconds} onChange={e=>setPolicy({...policy,defaultStepTimeoutSeconds:Number(e.target.value)})}/></label><label className="text-sm">Max active Steps<input type="number" className="mt-1 w-full rounded-xl border p-2" value={policy.maxActiveSteps} onChange={e=>setPolicy({...policy,maxActiveSteps:Number(e.target.value)})}/></label></div><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={policy.requireArtifactOnSuccess} onChange={e=>setPolicy({...policy,requireArtifactOnSuccess:e.target.checked})}/> Require normalized Artifact on success</label><button className="mt-3 rounded-xl bg-slate-950 px-4 py-2 text-sm font-black text-white" onClick={()=>void savePolicy()}>Save policy</button><p className="mt-2 text-xs text-slate-500">ACTIVE: {active?`${active.policyId} v${active.version}`:'none — fail closed'}</p></div>
  <div className="rounded-3xl border bg-white p-5"><h3 className="font-black">Start frozen Plan revision</h3><select className="mt-3 w-full rounded-xl border p-2" value={decisionId} onChange={e=>setDecisionId(e.target.value)}><option value="">Select PLAN_VALIDATED evidence…</option>{decisions.map(d=><option key={d.decisionId} value={d.decisionId}>{d.planId} · r{d.planRevision} · {d.decisionId}</option>)}</select><button className="mt-3 rounded-xl bg-emerald-700 px-4 py-2 text-sm font-black text-white" onClick={()=>void start()}>Start simulation run</button><p className="mt-2 text-xs text-slate-500">Simulation validates Phase 8 state/fan-out/fan-in without external adapter I/O. RUNTIME mode requires RUNTIME Phase 3/4/5 evidence plus authoritative Child Task and adapter implementations.</p></div></section>
  <section className="rounded-3xl border bg-white p-5"><h3 className="font-black">Step execution chain</h3><div className="mt-3 grid gap-2 md:grid-cols-2"><select className="rounded-xl border p-2" value={runId} onChange={e=>setRunId(e.target.value)}><option value="">Select run…</option>{runs.map(r=><option key={r.runId} value={r.runId}>{r.runId} · {r.status}</option>)}</select><select className="rounded-xl border p-2" value={stepId} onChange={e=>setStepId(e.target.value)}><option value="">Select Step…</option>{steps.map(s=><option key={s.stepId} value={s.stepId}>{s.stepId} · {s.state}</option>)}</select><input className="rounded-xl border p-2" placeholder="WHO MAY decision ID" value={authId} onChange={e=>setAuthId(e.target.value)}/><input className="rounded-xl border p-2" placeholder="WHO SHOULD decision ID" value={routingId} onChange={e=>setRoutingId(e.target.value)}/><input className="rounded-xl border p-2 md:col-span-2" placeholder="HOW resolution ID" value={adapterId} onChange={e=>setAdapterId(e.target.value)}/></div><div className="mt-3 flex flex-wrap gap-2"><button className="rounded-xl border px-3 py-2 text-sm font-black" onClick={()=>void attach()}>Attach authority</button><button className="rounded-xl border px-3 py-2 text-sm font-black" onClick={()=>void submit()}>Submit simulation</button><button className="rounded-xl border px-3 py-2 text-sm font-black" onClick={()=>void complete()}>Complete + Artifact</button></div><input className="mt-3 w-full rounded-xl border p-2" value={finding} onChange={e=>setFinding(e.target.value)}/><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-4">{steps.map(s=><div key={s.stepId} className="rounded-2xl bg-slate-50 p-3"><div className="font-black">{s.stepId}</div><div className="text-xs text-slate-500">{s.requiredCapability.capabilityCode} · {s.state}</div><div className="mt-1 text-xs">depends: {s.dependsOn?.join(', ')||'none'}</div></div>)}</div></section>
  <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-3xl border bg-white p-5"><h3 className="font-black">Normalized Artifacts</h3><pre className="mt-3 max-h-80 overflow-auto rounded-2xl bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(artifacts,null,2)}</pre></div><div className="rounded-3xl border bg-white p-5"><h3 className="font-black">Execution Events</h3><pre className="mt-3 max-h-80 overflow-auto rounded-2xl bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(events,null,2)}</pre></div></section>
  {status?<div className="rounded-2xl border bg-slate-50 p-3 text-sm">{status}</div>:null}
 </div>
}
