'use client';
import { useEffect, useMemo, useState } from 'react';
import { coreAdminApi } from '@/lib/api/coreAdminApi';
import type { CoreRoutingProfile, CoreRuntimeStepAuthorityDecision, CoreRuntimeStepAuthorityPolicy } from '@/lib/types/core';

const splitMap=(text:string)=>Object.fromEntries(text.split(/[,\n]+/).map(x=>x.trim()).filter(Boolean).map(x=>{const [k,...r]=x.split('=');return [k?.trim(),r.join('=').trim()||'READ'];}));
export function RuntimeStepAuthorityConsole(){
  const [policies,setPolicies]=useState<CoreRuntimeStepAuthorityPolicy[]>([]); const [profiles,setProfiles]=useState<CoreRoutingProfile[]>([]); const [decisions,setDecisions]=useState<CoreRuntimeStepAuthorityDecision[]>([]); const [message,setMessage]=useState(''); const [busy,setBusy]=useState('');
  const [policyId,setPolicyId]=useState('default-runtime-step-authority'); const [displayName,setDisplayName]=useState('Default Runtime Step Authority'); const [routingProfileId,setRoutingProfileId]=useState(''); const [defaultAccessMode,setDefaultAccessMode]=useState('READ'); const [operationMap,setOperationMap]=useState('READ=READ\nWRITE=WRITE\nEXECUTE=EXECUTE'); const [maxCandidates,setMaxCandidates]=useState(1000); const [automatic,setAutomatic]=useState(true); const [runId,setRunId]=useState(''); const [stepId,setStepId]=useState('');
  const active=useMemo(()=>policies.find(p=>p.status==='ACTIVE'),[policies]);
  async function load(){const [p,r,d]=await Promise.all([coreAdminApi.getRuntimeStepAuthorityPolicies(undefined,'',100),coreAdminApi.getProviderRoutingProfiles('ACTIVE','','',undefined,100),coreAdminApi.getRuntimeStepAuthorityDecisions(undefined,undefined,'',200)]);setPolicies(p);setProfiles(r);setDecisions(d);if(!routingProfileId&&r[0])setRoutingProfileId(r[0].profileId);}
  useEffect(()=>{load().catch(e=>setMessage(String(e)));},[]); // eslint-disable-line react-hooks/exhaustive-deps
  async function run(key:string,fn:()=>Promise<unknown>){setBusy(key);setMessage('');try{await fn();await load();setMessage('Saved. Review append-only runtime authority evidence below.');}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy('');}}
  return <div className="space-y-5">
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-black uppercase tracking-wide text-indigo-700">Phase 12 · Runtime Step Authority Automation</div><h2 className="mt-1 text-xl font-black">READY → WHO CAN → WHO MAY → WHO SHOULD → HOW → DISPATCH_READY</h2><p className="mt-2 text-sm leading-6 text-slate-600">Provider discovery, current requester resolution, authorization, routing and HOW resolution are server-side. No Provider, Agent, Pool, Domain or transport selector is accepted here. Every retry clears old authority evidence and rebuilds a fresh chain.</p></section>
    {message&&<div className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm">{message}</div>}
    <section className="grid gap-4 xl:grid-cols-2">
      <div className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-black">1. Runtime authority policy</h3><p className="mt-1 text-sm text-slate-600">This chooses a Routing Profile and maps semantic operations to access modes. It never selects a Provider.</p><div className="mt-3 grid gap-2"><input className="rounded-xl border p-2 text-sm" value={policyId} onChange={e=>setPolicyId(e.target.value)} placeholder="Policy ID"/><input className="rounded-xl border p-2 text-sm" value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Display name"/><select className="rounded-xl border p-2 text-sm" value={routingProfileId} onChange={e=>setRoutingProfileId(e.target.value)}><option value="">Choose ACTIVE Routing Profile</option>{profiles.map(p=><option key={p.profileId} value={p.profileId}>{p.displayName} · {p.profileId}</option>)}</select><select className="rounded-xl border p-2 text-sm" value={defaultAccessMode} onChange={e=>setDefaultAccessMode(e.target.value)}><option>READ</option><option>WRITE</option><option>EXECUTE</option></select><textarea className="min-h-24 rounded-xl border p-2 font-mono text-xs" value={operationMap} onChange={e=>setOperationMap(e.target.value)} placeholder="operation=READ"/><label className="text-xs font-bold text-slate-600">Maximum WHO CAN candidates<input type="number" min={1} max={5000} className="mt-1 w-full rounded-xl border p-2 text-sm" value={maxCandidates} onChange={e=>setMaxCandidates(Number(e.target.value)||1)}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={automatic} onChange={e=>setAutomatic(e.target.checked)}/> Automatically attach fresh authority when a RUNTIME Step becomes READY</label></div><button className="mt-3 rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={!routingProfileId||!!busy} onClick={()=>run('policy',()=>coreAdminApi.upsertRuntimeStepAuthorityPolicy(policyId,{policyId,displayName,routingProfileId,defaultAccessMode,operationAccessModes:splitMap(operationMap),maxCandidateBindings:maxCandidates,automaticAttachmentEnabled:automatic,status:'ACTIVE'},'',active?'Update Phase 12 runtime authority policy':'Initial Phase 12 runtime authority policy'))}>{active?'Update active policy':'Create active policy'}</button>{active&&<div className="mt-3 rounded-2xl bg-emerald-50 p-3 text-sm text-emerald-950"><b>{active.displayName}</b><div>Routing profile: {active.routingProfileId} · Max candidates: {active.maxCandidateBindings} · Auto attach: {String(active.automaticAttachmentEnabled)}</div></div>}</div>
      <div className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-black">2. Reconcile one READY runtime Step</h3><p className="mt-1 text-sm text-slate-600">This is an operational reconcile trigger. It accepts only Run + Step identity. Provider/Agent/Pool/transport remain server-side decisions.</p><input className="mt-3 w-full rounded-xl border p-2 text-sm" value={runId} onChange={e=>setRunId(e.target.value)} placeholder="RUNTIME run ID"/><input className="mt-2 w-full rounded-xl border p-2 text-sm" value={stepId} onChange={e=>setStepId(e.target.value)} placeholder="READY step ID"/><button className="mt-2 rounded-xl bg-indigo-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={!runId||!stepId||!!busy} onClick={()=>run('reconcile',()=>coreAdminApi.automatePlanExecutionStepAuthority(runId,stepId))}>Rebuild authority chain</button><div className="mt-4 rounded-2xl bg-amber-50 p-3 text-sm text-amber-950"><b>Requester authority</b><p className="mt-1">Task origin is only a lookup key. Current principal status, Department/Group and RBAC roles are re-resolved by Core. Approval count is never supplied by this UI.</p></div></div>
    </section>
    <section className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-black">3. Append-only authority evidence</h3><p className="mt-1 text-sm text-slate-600">WAITING_APPROVAL stays READY. AUTHORIZED carries a fresh Phase 3/4/5 chain and may become DISPATCH_READY only after existing Phase 8 freshness validation passes.</p><div className="mt-3 space-y-2">{decisions.slice(0,30).map(d=><div key={d.decisionId} className="rounded-2xl bg-slate-50 p-3 text-sm"><div className="flex flex-wrap items-center gap-2"><b>{d.result}</b><span>{d.runId} / {d.stepId}</span><span className="text-xs text-slate-500">generation {d.attemptGeneration}</span></div><div className="mt-1 text-xs text-slate-500">{d.capabilityCode}#{d.operation} · candidates {d.candidateCount} · PASS {d.passCount} · waiting {d.waitingApprovalCount}</div><div className="mt-1 text-xs text-slate-500">{(d.reasonCodes||[]).join(' · ')||'No reason codes'}</div></div>)}</div></section>
    <section className="rounded-3xl border border-red-200 bg-red-50 p-5 text-red-950"><h3 className="font-black">Runtime invariant</h3><p className="mt-2 text-sm leading-6">WHO CAN discovers current REGISTERED + APPROVED providers. WHO MAY is a hard authorization gate. WHO SHOULD ranks only PASS candidates. HOW resolves only the selected Binding. The authority chain is rebuilt for every Step and every Retry; no legacy Source → Target topology is used.</p></section>
  </div>;
}
