'use client';

import { useCallback, useEffect, useState } from 'react';
import { accessManagementApi } from '@/lib/api/accessManagementApi';
import { formatIamError } from '@/lib/iam/errorPresentation';
import type { HumanReadableAudit } from '@/lib/iam/types';
import { HumanStatus, SelectField } from '../shared/beginnerUi';
import { WorkspaceEmpty, WorkspaceError, WorkspaceLoading } from '../shared/workspaceUi';

export function HumanReadableAuditFeed({ tenantId }: Readonly<{ tenantId: string }>) {
  const [items, setItems] = useState<HumanReadableAudit[]>([]); const [category, setCategory] = useState(''); const [outcome, setOutcome] = useState(''); const [nextCursor, setNextCursor] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async (append = false, requestedCursor = '') => { setLoading(true); setError(''); try { const page = await accessManagementApi.humanReadableAudit(tenantId, 50, requestedCursor, category, outcome); setItems((current) => append ? [...current, ...page.items] : page.items); setNextCursor(page.nextCursor); } catch (cause) { setError(formatIamError(cause, 'Unable to load the audit activity.')); } finally { setLoading(false); } }, [category, outcome, tenantId]);
  useEffect(() => { void load(false, ''); }, [load]);
  return <div className="space-y-5"><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-2"><div><label htmlFor="audit-category" className="mb-1.5 block text-sm font-black">Activity category</label><SelectField id="audit-category" value={category} onChange={setCategory} placeholder="All categories" options={[{value:'ACCESS',label:'Access'},{value:'IDENTITY',label:'Identity'},{value:'SECURITY',label:'Security'},{value:'CREDENTIAL',label:'Credentials'},{value:'POLICY',label:'Policy'}]} /></div><div><label htmlFor="audit-outcome" className="mb-1.5 block text-sm font-black">Outcome</label><SelectField id="audit-outcome" value={outcome} onChange={setOutcome} placeholder="All outcomes" options={[{value:'SUCCESS',label:'Succeeded'},{value:'DENIED',label:'Denied'},{value:'FAILED',label:'Failed'}]} /></div></div></section>
    {error ? <WorkspaceError message={error} onRetry={() => { void load(false); }} /> : null}{loading && !items.length ? <WorkspaceLoading title="Loading audit activity" /> : null}{!loading && !items.length ? <WorkspaceEmpty title="No audit activity" description="No human-readable event matches the selected filters." /> : null}
    <div className="space-y-3">{items.map((item) => <article key={item.eventId} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wide text-blue-700">{humanize(item.category)} · {humanize(item.action)}</p><h3 className="mt-1 text-base font-black text-slate-950">{item.summary}</h3></div><HumanStatus value={item.outcome} /></div><dl className="mt-4 grid gap-2 text-sm text-slate-600 md:grid-cols-3"><div><dt className="text-xs font-black text-slate-500">Actor</dt><dd>{item.actorName || item.actorId}</dd></div><div><dt className="text-xs font-black text-slate-500">Target</dt><dd>{item.targetName || item.targetId}</dd></div><div><dt className="text-xs font-black text-slate-500">When</dt><dd>{formatDate(item.occurredAt)}</dd></div></dl>{item.reason ? <p className="mt-3 rounded-2xl bg-slate-50 p-3 text-sm text-slate-700"><b>Business reason:</b> {item.reason}</p> : null}<details className="mt-3 rounded-2xl border border-slate-200 bg-slate-50 p-3 text-xs text-slate-600"><summary className="cursor-pointer font-black">Immutable technical evidence</summary><dl className="mt-2 grid gap-1"><div><dt className="inline font-black">Event ID: </dt><dd className="inline break-all">{item.eventId}</dd></div><div><dt className="inline font-black">Correlation ID: </dt><dd className="inline break-all">{item.correlationId || 'Not recorded'}</dd></div><div><dt className="inline font-black">Evidence: </dt><dd className="mt-1 whitespace-pre-wrap break-all font-mono">{item.technicalEvidence || 'No additional evidence payload.'}</dd></div></dl></details></article>)}</div>
    {nextCursor ? <button type="button" disabled={loading} onClick={() => { void load(true, nextCursor); }} className="w-full rounded-xl border border-slate-300 px-4 py-3 text-sm font-black disabled:opacity-50">Load more activity</button> : null}
  </div>;
}
function humanize(value: string) { return value.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,(c)=>c.toUpperCase()); }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleString(); }
