'use client';

import { useCallback, useEffect, useMemo, useState, type Dispatch, type SetStateAction } from 'react';
import { accessManagementApi } from '@/lib/api/accessManagementApi';
import { formatIamError } from '@/lib/iam/errorPresentation';
import type { SecurityPolicies, SecurityPolicyRevision } from '@/lib/iam/types';
import { AuditReasonSelector, FieldLabel, HumanStatus, SelectField, isAuditReasonValid } from '../shared/beginnerUi';
import { WorkspaceEmpty, WorkspaceError, WorkspaceLoading, WorkspaceModal } from '../shared/workspaceUi';

type Kind = 'password' | 'mfa' | 'session' | 'token';
type FormState = Record<string, string | boolean>;
const KINDS: Array<{ value: Kind; label: string; description: string }> = [
  { value: 'password', label: 'Password', description: 'Length, history and lockout rules.' },
  { value: 'mfa', label: 'MFA', description: 'Administrator and recovery requirements.' },
  { value: 'session', label: 'Sessions', description: 'Idle, absolute and reauthentication limits.' },
  { value: 'token', label: 'Tokens', description: 'Maximum TTL and service credential safeguards.' },
];

export function SecurityPolicyForms({ tenantId, canManage, onChanged }: Readonly<{ tenantId: string; canManage: boolean; onChanged: () => void }>) {
  const [policies, setPolicies] = useState<SecurityPolicies | null>(null); const [kind, setKind] = useState<Kind>('password'); const [form, setForm] = useState<FormState>({});
  const [revisions, setRevisions] = useState<SecurityPolicyRevision[]>([]); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [reason, setReason] = useState(''); const [restoreRevision, setRestoreRevision] = useState<SecurityPolicyRevision | null>(null);
  const currentMap = useMemo(() => policies ? policyMap(policies, kind) : {}, [kind, policies]);
  const currentVersion = numberValue(currentMap.version, policies?.version ?? 0);

  const load = useCallback(async () => { setLoading(true); setError(''); try { const [policySet, history] = await Promise.all([accessManagementApi.securityPolicies(), accessManagementApi.securityPolicyRevisions(tenantId, kind, 50)]); setPolicies(policySet); setForm(toForm(kind, policyMap(policySet, kind))); setRevisions(history.items); } catch (cause) { setError(formatIamError(cause, 'Unable to load Tenant security policy.')); } finally { setLoading(false); } }, [kind, tenantId]);
  useEffect(() => { void load(); }, [load]);

  const changes = useMemo(() => diff(kind, currentMap, form), [currentMap, form, kind]);
  async function save() { if (!policies || !isAuditReasonValid(reason, 'HIGH_RISK') || !changes.length) return; setSaving(true); setError(''); setNotice(''); try { const updated = await accessManagementApi.updateSecurityPolicy(kind, toRequest(kind, form), currentVersion, reason); setPolicies(updated); setForm(toForm(kind, policyMap(updated, kind))); setNotice(`${label(kind)} policy updated. Previous values were archived as an immutable revision.`); onChanged(); const history = await accessManagementApi.securityPolicyRevisions(tenantId, kind, 50); setRevisions(history.items); } catch (cause) { setError(formatIamError(cause, 'Security Policy update failed.')); } finally { setSaving(false); } }
  async function restore() { if (!restoreRevision || !policies || !isAuditReasonValid(reason, 'HIGH_RISK')) return; setSaving(true); setError(''); setNotice(''); try { const updated = await accessManagementApi.restoreSecurityPolicy(kind, restoreRevision.revisionId, currentVersion, reason); setPolicies(updated); setForm(toForm(kind, policyMap(updated, kind))); setRestoreRevision(null); setNotice(`${label(kind)} policy restored from the selected revision.`); onChanged(); const history = await accessManagementApi.securityPolicyRevisions(tenantId, kind, 50); setRevisions(history.items); } catch (cause) { setError(formatIamError(cause, 'The Security Policy revision could not be restored.')); } finally { setSaving(false); } }

  return <div className="space-y-5">
    <nav aria-label="Security policy sections" className="grid gap-2 rounded-3xl border border-slate-200 bg-white p-2 shadow-sm md:grid-cols-4">{KINDS.map((item) => <button key={item.value} type="button" onClick={() => { setKind(item.value); setNotice(''); setReason(''); }} className={`rounded-2xl p-3 text-left ${kind === item.value ? 'bg-slate-950 text-white' : 'hover:bg-slate-50'}`}><span className="block text-sm font-black">{item.label}</span><span className={`mt-1 block text-xs leading-5 ${kind === item.value ? 'text-slate-300' : 'text-slate-500'}`}>{item.description}</span></button>)}</nav>
    {error ? <WorkspaceError message={error} onRetry={() => { void load(); }} /> : null}{notice ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-900">{notice}</div> : null}{loading && !policies ? <WorkspaceLoading title="Loading Security Policy" /> : null}
    {policies ? <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-blue-700">{label(kind)} policy</p><h2 className="mt-1 text-xl font-black text-slate-950">Governed security settings</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Use validated controls rather than editing policy JSON. Saving creates an immutable prior revision and increments the Tenant security epoch.</p></div><HumanStatus value="ACTIVE" /></div>
      <div className="mt-5">{kind === 'password' ? <PasswordFields form={form} setForm={setForm} /> : null}{kind === 'mfa' ? <MfaFields form={form} setForm={setForm} /> : null}{kind === 'session' ? <SessionFields form={form} setForm={setForm} /> : null}{kind === 'token' ? <TokenFields form={form} setForm={setForm} /> : null}</div>
      <div className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Change preview</p>{changes.length ? <ul className="mt-2 space-y-1 text-sm text-slate-700">{changes.map((change) => <li key={change}>• {change}</li>)}</ul> : <p className="mt-2 text-sm text-slate-600">No change from the current effective policy.</p>}</div>
      {canManage ? <div className="mt-5 space-y-4"><AuditReasonSelector idPrefix={`policy-${kind}`} value={reason} onChange={setReason} tier="HIGH_RISK" /><div className="flex justify-end"><button type="button" disabled={saving || !changes.length || !isAuditReasonValid(reason, 'HIGH_RISK')} onClick={() => { void save(); }} className="rounded-xl bg-blue-700 px-5 py-2.5 text-sm font-black text-white disabled:bg-slate-300">Save policy</button></div></div> : null}
    </section> : null}
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black text-slate-950">Revision history</h2><p className="mt-1 text-sm text-slate-600">Each successful update archives the previous effective values. Restore is version-checked and audited.</p>{!revisions.length ? <div className="mt-4"><WorkspaceEmpty title="No archived revisions" description="The first policy update will archive the current values here." /></div> : <div className="mt-4 space-y-2">{revisions.map((revision) => <div key={revision.revisionId} className="flex flex-col gap-3 rounded-2xl border border-slate-200 p-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-black text-slate-950">Version {revision.policyVersion}</p><p className="mt-1 text-sm text-slate-600">{revision.auditReason || 'No business reason recorded'} · {formatDate(revision.createdAt)}</p><p className="mt-1 text-xs text-slate-500">Archived by {revision.actorId}</p></div>{canManage ? <button type="button" onClick={() => { setRestoreRevision(revision); setReason(''); }} className="rounded-xl border border-blue-300 px-4 py-2 text-sm font-black text-blue-700">Review restore</button> : null}</div>)}</div>}</section>
    <WorkspaceModal open={Boolean(restoreRevision)} title={`Restore ${label(kind)} policy`} description="The current values will be archived before the selected revision becomes effective." onClose={() => setRestoreRevision(null)}><div className="space-y-4"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><p className="font-black">Revision version {restoreRevision?.policyVersion}</p><p className="mt-1">Archived {formatDate(restoreRevision?.createdAt ?? '')}</p><p className="mt-1">Original reason: {restoreRevision?.auditReason || 'Not recorded'}</p></div><RevisionPreview revision={restoreRevision} /><AuditReasonSelector idPrefix={`restore-${kind}`} value={reason} onChange={setReason} tier="HIGH_RISK" /><div className="flex justify-end gap-2"><button type="button" onClick={() => setRestoreRevision(null)} className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-black">Cancel</button><button type="button" disabled={saving || !isAuditReasonValid(reason, 'HIGH_RISK')} onClick={() => { void restore(); }} className="rounded-xl bg-amber-700 px-4 py-2 text-sm font-black text-white disabled:bg-slate-300">Restore revision</button></div></div></WorkspaceModal>
  </div>;
}

function PasswordFields({ form, setForm }: FieldsProps) { return <div className="grid gap-4 md:grid-cols-2"><Choice id="password-length" label="Minimum password length" value={String(form.minimumLength ?? '14')} set={(v)=>patch(setForm,'minimumLength',v)} options={['14','16','18','20','24']} /><Choice id="password-history" label="Password history" value={String(form.historyCount ?? '12')} set={(v)=>patch(setForm,'historyCount',v)} options={['0','5','10','12','24']} suffix=" previous passwords" /><Choice id="password-failures" label="Failed attempts before lockout" value={String(form.failedAttemptThreshold ?? '5')} set={(v)=>patch(setForm,'failedAttemptThreshold',v)} options={['3','5','7','10']} /><Choice id="password-lockout" label="Lockout duration" value={String(form.lockoutMinutes ?? '15')} set={(v)=>patch(setForm,'lockoutMinutes',v)} options={['5','15','30','60']} suffix=" minutes" /></div>; }
function MfaFields({ form, setForm }: FieldsProps) { return <div className="grid gap-3"><Toggle id="mfa-admin" label="Require MFA for administrators" help="Applies to privileged Tenant administration responsibilities." checked={Boolean(form.requiredForAdministrators)} set={(v)=>patch(setForm,'requiredForAdministrators',v)} /><Toggle id="mfa-totp" label="Allow authenticator applications (TOTP)" help="Supports Google Authenticator, Microsoft Authenticator and compatible applications." checked={Boolean(form.allowTotp)} set={(v)=>patch(setForm,'allowTotp',v)} /><Toggle id="mfa-recovery" label="Allow one-time recovery codes" help="Users must store recovery codes in an approved secure location." checked={Boolean(form.allowRecoveryCodes)} set={(v)=>patch(setForm,'allowRecoveryCodes',v)} /></div>; }
function SessionFields({ form, setForm }: FieldsProps) { return <div className="grid gap-4 md:grid-cols-2"><Choice id="session-idle" label="Idle timeout" value={String(form.idleTimeoutMinutes ?? '30')} set={(v)=>patch(setForm,'idleTimeoutMinutes',v)} options={['15','30','60','120']} suffix=" minutes" /><Choice id="session-absolute" label="Maximum session duration" value={String(form.absoluteTimeoutMinutes ?? '480')} set={(v)=>patch(setForm,'absoluteTimeoutMinutes',v)} options={['240','480','720','1440']} suffix=" minutes" /><Choice id="session-count" label="Maximum concurrent sessions" value={String(form.maxConcurrentSessions ?? '5')} set={(v)=>patch(setForm,'maxConcurrentSessions',v)} options={['1','3','5','10']} /><Choice id="session-reauth" label="Reauthentication interval" value={String(form.reauthenticationMinutes ?? '60')} set={(v)=>patch(setForm,'reauthenticationMinutes',v)} options={['15','30','60','120']} suffix=" minutes" /><Toggle id="session-password" label="Revoke sessions after password change" checked={Boolean(form.revokeOnPasswordChange)} set={(v)=>patch(setForm,'revokeOnPasswordChange',v)} /><Toggle id="session-mfa" label="Revoke sessions after MFA reset" checked={Boolean(form.revokeOnMfaReset)} set={(v)=>patch(setForm,'revokeOnMfaReset',v)} /></div>; }
function TokenFields({ form, setForm }: FieldsProps) { return <div className="grid gap-4 md:grid-cols-2"><Choice id="token-personal" label="Personal token maximum TTL" value={String(form.personalTokenMaxTtlDays ?? '30')} set={(v)=>patch(setForm,'personalTokenMaxTtlDays',v)} options={['1','7','30','60','90']} suffix=" days" /><Choice id="token-service" label="Service token maximum TTL" value={String(form.serviceTokenMaxTtlDays ?? '30')} set={(v)=>patch(setForm,'serviceTokenMaxTtlDays',v)} options={['1','7','30','60','90']} suffix=" days" /><Choice id="token-active" label="Maximum active tokens" value={String(form.maxActiveTokens ?? '3')} set={(v)=>patch(setForm,'maxActiveTokens',v)} options={['1','2','3','5','10']} /><Toggle id="token-cidr" label="Require a network boundary for Service Accounts" help="A Service Account cannot issue a token without an approved CIDR profile." checked={Boolean(form.requireServiceAccountCidr)} set={(v)=>patch(setForm,'requireServiceAccountCidr',v)} /></div>; }

type FieldsProps = { form: FormState; setForm: Dispatch<SetStateAction<FormState>> };
function Choice({ id, label: fieldLabel, value, set, options, suffix = '' }: Readonly<{ id:string; label:string; value:string; set:(value:string)=>void; options:string[]; suffix?:string }>) { return <FieldLabel htmlFor={id} label={fieldLabel}><SelectField id={id} value={value} onChange={set} required options={options.map((item)=>({value:item,label:`${item}${suffix}`}))} /></FieldLabel>; }
function Toggle({ id, label: fieldLabel, help, checked, set }: Readonly<{id:string;label:string;help?:string;checked:boolean;set:(value:boolean)=>void}>) { return <label htmlFor={id} className="flex cursor-pointer gap-3 rounded-2xl border border-slate-200 p-4"><input id={id} type="checkbox" checked={checked} onChange={(event)=>set(event.target.checked)} className="mt-1 size-4 rounded" /><span><span className="block text-sm font-black text-slate-950">{fieldLabel}</span>{help ? <span className="mt-1 block text-xs leading-5 text-slate-500">{help}</span> : null}</span></label>; }
function patch(setForm: Dispatch<SetStateAction<FormState>>, key:string, value:string|boolean) { setForm((current)=>({...current,[key]:value})); }
function policyMap(policies: SecurityPolicies, kind: Kind): Record<string, unknown> { return policies[kind] ?? {}; }
function numberValue(value: unknown, fallback: number) { if (typeof value === 'number') return value; const parsed = Number(value); return Number.isFinite(parsed) ? parsed : fallback; }
function boolValue(value: unknown, fallback: boolean) { return typeof value === 'boolean' ? value : fallback; }
function toForm(kind:Kind,map:Record<string,unknown>):FormState { if(kind==='password') return {minimumLength:String(numberValue(map.minimumLength,14)),historyCount:String(numberValue(map.historyCount,12)),failedAttemptThreshold:String(numberValue(map.failedAttemptThreshold,5)),lockoutMinutes:String(Math.max(1,Math.round(numberValue(map.lockoutSeconds,900)/60)))}; if(kind==='mfa') return {requiredForAdministrators:boolValue(map.requiredForAdministrators,true),allowRecoveryCodes:boolValue(map.allowRecoveryCodes,true),allowTotp:boolValue(map.allowTotp,true)}; if(kind==='session') return {idleTimeoutMinutes:String(Math.max(1,Math.round(numberValue(map.idleTimeoutSeconds,1800)/60))),absoluteTimeoutMinutes:String(Math.max(2,Math.round(numberValue(map.absoluteTimeoutSeconds,28800)/60))),maxConcurrentSessions:String(numberValue(map.maxConcurrentSessions,5)),revokeOnPasswordChange:boolValue(map.revokeOnPasswordChange,true),revokeOnMfaReset:boolValue(map.revokeOnMfaReset,true),reauthenticationMinutes:String(Math.max(1,Math.round(numberValue(map.reauthenticationSeconds,3600)/60)))}; return {personalTokenMaxTtlDays:String(Math.max(1,Math.round(numberValue(map.personalMaxTtlSeconds,2592000)/86400))),serviceTokenMaxTtlDays:String(Math.max(1,Math.round(numberValue(map.serviceMaxTtlSeconds,2592000)/86400))),maxActiveTokens:String(numberValue(map.maxActiveTokens,3)),requireServiceAccountCidr:boolValue(map.requireServiceCidr,true)}; }
function toRequest(kind:Kind,form:FormState):Record<string,unknown>{ if(kind==='password') return {minimumLength:Number(form.minimumLength),historyCount:Number(form.historyCount),failedAttemptThreshold:Number(form.failedAttemptThreshold),lockoutMinutes:Number(form.lockoutMinutes)}; if(kind==='mfa') return {requiredForAdministrators:Boolean(form.requiredForAdministrators),allowRecoveryCodes:Boolean(form.allowRecoveryCodes),allowTotp:Boolean(form.allowTotp)}; if(kind==='session') return {idleTimeoutMinutes:Number(form.idleTimeoutMinutes),absoluteTimeoutMinutes:Number(form.absoluteTimeoutMinutes),maxConcurrentSessions:Number(form.maxConcurrentSessions),revokeOnPasswordChange:Boolean(form.revokeOnPasswordChange),revokeOnMfaReset:Boolean(form.revokeOnMfaReset),reauthenticationMinutes:Number(form.reauthenticationMinutes)}; return {personalTokenMaxTtlDays:Number(form.personalTokenMaxTtlDays),serviceTokenMaxTtlDays:Number(form.serviceTokenMaxTtlDays),maxActiveTokens:Number(form.maxActiveTokens),requireServiceAccountCidr:Boolean(form.requireServiceAccountCidr)}; }
function diff(kind:Kind,current:Record<string,unknown>,form:FormState):string[]{ const before=toForm(kind,current); return Object.keys(form).filter((key)=>String(before[key])!==String(form[key])).map((key)=>`${fieldName(key)}: ${display(before[key])} → ${display(form[key])}`); }
function fieldName(value:string){ return value.replace(/([A-Z])/g,' $1').replace(/^./,(c)=>c.toUpperCase()); }
function display(value:unknown){ if(typeof value==='boolean') return value?'Enabled':'Disabled'; return String(value ?? 'Not set'); }
function label(kind:Kind){ return KINDS.find((item)=>item.value===kind)?.label ?? kind; }
function formatDate(value:string){ const date=new Date(value); return Number.isNaN(date.valueOf())?value:date.toLocaleString(); }
function RevisionPreview({ revision }: Readonly<{revision:SecurityPolicyRevision|null}>){ if(!revision)return null; let values:Record<string,unknown>={}; try{values=JSON.parse(revision.policyJson) as Record<string,unknown>;}catch{return <p className="rounded-2xl bg-slate-50 p-3 text-sm text-slate-600">The stored revision can be restored, but its preview is unavailable.</p>;} return <dl className="grid gap-2 rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-2">{Object.entries(values).filter(([key])=>!['tenantId','updatedBy','updatedAt'].includes(key)).map(([key,value])=><div key={key}><dt className="text-xs font-black text-slate-500">{fieldName(key)}</dt><dd className="text-sm text-slate-800">{display(value)}</dd></div>)}</dl>; }
