'use client';

import { useCallback, useEffect, useState } from 'react';
import { accessManagementApi } from '@/lib/api/accessManagementApi';
import { formatIamError } from '@/lib/iam/errorPresentation';
import type { Session } from '@/lib/iam/types';
import { AuditReasonSelector, HumanStatus, SearchField, isAuditReasonValid } from '../shared/beginnerUi';
import { WorkspaceEmpty, WorkspaceError, WorkspaceLoading, WorkspaceModal } from '../shared/workspaceUi';

export function SessionManagementPanel({ tenantId, canManage, onChanged }: Readonly<{ tenantId: string; canManage: boolean; onChanged: () => void }>) {
  const [items, setItems] = useState<Session[]>([]); const [subject, setSubject] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const [selected, setSelected] = useState<Session | null>(null); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const page = await accessManagementApi.sessions(tenantId, 200, '', subject); setItems(page.items); } catch (cause) { setError(formatIamError(cause, 'Unable to load active sessions.')); } finally { setLoading(false); } }, [subject, tenantId]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 200); return () => window.clearTimeout(timer); }, [load]);
  async function revoke() { if (!selected || !isAuditReasonValid(reason, 'HIGH_RISK')) return; setBusy(true); setError(''); try { await accessManagementApi.revokeSession(tenantId, selected.sessionId, selected.version, reason); setSelected(null); await load(); onChanged(); } catch (cause) { setError(formatIamError(cause, 'The session could not be revoked.')); } finally { setBusy(false); } }
  return <div className="space-y-5">
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><label htmlFor="session-subject-search" className="mb-1.5 block text-sm font-black text-slate-800">Find a person or principal</label><SearchField id="session-subject-search" value={subject} onChange={setSubject} placeholder="Search by subject identifier" /></section>
    {error ? <WorkspaceError message={error} onRetry={() => { void load(); }} /> : null}
    {loading && !items.length ? <WorkspaceLoading title="Loading sessions" /> : null}
    {!loading && !items.length ? subject.trim() ? <WorkspaceEmpty title="No sessions match this search" description="No active session in your current workspace matches the entered person or principal." nextAction={<button type="button" onClick={() => setSubject('')} className="font-black text-blue-700 hover:underline">Clear the search</button>} /> : <WorkspaceEmpty title="No active sessions" description="There are no active browser or client sessions in your current workspace." nextAction="No recovery action is required. New sessions will appear after successful sign-in." /> : null}
    <div className="space-y-3">{items.map((session) => <article key={session.sessionId} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-black text-slate-950">{session.subjectId}</h3><HumanStatus value={session.status} /></div><p className="mt-1 text-sm text-slate-600">{session.subjectType} · {session.ipAddress || 'IP unavailable'}</p><p className="mt-2 text-xs text-slate-500">Last activity {formatDate(session.lastSeenAt)} · Absolute expiry {formatDate(session.absoluteExpiresAt)}</p><p className="mt-1 line-clamp-2 text-xs text-slate-500">{session.userAgent}</p></div>{canManage && session.status === 'ACTIVE' ? <button type="button" onClick={() => { setSelected(session); setReason(''); }} className="rounded-xl border border-rose-300 px-4 py-2 text-sm font-black text-rose-700">Revoke session</button> : null}</div><details className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-3 text-xs text-slate-600"><summary className="cursor-pointer font-black">Technical evidence</summary><dl className="mt-2 grid gap-1"><div><dt className="inline font-black">Session ID: </dt><dd className="inline break-all">{session.sessionId}</dd></div><div><dt className="inline font-black">Methods: </dt><dd className="inline">{session.methods.join(', ') || 'Unknown'}</dd></div><div><dt className="inline font-black">Idle expiry: </dt><dd className="inline">{formatDate(session.idleExpiresAt)}</dd></div></dl></details></article>)}</div>
    <WorkspaceModal open={Boolean(selected)} title="Revoke session" description="The selected browser or client will need to authenticate again." onClose={() => setSelected(null)}><div className="space-y-4"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><b>{selected?.subjectId}</b><p className="mt-1">Last active {formatDate(selected?.lastSeenAt ?? '')}</p></div><AuditReasonSelector idPrefix="revoke-session" value={reason} onChange={setReason} tier="HIGH_RISK" /><div className="flex justify-end gap-2"><button type="button" onClick={() => setSelected(null)} className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-black">Cancel</button><button type="button" disabled={busy || !isAuditReasonValid(reason, 'HIGH_RISK')} onClick={() => { void revoke(); }} className="rounded-xl bg-rose-700 px-4 py-2 text-sm font-black text-white disabled:bg-slate-300">Revoke session</button></div></div></WorkspaceModal>
  </div>;
}
function formatDate(value: string) { if (!value) return 'Not available'; const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleString(); }
