package com.opensocket.aievent.database.persistence.a2a;

import java.util.List;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;
import com.opensocket.aievent.core.a2a.*;
import com.opensocket.aievent.database.persistence.a2a.po.*;
import org.springframework.stereotype.Component;

@Component
@ConditionalOnProperty(prefix="task", name="store", havingValue="MYBATIS")
public class A2APersistenceConverter {
    private final ObjectMapper mapper;
    public A2APersistenceConverter(ObjectMapper mapper) { this.mapper = mapper; }

    public A2APolicyPo toPo(A2APolicy v) {
        A2APolicyPo p = new A2APolicyPo();
        p.setTenantId(v.getTenantId()); p.setPolicyId(v.getPolicyId()); p.setPolicyCode(v.getPolicyCode()); p.setPolicyName(v.getPolicyName());
        p.setSourceDomainId(v.getSourceDomainId()); p.setSourceDepartmentId(v.getSourceDepartmentId()); p.setSourceGroupId(v.getSourceGroupId()); p.setSourceAgentPoolId(v.getSourceAgentPoolId()); p.setSourceAgentId(v.getSourceAgentId());
        p.setTargetDomainId(v.getTargetDomainId()); p.setTargetDepartmentId(v.getTargetDepartmentId()); p.setTargetGroupId(v.getTargetGroupId()); p.setTargetAgentPoolId(v.getTargetAgentPoolId());
        p.setGovernanceOwnerDepartmentId(v.getGovernanceOwnerDepartmentId()); p.setGovernanceOwnerGroupId(v.getGovernanceOwnerGroupId()); p.setGovernanceScopeClass(v.getGovernanceScopeClass()==null?null:v.getGovernanceScopeClass().name()); p.setGovernanceScopeStatus(v.getGovernanceScopeStatus());
        p.setAllowedTaskTypesJson(json(v.getAllowedTaskTypes())); p.setAllowedServiceCodesJson(json(v.getAllowedServiceCodes())); p.setAllowedCapabilityCodesJson(json(v.getAllowedCapabilityCodes()));
        p.setMaxSensitivityLevel(v.getMaxSensitivityLevel()); p.setApprovalMode(v.getApprovalMode().name()); p.setMaxHopCount(v.getMaxHopCount()); p.setRateLimitPerMinute(v.getRateLimitPerMinute()); p.setTimeoutSeconds(v.getTimeoutSeconds());
        p.setIssueProjectionPolicy(v.getIssueProjectionPolicy()); p.setHandoffContextPolicyId(v.getHandoffContextPolicyId()); p.setHandoffContextRequirement(v.getHandoffContextRequirement());
        p.setResultAggregationPolicy(v.getResultAggregationPolicy().name()); p.setAggregationQuorum(v.getAggregationQuorum()); p.setCancellationPolicy(v.getCancellationPolicy().name()); p.setFailurePropagationPolicy(v.getFailurePropagationPolicy().name());
        p.setAllowReturnToExistingDomain(v.isAllowReturnToExistingDomain()); p.setEnabled(v.isEnabled()); p.setEffectiveAt(v.getEffectiveAt()); p.setExpiresAt(v.getExpiresAt()); p.setVersion(v.getVersion()); p.setCreatedAt(v.getCreatedAt()); p.setUpdatedAt(v.getUpdatedAt());
        return p;
    }

    public A2APolicy toDomain(A2APolicyPo p) {
        A2APolicy v = new A2APolicy();
        v.setTenantId(p.getTenantId()); v.setPolicyId(p.getPolicyId()); v.setPolicyCode(p.getPolicyCode()); v.setPolicyName(p.getPolicyName());
        v.setSourceDomainId(p.getSourceDomainId()); v.setSourceDepartmentId(p.getSourceDepartmentId()); v.setSourceGroupId(p.getSourceGroupId()); v.setSourceAgentPoolId(p.getSourceAgentPoolId()); v.setSourceAgentId(p.getSourceAgentId());
        v.setTargetDomainId(p.getTargetDomainId()); v.setTargetDepartmentId(p.getTargetDepartmentId()); v.setTargetGroupId(p.getTargetGroupId()); v.setTargetAgentPoolId(p.getTargetAgentPoolId());
        v.setGovernanceOwnerDepartmentId(p.getGovernanceOwnerDepartmentId()); v.setGovernanceOwnerGroupId(p.getGovernanceOwnerGroupId()); v.setGovernanceScopeClass(enumValue(A2AGovernanceScopeClass.class,p.getGovernanceScopeClass(),A2AGovernanceScopeClass.TENANT)); v.setGovernanceScopeStatus(p.getGovernanceScopeStatus()==null?"RESOLVED":p.getGovernanceScopeStatus());
        v.setAllowedTaskTypes(list(p.getAllowedTaskTypesJson())); v.setAllowedServiceCodes(list(p.getAllowedServiceCodesJson())); v.setAllowedCapabilityCodes(list(p.getAllowedCapabilityCodesJson()));
        v.setMaxSensitivityLevel(p.getMaxSensitivityLevel()); v.setApprovalMode(enumValue(A2AApprovalMode.class, p.getApprovalMode(), A2AApprovalMode.NONE)); v.setMaxHopCount(p.getMaxHopCount()); v.setRateLimitPerMinute(p.getRateLimitPerMinute()); v.setTimeoutSeconds(p.getTimeoutSeconds());
        v.setIssueProjectionPolicy(p.getIssueProjectionPolicy()); v.setHandoffContextPolicyId(p.getHandoffContextPolicyId()); v.setHandoffContextRequirement(p.getHandoffContextRequirement());
        v.setResultAggregationPolicy(enumValue(A2AResultAggregationPolicy.class, p.getResultAggregationPolicy(), A2AResultAggregationPolicy.MANUAL_DECISION)); v.setAggregationQuorum(Math.max(1,p.getAggregationQuorum())); v.setCancellationPolicy(enumValue(A2ACancellationPolicy.class, p.getCancellationPolicy(), A2ACancellationPolicy.MANUAL_DECISION)); v.setFailurePropagationPolicy(enumValue(A2AFailurePropagationPolicy.class, p.getFailurePropagationPolicy(), A2AFailurePropagationPolicy.WAIT_HUMAN));
        v.setAllowReturnToExistingDomain(p.isAllowReturnToExistingDomain()); v.setEnabled(p.isEnabled()); v.setEffectiveAt(p.getEffectiveAt()); v.setExpiresAt(p.getExpiresAt()); v.setVersion(p.getVersion()); v.setCreatedAt(p.getCreatedAt()); v.setUpdatedAt(p.getUpdatedAt());
        return v;
    }

    public A2ARequestPo toPo(A2ARequest v) {
        A2ARequestPo p = new A2ARequestPo();
        p.setTenantId(v.getTenantId()); p.setRequestId(v.getRequestId()); p.setRootTaskId(v.getRootTaskId()); p.setSourceTaskId(v.getSourceTaskId()); p.setRequestingTaskId(v.getRequestingTaskId()); p.setRequestingAgentId(v.getRequestingAgentId()); p.setRequesterType(v.getRequesterType().name());
        p.setSourceDepartmentId(v.getSourceDepartmentId()); p.setSourceGroupId(v.getSourceGroupId()); p.setSourceDomainId(v.getSourceDomainId()); p.setTargetDepartmentId(v.getTargetDepartmentId()); p.setTargetGroupId(v.getTargetGroupId()); p.setTargetDomainId(v.getTargetDomainId());
        p.setRequestedTaskType(v.getRequestedTaskType()); p.setRequestedServiceCode(v.getRequestedServiceCode()); p.setRequestedCapabilityCodesJson(json(v.getRequestedCapabilityCodes())); p.setTargetAgentPoolId(v.getTargetAgentPoolId()); p.setPolicyId(v.getPolicyId());
        p.setPolicyVersion(v.getPolicyVersion()); p.setPolicySnapshotJson(objectJson(v.getPolicySnapshot())); p.setPolicySnapshotHash(v.getPolicySnapshotHash());
        p.setApprovalStatus(v.getApprovalStatus().name()); p.setApprovalCount(v.getApprovalCount()); p.setRequiredApprovalCount(v.getRequiredApprovalCount()); p.setApprovalActorIdsJson(json(v.getApprovalActorIds())); p.setRequestStatus(v.getRequestStatus().name());
        p.setOperationalStage(v.getOperationalStage()==null?null:v.getOperationalStage().name()); p.setBlockerCode(v.getBlockerCode()==null?null:v.getBlockerCode().name()); p.setBlockerReason(v.getBlockerReason());
        p.setReason(v.getReason()); p.setInputPayloadRef(v.getInputPayloadRef()); p.setSensitivityLevel(v.getSensitivityLevel()); p.setHopCount(v.getHopCount()); p.setIdempotencyKey(v.getIdempotencyKey()); p.setCorrelationId(v.getCorrelationId()); p.setChildTaskId(v.getChildTaskId());
        p.setRequestedByType(v.getRequestedByType()); p.setRequestedById(v.getRequestedById());
        p.setOriginPrincipalType(v.getOriginPrincipalType()); p.setOriginPrincipalId(v.getOriginPrincipalId()); p.setDelegatingPrincipalType(v.getDelegatingPrincipalType()); p.setDelegatingPrincipalId(v.getDelegatingPrincipalId()); p.setExecutingPrincipalType(v.getExecutingPrincipalType()); p.setExecutingPrincipalId(v.getExecutingPrincipalId()); p.setDelegationDepth(v.getDelegationDepth());
        p.setRejectionReasonCode(v.getRejectionReasonCode()); p.setCreatedAt(v.getCreatedAt()); p.setUpdatedAt(v.getUpdatedAt()); p.setExpiresAt(v.getExpiresAt()); p.setVersion(v.getVersion());
        return p;
    }

    public A2ARequest toDomain(A2ARequestPo p) {
        A2ARequest v = new A2ARequest();
        v.setTenantId(p.getTenantId()); v.setRequestId(p.getRequestId()); v.setRootTaskId(p.getRootTaskId()); v.setSourceTaskId(p.getSourceTaskId()); v.setRequestingTaskId(p.getRequestingTaskId()); v.setRequestingAgentId(p.getRequestingAgentId()); v.setRequesterType(enumValue(A2ARequesterType.class, p.getRequesterType(), A2ARequesterType.TASK));
        v.setSourceDepartmentId(p.getSourceDepartmentId()); v.setSourceGroupId(p.getSourceGroupId()); v.setSourceDomainId(p.getSourceDomainId()); v.setTargetDepartmentId(p.getTargetDepartmentId()); v.setTargetGroupId(p.getTargetGroupId()); v.setTargetDomainId(p.getTargetDomainId());
        v.setRequestedTaskType(p.getRequestedTaskType()); v.setRequestedServiceCode(p.getRequestedServiceCode()); v.setRequestedCapabilityCodes(list(p.getRequestedCapabilityCodesJson())); v.setTargetAgentPoolId(p.getTargetAgentPoolId()); v.setPolicyId(p.getPolicyId());
        v.setPolicyVersion(p.getPolicyVersion()); v.setPolicySnapshot(object(p.getPolicySnapshotJson(), A2ADirectionalPolicySnapshot.class)); v.setPolicySnapshotHash(p.getPolicySnapshotHash());
        v.setApprovalStatus(enumValue(A2AApprovalStatus.class, p.getApprovalStatus(), A2AApprovalStatus.NOT_REQUIRED)); v.setApprovalCount(p.getApprovalCount()); v.setRequiredApprovalCount(p.getRequiredApprovalCount()); v.setApprovalActorIds(list(p.getApprovalActorIdsJson())); v.setRequestStatus(enumValue(A2ARequestStatus.class, p.getRequestStatus(), A2ARequestStatus.REQUESTED));
        v.setOperationalStage(enumValue(A2AOperationalStage.class, p.getOperationalStage(), A2AOperationalStage.defaultFor(v.getRequestStatus()))); v.setBlockerCode(enumValue(A2ABlockerCode.class, p.getBlockerCode(), A2ABlockerCode.NONE)); v.setBlockerReason(p.getBlockerReason());
        v.setReason(p.getReason()); v.setInputPayloadRef(p.getInputPayloadRef()); v.setSensitivityLevel(p.getSensitivityLevel()); v.setHopCount(p.getHopCount()); v.setIdempotencyKey(p.getIdempotencyKey()); v.setCorrelationId(p.getCorrelationId()); v.setChildTaskId(p.getChildTaskId());
        v.setRequestedByType(p.getRequestedByType()); v.setRequestedById(p.getRequestedById());
        v.setOriginPrincipalType(p.getOriginPrincipalType()); v.setOriginPrincipalId(p.getOriginPrincipalId()); v.setDelegatingPrincipalType(p.getDelegatingPrincipalType()); v.setDelegatingPrincipalId(p.getDelegatingPrincipalId()); v.setExecutingPrincipalType(p.getExecutingPrincipalType()); v.setExecutingPrincipalId(p.getExecutingPrincipalId()); v.setDelegationDepth(p.getDelegationDepth());
        v.setRejectionReasonCode(p.getRejectionReasonCode()); v.setCreatedAt(p.getCreatedAt()); v.setUpdatedAt(p.getUpdatedAt()); v.setExpiresAt(p.getExpiresAt()); v.setVersion(p.getVersion());
        return v;
    }

    public A2AResultPo toPo(A2AResult v) { A2AResultPo p=new A2AResultPo();p.setTenantId(v.getTenantId());p.setResultId(v.getResultId());p.setRequestId(v.getRequestId());p.setRootTaskId(v.getRootTaskId());p.setParentTaskId(v.getParentTaskId());p.setChildTaskId(v.getChildTaskId());p.setResultStatus(v.getResultStatus()==null?null:v.getResultStatus().name());p.setResultSummary(v.getResultSummary());p.setResultPayloadRef(v.getResultPayloadRef());p.setEvidenceRefsJson(json(v.getEvidenceRefs()));p.setCompletedByAgentId(v.getCompletedByAgentId());p.setAssignmentId(v.getAssignmentId());p.setExecutionAttemptId(v.getExecutionAttemptId());p.setAttemptNo(v.getAttemptNo());p.setDispatchRequestId(v.getDispatchRequestId());p.setDispatchTokenHash(v.getDispatchTokenHash());p.setFencingTokenHash(v.getFencingTokenHash());p.setAgentSessionId(v.getAgentSessionId());p.setCallbackInboxId(v.getCallbackInboxId());p.setPayloadHash(v.getPayloadHash());p.setResultSchemaVersion(v.getResultSchemaVersion());p.setResultEvidenceHash(v.getResultEvidenceHash());p.setResultFingerprint(v.getResultFingerprint());p.setPolicyVersion(v.getPolicyVersion());p.setPolicySnapshotHash(v.getPolicySnapshotHash());p.setAcceptanceAttemptId(v.getAcceptanceAttemptId());p.setReceivedAt(v.getReceivedAt());p.setAcceptedAt(v.getAcceptedAt());p.setCompletedAt(v.getCompletedAt());p.setIdempotencyKey(v.getIdempotencyKey());p.setCreatedAt(v.getCreatedAt());p.setVersion(v.getVersion());return p; }
    public A2AResult toDomain(A2AResultPo p) { A2AResult v=new A2AResult();v.setTenantId(p.getTenantId());v.setResultId(p.getResultId());v.setRequestId(p.getRequestId());v.setRootTaskId(p.getRootTaskId());v.setParentTaskId(p.getParentTaskId());v.setChildTaskId(p.getChildTaskId());v.setResultStatus(enumValue(A2AResultStatus.class,p.getResultStatus(),null));v.setResultSummary(p.getResultSummary());v.setResultPayloadRef(p.getResultPayloadRef());v.setEvidenceRefs(list(p.getEvidenceRefsJson()));v.setCompletedByAgentId(p.getCompletedByAgentId());v.setAssignmentId(p.getAssignmentId());v.setExecutionAttemptId(p.getExecutionAttemptId());v.setAttemptNo(p.getAttemptNo());v.setDispatchRequestId(p.getDispatchRequestId());v.setDispatchTokenHash(p.getDispatchTokenHash());v.setFencingTokenHash(p.getFencingTokenHash());v.setAgentSessionId(p.getAgentSessionId());v.setCallbackInboxId(p.getCallbackInboxId());v.setPayloadHash(p.getPayloadHash());v.setResultSchemaVersion(Math.max(1,p.getResultSchemaVersion()));v.setResultEvidenceHash(p.getResultEvidenceHash());v.setResultFingerprint(p.getResultFingerprint());v.setPolicyVersion(p.getPolicyVersion());v.setPolicySnapshotHash(p.getPolicySnapshotHash());v.setAcceptanceAttemptId(p.getAcceptanceAttemptId());v.setReceivedAt(p.getReceivedAt());v.setAcceptedAt(p.getAcceptedAt());v.setCompletedAt(p.getCompletedAt());v.setIdempotencyKey(p.getIdempotencyKey());v.setCreatedAt(p.getCreatedAt());v.setVersion(p.getVersion());return v; }
    public A2AResultAttemptPo toPo(A2AResultAttempt v) { A2AResultAttemptPo p=new A2AResultAttemptPo();p.setTenantId(v.getTenantId());p.setAttemptId(v.getAttemptId());p.setRequestId(v.getRequestId());p.setChildTaskId(v.getChildTaskId());p.setResultId(v.getResultId());p.setAssignmentId(v.getAssignmentId());p.setExecutionAttemptId(v.getExecutionAttemptId());p.setAttemptNo(v.getAttemptNo());p.setDispatchRequestId(v.getDispatchRequestId());p.setCallbackInboxId(v.getCallbackInboxId());p.setAgentId(v.getAgentId());p.setAgentSessionId(v.getAgentSessionId());p.setResultStatus(v.getResultStatus()==null?null:v.getResultStatus().name());p.setDecision(v.getDecision()==null?null:v.getDecision().name());p.setClassification(v.getClassification()==null?null:v.getClassification().name());p.setResultSchemaVersion(v.getResultSchemaVersion());p.setResultEvidenceHash(v.getResultEvidenceHash());p.setResultFingerprint(v.getResultFingerprint());p.setPolicyVersion(v.getPolicyVersion());p.setPolicySnapshotHash(v.getPolicySnapshotHash());p.setReasonCode(v.getReasonCode());p.setReason(v.getReason());p.setPayloadHash(v.getPayloadHash());p.setIdempotencyKey(v.getIdempotencyKey());p.setCorrelationId(v.getCorrelationId());p.setOccurredAt(v.getOccurredAt());p.setReceivedAt(v.getReceivedAt());return p; }
    public A2AResultAttempt toDomain(A2AResultAttemptPo p) { A2AResultAttempt v=new A2AResultAttempt();v.setTenantId(p.getTenantId());v.setAttemptId(p.getAttemptId());v.setRequestId(p.getRequestId());v.setChildTaskId(p.getChildTaskId());v.setResultId(p.getResultId());v.setAssignmentId(p.getAssignmentId());v.setExecutionAttemptId(p.getExecutionAttemptId());v.setAttemptNo(p.getAttemptNo());v.setDispatchRequestId(p.getDispatchRequestId());v.setCallbackInboxId(p.getCallbackInboxId());v.setAgentId(p.getAgentId());v.setAgentSessionId(p.getAgentSessionId());v.setResultStatus(enumValue(A2AResultStatus.class,p.getResultStatus(),null));v.setDecision(enumValue(A2AResultAcceptanceDecision.class,p.getDecision(),A2AResultAcceptanceDecision.MISSING_EVIDENCE));v.setClassification(enumValue(A2AResultClassification.class,p.getClassification(),null));v.setResultSchemaVersion(Math.max(1,p.getResultSchemaVersion()));v.setResultEvidenceHash(p.getResultEvidenceHash());v.setResultFingerprint(p.getResultFingerprint());v.setPolicyVersion(p.getPolicyVersion());v.setPolicySnapshotHash(p.getPolicySnapshotHash());v.setReasonCode(p.getReasonCode());v.setReason(p.getReason());v.setPayloadHash(p.getPayloadHash());v.setIdempotencyKey(p.getIdempotencyKey());v.setCorrelationId(p.getCorrelationId());v.setOccurredAt(p.getOccurredAt());v.setReceivedAt(p.getReceivedAt());return v; }
    public A2AResultEvidencePo toPo(A2AResultEvidence v) { A2AResultEvidencePo p=new A2AResultEvidencePo();p.setTenantId(v.getTenantId());p.setEvidenceId(v.getEvidenceId());p.setAttemptId(v.getAttemptId());p.setRequestId(v.getRequestId());p.setEvidenceType(v.getEvidenceType());p.setEvidenceReference(v.getEvidenceReference());p.setEvidenceHash(v.getEvidenceHash());p.setVerificationDecision(v.getVerificationDecision());p.setClassification(v.getClassification()==null?null:v.getClassification().name());p.setResultFingerprint(v.getResultFingerprint());p.setReasonCode(v.getReasonCode());p.setVerifiedAt(v.getVerifiedAt());return p; }
    public A2AResultEvidence toDomain(A2AResultEvidencePo p) { A2AResultEvidence v=new A2AResultEvidence();v.setTenantId(p.getTenantId());v.setEvidenceId(p.getEvidenceId());v.setAttemptId(p.getAttemptId());v.setRequestId(p.getRequestId());v.setEvidenceType(p.getEvidenceType());v.setEvidenceReference(p.getEvidenceReference());v.setEvidenceHash(p.getEvidenceHash());v.setVerificationDecision(p.getVerificationDecision());v.setClassification(enumValue(A2AResultClassification.class,p.getClassification(),null));v.setResultFingerprint(p.getResultFingerprint());v.setReasonCode(p.getReasonCode());v.setVerifiedAt(p.getVerifiedAt());return v; }
    public A2AResultQuarantinePo toPo(A2AResultQuarantine v) { A2AResultQuarantinePo p=new A2AResultQuarantinePo();p.setTenantId(v.getTenantId());p.setQuarantineId(v.getQuarantineId());p.setAttemptId(v.getAttemptId());p.setRequestId(v.getRequestId());p.setChildTaskId(v.getChildTaskId());p.setClassification(v.getClassification()==null?null:v.getClassification().name());p.setReasonCode(v.getReasonCode());p.setReason(v.getReason());p.setPayloadHash(v.getPayloadHash());p.setCallbackInboxId(v.getCallbackInboxId());p.setAssignmentId(v.getAssignmentId());p.setExecutionAttemptId(v.getExecutionAttemptId());p.setStatus(v.getStatus());p.setResolvedBy(v.getResolvedBy());p.setResolutionReason(v.getResolutionReason());p.setQuarantinedAt(v.getQuarantinedAt());p.setResolvedAt(v.getResolvedAt());return p; }
    public A2AResultQuarantine toDomain(A2AResultQuarantinePo p) { A2AResultQuarantine v=new A2AResultQuarantine();v.setTenantId(p.getTenantId());v.setQuarantineId(p.getQuarantineId());v.setAttemptId(p.getAttemptId());v.setRequestId(p.getRequestId());v.setChildTaskId(p.getChildTaskId());v.setClassification(enumValue(A2AResultClassification.class,p.getClassification(),A2AResultClassification.BINDING_CONFLICT));v.setReasonCode(p.getReasonCode());v.setReason(p.getReason());v.setPayloadHash(p.getPayloadHash());v.setCallbackInboxId(p.getCallbackInboxId());v.setAssignmentId(p.getAssignmentId());v.setExecutionAttemptId(p.getExecutionAttemptId());v.setStatus(p.getStatus());v.setResolvedBy(p.getResolvedBy());v.setResolutionReason(p.getResolutionReason());v.setQuarantinedAt(p.getQuarantinedAt());v.setResolvedAt(p.getResolvedAt());return v; }
    public A2AParentAggregationPo toPo(A2AParentAggregation v) { A2AParentAggregationPo p=new A2AParentAggregationPo();p.setTenantId(v.getTenantId());p.setParentTaskId(v.getParentTaskId());p.setAggregationPolicy(v.getAggregationPolicy()==null?null:v.getAggregationPolicy().name());p.setPolicyVersion(v.getPolicyVersion());p.setPolicySnapshotHash(v.getPolicySnapshotHash());p.setQuorumCount(v.getQuorumCount());p.setAggregateStatus(v.getAggregateStatus());p.setDecisionReason(v.getDecisionReason());p.setManualDecisionRequired(v.isManualDecisionRequired());p.setTotalCount(v.getTotalCount());p.setResultCount(v.getResultCount());p.setPendingCount(v.getPendingCount());p.setSucceededCount(v.getSucceededCount());p.setPartialCount(v.getPartialCount());p.setFailedCount(v.getFailedCount());p.setCancelledCount(v.getCancelledCount());p.setSummary(v.getSummary());p.setComputationHash(v.getComputationHash());p.setLastResultId(v.getLastResultId());p.setComputedAt(v.getComputedAt());p.setVersion(v.getVersion());return p; }
    public A2AParentAggregation toDomain(A2AParentAggregationPo p) { A2AParentAggregation v=new A2AParentAggregation();v.setTenantId(p.getTenantId());v.setParentTaskId(p.getParentTaskId());v.setAggregationPolicy(enumValue(A2AResultAggregationPolicy.class,p.getAggregationPolicy(),A2AResultAggregationPolicy.MANUAL_DECISION).canonical());v.setPolicyVersion(p.getPolicyVersion());v.setPolicySnapshotHash(p.getPolicySnapshotHash());v.setQuorumCount(Math.max(1,p.getQuorumCount()));v.setAggregateStatus(p.getAggregateStatus());v.setDecisionReason(p.getDecisionReason());v.setManualDecisionRequired(p.isManualDecisionRequired());v.setTotalCount(p.getTotalCount());v.setResultCount(p.getResultCount());v.setPendingCount(p.getPendingCount());v.setSucceededCount(p.getSucceededCount());v.setPartialCount(p.getPartialCount());v.setFailedCount(p.getFailedCount());v.setCancelledCount(p.getCancelledCount());v.setSummary(p.getSummary());v.setComputationHash(p.getComputationHash());v.setLastResultId(p.getLastResultId());v.setComputedAt(p.getComputedAt());v.setVersion(p.getVersion());return v; }
    public A2AResultProcessingPo toPo(A2AResultProcessing v){A2AResultProcessingPo p=new A2AResultProcessingPo();p.setTenantId(v.getTenantId());p.setResultId(v.getResultId());p.setRequestId(v.getRequestId());p.setParentTaskId(v.getParentTaskId());p.setChildTaskId(v.getChildTaskId());p.setProcessingStatus(v.getProcessingStatus().name());p.setReconciliationClassification(v.getReconciliationClassification().name());p.setLastErrorCode(v.getLastErrorCode());p.setLastError(v.getLastError());p.setAttemptCount(v.getAttemptCount());p.setNextReconcileAt(v.getNextReconcileAt());p.setLastReconciledAt(v.getLastReconciledAt());p.setCompletedAt(v.getCompletedAt());p.setCreatedAt(v.getCreatedAt());p.setUpdatedAt(v.getUpdatedAt());p.setRowVersion(v.getRowVersion());return p;}
    public A2AResultProcessing toDomain(A2AResultProcessingPo p){A2AResultProcessing v=new A2AResultProcessing();v.setTenantId(p.getTenantId());v.setResultId(p.getResultId());v.setRequestId(p.getRequestId());v.setParentTaskId(p.getParentTaskId());v.setChildTaskId(p.getChildTaskId());v.setProcessingStatus(enumValue(A2AResultProcessingStatus.class,p.getProcessingStatus(),A2AResultProcessingStatus.CHILD_COMPLETION_PENDING));v.setReconciliationClassification(enumValue(A2AResultReconciliationClassification.class,p.getReconciliationClassification(),A2AResultReconciliationClassification.NONE));v.setLastErrorCode(p.getLastErrorCode());v.setLastError(p.getLastError());v.setAttemptCount(p.getAttemptCount());v.setNextReconcileAt(p.getNextReconcileAt());v.setLastReconciledAt(p.getLastReconciledAt());v.setCompletedAt(p.getCompletedAt());v.setCreatedAt(p.getCreatedAt());v.setUpdatedAt(p.getUpdatedAt());v.setRowVersion(p.getRowVersion());return v;}
    public A2AAggregationEvidencePo toPo(A2AAggregationEvidence v){A2AAggregationEvidencePo p=new A2AAggregationEvidencePo();p.setTenantId(v.getTenantId());p.setEvidenceId(v.getEvidenceId());p.setParentTaskId(v.getParentTaskId());p.setResultId(v.getResultId());p.setEvidenceType(v.getEvidenceType());p.setComputationHash(v.getComputationHash());p.setAggregateStatus(v.getAggregateStatus());p.setDecisionReason(v.getDecisionReason());p.setExpectedVersion(v.getExpectedVersion());p.setResultingVersion(v.getResultingVersion());p.setAttemptNo(v.getAttemptNo());p.setOccurredAt(v.getOccurredAt());return p;}
    public A2AAggregationEvidence toDomain(A2AAggregationEvidencePo p){A2AAggregationEvidence v=new A2AAggregationEvidence();v.setTenantId(p.getTenantId());v.setEvidenceId(p.getEvidenceId());v.setParentTaskId(p.getParentTaskId());v.setResultId(p.getResultId());v.setEvidenceType(p.getEvidenceType());v.setComputationHash(p.getComputationHash());v.setAggregateStatus(p.getAggregateStatus());v.setDecisionReason(p.getDecisionReason());v.setExpectedVersion(p.getExpectedVersion());v.setResultingVersion(p.getResultingVersion());v.setAttemptNo(p.getAttemptNo());v.setOccurredAt(p.getOccurredAt());return v;}

    public A2ACancellationPo toPo(A2ACancellationRecord v) {
        A2ACancellationPo p=new A2ACancellationPo();
        p.setTenantId(v.getTenantId());p.setCancellationId(v.getCancellationId());p.setRequestId(v.getRequestId());p.setChildTaskId(v.getChildTaskId());p.setAssignmentId(v.getAssignmentId());p.setExecutionAttemptId(v.getExecutionAttemptId());p.setAttemptNo(v.getAttemptNo());p.setDispatchRequestId(v.getDispatchRequestId());p.setAgentId(v.getAgentId());p.setAgentSessionId(v.getAgentSessionId());p.setOwnerGatewayNodeId(v.getOwnerGatewayNodeId());p.setRevokedFencingTokenHash(v.getRevokedFencingTokenHash());p.setActiveFencingTokenHash(v.getActiveFencingTokenHash());p.setCancellationFingerprint(v.getCancellationFingerprint());p.setIdempotencyKey(v.getIdempotencyKey());p.setStatus(v.getStatus()==null?null:v.getStatus().name());p.setOutcome(v.getOutcome()==null?null:v.getOutcome().name());p.setProcessingStatus(v.getProcessingStatus()==null?null:v.getProcessingStatus().name());p.setReconciliationClassification(v.getReconciliationClassification()==null?null:v.getReconciliationClassification().name());p.setReason(v.getReason());p.setRequestedByType(v.getRequestedByType());p.setRequestedById(v.getRequestedById());p.setDeliveryStatus(v.getDeliveryStatus());p.setLastError(v.getLastError());p.setRetryCount(v.getRetryCount());p.setReconciliationCount(v.getReconciliationCount());p.setRequestedAt(v.getRequestedAt());p.setResultCutoffAt(v.getResultCutoffAt());p.setDeliveryAt(v.getDeliveryAt());p.setAcknowledgedAt(v.getAcknowledgedAt());p.setDeadlineAt(v.getDeadlineAt());p.setNextReconcileAt(v.getNextReconcileAt());p.setLastReconciledAt(v.getLastReconciledAt());p.setCompletedAt(v.getCompletedAt());p.setUpdatedAt(v.getUpdatedAt());p.setVersion(v.getVersion());return p;
    }
    public A2ACancellationRecord toDomain(A2ACancellationPo p) {
        A2ACancellationRecord v=new A2ACancellationRecord();
        v.setTenantId(p.getTenantId());v.setCancellationId(p.getCancellationId());v.setRequestId(p.getRequestId());v.setChildTaskId(p.getChildTaskId());v.setAssignmentId(p.getAssignmentId());v.setExecutionAttemptId(p.getExecutionAttemptId());v.setAttemptNo(p.getAttemptNo());v.setDispatchRequestId(p.getDispatchRequestId());v.setAgentId(p.getAgentId());v.setAgentSessionId(p.getAgentSessionId());v.setOwnerGatewayNodeId(p.getOwnerGatewayNodeId());v.setRevokedFencingTokenHash(p.getRevokedFencingTokenHash());v.setActiveFencingTokenHash(p.getActiveFencingTokenHash());v.setCancellationFingerprint(p.getCancellationFingerprint());v.setIdempotencyKey(p.getIdempotencyKey());v.setStatus(enumValue(A2ACancellationStatus.class,p.getStatus(),A2ACancellationStatus.REQUESTED));v.setOutcome(enumValue(A2ACancellationOutcome.class,p.getOutcome(),A2ACancellationOutcome.PENDING));v.setProcessingStatus(enumValue(A2ACancellationProcessingStatus.class,p.getProcessingStatus(),A2ACancellationProcessingStatus.REQUESTED));v.setReconciliationClassification(enumValue(A2ACancellationReconciliationClassification.class,p.getReconciliationClassification(),A2ACancellationReconciliationClassification.NONE));v.setReason(p.getReason());v.setRequestedByType(p.getRequestedByType());v.setRequestedById(p.getRequestedById());v.setDeliveryStatus(p.getDeliveryStatus());v.setLastError(p.getLastError());v.setRetryCount(p.getRetryCount()==null?0:p.getRetryCount());v.setReconciliationCount(p.getReconciliationCount()==null?0:p.getReconciliationCount());v.setRequestedAt(p.getRequestedAt());v.setResultCutoffAt(p.getResultCutoffAt());v.setDeliveryAt(p.getDeliveryAt());v.setAcknowledgedAt(p.getAcknowledgedAt());v.setDeadlineAt(p.getDeadlineAt());v.setNextReconcileAt(p.getNextReconcileAt());v.setLastReconciledAt(p.getLastReconciledAt());v.setCompletedAt(p.getCompletedAt());v.setUpdatedAt(p.getUpdatedAt());v.setVersion(p.getVersion());return v;
    }
    public A2ACancellationEvidencePo toPo(A2ACancellationEvidence v) {
        A2ACancellationEvidencePo p=new A2ACancellationEvidencePo();p.setTenantId(v.getTenantId());p.setEvidenceId(v.getEvidenceId());p.setCancellationId(v.getCancellationId());p.setRequestId(v.getRequestId());p.setEventKey(v.getEventKey());p.setAttemptNo(v.getAttemptNo());p.setAssignmentId(v.getAssignmentId());p.setExecutionAttemptId(v.getExecutionAttemptId());p.setEvidenceType(v.getEvidenceType());p.setEvidenceReference(v.getEvidenceReference());p.setEvidenceHash(v.getEvidenceHash());p.setDecision(v.getDecision());p.setReasonCode(v.getReasonCode());p.setDetails(v.getDetails());p.setOccurredAt(v.getOccurredAt());return p;
    }
    public A2ACancellationEvidence toDomain(A2ACancellationEvidencePo p) {
        A2ACancellationEvidence v=new A2ACancellationEvidence();v.setTenantId(p.getTenantId());v.setEvidenceId(p.getEvidenceId());v.setCancellationId(p.getCancellationId());v.setRequestId(p.getRequestId());v.setEventKey(p.getEventKey());v.setAttemptNo(p.getAttemptNo());v.setAssignmentId(p.getAssignmentId());v.setExecutionAttemptId(p.getExecutionAttemptId());v.setEvidenceType(p.getEvidenceType());v.setEvidenceReference(p.getEvidenceReference());v.setEvidenceHash(p.getEvidenceHash());v.setDecision(p.getDecision());v.setReasonCode(p.getReasonCode());v.setDetails(p.getDetails());v.setOccurredAt(p.getOccurredAt());return v;
    }

    public A2AStateHistoryPo toPo(A2AStateHistoryEntry v) {
        A2AStateHistoryPo p = new A2AStateHistoryPo();
        p.setTenantId(v.getTenantId()); p.setHistoryId(v.getHistoryId()); p.setRequestId(v.getRequestId());
        p.setFromStatus(v.getFromStatus() == null ? null : v.getFromStatus().name());
        p.setFromOperationalStage(v.getFromOperationalStage() == null ? null : v.getFromOperationalStage().name());
        p.setToStatus(v.getToStatus() == null ? null : v.getToStatus().name());
        p.setToOperationalStage(v.getToOperationalStage() == null ? null : v.getToOperationalStage().name());
        p.setBlockerCode(v.getBlockerCode() == null ? null : v.getBlockerCode().name());
        p.setTransitionCommand(v.getTransitionCommand() == null ? null : v.getTransitionCommand().name());
        p.setRequiredPermission(v.getRequiredPermission() == null ? null : v.getRequiredPermission().name());
        p.setEvidenceType(v.getEvidenceType() == null ? null : v.getEvidenceType().name());
        p.setEvidenceReference(v.getEvidenceReference());
        p.setDomainEventCode(v.getDomainEventCode());
        p.setFailureHandling(v.getFailureHandling() == null ? null : v.getFailureHandling().name());
        p.setTimeoutPolicy(v.getTimeoutPolicy() == null ? null : v.getTimeoutPolicy().name());
        p.setExpectedVersion(v.getExpectedVersion()); p.setResultingVersion(v.getResultingVersion()); p.setRecovery(v.isRecovery());
        p.setReasonCode(v.getReasonCode()); p.setReason(v.getReason()); p.setActorType(v.getActorType()); p.setActorId(v.getActorId());
        p.setCorrelationId(v.getCorrelationId()); p.setTransitionAt(v.getTransitionAt()); p.setRequestVersion(v.getRequestVersion());
        p.setIdempotencyKey(v.getIdempotencyKey());
        return p;
    }

    public A2AStateHistoryEntry toDomain(A2AStateHistoryPo p) {
        A2AStateHistoryEntry v = new A2AStateHistoryEntry();
        v.setTenantId(p.getTenantId()); v.setHistoryId(p.getHistoryId()); v.setRequestId(p.getRequestId());
        v.setFromStatus(enumValue(A2ARequestStatus.class, p.getFromStatus(), null));
        v.setFromOperationalStage(enumValue(A2AOperationalStage.class, p.getFromOperationalStage(), null));
        v.setToStatus(enumValue(A2ARequestStatus.class, p.getToStatus(), A2ARequestStatus.REQUESTED));
        v.setToOperationalStage(enumValue(A2AOperationalStage.class, p.getToOperationalStage(), A2AOperationalStage.defaultFor(v.getToStatus())));
        v.setBlockerCode(enumValue(A2ABlockerCode.class, p.getBlockerCode(), A2ABlockerCode.NONE));
        v.setTransitionCommand(enumValue(A2ATransitionCommand.class, p.getTransitionCommand(), null));
        v.setRequiredPermission(enumValue(A2ATransitionPermission.class, p.getRequiredPermission(), null));
        v.setEvidenceType(enumValue(A2ATransitionEvidenceType.class, p.getEvidenceType(), null));
        v.setEvidenceReference(p.getEvidenceReference());
        v.setDomainEventCode(p.getDomainEventCode());
        v.setFailureHandling(enumValue(A2ATransitionFailureHandling.class, p.getFailureHandling(), null));
        v.setTimeoutPolicy(enumValue(A2ATransitionTimeoutPolicy.class, p.getTimeoutPolicy(), null));
        v.setExpectedVersion(p.getExpectedVersion()); v.setResultingVersion(p.getResultingVersion()); v.setRecovery(p.isRecovery());
        v.setReasonCode(p.getReasonCode()); v.setReason(p.getReason()); v.setActorType(p.getActorType()); v.setActorId(p.getActorId());
        v.setCorrelationId(p.getCorrelationId()); v.setTransitionAt(p.getTransitionAt()); v.setRequestVersion(p.getRequestVersion());
        v.setIdempotencyKey(p.getIdempotencyKey());
        return v;
    }

    public A2AResultIdempotencyClaimPo toPo(A2AResultIdempotencyClaim v){A2AResultIdempotencyClaimPo p=new A2AResultIdempotencyClaimPo();p.setTenantId(v.getTenantId());p.setIdempotencyKey(v.getIdempotencyKey());p.setRequestId(v.getRequestId());p.setResultId(v.getResultId());p.setAcceptanceAttemptId(v.getAcceptanceAttemptId());p.setResultFingerprint(v.getResultFingerprint());p.setClaimedAt(v.getClaimedAt());return p;}
    public A2AResultIdempotencyClaim toDomain(A2AResultIdempotencyClaimPo p){A2AResultIdempotencyClaim v=new A2AResultIdempotencyClaim();v.setTenantId(p.getTenantId());v.setIdempotencyKey(p.getIdempotencyKey());v.setRequestId(p.getRequestId());v.setResultId(p.getResultId());v.setAcceptanceAttemptId(p.getAcceptanceAttemptId());v.setResultFingerprint(p.getResultFingerprint());v.setClaimedAt(p.getClaimedAt());return v;}

    private String json(Object v) { try { return mapper.writeValueAsString(v == null ? List.of() : v); } catch (Exception e) { return "[]"; } }
    private String objectJson(Object v) { try { return v == null ? null : mapper.writeValueAsString(v); } catch (Exception e) { throw new IllegalStateException("A2A JSON serialization failed", e); } }
    private <T> T object(String v, Class<T> type) { try { return v == null || v.isBlank() ? null : mapper.readValue(v, type); } catch (Exception e) { throw new IllegalStateException("A2A JSON deserialization failed", e); } }
    private List<String> list(String v) { try { return v == null || v.isBlank() ? List.of() : mapper.readValue(v, new TypeReference<List<String>>(){}); } catch (Exception e) { return List.of(); } }
    private <E extends Enum<E>> E enumValue(Class<E> c, String v, E d) { try { return v == null ? d : Enum.valueOf(c, v); } catch (Exception e) { return d; } }
    public A2AReconciliationCasePo toPo(A2AReconciliationCase v){A2AReconciliationCasePo p=new A2AReconciliationCasePo();p.setTenantId(v.getTenantId());p.setCaseId(v.getCaseId());p.setRequestId(v.getRequestId());p.setCancellationId(v.getCancellationId());p.setChildTaskId(v.getChildTaskId());p.setDispatchRequestId(v.getDispatchRequestId());p.setResultId(v.getResultId());p.setHandoffSnapshotId(v.getHandoffSnapshotId());p.setCaseType(v.getCaseType());p.setStatus(v.getStatus()==null?null:v.getStatus().name());p.setAuthorityOwner(v.getAuthorityOwner());p.setReasonCode(v.getReasonCode());p.setReason(v.getReason());p.setDiagnosisCode(v.getDiagnosisCode());p.setEvidenceSummary(v.getEvidenceSummary());p.setEvidenceSnapshotHash(v.getEvidenceSnapshotHash());p.setRecommendedAction(v.getRecommendedAction());p.setRepairAction(v.getRepairAction());p.setRequiredPermission(v.getRequiredPermission());p.setImpactSummary(v.getImpactSummary());p.setPlanHash(v.getPlanHash());p.setExpectedResourceVersion(v.getExpectedResourceVersion());p.setAttemptCount(v.getAttemptCount());p.setRepairAttemptNo(v.getRepairAttemptNo());p.setIdempotencyKey(v.getIdempotencyKey());p.setClaimedBy(v.getClaimedBy());p.setClaimTokenHash(v.getClaimTokenHash());p.setClaimUntil(v.getClaimUntil());p.setHeartbeatAt(v.getHeartbeatAt());p.setNextAttemptAt(v.getNextAttemptAt());p.setLastErrorCode(v.getLastErrorCode());p.setLastError(v.getLastError());p.setRepairEvidenceId(v.getRepairEvidenceId());p.setResolvedBy(v.getResolvedBy());p.setResolutionReason(v.getResolutionReason());p.setCreatedAt(v.getCreatedAt());p.setUpdatedAt(v.getUpdatedAt());p.setResolvedAt(v.getResolvedAt());p.setVersion(v.getVersion());return p;}
    public A2AReconciliationCase toDomain(A2AReconciliationCasePo p){A2AReconciliationCase v=new A2AReconciliationCase();v.setTenantId(p.getTenantId());v.setCaseId(p.getCaseId());v.setRequestId(p.getRequestId());v.setCancellationId(p.getCancellationId());v.setChildTaskId(p.getChildTaskId());v.setDispatchRequestId(p.getDispatchRequestId());v.setResultId(p.getResultId());v.setHandoffSnapshotId(p.getHandoffSnapshotId());v.setCaseType(p.getCaseType());v.setStatus(enumValue(A2AReconciliationStatus.class,p.getStatus(),A2AReconciliationStatus.OPEN));v.setAuthorityOwner(p.getAuthorityOwner());v.setReasonCode(p.getReasonCode());v.setReason(p.getReason());v.setDiagnosisCode(p.getDiagnosisCode());v.setEvidenceSummary(p.getEvidenceSummary());v.setEvidenceSnapshotHash(p.getEvidenceSnapshotHash());v.setRecommendedAction(p.getRecommendedAction());v.setRepairAction(p.getRepairAction());v.setRequiredPermission(p.getRequiredPermission());v.setImpactSummary(p.getImpactSummary());v.setPlanHash(p.getPlanHash());v.setExpectedResourceVersion(p.getExpectedResourceVersion());v.setAttemptCount(p.getAttemptCount());v.setRepairAttemptNo(p.getRepairAttemptNo());v.setIdempotencyKey(p.getIdempotencyKey());v.setClaimedBy(p.getClaimedBy());v.setClaimTokenHash(p.getClaimTokenHash());v.setClaimUntil(p.getClaimUntil());v.setHeartbeatAt(p.getHeartbeatAt());v.setNextAttemptAt(p.getNextAttemptAt());v.setLastErrorCode(p.getLastErrorCode());v.setLastError(p.getLastError());v.setRepairEvidenceId(p.getRepairEvidenceId());v.setResolvedBy(p.getResolvedBy());v.setResolutionReason(p.getResolutionReason());v.setCreatedAt(p.getCreatedAt());v.setUpdatedAt(p.getUpdatedAt());v.setResolvedAt(p.getResolvedAt());v.setVersion(p.getVersion());return v;}
    public A2AReconciliationEvidencePo toPo(A2AReconciliationEvidence v){A2AReconciliationEvidencePo p=new A2AReconciliationEvidencePo();p.setTenantId(v.getTenantId());p.setEvidenceId(v.getEvidenceId());p.setCaseId(v.getCaseId());p.setRepairAttemptNo(v.getRepairAttemptNo());p.setEventKey(v.getEventKey());p.setEvidenceType(v.getEvidenceType());p.setEvidenceReference(v.getEvidenceReference());p.setEvidenceHash(v.getEvidenceHash());p.setDecision(v.getDecision());p.setReasonCode(v.getReasonCode());p.setSafeSummary(v.getSafeSummary());p.setActorId(v.getActorId());p.setOccurredAt(v.getOccurredAt());return p;}
    public A2AReconciliationEvidence toDomain(A2AReconciliationEvidencePo p){A2AReconciliationEvidence v=new A2AReconciliationEvidence();v.setTenantId(p.getTenantId());v.setEvidenceId(p.getEvidenceId());v.setCaseId(p.getCaseId());v.setRepairAttemptNo(p.getRepairAttemptNo());v.setEventKey(p.getEventKey());v.setEvidenceType(p.getEvidenceType());v.setEvidenceReference(p.getEvidenceReference());v.setEvidenceHash(p.getEvidenceHash());v.setDecision(p.getDecision());v.setReasonCode(p.getReasonCode());v.setSafeSummary(p.getSafeSummary());v.setActorId(p.getActorId());v.setOccurredAt(p.getOccurredAt());return v;}
    public A2ACutoverStatePo toPo(A2ACutoverState v){A2ACutoverStatePo p=new A2ACutoverStatePo();p.setScopeId(v.getScopeId());p.setStage(v.getStage()==null?A2ACutoverStage.EXPAND.name():v.getStage().name());p.setShadowReadEnabled(v.isShadowReadEnabled());p.setLegacyWriteEnabled(v.isLegacyWriteEnabled());p.setIssueTrackingEnabled(v.isIssueTrackingEnabled());p.setShadowMismatchCount(v.getShadowMismatchCount());p.setMigrationEvidenceReference(v.getMigrationEvidenceReference());p.setRuntimeGateRunId(v.getRuntimeGateRunId());p.setReleaseEvidenceReference(v.getReleaseEvidenceReference());p.setRollbackDeadline(v.getRollbackDeadline());p.setUpdatedAt(v.getUpdatedAt());p.setUpdatedBy(v.getUpdatedBy());p.setVersion(v.getVersion());return p;}
    public A2ACutoverState toDomain(A2ACutoverStatePo p){A2ACutoverState v=new A2ACutoverState();v.setScopeId(p.getScopeId());v.setStage(enumValue(A2ACutoverStage.class,p.getStage(),A2ACutoverStage.EXPAND));v.setShadowReadEnabled(p.isShadowReadEnabled());v.setLegacyWriteEnabled(p.isLegacyWriteEnabled());v.setIssueTrackingEnabled(p.isIssueTrackingEnabled());v.setShadowMismatchCount(p.getShadowMismatchCount());v.setMigrationEvidenceReference(p.getMigrationEvidenceReference());v.setRuntimeGateRunId(p.getRuntimeGateRunId());v.setReleaseEvidenceReference(p.getReleaseEvidenceReference());v.setRollbackDeadline(p.getRollbackDeadline());v.setUpdatedAt(p.getUpdatedAt());v.setUpdatedBy(p.getUpdatedBy());v.setVersion(p.getVersion());return v;}
    public A2ACutoverEvidencePo toPo(A2ACutoverEvidence v){A2ACutoverEvidencePo p=new A2ACutoverEvidencePo();p.setEvidenceId(v.getEvidenceId());p.setScopeId(v.getScopeId());p.setFromStage(v.getFromStage()==null?null:v.getFromStage().name());p.setToStage(v.getToStage()==null?null:v.getToStage().name());p.setEvidenceType(v.getEvidenceType());p.setEvidenceReference(v.getEvidenceReference());p.setEvidenceHash(v.getEvidenceHash());p.setActorId(v.getActorId());p.setOccurredAt(v.getOccurredAt());return p;}
    public A2ACutoverEvidence toDomain(A2ACutoverEvidencePo p){A2ACutoverEvidence v=new A2ACutoverEvidence();v.setEvidenceId(p.getEvidenceId());v.setScopeId(p.getScopeId());v.setFromStage(enumValue(A2ACutoverStage.class,p.getFromStage(),null));v.setToStage(enumValue(A2ACutoverStage.class,p.getToStage(),null));v.setEvidenceType(p.getEvidenceType());v.setEvidenceReference(p.getEvidenceReference());v.setEvidenceHash(p.getEvidenceHash());v.setActorId(p.getActorId());v.setOccurredAt(p.getOccurredAt());return v;}
}
