package com.opensocket.aievent.core.resourceaccess.contract;
/** Stable reason-code catalog used by P4RA-D. */
public final class ResourceDecisionReasonCodes{
 private ResourceDecisionReasonCodes(){}
 public static final String AUTHENTICATION_REQUIRED="AUTHENTICATION_REQUIRED";
 public static final String TENANT_CONTEXT_REQUIRED="TENANT_CONTEXT_REQUIRED";
 public static final String TENANT_CONTEXT_MISMATCH="TENANT_CONTEXT_MISMATCH";
 public static final String RESOURCE_DESCRIPTOR_NOT_FOUND="RESOURCE_DESCRIPTOR_NOT_FOUND";
 public static final String RESOURCE_DESCRIPTOR_STALE="RESOURCE_DESCRIPTOR_STALE";
 public static final String PERMISSION_NOT_GRANTED="PERMISSION_NOT_GRANTED";
 public static final String RESOURCE_SCOPE_NOT_MATCHED="RESOURCE_SCOPE_NOT_MATCHED";
 public static final String RESOURCE_PARTICIPANT_MATCHED="RESOURCE_PARTICIPANT_MATCHED";
 public static final String RESOURCE_OWNER_SCOPE_MATCHED="RESOURCE_OWNER_SCOPE_MATCHED";
 public static final String EXPLICIT_GRANT_MATCHED="EXPLICIT_GRANT_MATCHED";
 public static final String TENANT_ROLE_FALLBACK_MATCHED="TENANT_ROLE_FALLBACK_MATCHED";
 public static final String EXPLICIT_DENY_MATCHED="EXPLICIT_DENY_MATCHED";
 public static final String RESOURCE_QUARANTINED="RESOURCE_QUARANTINED";
 public static final String RESOURCE_LEGAL_HOLD_RESTRICTED="RESOURCE_LEGAL_HOLD_RESTRICTED";
 public static final String RESOURCE_INVESTIGATION_RESTRICTED="RESOURCE_INVESTIGATION_RESTRICTED";
 public static final String RESOURCE_ARCHIVED_READ_ONLY="RESOURCE_ARCHIVED_READ_ONLY";
 public static final String RESOURCE_DELETED="RESOURCE_DELETED";
 public static final String RESOURCE_ORPHANED="RESOURCE_ORPHANED";
 public static final String VISIBILITY_LEVEL_INSUFFICIENT="VISIBILITY_LEVEL_INSUFFICIENT";
 public static final String SENSITIVITY_CLEARANCE_INSUFFICIENT="SENSITIVITY_CLEARANCE_INSUFFICIENT";
 public static final String RESOURCE_SECURITY_EPOCH_STALE="RESOURCE_SECURITY_EPOCH_STALE";
 public static final String STALE_EPOCH_ALLOW_REJECTED="STALE_EPOCH_ALLOW_REJECTED";
 public static final String AUTHORIZATION_ALLOWED="AUTHORIZATION_ALLOWED";
 public static final String AUTHORIZATION_CACHE_HIT="AUTHORIZATION_CACHE_HIT";
 public static final String AUTHORIZATION_ERROR="AUTHORIZATION_ERROR";
 public static final String ATTACHMENT_MALWARE_STATUS_BLOCKED="ATTACHMENT_MALWARE_STATUS_BLOCKED";
 public static final String ATTACHMENT_CONTENT_UNAVAILABLE="ATTACHMENT_CONTENT_UNAVAILABLE";
 public static final String ATTACHMENT_DOWNLOAD_POLICY_DENIED="ATTACHMENT_DOWNLOAD_POLICY_DENIED";
 public static final String ATTACHMENT_DIRECT_URL_FORBIDDEN="ATTACHMENT_DIRECT_URL_FORBIDDEN";
 public static final String EXPORT_FIELD_POLICY_REQUIRED="EXPORT_FIELD_POLICY_REQUIRED";
 public static final String EXPORT_ARTIFACT_COMMIT_DENIED="EXPORT_ARTIFACT_COMMIT_DENIED";
 public static final String BACKGROUND_RESOURCE_AUTHORIZATION_REQUIRED="BACKGROUND_RESOURCE_AUTHORIZATION_REQUIRED";
 public static final String RUNTIME_AUTHORIZATION_LEASE_EXPIRED="RUNTIME_AUTHORIZATION_LEASE_EXPIRED";
 public static final String RUNTIME_MAXIMUM_STALE_WINDOW_EXCEEDED="RUNTIME_MAXIMUM_STALE_WINDOW_EXCEEDED";
 public static final String RUNTIME_LEASE_DECISION_BINDING_MISMATCH="RUNTIME_LEASE_DECISION_BINDING_MISMATCH";
 public static final String RUNTIME_EPOCH_MISMATCH="RUNTIME_EPOCH_MISMATCH";
 public static final String SIMULATION_ONLY="SIMULATION_ONLY";
 public static final String SHADOW_ONLY="SHADOW_ONLY";
    public static final String RUNTIME_LATE_RESULT_QUARANTINED = "RUNTIME_LATE_RESULT_QUARANTINED";
    public static final String SCOPE_SNAPSHOT_REVISION_NOT_ACTIVE = "SCOPE_SNAPSHOT_REVISION_NOT_ACTIVE";
}
