package com.opensocket.aievent.core.resourceaccess.contract;
public enum ScopeType { TENANT, DEPARTMENT, DEPARTMENT_SUBTREE, GROUP, RESOURCE, RESOURCE_TREE, TASK_CHAIN, PARTICIPANT, OWNER, CREATED_BY_ME, ASSIGNED_TO_ME, AUDIT_WINDOW, EXPLICIT_SET }
