package com.opensocket.aievent.core.resourceaccess.persistence;
import com.opensocket.aievent.core.resourceaccess.contract.*;import com.opensocket.aievent.database.persistence.spi.DatabaseRepositoryAdapter;import java.sql.*;import java.util.*;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.transaction.annotation.Transactional;
@DatabaseRepositoryAdapter @ConditionalOnProperty(prefix="resource-access",name={"enabled","export-enabled"},havingValue="true")
public class JdbcResourceExportAuthorizationRepository implements ResourceExportAuthorizationRepositoryPort {private final JdbcTemplate jdbc;public JdbcResourceExportAuthorizationRepository(JdbcTemplate j){jdbc=Objects.requireNonNull(j);}
 @Override @Transactional public ResourceExportAuthorization save(ResourceExportAuthorization a,String principal,String purpose,String idempotency,String correlation){if(!a.principalId().equals(principal))throw new IllegalArgumentException("EXPORT_PRINCIPAL_EVIDENCE_MISMATCH");jdbc.update("insert into resource_export_authorizations(tenant_id,export_authorization_id,resource_type,resource_id,export_format,selected_fields_text,field_set_hash,maximum_rows,read_decision_id,export_decision_id,policy_catalog_version,policy_revision,policy_content_hash,security_epoch_fingerprint,descriptor_hash,runtime_lease_id,fencing_version,principal_id,purpose,idempotency_key,correlation_id,issued_at,expires_at,executable,created_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) on conflict(tenant_id,idempotency_key) do nothing",a.resourceRef().tenantId(),a.exportAuthorizationId(),a.resourceRef().resourceType().name(),a.resourceRef().resourceId(),a.format().name(),encode(a.allowedFields()),a.fieldSetHash(),a.maximumRows(),a.readDecisionId(),a.exportDecisionId(),a.policyVersion().catalogVersion(),a.policyVersion().policyRevision(),a.policyVersion().contentHash(),epoch(a.securityEpoch()),a.descriptorHash(),a.runtimeLeaseId(),a.fencingVersion(),principal,purpose,idempotency,correlation,Timestamp.from(a.issuedAt()),Timestamp.from(a.expiresAt()),a.executable(),Timestamp.from(a.issuedAt()));ResourceExportAuthorization saved=findByIdempotency(a.resourceRef().tenantId(),idempotency).orElseThrow();validateIdempotentReplay(a,saved);return saved;}
 @Override public Optional<ResourceExportAuthorization> find(String tenant,String id){return jdbc.query("select * from resource_export_authorizations where tenant_id=? and export_authorization_id=?",(r,n)->map(r),tenant,id).stream().findFirst();}
 private Optional<ResourceExportAuthorization> findByIdempotency(String tenant,String key){return jdbc.query("select * from resource_export_authorizations where tenant_id=? and idempotency_key=?",(r,n)->map(r),tenant,key).stream().findFirst();}
 @Override public void appendCommit(ExportArtifactCommitResult r,String tenant,String principal,String correlation){jdbc.update("insert into resource_export_artifact_commits(tenant_id,commit_id,export_authorization_id,runtime_lease_id,principal_id,row_count,field_set_hash,artifact_sha256,artifact_size_bytes,accepted,reason_code,correlation_id,committed_at,created_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",tenant,"eac-"+UUID.randomUUID(),r.exportAuthorizationId(),r.runtimeLeaseId(),principal,r.rowCount(),r.fieldSetHash(),r.artifactSha256(),r.artifactSizeBytes(),r.accepted(),r.reasonCode(),correlation,Timestamp.from(r.committedAt()),Timestamp.from(r.committedAt()));}
 private static ResourceExportAuthorization map(ResultSet r)throws SQLException{String[] e=r.getString("security_epoch_fingerprint").split(":",-1);SecurityEpoch epoch=new SecurityEpoch(n(e,0),n(e,1),n(e,2),n(e,3),n(e,4),n(e,5));return new ResourceExportAuthorization(r.getString("export_authorization_id"),new ResourceRef(r.getString("tenant_id"),ResourceType.valueOf(r.getString("resource_type")),r.getString("resource_id")),r.getString("principal_id"),ResourceExportFormat.valueOf(r.getString("export_format")),decode(r.getString("selected_fields_text")),r.getString("field_set_hash"),r.getLong("maximum_rows"),r.getString("read_decision_id"),r.getString("export_decision_id"),new PolicyVersion(r.getLong("policy_catalog_version"),r.getLong("policy_revision"),r.getString("policy_content_hash")),epoch,r.getString("descriptor_hash"),r.getString("runtime_lease_id"),r.getLong("fencing_version"),r.getTimestamp("issued_at").toInstant(),r.getTimestamp("expires_at").toInstant(),r.getBoolean("executable"));}
 private static void validateIdempotentReplay(ResourceExportAuthorization requested,ResourceExportAuthorization saved){if(!requested.resourceRef().equals(saved.resourceRef())||!requested.principalId().equals(saved.principalId())||requested.format()!=saved.format()||!requested.fieldSetHash().equals(saved.fieldSetHash())||requested.maximumRows()!=saved.maximumRows())throw new IllegalStateException("EXPORT_IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD");}
 private static String encode(List<String> v){for(String s:v)if(s.contains("\n")||s.contains("\r"))throw new IllegalArgumentException("Export fields cannot contain line breaks");return String.join("\n",v);}private static List<String> decode(String s){return s==null||s.isBlank()?List.of():List.of(s.split("\\n",-1));}private static String epoch(SecurityEpoch e){return e.globalEpoch()+":"+e.tenantEpoch()+":"+e.principalEpoch()+":"+e.resourceEpoch()+":"+e.policyCatalogVersion()+":"+e.departmentTreeRevision();}private static long n(String[]a,int i){return i<a.length&&!a[i].isBlank()?Long.parseLong(a[i]):0;}
}
