package com.opensocket.aievent.database.persistence.task.po;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.OffsetDateTime;

@Getter
@Setter
@NoArgsConstructor
public class TaskPo {
    private String taskId;
    private String taskKey;
    private String title;
    private String description;
    private String severity;
    private String incidentId;
    private String sourceEventId;
    private String sourceSystem;
    private String eventStage;
    private String originSourceSystem;
    private String targetSystem;
    private String taskType;
    private String taskTypeCode;
    private String status;
    private String priority;
    private String tenantId;
    private String siteId;
    private String plantId;
    private String objectType;
    private String objectId;
    private String eventType;
    private String errorCode;
    private String requestedSkill;
    private String handoffMode;
    private String correlationId;
    private String rootTaskId;
    private String parentTaskId;
    private String sourceTaskId;
    private String requestingTaskId;
    private String requestingAgentId;
    private String a2aPolicyId;
    private int hopCount;
    private String resultAggregationPolicy;
    private String childCancellationPolicy;
    private String childFailurePolicy;
    private String issueSyncPolicy;
    private String issueSyncPolicySource;
    private String issueSyncPolicyInheritanceMode;
    private String issueSyncPolicyInheritedFromTaskId;
    private String createdByType;
    private String createdById;
    private String originPrincipalType;
    private String originPrincipalId;
    private String actorPrincipalType;
    private String actorPrincipalId;
    private String originCredentialId;
    private String originOauthClientId;
    private String originEventId;
    private String originWorkloadSourceSystem;
    private String originCorrelationId;
    private String initialPriority;
    private String initialSeverity;
    private String originDepartmentId;
    private String originGroupId;
    private String originOrganizationSource;
    private String originOrganizationStatus;
    private String originSourceIp;
    private String originApiResource;
    private String authorizationDecisionId;
    private long securityGlobalEpoch;
    private long securityTenantEpoch;
    private long securityPrincipalEpoch;
    private String requestId;
    private String traceId;
    private String authenticationMethod;
    private String workloadPurpose;
    private boolean synthetic;
    private OffsetDateTime provenanceCapturedAt;
    private long version;
    private String creationIdempotencyKey;
    private String ownerDepartmentId;
    private String ownerGroupId;
    private String originScopeStatus;
    private Long originScopeSourceVersion;
    private OffsetDateTime originScopeInheritedAt;
    private String requesterDepartmentId;
    private String requesterGroupId;
    private String requesterDomainId;
    private String executorDepartmentId;
    private String executorGroupId;
    private String executorDomainId;
    private String visibilityPolicy;
    private String sensitivityLevel;
    private String matchedFlowId;
    private String matchedRuleId;
    private String assignedPoolId;
    private String targetPoolId;
    private String classificationStatus;
    private String classificationResultJson;
    private String routingPath;
    private String routingPolicy;
    private String requiredCapabilitiesJson;
    private String createdReason;
    private long occurrenceCountAtCreation;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
    private OffsetDateTime timeoutAt;
    private OffsetDateTime terminalAt;
    private int reassignmentCount;
    private OffsetDateTime nextDispatchAttemptAt;
    private int dispatchAttemptCount;
    private String dispatchRetryReason;
    private String dispatchRecoveryClaimedBy;
    private OffsetDateTime dispatchRecoveryClaimUntil;
    private String lifecycleReason;
    private String failureDomain;
    private String failureCode;
    private OffsetDateTime failureAt;
    private String externalExecutionKey;
    private String taskLifecycle;
    private String taskPhase;
    private String taskOutcome;
    private String taskStateAuthorityVersion;
    private String terminalizationReason;
    private OffsetDateTime terminalizationRequestedAt;
    private String terminalizationActorRef;
    private String outcomeResolverVersion;
    private String cancellationState;
    private String finalizationState;
    private String finalizationCheckpoint;
    private int finalizationAttemptCount;
    private OffsetDateTime finalizationNextAttemptAt;
    private String finalizationClaimedBy;
    private OffsetDateTime finalizationClaimUntil;
    private String finalizationLastErrorCode;
    private String finalizationLastErrorMessage;
    private OffsetDateTime finalizationCompletedAt;
    private String evidenceAvailabilityRequirement;
    public void setReassignmentCount(int reassignmentCount) { this.reassignmentCount = Math.max(0, reassignmentCount); }
    public void setDispatchAttemptCount(int dispatchAttemptCount) { this.dispatchAttemptCount = Math.max(0, dispatchAttemptCount); }
}

