package com.opensocket.aievent.core.integration.identity;
import java.util.*; import java.util.concurrent.ConcurrentHashMap; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.context.annotation.Profile; import org.springframework.stereotype.Repository;
@Repository @Profile("!prod") @ConditionalOnProperty(prefix="integration-identity",name="store",havingValue="MEMORY")
public class InMemoryIntegrationIdentityRepository implements IntegrationIdentityRepository {
 private final Map<String,IntegrationConnection> connections=new ConcurrentHashMap<>();
 private final Map<String,IntegrationPrincipal> principals=new ConcurrentHashMap<>();
 private final Map<String,IntegrationCredentialMetadata> credentials=new ConcurrentHashMap<>();
 private final Map<String,IntegrationProjectMapping> mappings=new ConcurrentHashMap<>();
 private final Map<String,PermissionProbeResult> probes=new ConcurrentHashMap<>();
 private final Map<String,CredentialRotationEvent> rotations=new ConcurrentHashMap<>();
 private final Map<String,IntegrationPrincipalScope> scopes=new ConcurrentHashMap<>();
 private final Map<String,IntegrationSecurityOverride> overrides=new ConcurrentHashMap<>();
 private final Map<String,IntegrationPermissionChangeEvent> permissionChanges=new ConcurrentHashMap<>();
 private final Map<String,IntegrationProviderAuthorizationFailure> authorizationFailures=new ConcurrentHashMap<>();
 private final Map<String,ProviderMetadataSnapshot> metadataSnapshots=new ConcurrentHashMap<>();
 private final Map<String,IntegrationProjectMappingVersion> mappingVersions=new ConcurrentHashMap<>();
 private String k(String t,String id){return t+":"+id;}
 public IntegrationConnection saveConnection(IntegrationConnection v){connections.put(k(v.tenantId(),v.connectionId()),v);return v;} public Optional<IntegrationConnection> findConnection(String t,String id){return Optional.ofNullable(connections.get(k(t,id)));} public List<IntegrationConnection> listConnections(String t,int n){return connections.values().stream().filter(v->t.equals(v.tenantId())).limit(n).toList();} public List<IntegrationConnection> listConnectionsAuthorized(String t,IntegrationResourceScope s,int n){return s.denyAll()?List.of():listConnections(t,10000).stream().filter(v->allowed(s,v.connectionId(),v.ownerDepartmentId(),v.ownerGroupId())).limit(n).toList();}
 public IntegrationPrincipal savePrincipal(IntegrationPrincipal v){principals.put(k(v.tenantId(),v.principalId()),v);return v;} public Optional<IntegrationPrincipal> findPrincipal(String t,String id){return Optional.ofNullable(principals.get(k(t,id)));} public List<IntegrationPrincipal> listPrincipals(String t,String c,int n){return principals.values().stream().filter(v->t.equals(v.tenantId())&&(c==null||c.isBlank()||c.equals(v.connectionId()))).limit(n).toList();} public List<IntegrationPrincipal> listPrincipalsAuthorized(String t,String c,IntegrationResourceScope s,int n){return s.denyAll()?List.of():listPrincipals(t,c,10000).stream().filter(v->allowed(s,v.principalId(),v.ownerDepartmentId(),v.ownerGroupId())).limit(n).toList();}
 public IntegrationCredentialMetadata saveCredential(IntegrationCredentialMetadata v){credentials.put(k(v.tenantId(),v.credentialId()),v);return v;} public Optional<IntegrationCredentialMetadata> findCredential(String t,String id){return Optional.ofNullable(credentials.get(k(t,id)));} public List<IntegrationCredentialMetadata> listCredentials(String t,String p,int n){return credentials.values().stream().filter(v->t.equals(v.tenantId())&&(p==null||p.isBlank()||p.equals(v.principalId()))).sorted(Comparator.comparing(IntegrationCredentialMetadata::createdAt,Comparator.nullsLast(Comparator.reverseOrder()))).limit(n).toList();} public List<IntegrationCredentialMetadata> listCredentialsAuthorized(String t,String p,IntegrationResourceScope s,int n){return s.denyAll()?List.of():listCredentials(t,p,10000).stream().filter(v->findPrincipal(t,v.principalId()).map(pr->allowed(s,v.credentialId(),pr.ownerDepartmentId(),pr.ownerGroupId())).orElse(false)).limit(n).toList();}
 public IntegrationProjectMapping saveMapping(IntegrationProjectMapping v){mappings.put(k(v.tenantId(),v.mappingId()),v);return v;} public Optional<IntegrationProjectMapping> findMapping(String t,String id){return Optional.ofNullable(mappings.get(k(t,id)));} public List<IntegrationProjectMapping> listMappings(String t,String c,int n){return mappings.values().stream().filter(v->t.equals(v.tenantId())&&(c==null||c.isBlank()||c.equals(v.connectionId()))).limit(n).toList();} public List<IntegrationProjectMapping> listMappingsAuthorized(String t,String c,IntegrationResourceScope s,int n){return s.denyAll()?List.of():listMappings(t,c,10000).stream().filter(v->allowed(s,v.mappingId(),v.departmentId(),v.groupId())).limit(n).toList();}
 public List<IntegrationProjectMapping> resolutionCandidates(MappingResolutionRequest r){return mappings.values().stream().filter(v->r.tenantId().equals(v.tenantId())&&v.enabled()&&(r.connectionId()==null||r.connectionId().equals(v.connectionId()))).sorted(Comparator.comparingInt(IntegrationProjectMapping::resolutionPriority)).toList();}
 public PermissionProbeResult saveProbe(PermissionProbeResult v){probes.put(k(v.tenantId(),v.probeId()),v);return v;} public Optional<PermissionProbeResult> latestProbe(String t,String p,String m){return probes.values().stream().filter(v->t.equals(v.tenantId())&&p.equals(v.principalId())&&(m==null||Objects.equals(m,v.mappingId()))).max(Comparator.comparing(PermissionProbeResult::startedAt));}
 public CredentialRotationEvent saveRotationEvent(CredentialRotationEvent v){rotations.put(k(v.tenantId(),v.rotationEventId()),v);return v;} public List<CredentialRotationEvent> listRotationEvents(String t,String p,int n){return rotations.values().stream().filter(v->t.equals(v.tenantId())&&(p==null||p.equals(v.principalId()))).sorted(Comparator.comparing(CredentialRotationEvent::createdAt,Comparator.reverseOrder())).limit(n).toList();}
 public IntegrationPrincipalScope savePrincipalScope(IntegrationPrincipalScope v){scopes.put(k(v.tenantId(),v.principalId()),v);return v;} public Optional<IntegrationPrincipalScope> findPrincipalScope(String t,String p){return Optional.ofNullable(scopes.get(k(t,p)));} public List<IntegrationPrincipalScope> listPrincipalScopes(String t,String c,int n){return scopes.values().stream().filter(v->t.equals(v.tenantId())).filter(v->c==null||c.isBlank()||findPrincipal(t,v.principalId()).map(p->c.equals(p.connectionId())).orElse(false)).limit(n).toList();}
 public IntegrationSecurityOverride saveSecurityOverride(IntegrationSecurityOverride v){overrides.put(k(v.tenantId(),v.overrideId()),v);return v;} public Optional<IntegrationSecurityOverride> findSecurityOverride(String t,String id){return Optional.ofNullable(overrides.get(k(t,id)));} public List<IntegrationSecurityOverride> listSecurityOverrides(String t,String p,String m,int n){return overrides.values().stream().filter(v->t.equals(v.tenantId())&&(p==null||p.equals(v.principalId()))&&(m==null||Objects.equals(m,v.mappingId()))).sorted(Comparator.comparing(IntegrationSecurityOverride::createdAt,Comparator.reverseOrder())).limit(n).toList();}
 public IntegrationPermissionChangeEvent savePermissionChangeEvent(IntegrationPermissionChangeEvent v){permissionChanges.put(k(v.tenantId(),v.changeEventId()),v);return v;} public List<IntegrationPermissionChangeEvent> listPermissionChangeEvents(String t,String p,String m,int n){return permissionChanges.values().stream().filter(v->t.equals(v.tenantId())&&(p==null||p.equals(v.principalId()))&&(m==null||Objects.equals(m,v.mappingId()))).sorted(Comparator.comparing(IntegrationPermissionChangeEvent::detectedAt,Comparator.reverseOrder())).limit(n).toList();}
 public IntegrationProviderAuthorizationFailure saveAuthorizationFailure(IntegrationProviderAuthorizationFailure v){authorizationFailures.put(k(v.tenantId(),v.failureId()),v);return v;} public List<IntegrationProviderAuthorizationFailure> listAuthorizationFailures(String t,String m,int n){return authorizationFailures.values().stream().filter(v->t.equals(v.tenantId())&&(m==null||Objects.equals(m,v.mappingId()))).sorted(Comparator.comparing(IntegrationProviderAuthorizationFailure::occurredAt,Comparator.reverseOrder())).limit(n).toList();}
 public ProviderMetadataSnapshot saveMetadataSnapshot(ProviderMetadataSnapshot v){metadataSnapshots.put(k(v.tenantId(),v.snapshotId()),v);return v;} public Optional<ProviderMetadataSnapshot> findMetadataSnapshot(String t,String id){return Optional.ofNullable(metadataSnapshots.get(k(t,id)));} public Optional<ProviderMetadataSnapshot> latestMetadataSnapshot(String t,String m){return metadataSnapshots.values().stream().filter(v->t.equals(v.tenantId())&&Objects.equals(m,v.mappingId())).max(Comparator.comparing(ProviderMetadataSnapshot::probedAt));} public List<ProviderMetadataSnapshot> listMetadataSnapshots(String t,String m,int n){return metadataSnapshots.values().stream().filter(v->t.equals(v.tenantId())&&(m==null||Objects.equals(m,v.mappingId()))).sorted(Comparator.comparing(ProviderMetadataSnapshot::probedAt).reversed()).limit(n).toList();}
 public IntegrationProjectMappingVersion saveMappingVersion(IntegrationProjectMappingVersion v){mappingVersions.put(k(v.tenantId(),v.mappingId()+":"+v.mappingVersion()),v);return v;} public Optional<IntegrationProjectMappingVersion> findMappingVersion(String t,String m,int v){return Optional.ofNullable(mappingVersions.get(k(t,m+":"+v)));} public List<IntegrationProjectMappingVersion> listMappingVersions(String t,String m,int n){return mappingVersions.values().stream().filter(v->t.equals(v.tenantId())&&m.equals(v.mappingId())).sorted(Comparator.comparingInt(IntegrationProjectMappingVersion::mappingVersion).reversed()).limit(n).toList();}
 public CredentialBlastRadius blastRadius(String t,String id){var c=findCredential(t,id).orElseThrow();var p=findPrincipal(t,c.principalId()).orElseThrow();var projects=mappings.values().stream().filter(v->t.equals(v.tenantId())&&java.util.stream.Stream.of(v.readPrincipalId(),v.createPrincipalId(),v.commentPrincipalId(),v.updatePrincipalId(),v.relationPrincipalId(),v.webhookPrincipalId()).filter(Objects::nonNull).anyMatch(p.principalId()::equals)).map(IntegrationProjectMapping::externalProjectId).distinct().toList();return new CredentialBlastRadius(id,p.principalId(),p.connectionId(),p.ownerDepartmentId(),p.trustZoneId(),projects,0,c.expiresAt(),c.lastUsedAt());}
 private boolean allowed(IntegrationResourceScope s,String id,String d,String g){return !s.excludedResourceIds().contains(id)&&(s.tenantWide()||s.explicitResourceIds().contains(id)||(d!=null&&s.exactDepartmentIds().contains(d))||(g!=null&&s.groupIds().contains(g)));}
 public String mode(){return "MEMORY";}
}
