package com.opensocket.aievent.core.resourceaccess.bridge;
import com.opensocket.aievent.core.iam.security.contract.*;import com.opensocket.aievent.core.issuetracking.background.*;import com.opensocket.aievent.core.resourceaccess.contract.*;import java.time.Instant;import java.util.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.stereotype.Component;
/** Converts configured Issue workers into least-privilege service-authenticated Resource Access requests. */
@Component @ConditionalOnProperty(prefix="resource-access",name={"enabled","background-enabled","runtime-lease-enabled"},havingValue="true")
public final class IssueBackgroundAuthorizationAdapter implements IssueBackgroundAuthorizationPort {
 private final BackgroundResourceAccessGuardPort guard;private final RuntimeAuthorizationLeasePort leases;private final String principalId;
 public IssueBackgroundAuthorizationAdapter(BackgroundResourceAccessGuardPort guard,RuntimeAuthorizationLeasePort leases,@Value("${resource-access.background.issue-worker-principal-id:opendispatch-issue-worker}")String principalId){this.guard=Objects.requireNonNull(guard);this.leases=Objects.requireNonNull(leases);this.principalId=required(principalId,"principalId");}
 @Override public IssueBackgroundExecutionAuthorization authorize(String tenant,String job,String type,String id,String permission,String purpose,String correlation){Instant now=Instant.now();PrincipalRef principal=new PrincipalRef(PrincipalRef.PrincipalType.SYSTEM_SERVICE,principalId);AuthenticationContext authentication=new AuthenticationContext(new SubjectRef(SubjectRef.IdentityType.SYSTEM_SERVICE,principalId),principal,TenantRef.tenant(required(tenant,"tenantId")),Optional.empty(),new AuthenticationAssurance(AuthenticationAssurance.Level.SYSTEM,Set.of("SYSTEM_SERVICE"),now),com.opensocket.aievent.core.iam.security.contract.SecurityEpoch.ZERO,Optional.empty(),now,now.plusSeconds(300));ResourceRef ref=new ResourceRef(tenant,ResourceType.valueOf(required(type,"resourceType")),required(id,"resourceId"));BackgroundJobAuthorization result=guard.authorize(new BackgroundJobAuthorizationCommand(required(job,"jobCode"),authentication,List.of(new BackgroundJobResourceRequest(new ResourceAction(required(permission,"permissionCode"),ResourceAction.ActionKind.EXECUTE,true),ref,VisibilityLevel.METADATA)),required(purpose,"purpose"),required(correlation,"correlationId")));if(!result.executable())throw new IllegalStateException("BACKGROUND_RESOURCE_AUTHORIZATION_REQUIRED");return convert(tenant,result);}
 @Override public IssueBackgroundExecutionAuthorization checkpoint(IssueBackgroundExecutionAuthorization authorization,String operationPhase,String correlation){OperationPhase phase=checkpointPhase(operationPhase);List<IssueBackgroundLeaseRef> checked=new ArrayList<>();for(IssueBackgroundLeaseRef ref:authorization.leases()){RuntimeAuthorizationLease lease=leases.check(new RuntimeAuthorizationCheckpoint(authorization.tenantId(),ref.leaseId(),phase,ref.fencingVersion(),required(correlation,"correlationId")));if(lease.status()!=RuntimeLeaseStatus.ACTIVE)throw new IllegalStateException("BACKGROUND_RUNTIME_AUTHORIZATION_"+lease.status());checked.add(new IssueBackgroundLeaseRef(lease.leaseId(),lease.fencingVersion()));}return new IssueBackgroundExecutionAuthorization(authorization.tenantId(),authorization.authorizationId(),checked);}
 @Override public void complete(IssueBackgroundExecutionAuthorization authorization,String correlation){for(IssueBackgroundLeaseRef ref:authorization.leases())leases.complete(authorization.tenantId(),ref.leaseId(),required(correlation,"correlationId"));}
 @Override public void revoke(IssueBackgroundExecutionAuthorization authorization,String reason,String correlation){for(IssueBackgroundLeaseRef ref:authorization.leases()){try{leases.revoke(authorization.tenantId(),ref.leaseId(),required(reason,"reasonCode"),required(correlation,"correlationId"));}catch(RuntimeException ignored){}}}
 private static OperationPhase checkpointPhase(String value){OperationPhase phase=OperationPhase.valueOf(required(value,"operationPhase"));if(phase!=OperationPhase.BEFORE_SIDE_EFFECT&&phase!=OperationPhase.BEFORE_RESULT_COMMIT)throw new IllegalArgumentException("Issue background workers only support BEFORE_SIDE_EFFECT or BEFORE_RESULT_COMMIT checkpoints");return phase;}
 private static IssueBackgroundExecutionAuthorization convert(String tenant,BackgroundJobAuthorization value){return new IssueBackgroundExecutionAuthorization(tenant,value.authorizationId(),value.runtimeLeases().stream().map(l->new IssueBackgroundLeaseRef(l.leaseId(),l.fencingVersion())).toList());}
 private static String required(String v,String f){if(v==null||v.isBlank())throw new IllegalArgumentException(f+" is required");return v.trim();}
}
