package com.opensocket.aievent.core.resourceaccess.bridge;

import com.opensocket.aievent.core.integration.identity.*;
import com.opensocket.aievent.core.integration.issue.*;
import com.opensocket.aievent.core.issue.*;
import com.opensocket.aievent.core.issuetracking.relay.*;
import com.opensocket.aievent.core.resourceaccess.contract.*;
import com.opensocket.aievent.core.task.*;
import java.time.Instant; import java.util.*;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.stereotype.Component;

/** Resolves Issue projection resources through Task/Issue authorities; opaque child IDs are never guessed. */
@Component
@ConditionalOnProperty(prefix="resource-access",name="enabled",havingValue="true")
public final class IssueResourceDescriptorResolver implements ResourceDescriptorResolverPort,ResourceParticipantResolverPort {
 private final TaskIssueLinkRepository links; private final IssueSyncRepository sync; private final IntegrationIdentityRepository identities;
 private final RelayGovernanceRepository relays; private final TaskRepository tasks;
 public IssueResourceDescriptorResolver(TaskIssueLinkRepository links,IssueSyncRepository sync,IntegrationIdentityRepository identities,RelayGovernanceRepository relays,TaskRepository tasks){this.links=links;this.sync=sync;this.identities=identities;this.relays=relays;this.tasks=tasks;}
 @Override public boolean supports(ResourceType t){return EnumSet.of(ResourceType.TASK_ISSUE_LINK,ResourceType.ISSUE_CONTEXT_SNAPSHOT,ResourceType.ISSUE_CONFLICT,ResourceType.ISSUE_DEAD_LETTER,ResourceType.ISSUE_TOPOLOGY).contains(t);}
 @Override public boolean supportsParticipants(ResourceType t){return supports(t);}
 @Override public Optional<ResourceDescriptor> resolve(ResourceRef ref,DescriptorResolutionContext c){if(!supports(ref.resourceType()))return Optional.empty();return switch(ref.resourceType()){
  case TASK_ISSUE_LINK->links.findByTenantAndLinkId(ref.tenantId(),ref.resourceId()).flatMap(v->fromIssueLink(ref,v,c));
  case ISSUE_CONTEXT_SNAPSHOT->identities.findMetadataSnapshot(ref.tenantId(),ref.resourceId()).flatMap(v->fromMapping(ref,v.mappingId(),"snapshot-"+v.snapshotId(),v.metadataVersion(),c));
  case ISSUE_CONFLICT->sync.findConflict(ref.tenantId(),ref.resourceId()).flatMap(v->fromTaskOrLink(ref,v.taskId(),v.taskIssueLinkId(),"conflict-"+v.conflictId(),revision(v.detectedAt()),c));
  case ISSUE_DEAD_LETTER->sync.findDeadLetter(ref.tenantId(),ref.resourceId()).flatMap(v->fromTaskOrLink(ref,v.taskId(),v.taskIssueLinkId(),"dead-letter-"+v.deadLetterId(),revision(v.openedAt()),c));
  case ISSUE_TOPOLOGY->relays.findTopology(ref.tenantId(),ref.resourceId()).flatMap(v->relays.findRelation(ref.tenantId(),v.canonicalRelationId()).flatMap(r->fromTask(ref,r.parentTaskId(),"topology-"+v.topologyId(),v.version(),c)));
  default->Optional.empty();};}
 @Override public Optional<ParticipantProjectionSnapshot> resolveParticipants(ResourceRef ref,DescriptorResolutionContext c){Optional<ResourceDescriptor>d=resolve(ref,c);if(d.isEmpty())return Optional.empty();List<ResourceParticipantProjection> v=new ArrayList<>();OwnershipDescriptor o=d.get().ownership();add(v,ref,ResourceParticipantType.DEPARTMENT,o.ownerDepartmentId(),ResourceParticipantRole.OWNER,d.get().visibility().maximumVisibility(),d.get().resourceVersion(),c.requestedAt());add(v,ref,ResourceParticipantType.GROUP,o.ownerGroupId(),ResourceParticipantRole.OWNER,d.get().visibility().maximumVisibility(),d.get().resourceVersion(),c.requestedAt());if(ref.resourceType()==ResourceType.TASK_ISSUE_LINK){links.findByTenantAndLinkId(ref.tenantId(),ref.resourceId()).ifPresent(link->tasks.findByTenantAndId(ref.tenantId(),link.getTaskId()).ifPresent(t->{add(v,ref,ResourceParticipantType.DEPARTMENT,t.getRequesterDepartmentId(),ResourceParticipantRole.REQUESTER,VisibilityLevel.SENSITIVE,t.getVersion(),c.requestedAt());add(v,ref,ResourceParticipantType.GROUP,t.getRequesterGroupId(),ResourceParticipantRole.REQUESTER,VisibilityLevel.SENSITIVE,t.getVersion(),c.requestedAt());add(v,ref,ResourceParticipantType.DEPARTMENT,t.getExecutorDepartmentId(),ResourceParticipantRole.EXECUTOR,VisibilityLevel.SENSITIVE,t.getVersion(),c.requestedAt());add(v,ref,ResourceParticipantType.GROUP,t.getExecutorGroupId(),ResourceParticipantRole.EXECUTOR,VisibilityLevel.SENSITIVE,t.getVersion(),c.requestedAt());}));}return Optional.of(new ParticipantProjectionSnapshot(ref,v.isEmpty()?0:BridgeDescriptorSupport.revisionToken(v.toString()),v,DescriptorAuthority.ISSUE_TRACKING,"",c.requestedAt()));}
 private Optional<ResourceDescriptor> fromTaskOrLink(ResourceRef ref,String taskId,String linkId,String key,long version,DescriptorResolutionContext c){if(linkId!=null&&!linkId.isBlank())return links.findByTenantAndLinkId(ref.tenantId(),linkId).flatMap(v->fromIssueLink(ref,v,c));if(taskId!=null&&!taskId.isBlank())return fromTask(ref,taskId,key,version,c);return Optional.empty();}
 private Optional<ResourceDescriptor> fromIssueLink(ResourceRef ref,TaskIssueLink link,DescriptorResolutionContext c){
  if(link==null||!"RESOLVED".equalsIgnoreCase(link.getScopeStatus()))return Optional.empty();
  OwnershipDescriptor o=new OwnershipDescriptor(BridgeDescriptorSupport.owner(link.getOwnerDepartmentId()),BridgeDescriptorSupport.owner(link.getOwnerGroupId()),"","",BridgeDescriptorSupport.owner(link.getRequesterDepartmentId()),BridgeDescriptorSupport.owner(link.getExecutorDepartmentId()),link.getResourceVersion());
  ResourceRef parent=new ResourceRef(ref.tenantId(),ResourceType.TASK,link.getTaskId());
  ResourceRef root=tasks.findByTenantAndId(ref.tenantId(),link.getTaskId()).map(t->new ResourceRef(ref.tenantId(),ResourceType.TASK,t.getRootTaskId()==null?t.getTaskId():t.getRootTaskId())).orElse(parent);
  VisibilityDescriptor visibility=BridgeDescriptorSupport.visibility(SensitivityLevel.CONFIDENTIAL,VisibilityLevel.SENSITIVE,"RS5_ISSUE_SCOPE_SNAPSHOT",link.getResourceVersion());
  String canonical=String.join("|",ref.toString(),link.getLinkId(),String.valueOf(link.getScopeSourceType()),String.valueOf(link.getScopeSourceId()),String.valueOf(link.getScopeSourceVersion()),o.toString(),parent.toString(),root.toString());
  return Optional.of(new ResourceDescriptor(ref,"issue-"+link.getLinkId(),o,parent,root,visibility,ResourceSecurityState.NORMAL,0,link.getResourceVersion(),DescriptorAuthority.ISSUE_TRACKING,BridgeDescriptorSupport.hash(ref,canonical),c.requestedAt()));
 }
 private Optional<ResourceDescriptor> fromMapping(ResourceRef ref,String mappingId,String key,long version,DescriptorResolutionContext c){return identities.findMapping(ref.tenantId(),mappingId).map(m->{OwnershipDescriptor o=new OwnershipDescriptor(BridgeDescriptorSupport.owner(m.departmentId()),BridgeDescriptorSupport.owner(m.groupId()),"","","",BridgeDescriptorSupport.owner(m.departmentId()),Math.max(version,m.version()));ResourceRef parent=new ResourceRef(ref.tenantId(),ResourceType.ISSUE_PROJECT_MAPPING,m.mappingId());VisibilityDescriptor visibility=BridgeDescriptorSupport.visibility(SensitivityLevel.CONFIDENTIAL,VisibilityLevel.SENSITIVE,"ISSUE_CONTEXT_SNAPSHOT",Math.max(version,m.mappingVersion()));return descriptor(ref,key,o,parent,parent,visibility,ResourceSecurityState.NORMAL,Math.max(version,m.version()),c.requestedAt());});}
 private Optional<ResourceDescriptor> fromTask(ResourceRef ref,String taskId,String key,long version,DescriptorResolutionContext c){return tasks.findByTenantAndId(ref.tenantId(),taskId).map(t->{OwnershipDescriptor o=new OwnershipDescriptor(BridgeDescriptorSupport.owner(t.getOwnerDepartmentId()),BridgeDescriptorSupport.owner(t.getOwnerGroupId()),"","",BridgeDescriptorSupport.owner(t.getRequesterDepartmentId()),BridgeDescriptorSupport.owner(t.getExecutorDepartmentId()),Math.max(version,t.getVersion()));ResourceRef parent=new ResourceRef(ref.tenantId(),ResourceType.TASK,t.getTaskId());String root=t.getRootTaskId()==null?t.getTaskId():t.getRootTaskId();ResourceRef rootRef=new ResourceRef(ref.tenantId(),ResourceType.TASK,root);SensitivityLevel sensitivity=BridgeDescriptorSupport.sensitivity(t.getSensitivityLevel(),SensitivityLevel.CONFIDENTIAL);VisibilityLevel max=ref.resourceType()==ResourceType.ISSUE_DEAD_LETTER?VisibilityLevel.METADATA:VisibilityLevel.SENSITIVE;VisibilityDescriptor visibility=BridgeDescriptorSupport.visibility(sensitivity,max,ref.resourceType().name(),Math.max(version,t.getVersion()));return descriptor(ref,key,o,parent,rootRef,visibility,ResourceSecurityState.NORMAL,Math.max(version,t.getVersion()),c.requestedAt());});}
 private ResourceDescriptor descriptor(ResourceRef ref,String key,OwnershipDescriptor o,ResourceRef parent,ResourceRef root,VisibilityDescriptor v,ResourceSecurityState state,long version,Instant at){String canonical=String.join("|",ref.toString(),key,o.toString(),String.valueOf(parent),String.valueOf(root),v.toString(),state.name(),String.valueOf(version));return new ResourceDescriptor(ref,key,o,parent,root,v,state,0,version,DescriptorAuthority.ISSUE_TRACKING,BridgeDescriptorSupport.hash(ref,canonical),at);}
 private static long revision(java.time.OffsetDateTime at){return at==null?1:Math.max(1,at.toInstant().toEpochMilli());}
 private void add(List<ResourceParticipantProjection> out,ResourceRef ref,ResourceParticipantType type,String id,ResourceParticipantRole role,VisibilityLevel visibility,long version,Instant at){if(id==null||id.isBlank())return;out.add(new ResourceParticipantProjection(BridgeDescriptorSupport.participantId(ref,type,id,role),ref,type,id,role,visibility,role==ResourceParticipantRole.EXECUTOR||role==ResourceParticipantRole.REQUESTER?List.of("integration.issue.link.read","integration.issue.link.update"):List.of("integration.issue.link.read"),at,null,DescriptorAuthority.ISSUE_TRACKING,version,ResourceParticipantStatus.ACTIVE));}
}
