package com.opensocket.aievent.core.issuetracking.application.change;
import java.time.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.opensocket.aievent.core.issuetracking.change.*; import com.opensocket.aievent.core.issuetracking.core.ExternalSyncMarker; import com.opensocket.aievent.core.issuetracking.identity.ProviderExecutionAuthorizationRef;
@Service public class BidirectionalRelationSyncService {
 private final ExternalChangeGovernanceRepository repository; private final ExternalChangeProviderGateway provider; private final OpenDispatchCollaborationPort upstream;
 public BidirectionalRelationSyncService(ExternalChangeGovernanceRepository repository,ExternalChangeProviderGateway provider,OpenDispatchCollaborationPort upstream){this.repository=repository;this.provider=provider;this.upstream=upstream;}
 @Transactional public ExternalRelationSync project(String tenantId,String connectionId,String mappingId,String projectId,String sourceIssueId,String targetIssueId,String sourceLinkId,String targetLinkId,String relationType,String idempotencyKey,String correlationId){return project(tenantId,connectionId,mappingId,projectId,sourceIssueId,targetIssueId,sourceLinkId,targetLinkId,relationType,idempotencyKey,correlationId,null);}
 @Transactional public ExternalRelationSync project(String tenantId,String connectionId,String mappingId,String projectId,String sourceIssueId,String targetIssueId,String sourceLinkId,String targetLinkId,String relationType,String idempotencyKey,String correlationId,ProviderExecutionAuthorizationRef executionAuthorization){Optional<ExternalRelationSync> existing=repository.findRelationByIdempotency(tenantId,sourceIssueId,targetIssueId,relationType,ExternalSyncDirection.OPENDISPATCH_TO_PROVIDER);if(existing.isPresent())return existing.get();String marker=ExternalSyncMarker.create(tenantId,connectionId,"LINK",sourceIssueId+":"+targetIssueId+":"+relationType);OffsetDateTime now=now();ExternalRelationSync pending=new ExternalRelationSync(tenantId,"relation-sync-"+UUID.randomUUID(),connectionId,mappingId,projectId,sourceIssueId,targetIssueId,sourceLinkId,targetLinkId,relationType,ExternalSyncDirection.OPENDISPATCH_TO_PROVIDER,marker,"",ExternalSyncStatus.IN_PROGRESS,0,"","",1,now,now,correlationId);repository.saveRelationSync(pending);ProviderSyncResult result=provider.createRelation(new ProviderRelationSyncCommand(tenantId,connectionId,mappingId,projectId,sourceIssueId,targetIssueId,relationType,marker,idempotencyKey,correlationId,executionAuthorization));ExternalSyncStatus status=result.success()?ExternalSyncStatus.SYNCED:result.retryable()?ExternalSyncStatus.RETRY_WAITING:ExternalSyncStatus.FAILED_PERMANENT;return repository.saveRelationSync(copy(pending,result.providerObjectId(),status,result.success()?0:1,result.reasonCode(),result.safeMessage(),2));}
 @Transactional public ExternalRelationSync acceptProvider(String tenantId,String connectionId,String mappingId,String projectId,String sourceIssueId,String targetIssueId,String sourceLinkId,String targetLinkId,String relationType,String providerRelationId,String marker,String correlationId){Optional<ExternalRelationSync> existing=repository.findRelationByIdempotency(tenantId,sourceIssueId,targetIssueId,relationType,ExternalSyncDirection.PROVIDER_TO_OPENDISPATCH);if(existing.isPresent())return existing.get();OffsetDateTime now=now();String identity=marker==null||marker.isBlank()?"provider-link:"+sourceIssueId+":"+targetIssueId+":"+relationType:marker.trim();ExternalRelationSync received=new ExternalRelationSync(tenantId,"relation-sync-"+UUID.randomUUID(),connectionId,mappingId,projectId,sourceIssueId,targetIssueId,sourceLinkId,targetLinkId,relationType,ExternalSyncDirection.PROVIDER_TO_OPENDISPATCH,identity,providerRelationId,ExternalSyncStatus.RECEIVED,0,"","",1,now,now,correlationId);if(ExternalSyncMarker.isOpenDispatchMarker(marker)){return repository.saveRelationSync(copy(received,providerRelationId,ExternalSyncStatus.LOOP_SUPPRESSED,0,"LOOP_MARKER_MATCHED","Provider relation originated from OpenDispatch.",2));}repository.saveRelationSync(received);OpenDispatchCollaborationResult result=upstream.applyProviderRelation(new ProviderRelationSyncCommand(tenantId,connectionId,mappingId,projectId,sourceIssueId,targetIssueId,relationType,identity,"provider-link:"+providerRelationId,correlationId));ExternalSyncStatus status=result.accepted()?ExternalSyncStatus.SYNCED:result.retryable()?ExternalSyncStatus.RETRY_WAITING:ExternalSyncStatus.WAIT_HUMAN;return repository.saveRelationSync(copy(received,providerRelationId,status,result.accepted()?0:1,result.reasonCode(),result.safeMessage(),2));}
 public List<ExternalRelationSync> list(String tenantId,ExternalSyncStatus status,int limit){return repository.listRelationSync(tenantId,status,Math.max(1,Math.min(limit,1000)));}
 private ExternalRelationSync copy(ExternalRelationSync r,String providerId,ExternalSyncStatus status,int retry,String code,String message,long version){return new ExternalRelationSync(r.tenantId(),r.syncId(),r.connectionId(),r.projectMappingId(),r.externalProjectId(),r.sourceExternalIssueId(),r.targetExternalIssueId(),r.sourceTaskIssueLinkId(),r.targetTaskIssueLinkId(),r.relationType(),r.direction(),r.sourceMarker(),providerId==null?r.providerRelationId():providerId,status,retry,code,message,version,r.createdAt(),now(),r.correlationId());} private OffsetDateTime now(){return OffsetDateTime.now(ZoneOffset.UTC);}
}
