package com.opensocket.aievent.core.issuetracking.application.change;
import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.*; import java.util.*; import java.util.HexFormat; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.opensocket.aievent.core.issuetracking.change.*; import com.opensocket.aievent.core.issuetracking.core.*; import com.opensocket.aievent.core.issuetracking.identity.ProviderExecutionAuthorizationRef;
@Service public class BidirectionalCommentSyncService {
 private final ExternalChangeGovernanceRepository repository; private final ExternalChangeProviderGateway provider; private final OpenDispatchCollaborationPort upstream;
 public BidirectionalCommentSyncService(ExternalChangeGovernanceRepository repository,ExternalChangeProviderGateway provider,OpenDispatchCollaborationPort upstream){this.repository=repository;this.provider=provider;this.upstream=upstream;}
 @Transactional public ExternalCommentSync project(String tenantId,String connectionId,String mappingId,String projectId,String issueId,String linkId,String sourceCommentId,String body,String idempotencyKey,String correlationId){return project(tenantId,connectionId,mappingId,projectId,issueId,linkId,sourceCommentId,body,idempotencyKey,correlationId,null);}
 @Transactional public ExternalCommentSync project(String tenantId,String connectionId,String mappingId,String projectId,String issueId,String linkId,String sourceCommentId,String body,String idempotencyKey,String correlationId,ProviderExecutionAuthorizationRef executionAuthorization){
  Optional<ExternalCommentSync> existing=repository.findCommentByIdempotency(tenantId,sourceCommentId,ExternalSyncDirection.OPENDISPATCH_TO_PROVIDER);if(existing.isPresent())return existing.get();String safe=ExternalCommentSanitizer.sanitize(body);String marker=ExternalSyncMarker.create(tenantId,connectionId,"COMMENT",sourceCommentId);OffsetDateTime now=now();ExternalCommentSync pending=new ExternalCommentSync(tenantId,"comment-sync-"+UUID.randomUUID(),connectionId,mappingId,projectId,issueId,linkId,sourceCommentId,"",ExternalSyncDirection.OPENDISPATCH_TO_PROVIDER,marker,sha(safe),ExternalCommentSanitizer.preview(safe),ExternalSyncStatus.IN_PROGRESS,0,"","",1,now,now,correlationId);repository.saveCommentSync(pending);
  ProviderSyncResult result=provider.appendComment(new ProviderCommentSyncCommand(tenantId,connectionId,mappingId,projectId,issueId,sourceCommentId,safe+"\n\n"+ExternalSyncMarker.bodyMarker(marker),marker,idempotencyKey,correlationId,executionAuthorization));ExternalSyncStatus status=result.success()?ExternalSyncStatus.SYNCED:result.retryable()?ExternalSyncStatus.RETRY_WAITING:ExternalSyncStatus.FAILED_PERMANENT;ExternalCommentSync done=copy(pending,result.providerObjectId(),status,result.success()?0:1,result.reasonCode(),result.safeMessage(),2);return repository.saveCommentSync(done);
 }
 @Transactional public ExternalCommentSync acceptProvider(String tenantId,String connectionId,String mappingId,String projectId,String issueId,String linkId,String providerCommentId,String body,String marker,String correlationId){
  String safe=ExternalCommentSanitizer.sanitize(body);String detected=marker==null||marker.isBlank()?ExternalSyncMarker.extract(safe):marker.trim();String identity=providerCommentId==null||providerCommentId.isBlank()?sha(safe):providerCommentId.trim();Optional<ExternalCommentSync> existing=repository.findCommentByIdempotency(tenantId,identity,ExternalSyncDirection.PROVIDER_TO_OPENDISPATCH);if(existing.isPresent())return existing.get();OffsetDateTime now=now();String storedMarker=detected.isBlank()?"provider-comment:"+sha(connectionId+"\n"+identity):detected;ExternalCommentSync received=new ExternalCommentSync(tenantId,"comment-sync-"+UUID.randomUUID(),connectionId,mappingId,projectId,issueId,linkId,identity,providerCommentId,ExternalSyncDirection.PROVIDER_TO_OPENDISPATCH,storedMarker,sha(safe),ExternalCommentSanitizer.preview(safe),ExternalSyncStatus.RECEIVED,0,"","",1,now,now,correlationId);
  if(ExternalSyncMarker.isOpenDispatchMarker(detected)){return repository.saveCommentSync(copy(received,providerCommentId,ExternalSyncStatus.LOOP_SUPPRESSED,0,"LOOP_MARKER_MATCHED","Provider comment originated from OpenDispatch.",2));}
  repository.saveCommentSync(received);ProviderCommentSyncCommand command=new ProviderCommentSyncCommand(tenantId,connectionId,mappingId,projectId,issueId,identity,safe,storedMarker,"provider-comment:"+identity,correlationId);OpenDispatchCollaborationResult result=upstream.applyProviderComment(command);ExternalSyncStatus status=result.accepted()?ExternalSyncStatus.SYNCED:result.retryable()?ExternalSyncStatus.RETRY_WAITING:ExternalSyncStatus.WAIT_HUMAN;return repository.saveCommentSync(copy(received,providerCommentId,status,result.accepted()?0:1,result.reasonCode(),result.safeMessage(),2));
 }
 public List<ExternalCommentSync> list(String tenantId,ExternalSyncStatus status,int limit){return repository.listCommentSync(tenantId,status,Math.max(1,Math.min(limit,1000)));}
 private ExternalCommentSync copy(ExternalCommentSync c,String providerId,ExternalSyncStatus s,int retry,String code,String message,long version){return new ExternalCommentSync(c.tenantId(),c.syncId(),c.connectionId(),c.projectMappingId(),c.externalProjectId(),c.externalIssueId(),c.taskIssueLinkId(),c.sourceCommentId(),providerId==null?c.providerCommentId():providerId,c.direction(),c.sourceMarker(),c.bodyHash(),c.bodyPreview(),s,retry,code,message,version,c.createdAt(),now(),c.correlationId());}
 private String sha(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}} private OffsetDateTime now(){return OffsetDateTime.now(ZoneOffset.UTC);}
}
