package com.opensocket.aievent.core.issuetracking.application.change;
import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Propagation; import org.springframework.transaction.annotation.Transactional; import tools.jackson.databind.ObjectMapper;
import com.opensocket.aievent.core.issuetracking.change.*;
@Service public class ExternalChangeIngestionService {
 private final ExternalChangePolicyService policies; private final BidirectionalCommentSyncService comments; private final BidirectionalRelationSyncService relations; private final ProviderActionCandidateService candidates; private final ObjectMapper json;
 public ExternalChangeIngestionService(ExternalChangePolicyService policies,BidirectionalCommentSyncService comments,BidirectionalRelationSyncService relations,ProviderActionCandidateService candidates,ObjectMapper json){this.policies=policies;this.comments=comments;this.relations=relations;this.candidates=candidates;this.json=json;}
 @SuppressWarnings("unchecked") @Transactional(propagation=Propagation.REQUIRES_NEW) public ExternalChangeIngestionResult ingest(ExternalChangeIngestionCommand command){Map<String,Object> document=parse(command.normalizedObservationJson());ExternalChangeResourceType resource=resource(command.eventType());String fieldPath=fieldPath(resource);ExternalChangeEvaluationContext context=new ExternalChangeEvaluationContext(command.tenantId(),command.connectionId(),command.projectMappingId(),command.externalProjectId(),command.externalIssueId(),text(document,"issueType"),resource,fieldPath,ExternalChangeDirection.PROVIDER_TO_OPENDISPATCH,command.eventType(),command.providerIdentityHash(),"");ExternalChangeDecision decision=policies.evaluate(context);
  if(decision.action()==ExternalChangeDecisionAction.IGNORE||decision.action()==ExternalChangeDecisionAction.REJECT||decision.action()==ExternalChangeDecisionAction.CREATE_CONFLICT)return new ExternalChangeIngestionResult(decision,"","","",decision.reasonCode());
  if(resource==ExternalChangeResourceType.COMMENT&&decision.action()==ExternalChangeDecisionAction.ACCEPT){Map<String,Object> comment=map(document.get("comment"));String id=first(text(comment,"id"),text(document,"commentId"),"provider-comment-"+UUID.randomUUID());String body=first(text(comment,"body"),text(document,"commentBody"));String marker=first(text(comment,"sourceMarker"),text(document,"sourceMarker"));ExternalCommentSync sync=comments.acceptProvider(command.tenantId(),command.connectionId(),command.projectMappingId(),command.externalProjectId(),command.externalIssueId(),command.taskIssueLinkId(),id,required(body,"comment body"),marker,command.correlationId());return new ExternalChangeIngestionResult(decision,sync.syncId(),"","",sync.status().name());}
  if(resource==ExternalChangeResourceType.LINK&&decision.action()==ExternalChangeDecisionAction.ACCEPT){Map<String,Object> link=map(document.get("link"));String target=first(text(link,"targetIssueId"),text(document,"targetExternalIssueId"));String type=first(text(link,"relationType"),text(document,"relationType"),"RELATES");String providerId=first(text(link,"id"),text(document,"providerRelationId"),"");String marker=first(text(link,"sourceMarker"),text(document,"sourceMarker"));ExternalRelationSync sync=relations.acceptProvider(command.tenantId(),command.connectionId(),command.projectMappingId(),command.externalProjectId(),command.externalIssueId(),required(target,"targetExternalIssueId"),command.taskIssueLinkId(),"",type,providerId,marker,command.correlationId());return new ExternalChangeIngestionResult(decision,"",sync.syncId(),"",sync.status().name());}
  ProviderActionCandidateType type=candidateType(resource,command.eventType());String requestJson=command.normalizedObservationJson();ProviderActionCandidate candidate=candidates.create(command.tenantId(),command.conflictId(),command.observationId(),command.connectionId(),command.externalProjectId(),command.externalIssueId(),type,decision.riskLevel(),requestJson,command.providerIdentityHash(),decision.requiresReauthentication(),decision.requiresApproval(),"provider-action:"+command.connectionId()+":"+command.observationId()+":"+type,command.correlationId());return new ExternalChangeIngestionResult(decision,"","",candidate.candidateId(),candidate.status().name());
 }
 private ExternalChangeResourceType resource(String event){String e=event==null?"":event.toUpperCase(Locale.ROOT);if(e.contains("COMMENT"))return ExternalChangeResourceType.COMMENT;if(e.contains("LINK")||e.contains("RELATION"))return ExternalChangeResourceType.LINK;if(e.contains("ASSIGNEE"))return ExternalChangeResourceType.ASSIGNEE;if(e.contains("PRIORITY"))return ExternalChangeResourceType.PRIORITY;if(e.contains("APPROV"))return ExternalChangeResourceType.APPROVAL;if(e.contains("DELETE"))return ExternalChangeResourceType.ISSUE_DELETE;if(e.contains("PROJECT")&&e.contains("MOVE"))return ExternalChangeResourceType.PROJECT_MOVE;if(e.contains("STATUS")||e.contains("CLOSE")||e.contains("CANCEL"))return ExternalChangeResourceType.STATUS;return ExternalChangeResourceType.ISSUE_FIELD;}
 private ProviderActionCandidateType candidateType(ExternalChangeResourceType r,String event){String e=event==null?"":event.toUpperCase(Locale.ROOT);return switch(r){case STATUS->e.contains("CLOSE")?ProviderActionCandidateType.CLOSE_TASK:e.contains("CANCEL")?ProviderActionCandidateType.CANCEL_TASK:ProviderActionCandidateType.CHANGE_STATUS;case APPROVAL->e.contains("REJECT")?ProviderActionCandidateType.REJECT_TASK:ProviderActionCandidateType.APPROVE_TASK;case PRIORITY->ProviderActionCandidateType.CHANGE_PRIORITY;case ASSIGNEE->ProviderActionCandidateType.CHANGE_ASSIGNEE;case ISSUE_DELETE->ProviderActionCandidateType.DELETE_EXTERNAL_ISSUE;case PROJECT_MOVE->ProviderActionCandidateType.MOVE_EXTERNAL_PROJECT;default->ProviderActionCandidateType.APPLY_FIELD_UPDATE;};}
 private String fieldPath(ExternalChangeResourceType r){return switch(r){case STATUS->"/status";case ASSIGNEE->"/assignee";case PRIORITY->"/priority";case APPROVAL->"/approval";case COMMENT->"/comment";case LINK->"/link";default->"/";};}
 private Map<String,Object> parse(String value){try{return json.readValue(value,Map.class);}catch(Exception e){throw new IllegalArgumentException("NORMALIZED_OBSERVATION_JSON_INVALID");}} private Map<String,Object> map(Object value){return value instanceof Map<?,?> m?(Map<String,Object>)m:Map.of();} private String text(Map<String,Object> m,String key){Object v=m.get(key);return v==null?"":String.valueOf(v).trim();} private String first(String...values){for(String v:values)if(v!=null&&!v.isBlank())return v.trim();return "";} private String required(String v,String n){if(v==null||v.isBlank())throw new IllegalArgumentException(n+" is required");return v.trim();}
}
