package com.opensocket.aievent.core.issuetracking.application.change;
import java.util.*; import java.util.concurrent.ConcurrentHashMap; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.context.annotation.Profile; import org.springframework.stereotype.Repository; import com.opensocket.aievent.core.issuetracking.change.*;
@Repository @Profile("!prod") @ConditionalOnProperty(prefix="issue-external-change",name="store",havingValue="MEMORY")
public class InMemoryExternalChangeGovernanceRepository implements ExternalChangeGovernanceRepository {
 private final Map<String,ExternalChangePolicy> policies=new ConcurrentHashMap<>(); private final Map<String,ExternalCommentSync> comments=new ConcurrentHashMap<>(); private final Map<String,ExternalRelationSync> relations=new ConcurrentHashMap<>(); private final Map<String,ProviderActionCandidate> candidates=new ConcurrentHashMap<>(); private final Map<String,ProviderActionCandidateEvent> events=new ConcurrentHashMap<>(); private String k(String t,String id){return t+":"+id;}
 public ExternalChangePolicy savePolicy(ExternalChangePolicy v){policies.put(k(v.tenantId(),v.policyId()),v);return v;} public synchronized boolean savePolicyExpectedVersion(ExternalChangePolicy v,long expected){ExternalChangePolicy current=policies.get(k(v.tenantId(),v.policyId()));if(current==null||current.version()!=expected)return false;policies.put(k(v.tenantId(),v.policyId()),v);return true;} public Optional<ExternalChangePolicy> findPolicy(String t,String id){return Optional.ofNullable(policies.get(k(t,id)));} public List<ExternalChangePolicy> listPolicies(String t,ExternalChangePolicyStatus s,int n){return policies.values().stream().filter(v->t.equals(v.tenantId())&&(s==null||s==v.status())).sorted(Comparator.comparingInt(ExternalChangePolicy::priority).reversed()).limit(n).toList();}
 public ExternalCommentSync saveCommentSync(ExternalCommentSync v){comments.put(k(v.tenantId(),v.syncId()),v);return v;} public Optional<ExternalCommentSync> findCommentByMarker(String t,String c,String m){return comments.values().stream().filter(v->t.equals(v.tenantId())&&c.equals(v.connectionId())&&m.equals(v.sourceMarker())).findFirst();} public Optional<ExternalCommentSync> findCommentByIdempotency(String t,String id,ExternalSyncDirection d){return comments.values().stream().filter(v->t.equals(v.tenantId())&&id.equals(v.sourceCommentId())&&d==v.direction()).findFirst();} public List<ExternalCommentSync> listCommentSync(String t,ExternalSyncStatus s,int n){return comments.values().stream().filter(v->t.equals(v.tenantId())&&(s==null||s==v.status())).sorted(Comparator.comparing(ExternalCommentSync::updatedAt).reversed()).limit(n).toList();}
 public ExternalRelationSync saveRelationSync(ExternalRelationSync v){relations.put(k(v.tenantId(),v.syncId()),v);return v;} public Optional<ExternalRelationSync> findRelationByMarker(String t,String c,String m){return relations.values().stream().filter(v->t.equals(v.tenantId())&&c.equals(v.connectionId())&&m.equals(v.sourceMarker())).findFirst();} public Optional<ExternalRelationSync> findRelationByIdempotency(String t,String a,String b,String r,ExternalSyncDirection d){return relations.values().stream().filter(v->t.equals(v.tenantId())&&a.equals(v.sourceExternalIssueId())&&b.equals(v.targetExternalIssueId())&&r.equals(v.relationType())&&d==v.direction()).findFirst();} public List<ExternalRelationSync> listRelationSync(String t,ExternalSyncStatus s,int n){return relations.values().stream().filter(v->t.equals(v.tenantId())&&(s==null||s==v.status())).sorted(Comparator.comparing(ExternalRelationSync::updatedAt).reversed()).limit(n).toList();}
 public ProviderActionCandidate saveCandidate(ProviderActionCandidate v){candidates.put(k(v.tenantId(),v.candidateId()),v);return v;} public synchronized boolean saveCandidateExpectedVersion(ProviderActionCandidate v,long e){ProviderActionCandidate c=candidates.get(k(v.tenantId(),v.candidateId()));if(c==null||c.version()!=e)return false;candidates.put(k(v.tenantId(),v.candidateId()),v);return true;} public Optional<ProviderActionCandidate> findCandidate(String t,String id){return Optional.ofNullable(candidates.get(k(t,id)));} public Optional<ProviderActionCandidate> findCandidateByIdempotency(String t,String id){return candidates.values().stream().filter(v->t.equals(v.tenantId())&&id.equals(v.idempotencyKey())).findFirst();} public List<ProviderActionCandidate> listCandidates(String t,ProviderActionCandidateStatus s,int n){return candidates.values().stream().filter(v->t.equals(v.tenantId())&&(s==null||s==v.status())).sorted(Comparator.comparing(ProviderActionCandidate::updatedAt).reversed()).limit(n).toList();}
 public ProviderActionCandidateEvent appendCandidateEvent(ProviderActionCandidateEvent v){events.put(k(v.tenantId(),v.eventId()),v);return v;} public Optional<ProviderActionCandidateEvent> latestCandidateEvent(String t,String id){return events.values().stream().filter(v->t.equals(v.tenantId())&&id.equals(v.candidateId())).max(Comparator.comparing(ProviderActionCandidateEvent::occurredAt));} public List<ProviderActionCandidateEvent> listCandidateEvents(String t,String id,int n){return events.values().stream().filter(v->t.equals(v.tenantId())&&id.equals(v.candidateId())).sorted(Comparator.comparing(ProviderActionCandidateEvent::occurredAt).reversed()).limit(n).toList();} public String mode(){return "MEMORY";}
}
