'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ExportOperationsPanel } from '@/components/phase7f/ExportOperationsPanel';
import { ExportJobExperiencePanel } from '@/components/phase7f/ExportJobExperiencePanel';
import { AttachmentSecurityPanel } from '@/components/phase7f/AttachmentSecurityPanel';
import { BackgroundJobAuthorizationPanel } from '@/components/phase7f/BackgroundJobAuthorizationPanel';
import { BulkImportExperiencePanel } from '@/components/phase7f/BulkImportExperiencePanel';
import { AuditSupportDiagnosticPanel } from '@/components/phase7f/AuditSupportDiagnosticPanel';
const sections=[['overview','Overview'],['exports','Exports'],['attachments','Attachments'],['jobs','Background Jobs'],['bulk','Bulk & Import'],['audit','Audit & Support']] as const;
type Section=(typeof sections)[number][0];
export function OperationsWorkspace(){const [active,setActive]=useState<Section>('overview');return <div className="space-y-5"><section className="rounded-2xl border border-indigo-200 bg-indigo-50 p-5"><div className="text-xs font-black uppercase tracking-[.2em] text-indigo-700">Phase 7F Operations</div><h2 className="mt-2 text-xl font-black text-indigo-950">Governed operational artifacts</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-indigo-900">Exports, attachments, background jobs, bulk operations, imports, audit and diagnostics remain subordinate to resource authorization, field policy, malware gates, runtime leases and immutable evidence.</p></section><div className="grid gap-5 xl:grid-cols-[minmax(15rem,.25fr)_minmax(0,.75fr)]"><nav aria-label="Operations workspace sections" className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><ul className="space-y-1">{sections.map(([id,label])=><li key={id}><button type="button" onClick={()=>setActive(id)} aria-current={active===id?'page':undefined} className={`w-full rounded-xl px-3 py-3 text-left text-sm font-black ${active===id?'bg-slate-950 text-white':'text-slate-700 hover:bg-slate-100'}`}>{label}</button></li>)}</ul><Link href="/operations/integration-sync" className="mt-4 block rounded-xl border border-slate-200 px-3 py-3 text-sm font-black text-slate-700 hover:bg-slate-50">Open Sync Operations</Link></nav><section className="min-w-0 space-y-5">{active==='overview'?<><ExportJobExperiencePanel/><BackgroundJobAuthorizationPanel/></>:null}{active==='exports'?<><ExportOperationsPanel/><ExportJobExperiencePanel/></>:null}{active==='attachments'?<AttachmentSecurityPanel/>:null}{active==='jobs'?<BackgroundJobAuthorizationPanel/>:null}{active==='bulk'?<BulkImportExperiencePanel/>:null}{active==='audit'?<AuditSupportDiagnosticPanel/>:null}</section></div></div>}
